README.md
- Add maintenance and support for Java versions section in README
- Minor edit on other sections
=> Add maintenance and support for Java versions section in README

http-clients/url-connection-client/src/it/java/software/amazon/awssdk/http/urlconnection/HeadObjectIntegrationTest.java
Handle comment mentioned in https://github.com/aws/aws-sdk-java-v2/pull/3346#discussion_r941812708
- There is no need to add a specific check like `responseHasNoContent()` for errorStream as done for inputStream in https://github.com/aws/aws-sdk-java-v2/pull/3346 for following reasons
- Unlike inputStream where the InputStream is explicitly set to [emptyStream](https://github.com/JetBrains/jdk8u_jdk/blob/94318f9185757cc33d2b8d527d36be26ac6b7582/src/share/classes/sun/net/www/protocol/http/HttpURLConnection.java#L1858)  for `method.equals("HEAD")`  the HttpURLConnection does not do such thing for  error Responses , it straight away passed this to delegates as 
https://github.com/JetBrains/jdk8u_jdk/blob/master/src/share/classes/sun/net/www/protocol/http/HttpURLConnection.java#L1961-L1970
- …
=> Added Junit for request with HeadObject and gzipped enabled

.changes/next-release/bugfix-AWSSDKforJavav2-a18a347.json, core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/handler/BaseSyncClientHandler.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/sync/ResponseTransformer.java, http-client-spi/src/main/java/software/amazon/awssdk/http/AbortableInputStream.java, http-clients/url-connection-client/src/it/java/software/amazon/awssdk/http/urlconnection/EmptyFileS3IntegrationTest.java, http-clients/url-connection-client/src/it/java/software/amazon/awssdk/http/urlconnection/UrlHttpConnectionS3IntegrationTestBase.java
Before this change, we passed null to response transformers when the HTTP client returned empty. Our built-in response transformers expected non-null, so this would fail. This change passes an empty body to response transformers, instead.
Fixes #3359
=> Fixed an issue in sync clients where empty response payloads could cause a null pointer exception.

http-clients/url-connection-client/src/it/java/software/amazon/awssdk/http/urlconnection/EmptyFileS3IntegrationTest.java, http-clients/url-connection-client/src/it/java/software/amazon/awssdk/http/urlconnection/HeadObjectIntegrationTest.java, http-clients/url-connection-client/src/it/java/software/amazon/awssdk/http/urlconnection/S3WithUrlHttpClientIntegrationTest.java, http-clients/url-connection-client/src/it/java/software/amazon/awssdk/http/urlconnection/UrlHttpConnectionS3IntegrationTestBase.java
- UrlHttp Client's Integ test cases were failing because base class was of Junit 4 and main class had junit 5 annotations
=> Upgrading all the Integ test case of UrlHttpClient to junit 5

services-custom/s3-transfer-manager/src/it/java/software/amazon/awssdk/transfer/s3/S3TransferManagerUploadIntegrationTest.java, services/s3/src/it/java/software/amazon/awssdk/services/s3/PutObjectIntegrationTest.java, services/s3/src/it/java/software/amazon/awssdk/services/s3/S3IntegrationTestBase.java, services/s3/src/it/java/software/amazon/awssdk/services/s3/crt/ChecksumIntegrationTest.java, services/s3/src/main/java/software/amazon/awssdk/services/s3/S3CrtAsyncClientBuilder.java, services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/crt/DefaultS3CrtAsyncClient.java, services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/crt/S3CrtAsyncHttpClient.java, services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/crt/S3InternalSdkHttpExecutionAttribute.java, test/s3-benchmarks/src/main/java/software/amazon/awssdk/s3benchmarks/BaseTransferManagerBenchmark.java, test/s3-benchmarks/src/main/java/software/amazon/awssdk/s3benchmarks/BenchmarkRunner.java, test/s3-benchmarks/src/main/java/software/amazon/awssdk/s3benchmarks/TransferManagerBenchmarkConfig.java, test/s3-benchmarks/src/main/java/software/amazon/awssdk/s3benchmarks/TransferManagerUploadBenchmark.java
Add flexible checksum support and update perf tests
Added tests
=> Add flexible checksum support and update perf tests

services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/crt/S3CrtAsyncHttpClient.java, services/s3/src/test/java/software/amazon/awssdk/services/s3/internal/crt/S3CrtAsyncHttpClientTest.java
This is the first part of fixing endpoint overrides in transfer manager. The next part will be in the CRT.
=> Pass endpoint override to S3 CRT Async HTTP client. 

http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/internal/utils/NettyUtils.java
Replacing "pool lease timeout" with "connection acquisition timeout"
"Pool lease timeout" is ambiguous in error message for too many acquire operations in Runnable Request class
Updating error message to clearly state "connection acquisition timeout"
=> Clarify error message in Runnable Request

.changes/next-release/bugfix-AWSSDKforJavav2-0f4a264.json, core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/interceptor/HttpChecksumInHeaderInterceptor.java, test/codegen-generated-classes-test/src/test/java/software/amazon/awssdk/services/HttpChecksumInHeaderTest.java
```
java.lang.NullPointerException
at software.amazon.awssdk.auth.signer.internal.AbstractAws4Signer$CanonicalRequest.addAndTrim(AbstractAws4Signer.java:561)
at software.amazon.awssdk.auth.signer.internal.AbstractAws4Signer$CanonicalRequest.lambda$addCanonicalizedHeaderString$0(AbstractAws4Signer.java:518)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at software.amazon.awssdk.auth.signer.internal.AbstractAws4Signer$CanonicalRequest.addCanonicalizedHeaderString(AbstractAws4Signer.java:514)
at software.amazon.awssdk.auth.signer.internal.AbstractAws4Signer$CanonicalRequest.string(AbstractAws4Signer.java:481)
at software.amazon.awssdk.auth.signer.internal.AbstractAws4Signer.doSign(AbstractAws4Signer.java:104)
at software.amazon.awssdk.auth.signer.internal.AbstractAws4Signer.doSign(Abstr …
```
=> Fix for NPE when Http Checksum algorithm  is set for Empty payload

services-custom/s3-transfer-manager/pom.xml, services-custom/s3-transfer-manager/src/it/java/software/amazon/awssdk/transfer/s3/S3TransferManagerUploadPauseResumeIntegrationTest.java, services-custom/s3-transfer-manager/src/main/java/software/amazon/awssdk/transfer/s3/internal/DefaultS3TransferManager.java, services-custom/s3-transfer-manager/src/main/java/software/amazon/awssdk/transfer/s3/internal/model/DefaultFileDownload.java, services-custom/s3-transfer-manager/src/main/java/software/amazon/awssdk/transfer/s3/internal/model/DefaultFileUpload.java, services-custom/s3-transfer-manager/src/main/java/software/amazon/awssdk/transfer/s3/internal/serialization/CrtUploadResumeToken.java, services-custom/s3-transfer-manager/src/main/java/software/amazon/awssdk/transfer/s3/internal/serialization/ResumableFileDownloadSerializer.java, services-custom/s3-transfer-manager/src/main/java/software/amazon/awssdk/transfer/s3/internal/utils/FileUtils.java, services-custom/s3-transfer-manager/src/main/java/software/amazon/awssdk/transfer/s3/internal/utils/ResumableRequestConverter.java, services-custom/s3-transfer-manager/src/main/java/software/amazon/awssdk/transfer/s3/model/FileUpload.java, services-custom/s3-transfer-manager/src/main/java/software/amazon/awssdk/transfer/s3/model/ResumableFileDownload.java, services-custom/s3-transfer-manager/src/main/java/software/amazon/awssdk/transfer/s3/model/ResumableFileUpload.java, services-custom/s3-transfer-manager/src/test/java/software/amazon/awssdk/transfer/s3/internal/DefaultFileUploadTest.java, services-custom/s3-transfer-manager/src/test/java/software/amazon/awssdk/transfer/s3/internal/S3TransferManagerUploadPauseAndResumeTest.java, services-custom/s3-transfer-manager/src/test/java/software/amazon/awssdk/transfer/s3/internal/UploadDirectoryHelperParameterizedTest.java, services-custom/s3-transfer-manager/src/test/java/software/amazon/awssdk/transfer/s3/internal/UploadDirectoryHelperTest.java, services-custom/s3-transfer-manager/src/test/java/software/amazon/awssdk/transfer/s3/internal/serialization/CrtUploadResumeTokenTest.java, services-custom/s3-transfer-manager/src/test/java/software/amazon/awssdk/transfer/s3/model/ResumableFileUploadTest.java, services-custom/s3-transfer-manager/src/test/resources/log4j2.properties, services/s3/src/it/java/software/amazon/awssdk/services/s3/S3IntegrationTestBase.java, services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/crt/DefaultS3CrtAsyncClient.java, services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/crt/S3CrtAsyncHttpClient.java, services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/crt/S3InternalSdkHttpExecutionAttribute.java, services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/crt/S3MetaRequestPauseObservable.java
This is part 2 of pause/resume for uploadFile.
=> [TM upload pause/resume Part 2] Implement pause and resume for uploadFile

buildspecs/release-javadoc.yml
Use JDK 18 to build Javadocs so that we can use snippet 
Tested on CodeBuild job
=> Use JDK 18 to build Javadocs so that we can use snippet

pom.xml
Disable [index](https://openjdk.org/jeps/225#:~:text=The%20%2Dnoindex%20option%20to%20javadoc,files%20in%20the%20output%20directory.) to disable search 
functionality on the javadoc site because Javadoc is using an older version of jquery-ui. We can re-enable it once it's fixed in JDK
Tested on CodeBuild
=> Disable index 

.changes/next-release/bugfix-AWSSDKforJavav2-ee04822.json, core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/http/pipeline/stages/AsyncRetryableStage.java, core/sdk-core/src/test/java/software/amazon/awssdk/core/internal/http/pipeline/stages/AsyncRetryableStageAdaptiveModeTest.java
Errors should not be wrapped by SdkClientException
Primary fix to https://github.com/aws/aws-sdk-java-v2/issues/3381, for http
Do instance check of Throwable returned by CompletableFuture and handle accordingly
Test added
=> Errors should not be wrapped - Http

build-tools/src/main/resources/software/amazon/awssdk/spotbugs-suppressions.xml, services-custom/s3-transfer-manager/src/main/java/software/amazon/awssdk/transfer/s3/internal/serialization/ResumableFileDownloadSerializer.java, services-custom/s3-transfer-manager/src/main/java/software/amazon/awssdk/transfer/s3/internal/serialization/ResumableFileUploadSerializer.java, services-custom/s3-transfer-manager/src/main/java/software/amazon/awssdk/transfer/s3/internal/serialization/TransferManagerJsonUnmarshaller.java, services-custom/s3-transfer-manager/src/main/java/software/amazon/awssdk/transfer/s3/internal/serialization/TransferManagerMarshallingUtils.java, services-custom/s3-transfer-manager/src/main/java/software/amazon/awssdk/transfer/s3/model/ResumableFileUpload.java, services-custom/s3-transfer-manager/src/test/java/software/amazon/awssdk/transfer/s3/internal/serialization/ResumableFileUploadSerializerTest.java, services-custom/s3-transfer-manager/src/test/java/software/amazon/awssdk/transfer/s3/internal/serialization/TransferManagerMarshallerUtilsTest.java, services-custom/s3-transfer-manager/src/test/java/software/amazon/awssdk/transfer/s3/model/ResumableFileUploadTest.java
Add serialization and deserialization support for `ResumableFileUpload`
=> Add serialization and deserialization support for ResumableFileUpload

.changes/next-release/bugfix-S3TransferManager-f1c2208.json, services-custom/s3-transfer-manager/src/main/java/software/amazon/awssdk/transfer/s3/internal/DefaultS3TransferManager.java, services-custom/s3-transfer-manager/src/test/java/software/amazon/awssdk/transfer/s3/internal/S3TransferManagerPauseAndResumeTest.java
Errors should not be wrapped by SdkClientException
Partial fix to https://github.com/aws/aws-sdk-java-v2/issues/3381, for s3 Transfer Manager
Update handleException() to perform instance check of throwable, and handle accordingly
Test added
=> Errors should not be wrapped - S3 Transfer Manager

core/auth/src/main/java/software/amazon/awssdk/auth/credentials/WebIdentityTokenFileCredentialsProvider.java
WebIdentityTokenFileCredentialsProvider currently does not implement AutoCloseable, which means that the StsWebIdentityCredentialsProvider that it creates does not close its STS client, causing memory leaks.
Fixes https://github.com/aws/aws-sdk-java-v2/issues/3270
Implemented SdkAutoCloseable interface and added close method
=> Make WebIdentityTokenFileCredentialsProvider implement AutoCloseable

.changes/next-release/feature-AWSSDKforJavav2-1a1ccf3.json, http-clients/apache-client/src/main/java/software/amazon/awssdk/http/apache/ApacheHttpClient.java, http-clients/apache-client/src/test/java/software/amazon/awssdk/http/apache/ApacheClientTlsAuthTest.java
Provide SDK users more control of the TLS negotiation by setting a socket factory.
Fixes [#2966](https://github.com/aws/aws-sdk-java-v2/issues/2966)
Add method to the HTTP client builder for setting a socket factory.
Added two tests to Apache HTTP TLS Auth suite.
=> Provide the ability to set a custom socket factory when building an HTTP client

codegen/src/main/java/software/amazon/awssdk/codegen/poet/rules/EndpointProviderSpec.java, codegen/src/main/java/software/amazon/awssdk/codegen/poet/rules/EndpointResolverInterceptorSpec.java, codegen/src/main/java/software/amazon/awssdk/codegen/poet/rules/RequestEndpointInterceptorSpec.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/rules/endpoint-provider-class.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/rules/endpoint-resolve-interceptor.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/rules/request-set-endpoint-interceptor.java, core/aws-core/src/main/java/software/amazon/awssdk/awscore/client/builder/AwsDefaultClientBuilder.java, core/aws-core/src/main/java/software/amazon/awssdk/awscore/rules/AwsEndpointProviderUtils.java, core/aws-core/src/main/java/software/amazon/awssdk/awscore/rules/AwsProviderUtils.java, services/s3/src/main/resources/software/amazon/awssdk/services/s3/execution.interceptors, services/s3/src/test/java/software/amazon/awssdk/services/s3/EndpointOverrideEndpointResolutionTest.java, test/codegen-generated-classes-test/src/test/java/software/amazon/awssdk/services/endpointproviders/AwsEndpointProviderUtilsTest.java, test/codegen-generated-classes-test/src/test/java/software/amazon/awssdk/services/endpointproviders/AwsProviderUtilsTest.java
- Don't include query params when resolving the SDK::Endpoint BuiltIn
- Correctly remove the endpoint override path from the request path before recombining the endpoints after endpoint resolution. Otherwise, the override's path will be repeated in the final endpoint.
- Fix some test expactations based around endpoint overrides in S3. Previously we did not do virtual addressing for normal bucket unless the endpoint startswith 's3'. This is no longer the case as the rules will use virtual addressing unless path style is enabled.
- Add additional tests for AwsProviderUtils
- Uncomment commented out endpoint param resolution in client builder. This was previously commented out for to make client endpoint tests pass but they will just be ignored in the generated tests instead.
=> Fixes to endpoint resolution

test/sdk-benchmarks/pom.xml
Fix `java.lang.NoClassDefFoundError: org/eclipse/jetty/util/component/AttributeContainerMap` caused by mixed version of jetty
Tested locally
=> Fix sdk-benchmarks version

.changes/next-release/bugfix-AWSSDKforJavav2-83d35fd.json, core/aws-core/src/test/java/software/amazon/awssdk/awscore/exception/AwsServiceExceptionTest.java, core/aws-core/src/test/java/software/amazon/awssdk/awscore/retry/AwsRetryPolicyTest.java, core/protocols/aws-json-protocol/src/main/java/software/amazon/awssdk/protocols/json/internal/marshall/SimpleTypeJsonMarshaller.java, core/protocols/protocol-core/src/main/java/software/amazon/awssdk/protocols/core/InstantToString.java, core/protocols/protocol-core/src/main/java/software/amazon/awssdk/protocols/core/StringToInstant.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/retry/ClockSkew.java, core/sdk-core/src/test/java/software/amazon/awssdk/core/internal/retry/ClockSkewAdjusterTest.java, test/protocol-tests/src/test/java/software/amazon/awssdk/protocol/tests/clockskew/ClockSkewAdjustmentTest.java, utils/src/main/java/software/amazon/awssdk/utils/DateUtils.java, utils/src/test/java/software/amazon/awssdk/utils/DateUtilsTest.java
Add utility method so that dates are marshalled using RFC 822 format.
The formatted representation of dates with single-digit day of month also includes a single-digit. This code fix will change the representation to two-digit day of month.
Current:
```
Expires: Fri, 1 Sep 2023 01:01:01 GMT.
```
Expected:
```
Expires: Fri, 01 Sep 2023 01:01:01 GMT
```
Modified DateUtils.java to add parse and format methods specific to RFC 822. Cascaded these changes to other modules.
=> Use RFC 822 format for marshalling date shapes

pom.xml, services-custom/s3-transfer-manager/pom.xml, services-custom/s3-transfer-manager/src/main/java/software/amazon/awssdk/transfer/s3/S3TransferManager.java, services-custom/s3-transfer-manager/src/main/java/software/amazon/awssdk/transfer/s3/config/TransferRequestOverrideConfiguration.java, services-custom/s3-transfer-manager/src/main/java/software/amazon/awssdk/transfer/s3/model/CopyRequest.java, services-custom/s3-transfer-manager/src/test/java/software/amazon/awssdk/transfer/s3/samples/S3TransferManagerSamples.java
Replace inline snippets with external snippets so that we can make sure sample code compiles
Use `@snippet` introduced in Java 18 in S3 transfer manager for code snippets 
https://docs.oracle.com/en/java/javase/18/code-snippet/index.html#external-snippets
Tested it locally and verified the generated Javadoc, will test it using CodeBuild
=> Replace inline snippets with external compilable snippets

core/auth/src/main/java/software/amazon/awssdk/auth/signer/internal/util/SignerMethodResolver.java, services/s3/src/it/java/software/amazon/awssdk/services/s3/S3IntegrationTestBase.java, services/s3/src/it/java/software/amazon/awssdk/services/s3/crt/ChecksumIntegrationTest.java, services/s3/src/main/java/software/amazon/awssdk/services/s3/S3CrtAsyncClientBuilder.java, services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/crt/CrtChecksumUtils.java, services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/crt/DefaultS3CrtAsyncClient.java, services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/crt/S3CrtAsyncHttpClient.java, services/s3/src/test/java/software/amazon/awssdk/services/s3/internal/crt/CrtChecksumUtilsTest.java, services/s3/src/test/java/software/amazon/awssdk/services/s3/internal/crt/S3CrtAsyncHttpClientTest.java
CRT does not support flexible checksum for non-streaming operation. After this change, we only pass checksum algorithm and isValidateChecksum for `getObject` and `putObject`
Only enable CRT checksum for getObject and putObject
Integ tests passed
=> Only enable CRT checksum for getObject and putObject

services-custom/s3-transfer-manager/src/it/java/software/amazon/awssdk/transfer/s3/S3IntegrationTestBase.java, services-custom/s3-transfer-manager/src/it/java/software/amazon/awssdk/transfer/s3/S3TransferManagerCopyIntegrationTest.java, services-custom/s3-transfer-manager/src/it/java/software/amazon/awssdk/transfer/s3/S3TransferManagerDownloadDirectoryIntegrationTest.java, services-custom/s3-transfer-manager/src/it/java/software/amazon/awssdk/transfer/s3/S3TransferManagerDownloadIntegrationTest.java, services-custom/s3-transfer-manager/src/it/java/software/amazon/awssdk/transfer/s3/S3TransferManagerDownloadPauseResumeIntegrationTest.java, services-custom/s3-transfer-manager/src/it/java/software/amazon/awssdk/transfer/s3/S3TransferManagerUploadDirectoryIntegrationTest.java, services-custom/s3-transfer-manager/src/it/java/software/amazon/awssdk/transfer/s3/S3TransferManagerUploadIntegrationTest.java, services-custom/s3-transfer-manager/src/it/java/software/amazon/awssdk/transfer/s3/S3TransferManagerUploadPauseResumeIntegrationTest.java
Fix TM integ tests set up and tear down steps to ensure resources are created and closed properly.
- Rename set up and tear down method names in `S3IntegrationTestBase` class so that they don't get hidden from child classes.
- Remove invocations of set up and tear down super methods from `S3IntegrationTestBase` in child classes because they are not needed
Integ tests passed locally
=> Fix TM integ tests set up and tear down steps

pom.xml
Set release target version to JDK8 to avoid getting `NoSuchMethodException for ByteBuffer.position.` error when we run tests using JDK 8 after we build the SDK using JDK11+ 
Add maven.compiler.release property for JDK11+ build
Tested locally
=> Add maven.compiler.release property for JDK11+ build

.changes/next-release/bugfix-AWSSDKforJavav2-3c99b83.json, core/aws-core/src/main/java/software/amazon/awssdk/awscore/internal/AwsExecutionContextBuilder.java, core/aws-core/src/test/java/software/amazon/awssdk/awscore/internal/AwsExecutionContextBuilderTest.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/util/HttpChecksumResolver.java
In order to avoid constantly resolving the `ChecksumSpecs` object for a given request, `HttpChecksumResolver#getResolvedChecksumSpecs` will first attempt to retrieve said object from the `ExecutionAttributes`. Only when it is missing, will it be resolved.
Optimize `HttpChecksumUtils` calls delegated to `HttpChecksumResolver` in order to avoid recomputing the same object.
Method `HttpChecksumResolver#getResolvedChecksumSpecs` has been renamed `resolveChecksumSpecs`. A replacement `getResolvedChecksumSpecs` now attempts to retrieved the cached `ChecksumSpecs` object.
=> Return previously resolved ChecksumSpecs with HttpChecksumResolver#getResolvedChecksumSpecs

utils/pom.xml, utils/src/main/java/software/amazon/awssdk/utils/cache/lru/LruCache.java, utils/src/test/java/software/amazon/awssdk/utils/cache/lru/LruCacheTest.java
An LRU (Least Recently Used) cache is needed when you need to store resources in memory in order of when they've been accessed. No existing utility exists for this functionality within our dependencies. 
The LRU cache 
- has a standard size of 100 (configurable)
- returns the value for the key that is given. 
- If the value exists, the cache will move it to the front (most-recently-used) part of the cache before returning it
- If no value exists, the cache will used the supplied function to retrieve a value and add it to the front of the cache. If the cache is full, the least recently value will be evicted. 
- Supports concurrency
- Does not (yet) support individual refresh of the cached values. This is a planned feature add-on.
Unit tested
=> Add LRU Cache to utilities

.changes/next-release/bugfix-AWSSDKforJavav2-d06ff61.json, core/auth/src/main/java/software/amazon/awssdk/auth/signer/AwsSignerExecutionAttribute.java, core/auth/src/main/java/software/amazon/awssdk/auth/signer/internal/AbstractAws4Signer.java, core/auth/src/main/java/software/amazon/awssdk/auth/signer/internal/AbstractAwsSigner.java, core/auth/src/main/java/software/amazon/awssdk/auth/signer/params/Aws4SignerParams.java, core/auth/src/test/java/software/amazon/awssdk/auth/signer/internal/Aws4SignerPathNormalizationTest.java, services/apigateway/src/it/java/software/amazon/awssdk/services/apigateway/ServiceIntegrationTest.java, services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/handlers/ConfigureSignerInterceptor.java, services/s3/src/main/resources/META-INF/native-image/software.amazon.awssdk/s3/reflect-config.json, services/s3/src/main/resources/software/amazon/awssdk/services/s3/execution.interceptors, services/s3control/src/main/java/software/amazon/awssdk/services/s3control/internal/interceptors/ConfigureSignerInterceptor.java, services/s3control/src/main/resources/META-INF/native-image/software.amazon.awssdk/s3control/reflect-config.json, services/s3control/src/main/resources/software/amazon/awssdk/services/s3control/execution.interceptors
During signing when generating the canonical request, request paths are supposed to be normalized to remove . and .. path components. We were not doing this before, making it possible to construct requests that fail signature validation.
=> Normalize URLs during signing (except for S3).

pom.xml, services-custom/s3-transfer-manager/src/it/java/software/amazon/awssdk/transfer/s3/S3TransferManagerDownloadIntegrationTest.java, services/s3/src/main/java/software/amazon/awssdk/services/s3/S3CrtAsyncClientBuilder.java, services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/crt/DefaultS3CrtAsyncClient.java, services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/crt/S3CrtAsyncHttpClient.java, services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/crt/S3CrtDataPublisher.java, services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/crt/S3CrtResponseHandlerAdapter.java, services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/crt/S3NativeClientConfiguration.java, services/s3/src/test/java/software/amazon/awssdk/services/s3/functionaltests/CompleteMultipartUploadFunctionalTest.java, services/s3/src/test/java/software/amazon/awssdk/services/s3/internal/crt/DefaultS3CrtAsyncClientTest.java, services/s3/src/test/java/software/amazon/awssdk/services/s3/internal/crt/S3CrtDataPublisherTest.java, services/s3/src/test/java/software/amazon/awssdk/services/s3/internal/crt/S3CrtResponseHandlerAdapterTest.java, test/s3-benchmarks/pom.xml, test/s3-benchmarks/src/main/java/software/amazon/awssdk/s3benchmarks/BaseTransferManagerBenchmark.java, test/s3-benchmarks/src/main/java/software/amazon/awssdk/s3benchmarks/BenchmarkRunner.java, test/s3-benchmarks/src/main/java/software/amazon/awssdk/s3benchmarks/BenchmarkUtils.java, test/s3-benchmarks/src/main/java/software/amazon/awssdk/s3benchmarks/CrtS3ClientBenchmark.java, test/s3-benchmarks/src/main/java/software/amazon/awssdk/s3benchmarks/NoOpResponseTransformer.java, test/s3-benchmarks/src/main/java/software/amazon/awssdk/s3benchmarks/TransferManagerBenchmark.java, test/s3-benchmarks/src/main/java/software/amazon/awssdk/s3benchmarks/TransferManagerBenchmarkConfig.java, test/s3-benchmarks/src/main/java/software/amazon/awssdk/s3benchmarks/TransferManagerDownloadBenchmark.java, test/s3-benchmarks/src/main/java/software/amazon/awssdk/s3benchmarks/TransferManagerUploadBenchmark.java, test/s3-benchmarks/src/main/java/software/amazon/awssdk/s3benchmarks/V1BaseTransferManagerBenchmark.java, test/s3-benchmarks/src/main/java/software/amazon/awssdk/s3benchmarks/V1TransferManagerDownloadBenchmark.java, test/s3-benchmarks/src/main/java/software/amazon/awssdk/s3benchmarks/V1TransferManagerUploadBenchmark.java, test/s3-benchmarks/src/main/resources/log4j2.properties
- Enable backpressure for read in TM to fix the issue where OOM was thrown if the consumer could not keep up with the speed of download. #3394 
- Enable backpressure for read in TM
- Expose initialReadBufferSize config. The default `initialReadBufferSize` is 10 * partSize
- Add more perf tests
Tested in an EC2 instance
=> Enable backpressure in TM

.changes/next-release/feature-AWSSDKforJavav2-05b771b.json, .changes/next-release/feature-AWSSDKforJavav2-2636db0.json, .idea/inspectionProfiles/AWS_Java_SDK_2_0.xml, codegen/src/main/java/software/amazon/awssdk/codegen/poet/model/ExceptionProperties.java, codegen/src/main/resources/software/amazon/awssdk/codegen/rules/SourceException.java.resource, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/baseserviceexception.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/emptymodeledexception.java, core/aws-core/src/main/java/software/amazon/awssdk/awscore/exception/AwsServiceException.java, core/protocols/aws-json-protocol/src/main/java/software/amazon/awssdk/protocols/json/internal/unmarshall/AwsJsonProtocolErrorUnmarshaller.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/endpointdiscovery/EndpointDiscoveryFailedException.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/exception/AbortedException.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/exception/ApiCallAttemptTimeoutException.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/exception/ApiCallTimeoutException.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/exception/Crc32MismatchException.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/exception/NonRetryableException.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/exception/RetryableException.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/exception/SdkClientException.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/exception/SdkException.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/exception/SdkServiceException.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/http/pipeline/stages/AsyncRetryableStage.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/http/pipeline/stages/utils/RetryableStageHelper.java, services/sso/src/main/java/software/amazon/awssdk/services/sso/auth/ExpiredTokenException.java, test/codegen-generated-classes-test/src/test/java/software/amazon/awssdk/services/retry/AsyncRetryFailureTest.java, test/codegen-generated-classes-test/src/test/java/software/amazon/awssdk/services/retry/RetryFailureTestSuite.java, test/codegen-generated-classes-test/src/test/java/software/amazon/awssdk/services/retry/SyncRetryFailureTest.java
Additionally, always include a useful exception message even when the service returns no error message.
Stack trace example before this change:
```
software.amazon.awssdk.services.protocolrestjson.model.ProtocolRestJsonException: null (Service: ProtocolRestJson, Status Code: 400, Request ID: null)
at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handleErrorResponse(CombinedResponseHandler.java:125)
...
at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
```
Stack trace example after this change:
```
software.amazon.awssdk.services.protocolrestjson.model.ProtocolRestJsonException: Service returned HTTP status code 400 (Service: ProtocolRestJson, Status Code: 400, Request ID: null)
at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handleErr …
```
=> Include retried failure messages as "suppressed" exceptions.

.changes/next-release/feature-AWSSDKforJavav2-a887c1c.json, core/sdk-core/src/main/java/software/amazon/awssdk/core/ResponseInputStream.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/async/AsyncResponseTransformer.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/async/InputStreamResponseTransformer.java, core/sdk-core/src/test/java/software/amazon/awssdk/core/internal/async/InputStreamResponseTransformerTest.java, test/codegen-generated-classes-test/src/test/java/software/amazon/awssdk/services/BlockingAsyncRequestResponseBodyTest.java, utils/src/main/java/software/amazon/awssdk/utils/async/ByteBufferStoringSubscriber.java, utils/src/main/java/software/amazon/awssdk/utils/async/InputStreamSubscriber.java, utils/src/test/java/software/amazon/awssdk/utils/async/ByteBufferStoringSubscriberTest.java, utils/src/test/java/software/amazon/awssdk/utils/async/InputStreamSubscriberTckTest.java, utils/src/test/java/software/amazon/awssdk/utils/async/InputStreamSubscriberTest.java
This allows streaming operation responses to be read as if they're an InputStream.
Example usage:
```java
CompletableFuture<ResponseInputStream<GetObjectResponse>> responseFuture =
s3AsyncClient.getObject(getObjectRequest, AsyncResponseTransformer.toBlockingInputStream());
try (ResponseInputStream<GetObjectResponse> responseStream = responseFuture.join()) {
responseStream.transferTo(System.out); // BLOCKS the calling thread
}
```
Other changes made to support this change:
1. Created `InputStreamSubscriber`, a `Subscriber<ByteBuffer>` that extends `InputStream`. It allows subscribing to a publisher and then performing blocking reads against it. This is used by `AsyncResponseTransformer`.
1. Updated `ByteBufferStoringSubscriber` to support `blockingTransferTo(ByteBuffer)`. It's like …
=> Added AsyncResponseTransformer.toBlockingInputStream. 

pom.xml, services-custom/s3-transfer-manager/src/main/java/software/amazon/awssdk/transfer/s3/progress/TransferListener.java, services-custom/s3-transfer-manager/src/test/java/software/amazon/awssdk/transfer/s3/samples/S3TransferManagerSamples.java
Update sample code and fix snippet path
=> Update sample code and fix snippet path

.changes/next-release/feature-AWSSDKforJavav2-2c6b2b3.json, core/sdk-core/src/main/java/software/amazon/awssdk/core/async/AsyncRequestBody.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/async/BlockingOutputStreamAsyncRequestBody.java, core/sdk-core/src/test/java/software/amazon/awssdk/core/async/BlockingOutputStreamAsyncRequestBodyTest.java, services/s3/src/it/java/software/amazon/awssdk/services/s3/AsyncInOutStreamIntegrationTest.java, test/codegen-generated-classes-test/src/test/java/software/amazon/awssdk/services/BlockingAsyncRequestResponseBodyTest.java, utils/src/main/java/software/amazon/awssdk/utils/CancellableOutputStream.java, utils/src/main/java/software/amazon/awssdk/utils/CompletableFutureUtils.java, utils/src/main/java/software/amazon/awssdk/utils/async/OutputStreamPublisher.java, utils/src/main/java/software/amazon/awssdk/utils/async/SimplePublisher.java, utils/src/test/java/software/amazon/awssdk/utils/async/OutputStreamPublisherTckTest.java, utils/src/test/java/software/amazon/awssdk/utils/async/OutputStreamPublisherTest.java, utils/src/test/java/software/amazon/awssdk/utils/async/SimplePublisherTest.java
This allows streaming operation requests to be written to like an output stream.
Example usage:
```java
BlockingOutputStreamAsyncRequestBody body = AsyncRequestBody.forBlockingOutputStream(5L);
CompletableFuture<?> responseFuture =
client.streamingInputOperation(StreamingInputOperationRequest.builder().build(), body);
try (OutputStream stream = body.outputStream()) { // TODO: Test writing too much data and too little data
stream.write("Hello".getBytes(StandardCharsets.UTF_8));
}
responseFuture.join();
```
Other changes made to support this change:
1. Added `OutputStreamPublisher` to utils. This is a `Publisher<ByteBuffer>` that can be written to like it's an output stream. Writes will block when there is no available downstream demand.
1. Added `CancellableOutputStream` to utils. This is …
=> Added AsyncRequestBody.forBlockingOutputStream

codegen/src/main/java/software/amazon/awssdk/codegen/model/config/customization/AdditionalBuilderMethod.java, codegen/src/main/java/software/amazon/awssdk/codegen/poet/client/AsyncClientInterface.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/c2j/rest-json/customization.config, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/test-json-async-client-interface.java, services-custom/s3-transfer-manager/src/it/java/software/amazon/awssdk/transfer/s3/S3TransferManagerDownloadDirectoryIntegrationTest.java, services-custom/s3-transfer-manager/src/it/java/software/amazon/awssdk/transfer/s3/S3TransferManagerUploadDirectoryIntegrationTest.java, services-custom/s3-transfer-manager/src/main/java/software/amazon/awssdk/transfer/s3/internal/UploadDirectoryHelper.java, services-custom/s3-transfer-manager/src/main/java/software/amazon/awssdk/transfer/s3/model/UploadDirectoryRequest.java, services-custom/s3-transfer-manager/src/test/java/software/amazon/awssdk/transfer/s3/internal/S3TransferManagerTest.java, services-custom/s3-transfer-manager/src/test/java/software/amazon/awssdk/transfer/s3/internal/TransferManagerConfigurationTest.java, services-custom/s3-transfer-manager/src/test/java/software/amazon/awssdk/transfer/s3/internal/UploadDirectoryHelperTest.java, services-custom/s3-transfer-manager/src/test/java/software/amazon/awssdk/transfer/s3/model/UploadDirectoryRequestTest.java, services-custom/s3-transfer-manager/src/test/java/software/amazon/awssdk/transfer/s3/samples/S3TransferManagerSamples.java, services/s3/src/main/resources/codegen-resources/customization.config, test/s3-benchmarks/src/main/java/software/amazon/awssdk/s3benchmarks/TransferManagerUploadDirectoryBenchmark.java
- Rename `sourceDirectory` to `source` to be consistent with downloadDirectory
- Add `crtCreate` in `S3AsyncClient`
=> Rename sourceDirectory to source and add S3AsycncClient#crtCreate

.changes/next-release/feature-AWSSDKforJavav2-8c45016.json, core/auth/src/main/java/software/amazon/awssdk/auth/credentials/ProfileCredentialsProvider.java, core/auth/src/test/java/software/amazon/awssdk/auth/credentials/ProfileCredentialsProviderTest.java, core/profiles/src/main/java/software/amazon/awssdk/profiles/ProfileFileSupplier.java, core/profiles/src/main/java/software/amazon/awssdk/profiles/ProfileFileSupplierBuilder.java, core/profiles/src/test/java/software/amazon/awssdk/profiles/ProfileFileSupplierTest.java
Update the `ProfileFileSupplier` API to include methods for aggregating multiple `ProfileFile` objects into a single `ProfileFileSupplier`. This will mimic how multiple `ProfileFile` can be aggregated into another `ProfileFile` object.
This change is in preparation for adding reloading functionality to `DefaultCredentialsProvider`.
Revised 2 methods and added 4 methods to `ProfileFileSupplier`.
=> ProfileFileSupplier API changes, aggregating

core/auth/src/main/java/software/amazon/awssdk/auth/credentials/DefaultCredentialsProvider.java, core/auth/src/main/java/software/amazon/awssdk/auth/credentials/InstanceProfileCredentialsProvider.java, core/auth/src/test/java/software/amazon/awssdk/auth/credentials/DefaultCredentialsProviderTest.java, core/auth/src/test/java/software/amazon/awssdk/auth/credentials/InstanceProfileCredentialsProviderTest.java
`DefaultCredentialsProvider`  creates a chain of providers. Allow the default provider to take in a `ProfileFileSupplier` to enable profile reloading functionality.
Unit tests added.
=> DefaultCredentialsProvider reload profile

.changes/next-release/feature-AWSSDKforJavav2-303765f.json, core/sdk-core/src/main/java/software/amazon/awssdk/core/async/AsyncRequestBody.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/async/BlockingInputStreamAsyncRequestBody.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/exception/NonRetryableException.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/async/InputStreamWithExecutorAsyncRequestBody.java, core/sdk-core/src/test/java/software/amazon/awssdk/core/async/BlockingInputStreamAsyncRequestBodyTest.java, core/sdk-core/src/test/java/software/amazon/awssdk/core/internal/async/InputStreamWithExecutorAsyncRequestBodyTest.java, pom.xml, test/codegen-generated-classes-test/src/test/java/software/amazon/awssdk/services/BlockingAsyncRequestResponseBodyTest.java, utils/src/main/java/software/amazon/awssdk/utils/async/InputStreamConsumingPublisher.java, utils/src/main/java/software/amazon/awssdk/utils/async/InputStreamSubscriber.java, utils/src/test/java/software/amazon/awssdk/utils/async/InputStreamConsumingPublisherTckTest.java, utils/src/test/java/software/amazon/awssdk/utils/async/InputStreamConsumingPublisherTest.java, utils/src/test/java/software/amazon/awssdk/utils/async/InputStreamSubscriberTest.java
This allows streaming operation requests to be written to like an input stream.
Example usage with retry support, without blocking calling thread:
```java
String data = "Hello, world!";
ExecutorService executor = Executors.newCachedThreadPool();
InputStream data = new StringInputStream("Hello, world!");
s3.putObject(r -> r.bucket("foo").key("bar"),
AsyncRequestBody.fromInputStream(data, data.length(), executor))
.join();
```
Example usage without retry support, with blocking calling thread:
```java
String data = "Hello, world!";
BlockingInputStreamAsyncRequestBody body = AsyncRequestBody.forBlockingInputStream(data.length());
CompletableFuture<?> responseFuture = s3.putObject(r -> r.bucket("foo").key("bar"), body);
body.writeInputStream(new StringInputStream(data));
responseFuture.join(); …
```
=> Added AsyncResponseBody.fromInputStream and AsyncRequestBody.forBlockingInputStream.

services-custom/s3-transfer-manager/src/main/java/software/amazon/awssdk/transfer/s3/internal/DefaultS3TransferManager.java
The default chunk size in `FileAsyncRequestBody` is 16KB. Increasing it to 16MB can improve performance of uploading a file of 4GB by 
Set chunk size to 16MB in TM
Ran perf tests on an EC2 instance
=> Increase chunk size for file upload

buildspecs/build.yml, buildspecs/integ-test.yml, buildspecs/stability-test.yml
- Maven options are used from codebuild environment variable
- Add retry to 
- Integ test, Stability test and jdk8 builds.
- Will add it to others if the retry mechanism works.
- Ran check builds with these options
=> Add maven option in build specs

.changes/next-release/bugfix-AmazonS3-ba24933.json, core/auth/src/main/java/software/amazon/awssdk/auth/signer/AwsSignerExecutionAttribute.java, core/auth/src/main/java/software/amazon/awssdk/auth/signer/internal/AbstractAws4Signer.java, core/auth/src/main/java/software/amazon/awssdk/auth/signer/internal/AbstractAwsS3V4Signer.java, core/auth/src/main/java/software/amazon/awssdk/auth/signer/params/Aws4PresignerParams.java, core/auth/src/main/java/software/amazon/awssdk/auth/signer/params/Aws4SignerParams.java, core/auth/src/main/java/software/amazon/awssdk/auth/signer/params/AwsS3V4SignerParams.java, core/auth/src/test/java/software/amazon/awssdk/auth/signer/AwsS3V4SignerTest.java
The issue was introduced with https://github.com/aws/aws-sdk-java-v2/pull/3534. The PR did not account for users who are using the signer directly.
=> Fixed a bug where path normalization was not being disabled when signing requests directly with AwsS3V4Signer.

scripts/doc_crosslinks/crosslink_redirect.html
When we used Java 8 to generate javadocs, it generated method IDs without method parameters: https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/services/s3/S3Client.html#createBucket--
Since moving to Java 17 for javadoc generation, it now requires the method parameter type in the ID: https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/services/s3/S3Client.html#createBucket(software.amazon.awssdk.services.s3.model.CreateBucketRequest)
This change was tested manually.
=> Fixed crosslinking of operations.

codegen/src/main/java/software/amazon/awssdk/codegen/CodeGenerator.java
This fixes a backwards-incompatibility for customers we didn't know existed: those that use CodeGenerator directly.
=> In CodeGenerator, default the resourceDirectory to the sourcesDirectory when one is not explicitly specified.

core/auth/src/main/java/software/amazon/awssdk/auth/credentials/DefaultCredentialsProvider.java, core/auth/src/main/java/software/amazon/awssdk/auth/credentials/InstanceProfileCredentialsProvider.java, core/auth/src/main/java/software/amazon/awssdk/auth/credentials/ProfileCredentialsProvider.java, core/auth/src/test/java/software/amazon/awssdk/auth/credentials/DefaultCredentialsProviderTest.java, core/auth/src/test/java/software/amazon/awssdk/auth/credentials/InstanceProfileCredentialsProviderTest.java, core/auth/src/test/java/software/amazon/awssdk/auth/credentials/ProfileCredentialsProviderTest.java
In order to keep the APIs consistent, current public methods taking `ProfileFileSupplier` as an argument will be switched over to `Supplier<ProfileFile>`. The former class is a subclass of the latter, so this is not a breaking change.
Only existing test cases.
=> Prefer Supplier<ProfileFile> over ProfileFileSupplier in APIs

.changes/next-release/removal-S3TransferManager-2c2c795.json, services-custom/s3-transfer-manager/README.md, services-custom/s3-transfer-manager/pom.xml, services-custom/s3-transfer-manager/src/main/java/software/amazon/awssdk/transfer/s3/S3TransferManager.java, services-custom/s3-transfer-manager/src/main/java/software/amazon/awssdk/transfer/s3/internal/DefaultS3TransferManager.java, services-custom/s3-transfer-manager/src/test/java/software/amazon/awssdk/transfer/s3/internal/S3TransferManagerTest.java, test/s3-benchmarks/pom.xml
Make crt dependency optional in transfer manager module so that once we have Java based TM, it'll be the default implementation. This means customers will need to explicitly add `aws-crt` dependency for now for parallel feature.
- Make crt dependency optional in transfer manager module
- Use Java based S3AsyncClient if CRT is not on the classpath in `S3TransferManager#create`
=> Make crt dependency optional in transfer manager module

services/s3/src/it/java/software/amazon/awssdk/services/s3/checksum/AsyncHttpChecksumIntegrationTest.java
…egrationTest
- Buckets were not delete at the end of AsyncHttpChecksumIntegrationTest
- Added tearDown to delete bucket at @AfterAll of AsyncHttpChecksumIntegrationTest
=> Added deleteBucketAndAllContents in  AfterAll of AsyncHttpChecksumIntegrationTest

pom.xml
2.14.0 has a bug (https://github.com/mojohaus/versions/issues/848) that broke us. We should be pinning all build tool versions, anyway.
=> Pin versions-maven-plugin version to 2.13.0.

.changes/next-release/bugfix-AmazonS3-cd8c17d.json, services/s3/src/it/java/software/amazon/awssdk/services/s3/CopyObjectIntegrationTest.java, services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/handlers/CopySourceInterceptor.java, services/s3/src/test/java/software/amazon/awssdk/services/s3/internal/handlers/CopySourceInterceptorTest.java
The main goal of this change is to fix an issue where access point ARNs were prefixed with /, causing them to fail because / is not supported as a prefix. This also stops prefixing buckets with /, but that seems to work fine in the included integration test.
=> Do not prefix copy-source with / when using the sourceBucket and sourceKey APIs

core/auth/src/main/java/software/amazon/awssdk/auth/token/credentials/ProfileTokenProvider.java, core/auth/src/main/java/software/amazon/awssdk/auth/token/internal/ProfileTokenProviderLoader.java, core/auth/src/test/java/software/amazon/awssdk/auth/token/credentials/ProfileTokenProviderTest.java, services/ssooidc/src/test/java/software/amazon/awssdk/services/ssooidc/internal/common/SsoOidcTokenRefreshTestBase.java, test/auth-tests/src/it/java/software/amazon/awssdk/auth/ssooidc/ProfileTokenProviderLoaderTest.java
Update `ProfileTokenProvider` so that the generated token uses the current contents of a `ProfileFile` if desired. This change mimics what was done with [PR 3487](https://github.com/aws/aws-sdk-java-v2/pull/3487).
Mirrored new behavior of `ProfileCredentialsProvider`.
Added single test case.
=> ProfileTokenProvider Reload ProfileFile

core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/retry/SdkDefaultRetrySetting.java
Retry on UncheckedIOException.
In some cases IOException is converted to UncheckedIOException and that suppresses retry with default retry policy. 
For example: in UrlConnectionHttpClient
```
throw new UncheckedIOException(new IOException(message, e));
```
Added UncheckedIOException to retryable exception list.
=> Retry on UncheckedIOException.

core/auth/src/main/java/software/amazon/awssdk/auth/credentials/ProfileCredentialsProvider.java
Mimic change from https://github.com/aws/aws-sdk-java-v2/pull/3608
No new tests.
=> Use synchronized block in ProfileCredentialsProvider

services/s3/src/main/java/software/amazon/awssdk/services/s3/S3Configuration.java, services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/settingproviders/DisableMultiRegionProviderChain.java, services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/settingproviders/ProfileDisableMultiRegionProvider.java, services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/settingproviders/ProfileUseArnRegionProvider.java, services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/settingproviders/UseArnRegionProviderChain.java, services/s3/src/test/java/software/amazon/awssdk/services/s3/S3ConfigurationTest.java, services/s3/src/test/java/software/amazon/awssdk/services/s3/internal/settingproviders/DisableMultiRegionProviderChainTest.java, services/s3/src/test/java/software/amazon/awssdk/services/s3/internal/settingproviders/ProfileDisableMultiRegionProviderTest.java, services/s3/src/test/java/software/amazon/awssdk/services/s3/internal/settingproviders/ProfileUseArnRegionProviderTest.java, services/s3/src/test/java/software/amazon/awssdk/services/s3/internal/settingproviders/UseArnRegionProviderChainTest.java
Continue updating the API to pass `Supplier<ProfileFile>` to classes.
Updated services/s3 classes using `ProfileFile` internally.
=> S3 support classes take Supplier<ProfileFile>

services/cloudfront/src/main/java/software/amazon/awssdk/services/cloudfront/CloudFrontUtilities.java, services/cloudfront/src/test/java/software/amazon/awssdk/services/cloudfront/CloudFrontUtilitiesTest.java
Bug fix - query params were not being included in signed URLs
https://github.com/aws/aws-sdk-java-v2/issues/3655
=> CloudFrontUtilities: Include query params in signed URL

core/sdk-core/src/main/java/software/amazon/awssdk/core/client/config/SdkClientOption.java, services/polly/src/main/java/software/amazon/awssdk/services/polly/internal/presigner/DefaultPollyPresigner.java, services/polly/src/test/java/software/amazon/awssdk/services/polly/internal/presigner/DefaultPollyPresignerTest.java, services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/endpoints/UseGlobalEndpointResolver.java, services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/signing/DefaultS3Presigner.java, services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/signing/DefaultSdkPresigner.java, services/s3/src/test/java/software/amazon/awssdk/services/s3/internal/endpoints/UseGlobalEndpointResolverProfileFileTest.java, services/s3/src/test/java/software/amazon/awssdk/services/s3/internal/endpoints/UseGlobalEndpointResolverTest.java
Continue adding functionality for using `Supplier<ProfileFile>`
Modified default presigner classes and support classes.
Partially added test cases.
=> Presigners, other Support classes take Supplier<ProfileFile>

docs/design/services/dynamodb/high-level-library/DocumentAPI.md
- Design for https://github.com/aws/aws-sdk-java-v2/issues/36
- 
- Updated the design doc
=> Design of DocumentAPI for DynamoDB

.brazil.json
Exclude javadoc JARs for third-party libraries
Verified the workflow
=> Exclude javadoc JARs for third-party libraries

.changes/next-release/bugfix-AmazonElasticContainerServiceECS-09f6115.json, core/auth/src/main/java/software/amazon/awssdk/auth/credentials/ContainerCredentialsProvider.java, core/auth/src/test/java/software/amazon/awssdk/auth/credentials/ContainerCredentialsEndpointProviderTest.java
HTTP(S) credential provider requires the implementation to verify that the resolved addresses for the host are actually loopback addresses.
InetAddress is used to resolve DNS names.
=> Validate that localhost resolves to loopback address

.changes/next-release/feature-AWSSDKforJavav2-688d30e.json
Updated changelog entry to reflect all additions made with feature branch.
=> Updated changelog entry for credentials reload feature

.changes/next-release/feature-AWSCRTHTTPClient-4b8e08d.json, http-clients/aws-crt-client/src/main/java/software/amazon/awssdk/http/crt/AwsCrtAsyncHttpClient.java
PR in support for CRT HTTP/1 GA - Surface Area Updates. This PR eliminates the default value for connection timeout.
Removed `CRT_HTTP_DEFAULTS`
No new tests added.
=> CRT HTTP/1 GA - Surface Area Updates - Timeout

http-clients/aws-crt-client/src/main/java/software/amazon/awssdk/http/crt/AwsCrtAsyncHttpClient.java, http-clients/aws-crt-client/src/main/java/software/amazon/awssdk/http/crt/internal/CrtRequestContext.java, http-clients/aws-crt-client/src/main/java/software/amazon/awssdk/http/crt/internal/request/CrtRequestBodyAdapter.java
PR in support for CRT HTTP/1 GA - Surface Area Updates. This PR modifies the `readBufferSizeInBytes` to take a `long`, not `int` parameter.
Updated method and cascaded changes into `CrtRequestContext` and `CrtRequestBodyAdapter`.
No new tests added.
=> CRT HTTP/1 GA - Surface Area Updates - readBufferSizeInBytes takes long

http-clients/aws-crt-client/src/main/java/software/amazon/awssdk/http/crt/AwsCrtAsyncHttpClient.java, pom.xml
We cut a ticket to the CRT team so that `HttpClientConnectionManagerOptions.withWindowSize` accepted a long parameter. The CRT team made the change with v0.21.5.
=> CRT window size API update

.changes/next-release/bugfix-AWSSDKforJavav2-a15138d.json, services/s3/src/main/java/software/amazon/awssdk/services/s3/checksums/ChecksumsEnabledValidator.java, services/s3/src/test/java/software/amazon/awssdk/services/s3/functionaltests/PutObjectWithChecksumTest.java
- By default for putRequest Md5 checksum validation should happen. By default as in when the new http checksum is not set to any algorithm.
- Currently it was skipping since the check was directly checking for ResolvedChecksum specs even when request algorithm were null.
- Note that this validation is done in S3 when httpChecksum algorithm is set.
- Added checks to check for requestAlgorithms.
- Added new Test cases for putObject
=> Fix for Default MD5 check getting skipped even when http checksum algorithm is not set

services-custom/dynamodb-enhanced/src/main/java/software/amazon/awssdk/enhanced/dynamodb/document/EnhancedDocument.java, services-custom/dynamodb-enhanced/src/test/java/software/amazon/awssdk/enhanced/dynamodb/document/DefaultEnhancedDocumentTest.java, services-custom/dynamodb-enhanced/src/test/java/software/amazon/awssdk/enhanced/dynamodb/document/EnhancedDocumentTest.java
- Implement Static factory methods of EnhancedDocument
- Implement from EnhancedDocument
- Added Junits
=> Implement Static factory methods of EnhancedDocument

core/imds/src/test/java/software/amazon/awssdk/imds/internal/CachedTokenClientTest.java
Trying to fix the flaky test
```
getToken_responseTtlHeadersNotANumber_shouldFailAndNotRetry
com.github.tomakehurst.wiremock.client.VerificationException: 
Expected exactly 1 requests matching the following pattern but received 2:
{
"urlPath" : "/latest/api/token",
"method" : "PUT",
"headers" : {
"x-aws-ec2-metadata-token-ttl-seconds" : {
"equalTo" : "21600"
}
}
}
at software.amazon.awssdk.imds.internal.Ec2MetadataClientTest.failureAssertions(Ec2MetadataClientTest.java:80)
```
Resetting wiremock mappings manually
=> Resetting wiremock manually

.changes/next-release/bugfix-AWSSDKforJavav2-6d1d0aa.json, core/profiles/src/main/java/software/amazon/awssdk/profiles/ProfileFileSupplier.java, core/profiles/src/test/java/software/amazon/awssdk/profiles/ProfileFileSupplierTest.java
The implementation of `aggregate` does not guarantee the profile files were submitted to `ProfileFile.Aggregator.addFile()` in the order given by the suppliers.
The current implementation uses a `Map` to keep track of whether a supplier returns a different object. Unfortunately, the `values()` method does not guarantee an ordering.
In order to preserve ordering and thread-safety, a `List` scoped to the method will be used to store the supplied profile files. If these need to be aggregated, the list will be used to feed the aggregator.
Added two unit tests.
=> ProfileFileSupplier aggregate files in order

services-custom/dynamodb-enhanced/src/main/java/software/amazon/awssdk/enhanced/dynamodb/DefaultAttributeConverterProvider.java, services-custom/dynamodb-enhanced/src/main/java/software/amazon/awssdk/enhanced/dynamodb/document/EnhancedDocument.java, services-custom/dynamodb-enhanced/src/main/java/software/amazon/awssdk/enhanced/dynamodb/internal/document/DefaultEnhancedDocument.java, services-custom/dynamodb-enhanced/src/main/java/software/amazon/awssdk/enhanced/dynamodb/mapper/DocumentTableSchema.java, services-custom/dynamodb-enhanced/src/test/java/software/amazon/awssdk/enhanced/dynamodb/document/DefaultEnhancedDocumentTest.java, services-custom/dynamodb-enhanced/src/test/java/software/amazon/awssdk/enhanced/dynamodb/document/EnhancedDocumentTest.java, services-custom/dynamodb-enhanced/src/test/java/software/amazon/awssdk/enhanced/dynamodb/mapper/DocumentTableSchemaTest.java
- Implementation of Document Table Schema
- ItemToMap amd MapToItem directly uses the DefaultEnhancedDocument to get the AttributeValue Map.
- Junits added
=> DocumentTableSchema Implementation

core/auth-crt/pom.xml, core/auth/pom.xml, core/http-auth-aws-crt/pom.xml, core/http-auth-aws-crt/src/main/java/software/amazon/awssdk/http/auth/aws/crt/Placeholder.java, core/http-auth-aws/pom.xml, core/http-auth-aws/src/main/java/software/amazon/awssdk/http/auth/aws/Placeholder.java, core/http-auth-event-stream/pom.xml, core/http-auth-event-stream/src/main/java/software/amazon/awssdk/http/auth/eventstream/Placeholder.java, core/http-auth-spi/pom.xml, core/http-auth-spi/src/main/java/software/amazon/awssdk/http/auth/spi/Placeholder.java, core/http-auth/pom.xml, core/http-auth/src/main/java/software/amazon/awssdk/http/auth/Placeholder.java, core/identity-spi/pom.xml, core/identity-spi/src/main/java/software/amazon/awssdk/identity/spi/Placeholder.java, core/pom.xml, core/sdk-core/pom.xml, pom.xml
As part of Smithy Reference Architecture, we are defining new Identity and Auth interfaces that will reside in new modules.
This change adds new modules and makes existing modules will depend on these new modules for backwards-compatibility. The actual code changes will be done in separate PRs. This change preps the module changes only. To allow the build to succeed, Placeholder.java classes are added to make the module jar non-empty and also maven-dependency-plugin has been temporarily disabled.
`./mvnw clean install`
=> Module changes for Identity & Auth

utils/src/main/java/software/amazon/awssdk/utils/cache/CachedSupplier.java
Fixes [issue 3323](https://github.com/aws/aws-sdk-java-v2/issues/3323)
Prevents having to initialize at buildtime `software.amazon.awssdk.utils.cache.CachedSupplier` when building native images.
Tested the fix based on steps to reproduce in the [issue](https://github.com/aws/aws-sdk-java-v2/issues/3323#issuecomment-1308034440)
=> [Bug bash] Native image build fails due to CachedSupplier/SplittableRandom

services-custom/dynamodb-enhanced/src/main/java/software/amazon/awssdk/enhanced/dynamodb/internal/document/DefaultEnhancedDocument.java, services-custom/dynamodb-enhanced/src/main/java/software/amazon/awssdk/enhanced/dynamodb/internal/document/DocumentUtils.java, services-custom/dynamodb-enhanced/src/test/java/software/amazon/awssdk/enhanced/dynamodb/converters/document/CustomAttributeForDocumentConverterProvider.java, services-custom/dynamodb-enhanced/src/test/java/software/amazon/awssdk/enhanced/dynamodb/converters/document/CustomClassForDocumentAPI.java, services-custom/dynamodb-enhanced/src/test/java/software/amazon/awssdk/enhanced/dynamodb/converters/document/CustomClassForDocumentAPIBuilder.java, services-custom/dynamodb-enhanced/src/test/java/software/amazon/awssdk/enhanced/dynamodb/converters/document/CustomClassForDocumentAttributeConverter.java, services-custom/dynamodb-enhanced/src/test/java/software/amazon/awssdk/enhanced/dynamodb/converters/document/CustomIntegerAttributeConverter.java, services-custom/dynamodb-enhanced/src/test/java/software/amazon/awssdk/enhanced/dynamodb/document/EnhancedDocumentTest.java
…h attribute converters are added to it
- The builder for EnhancedDocument should not rely on the order in which attribute converters are added to it
- The generic objects are converted to AttributeValue Object are Build time.
- Added Junits
#
=> The builder for EnhancedDocument should not rely on the order in which attribute converters are added to it

.changes/next-release/bugfix-AWSSDKforJavav2-3a9f7b8.json, bom-internal/pom.xml, http-clients/apache-client/pom.xml
Fix #3787 
Add commons-codec to bom-internal to fix dependency convergence issue
Tested locally with `maven-enforcer-plugin` and verified the dependency convergence issue was resolved.
=> Add commons-codec to bom-internal to fix dependency convergence issue

javadoc-resources/aws-sdk-java-v2-javadoc.css, pom.xml
Update the `maven-javadoc-plugin` to add a new custom css file to the generated javadoc. This custom css file will make **all** links in the javadoc website bold.
Ran `mvn clean install javadoc:aggregate -B -Ppublic-javadoc -Dcheckstyle.skip -Dspotbugs.skip -DskipTests -Ddoclint=none -pl <module>` locally for a few modules and open the generated javadoc in chrome and firefox. That is the command ran by the release-javadoc build
=> Make 'a href' links bold in javadoc

services-custom/dynamodb-enhanced/src/main/java/software/amazon/awssdk/enhanced/dynamodb/internal/document/DefaultEnhancedDocument.java, services-custom/dynamodb-enhanced/src/main/java/software/amazon/awssdk/enhanced/dynamodb/internal/document/JsonStringFormatHelper.java, services-custom/dynamodb-enhanced/src/test/java/software/amazon/awssdk/enhanced/dynamodb/document/EnhancedDocumentTest.java, services-custom/dynamodb-enhanced/src/test/java/software/amazon/awssdk/enhanced/dynamodb/document/EnhancedDocumentTestData.java, services-custom/dynamodb-enhanced/src/test/java/software/amazon/awssdk/enhanced/dynamodb/document/ParameterizedDocumentTest.java
- The present implementation of toJson representations in ArrayJsonNode and ObjectJsonNode includes additional spaces. This, however, contrasts with the V1 to Json, which does not incorporate any spaces between array elements or between key and values in a map. 
- Additionally, character escaping has not been executed, and hence, it is imperative to add the same.
- Not using toString of JsonNode
- Added new code to generate to String for Arrays and Map without the commas.
- Added temporary parmeterized test and verified both V1 and v2 matches
```java
@ParameterizedTest
@ArgumentsSource(EnhancedDocumentTestData.class)
void testV1VsV2(TestData testData){
Assertions.assertThat(EnhancedDocument.fromJson(testData.getJson()).toJson())
.isEqualTo(Item.fromJSON(testData.getJson()).toJSON());
} …
```
=> Remove extra spaces in Json and make it same as Items as in V1

services-custom/dynamodb-enhanced/src/main/java/software/amazon/awssdk/enhanced/dynamodb/document/EnhancedDocument.java, services-custom/dynamodb-enhanced/src/main/java/software/amazon/awssdk/enhanced/dynamodb/internal/document/DefaultEnhancedDocument.java, services-custom/dynamodb-enhanced/src/main/java/software/amazon/awssdk/enhanced/dynamodb/mapper/DocumentTableSchema.java, services-custom/dynamodb-enhanced/src/test/java/software/amazon/awssdk/enhanced/dynamodb/document/EnhancedDocumentTest.java, services-custom/dynamodb-enhanced/src/test/java/software/amazon/awssdk/enhanced/dynamodb/document/EnhancedDocumentTestData.java, services-custom/dynamodb-enhanced/src/test/java/software/amazon/awssdk/enhanced/dynamodb/document/ParameterizedDocumentTest.java, services-custom/dynamodb-enhanced/src/test/java/software/amazon/awssdk/enhanced/dynamodb/functionaltests/document/BasicAsyncCrudTest.java, services-custom/dynamodb-enhanced/src/test/java/software/amazon/awssdk/enhanced/dynamodb/functionaltests/document/BasicCrudTest.java, services-custom/dynamodb-enhanced/src/test/java/software/amazon/awssdk/enhanced/dynamodb/functionaltests/document/BasicQueryTest.java, services-custom/dynamodb-enhanced/src/test/java/software/amazon/awssdk/enhanced/dynamodb/functionaltests/document/BasicScanTest.java, services-custom/dynamodb-enhanced/src/test/java/software/amazon/awssdk/enhanced/dynamodb/functionaltests/document/IndexQueryTest.java, services-custom/dynamodb-enhanced/src/test/java/software/amazon/awssdk/enhanced/dynamodb/functionaltests/document/IndexScanTest.java, services-custom/dynamodb-enhanced/src/test/java/software/amazon/awssdk/enhanced/dynamodb/functionaltests/models/InnerAttribConverterProvider.java
- Surface API Review 2 and Dog feeding session 2 comments
- changed API name of Type  in postfix like putMapOfType to putMap.
- Added API for class <T> type gets and puts
- Added functional test cases.
- Added Junit Test cases
- Added Basic Crud, Async , Query, Scan related test cases for DDB.
=> Functional Test Cases for Document DDB API and Surface API Review 2 comments

services-custom/dynamodb-enhanced/src/main/java/software/amazon/awssdk/enhanced/dynamodb/internal/EnhancedClientUtils.java, services-custom/dynamodb-enhanced/src/test/java/software/amazon/awssdk/enhanced/dynamodb/functionaltests/BasicCrudTest.java
Attribute names containing spaces are legal in DDB (only '#' and ':' are reserved). When the enhanced client constructs an "expression attribute name", i.e. a label that is safe to be used in lieu of the actual attribute name, we do that by removing some special chars from the original attribute name and add it to a prefix. 
Example: `my/Strange.Attribute`  -> `#AMZN_MAPPED_my_Strange_Attribute`
At the moment, spaces are missing from the list of special chars.
This bug fix adds space to the list of special chars so that the following use case works as expected:
Example: `Spaced Attribute`  -> `#AMZN_MAPPED_Spaced_Attribute`
We could consider removing the attribute name from the expression name label altogether, favoring numbered names. 
Example:
`Spaced Attribute`  ->  `#AMZN_MAPPED_1` …
=> Cleans spaces when constructing an expression name

pom.xml
Attempt to fix wrong Sonatype Source Control link. 
Example: https://central.sonatype.com/artifact/software.amazon.awssdk/core/2.20.35
=> fix wrong Source Control url in sonatype

core/auth/src/main/java/software/amazon/awssdk/auth/credentials/CredentialUtils.java, core/auth/src/test/java/software/amazon/awssdk/auth/credentials/CredentialUtilsTest.java
In CredentialUtils.toCredentialsProvider, avoid creating another object if the input is already the right type. Made similar change in recent [PR](https://github.com/aws/aws-sdk-java-v2/pull/3829/files#diff-928b4009e4b9df4c8822e946fe1512c7b38f05dbc88ed67f69cf4dd1d690a8a5), to only for toCredentials. Did not want to add more to that PR as it was already big.
In CredentialUtils.toCredentialsProvider, avoid creating another object if the input is already the right type.
Added unit test and
```
./mvnw clean install -pl :auth
```
=> Skip avoidable conversion in CredentialsUtils

services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/crt/DefaultS3CrtAsyncClient.java
Remove unused methods. Discovered while working on https://github.com/aws/aws-sdk-java-v2/pull/3829, but pulled into separate PR here.
Remove unused methods.
` ./mvnw clean install -pl :s3`
=> Remove unused methods in DefaultS3CrtClientBuilder

services-custom/dynamodb-enhanced/src/main/java/software/amazon/awssdk/enhanced/dynamodb/model/UpdateItemEnhancedResponse.java
to correctly describe which return values the attributes have. 
The documentation for UpdateItemEnhancedResponse.attributes() is incorrect and states that the attribute values returned after updateItem operation has been called are the old values, while in fact we return the new values.
In UpdateItemOperation.generateRequest():
~~~
UpdateItemRequest.Builder requestBuilder = UpdateItemRequest.builder()
.tableName(operationContext.tableName())
.key(keyAttributes)
.returnValues(ReturnValue.ALL_NEW);
~~~
=> Fixing the documentation for UpdateItemEnhancedResponse ..

.changes/next-release/feature-AmazonS3-92ece24.json, services/s3/src/main/java/software/amazon/awssdk/services/s3/S3Uri.java, services/s3/src/main/java/software/amazon/awssdk/services/s3/S3Utilities.java, services/s3/src/main/java/software/amazon/awssdk/services/s3/parsing/S3Uri.java, services/s3/src/test/java/software/amazon/awssdk/services/s3/S3UtilitiesTest.java
V2 Parity - S3 URI Parser
https://github.com/aws/aws-sdk-java-v2/issues/272
Adds parseUri() to S3Utilities, which returns a parsed S3Uri object
=> S3 URI Parser

core/auth/src/main/java/software/amazon/awssdk/auth/credentials/AwsCredentialsProviderChain.java, core/auth/src/test/java/software/amazon/awssdk/auth/credentials/AwsCredentialsProviderChainTest.java
As part of SRA changes, update AwsCredentialsProviderChain for new Identity type.
Added overloaded methods that accept the new Identity type. For Collection input, cannot use the same method name because it results in compile error: `both methods have same erasure`, so created method with different name.
Confirmed that adding overloaded varargs for the 2 types is fine and not ambiguous when when called with zero args, because of https://docs.oracle.com/javase/specs/jls/se8/html/jls-15.html#jls-15.12.2.5 - it chooses the more specific method (old type, which is sub-type of the new type). In any case these methods with varargs when called with zero args, throws RuntimeException because we require at least 1 provider in the chain.
Added unit tests and `./mvnw clean install -pl :auth`
=> Update AwsCredentialsProviderChain for new Identity type

test/protocol-tests/src/test/java/software/amazon/awssdk/protocol/tests/timeout/async/AsyncApiCallTimeoutTest.java, test/protocol-tests/src/test/java/software/amazon/awssdk/protocol/tests/util/MockAsyncHttpClient.java
Intermittent test failures in AsyncApiCallTimeoutTest
Use mock HTTP client instead of Wiremock
Updated tests and ran successfully
=> Fix intermittent test failures in AsyncApiCallTimeoutTest

.changes/next-release/feature-AWSSDKforJavav2-f449613.json, codegen/src/main/java/software/amazon/awssdk/codegen/poet/builder/AsyncClientBuilderClass.java, codegen/src/main/java/software/amazon/awssdk/codegen/poet/builder/SyncClientBuilderClass.java, codegen/src/main/java/software/amazon/awssdk/codegen/poet/model/ServiceClientConfigurationClass.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/builder/test-async-client-builder-class.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/builder/test-sync-client-builder-class.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/serviceclientconfiguration.java, core/aws-core/src/main/java/software/amazon/awssdk/awscore/AwsServiceClientConfiguration.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/SdkServiceClientConfiguration.java, test/codegen-generated-classes-test/src/test/java/software/amazon/awssdk/services/serviceclientconfiguration/ServiceClientConfigurationTest.java
Expose endpointOverride of SdkClient, through ServiceClientConfiguration
Added endpointOverride to ServiceClientConfiguration
=> Expose endpointOverride through ServiceClientConfiguration

.changes/next-release/feature-AWSSDKforJavav2-e102314.json, services/s3/src/main/java/software/amazon/awssdk/services/s3/crt/S3CrtHttpConfiguration.java, services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/crt/S3NativeClientConfiguration.java
- S3 Crtclient did not have a way to disable TrustCertificates in its in-built http client
Based on https://github.com/aws/aws-sdk-java-v2/blob/master/http-clients/aws-crt-client/src/main/java/software/amazon/awssdk/http/crt/AwsCrtAsyncHttpClient.java#L103 added a option in S3CrtHttpConfiguration class to disable TrustAllCertificates options
- Reference [tls_context_options](https://awslabs.github.io/aws-crt-cpp/class_aws_1_1_crt_1_1_io_1_1_tls_context_options.html#a94e652e626b9b6f5b6fcde274244fcb7)
=> Add TrustAllCertificates in CRT S3 Client options

codegen/src/main/java/software/amazon/awssdk/codegen/poet/rules/EndpointProviderSpec.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/rules/endpoint-provider-class.java, test/codegen-generated-classes-test/src/test/java/software/amazon/awssdk/services/endpointproviders/EndpointProviderTest.java
Add validation that ensures that required params are present on the endpoint params object before evaluating the rule-set.
Validation required by the cross-SDK standard for this.
=> Validate required params present before running rules

codegen/src/main/java/software/amazon/awssdk/codegen/poet/client/SyncClientClass.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/test-endpoint-discovery-sync.java, core/auth/src/main/java/software/amazon/awssdk/auth/credentials/AwsCredentialsProviderChain.java, core/auth/src/main/java/software/amazon/awssdk/auth/credentials/CredentialUtils.java, core/auth/src/main/java/software/amazon/awssdk/auth/token/credentials/SdkTokenProviderChain.java, services/polly/src/main/java/software/amazon/awssdk/services/polly/internal/presigner/DefaultPollyPresigner.java, services/rds/src/main/java/software/amazon/awssdk/services/rds/DefaultRdsUtilities.java, services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/crt/CrtCredentialsProviderAdapter.java, utils/src/main/java/software/amazon/awssdk/utils/CompletableFutureUtils.java, utils/src/test/java/software/amazon/awssdk/utils/CompletableFutureUtilsTest.java
Identity resolution is async now. Inside sync client we have to "join", but we can handle the exceptions from async resolution to make it appear like sync.
Add a utility `joinLikeSync()` method to handle exceptions just like the async task would have thrown if it was executed synchronously.
=> Use joinLikeSync when resolving identity in sync code

core/pom.xml, core/retries-api/src/main/java/software/amazon/awssdk/retries/api/AcquireInitialTokenRequest.java, core/retries-api/src/main/java/software/amazon/awssdk/retries/api/AcquireInitialTokenResponse.java, core/retries-api/src/main/java/software/amazon/awssdk/retries/api/RecordSuccessRequest.java, core/retries-api/src/main/java/software/amazon/awssdk/retries/api/RecordSuccessResponse.java, core/retries-api/src/main/java/software/amazon/awssdk/retries/api/RefreshRetryTokenRequest.java, core/retries-api/src/main/java/software/amazon/awssdk/retries/api/RefreshRetryTokenResponse.java, core/retries-api/src/main/java/software/amazon/awssdk/retries/api/RetryStrategy.java, core/retries-api/src/main/java/software/amazon/awssdk/retries/api/internal/AcquireInitialTokenRequestImpl.java, core/retries-api/src/main/java/software/amazon/awssdk/retries/api/internal/AcquireInitialTokenResponseImpl.java, core/retries-api/src/main/java/software/amazon/awssdk/retries/api/internal/RecordSuccessRequestImpl.java, core/retries-api/src/main/java/software/amazon/awssdk/retries/api/internal/RecordSuccessResponseImpl.java, core/retries-api/src/main/java/software/amazon/awssdk/retries/api/internal/RefreshRetryTokenRequestImpl.java, core/retries-api/src/main/java/software/amazon/awssdk/retries/api/internal/RefreshRetryTokenResponseImpl.java, core/retries-api/src/test/java/software/amazon/awssdk/retries/api/RetryStrategyBuilderTest.java, core/retries/src/main/java/software/amazon/awssdk/retries/DefaultRetryStrategy.java, core/retries/src/main/java/software/amazon/awssdk/retries/StandardRetryStrategy.java, core/retries/src/main/java/software/amazon/awssdk/retries/internal/DefaultRetryToken.java, core/retries/src/main/java/software/amazon/awssdk/retries/internal/StandardRetryStrategyImpl.java, core/retries/src/main/java/software/amazon/awssdk/retries/internal/circuitbreaker/AcquireResponse.java, core/retries/src/main/java/software/amazon/awssdk/retries/internal/circuitbreaker/ReleaseResponse.java, core/retries/src/main/java/software/amazon/awssdk/retries/internal/circuitbreaker/TokenBucket.java, core/retries/src/main/java/software/amazon/awssdk/retries/internal/circuitbreaker/TokenBucketStore.java, core/retries/src/test/java/software/amazon/awssdk/retries/internal/StandardRetryStrategyMiscTest.java, core/retries/src/test/java/software/amazon/awssdk/retries/internal/StandardRetryStrategyTest.java, test/tests-coverage-reporting/pom.xml
This new module includes the interfaces and classes that will be used to implement the new retry logic within the SDK.
As part of the Smithy Reference Architecture this change adds the new default standard strategy.
No modifications to existing code were made. We will make those changes in follow up pull requests.
* Added unit tests for the new `StandarRetryStrategy`
N/A
=> Add standard retry strategy

.changes/next-release/bugfix-NettyNIOHTTPClient-b68759c.json, http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/internal/utils/NettyUtils.java, http-clients/netty-nio-client/src/test/java/software/amazon/awssdk/http/nio/netty/internal/utils/NettyUtilsTest.java
https://github.com/aws/aws-sdk-java-v2/issues/3935
Added null-pointer check and regression tests to increase coverage.
The included tests were tested running the unit tests of that module with `./mvnw package`
Testing environment
JDK: java-1.8.0-amazon-corretto-devel
OS: Amazon Linux 2 Kernel 5.10, 64 bits.
=> NettyUtils: added safe check for null pointers. Added regression tests.

codegen/src/main/java/software/amazon/awssdk/codegen/poet/client/AsyncClientClass.java, codegen/src/main/java/software/amazon/awssdk/codegen/poet/client/specs/JsonProtocolSpec.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/test-endpoint-discovery-async.java
Identity resolution is async now. Inside async client we shouldn't `join()`. This removes earlier use of `join()` in endpoint discovery logic in async clients, addressing https://github.com/aws/aws-sdk-java-v2/pull/3829#discussion_r1140705992.
Uses combination of thenApply and thenCompose to get from credentials->endpoint->execute.
=> Remove identity join in async client for endpoint discovery

.changes/next-release/bugfix-AWSSDKforJavav2-540f927.json, core/profiles/src/main/java/software/amazon/awssdk/profiles/ProfileFile.java, core/profiles/src/test/java/software/amazon/awssdk/profiles/ProfileFileTest.java
Now it returns an empty map, as it used to in previous sdk versions.
https://github.com/aws/aws-sdk-java-v2/issues/3869
Returning empty map instead of null. This prevents null-pointer exceptions when calling the profiles() method.
The included tests were tested running the unit tests of that module with ./mvnw package
Testing environment
Java version: 1.8.0_361, vendor: Oracle Corporation
OS name: "windows 10", version: "10.0", arch: "amd64"
=> ProfileFile: Corrects behaviour when config and credentials not found

core/retries/src/main/java/software/amazon/awssdk/retries/AdaptiveRetryStrategy.java, core/retries/src/main/java/software/amazon/awssdk/retries/DefaultRetryStrategy.java, core/retries/src/main/java/software/amazon/awssdk/retries/StandardRetryStrategy.java, core/retries/src/main/java/software/amazon/awssdk/retries/internal/AdaptiveRetryStrategyImpl.java, core/retries/src/main/java/software/amazon/awssdk/retries/internal/circuitbreaker/TokenBucketStore.java, core/retries/src/main/java/software/amazon/awssdk/retries/internal/ratelimiter/RateLimiterAcquireResponse.java, core/retries/src/main/java/software/amazon/awssdk/retries/internal/ratelimiter/RateLimiterClock.java, core/retries/src/main/java/software/amazon/awssdk/retries/internal/ratelimiter/RateLimiterTokenBucket.java, core/retries/src/main/java/software/amazon/awssdk/retries/internal/ratelimiter/RateLimiterTokenBucketStore.java, core/retries/src/main/java/software/amazon/awssdk/retries/internal/ratelimiter/RateLimiterUpdateResponse.java, core/retries/src/main/java/software/amazon/awssdk/retries/internal/ratelimiter/SystemClock.java, core/retries/src/test/java/software/amazon/awssdk/retries/internal/AdaptiveRetryStrategyResourceConstrainedTest.java, core/retries/src/test/java/software/amazon/awssdk/retries/internal/AdaptiveRetryStrategyTest.java, core/retries/src/test/java/software/amazon/awssdk/retries/internal/ratelimiter/RateLimiterTokenBucketTest.java
This new module includes the interfaces and classes that will be used to implement the new retry logic within the SDK.
As part of the Smithy Reference Architecture this change adds the new default adaptive strategy.
No modifications to existing code were made. We will make those changes in follow up pull requests.
* Added unit tests for the new `AdaptiveRetryStrategy`
N/A
=> Add adaptive retry strategy

core/http-auth-spi/pom.xml, core/http-auth-spi/src/main/java/software/amazon/awssdk/http/auth/spi/HttpSignRequest.java, core/http-auth-spi/src/main/java/software/amazon/awssdk/http/auth/spi/HttpSigner.java, core/http-auth-spi/src/main/java/software/amazon/awssdk/http/auth/spi/SignedHttpRequest.java, core/http-auth-spi/src/main/java/software/amazon/awssdk/http/auth/spi/SignerProperty.java, core/http-auth-spi/src/main/java/software/amazon/awssdk/http/auth/spi/internal/DefaultHttpSignRequest.java, core/http-auth-spi/src/main/java/software/amazon/awssdk/http/auth/spi/internal/DefaultSignedHttpRequest.java, core/http-auth-spi/src/test/java/software/amazon/awssdk/http/auth/spi/SignerPropertyTest.java, core/pom.xml
As part of Smithy Reference Architecture, we are defining new Identity and Auth components. This changes adds the new Signer interfaces.
This changes adds the new Signer interfaces in the http-auth-spi module.
=> Add new Signer interfaces

core/retries-api/src/main/java/software/amazon/awssdk/retries/api/TokenAcquisitionFailedException.java, core/retries-api/src/test/java/software/amazon/awssdk/retries/api/RetryStrategyBuilderTest.java, core/retries-api/src/test/java/software/amazon/awssdk/retries/api/internal/backoff/ExponentialDelayWithJitterTest.java, core/retries-api/src/test/java/software/amazon/awssdk/retries/api/internal/backoff/FixedDelayWithJitterTest.java, core/retries/src/it/java/software/amazon/awssdk/retries/internal/AdaptiveRetryStrategyResourceConstrainedTest.java, core/retries/src/main/java/software/amazon/awssdk/retries/internal/AdaptiveRetryStrategyImpl.java, core/retries/src/main/java/software/amazon/awssdk/retries/internal/StandardRetryStrategyImpl.java, core/retries/src/test/java/software/amazon/awssdk/retries/internal/AdaptiveRetryStrategyResourceConstrainedTest.java, core/retries/src/test/java/software/amazon/awssdk/retries/internal/AdaptiveRetryStrategyTest.java, core/retries/src/test/java/software/amazon/awssdk/retries/internal/StandardRetryStrategyMiscTest.java, core/retries/src/test/java/software/amazon/awssdk/retries/internal/StandardRetryStrategyTest.java, core/retries/src/test/java/software/amazon/awssdk/retries/internal/ratelimiter/RateLimiterTokenBucketTest.java
This pull request is a follow up to the previous one that added [AdaptiveRetryStrategy](https://github.com/aws/aws-sdk-java-v2/pull/3975) to clean up the current SonarCloud smells.
Follow up to my previous pull request to clean up the reported code smells by SonarCloud.
No modifications to existing code were made. We will make those changes in follow up pull requests.
N/A
N/A
=> Fix SonarCloud code smells

core/http-auth-aws-crt/pom.xml, core/http-auth-aws-crt/src/main/java/software/amazon/awssdk/http/auth/aws/crt/AwsCrtS3V4aHttpAuthScheme.java, core/http-auth-aws-crt/src/main/java/software/amazon/awssdk/http/auth/aws/crt/AwsCrtV4aHttpAuthScheme.java, core/http-auth-aws/pom.xml, core/http-auth-aws/src/main/java/software/amazon/awssdk/http/auth/aws/AwsS3V4HttpSigner.java, core/http-auth-event-stream/pom.xml, core/http-auth-event-stream/src/main/java/software/amazon/awssdk/http/auth/eventstream/AwsV4EventStreamHttpAuthScheme.java, core/http-auth/pom.xml, core/http-auth/src/main/java/software/amazon/awssdk/http/auth/AwsV4HttpSigner.java, core/http-auth/src/main/java/software/amazon/awssdk/http/auth/AwsV4QueryHttpSigner.java, core/http-auth/src/main/java/software/amazon/awssdk/http/auth/BearerHttpSigner.java, core/pom.xml
This commit adds the new Signer interface stubs and poms to respective modules
`$ ./mvnw -pl :http-auth,:http-auth-aws,:http-auth-aws-crt,:http-auth-event-stream clean install -am`
- Made sure there were no build errors
=> Add interface stubs for new signer implementations

codegen/src/main/java/software/amazon/awssdk/codegen/model/config/customization/ServiceConfig.java, codegen/src/main/java/software/amazon/awssdk/codegen/poet/builder/AsyncClientBuilderClass.java, codegen/src/main/java/software/amazon/awssdk/codegen/poet/builder/SyncClientBuilderClass.java, codegen/src/main/java/software/amazon/awssdk/codegen/poet/model/ServiceClientConfigurationClass.java, codegen/src/main/java/software/amazon/awssdk/codegen/poet/rules/EndpointParametersClassSpec.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/builder/test-async-client-builder-class.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/builder/test-sync-client-builder-class.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/serviceclientconfiguration.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/rules/endpoint-parameters.java, core/aws-core/src/main/java/software/amazon/awssdk/awscore/AwsServiceClientConfiguration.java, core/aws-core/src/main/java/software/amazon/awssdk/awscore/internal/AwsExecutionContextBuilder.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/RequestOverrideConfiguration.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/SdkServiceClientConfiguration.java, services/s3/src/main/java/software/amazon/awssdk/services/s3/S3Configuration.java, services/s3/src/test/java/software/amazon/awssdk/services/s3/S3ConfigurationTest.java, test/codegen-generated-classes-test/src/test/java/software/amazon/awssdk/services/endpointproviders/RequestOverrideEndpointProviderTests.java, test/codegen-generated-classes-test/src/test/java/software/amazon/awssdk/services/serviceclientconfiguration/ServiceClientConfigurationTest.java
Add endpointProvider in ClientConfig and RequestOverrideConfig. Also add crossRegionBucketAccess in S3Configuration
Note : This PR just adds the interfaces in project branch to read/writ EndpointProviders/S3 config. The logic of overriding and resolving in COntectBuilders will be addded next PR
- CrossRegionBucketAccess needs the endpointProviders of the client.
- Its needed to decorate endpointProviders so that region name is changed based on HeadBucket request
=> Add endpointProvider in ClientConfig and RequestOverrideConfig. Also add crossRegionBucketAccess in S3Configuration

.changes/next-release/bugfix-AWSSDKforJavav2-abc1eac.json, core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/http/pipeline/stages/MakeAsyncHttpRequestStage.java, core/sdk-core/src/test/java/software/amazon/awssdk/core/internal/http/pipeline/stages/MakeAsyncHttpRequestStageTest.java
This commit fixes  an issue where CompletableFutures are leaked/never completed when the submission to the FUTURE_COMPLETE_EXECUTOR is rejected.
By default, the SDK uses `2 * number of cores` (with a maximum of 64), and uses bounded queue of size 1000. In cases where the throughput to the client exceeds the executor's ability to keep up, it would reject executions, and previously, this would lead to leaked futures.
- Unit tests.
- Integ tests.
=> Fix leaked futures when executor rejects Runnable

codegen/src/main/java/software/amazon/awssdk/codegen/model/rules/endpoints/BuiltInParameter.java, codegen/src/main/java/software/amazon/awssdk/codegen/poet/rules/EndpointResolverInterceptorSpec.java, codegen/src/main/resources/software/amazon/awssdk/codegen/rules/AwsEndpointProviderUtils.java.resource, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/c2j/query/endpoint-rule-set.json, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/rules/endpoint-parameters.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/rules/endpoint-provider-class.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/rules/endpoint-resolve-interceptor.java, core/aws-core/src/main/java/software/amazon/awssdk/awscore/AwsExecutionAttribute.java
Adds identity-sourced account ID as a built-in endpoint rule parameter
Codegen changes that modify the endpoint rule, the parameter resolution and the endpoint resolver interceptor. 
For now, the account ID is retrieved from an AWS execution attribute - this may change in later PRs.
=> Adds account ID as a built-in endpoint parameter

core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/http/pipeline/stages/MakeAsyncHttpRequestStage.java, core/sdk-core/src/test/java/software/amazon/awssdk/core/internal/http/pipeline/stages/MakeAsyncHttpRequestStageTest.java
Update the fix from #4009.
whenCompleteAsync is incorrect because if the response handler future completes exceptionally, then the returned future will also be completed with that exception which will incorrectly trigger a synchronous completion for the response future.
=> Switch to handleAsync

pom.xml
New version includes a fix for:
#3750 - S3 CRT client is ignoring content-encoding in single part uploads.
=> Bump aws-crt version to 0.21.16

.changes/next-release/feature-AWSSDKforJavav2-c5f66b2.json, core/sdk-core/src/main/java/software/amazon/awssdk/core/client/builder/SdkDefaultClientBuilder.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/client/config/ClientOverrideConfiguration.java, core/sdk-core/src/test/java/software/amazon/awssdk/core/client/builder/DefaultClientBuilderTest.java, test/protocol-tests/src/test/java/software/amazon/awssdk/protocol/tests/ResourceManagementTest.java, utils/src/main/java/software/amazon/awssdk/utils/ScheduledExecutorUtils.java
Customer should be able to use their own ThreadPool and reuse it accros multiple clients.
https://github.com/aws/aws-sdk-java-v2/issues/1690
Introduce new client config methods to allow to override `SCHEDULED_EXECUTOR_SERVICE` option. It is optional and when not provided will default to the actual code that create a new ThreadPool for each clients
Unit tests ensure the override is applied on the client configuration.
I also tested in a private project by setting api call timeout to actually create new thread on the custom thread pool.
=> Add client configuration overriding of SCHEDULED_EXECUTOR_SERVICE option

codegen/src/main/java/software/amazon/awssdk/codegen/poet/client/DelegatingAsyncClientClass.java, codegen/src/main/java/software/amazon/awssdk/codegen/poet/client/DelegatingSyncClientClass.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/test-abstract-async-client-class.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/test-abstract-sync-client-class.java, services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/crossregion/S3CrossRegionAsyncClient.java, services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/crossregion/S3CrossRegionSyncClient.java, services/s3/src/test/java/software/amazon/awssdk/services/s3/internal/crossregion/S3CrossRegionAsyncClientTest.java, services/s3/src/test/java/software/amazon/awssdk/services/s3/internal/crossregion/S3CrossRegionSyncClientTest.java, test/codegen-generated-classes-test/src/main/resources/codegen-resources/customresponsemetadata/customization.config, test/codegen-generated-classes-test/src/main/resources/codegen-resources/xml/service-2.json, test/codegen-generated-classes-test/src/test/java/software/amazon/awssdk/services/delegatingclients/DelegatingAsyncClientTest.java, test/codegen-generated-classes-test/src/test/java/software/amazon/awssdk/services/delegatingclients/DelegatingSyncClientTest.java
Adds the structure and signatures for the new cross region client to be able to successfully decorate the existing S3 client with an override config containing a decorated endpoint provider. 
- Changes the signature of `invokeOperation` (back) to `CompletableFuture`, which is necessary in order to use nonblocking I/O
- Modifies paginated methods that return `Publisher` or `Iterable` to NOT use `invokeOperation` in the abstract delegating clients, i.e. back to originating behavior. The correct place to intercept these calls is when each page is called which will be handled by a later PR. 
- Adds the logic of modifying the request and correctly creating/overriding the RequestOverrideConfig to the cross region client
- Adds a `BucketEndpointProvider` that will contain the cross-region logic …
=> Adds cross region client logic for decorating endpoint provider

core/identity-spi/src/main/java/software/amazon/awssdk/identity/spi/ResolveIdentityRequest.java, core/identity-spi/src/main/java/software/amazon/awssdk/identity/spi/internal/DefaultResolveIdentityRequest.java, core/identity-spi/src/test/java/software/amazon/awssdk/identity/spi/ResolveIdentityRequestTest.java
We prefer to use interfaces, even for such data objects. Similar to what we did in the Signer interfaces.
Change ResolveIdentityRequest to an interface and add an internal implementation class.
=> Change ResolveIdentityRequest to an interface

services/sts/src/main/java/software/amazon/awssdk/services/sts/auth/StsCredentialsProvider.java
This fixes an issue where their members weren't appearing in the javadoc of subclasses, even though their members could be called.
=> Mark StsCredentialsProvider and StsCredentialsProvider.Builder as public.

.changes/next-release/bugfix-AWSSDKforJavav2-5d8e168.json, services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/crt/CopyObjectHelper.java, services/s3/src/test/java/software/amazon/awssdk/services/s3/internal/crt/CopyObjectHelperTest.java
In `CopyObjectHelper` the method `calculateOptimalPartSizeForCopy(long contentLengthOfSource)` expect the content length of the whole object to copy, but is passed the part size instead. This PR is to fix that issue, now it is passed the content length so that the part size can be automatically adjusted if the total number of parts would exceed 10,000.
=> Fix bug about wrong part size number in CopyObjectHelper

core/auth/src/main/java/software/amazon/awssdk/auth/credentials/AwsBasicCredentials.java, core/auth/src/main/java/software/amazon/awssdk/auth/credentials/AwsSessionCredentials.java, core/auth/src/main/java/software/amazon/awssdk/auth/credentials/CredentialUtils.java, core/auth/src/test/java/software/amazon/awssdk/auth/credentials/StaticCredentialsProviderTest.java, core/auth/src/test/java/software/amazon/awssdk/auth/credentials/internal/AwsSessionCredentialsTest.java, core/identity-spi/src/main/java/software/amazon/awssdk/identity/spi/internal/DefaultAwsSessionCredentialsIdentity.java, pom.xml, services/sts/src/it/java/software/amazon/awssdk/services/sts/AssumeRoleIntegrationTest.java, services/sts/src/main/java/software/amazon/awssdk/services/sts/auth/SessionCredentialsHolder.java, services/sts/src/main/java/software/amazon/awssdk/services/sts/auth/StsAssumeRoleCredentialsProvider.java, services/sts/src/main/java/software/amazon/awssdk/services/sts/auth/StsAssumeRoleWithSamlCredentialsProvider.java, services/sts/src/main/java/software/amazon/awssdk/services/sts/auth/StsAssumeRoleWithWebIdentityCredentialsProvider.java, services/sts/src/main/java/software/amazon/awssdk/services/sts/auth/StsCredentialsProvider.java, services/sts/src/main/java/software/amazon/awssdk/services/sts/auth/StsGetFederationTokenCredentialsProvider.java, services/sts/src/main/java/software/amazon/awssdk/services/sts/auth/StsGetSessionTokenCredentialsProvider.java, services/sts/src/main/java/software/amazon/awssdk/services/sts/auth/StsWebIdentityTokenFileCredentialsProvider.java, services/sts/src/main/java/software/amazon/awssdk/services/sts/internal/StsAuthUtils.java, services/sts/src/test/java/software/amazon/awssdk/services/sts/auth/StsAssumeRoleCredentialsProviderTest.java, services/sts/src/test/java/software/amazon/awssdk/services/sts/auth/StsAssumeRoleWithSamlCredentialsProviderTest.java, services/sts/src/test/java/software/amazon/awssdk/services/sts/auth/StsAssumeRoleWithWebIdentityCredentialsProviderTest.java, services/sts/src/test/java/software/amazon/awssdk/services/sts/auth/StsCredentialsProviderTestBase.java, services/sts/src/test/java/software/amazon/awssdk/services/sts/auth/StsGetFederationTokenCredentialsProviderTest.java, services/sts/src/test/java/software/amazon/awssdk/services/sts/auth/StsGetSessionTokenCredentialsProviderTest.java, services/sts/src/test/java/software/amazon/awssdk/services/sts/auth/StsWebIdentityTokenCredentialsProviderBaseTest.java, test/codegen-generated-classes-test/src/main/resources/codegen-resources/endpointproviders/endpoint-rule-set.json, test/codegen-generated-classes-test/src/test/java/software/amazon/awssdk/services/endpointproviders/AccountIdParameterTests.java
STS provides accountId in the ARN of the assumedRoleUser included in its response objects. This PR extracts that accountId, if present, and adds it to the credentials identity. 
Resolving credentials end-to-end should work once credentials are resolved before the endpoint.
- Added accountId to `AwsBasicCredentials` and `AwsSessionCredentials` since the credentials providers use those classes. 
- Modified STS providers to find accountId in the response and add it to the returned credentials
Added codegen classes test to verify that the accountId is available to the endpoint resolution logic. Because we currently resolve the endpoint before we resolve credentials, this test is not working.
=> Adds accountId to STS credentials providers

core/http-auth-aws-crt/src/main/java/software/amazon/awssdk/http/auth/aws/crt/AwsCrtS3V4aHttpAuthScheme.java, core/http-auth-aws-crt/src/main/java/software/amazon/awssdk/http/auth/aws/crt/AwsCrtV4aHttpAuthScheme.java, core/http-auth-aws/src/main/java/software/amazon/awssdk/http/auth/aws/AwsS3V4HttpAuthScheme.java, core/http-auth-event-stream/src/main/java/software/amazon/awssdk/http/auth/eventstream/AwsV4EventStreamHttpAuthScheme.java, core/http-auth/src/main/java/software/amazon/awssdk/http/auth/AwsV4HttpAuthScheme.java, core/http-auth/src/main/java/software/amazon/awssdk/http/auth/AwsV4QueryHttpAuthScheme.java, core/http-auth/src/main/java/software/amazon/awssdk/http/auth/BearerHttpAuthScheme.java
Added AuthScheme sub-interfaces. All methods have default implementation. So for the default class, just created anonymous inner class within `create()`. I think, this can be moved to a named class if/when we want to later.
There is no `public interface AnonymousAuthScheme extends HttpAuthScheme<Void> {` as noted in the design doc. HttpAuthScheme's generic type is defined as `<T extends Identity>`, so `Void` can't be used. I think we may not need an actual sub-type of this interface for the anonymous use case.
**Note**: There will be some upcoming refactoring - dropping Http from some type names, moving the S3 specific interfaces to s3 module and possibly combining some signers. But those will happen separately, and signers and AuthScheme will be updated at the same time later. So want to …
=> Add AuthScheme sub-interfaces

pom.xml
Bump aws-crt to 0.22.1 that has support for streaming with unknown content length #139
=> Bump aws-crt to 0.22.1

core/aws-core/pom.xml, core/aws-core/src/main/java/software/amazon/awssdk/awscore/client/builder/AwsDefaultClientBuilder.java, core/aws-core/src/main/java/software/amazon/awssdk/awscore/retry/AwsRetryStrategy.java, core/retries/src/main/java/software/amazon/awssdk/retries/DefaultRetryStrategy.java, core/sdk-core/pom.xml, core/sdk-core/src/main/java/software/amazon/awssdk/core/client/builder/SdkDefaultClientBuilder.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/client/config/ClientOverrideConfiguration.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/client/config/SdkClientOption.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/client/config/SdkClientOptionValidation.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/InternalCoreExecutionAttribute.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/http/AmazonAsyncHttpClient.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/http/AmazonSyncHttpClient.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/http/pipeline/stages/ApplyUserAgentStage.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/http/pipeline/stages/AsyncRetryableStage2.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/http/pipeline/stages/RetryableStage2.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/http/pipeline/stages/utils/RetryableStageHelper2.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/retry/RetryPolicyAdapter.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/retry/SdkDefaultRetryStrategy.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/retry/backoff/FullJitterBackoffStrategy.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/retry/conditions/SdkRetryCondition.java, core/sdk-core/src/test/java/software/amazon/awssdk/core/client/AsyncClientHandlerExceptionTest.java, core/sdk-core/src/test/java/software/amazon/awssdk/core/client/handler/AsyncClientHandlerTest.java, core/sdk-core/src/test/java/software/amazon/awssdk/core/http/AmazonHttpClientTest.java, core/sdk-core/src/test/java/software/amazon/awssdk/core/internal/http/response/NullErrorResponseHandler.java, core/sdk-core/src/test/java/software/amazon/awssdk/core/internal/http/timers/AsyncHttpClientApiCallTimeoutTests.java, core/sdk-core/src/test/java/software/amazon/awssdk/core/internal/http/timers/HttpClientApiCallAttemptTimeoutTest.java, core/sdk-core/src/test/java/software/amazon/awssdk/core/internal/http/timers/HttpClientApiCallTimeoutTest.java, core/sdk-core/src/test/java/utils/HttpTestUtils.java, test/codegen-generated-classes-test/src/test/java/software/amazon/awssdk/services/retry/RetryHeaderTestSuite.java
This new module includes the interfaces and classes that will be used to implement the new retry logic within the SDK.
This change creates a retryable stages for the sync and async pipelines along side with a new helper. To avoid noisy diffs I suffixed the classes names with 2. After this is approved I will move the stages and helper to the original names.
Notice that this change **does not use yet the new retry policies** but instead it will use the adapter, this will allow us to validate that all the current tests cases work fine with the adapter and later on we will change the `SdkDefaultClientBuilder.java` and `AwsSdkDefaultClientBuilder.java` classes to return null if no explicit retry policy is configured and thus pick the retry strategy.
Also, there are several *fixme* comments …
=> Add new sync and async retryable stages

codegen/src/main/java/software/amazon/awssdk/codegen/model/config/customization/CustomizationConfig.java, codegen/src/main/java/software/amazon/awssdk/codegen/poet/auth/scheme/AuthSchemeParamsSpec.java, codegen/src/main/java/software/amazon/awssdk/codegen/poet/auth/scheme/AuthSchemeSpecUtils.java, codegen/src/main/java/software/amazon/awssdk/codegen/poet/auth/scheme/DefaultAuthSchemeParamsSpec.java, codegen/src/main/java/software/amazon/awssdk/codegen/poet/rules/EndpointParametersClassSpec.java, codegen/src/main/java/software/amazon/awssdk/codegen/poet/rules/EndpointRulesSpecUtils.java, codegen/src/test/java/software/amazon/awssdk/codegen/poet/ClientTestModels.java, codegen/src/test/java/software/amazon/awssdk/codegen/poet/auth/scheme/AuthSchemeSpecTest.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/auth/scheme/query-auth-scheme-default-params.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/auth/scheme/query-auth-scheme-default-provider.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/auth/scheme/query-auth-scheme-params.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/auth/scheme/query-auth-scheme-provider.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/auth/scheme/query-endpoint-auth-params-auth-scheme-default-params.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/auth/scheme/query-endpoint-auth-params-auth-scheme-default-provider.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/auth/scheme/query-endpoint-auth-params-auth-scheme-params.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/auth/scheme/query-endpoint-auth-params-auth-scheme-provider.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/c2j/query/customization-endpoint-auth-params.config, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/c2j/query/endpoint-rule-set.json, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/rules/endpoint-provider-class.java
Add the same set of parameters from the endpoint rules to the auth spec parameters class.
Supersedes [4053](https://github.com/aws/aws-sdk-java-v2/pull/4053) that got into a messy state after a merge attempt and conflicted with another recent change.
This is the generated interface for S3
```java
/*
* Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
* 
* Licensed under the Apache License, Version 2.0 (the "License"). You may not use this file except in compliance with
* the License. A copy of the License is located at
* 
* http://aws.amazon.com/apache2.0
* 
* or in the "license" file accompanying this file. This file is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
* CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language …
```
=> Add auth scheme params based on endpoint params

core/http-auth-aws-crt/pom.xml, core/http-auth-aws/pom.xml, core/http-auth-event-stream/pom.xml, core/http-auth-spi/pom.xml, core/http-auth/pom.xml, core/identity-spi/pom.xml
In the latest merge from master in https://github.com/aws/aws-sdk-java-v2/commit/4504f91e20fb0f424a93999545c8b68f16f21d1b, the version for the new modules in the branch weren't updated.
Update version in new modules to 2.20.83-SNAPSHOT
=> Update version in new modules to 2.20.83-SNAPSHOT after merge

codegen/src/main/java/software/amazon/awssdk/codegen/model/config/customization/CustomizationConfig.java, codegen/src/main/java/software/amazon/awssdk/codegen/model/intermediate/IntermediateModel.java, codegen/src/main/java/software/amazon/awssdk/codegen/poet/builder/AsyncClientBuilderClass.java, codegen/src/main/java/software/amazon/awssdk/codegen/poet/builder/SyncClientBuilderClass.java, codegen/src/main/java/software/amazon/awssdk/codegen/poet/client/DelegatingAsyncClientClass.java, codegen/src/main/java/software/amazon/awssdk/codegen/poet/client/DelegatingSyncClientClass.java, codegen/src/test/java/software/amazon/awssdk/codegen/poet/ClientTestModels.java, codegen/src/test/java/software/amazon/awssdk/codegen/poet/builder/BuilderClassTest.java, codegen/src/test/java/software/amazon/awssdk/codegen/poet/common/UserAgentClassSpecTest.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/builder/test-async-client-builder-class.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/builder/test-composed-async-client-builder-class.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/builder/test-composed-sync-client-builder-class.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/c2j/composedclient/customization.config, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/common/test-user-agent-class.java, core/aws-core/src/main/java/software/amazon/awssdk/awscore/internal/client/ClientComposer.java, services/s3/src/main/java/software/amazon/awssdk/services/s3/S3Configuration.java, services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/client/S3AsyncClientComposer.java, services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/client/S3ClientComposer.java, services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/client/S3SyncClientComposer.java, services/s3/src/main/resources/codegen-resources/customization.config, services/s3/src/test/java/software/amazon/awssdk/services/s3/internal/ClientCompositionFactoryTest.java, services/s3/src/test/java/software/amazon/awssdk/services/s3/internal/crossregion/S3CrossRegionAsyncClientTest.java, services/s3/src/test/java/software/amazon/awssdk/services/s3/internal/crossregion/S3CrossRegionSyncClientTest.java, utils/src/main/java/software/amazon/awssdk/utils/ConditionalDecorator.java, utils/src/main/java/software/amazon/awssdk/utils/internal/DefaultConditionalDecorator.java, utils/src/test/java/software/amazon/awssdk/utils/ConditionalDecoratorTest.java
Users want cross region ability, but do not want or need to know implementation details, they just want to enable the feature. This change modifies the S3 client builder code to check if cross region is enabled and then wraps the regular client in the cross region client and returns it (as an S3Client/S3AsyncClient). 
- Adds a customization flag to point out where the logic for creating a composed S3 client is located
- Changes the builder logic to check the customization flag and if so, call the composing code instead of just returning the client
- Also refactors the builder code to make it more readable
- Adds a decorator utility that can do conditional transforms
- Adds S3 specific logic for creating a list of decorators for client construction and conditions on when to apply them, …
=> Wraps s3 client in cross regional client when enabled

.changes/next-release/feature-DynamoDBEnhancedClient-270c65a.json, services-custom/dynamodb-enhanced/src/main/java/software/amazon/awssdk/enhanced/dynamodb/TableSchema.java, services-custom/dynamodb-enhanced/src/main/java/software/amazon/awssdk/enhanced/dynamodb/mapper/ImmutableAttribute.java, services-custom/dynamodb-enhanced/src/main/java/software/amazon/awssdk/enhanced/dynamodb/mapper/StaticAttribute.java, services-custom/dynamodb-enhanced/src/main/java/software/amazon/awssdk/enhanced/dynamodb/mapper/StaticImmutableTableSchema.java, services-custom/dynamodb-enhanced/src/main/java/software/amazon/awssdk/enhanced/dynamodb/mapper/StaticTableSchema.java, services-custom/dynamodb-enhanced/src/test/java/software/amazon/awssdk/enhanced/dynamodb/TableSchemaTest.java, services-custom/dynamodb-enhanced/src/test/java/software/amazon/awssdk/enhanced/dynamodb/mapper/StaticImmutableTableSchemaTest.java, services-custom/dynamodb-enhanced/src/test/java/software/amazon/awssdk/enhanced/dynamodb/mapper/StaticTableSchemaTest.java, services-custom/dynamodb-enhanced/src/test/java/software/amazon/awssdk/enhanced/dynamodb/mapper/testbeans/EntityEnvelopeBean.java, services-custom/dynamodb-enhanced/src/test/java/software/amazon/awssdk/enhanced/dynamodb/mapper/testimmutables/EntityEnvelopeImmutable.java
Adds `EnhancedType` parameters to static builder methods of `StaticTableSchema` and `StaticImmutableTableSchema`.
This is a QoL change that allows a static `TableSchema` to be constructed for a generic class without forcing you to use the raw-type of the class as the type parameter. For use-cases where you may want to dynamically create a static tableschema around a type that is being passed by a caller, this allows you to do so in a type-safe manner.
There are two workarounds I know about this today:
1. You simply use the raw-class and add extra type checking in the methods that get and set the attributes, and any methods that actually use the TableSchema type in its parameters (which is most operations!). This pushes the onus of ensuring type safety on the caller which is not ideal.
2. …
=> ddb-enhanced: adds EnhancedType parameters to static builder methods of StaticTableSchema and StaticImmutableTableSchema.

core/http-auth-spi/src/main/java/software/amazon/awssdk/http/auth/spi/IdentityProviderConfiguration.java, core/http-auth-spi/src/main/java/software/amazon/awssdk/http/auth/spi/internal/DefaultIdentityProviderConfiguration.java, core/http-auth-spi/src/test/java/software/amazon/awssdk/http/auth/spi/IdentityProviderConfigurationTest.java
Only an interface for IdentityProviderConfiguration was added earlier. Need a default implementation and builder.
Add Builder to the interface and a default internal implementation.
IdentityProviderConfiguration would initially be setup for a client, but we'd want to allow individual request to override its identity provider, so we would need to be able to copy the IdentityProviderConfiguration to mutate. So made it implement ToCopyableBuilder. This meant `@FunctionalInterface` needed to be dropped.
=> Add IdentityProviderConfiguration implementation

core/http-auth-spi/src/main/java/software/amazon/awssdk/http/auth/spi/internal/DefaultSignRequest.java
Otherwise, even after build() is called, if more properties are added to the same builder instance, it mutates the built DefaultSignRequest object.
In constructor of DefaultSignRequest, make copy of the properties map from the Builder.
=> Make copy of properties map from Builder

services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/crossregion/S3CrossRegionAsyncClient.java, services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/crossregion/S3CrossRegionSyncClient.java, services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/crossregion/utils/CrossRegionUtils.java, services/s3/src/test/java/software/amazon/awssdk/services/s3/internal/crossregion/S3CrossRegionAsyncClientTest.java, services/s3/src/test/java/software/amazon/awssdk/services/s3/internal/crossregion/S3CrossRegionSyncClientTest.java
- Add User Agent Api name for Cross region API calls
- Before calling the delgate the request Override config is updated
Final Sample User agent will look like this
```
Optional[aws-sdk-java/2.20.62-SNAPSHOT Mac_OS_X/19.9.1 OpenJDK_128-Bit_Server_VM/11.0.19+7-LTS Java/11.3.19 vendor/Comp_Inc. io/sync http/UNKNOWN cfg/retry-mode/legacy hll/cross-region]
```
- Updated Junit
=> Add User Agent Api name for Cross region API calls

core/identity-spi/src/main/java/software/amazon/awssdk/identity/spi/ResolveIdentityRequest.java, core/identity-spi/src/main/java/software/amazon/awssdk/identity/spi/internal/DefaultResolveIdentityRequest.java, core/identity-spi/src/test/java/software/amazon/awssdk/identity/spi/ResolveIdentityRequestTest.java
Helps resolve ambiguity with consumer builder pattern when using IdentityProvider.resolveIdentity. Identified the issue while working on this PR - https://github.com/aws/aws-sdk-java-v2/pull/4111/files#r1232724782
Make ResolveIdentityRequest copyable
=> Make ResolveIdentityRequest copyable

core/sdk-core/src/main/java/software/amazon/awssdk/core/HttpChecksumConstant.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/interceptor/HttpChecksumInHeaderInterceptor.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/interceptor/HttpChecksumRequiredInterceptor.java, test/codegen-generated-classes-test/src/test/java/software/amazon/awssdk/services/HttpChecksumInHeaderTest.java
Moving checksum calculation from `afterMarshalling` to `modifyHttpRequest` in `HttpChecksumRequiredInterceptor` and `HttpChecksumInHeaderInterceptor`
=> Move checksum calculation from afterMarshalling to modifyHttpRequest

pom.xml, services/s3/src/it/java/software/amazon/awssdk/services/s3/crt/S3CrossRegionCrtIntegrationTest.java, services/s3/src/it/java/software/amazon/awssdk/services/s3/crt/S3CrtClientCopyIntegrationTest.java, services/s3/src/it/java/software/amazon/awssdk/services/s3/crt/S3CrtGetObjectIntegrationTest.java, services/s3/src/it/java/software/amazon/awssdk/services/s3/crt/TestResponseTransformer.java, services/s3/src/main/java/software/amazon/awssdk/services/s3/S3CrtAsyncClientBuilder.java, services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/crt/DefaultS3CrtAsyncClient.java, services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/crt/S3CrtAsyncHttpClient.java, services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/crt/S3InternalSdkHttpExecutionAttribute.java, services/s3/src/test/java/software/amazon/awssdk/services/s3/internal/crt/DefaultS3CrtAsyncClientTest.java
Cross region support for CRT Client
- Api for crossRegionEnabled in Crt client
- Pass AwsSigning Config to crt if SigningRegion is changed
- Integ test for get/put/copy.
=> Cross region support for CRT Client

core/sdk-core/src/main/java/software/amazon/awssdk/core/client/builder/SdkDefaultClientBuilder.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/compression/CompressionType.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/compression/Compressor.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/compression/GzipCompressor.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/interceptor/RequestCompressionInterceptor.java
Adding request compression interceptor to handle compression, and implementing non-streaming compression.
Added CompressionType enum for supported encodings, Compressor interface and GzipCompressor implementation. 
To add tests once streaming compression is implemented.
Was able to send compressed PutMetricData request to CloudWatch successfully
=> Request compression interceptor and non-streaming compression

core/aws-core/src/main/java/software/amazon/awssdk/awscore/AwsRequestOverrideConfiguration.java
Address some old TODOs that didn't get addressed in initial [PR](https://github.com/aws/aws-sdk-java-v2/pull/3829/files#diff-64c4b71af1009af4b25f032c5ec51eb1f301192d7c57281f0171590eb591b1d6)
The Builder interface had a `credentialsProvider()` accessor method which doesn't make sense for a Builder. But since it is `@SdkPublicApi` that one cannot be removed. However, removing the newly added `credentialsIdentityProvider()` and instead using the BuilderImpl in the constructor gives direct access to the private builder.awsCredentialsProvider without an interface accessor method.
Also keeping the same name `credentialsProvider` for the overloaded setter that takes the new type (instead of `credentialsIdentityProvider`. We have followed the same pattern in other places where we accept the …
=> Remove unnecessary AwsRequestOverrideConfiguration.Builder accessor

services/acm/src/main/java/software/amazon/awssdk/services/acm/auth/scheme/internal/DefaultAcmAuthSchemeProvider.java
This was changed to SIGNING_CLOCK recently, which is optional.
Remove REQUEST_SIGNING_INSTANT from DefaultAcmAuthSchemeProvider
AwsCertificateManagerIntegrationTest passes.
=> Remove REQUEST_SIGNING_INSTANT from DefaultAcmAuthSchemeProvider

core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/http/pipeline/stages/SigningStage.java
The SRA logic to sign should be skipped when the selected auth scheme after auth resolution is the schemeId that represents no authentication.
Add condition to check for smithy.api#noAuth
=> Skip signing for smithy.api#noAuth

.changes/next-release/feature-AWSSDKforJavav2-5e523a4.json, core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/async/ByteBuffersAsyncRequestBody.java, core/sdk-core/src/test/java/software/amazon/awssdk/core/internal/async/ByteBuffersAsyncRequestBodyTest.java
Removes guards put in place on https://github.com/aws/aws-sdk-java-v2/pull/3925 to ensure off-heap buffers were copied to on-heap.
This change to the code enables off-heap buffers to be published directly allowing improved performance zero-copy transfers.
see: https://github.com/aws/aws-sdk-java-v2/issues/3928
This change is effectively running in my own production code where I upload files via [MappedByteBuffer](https://docs.oracle.com/javase/8/docs/api/java/nio/MappedByteBuffer.html), when performance testing I was able to achieve a 25% performance improvement over `TransferManager` uploading a 1GB file.
Removes a condition in `ByteBuffersAsyncRequestBody` that converts a direct (off-heap) buffer to a non-direct (on-heap) buffer.
The functionality is covered by existing tests, I've only …
=> Enable zero-copy ByteBuffer publishing in AsyncRequestBody "unsafe" constructors

services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/crt/CopyObjectHelper.java, services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/crt/RequestConversionUtils.java, services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/crt/UploadPartCopyRequestIterable.java, services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/multipart/MultipartUploadHelper.java, services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/multipart/SdkPojoConversionUtils.java, services/s3/src/test/java/software/amazon/awssdk/services/s3/internal/crt/RequestConversionUtilsTest.java, services/s3/src/test/java/software/amazon/awssdk/services/s3/internal/multipart/MultipartUploadHelperTest.java, services/s3/src/test/java/software/amazon/awssdk/services/s3/internal/multipart/SdkPojoConversionUtilsTest.java
Instead of setting each field manually, this change updates RequestConvertionUtils class to iterate SdkFields and set common fields automatically
=> Iterate SdkFields to convert requests

services/s3/src/it/java/software/amazon/awssdk/services/s3/multipart/S3ClientMultiPartCopyIntegrationTest.java, services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/crt/DefaultS3CrtAsyncClient.java, services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/multipart/CopyObjectHelper.java, services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/multipart/MultipartS3AsyncClient.java, services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/multipart/SdkPojoConversionUtils.java, services/s3/src/test/java/software/amazon/awssdk/services/s3/internal/crt/CopyObjectHelperTest.java
Implement multipart copy in Java-based S3 async client
=> Implement multipart copy in Java-based S3 async client

services/eventbridge/src/main/resources/codegen-resources/customization.config, services/s3/src/main/resources/codegen-resources/customization.config
S3 and EventBridge services are the only 2 services which will use endpoint based auth scheme resolution.
The codegen changes to support these cases are already in the feature branch. This PR adds the customization.config needed for s3 and eventbridge. For eventbridge - only EndpointId param is allowlisted. For s3 - no explicit allowlist enables all s3's params to be used for auth scheme resolution.
Built the s3 and eventbridge modules and here is the generated AuthSchemeProvider for each.
<details> 
<summary>
S3
</summary>
<p>
```
@Generated("software.amazon.awssdk:codegen")
@SdkInternalApi
public final class DefaultS3AuthSchemeProvider implements S3AuthSchemeProvider {
private static final DefaultS3AuthSchemeProvider DEFAULT = new DefaultS3AuthSchemeProvider();
private static final …
```
=> Add endpoint based auth scheme customization for s3, eventbridge

core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/http/pipeline/stages/AsyncSigningStage.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/http/pipeline/stages/SigningStage.java
Add SRA signing logic to AsyncSigningStage. SigingStage logic was added in [#4111](https://github.com/aws/aws-sdk-java-v2/pull/4111/files#diff-d42322e3fc21746722508844b8868872976da81f4db212d0f60212d36c37b395)
* Call sign v/s signAsync appropriately
Manual testing:
* Used Glacier's uploadArchive as example API that has a streaming API. So the AsyncClient would use AsyncRequestBody to test signAsync. Similar to https://github.com/aws/aws-sdk-java-v2/pull/4111, hand edited the code generated Glacier files and added a GlacierAuthSchemeInterceptor. Wrote an integ test based on https://github.com/awsdocs/aws-doc-sdk-examples/blob/main/javav2/example_code/glacier/src/main/java/com/example/glacier/UploadArchive.java and verified via debugger that it uses SRA logic and call succeeds.
* Another …
=> Handle sign/signAsync in AsyncSigningStage

utils/src/test/java/software/amazon/awssdk/utils/async/SimplePublisherTest.java
Before this change, a producer in the test would not wait for all other producers to finish sending their messages before calling complete(). Because a producer could end up calling complete() before the other publishers finished sending, the test would see those "trailing" messages after the complete() as having been dropped. To fix this, we now wait to call complete() until all producers have finished writing their messages.
=> Fix flaky test: SimplePublisherTest#stochastic_onNext_multiProducerSeemsThreadSafe

core/sdk-core/src/test/java/software/amazon/awssdk/core/internal/async/SplittingPublisherTest.java, services/s3/src/it/java/software/amazon/awssdk/services/s3/crt/S3CrossRegionCrtIntegrationTest.java, services/s3/src/it/java/software/amazon/awssdk/services/s3/multipart/S3ClientMultiPartCopyIntegrationTest.java, services/s3/src/it/java/software/amazon/awssdk/services/s3/multipart/S3MultipartClientPutObjectIntegrationTest.java
- Add more tests with ByteArrayAsyncRequestBody
- Remove TODO in test
=> Add more tests with ByteArrayAsyncRequestBody

core/http-auth-spi/src/main/java/software/amazon/awssdk/http/auth/spi/AuthSchemeOption.java, core/http-auth-spi/src/main/java/software/amazon/awssdk/http/auth/spi/internal/DefaultAuthSchemeOption.java, core/http-auth-spi/src/test/java/software/amazon/awssdk/http/auth/spi/AuthSchemeOptionTest.java
If someone wants to provide their own AuthSchemeProvider that decorates the default one, they may need to mutate the properties of an AuthSchemeOption.
This change adds a ToCopyableBuilder to AuthSchemeOption to allow creating modified copy.
=> Add ToCopyableBuilder to AuthSchemeOption

core/identity-spi/src/test/java/software/amazon/awssdk/identity/spi/ResolveIdentityRequestTest.java
When adding tests for similar case in https://github.com/aws/aws-sdk-java-v2/pull/4208 realized I could add a similar test to existing ResolveIdentityRequestTest.
Added a unit test
Tests pass
=> Add test to assert old properties are retained during copy

http-clients/url-connection-client/src/main/java/software/amazon/awssdk/http/urlconnection/UrlConnectionHttpClient.java, http-clients/url-connection-client/src/test/java/software/amazon/awssdk/http/urlconnection/UrlConnectionHttpClientWireMockTest.java
Enable chunked encoding in URLConnection HTTP Client.
`setRequestProperty("Transfer-Encoding", "chunked")` does not have any effect
`setChunkedStreamingMode(-1)` when `Transfer-Encoding:chunked` is present, which will [prompt HttpURLConnection to use the default chunklen value](https://docs.oracle.com/javase/8/docs/api/java/net/HttpURLConnection.html#setChunkedStreamingMode-int-) and enable chunked encoding
To uncomment integ test from [Apache fix PR](https://github.com/aws/aws-sdk-java-v2/pull/4198/commits/9dec1a8d95ad13f087dcdfc5bdd24d2161316001#diff-decc1ffb0a2cfcfc59f6e9d52a961f670d2c442fb62ef8de718b5dfac66e293eR121) once merged
=> Enable UrlConnection http client chunked encoding

core/sdk-core/src/main/java/software/amazon/awssdk/core/async/AsyncRequestBody.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/async/AsyncRequestBodySplitConfiguration.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/async/SplittingPublisher.java, core/sdk-core/src/test/java/software/amazon/awssdk/core/async/AsyncRequestBodyConfigurationTest.java, core/sdk-core/src/test/java/software/amazon/awssdk/core/async/AsyncRequestBodyTest.java, core/sdk-core/src/test/java/software/amazon/awssdk/core/internal/async/SplittingPublisherTest.java, services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/multipart/UploadWithKnownContentLengthHelper.java, services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/multipart/UploadWithUnknownContentLengthHelper.java
In the API surface area review meeting, we decided to create a wrapper class for split settings since it's more flexible to add more settings in the future.
Create a configuration class for `SdkPublisher#split`
=> Create a configuration class for SdkPublisher#split

core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/async/SplittingPublisher.java
When a retry attempt is made, DownstreamBody can be re-subscribed to leaving a confusing error. This change makes the error more obvious.
Add a flag that keep tracks if the DownstreamBody has a subscription or not.
=> Guard against re-subscription in SplittingPublisher

core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/http/pipeline/stages/AsyncSigningStage.java
It's a false positive bug, since signedRequest.payload() is immutable, but this avoids SonarCloud considering it as a bug. See https://github.com/aws/aws-sdk-java-v2/pull/4245#discussion_r1283488591.
Extract an `Optional` variable and use it instead of getting the reference again.
=> Avoid sonar reported bug related to Optional use

core/aws-core/src/main/java/software/amazon/awssdk/awscore/util/SignerOverrideUtils.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/http/pipeline/stages/AsyncSigningStage.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/http/pipeline/stages/SigningStage.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/http/pipeline/stages/utils/SignerOverrideUtils.java, core/sdk-core/src/test/java/software/amazon/awssdk/core/internal/http/pipeline/stages/AsyncSigningStageTest.java, core/sdk-core/src/test/java/software/amazon/awssdk/core/internal/http/pipeline/stages/SigningStageTest.java, test/codegen-generated-classes-test/src/test/java/software/amazon/awssdk/services/AsyncSignerOverrideTest.java, test/codegen-generated-classes-test/src/test/java/software/amazon/awssdk/services/ProfileFileConfigurationTest.java, test/codegen-generated-classes-test/src/test/java/software/amazon/awssdk/services/protocolrestjson/AsyncOperationCancelTest.java
Pre SRA, customer can provide their own Signer. This will be deprecated with SRA, where customer can provide their own HttpSigner (new interface) via configuring AuthScheme. But for customers that are still using the old approach, it needs to continue to work and override the signer setup via new SRA code.
To support old signer override, leaving the previous signer logic in (Async)SigningStage as is and branching to it, if signer is overridden.
Currently, signer is considered overridden in 2 cases: 1. by customer specifiying signer explicitly, 2. but also via older codegen that used different signer for certain operations than the client's default signer for cases like event streaming , etc. In subsequent PRs, with SRA, these operations specific signer overrides will go away, so …
=> Use old SigningStage logic if Signer is overridden

codegen/src/main/java/software/amazon/awssdk/codegen/poet/auth/scheme/AuthSchemeSpecUtils.java, codegen/src/main/java/software/amazon/awssdk/codegen/poet/builder/BaseClientBuilderClass.java, codegen/src/test/java/software/amazon/awssdk/codegen/poet/builder/BuilderClassTest.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/builder/test-bearer-auth-client-builder-class.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/builder/test-client-builder-class.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/builder/test-client-builder-endpoints-auth-params.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/builder/test-query-client-builder-class.java, core/http-auth/src/main/java/software/amazon/awssdk/http/auth/AwsV4aAuthScheme.java
`Sigv4a` is a supported auth scheme for endpoints but not directly modeled. This change adds it if the auth params from endpoints param switch is enabled.
**Note** The scheme currently does not exist but in the CRT package, this change just adds the scheme and the changes to the base client builder, subsequent changes will implement the signer that will dynamically load the required classes as currently done as [`SignerLoader`](https://github.com/aws/aws-sdk-java-v2/blob/efb5655f19cd7dbbbf6f4b5b141c94aaf59abe19/core/auth/src/main/java/software/amazon/awssdk/auth/signer/SignerLoader.java#L30) currently does.
For S3 the generated code in the base client will look like:
```java
private Map<String, AuthScheme<?>> defaultAuthSchemes() {
AwsV4AuthScheme awsV4AuthScheme = …
```
=> Add sigv4a for services that have enabled endpoint based auth params

core/aws-core/src/main/java/software/amazon/awssdk/awscore/AwsServiceClientConfiguration.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/SdkServiceClientConfiguration.java
This allows older client versions to still compile with newer runtime versions.
=> Add default methods to AwsServiceClientConfiguration.Builder and SdkServiceClientConfiguration.Builder

.changes/next-release/feature-AmazonS3-318ca43.json, services/s3/src/it/java/software/amazon/awssdk/services/s3/crt/S3CrtClientPutObjectIntegrationTest.java, services/s3/src/main/java/software/amazon/awssdk/services/s3/S3CrtAsyncClientBuilder.java, services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/crt/DefaultS3CrtAsyncClient.java, services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/crt/S3CrtAsyncHttpClient.java, services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/crt/S3NativeClientConfiguration.java, services/s3/src/test/java/software/amazon/awssdk/services/s3/internal/crt/S3CrtAsyncHttpClientTest.java
Allow users to configure upload threshold size for AWS CRT-based S3 client via `S3CrtAsyncClientBuilder#thresholdInBytes`
Expose thresholdSizeInBytes in AWS CRT-based S3 client builder
Added tests
=> Expose thresholdSizeInBytes in AWS CRT-based S3 client

codegen/src/main/java/software/amazon/awssdk/codegen/IntermediateModelBuilder.java, codegen/src/main/java/software/amazon/awssdk/codegen/model/intermediate/IntermediateModel.java, codegen/src/main/java/software/amazon/awssdk/codegen/model/intermediate/ShapeModel.java, codegen/src/main/java/software/amazon/awssdk/codegen/poet/client/AsyncClientClass.java, codegen/src/main/java/software/amazon/awssdk/codegen/poet/client/ClientClassUtils.java, codegen/src/main/java/software/amazon/awssdk/codegen/poet/client/SyncClientClass.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/test-aws-json-async-client-class.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/test-json-async-client-class.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/test-json-client-class.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/test-query-async-client-class.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/test-query-client-class.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/test-xml-async-client-class.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/test-xml-client-class.java
Currently, `Client`s are setup with a default signer, which is overridden for certain operations:
* unsigned payload
* event streaming
* async v4 streaming 
* have different authType than service.
With SRA, we do not have separate signers, the AwsV4HttpSigner interface supports all the sigv4 use cases, so this type of signer override is not needed in generated clients. And different authType than service (e.g., bearerToken, as opposed to sigv4) is supported by AuthSchemeProvider logic which is operation aware.
Note, customer can still override the default `Signer` at the client/request level, which will result in SIGNER_OVERRIDDEN=true, and that will continue to be supported at that's a public interface (but will be marked deprecated) and old clients may still use it. This PR just takes …
=> Remove SignerOverride related codegen logic

.changes/next-release/bugfix-AWSSDKforJavav2-5ae7899.json, utils/src/main/java/software/amazon/awssdk/utils/BinaryUtils.java, utils/src/test/java/software/amazon/awssdk/utils/BinaryUtilsTest.java
Limit is not copied over when cloning ByteBuffer using `BinaryUtils.immutableCopyOf()`
https://github.com/aws/aws-sdk-java-v2/issues/4166
=> Fix immutableCopyOf bug

.changes/next-release/bugfix-AWSDynamoDBEnhancedClient-8706d14.json, services-custom/dynamodb-enhanced/src/main/java/software/amazon/awssdk/enhanced/dynamodb/internal/document/JsonStringFormatHelper.java, services-custom/dynamodb-enhanced/src/test/java/software/amazon/awssdk/enhanced/dynamodb/document/EnhancedDocumentTest.java
Fix for Issue [#4156](https://github.com/aws/aws-sdk-java-v2/issues/4156) : Single quotes in toJson conversions for EnhancedDocuments are no longer being escaped.
https://github.com/aws/aws-sdk-java-v2/issues/4156
- The single quotes should not be escaped.
- Tested the behavior in V1 and confirmed single quotes not escaped
- Added Junits with ObjectMapper to test valid Jsons with escaped characters.
=> Fix for Issue #4156 : Single quotes in toJson conversions for EnhancedDocuments are no longer being escaped.

codegen/src/main/java/software/amazon/awssdk/codegen/model/intermediate/Metadata.java, codegen/src/main/java/software/amazon/awssdk/codegen/poet/builder/BaseClientBuilderClass.java, codegen/src/main/java/software/amazon/awssdk/codegen/poet/client/traits/NoneAuthTypeRequestTrait.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/builder/test-bearer-auth-client-builder-class.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/builder/test-client-builder-class.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/builder/test-client-builder-endpoints-auth-params.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/builder/test-client-builder-internal-defaults-class.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/builder/test-query-client-builder-class.java, test/codegen-generated-classes-test/src/test/java/software/amazon/awssdk/services/bearerauth/ClientBuilderTest.java
Currently, Clients are setup with a default `Signer`. With SRA, the new signer interface HttpSigner is used and these signers are configured via AuthSchemes, which is already added to generated clients. So removing codegen to setup default `Signer.
Related: In #4280 setting up Signer overrides was already removed.
Note, customer can still provide old `Signer` at the client/request level, which will result in SIGNER_OVERRIDDEN=true, and that will continue to be supported at that's a public interface (but will be marked deprecated).
This PR deletes codegen logic to _write_ the default signer into clients. Logic to _read_ the default signer is in aws-core (AwsExecutionContextBuilder, AuthorizationStrategy, SigningStage, etc.) which needs to remain to support old clients as well as customer …
=> Remove Signer related codegen logic in Clients

codegen/src/main/java/software/amazon/awssdk/codegen/poet/auth/scheme/AuthSchemeCodegenMetadata.java, codegen/src/main/java/software/amazon/awssdk/codegen/poet/auth/scheme/ModelBasedAuthSchemeProviderSpec.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/auth/scheme/granular-auth-scheme-default-provider.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/c2j/fine-grained-auth/service-2.json
`v4-unsigned-body` auth type was not properly setting the correct signer properties, in particular setting `PAYLOAD_SIGNING_ENABLED` to `false`.
For S3 the `ModeledS3AuthSchemeProvider#resolveAuthScheme` looks like this after this change:
```java
@Override
public List<AuthSchemeOption> resolveAuthScheme(S3AuthSchemeParams params) {
List<AuthSchemeOption> options = new ArrayList<>();
switch (params.operation()) {
case "WriteGetObjectResponse":
options.add(AuthSchemeOption.builder().schemeId("aws.auth#sigv4")
.putSignerProperty(AwsV4HttpSigner.SERVICE_SIGNING_NAME, "s3")
.putSignerProperty(AwsV4HttpSigner.REGION_NAME, params.region().id())
.putSignerProperty(AwsV4HttpSigner.PAYLOAD_SIGNING_ENABLED, false).build());
break;
default:
options.add(AuthSchemeOption.builder().schemeId("aws.auth#sig …
```
=> Set the correct signer properties for v4-unsigned-body

codegen/src/main/java/software/amazon/awssdk/codegen/poet/client/traits/RequestCompressionTrait.java, core/auth/src/main/java/software/amazon/awssdk/auth/signer/internal/chunkedencoding/AwsSignedChunkedEncodingInputStream.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/http/pipeline/stages/CompressRequestStage.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/io/AwsChunkedEncodingInputStream.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/io/AwsChunkedInputStream.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/io/AwsCompressionInputStream.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/io/UnderlyingStreamBuffer.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/sync/CompressionContentStreamProvider.java, core/sdk-core/src/test/java/software/amazon/awssdk/core/internal/io/AwsCompressionInputStreamTest.java, services/mediastoredata/pom.xml, services/mediastoredata/src/it/java/software/amazon/awssdk/services/mediastoredata/MediaStoreDataIntegrationTestBase.java, services/mediastoredata/src/it/java/software/amazon/awssdk/services/mediastoredata/RequestCompressionStreamingIntegrationTest.java, services/mediastoredata/src/it/java/software/amazon/awssdk/services/mediastoredata/TransferEncodingChunkedIntegrationTest.java, services/mediastoredata/src/it/resources/log4j2.properties, test/codegen-generated-classes-test/src/main/resources/codegen-resources/customresponsemetadata/service-2.json, test/codegen-generated-classes-test/src/test/java/software/amazon/awssdk/services/RequestCompressionTest.java
Implementing sync streaming compression
The `ContentStreamProvider` of the original `RequestBody` will be wrapped by `CompressionContentStreamProvider`, which will wrap the underlying `InputStream` with `AwsCompressionInputStream`. The `AwsCompressionInputStream` overrides `read(byte[] b, int off, int len)` to return compressed chunks.
Cleaned up and added to [previous PR](https://github.com/aws/aws-sdk-java-v2/pull/4135)
added functional and integ tests
=> Request compression sync streaming

codegen/src/main/java/software/amazon/awssdk/codegen/docs/OperationDocProvider.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/test-json-async-client-interface.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/test-json-client-interface.java
Javadoc links are broken for Consumer operations `@param` when the model input shape has the suffix `Input`
Example: https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/services/cloudwatch/CloudWatchClient.html#putMetricData(software.amazon.awssdk.services.cloudwatch.model.PutMetricDataRequest)
All request objects in the SDK have the `Request` suffix. If it is `Input` in the model, it is overridden [here
](https://github.com/aws/aws-sdk-java-v2/blob/master/codegen/src/main/java/software/amazon/awssdk/codegen/naming/DefaultNamingStrategy.java#L229)
Update codedgen to replace `getC2jName` with `getShapeName` when generating javadocs
=> Fix javadocs links - consumer request objects

release-scripts/src/main/java/software/amazon/awssdk/release/Cli.java, release-scripts/src/main/java/software/amazon/awssdk/release/CreateNewServiceModuleMain.java, release-scripts/src/main/java/software/amazon/awssdk/release/NewServiceMain.java
After adding the new `http-auth-aws` dependency this is needed by almost all but one service, codecatalyst which uses an bearer auth scheme and thus does not need to depend on this package. To bootstrap new services that might also need to opt-out of pulling this dependency this change adds to the commands
* `software.amazon.awssdk.release.CreateNewServiceModuleMain`
* `software.amazon.awssdk.release.NewServiceMain`
New, multivalued switches that can be used to either remove default dependencies or to add unlisted ones.
* `include-internal-dependency`
* `exclude-internal-dependency`
By default the default internal dependencies will be added:
```
./mvnw exec:java -pl :release-scripts -Dexec.mainClass="software.amazon.awssdk.release.CreateNewServiceModuleMain" \ …
```
=> Add new exclude/include to augment the created service pom

core/auth/src/main/java/software/amazon/awssdk/auth/credentials/internal/SystemSettingsCredentialsProvider.java, core/auth/src/test/java/software/amazon/awssdk/auth/credentials/SystemSettingCredentialsProvidersTest.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/SdkSystemSetting.java
Adds the capability to source account ID from environment variables and system properties. 
Adds a new system setting for account ID
=> Adding accountId support to environment variable credential provider

.changes/next-release/bugfix-AWSSDKforJavav2DynamoDbEnhanced-05cdcee.json, services-custom/dynamodb-enhanced/src/main/java/software/amazon/awssdk/enhanced/dynamodb/extensions/AtomicCounterExtension.java, services-custom/dynamodb-enhanced/src/test/java/software/amazon/awssdk/enhanced/dynamodb/extensions/AtomicCounterExtensionTest.java, services-custom/dynamodb-enhanced/src/test/java/software/amazon/awssdk/enhanced/dynamodb/functionaltests/AtomicCounterTest.java
The initial implementation of the atomic counter extension made the assumption that it was not necessary to modify the item itself while adding an update expression, because users should not include attributes that were tagged as an atomic counter in the item to be updated and if they did, they would get an error back. 
For instance, if attribute `accessCounter` of the class `Balance` was marked with the `AtomicCounter` attribute, this would result in an error:
~~~
Balance balanceToUpdate = new Balance();
balanceToUpdate.accessCounter(4);
table.updateItem(balanceToUpdate);
~~~
Which makes sense since `accessCounter` will be updated anyway in the `AtomicCounterExtension`, and the assumption was that an error is better than silently changing the item when `updateItem` was called. This …
=> Changes default behavior for DynamoDb Enhanced atomic counter extension

codegen/src/test/resources/software/amazon/awssdk/codegen/poet/auth/scheme/query-endpoint-auth-params-auth-scheme-default-params-without-allowlist.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/auth/scheme/query-endpoint-auth-params-auth-scheme-endpoint-provider-without-allowlist.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/auth/scheme/query-endpoint-auth-params-auth-scheme-params-without-allowlist.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/auth/scheme/query-endpoint-auth-params-without-allowlist-auth-scheme-interceptor.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/rules/endpoint-parameters.java, core/auth/src/main/java/software/amazon/awssdk/auth/credentials/ProcessCredentialsProvider.java, core/auth/src/test/java/software/amazon/awssdk/auth/credentials/ProcessCredentialsProviderTest.java, core/auth/src/test/resources/resources/process/linux-credentials-script.sh, core/auth/src/test/resources/resources/process/windows-credentials-script.bat
Adds accountId support to process credentials provider
- Process credentials provider attempts to read accountId from the JSON file and add to credentials
- Adds expiration time to the credentials as well since it's now supported
- Modifies the test scripts that produce different JSON files so they can handle an arbitrary number of optional arguments, with expiration, session token and accountId being named.
=> Adds accountId support to process credentials provider

core/auth/src/main/java/software/amazon/awssdk/auth/credentials/ProcessCredentialsProvider.java, core/auth/src/main/java/software/amazon/awssdk/auth/credentials/internal/ProfileCredentialsUtils.java, core/auth/src/test/java/software/amazon/awssdk/auth/credentials/ProcessCredentialsProviderTest.java, core/auth/src/test/java/software/amazon/awssdk/auth/credentials/ProfileCredentialsProviderTest.java, core/auth/src/test/java/software/amazon/awssdk/auth/credentials/StaticCredentialsProviderTest.java, core/auth/src/test/java/software/amazon/awssdk/auth/credentials/internal/ProfileCredentialsUtilsTest.java, core/profiles/src/main/java/software/amazon/awssdk/profiles/ProfileProperty.java, core/profiles/src/test/java/software/amazon/awssdk/profiles/ProfileFileSupplierTest.java
Adds support for account ID to profile credentials provider
- Adds a profile property for account ID
- Attempts to retrieve account ID from config and credential files if it exists
- Adds the capability to manually configure account ID to process credentials provider
=> Adds account ID support for profile credentials provider sources

test/codegen-generated-classes-test/src/test/java/software/amazon/awssdk/services/metrics/async/BaseAsyncCoreMetricsTest.java, test/codegen-generated-classes-test/src/test/java/software/amazon/awssdk/services/testutil/MockIdentityProviderUtil.java
Also make the mock identity provider in codegen-generated-classes-test lenient, so we don't have to use every resolveIdentity method type.
=> Temporarily disable tests that were broken by a missing metric.

codegen/src/main/java/software/amazon/awssdk/codegen/poet/rules/EndpointResolverInterceptorSpec.java, codegen/src/main/resources/software/amazon/awssdk/codegen/rules/AuthSchemeUtils.java.resource, codegen/src/main/resources/software/amazon/awssdk/codegen/rules/AwsEndpointProviderUtils.java.resource, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/rules/endpoint-resolve-interceptor.java, services/codecatalyst/pom.xml, test/codegen-generated-classes-test/src/test/java/software/amazon/awssdk/services/endpointproviders/AuthSchemeUtilsTest.java, test/codegen-generated-classes-test/src/test/java/software/amazon/awssdk/services/endpointproviders/EndpointInterceptorTests.java
Previously (#4311), AwsEndpointProviderUtils and AuthSchemeUtils, which are copied into every client, depend on classes from http-auth-aws. As a result, every client needed a dependency on http-auth-aws. With this change, we move the methods from those classes that depend on http-auth-aws to be code generated within only the clients that need them.
=> Remove dependency on http-auth-aws from codecatalyst.

utils/src/main/java/software/amazon/awssdk/utils/DateUtils.java, utils/src/test/java/software/amazon/awssdk/utils/DateUtilsTest.java
=> Limit timestamp string length

core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/async/CompressionAsyncRequestBody.java
Refactor `CompressionAsyncRequestBody` to use [`AddingTrailingDataSubscriber`](https://github.com/aws/aws-sdk-java-v2/pull/4366/) and remove duplicate logic
Replace existing logic to send buffered data with `addTrailingData()`
All current tests pass
=> Refactor to use AddingTrailingDataSubscriber

buildspecs/update-master-from-release.yml
`UpdateGithubMasterv2` fails silently when connection reset occurs during `mvn versions:set` , leading to failed `release-automation-v2` the following day
Add error handling to fail build if error occurs
=> Fail UpdateGitHubMasterv2 if error occurs

.changes/next-release/bugfix-AWSSDKforJavav2-85d899c.json, core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/http/async/CombinedResponseAsyncHttpResponseHandler.java, test/protocol-tests/src/test/java/software/amazon/awssdk/protocol/tests/AsyncFaultTest.java
#4354 #3335 
If there is a server error and the server fails to return response body that matches with the content length specified in the response header, the response future will get stuck. This is because we are not invoking onError for errorResponseHandler that is supposed to fail the return future.
Invoke `errorResponseHandler#onError` when onError is invoked.
Added functional test
=> Fixed an issue in async client causing resposne future to get stuck

core/http-auth-spi/src/main/java/software/amazon/awssdk/http/auth/spi/AuthSchemeOption.java, core/http-auth-spi/src/main/java/software/amazon/awssdk/http/auth/spi/internal/DefaultAuthSchemeOption.java
These are follow up changes for AuthSchemeOption from the surface area review. 
The topics for potential changes included:
* Do we need the forEach*Property methods instead of returning the Collection/Iterable?
* Removing `<T>` from forEach*Property method declaration
I worked on a few options and discussed with Dongie, but couldn't come up with better alternatives, so have kept things as-is for the above. While making the other changes listed below.
* Make AuthSchemeOption SdkPublicApi
* Add SuppressWarning for unchecked casts
* Add javadocs and some comments explaining not intuitive use of <T>
=> AuthSchemeOption changes based on surface review

.changes/next-release/bugfix-AWSSDKforJavav2-72bd387.json, services-custom/iam-policy-builder/src/main/java/software/amazon/awssdk/policybuilder/iam/internal/DefaultIamPolicyReader.java, services-custom/iam-policy-builder/src/test/java/software/amazon/awssdk/policybuilder/iam/IamPolicyReaderTest.java
The [IamPolicy](https://github.com/aws/aws-sdk-java-v2/blob/master/services-custom/iam-policy-builder/src/main/java/software/amazon/awssdk/policybuilder/iam/IamPolicy.java) class represents an IAM policy. You can serialize/deserialize this class to json. A principal is represented as a type/value in [IamPrincipal](https://github.com/aws/aws-sdk-java-v2/blob/master/services-custom/iam-policy-builder/src/main/java/software/amazon/awssdk/policybuilder/iam/IamPrincipal.java). 
If you have a principal of for instance "AWS" and it contains more than one value, you can create it by doing
`IamPrincipal.createAll("AWS", asList("arn1", "arn2"))`, which yields a list of `IamPrincipal` with the same type and the two different values. When reading from json, the principal is correctly interpreted if …
=> Allow IamPolicy to read json policies where the principal value itself an array

.changes/next-release/feature-AmazonDynamoDBEnhancedClient-ee18d70.json, services-custom/dynamodb-enhanced/src/main/java/software/amazon/awssdk/enhanced/dynamodb/internal/operations/BatchGetItemOperation.java, services-custom/dynamodb-enhanced/src/main/java/software/amazon/awssdk/enhanced/dynamodb/model/BatchGetItemEnhancedRequest.java, services-custom/dynamodb-enhanced/src/main/java/software/amazon/awssdk/enhanced/dynamodb/model/BatchGetResultPage.java, services-custom/dynamodb-enhanced/src/test/java/software/amazon/awssdk/enhanced/dynamodb/functionaltests/AsyncBatchGetItemTest.java, services-custom/dynamodb-enhanced/src/test/java/software/amazon/awssdk/enhanced/dynamodb/functionaltests/BatchGetItemTest.java, services-custom/dynamodb-enhanced/src/test/java/software/amazon/awssdk/enhanced/dynamodb/model/BatchGetItemEnhancedRequestTest.java
Add ReturnConsumedCapacity to BatchGetItemEnhancedRequest so callers can determine exactly how much RCUs BatchGetItem request consumed. 
Related to feature request https://github.com/aws/aws-sdk-java-v2/issues/4372
1. Add `returnConsumedCapacity` to `BatchGetItemEnhancedRequest`
2. Changes to `BatchGetItemOperation` to honor `returnConsumedCapacity` 
3. Unit and functional tests to verify the new param
Added new unit and functional tests, and ran them succcesfully
`./mvnw clean install -pl :dynamodb-enhanced  --am`
N/A
=> Add ReturnConsumedCapacity to BatchGetItemEnhancedRequest

core/http-auth-aws/src/main/java/software/amazon/awssdk/http/auth/aws/AwsV4FamilyHttpSigner.java, core/http-auth-aws/src/main/java/software/amazon/awssdk/http/auth/aws/AwsV4HttpSigner.java, core/http-auth-aws/src/main/java/software/amazon/awssdk/http/auth/aws/AwsV4aHttpSigner.java, core/http-auth-aws/src/main/java/software/amazon/awssdk/http/auth/aws/crt/internal/signer/AwsChunkedV4aPayloadSigner.java, core/http-auth-aws/src/main/java/software/amazon/awssdk/http/auth/aws/crt/internal/signer/DefaultAwsCrtV4aHttpSigner.java, core/http-auth-aws/src/test/java/software/amazon/awssdk/http/auth/aws/crt/internal/signer/AwsChunkedV4aPayloadSignerTest.java, core/http-auth-aws/src/test/java/software/amazon/awssdk/http/auth/aws/crt/internal/signer/DefaultAwsCrtV4aHttpSignerTest.java, core/http-auth-aws/src/test/java/software/amazon/awssdk/http/auth/aws/internal/signer/AwsChunkedV4PayloadSignerTest.java
- Almost entirely the same as #4383, but for CRT case
- Dependent on #4403
- Add common property, `CHECKSUM_ALGORITHM`
- Update `AwsChunkedV4aPayloadSigner` to use flexible checksums
- Add tests to cover checksums and trailer cases
- Run new and existing tests, make sure pass
- [] I have updated the Javadoc documentation accordingly
=> Add flexible checksums to chunk-encoding in CRT

core/http-auth-aws/src/main/java/software/amazon/awssdk/http/auth/aws/AwsV4AuthScheme.java, core/http-auth-aws/src/main/java/software/amazon/awssdk/http/auth/aws/AwsV4aAuthScheme.java, core/http-auth-aws/src/main/java/software/amazon/awssdk/http/auth/aws/internal/DefaultAwsV4AuthScheme.java, core/http-auth-aws/src/main/java/software/amazon/awssdk/http/auth/aws/internal/DefaultAwsV4aAuthScheme.java, core/http-auth-spi/src/main/java/software/amazon/awssdk/http/auth/spi/AuthScheme.java, core/http-auth/src/main/java/software/amazon/awssdk/http/auth/BearerAuthScheme.java, core/http-auth/src/main/java/software/amazon/awssdk/http/auth/NoAuthAuthScheme.java, core/http-auth/src/main/java/software/amazon/awssdk/http/auth/internal/DefaultBearerAuthScheme.java, core/http-auth/src/main/java/software/amazon/awssdk/http/auth/internal/DefaultNoAuthAuthScheme.java
Instead of anonymous inner classes.
Add auth scheme default impl classes instead of anonymous inner classes.
Note https://github.com/aws/aws-sdk-java-v2/pull/4416/commits/5c170777e1a125317afbe9acbb104f5cabf532d8 which creates sigv4a signer instance lazily as that depends on optional dependency http-auth-aws-crt. Whereas other signer instance are created eagerly in static block in AuthScheme impls.
s3-transfer-manager was failing earlier because of eager loading of crt signer. fixed with lazy loading.
=> Add auth scheme default impl classes

.brazil.json, bom/pom.xml, core/http-auth-aws-eventstream/pom.xml, core/http-auth-aws-eventstream/src/main/java/software/amazon/awssdk/http/auth/aws/eventstream/HttpAuthAwsEventStream.java, core/http-auth-aws/pom.xml, core/http-auth-aws/src/main/java/software/amazon/awssdk/http/auth/aws/internal/util/OptionalDependencyLoaderUtil.java, core/http-auth-aws/src/test/java/software/amazon/awssdk/http/auth/aws/internal/signer/DefaultAwsV4HttpSignerTest.java, core/pom.xml, test/tests-coverage-reporting/pom.xml
We are currently using `software.amazon.awssdk.http.auth.aws.eventstream` as the java package name and the module name is `http-auth-aws-event-stream`. The event stream dependency is:
```
<groupId>software.amazon.eventstream</groupId>
<artifactId>eventstream</artifactId>
```
in repo https://github.com/awslabs/aws-eventstream-java/.
So renaming the module to http-auth-aws-eventstream to be consistent with other usage.
Rename http-auth-aws-event-stream module to http-auth-aws-eventstream #4436 
CI rebuild
=> Rename http-auth-aws-event-stream module to http-auth-aws-eventstream

.changes/next-release/bugfix-AWSSDKforJavav2-750825c.json, core/auth-crt/src/main/java/software/amazon/awssdk/authcrt/signer/internal/SigningConfigProvider.java, services/s3control/src/it/java/software.amazon.awssdk.services.s3control/S3MrapIntegrationTest.java
When the Sigv4a signer is used, path normalization is true by default. This causes issues for S3 MRAP usage, where some paths don't work - S3 does not perform path normalization
This bugfix checks the signer attribute to see if it has a value, and chooses that value if it exists. Otherwise, it will fall back to `true`, which is the general Sigv4 setting. S3 and S3 Control always sets the path normalization to `false`.
No unit testing is possible because the normalization is performed in CRT, not in the SDK
Edit: added the path tests to existing integ tests
=> Change config for Sigv4a signing to not perform path normalization

core/http-auth-aws-crt/src/main/java/software/amazon/awssdk/http/auth/aws/crt/HttpAuthAwsCrt.java, core/http-auth-aws-eventstream/src/main/java/software/amazon/awssdk/http/auth/aws/eventstream/HttpAuthAwsEventStream.java, core/http-auth-aws/src/main/java/software/amazon/awssdk/http/auth/aws/crt/internal/signer/AwsChunkedV4aPayloadSigner.java, core/http-auth-aws/src/main/java/software/amazon/awssdk/http/auth/aws/crt/internal/signer/RollingSigner.java, core/http-auth-aws/src/main/java/software/amazon/awssdk/http/auth/aws/crt/internal/signer/SigV4aChunkExtensionProvider.java, core/http-auth-aws/src/main/java/software/amazon/awssdk/http/auth/aws/crt/internal/signer/SigV4aTrailerProvider.java, core/http-auth-aws/src/main/java/software/amazon/awssdk/http/auth/aws/internal/signer/AwsChunkedV4PayloadSigner.java, core/http-auth-aws/src/main/java/software/amazon/awssdk/http/auth/aws/internal/signer/chunkedencoding/ChecksumTrailerProvider.java, core/http-auth-aws/src/main/java/software/amazon/awssdk/http/auth/aws/internal/signer/chunkedencoding/ChunkExtensionProvider.java, core/http-auth-aws/src/main/java/software/amazon/awssdk/http/auth/aws/internal/signer/chunkedencoding/ChunkedEncodedInputStream.java, core/http-auth-aws/src/main/java/software/amazon/awssdk/http/auth/aws/internal/signer/chunkedencoding/Resettable.java, core/http-auth-aws/src/main/java/software/amazon/awssdk/http/auth/aws/internal/signer/chunkedencoding/SigV4ChunkExtensionProvider.java, core/http-auth-aws/src/main/java/software/amazon/awssdk/http/auth/aws/internal/signer/chunkedencoding/SigV4TrailerProvider.java, core/http-auth-aws/src/main/java/software/amazon/awssdk/http/auth/aws/internal/signer/chunkedencoding/TrailerProvider.java, core/http-auth-aws/src/main/java/software/amazon/awssdk/http/auth/aws/internal/signer/io/ResettableContentStreamProvider.java, core/http-auth-aws/src/test/java/software/amazon/awssdk/http/auth/aws/crt/internal/signer/AwsChunkedV4aPayloadSignerTest.java, core/http-auth-aws/src/test/java/software/amazon/awssdk/http/auth/aws/internal/signer/AwsChunkedV4PayloadSignerTest.java
- Fixes a bug where the stream provider returned from signing is not resettable (via `newStream`)
- Refactors some of the chunk-encoding logic so that resetting is possible
- Adds `reset()` implementation to `ChunkedEncodedInputStream`, `mark()` is not supported (and is made clear through `markSupported` returning false)
- Makes signer module classes final
- Run new and existing tests, make sure pass
=> Resettable Chunked Encoding streams and other TODOs

.changes/next-release/bugfix-S3TransferManager-433e16a.json, services-custom/s3-transfer-manager/src/it/java/software/amazon/awssdk/transfer/s3/CaptureTransferListener.java, services-custom/s3-transfer-manager/src/it/java/software/amazon/awssdk/transfer/s3/S3IntegrationTestBase.java, services-custom/s3-transfer-manager/src/it/java/software/amazon/awssdk/transfer/s3/S3TransferManagerCopyIntegrationTest.java, services-custom/s3-transfer-manager/src/it/java/software/amazon/awssdk/transfer/s3/S3TransferManagerDownloadDirectoryIntegrationTest.java, services-custom/s3-transfer-manager/src/it/java/software/amazon/awssdk/transfer/s3/S3TransferManagerDownloadIntegrationTest.java, services-custom/s3-transfer-manager/src/it/java/software/amazon/awssdk/transfer/s3/S3TransferManagerDownloadPauseResumeIntegrationTest.java, services-custom/s3-transfer-manager/src/it/java/software/amazon/awssdk/transfer/s3/S3TransferManagerUploadDirectoryIntegrationTest.java, services-custom/s3-transfer-manager/src/it/java/software/amazon/awssdk/transfer/s3/S3TransferManagerUploadIntegrationTest.java, services-custom/s3-transfer-manager/src/it/java/software/amazon/awssdk/transfer/s3/S3TransferManagerUploadPauseResumeIntegrationTest.java, services-custom/s3-transfer-manager/src/main/java/software/amazon/awssdk/transfer/s3/internal/progress/TransferProgressUpdater.java, services-custom/s3-transfer-manager/src/test/java/software/amazon/awssdk/transfer/s3/internal/TransferProgressUpdaterTest.java
Fixing Java S3 Client Transfer Manager issue with transferComplete() not called for AsyncRequestBody.fromFile
- Fix for issue https://github.com/aws/aws-sdk-java-v2/issues/3839
-
- [NettyRequestExecutor](https://github.com/aws/aws-sdk-java-v2/blob/df4753216daeb119408f7378ec68c3cb1d0824d7/http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/internal/NettyRequestExecutor.java#L496) prematurely cancels the subscription when the last chunk is sent.
- The logic of `shouldContinuePublishing` after [DoneCheck-OnNext](https://github.com/aws/aws-sdk-java-v2/blob/df4753216daeb119408f7378ec68c3cb1d0824d7/http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/internal/NettyRequestExecutor.java#L442) checks `<` instead of `<=` in …
=> Fixing Java S3 Client Transfer Manager issue with transferComplete() not called for AsyncRequestBody.fromFile

core/http-auth-spi/src/main/java/software/amazon/awssdk/http/auth/spi/internal/scheme/DefaultAuthSchemeOption.java, core/http-auth-spi/src/main/java/software/amazon/awssdk/http/auth/spi/scheme/AuthSchemeOption.java
AuthSchemeOption.forEach*Property methods were defined with <T> that is unnecessary. I tried some things earlier and ended up with in https://github.com/aws/aws-sdk-java-v2/pull/4411. But thanks to @millems for this suggestion.
Added a private method for <T> and removed <T> from the interface method. Code got simpler too!
=> Remove unnecessary <T> from forEach*Property methods

core/http-auth-aws/src/main/java/software/amazon/awssdk/http/auth/aws/signer/AwsV4FamilyHttpSigner.java, core/http-auth-aws/src/main/java/software/amazon/awssdk/http/auth/aws/signer/AwsV4HttpSigner.java, core/http-auth-aws/src/main/java/software/amazon/awssdk/http/auth/aws/signer/AwsV4aHttpSigner.java
AwsV4FamilyHttpSigner not being an actual HttpSigner could be confusing. This is a followup from offline discussion of https://github.com/aws/aws-sdk-java-v2/pull/4396#discussion_r1318141230.
* Make AwsV4FamilyHttpSigner extends HttpSigner, but use generic for Identity type, to leave the door open in case another implementation of V4 uses different type.
* Remove extends HttpSigner from the V4 and V4a signers.
=> Make AwsV4FamilyHttpSigner a sub-type of HttpSigner

.changes/next-release/feature-AWSSDKforJavav2-36670dc.json, codegen/src/main/java/software/amazon/awssdk/codegen/AddOperations.java, codegen/src/main/java/software/amazon/awssdk/codegen/model/intermediate/OperationModel.java, codegen/src/main/java/software/amazon/awssdk/codegen/poet/client/specs/JsonProtocolSpec.java, core/protocols/aws-json-protocol/src/main/java/software/amazon/awssdk/protocols/json/internal/marshall/JsonProtocolMarshaller.java, core/protocols/aws-json-protocol/src/main/java/software/amazon/awssdk/protocols/json/internal/unmarshall/JsonProtocolUnmarshaller.java, test/codegen-generated-classes-test/src/main/resources/codegen-resources/customresponsemetadata/service-2.json, test/codegen-generated-classes-test/src/test/java/software/amazon/awssdk/services/protocolrestjson/StringPayloadUnmarshallingTest.java, test/protocol-tests-core/src/main/resources/software/amazon/awssdk/protocol/suites/cases/rest-json-contenttype.json, test/protocol-tests/src/main/resources/codegen-resources/restjson/contenttype/service-2.json, test/protocol-tests/src/main/resources/codegen-resources/restjson/service-2.json, test/protocol-tests/src/test/java/software/amazon/awssdk/protocol/tests/EventTransformTest.java, test/protocol-tests/src/test/java/software/amazon/awssdk/protocol/tests/RestJsonEventStreamProtocolTest.java
To support non-Json String payloads
Update Json marshaller/unmarshaller to support explicit String payloads, including non-Json Strings
=> Support non-Json String payloads

buildspecs/release-javadoc.yml, pom.xml
Use JDK 21 to build javadocs so that we can enable search button
Verified jquery version is up-to-date with JDK 21 https://docs.oracle.com/en/java/javase/21/docs/api/script-dir/jquery-ui.min.js 
Tested locally and verified it worked
=> Use JDK 21 to build javadocs and enable search button

.changes/next-release/bugfix-AmazonSimpleStorageServic-acc4919.json, services/s3/src/it/java/software/amazon/awssdk/services/s3/crossregion/S3CrossRegionIntegrationTestBase.java, services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/crossregion/utils/CrossRegionUtils.java, services/s3/src/test/java/software/amazon/awssdk/services/s3/internal/crossregion/S3CrossRegionAsyncClientRedirectTest.java, services/s3/src/test/java/software/amazon/awssdk/services/s3/internal/crossregion/S3CrossRegionAsyncClientTest.java, services/s3/src/test/java/software/amazon/awssdk/services/s3/internal/crossregion/S3CrossRegionRedirectTestBase.java, services/s3/src/test/java/software/amazon/awssdk/services/s3/internal/crossregion/S3CrossRegionSyncClientRedirectTest.java, services/s3/src/test/java/software/amazon/awssdk/services/s3/internal/crossregion/S3CrossRegionSyncClientTest.java, services/s3/src/test/java/software/amazon/awssdk/services/s3/internal/crossregion/S3DecoratorRedirectTestBase.java
- Cross region feature fails to do Cross region calls when US_EAST_1 as client region and trying to access Bucket which were created in other regions.
- Note that we already had Integ test for this , yet this issue was not reproucible in Integ since we are creating New Buckets in cross regions and testing the US_EAST_1 immediately
- This issue is reproducible only if Buckets existed for a long time more than 48 hour.
- Updated the logic to consider as redirect when we Get AuthorizationHeaderMalformed error.
- When we get AuthorizationHeaderMalformed we will do a HeadBucket Call and AuthorizationHeaderMalformed for HeadBucket always contains x-amz-bucket headers and thus we will get the Cross region bucket
- For any Error if we find x-amzn-bucket-region in the response then this Region …
=> Fix for Cross-region calls failure due to AuthorizationHeaderMalformed errors while using clients with configured region as us-east-1

codegen/src/main/java/software/amazon/awssdk/codegen/poet/auth/scheme/EndpointBasedAuthSchemeProviderSpec.java, codegen/src/main/java/software/amazon/awssdk/codegen/poet/rules/EndpointResolverInterceptorSpec.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/auth/scheme/query-endpoint-auth-params-auth-scheme-endpoint-provider-without-allowlist.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/auth/scheme/query-endpoint-auth-params-auth-scheme-endpoint-provider.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/rules/endpoint-resolve-interceptor.java, core/auth/src/main/java/software/amazon/awssdk/auth/signer/AwsSignerExecutionAttribute.java, core/auth/src/test/java/software/amazon/awssdk/auth/signer/AwsSignerExecutionAttributeTest.java, core/http-auth-aws/src/main/java/software/amazon/awssdk/http/auth/aws/crt/internal/signer/DefaultAwsCrtV4aHttpSigner.java, core/http-auth-aws/src/main/java/software/amazon/awssdk/http/auth/aws/signer/AwsV4aHttpSigner.java, core/http-auth-aws/src/main/java/software/amazon/awssdk/http/auth/aws/signer/RegionSet.java, core/http-auth-aws/src/test/java/software/amazon/awssdk/http/auth/aws/RegionSetTest.java, core/http-auth-aws/src/test/java/software/amazon/awssdk/http/auth/aws/crt/TestUtils.java, core/http-auth-spi/src/main/java/software/amazon/awssdk/http/auth/spi/signer/SignerProperty.java, test/codegen-generated-classes-test/src/test/java/software/amazon/awssdk/services/endpointproviders/EndpointInterceptorTests.java
- V4a signers have a concept of "set of regions" that a signature is valid for, as opposed to a singular region with v4 signers
- The current code could technically support a set of regions in the form of a comma-separated string, but this could error-prone for a caller as there would be no validation of that string
- These changes update the interface to use a stronger typed `RegionSet`, which enables up-front validation on the inputs
- Create a `RegionSet` class, Update interface to use `RegionSet`
- Update codegen to form the correct input, and update codegen tests
- Update attribute-property adapter code to use region-set instead of region-name
- Run new and existing tests, make sure pass
=> Update AwsV4aHttpSigner to use RegionSet

core/http-auth-aws/src/main/java/software/amazon/awssdk/http/auth/aws/signer/AwsV4FamilyHttpSigner.java, core/http-auth-aws/src/main/java/software/amazon/awssdk/http/auth/aws/signer/AwsV4HttpSigner.java, core/http-auth-aws/src/main/java/software/amazon/awssdk/http/auth/aws/signer/AwsV4aHttpSigner.java, core/http-auth-aws/src/test/java/software/amazon/awssdk/http/auth/aws/AwsV4aHttpSignerTest.java, core/http-auth-spi/src/main/java/software/amazon/awssdk/http/auth/spi/signer/HttpSigner.java, core/http-auth-spi/src/main/java/software/amazon/awssdk/http/auth/spi/signer/SignerProperty.java, core/http-auth-spi/src/test/java/software/amazon/awssdk/http/auth/spi/scheme/AuthSchemeOptionTest.java, core/http-auth-spi/src/test/java/software/amazon/awssdk/http/auth/spi/signer/HttpSignerTest.java, core/http-auth-spi/src/test/java/software/amazon/awssdk/http/auth/spi/signer/SignerPropertyTest.java, core/identity-spi/src/main/java/software/amazon/awssdk/identity/spi/IdentityProperty.java, core/identity-spi/src/test/java/software/amazon/awssdk/identity/spi/IdentityPropertyTest.java, core/identity-spi/src/test/java/software/amazon/awssdk/identity/spi/ResolveIdentityRequestTest.java, core/sdk-core/src/test/java/software/amazon/awssdk/core/internal/http/pipeline/stages/AsyncSigningStageTest.java, core/sdk-core/src/test/java/software/amazon/awssdk/core/internal/http/pipeline/stages/SigningStageTest.java
- To ensure uniqueness of properties, we can add the concept on namespacing when properties are defined
- Add namespace to property definitions, which is derived from a class' name when `create()` is called
- Updates all places where properties are defined and tests
=> Add namespacing to Signer and Identity properties

codegen/src/main/java/software/amazon/awssdk/codegen/IntermediateModelBuilder.java, codegen/src/main/java/software/amazon/awssdk/codegen/model/intermediate/IntermediateModel.java, codegen/src/main/java/software/amazon/awssdk/codegen/model/intermediate/Metadata.java, codegen/src/main/java/software/amazon/awssdk/codegen/model/intermediate/ShapeModel.java, codegen/src/main/java/software/amazon/awssdk/codegen/poet/builder/BaseClientBuilderClass.java, codegen/src/main/java/software/amazon/awssdk/codegen/poet/client/AsyncClientClass.java, codegen/src/main/java/software/amazon/awssdk/codegen/poet/client/ClientClassUtils.java, codegen/src/main/java/software/amazon/awssdk/codegen/poet/client/SyncClientClass.java, codegen/src/main/java/software/amazon/awssdk/codegen/poet/client/specs/JsonProtocolSpec.java, codegen/src/main/java/software/amazon/awssdk/codegen/poet/client/specs/QueryProtocolSpec.java, codegen/src/main/java/software/amazon/awssdk/codegen/poet/client/specs/XmlProtocolSpec.java, codegen/src/main/java/software/amazon/awssdk/codegen/poet/client/traits/NoneAuthTypeRequestTrait.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/builder/test-bearer-auth-client-builder-class.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/builder/test-client-builder-class.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/builder/test-client-builder-endpoints-auth-params.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/builder/test-client-builder-internal-defaults-class.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/builder/test-composed-sync-default-client-builder.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/builder/test-no-auth-ops-client-builder-class.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/builder/test-query-client-builder-class.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/test-aws-json-async-client-class.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/test-json-async-client-class.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/test-json-client-class.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/test-query-async-client-class.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/test-query-client-class.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/test-xml-async-client-class.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/test-xml-client-class.java, services/s3/src/test/java/software/amazon/awssdk/services/s3/functionaltests/PutObjectWithChecksumTest.java, test/codegen-generated-classes-test/src/test/java/software/amazon/awssdk/services/bearerauth/ClientBuilderTest.java
To support service level release control, we need to be able to codegen with both pre SRA and post SRA code. So need to bring codegen code back related to old Signers.
Bringing back code by reverting these PRs:
#4286 
#4292
#4280 
Fixed tests the break with the reverts.
This is not the end state. With this PR, both old Signer and new SRA related logic (AuthSchemes and HttpSigner) are getting generated and configured on the client. Next PR needs to introduce a flag and switch the codegen logic to generate only one or the other. If the CI doesn't break at this PR, I'd prefer to keep the switching logic in separate PR, to make reviewing easier.
In this current state, because of https://github.com/aws/aws-sdk-java-v2/blob/5635201456dc0362db4a935c6fe817a1f50c7c6c/core/aws-core/src/main/java/sof …
=> Bring old Signer back

core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/http/pipeline/stages/AsyncSigningStage.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/http/pipeline/stages/SigningStage.java, core/sdk-core/src/test/java/software/amazon/awssdk/core/internal/http/pipeline/stages/AsyncSigningStageTest.java, core/sdk-core/src/test/java/software/amazon/awssdk/core/internal/http/pipeline/stages/SigningStageTest.java
`TIME_OFFSET` attribute is required to determine if an exception is clockskew exception or not when the SDK unmarshalls the error, eg: https://github.com/aws/aws-sdk-java-v2/blob/master/core/protocols/aws-json-protocol/src/main/java/software/amazon/awssdk/protocols/json/internal/unmarshall/AwsJsonProtocolErrorUnmarshaller.java#L86. W/o `TIME_OFFSET`, clockskew error is not retried.
Set TIME_OFFSET attribtue in SRA signind methods
Updated existing tests and verified integ tests passed with this change
=> Set TIME_OFFSET attribtue in SRA signin methods

core/aws-core/src/main/java/software/amazon/awssdk/awscore/util/SignerOverrideUtils.java, test/codegen-generated-classes-test/src/test/java/software/amazon/awssdk/services/SraIdentityResolutionTest.java
isSignerOverridden is used in AwsExecutionContextBuilder. 
The SIGNER_OVERRIDDEN ExecutionAttribute is set here
https://github.com/aws/aws-sdk-java-v2/blob/32390a25048bdae15b4cac319af8805759dd1aa6/core/aws-core/src/main/java/software/amazon/awssdk/awscore/internal/AwsExecutionContextBuilder.java#L110
And isSignerOverridden is called here
https://github.com/aws/aws-sdk-java-v2/blob/32390a25048bdae15b4cac319af8805759dd1aa6/core/aws-core/src/main/java/software/amazon/awssdk/awscore/internal/AwsExecutionContextBuilder.java#L156
which is called here
https://github.com/aws/aws-sdk-java-v2/blob/32390a25048bdae15b4cac319af8805759dd1aa6/core/aws-core/src/main/java/software/amazon/awssdk/awscore/internal/AwsExecutionContextBuilder.java#L129-L136
So when the client is configured if SIGNER_OVERRIDDEN …
=> Fix isClientSignerOverridden to check actual value

core/http-auth-spi/pom.xml, core/http-auth-spi/src/main/java/software/amazon/awssdk/http/auth/spi/signer/SignerProperty.java, core/http-auth-spi/src/test/java/software/amazon/awssdk/http/auth/spi/signer/SignerPropertyTest.java, core/identity-spi/pom.xml, core/identity-spi/src/main/java/software/amazon/awssdk/identity/spi/IdentityProperty.java, core/identity-spi/src/test/java/software/amazon/awssdk/identity/spi/IdentityPropertyTest.java
This ensures that users won't unintentionally define two separate properties that are equal.
=> Validate that SignerProperty and IdentityProperty namespaces/names are unique.

.brazil.json, buildspecs/release-javadoc.yml, buildspecs/release-to-maven.yml, pom.xml, test/old-client-version-compatibility-test/pom.xml, test/old-client-version-compatibility-test/src/it/java/software/amazon/awssdk/services/oldclient/S3PutGetIntegrationTest.java, test/old-client-version-compatibility-test/src/it/java/software/amazon/awssdk/services/oldclient/TestUtils.java, test/old-client-version-compatibility-test/src/it/resources/log4j2.properties, test/tests-coverage-reporting/pom.xml
Dependency tree, validating the package versions:
```
[INFO] --- maven-dependency-plugin:3.1.1:tree (default-cli) @ old-client-version-compatibility-test ---
[INFO] software.amazon.awssdk:old-client-version-compatibility-test:jar:2.20.154-SNAPSHOT
[INFO] +- software.amazon.awssdk:s3:jar:2.20.136:compile
[INFO] |  +- software.amazon.awssdk:aws-xml-protocol:jar:2.20.154-SNAPSHOT:compile
[INFO] |  |  \- software.amazon.awssdk:aws-query-protocol:jar:2.20.154-SNAPSHOT:compile
[INFO] |  +- software.amazon.awssdk:protocol-core:jar:2.20.154-SNAPSHOT:compile
[INFO] |  +- software.amazon.awssdk:arns:jar:2.20.154-SNAPSHOT:compile
[INFO] |  +- software.amazon.awssdk:profiles:jar:2.20.154-SNAPSHOT:compile
[INFO] |  +- software.amazon.awssdk:crt-core:jar:2.20.136:compile
[INFO] |  +- …
```
=> Add read-after-write S3 integration tests using old S3 clients and new core modules.

test/codegen-generated-classes-test/src/main/resources/codegen-resources/query/customization.config, test/codegen-generated-classes-test/src/test/java/software/amazon/awssdk/services/SraIdentityResolutionTest.java
This test broke after #4491 , since now the client was defaulting to useSraAuth=false.
* Add useSraAuth=true
* Using the query service, as the restjson service was from codegen-resources/customresponsemetadata which seemed odd to use for this test. It doesn't really matter, but just switched to query, to use a vanilla service with no other customization.config.
`./mvnw clean install -pl :codegen-generated-classes-test`
=> Add useSraAuth=true for SraIdentityResolutionTest

core/sdk-core/src/main/java/software/amazon/awssdk/core/interceptor/ExecutionAttribute.java, test/old-client-version-compatibility-test/src/test/java/InterceptorSignerAttributeTest.java, test/old-client-version-compatibility-test/src/test/java/S3AnonymousTest.java, test/service-test-utils/src/main/java/software/amazon/awssdk/testutils/service/http/MockHttpClient.java
1. Ensure anonymous credentials function correctly
2. Ensure attributes set in custom execution interceptors make it to the legacy signer
=> Add additional backwards-compatibility testing for legacy clients.

codegen/src/main/java/software/amazon/awssdk/codegen/poet/builder/BaseClientBuilderClass.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/builder/sra/test-bearer-auth-client-builder-class.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/builder/sra/test-client-builder-class.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/builder/sra/test-client-builder-endpoints-auth-params.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/builder/sra/test-client-builder-internal-defaults-class.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/builder/sra/test-composed-sync-default-client-builder.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/builder/sra/test-no-auth-ops-client-builder-class.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/builder/sra/test-no-auth-service-client-builder-class.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/builder/sra/test-query-client-builder-class.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/builder/test-bearer-auth-client-builder-class.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/builder/test-client-builder-class.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/builder/test-client-builder-endpoints-auth-params.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/builder/test-client-builder-internal-defaults-class.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/builder/test-composed-sync-default-client-builder.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/builder/test-no-auth-ops-client-builder-class.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/builder/test-no-auth-service-client-builder-class.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/builder/test-query-client-builder-class.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/client/config/internal/ConfigurationUpdater.java
Added a new protected method to each of the base client builders to return the service specific `ConfigurationUpdater` instance that will be used to run the plugins
=> Add codegen to generate an accessor for ConfigurationUpdater

services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/handlers/DisablePayloadSigningInterceptor.java, services/s3/src/main/resources/codegen-resources/customization.config, services/s3/src/test/java/software/amazon/awssdk/services/s3/PayloadSigningDisabledTest.java
This is currently redundant, but when useSraAuth is made true, it will ensure that payload signing remains disabled.
=> Disable S3 payload signing.

core/auth-crt/pom.xml
Customers currently depend on auth-crt to get Sigv4a support. In the future, customers should depend on http-auth-aws-crt for Sigv4a support. In order to ensure existing customers still work after SRA, we want users who depend on auth-crt today to automatically depend on http-auth-aws-crt.
=> Add dependency on http-auth-aws-crt from auth-crt.

core/http-auth-aws/src/main/java/software/amazon/awssdk/http/auth/aws/internal/signer/DefaultAwsV4HttpSigner.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/http/pipeline/stages/HttpChecksumStage.java, services/s3/src/it/java/software/amazon/awssdk/services/s3/checksum/AsyncHttpChecksumIntegrationTest.java
Async signing is not supported in SRA signer at the moment, so we need to rely on existing HttpChecksumStage. Note that for sync, we still use new SRA signer.
Use HttpChecksumStage for async trailer support
Ran `AsyncHttpChecksumIntegrationTest` and verified it worked.
=> Use HttpChecksumStage for async trailer support

core/sdk-core/src/main/java/software/amazon/awssdk/core/client/builder/SdkDefaultClientBuilder.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/client/config/internal/SdkClientConfigurationUtil.java, test/codegen-generated-classes-test/src/test/java/software/amazon/awssdk/services/SraIdentityResolutionUsingPluginsTest.java
Adds the wiring to run the plugins at client build time. 
The plugins will be invoked **after** building the configuration and **before** the finalizing hooks, 
The final configuration used for the sync client is [built here](https://github.com/aws/aws-sdk-java-v2/blob/349a0e6918b90478d5704006ef348e5c0bb9f006/core/sdk-core/src/main/java/software/amazon/awssdk/core/client/builder/SdkDefaultClientBuilder.java#L169) for the sync configuration and [built here](https://github.com/aws/aws-sdk-java-v2/blob/349a0e6918b90478d5704006ef348e5c0bb9f006/core/sdk-core/src/main/java/software/amazon/awssdk/core/client/builder/SdkDefaultClientBuilder.java#L197) for the async configuration. 
During the first phase (as demarcated by the comments) the override configuration and defaults creates the initial …
=> Invoke plugins at client build time

core/sdk-core/src/main/java/software/amazon/awssdk/core/interceptor/SdkExecutionAttribute.java
The release plan is service-by-service, so we don't want to deprecate any public interfaces until the release is fully rolled out.
`git diff origin/master origin/feature/master/sra-identity-auth` - looking through the diff, the relevant @Deprecated changes are in:
AwsSignerExecutionAttribute
S3SignerExecutionAttribute
SdkTokenExecutionAttribute
AwsClientOption.CREDENTIALS_PROVIDER, TOKEN_PROVIDER
AuthorizationStrategy
AuthorizationStrategyFactory
AwsCredentialsAuthorizationStrategy
TokenAuthorizationStrategy
SignerOverrideUtils methods.
SdkExecutionAttribute.RESOLVED_CHECKSUM_SPECS
Of these, only SdkExecutionAttribute.RESOLVED_CHECKSUM_SPECS is SdkPublicApi, rest are all protected/internal. So reverting just that one. Note, javadoc content also reverted to what was earlier.
Revert …
=> Revert deprecations until SRA release is complete

services/polly/src/main/java/software/amazon/awssdk/services/polly/internal/presigner/DefaultPollyPresigner.java, services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/signing/DefaultS3Presigner.java
Since the release will be service by service, will start with S3/Polly on preSRA, making the Presigners be not dependent on new interfaces.
So reverting SRA changes for Presigners from https://github.com/aws/aws-sdk-java-v2/pull/4311. That change was necessary in the scope of #4311, but now is not necessary because of derived attributes change from https://github.com/aws/aws-sdk-java-v2/pull/4396.
` ./mvnw clean install -pl :polly,:s3`
=> Revert Presigners to pre SRA Identity & Auth

services/s3/src/test/java/software/amazon/awssdk/services/s3/S3PresignerTest.java
This test was disabled earlier as sigv4a signer wasn't wired up properly.
Uncomment the test.
the test passes
=> Uncomment disabled S3PresignerTest for sigv4a

core/http-auth-aws/src/main/java/software/amazon/awssdk/http/auth/aws/internal/signer/Checksummer.java, core/http-auth-aws/src/main/java/software/amazon/awssdk/http/auth/aws/internal/signer/DefaultAwsV4HttpSigner.java, core/http-auth-aws/src/main/java/software/amazon/awssdk/http/auth/aws/internal/signer/V4RequestSigner.java, core/http-auth-aws/src/test/java/software/amazon/awssdk/http/auth/aws/internal/signer/DefaultAwsV4HttpSignerTest.java
- If a request has an anonymous identity, we should not sign it, but we should still optionally encode it and add flexible checksum information to it
- If a request is chunk-encoding enabled, we still must do some checks before we decide to chunk-encode the payload (i.e. if checksum is in headers and it's unsigned, we should NOT chunk-encode)
- If a checksum is already provided in the request headers, we should not re-compute it or override it
- Run s3 integration tests
- Run unit tests
=> Handling Anonymous, chunking decisions, and existing checksums

build-tools/src/main/resources/software/amazon/awssdk/spotbugs-suppressions.xml, core/http-auth-aws/src/main/java/software/amazon/awssdk/http/auth/aws/crt/internal/signer/AwsChunkedV4aPayloadSigner.java, core/http-auth-aws/src/main/java/software/amazon/awssdk/http/auth/aws/crt/internal/signer/DefaultAwsCrtV4aHttpSigner.java, core/http-auth-aws/src/main/java/software/amazon/awssdk/http/auth/aws/crt/internal/signer/RollingSigner.java, core/http-auth-aws/src/main/java/software/amazon/awssdk/http/auth/aws/internal/signer/DefaultAwsV4HttpSigner.java, core/http-auth-aws/src/test/java/software/amazon/awssdk/http/auth/aws/crt/internal/signer/DefaultAwsCrtV4aHttpSignerTest.java
- Similar to #4517, but for crt case, and includes fixes that enable MRAP integ tests to succeed
- Adjust chunk-encoding conditions, ensuring that requests that shouldn't be chunk-encoded are not
- Fix rolling signer to correctly use previous-signatures in a rolling manner
- Run unit tests
- Run s3 and s3control integ tests, make sure pass
=> Adjust decision for chunk-encoding for CRT, fix rolling signer

core/aws-core/src/main/java/software/amazon/awssdk/awscore/internal/AwsExecutionContextBuilder.java, core/aws-core/src/test/java/software/amazon/awssdk/awscore/internal/AwsExecutionContextBuilderTest.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/http/pipeline/stages/AsyncSigningStage.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/http/pipeline/stages/SigningStage.java, core/sdk-core/src/test/java/software/amazon/awssdk/core/internal/http/pipeline/stages/AsyncSigningStageTest.java, core/sdk-core/src/test/java/software/amazon/awssdk/core/internal/http/pipeline/stages/SigningStageTest.java, test/codegen-generated-classes-test/src/test/java/software/amazon/awssdk/services/NoneAuthTypeRequestTest.java
This addresses https://github.com/aws/aws-sdk-java-v2/pull/4396#discussion_r1318175674. If authType=none, there is no need to do identity resolution. https://github.com/aws/aws-sdk-java-v2/pull/4519 shows that that was the behavior before SRA (since they pass in the PR). But this behavior was changing because of https://github.com/aws/aws-sdk-java-v2/pull/4396#discussion_r1318175674 and this PR fixes it.
First I added a commit that adds the same pre SRA tests from https://github.com/aws/aws-sdk-java-v2/pull/4519. Also, added some more tests for similar expected behavior for post SRA. Without making the change to AwsExecutionContextBuilder, these tests failed:
* preSra_authTypeNone_signerRequestOverride_doesNotAssignSigner_doesNotResolveIdentity
* …
=> If authType=none don't use the old signer, even if overridden 

services/s3/src/it/java/software/amazon/awssdk/services/s3/S3PresignerIntegrationTest.java
- Bug in code where the test object gets deleted before tests run that depend on the object being present
- Fix reference to object key, delete test should use the object that was meant to be deleted
=> Fix incorrect variable usage in S3PresignerIntegrationTest

services/polly/src/main/java/software/amazon/awssdk/services/polly/internal/presigner/DefaultPollyPresigner.java, services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/signing/DefaultS3Presigner.java
https://github.com/aws/aws-sdk-java-v2/pull/4515 caused S3PresignerIntegrationTest.keysWithScaryCharactersWorks to fail when useSraAuth=true. 
In master, the DefaultS3Presigner would include S3EndpointAuthSchemeInterceptor as seen [here](https://github.com/aws/aws-sdk-java-v2/blob/3fbf13cbed80c3e8ce355963be8f7bcffc2a49ab/services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/signing/DefaultS3Presigner.java#L207). With SRA codegen changes, there is no longer S3EndpointAuthSchemeInterceptor but it's functionality is part of S3ResolveEndpointInterceptor. However, because of https://github.com/aws/aws-sdk-java-v2/pull/4505 S3ResolveEndpointInterceptor behaves differently for useSraAuth=false v/s true. The integ test is fine with useSraAuth=false, but with useSraAuth=true, 
``` …
```
=> Revert "Revert Presigners to pre SRA Identity & Auth (#4515)"

test/codegen-generated-classes-test/src/main/resources/codegen-resources/endpointdiscovery/customization.config, test/codegen-generated-classes-test/src/main/resources/codegen-resources/endpointproviders/customization.config, test/codegen-generated-classes-test/src/test/java/software/amazon/awssdk/services/endpointproviders/EndpointInterceptorTests.java
Was switched to useSraAuth=true in https://github.com/aws/aws-sdk-java-v2/pull/4491/commits/e0e6a422e5d5bdab613e567e352df7e18d56e5c5 as part of #4491. Switching it back to false, like the rest of the feature/master/sra-identity-auth branch. New tests that were added earlier for useSraAuth=true have been disabled here. They should be enabled when we switch useSraAuth=true.
=> Switch endpointdiscovery/endpointproviders back to useSraAuth=false

services/s3/src/test/java/software/amazon/awssdk/services/s3/S3PresignerTest.java, services/s3/src/test/java/software/amazon/awssdk/services/s3/functionaltests/PutObjectWithChecksumTest.java, services/s3/src/test/java/software/amazon/awssdk/services/s3/internal/resource/MultiRegionAccessPointEndpointResolutionTest.java, test/codegen-generated-classes-test/src/test/java/software/amazon/awssdk/services/eventstreams/EventMarshallingTest.java, test/codegen-generated-classes-test/src/test/java/software/amazon/awssdk/services/protocolrestjson/AsyncOperationCancelTest.java, test/protocol-tests/src/test/java/software/amazon/awssdk/protocol/tests/clockskew/ClockSkewAdjustmentTest.java
Some tests were disabled earlier while we were working on the feature branch, as they used to fail on SRA codepath, i.e., what is now useSraAuth=true. Some of these are now fixed. Uncommenting those tests. But some still fail with useSraAuth=true. The feature branch is now defaulting to useSraAuth=false, so uncommenting even those tests, with a TODO to fix them in the useSraAuth=true testing branch (feature/master/sra-identity-auth-testing). At least, this way we've ensured these tests work for useSraAuth=false - the first stage of the release; when we merge the feature/master/sra-identity-auth branch to master, we won't be reducing the tests run.
With this, the known tests failing with useSraAuth=true are in:
1. EventMarshallingTest
1. protocolrestjson/AsyncOperationCancelTest
1. …
=> Uncomment some previously disabled tests

codegen/src/test/java/software/amazon/awssdk/codegen/poet/builder/BaseClientBuilderClassTest.java, codegen/src/test/java/software/amazon/awssdk/codegen/poet/client/AsyncClientClassTest.java, codegen/src/test/java/software/amazon/awssdk/codegen/poet/client/SyncClientClassTest.java
These tests don't work as-is in the testing branch where we default useSraAuth=true.
So these tests work in both the feature branch and the testing branch where we default useSraAuth=true.
`./mvnw clean install -pl :codegen`
=> Update codegen tests and explicitly use useSraAuth=false/true

core/auth/pom.xml, core/aws-core/pom.xml, core/aws-core/src/test/java/software/amazon/awssdk/awscore/internal/AwsExecutionContextBuilderTest.java, core/http-auth-aws/pom.xml, services/bedrock/pom.xml, services/bedrockruntime/pom.xml
Searched for "Used undeclared dependencies found:" in the build logs. Fixed 4/6. 
One was in old-client-version-compatibility-test which is a test module, so didn't bother.
```
2023-10-04T01:37:29.2974524Z [INFO] --- dependency:3.1.1:analyze-only (default) @ old-client-version-compatibility-test ---
2023-10-04T01:37:29.2974722Z [WARNING] Used undeclared dependencies found:
2023-10-04T01:37:29.2975084Z [WARNING]    software.amazon.awssdk:regions:jar:2.20.158-SNAPSHOT:compile
2023-10-04T01:37:29.2975426Z [WARNING]    software.amazon.awssdk:sdk-core:jar:2.20.158-SNAPSHOT:compile
2023-10-04T01:37:29.2975749Z [WARNING]    software.amazon.awssdk:auth:jar:2.20.158-SNAPSHOT:compile
2023-10-04T01:37:29.2976084Z [WARNING]    software.amazon.awssdk:aws-core:jar:2.20.158-SNAPSHOT:compile …
```
=> Add used but undeclared dependencies to pom.xmls

core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/http/pipeline/stages/HttpChecksumStage.java, services/s3/src/it/java/software/amazon/awssdk/services/s3/checksum/AsyncHttpChecksumIntegrationTest.java
They were commented out in https://github.com/aws/aws-sdk-java-v2/pull/4503.
Enabled those tests, and update TODO comment.
Ran those tests locally with both useSraAuth=false/true.
=> Uncomment previously disabled AsyncHttpChecksumIntegrationTest

test/codegen-generated-classes-test/src/test/java/software/amazon/awssdk/services/NoneAuthTypeRequestTest.java, test/codegen-generated-classes-test/src/test/java/software/amazon/awssdk/services/bearerauth/ClientBuilderTest.java, test/codegen-generated-classes-test/src/test/java/software/amazon/awssdk/services/mixedauth/ClientBuilderTest.java, test/codegen-generated-classes-test/src/test/java/software/amazon/awssdk/services/protocolrestjson/ClientBuilderTest.java
These are the 2 failing tests for codegen-generated-classes-test with useSraAuth=true (in the feature/master/sra-identity-auth-testing branch). Updating the tests for SRA. We would merge this to master, towards the end of the release, once useSraAuth=true in master.
The ClientBuilder tests actually should be updated to assert for SRA types, but just made it a TODO for now, to get the branch to green first.
Update tests.
=> Update codegen-generated-classes-test for SRA

core/aws-core/src/main/java/software/amazon/awssdk/awscore/client/builder/AwsClientBuilder.java, core/aws-core/src/test/java/software/amazon/awssdk/awscore/client/builder/DefaultAwsClientBuilderTest.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/client/builder/SdkClientBuilder.java, core/sdk-core/src/test/java/software/amazon/awssdk/core/client/builder/DefaultClientBuilderTest.java
Move `putAuthSchemes` out of `AwsClientBuilder` and into `SdkClientBuilder`.
=> Move putAuthScheme to SdkClientBuilder

core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/http/pipeline/stages/AsyncSigningStage.java, core/sdk-core/src/test/java/software/amazon/awssdk/core/internal/http/pipeline/stages/AsyncSigningStageTest.java
With the short-circuit it is possible that the signedRequest.payload() isn't set on the resulting SdkHttpFullRequest. In cases where the payload doesn't actually change during HttpSigner.sign(), this is ok. But the payload *can* change, e.g., for chunk-encoding, so need to extract the resulting payload from signedRequest.payload().
This change was already made to SigningStage in https://github.com/aws/aws-sdk-java-v2/pull/4507/files#r1341852647.
Making the same change here.
=> Do not short-circuit toSdkHttpFullRequest

core/sdk-core/src/main/java/software/amazon/awssdk/core/RequestOverrideConfiguration.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/SdkPlugin.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/client/builder/SdkClientBuilder.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/client/builder/SdkDefaultClientBuilder.java
Mark all the plugins API as preview.
=> Mark plugin API as preview

codegen/src/main/java/software/amazon/awssdk/codegen/poet/model/ServiceClientConfigurationBuilderClass.java, codegen/src/main/java/software/amazon/awssdk/codegen/poet/model/ServiceClientConfigurationClass.java, codegen/src/main/java/software/amazon/awssdk/codegen/poet/model/ServiceClientConfigurationUtils.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/serviceclientconfiguration-builder.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/serviceclientconfiguration.java, core/aws-core/src/main/java/software/amazon/awssdk/awscore/AwsServiceClientConfiguration.java
This change exposes the map of AuthSchemes configured in the client using the `SdkServiceClientConfiguration` class.
=> Add AuthScheme to the SerivceClientConfiguration

codegen/src/main/java/software/amazon/awssdk/codegen/AddOperations.java, codegen/src/main/java/software/amazon/awssdk/codegen/customization/processors/DefaultCustomizationProcessor.java, codegen/src/main/java/software/amazon/awssdk/codegen/customization/processors/ExplicitStringPayloadQueryProtocolProcessor.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/c2j/query/service-2.json, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/test-json-async-client-class.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/test-json-client-class.java
Explicit String payloads are not supported for Query protocols
Update codegen to fail if there is Query protocol operation with explicit String payload
Update Json codegen test classes which were missed in previous [PR](https://github.com/aws/aws-sdk-java-v2/pull/4450) - `string` can be lowercase when calling `shape.getType()`
=> Fail codegen for Query protocol operations with explicit String payload

core/aws-core/src/main/java/software/amazon/awssdk/awscore/AwsServiceClientConfiguration.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/RequestOverrideConfiguration.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/SdkServiceClientConfiguration.java
In a previous [pull request](https://github.com/aws/aws-sdk-java-v2/pull/4551) the method to put auth schemes was moved from `AwsClientBuilder` to `SdkClientBuilder`. This change does the same for the configuration moving the auth scheme related methods from `AwsServiceClientConfiguration` to `SdkServiceClientConfiguration`.
=> Move the auth schemes into sdk configuration

.changes/next-release/feature-AWSSDKforJavav2-78a6c88.json, core/protocols/aws-json-protocol/src/main/java/software/amazon/awssdk/protocols/json/internal/MarshallerUtil.java, core/protocols/aws-json-protocol/src/main/java/software/amazon/awssdk/protocols/json/internal/unmarshall/JsonProtocolUnmarshaller.java, core/protocols/aws-json-protocol/src/main/java/software/amazon/awssdk/protocols/json/internal/unmarshall/JsonUnmarshallerContext.java, core/protocols/aws-xml-protocol/src/main/java/software/amazon/awssdk/protocols/xml/internal/unmarshall/XmlProtocolUnmarshaller.java, test/codegen-generated-classes-test/src/main/resources/codegen-resources/xml/service-2.json, test/codegen-generated-classes-test/src/test/java/software/amazon/awssdk/services/protocolrestjson/StringPayloadUnmarshallingTest.java, test/protocol-tests/src/main/resources/codegen-resources/restxml/service-2.json, test/protocol-tests/src/test/java/software/amazon/awssdk/protocol/tests/RestXmlEventStreamProtocolTest.java, test/protocol-tests/src/test/java/software/amazon/awssdk/protocol/tests/XmlPayloadStringTest.java
To support non-XML String payloads
Update XML marshaller/unmarshaller to support explicit String payloads, including non-XML Strings
=> Support non-XML String payloads

.changes/next-release/feature-AWSCRTbasedS3client-666199c.json, core/crt-core/src/main/java/software/amazon/awssdk/crtcore/CrtProxyConfiguration.java, services/s3/src/main/java/software/amazon/awssdk/services/s3/crt/S3CrtProxyConfiguration.java, services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/crt/S3CrtAsyncHttpClient.java, services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/crt/S3NativeClientConfiguration.java, services/s3/src/test/java/software/amazon/awssdk/services/s3/internal/crt/S3CrtAsyncHttpClientTest.java, utils/src/main/java/software/amazon/awssdk/utils/ProxyConfigProvider.java
Support to Disable Ennvironment Variable Proxy option when using S3CrtClient HttpProxyConfig options
- Crt Client picks up HTTP_PROXY environment proxy settings
- User needs a way to disable picking up of Proxy settings from env variable.
- Added  logic in S3CrtAsyncHttpClient to set HttpProxyEnvironmentVariableSetting.HttpProxyEnvironmentVariableType.DISABLED when useEnvironmentVariableValues is enabled
```java
S3AsyncClient.crtBuilder()
.httpConfiguration(h -> h
.proxyConfiguration(proxy -> proxy.useEnvironmentVariableValues(false)))
.build();
```
- Added Junits
- tested by creating a jar and running on terminal which had environment variables set.
=> Support to Disable Ennvironment Variable Proxy option when using S3CrtClient HttpProxyConfig options

pom.xml
With move to SRA Identity & Auth, most clients won't need a dependency on auth module. But cannot remove it from services/pom.xml until all services have switched.
Right now the feature/master/sra-identity-auth-testing branch fails because of this - https://github.com/aws/aws-sdk-java-v2/actions/runs/6512780114/job/17691098594?pr=4478. 
```
2023-10-13T20:41:15.3125267Z [WARNING] Unused declared dependencies found:
2023-10-13T20:41:15.3126264Z [WARNING]    software.amazon.awssdk:auth:jar:2.21.1-SNAPSHOT:compile
```
Want to merge this to `master` before we start switching services to useSraAuth=true.
Add ignore for the auth module.
Tested locally that one service module with useSraAuth=true, fails before this change, and passes after.
=> Ignore auth maven-dependency-plugin failure

core/auth/src/main/java/software/amazon/awssdk/auth/signer/AwsSignerExecutionAttribute.java, core/auth/src/test/java/software/amazon/awssdk/auth/signer/AwsSignerExecutionAttributeTest.java, services/s3/src/test/java/software/amazon/awssdk/services/s3/S3PresignerTest.java
Because of the 2 instant() calls in the write/read mappings, a basic write this attribute and read it back, would give different values.
Since this attribute should only be set/read explicitly by our presigner code, we don't need this mapping logic at all.
*Remove derived attribute logic for PRESIGNER_EXPIRATION
*Also, update S3PresignerTest to assert isEqualTo instead of isCloseTo and remove unnecessary override
=> Remove derived attribute logic for PRESIGNER_EXPIRATION

.changes/next-release/bugfix-AWSSDKforJavav2-bd91b46.json, .changes/next-release/bugfix-AmazonPolly-2ee8af5.json, services/polly/src/main/java/software/amazon/awssdk/services/polly/presigner/PollyPresigner.java, services/s3/src/main/java/software/amazon/awssdk/services/s3/presigner/S3Presigner.java
A bug reported by a customer #4604 noticed that the Scala compiler is getting confused about an overridden method with a more specific type. In order to work around that this change defines a default method instead which makes the Scala compiler happy.
Fixes #4604.
Added a default method for the `SdkPresigner.Builder` class.
Tested manually using an internal Scala based project.
=> Add a default method to override credentialsProvider

test/codegen-generated-classes-test/src/test/java/software/amazon/awssdk/services/NoneAuthTypeRequestTest.java, test/codegen-generated-classes-test/src/test/java/software/amazon/awssdk/services/eventstreams/EventMarshallingTest.java, test/codegen-generated-classes-test/src/test/java/software/amazon/awssdk/services/protocolrestjson/AsyncOperationCancelTest.java
Cleanup some SRA identity auth TODOs.
* EventMarshallingTest passes with useSraAuth=true
* AsyncOperationCancelTest passes with useSraAuth=true
*  NoneAuthTypeRequestTest - the test needs some updates to the assertion in the test for useSraAuth=true. These have been made in https://github.com/aws/aws-sdk-java-v2/pull/4548/files#diff-4eea6ae550c8f98cf083d8cb756b42da8c010b31d3b3dfc2352f111acd4740f6 in the sra-identity-auth-testing branch, so updating this TODO - we will need to make those changes in master when we default useSraAuth=true in `master` branch.
=> Cleanup some SRA identity auth TODOs

services/acm/pom.xml, services/acm/src/it/java/software/amazon/awssdk/services/acm/AwsCertficateManagerIntegrationTest.java, services/acm/src/it/resources/log4j2.properties
Adding an integration test to make sure overriding client to use Sigv4a signer works and continues to work with useSraAuth=true.
Add integ test
Ran integ test locally, with both useSraAuth=false/true
=> Add integ test with old Signer override for sigv4a

.changes/next-release/bugfix-AWSSDKforJavav2-86ff2d3.json
Change log entry for https://github.com/aws/aws-sdk-java-v2/pull/4621
=> Change log for RESOLVED_CHECKSUM_SPECS bug fix.

core/auth/src/test/java/software/amazon/awssdk/auth/signer/AwsSignerExecutionAttributeTest.java, core/sdk-core/pom.xml, core/sdk-core/src/main/java/software/amazon/awssdk/core/interceptor/SdkExecutionAttribute.java
Fix for https://github.com/aws/aws-sdk-java-v2/issues/4608.
This is reverting the read/write mapping logic for checksum related execution attribute (RESOLVED_CHECKSUM_SPECS) that was introduced in https://github.com/aws/aws-sdk-java-v2/pull/4452/files#diff-933c20d96318c11c8224fcd3904f17bad1614606bd1d934e17bb719d99b183be to support SRA SignerProperty for the same. With this revert, flexible checksums (used only by SRA) will to not work with useSraAuth=true, but this is a minimal fix to resolve the issue, and we can make a different fix with SRA support later.
Ran regular tests in CI, as well as integration/stability tests.
=> Revert RESOLVED_CHECKSUM_SPECS mapping for SRA

test/s3-benchmarks/src/main/java/software/amazon/awssdk/s3benchmarks/BaseCrtClientBenchmark.java
Remove the use of `CrtS3RuntimeException` in our tests. This class is to be removed in https://github.com/awslabs/aws-crt-java/pull/700
=> Remove the use of CrtS3RuntimeException in tests

core/auth/src/test/java/software/amazon/awssdk/auth/signer/AwsSignerExecutionAttributeTest.java, core/aws-core/src/test/java/software/amazon/awssdk/awscore/checksum/AwsSignerWithChecksumTest.java, core/sdk-core/pom.xml, core/sdk-core/src/main/java/software/amazon/awssdk/core/interceptor/ExecutionAttribute.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/interceptor/SdkExecutionAttribute.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/interceptor/SdkInternalExecutionAttribute.java, core/sdk-core/src/test/java/software/amazon/awssdk/core/internal/http/pipeline/stages/HttpChecksumStageTest.java, pom.xml
- Update `RESOLVED_CHECKSUM_SPECS` execution-attribute to be backed by an internal execution attribute, so that it doesn't need to rely on lossless conversion
- Remove bugged code that relies on `AtomicReference`
=> Use a backing attribute for ResolvedChecksumSpecs

.changes/next-release/feature-AWSCRTbasedS3Client-1ebf6a0.json, pom.xml, services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/crt/S3CrtResponseHandlerAdapter.java, services/s3/src/test/java/software/amazon/awssdk/services/s3/internal/crt/S3CrtResponseHandlerAdapterTest.java
https://github.com/awslabs/aws-crt-java/issues/697
Add the cause of failure to the stacktrace for the CRT-based S3 client
Added unit test
=> Add the cause of failure to the stacktrace for the CRT-based S3 client

codegen/src/main/java/software/amazon/awssdk/codegen/emitters/tasks/EndpointProviderTasks.java, codegen/src/main/java/software/amazon/awssdk/codegen/poet/rules/EndpointRulesClientTestSpec.java
Client endpoint tests for S3 were not generated due to faulty codegen logic. 
Updated logic & changed it to be more readable
Ran on S3 module
=> Fix bug that prevented generating client endpoint tests

services/mediastoredata/pom.xml, services/mediastoredata/src/it/java/software/amazon/awssdk/services/mediastoredata/MediaStoreDataIntegrationTestBase.java, services/mediastoredata/src/it/java/software/amazon/awssdk/services/mediastoredata/RequestCompressionStreamingIntegrationTest.java, services/mediastoredata/src/it/java/software/amazon/awssdk/services/mediastoredata/TransferEncodingChunkedIntegrationTest.java
When containers fail to delete and tests retry, `ContainerInUseException` is thrown, leading to integ test failure, causing release to fail
Keep one container always active per account, only create if it doesn't exist
Ran tests with existing container successfully
=> Fix flakey MediaStoreData integ tests

buildspecs/release-to-maven.yml
- Build failure due to typo in build script
- this typo was introduced in  https://github.com/aws/aws-sdk-java-v2/pull/4488
- Tested by updating the buildspec in codebuild
=> Rectified a typo error in build spec where a comma was missing

core/http-auth-aws/src/main/java/software/amazon/awssdk/http/auth/aws/crt/internal/signer/DefaultAwsCrtV4aHttpSigner.java, core/http-auth-aws/src/main/java/software/amazon/awssdk/http/auth/aws/internal/signer/DefaultAwsV4HttpSigner.java, core/http-auth-aws/src/test/java/software/amazon/awssdk/http/auth/aws/internal/signer/DefaultAwsV4HttpSignerTest.java
- Prior to SRA, certain signers (i.e. `Aws4UnsignedPayloadSigner`) enforce usage of payload-signing when HTTP (not HTTPS) is used
- SRA tries to keep this behavior, but there is no way to force the signer to do unsigned-payload with HTTP (this PR changes this)
- Presigned requests will not have a payload, so `UNSIGNED-PAYLOAD` should always be used in this case.
- Addresses #4697
- Updates the conditionals for checking whether to sign the payload or not
- If `PAYLOAD_SIGNING_ENABLED` is set to false, we will honor that if the payload is not present (such as in the case of presigned requests), otherwise, we will still sign the payload (for security)
- Ran local integration tests for s3, all passed
- Ran unit tests for all signers and s3
=> Update signer payload-signing conditional to honor PAYLOAD_SIGNING_ENABLED when payload is null

.changes/next-release/feature-AWSSDKforJavav2-341feda.json, core/auth/src/main/java/software/amazon/awssdk/auth/credentials/ContainerCredentialsProvider.java, core/auth/src/test/java/software/amazon/awssdk/auth/credentials/ContainerCredentialsEndpointProviderTest.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/SdkSystemSetting.java
- Add support for EKS host and auth token file, EKS: IRSAv2 auth
- Also validation is updated to validate the loopBacks even for Relative URI
- EKS hosts IPV4 and IPV6 added in the allow hosts
- Validation of Endpoint is done as soon as final endpoint is resolved
- Added new Test cases from specifications
=> Add EKS container host in ContainerCredentialsProvider , also validate the resolved endpoint for RelativeURI

.changes/next-release/feature-AWSCRTbasedS3client-153faa9.json, pom.xml, services/s3/src/it/java/software/amazon/awssdk/services/s3/s3express/S3ExpressIntegrationTest.java, services/s3/src/it/java/software/amazon/awssdk/services/s3/s3express/S3ExpressIntegrationTestBase.java, services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/crt/CrtS3ExpressNoOpAuthScheme.java, services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/crt/DefaultS3CrtAsyncClient.java, services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/crt/S3CrtAsyncHttpClient.java, services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/crt/S3InternalSdkHttpExecutionAttribute.java, services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/s3express/S3ExpressUtils.java, services/s3/src/test/java/software/amazon/awssdk/services/s3/internal/crt/S3CrtAsyncHttpClientTest.java
Add s3 express suppport for AWS CRT-based S3 Client
Added integ tests/unit tests
=> Add s3 express suppport for AWS CRT-based S3 Client

.changes/next-release/bugfix-AWSSDKforJavav2-02e443d.json, core/crt-core/src/main/java/software/amazon/awssdk/crtcore/CrtProxyConfiguration.java, http-clients/apache-client/src/main/java/software/amazon/awssdk/http/apache/ProxyConfiguration.java, http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/ProxyConfiguration.java, http-clients/url-connection-client/src/main/java/software/amazon/awssdk/http/urlconnection/ProxyConfiguration.java, utils/src/main/java/software/amazon/awssdk/utils/http/SdkHttpUtils.java, utils/src/test/java/software/amazon/awssdk/utils/SdkHttpUtilsTest.java, utils/src/test/java/software/amazon/awssdk/utils/proxy/ProxyConfigurationTest.java
[4703](https://github.com/aws/aws-sdk-java-v2/issues/4703)
- The logic to parse no_proxy environment variables for multiple host used logic same as that of System property NO_PROXY setting which treated "|" as separator
- Why was this missed in testing ?
- [ProxyConfigurationTest](https://github.com/aws/aws-sdk-java-v2/blob/0e3b14d013a698b9cf4d6a1bc208542509fbe2bb/utils/src/test/java/software/amazon/awssdk/utils/proxy/ProxyConfigurationTest.java#L75-L82) had added a test case to test multiple hosts scenario. Unfortunately the test had a typo error where hosts names were added in double quotes instead of separate string.
- Added logic to split string based on  "," instead of "|".
- Added logic to trim extra spaces
- We are not adding greedy to non-greedy since it can cause issues if user …
=> Bugfix to support comma separated values in no_proxy environment settings

http-clients/aws-crt-client/src/test/java/software/amazon/awssdk/http/crt/AwsCrtAsyncHttpClientSpiVerificationTest.java, http-clients/aws-crt-client/src/test/java/software/amazon/awssdk/http/crt/AwsCrtHttpClientSpiVerificationTest.java, test/http-client-tests/src/main/java/software/amazon/awssdk/http/SdkHttpClientTestSuite.java
Make sure resources are closed in tests
=> Make sure CRT resources are closed in tests

test/stability-tests/src/it/java/software/amazon/awssdk/stability/tests/s3/S3MockStabilityTestBase.java, test/stability-tests/src/it/java/software/amazon/awssdk/stability/tests/s3/S3MockWithAsyncClientStabilityTest.java
Test [#4608](https://github.com/aws/aws-sdk-java-v2/issues/4608)
The issue was fixed with revert  https://github.com/aws/aws-sdk-java-v2/pull/4621 and actual fix https://github.com/aws/aws-sdk-java-v2/pull/4620
Following was the root cause
1. This issue is specific when we have S3 API calls with and without checksum back to back.
2. The Race condition occurs in [This code](https://github.com/aws/aws-sdk-java-v2/blob/1c93c02108fc10f077f393e5f03dabb2b262783c/core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/http/pipeline/stages/HttpChecksumStage.java#L218-L225)
```
return headerChecksumSpecs != null &&
headerChecksumSpecs.algorithm() != null &&
!HttpChecksumUtils.isHttpChecksumPresent(interceptorContext.httpRequest(), headerChecksumSpecs) && …
```
=> Add stability test case to test issue #4608

.changes/next-release/feature-AWSSDKforJavav2-0090bf8.json, core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/http/loader/ClasspathSdkHttpServiceProvider.java, core/sdk-core/src/test/java/software/amazon/awssdk/core/internal/http/loader/ClasspathSdkHttpServiceProviderTest.java
This change allows multiple HTTP implementations to be present on the classpath. Previously, exception will be thrown in this case, and with this change, the SDK will pick an HTTP implementation based on priority order.
Context: we found that if we release CRT sync HTTP client in the same `aws-crt-client` module, it will break customers who depend on `aws-crt-client` and use sync SDK client without specifying http client builder because there will be two sync HTTP implementations, Apache HTTP client and CRT Sync HTTP client. In order to fix this, we need to either change classpath loading logic to allow multiple HTTP implementations or create a separate module for CRT sync HTTP client service. After discussing with the team, we decided to go with the first approach because 1) we'll need …
=> Load HTTP implementation from classpath based on priority order

.changes/next-release/bugfix-AWSSDKforJavav2Bundle-d0cd612.json, bundle-logging-bridge/src/main/java/software/amazon/awssdk/thirdparty/org/slf4j/impl/StaticLoggerBinder.java, bundle-logging-bridge/src/main/java/software/amazon/awssdk/thirdparty/org/slf4j/impl/StaticMarkerBinder.java, test/bundle-logging-bridge-binding-test/src/test/java/software/amazon/awssdk/thirdparty/org/slf4j/impl/StaticLoggerBinderTest.java, test/bundle-logging-bridge-binding-test/src/test/java/software/amazon/awssdk/thirdparty/org/slf4j/impl/StaticMarkerBinderTest.java
SLF4J uses this to for reporting when there are multiple bindings.
=> Implement get(Marker|Logger)FactoryClassStr

core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/http/loader/ClasspathSdkHttpServiceProvider.java, core/sdk-core/src/test/java/software/amazon/awssdk/core/internal/http/loader/ClasspathSdkHttpServiceProviderTest.java, http-client-spi/src/main/java/software/amazon/awssdk/http/HttpExecuteResponse.java, http-clients/aws-crt-client/pom.xml, http-clients/aws-crt-client/src/main/java/software/amazon/awssdk/http/crt/internal/CrtRequestExecutor.java, http-clients/aws-crt-client/src/main/java/software/amazon/awssdk/http/crt/internal/response/CrtResponseAdapter.java, http-clients/aws-crt-client/src/main/java/software/amazon/awssdk/http/crt/internal/response/InputStreamAdaptingHttpStreamResponseHandler.java, services/s3/pom.xml, services/s3/src/it/java/software/amazon/awssdk/services/s3/S3IntegrationTestBase.java, services/s3/src/it/java/software/amazon/awssdk/services/s3/crthttpclient/S3WithCrtHttpClientsIntegrationTests.java, utils/src/main/java/software/amazon/awssdk/utils/async/InputStreamSubscriber.java
Various performance optimization for CRT sync HTTP client:
1. `InputStreamSubscriber`:  not throw exception when `close` is invoked if it has buffered all content to avoid exception creation.
2. `InputStreamAdaptingHttpStreamResponseHandler`: remove volatile for simplePublisher variable since it's unncesssary `private volatile SimplePublisher<ByteBuffer> simplePublisher;` 
3.  `InputStreamAdaptingHttpStreamResponseHandler`: complete future as soon as streaming starts. Previously, the future completes after streaming has finished, which means we'll buffer all data in memory first before user starts to read from the inputstream
=> Various performance optimization for CRT sync HTTP client

core/aws-core/pom.xml
In the PR to switch S3 to SRA, aws-core -> http-auth-aws dependency was added [here](
https://github.com/aws/aws-sdk-java-v2/pull/4653/files#diff-66154f30c8a4d9715ca5c5bdc044a40ddcc317a5a38fcc82c32484d9943d4490) but it only needs to be a `test` dependency because of [this change](https://github.com/aws/aws-sdk-java-v2/pull/4653/files#diff-5831d375cc0faaf3f965fd4f1edc6a0f3818f59a789dd4df28deebfc9d86797dR404)
Made the dependency only `test` scope.
`./mvnw clean install -pl :aws-core` passes locally.
=> Specify aws-core -> http-auth-aws as test dependency

.changes/next-release/bugfix-AWSSDKforJavav2-1054797.json, utils/src/main/java/software/amazon/awssdk/utils/internal/proxy/ProxyEnvironmentVariableConfigProvider.java, utils/src/main/java/software/amazon/awssdk/utils/internal/proxy/ProxySystemPropertyConfigProvider.java
Currently, the exception is already ignored but logged as `error`, which can be confusing.
This changes the log level to `warning`.
=> Proxy Port system properties: changed log level from error to warning

.changes/next-release/bugfix-AWSSDKforJavav2-aada2c3.json, core/auth-crt/src/main/java/software/amazon/awssdk/authcrt/signer/internal/CrtHttpRequestConverter.java, core/auth-crt/src/test/java/software/amazon/awssdk/authcrt/signer/internal/CrtHttpRequestConverterTest.java
-  Signing Error when ampersand character included in HttpQuery when using DefaultAwsCrtV4aSigner
- If the Query parameters had `&` in its value then Signing for those request used to always fail.
- The `crtRequestToHttp` loops through query returned by fullUri using "&" and "=" for finding Key and Value.
- When the value has "&" or "=" it assumes it as separate parameters thus we need to use Raw non-decoded parameters,
- The looping is done on `getRawQuery` and then its Decoded while doing a `appendRawQueryParameter`
- Added Junit test case.
- tested with a service where the issue was seen.
=> Fix for Signing Error when ampersand character included in HttpQuery when using DefaultAwsCrtV4aSigner

services/cloudfront/pom.xml, services/cloudfront/src/test/java/software/amazon/awssdk/services/cloudfront/CloudFrontUtilitiesIntegrationTest.java, services/cloudfront/src/test/java/software/amazon/awssdk/services/cloudfront/IntegrationTestBase.java
Resources are now reused between runs of the integration test, so they should not build up on the account anymore and no longer need to be re-created each time the test is run.
=> Improved speed and reliability of CloudFrontUtilitiesIntegrationTest.

.changes/next-release/bugfix-AWSSDKforJavav2-daafab1.json, core/sdk-core/src/main/java/software/amazon/awssdk/core/retry/backoff/FullJitterBackoffStrategy.java, core/sdk-core/src/test/java/software/amazon/awssdk/core/retry/RetryPolicyTest.java, utils/src/main/java/software/amazon/awssdk/utils/Validate.java
When providing zero base delay and zero max backoff time to FullJitterBackoffStrategy, the SDK throws an IllegalArgumentException:
```
java.lang.IllegalArgumentException: bound must be positive
at java.base/java.util.Random.nextInt(Random.java:388)
at software.amazon.awssdk.core.retry.backoff.FullJitterBackoffStrategy.computeDelayBeforeNextRetry(FullJitterBackoffStrategy.java:65)
at software.amazon.awssdk.core.internal.http.pipeline.stages.utils.RetryableStageHelper.getBackoffDelay(RetryableStageHelper.java:146)
...
```
That's because bound in `Random#nextInt(bound)` must be positive, and in the first retry attempt the calculated bound was zero.
After this change, the calculated delay will be ~~1ms~~ 0ms in this case.
Repro code:
```java
S3Client client = S3Client.builder() …
```
=> FullJitterBackoffStrategy zero check

.changes/next-release/bugfix-AWSSDKforJavav2-1e17bfe.json, bundle-sdk/pom.xml
This fixes #4799.
- This is not a direct dependency of the SDK, and no log4j classes are actually included in the bundle, so we should not be shading it.
- By not shading it, classes that we *do* include in the bundle, i.e. from apache-commons-logging can reference the log4j classes properly.
Build the SDK using
```
mvn clean install -P publishing  -Dspotbugs.skip -DskipTests -Dcheckstyle.skip -Djapicmp.skip -Dgpg.skip=true
```
Use created `bundle` in a test Maven project with the following Log4j config:
```xml
<Configuration status="WARN">
<Appenders>
<Console name="ConsoleAppender" target="SYSTEM_OUT">
<PatternLayout pattern="%d{YYYY-MM-dd HH:mm:ss} [%t] %-5p %c:%L - %m%n" />
</Console>
</Appenders>
<Loggers>
<Root level="DEBUG">
<AppenderRef ref="ConsoleAppender"/>
</Root>
<Logger …
```
=> Don't shade org.apache.log4j

.changes/next-release/feature-AmazonS3-04b3f91.json, services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/s3express/S3ExpressIdentityCache.java, services/s3/src/test/java/software/amazon/awssdk/services/s3/S3PresignerTest.java, services/s3/src/test/java/software/amazon/awssdk/services/s3/functionaltests/S3ExpressCreateSessionTest.java, services/s3/src/test/java/software/amazon/awssdk/services/s3/internal/s3express/S3ExpressCreateSessionConfigurationTest.java
ApiCallTimeout and ApiCallAttemptTimeout are not set by default on calls. For a nested call such as createSession, this would create an issue by making S3 calls with S3Express authentication unresponsive in case of delayed responses or errors. Therefore, createSession has a default ApiCallTimeout value of 10s. This however can cause the opposite issue, if the user wishes the SDK to try longer to retrieve the credentials. 
This PR lets the S3Express identity cache check if there is a client level apiCallTimeout set, and if it is, use that instead of the default value. 
Note that request overrides for apiCallTimeout (on the outer call, such as getObject, putObject etc) are deliberately not taken into account since the cache is common to the client, and separate request timeout values would …
=> Propagating client apiCallTimeout values to S3Express createSession

.changes/next-release/feature-AWSBackupStorageAmazonCodeCatalystAmazonCognitoIdentityAmazonCognitoIdentityProviderAWSIdentityandAccessManagementIAMAmazonKinesisAWSElementalMediaStoreDataPlaneAmazonTranscribeServiceAmazonTranscribeStreamingService-9088dc7.json, services/backupstorage/src/main/resources/codegen-resources/customization.config, services/codecatalyst/src/main/resources/codegen-resources/customization.config, services/cognitoidentity/src/main/resources/codegen-resources/customization.config, services/cognitoidentityprovider/src/main/resources/codegen-resources/customization.config, services/iam/src/main/resources/codegen-resources/customization.config, services/kinesis/src/main/resources/codegen-resources/customization.config, services/mediastoredata/src/main/resources/codegen-resources/customization.config, services/transcribe/src/main/resources/codegen-resources/customization.config, services/transcribestreaming/src/main/resources/codegen-resources/customization.config
Switching a set of services onto the new SRA (Smithy Reference Architecture) identity and auth logic that was released in v2.21.0. 
Services (service id):
- backupstorage
- codecatalyst
- cognitoidentity
- cognitoidentityprovider
- iam
- kinesis
- mediastoredata
- transcribe
- transcribestreaming
=> Activating SRA auth for services with specific signer behaviors, and iam

.changes/next-release/bugfix-AWSCRTHTTPClient-7e448e2.json, http-clients/aws-crt-client/src/main/java/software/amazon/awssdk/http/crt/internal/response/CrtResponseAdapter.java, http-clients/aws-crt-client/src/main/java/software/amazon/awssdk/http/crt/internal/response/InputStreamAdaptingHttpStreamResponseHandler.java, http-clients/aws-crt-client/src/main/java/software/amazon/awssdk/http/crt/internal/response/ResponseHandlerHelper.java, http-clients/aws-crt-client/src/test/java/software/amazon/awssdk/http/crt/internal/BaseHttpStreamResponseHandlerTest.java, pom.xml
If stream is null and `stream.incrementWindow` is invoked, JVM will crash. This can happen if [onResponseComplete](https://github.com/aws/aws-sdk-java-v2/blob/master/http-clients/aws-crt-client/src/main/java/software/amazon/awssdk/http/crt/internal/response/CrtResponseAdapter.java#L107) gets invoked before [responsePublisher.send() future](https://github.com/aws/aws-sdk-java-v2/blob/master/http-clients/aws-crt-client/src/main/java/software/amazon/awssdk/http/crt/internal/response/CrtResponseAdapter.java#L92) completes in onResponseBody.
CRT is working on the change to make `stream.incrementWindow` no-op if the stream is closed. Meanwhile this change checks if stream is closed before trying to increment window.
This change also bumps crt version.
Added unit tests. Running our test suites.
=> Check if stream is closed before trying to increment window.

services-custom/dynamodb-enhanced/src/main/java/software/amazon/awssdk/enhanced/dynamodb/DynamoDbAsyncTable.java
=> A few corrections in DynamoDbAsyncTable javadoc

.changes/next-release/bugfix-AWSSDKforJavav2-8b416ff.json, .changes/next-release/feature-AWSSDKforJavav2-9014236.json, core/auth/src/main/java/software/amazon/awssdk/auth/credentials/ProfileCredentialsProvider.java, core/http-auth-aws/src/main/java/software/amazon/awssdk/http/auth/aws/internal/signer/chunkedencoding/ChunkedEncodedInputStream.java
The following changes were made:
- Fixed bug where the ProfileCredentialsProvider would re-read the credentials file with each request by default
- Improved performance of chunk-encoded streaming uploads, like S3's PutObject
=> Performance improvements

.changes/next-release/feature-AWSSDKforJavav2-2c52c12.json, core/auth/src/main/java/software/amazon/awssdk/auth/credentials/InstanceProfileCredentialsProvider.java, core/auth/src/main/java/software/amazon/awssdk/auth/credentials/internal/Ec2MetadataDisableV1Resolver.java, core/auth/src/main/java/software/amazon/awssdk/auth/credentials/internal/ProfileCredentialsUtils.java, core/auth/src/test/java/software/amazon/awssdk/auth/credentials/InstanceProfileCredentialsProviderTest.java, core/auth/src/test/java/software/amazon/awssdk/auth/credentials/internal/Ec2MetadataDisableV1ResolverTest.java, core/profiles/src/main/java/software/amazon/awssdk/profiles/ProfileProperty.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/SdkSystemSetting.java, test/auth-tests/src/it/java/software/amazon/awssdk/auth/sts/ProfileCredentialsProviderIntegrationTest.java
Currently, InstanceProfileCredentialsProvider makes credentials call to the EC2 Instance Metadata Service (IMDS) by first attempting to fetch a token which is then attached to the credentials call, to provide better security. If token fetching fails due to some errors (403, 404, 405) or timeouts, the provider makes an unsecure call without the token header. 
For some use cases, this fallback behavior with unsecure, IMDS v1 style calls without a token is forbidden. To facilitate disabling this fallback, this PR adds a configuration option. 
Note that currently, it's only IMDS credential calls that honor the config option. Other calls to IMDS for region etc are not affected. 
- Adds setting to disable IMDS v1 fallback through 
- Environment variables (`AWS_EC2_METADATA_V1_DISABLED`)
- …
=> Add option to disable IMDS v1 fallback when token is not returned

codegen/src/main/java/software/amazon/awssdk/codegen/AddOperations.java, codegen/src/main/java/software/amazon/awssdk/codegen/compression/RequestCompression.java, codegen/src/main/java/software/amazon/awssdk/codegen/model/intermediate/OperationModel.java, codegen/src/main/java/software/amazon/awssdk/codegen/model/service/Operation.java, codegen/src/main/java/software/amazon/awssdk/codegen/poet/client/traits/RequestCompressionTrait.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/c2j/json/service-2.json, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/c2j/query/service-2.json, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/c2j/rest-json/service-2.json, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/c2j/xml/service-2.json, test/codegen-generated-classes-test/src/main/resources/codegen-resources/customresponsemetadata/service-2.json
Request Compression trait name is all lowercase `requestcompression`, but Java currently looks for `requestCompression`
Updated codegen to get `requestcompression`
Updated test models and ran tests successfully
=> Update requestcompression codegen name

.changes/next-release/bugfix-AmazonSimpleStorageService-4b6b8dd.json, services/s3/src/it/java/software/amazon/awssdk/services/s3/crossregion/S3CrossRegionAsyncIntegrationTestBase.java, services/s3/src/it/java/software/amazon/awssdk/services/s3/crossregion/S3CrossRegionIntegrationTestBase.java, services/s3/src/it/java/software/amazon/awssdk/services/s3/crossregion/S3CrossRegionSyncIntegrationTest.java, services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/crossregion/S3CrossRegionAsyncClient.java, services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/crossregion/S3CrossRegionSyncClient.java, services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/crossregion/endpointprovider/BucketEndpointProvider.java, services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/crossregion/utils/CrossRegionUtils.java, services/s3/src/test/java/software/amazon/awssdk/services/s3/internal/crossregion/S3CrossRegionAsyncClientRedirectTest.java, services/s3/src/test/java/software/amazon/awssdk/services/s3/internal/crossregion/S3CrossRegionAsyncClientTest.java, services/s3/src/test/java/software/amazon/awssdk/services/s3/internal/crossregion/S3CrossRegionRedirectTestBase.java, services/s3/src/test/java/software/amazon/awssdk/services/s3/internal/crossregion/S3CrossRegionSyncClientRedirectTest.java, services/s3/src/test/java/software/amazon/awssdk/services/s3/internal/crossregion/S3CrossRegionSyncClientTest.java
Fix for issue #4720 , Cross Region enabled Clients created in US-EAST-1 will by internally disable global endpoint and do a regional endpoint call.
In Version 2 (V2), when calling from "US-EAST-1" and "AWS_GLOBAL" regions, we directly address the global endpoint. For instance:
`Host: mumbai-crossregion-bucket.s3.amazonaws.com`
Here, the region is global, and the signing region is "us-east-1". 
For other client regions (e.g., us-east-2), we send requests to regional endpoints:
`Host: mumbai-crossregion-bucket.us-east-2.s3.amazonaws.com`
In this case, the signing region is "us-east-2". When HeadObject is called on the global endpoint, the service does not throw redirect errors; it redirects only for regional endpoints.
However , the S3 Cross region relies on the service to send the redirect …
=> Fix for issue #4720 , Cross Region enabled Clients created in US-EAST-1 will by internally disable global endpoint and do a regional endpoint call.

core/http-auth-spi/src/main/java/software/amazon/awssdk/http/auth/spi/signer/BaseSignRequest.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/http/pipeline/stages/SigningStage.java
1. Do not call SignerProperty.toString() whenever required properties are read. 
2. Check if an SdkHttpRequest is an SdkHttpFullRequest before performing a full conversion to the latter.
=> Performance improvements for SRA changes.

core/sdk-core/src/main/java/software/amazon/awssdk/core/interceptor/ExecutionInterceptorChain.java
1. Removed apply*Hack method. This method wasn't doing anything, because its side effects were immediately overridden.
2. Do not modify the execution context in the modify* methods unless the interceptor requests a modification. The time added by the comparisons are less than the cost of always modifying the interceptor context, because modifying the execution context is relatively rare.
=> Performance optimizations in ExecutionInterceptorChain

.changes/next-release/feature-AWSSDKforJavav2-a5aec87.json, core/http-auth-aws/src/main/java/software/amazon/awssdk/http/auth/aws/crt/internal/signer/AwsChunkedV4aPayloadSigner.java, core/http-auth-aws/src/main/java/software/amazon/awssdk/http/auth/aws/crt/internal/signer/RollingSigner.java, core/http-auth-aws/src/main/java/software/amazon/awssdk/http/auth/aws/crt/internal/signer/SigV4aChunkExtensionProvider.java, core/http-auth-aws/src/main/java/software/amazon/awssdk/http/auth/aws/internal/signer/AwsChunkedV4PayloadSigner.java, core/http-auth-aws/src/main/java/software/amazon/awssdk/http/auth/aws/internal/signer/chunkedencoding/ChunkExtensionProvider.java, core/http-auth-aws/src/main/java/software/amazon/awssdk/http/auth/aws/internal/signer/chunkedencoding/ChunkHeaderProvider.java, core/http-auth-aws/src/main/java/software/amazon/awssdk/http/auth/aws/internal/signer/chunkedencoding/ChunkedEncodedInputStream.java, core/http-auth-aws/src/main/java/software/amazon/awssdk/http/auth/aws/internal/signer/chunkedencoding/SigV4ChunkExtensionProvider.java, core/http-auth-aws/src/main/java/software/amazon/awssdk/http/auth/aws/internal/signer/util/SignerUtils.java, core/http-auth-aws/src/test/java/software/amazon/awssdk/http/auth/aws/internal/signer/chunkedencoding/ChunkedEncodedInputStreamTest.java
Before this change, our chunk encoding logic would copy customer data five times:
1. [From the customer's stream into a byte array.](https://github.com/aws/aws-sdk-java-v2/blob/6040b2be6731e4b5ef64e775a2cfffb07d76766c/core/http-auth-aws/src/main/java/software/amazon/awssdk/http/auth/aws/internal/signer/chunkedencoding/ChunkedEncodedInputStream.java#L106-L107)
2. [From the byte array into a slightly smaller byte array.](https://github.com/aws/aws-sdk-java-v2/blob/6040b2be6731e4b5ef64e775a2cfffb07d76766c/core/http-auth-aws/src/main/java/software/amazon/awssdk/http/auth/aws/internal/signer/chunkedencoding/ChunkedEncodedInputStream.java#L111)
3. [From the smaller byte array into a byte array output stream.](https://github.com/aws/aws-sdk-java-v2/blob/6040b2be6731e4b5ef64e775a2cfffb07d76766c/co …
=> Reduce memory usage for chunk-encoded streaming uploads, like those used by flexible checksums in S3.

buildspecs/release-to-github.yml
The original check checks whether the tag *exists* in the local and then tries to remove it from the public repo. However, it's possible that the tag is in the private repo, where it might not exists (refs from both remotes are present locally).
This commit fixes this by explicitly check if the tag exists in the public repo and only then will it try to delete it.
=> Fix check for release tag

core/http-auth-aws/src/main/java/software/amazon/awssdk/http/auth/aws/internal/signer/checksums/Crc32CChecksum.java, core/http-auth-aws/src/main/java/software/amazon/awssdk/http/auth/aws/internal/signer/checksums/Crc32Checksum.java
We use a thread local, because the classpath helper used to load the CRT may use the thread-level class loader.
=> Cache whether CRT is available in the flexible checksum algorithm.

services/backupstorage/src/main/resources/codegen-resources/customization.config, services/codecatalyst/src/main/resources/codegen-resources/customization.config, services/cognitoidentity/src/main/resources/codegen-resources/customization.config, services/kinesis/src/main/resources/codegen-resources/customization.config, services/mediastoredata/src/main/resources/codegen-resources/customization.config, services/transcribe/src/main/resources/codegen-resources/customization.config, services/transcribestreaming/src/main/resources/codegen-resources/customization.config
Enable compiled endpoint rules for the second wave of services.
Services included are: 
* backupstorage, 
* codecatalyst, 
* cognitoidentity, 
* kinesis, 
* mediastoredata, 
* transcribe, 
* transcribestreaming
=> Enable compiled endpoint rules for the second wave

core/http-auth-aws/src/main/java/software/amazon/awssdk/http/auth/aws/internal/signer/V4CanonicalRequest.java, core/http-auth-aws/src/test/java/software/amazon/awssdk/http/auth/aws/internal/signer/V4CanonicalRequestTest.java
This is a reintroduction of the reverted commit https://github.com/aws/aws-sdk-java-v2/pull/4867. This includes a fix to the issue that caused the revert: improper handling of empty header values.
=> Performance improvement for sigv4 signing.

.changes/next-release/feature-AWSCRTbasedS3Client-353870f.json, .changes/next-release/feature-AmazonS3-c28f9de.json, pom.xml, services/s3/src/main/java/software/amazon/awssdk/services/s3/S3CrtAsyncClientBuilder.java, services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/crt/DefaultS3CrtAsyncClient.java, services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/crt/S3CrtAsyncHttpClient.java, services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/crt/S3NativeClientConfiguration.java, services/s3/src/test/java/software/amazon/awssdk/services/s3/internal/crt/S3CrtAsyncHttpClientTest.java
CRT has published a new setting to limit memory used when making S3 calls.
- Updated CRT version
- Added new parameter
- Added Javadoc description for parameter, and for throughput
Unit tested
=> Bump CRT version and expose setting memory limits for S3 calls

.changes/next-release/bugfix-AWSCRTSyncHTTPClient-660cc21.json, http-clients/aws-crt-client/src/main/java/software/amazon/awssdk/http/crt/AwsCrtHttpClient.java, http-clients/aws-crt-client/src/test/java/software/amazon/awssdk/http/crt/AwsCrtHttpClientWireMockTest.java, test/protocol-tests/pom.xml, test/protocol-tests/src/test/java/software/amazon/awssdk/protocol/tests/timeout/CrtHttpClientApiCallTimeoutTest.java
Fixed an issue where `CancellationException` was thrown incorrectly from AWS CRT Sync HTTP client when execution time exceeded the total configured API call attempt timeout or API call timeout. Now it throws `ApiCallAttemptTimeoutException`/`ApiCallTimeoutException` accordingly. Closes [#4820](https://github.com/aws/aws-sdk-java-v2/issues/4820)
Ensure the right exception is thrown the request is aborted so that the SDK core can translate the exception to the corresponding `ApiCallAttemptTimeoutException` and `ApiCallTimeoutException`.
https://github.com/aws/aws-sdk-java-v2/blob/767b527f17ca295f48e9c9ab0e3dc9036e993e1b/core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/http/pipeline/stages/TimeoutExceptionHandlingStage.java#L92-L97
=> Fix request cancellation logic in the AWS CRT Sync HTTP client

.changes/next-release/bugfix-AmazonS3-04d48e6.json, services/s3/src/it/java/software/amazon/awssdk/services/s3/multipart/S3ClientMultiPartCopyIntegrationTest.java, services/s3/src/it/java/software/amazon/awssdk/services/s3/multipart/S3MultipartClientPutObjectIntegrationTest.java, services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/multipart/GenericMultipartHelper.java, services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/multipart/MultipartS3AsyncClient.java, services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/multipart/SdkPojoConversionUtils.java, services/s3/src/main/resources/codegen-resources/customization.config, services/s3/src/test/java/software/amazon/awssdk/services/s3/internal/multipart/MultipartClientChecksumTest.java, services/s3/src/test/java/software/amazon/awssdk/services/s3/internal/multipart/SdkPojoConversionUtilsTest.java
1) Fix bug where PUT fails when using SSE-C with Checksum
2) Enable CRC32 for PUT for MultipartS3AsyncClient -> Keep behavior consistent between CRT TransferManager and Java TransferManager
Copy over SSE-C fields when converting requests.
Set CRC32 for PUT in multipart client IF checksum is not set by user && checksum validation is not disabled
added unit + integ tests
=> Enable CRC32 for PUT for MultipartS3AsyncClient

.changes/2.24.0.json, CHANGELOG.md
=> Backfilling changelog to include signing attribute changes

.changes/next-release/bugfix-AmazonSimpleStorageService-7648336.json, services/s3/src/it/java/software/amazon/awssdk/services/s3/crossregion/S3CrossRegionCrtIntegrationTest.java, services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/crossregion/endpointprovider/BucketEndpointProvider.java, services/s3/src/test/java/software/amazon/awssdk/services/s3/internal/crossregion/S3CrossRegionAsyncClientTest.java, services/s3/src/test/java/software/amazon/awssdk/services/s3/internal/crossregion/S3CrossRegionSyncClientTest.java
-  Issue #4912
- Note that PR #4849 add fix to enable regional endpoints by setting useGlobalEndpoint , however this doesnot work for AWS_GLOBAL region.
- Also if we try to make direct calls with AWS_GLOBAL without disabling useGlobalEndpoint then we will not get the Redirected region for `Head` Apis like "HeadObject" and "HeadBucket".
- Thus we need to update the AWS_GLOBAL as "US_EAST_1" in order to get the redirected region
- Update Region as  "US_EAST_1" if the call is made from AWS_GLOBAL.
- This makes sure we do a regional endpoint call to get the redirected region
=> Fix for Issue #4912 where Cross Region S3 Access using AWS_GLOBAL Endpoint failed.

.github/workflows/codebuild-ci.yml
Update codebuild-ci.yml to trigger CI on doc changes so that PRs like https://github.com/aws/aws-sdk-java-v2/pull/4853 can be merged w/o requiring me to run the scrip to trigger CI.
=> Update codebuild-ci.yml to trigger CI on doc changes

.changes/next-release/feature-AmazonS3-a20b910.json, services-custom/s3-transfer-manager/src/it/java/software/amazon/awssdk/transfer/s3/S3IntegrationTestBase.java, services-custom/s3-transfer-manager/src/it/java/software/amazon/awssdk/transfer/s3/S3TransferManagerUploadPauseResumeIntegrationTest.java, services-custom/s3-transfer-manager/src/main/java/software/amazon/awssdk/transfer/s3/internal/CrtS3TransferManager.java, services-custom/s3-transfer-manager/src/main/java/software/amazon/awssdk/transfer/s3/internal/GenericS3TransferManager.java, services-custom/s3-transfer-manager/src/main/java/software/amazon/awssdk/transfer/s3/internal/PauseResumeHelper.java, services-custom/s3-transfer-manager/src/main/java/software/amazon/awssdk/transfer/s3/internal/model/CrtFileUpload.java, services-custom/s3-transfer-manager/src/main/java/software/amazon/awssdk/transfer/s3/internal/model/DefaultFileUpload.java, services-custom/s3-transfer-manager/src/main/java/software/amazon/awssdk/transfer/s3/model/FileUpload.java, services-custom/s3-transfer-manager/src/test/java/software/amazon/awssdk/transfer/s3/internal/DefaultFileUploadTest.java, services-custom/s3-transfer-manager/src/test/java/software/amazon/awssdk/transfer/s3/internal/S3TransferManagerUploadPauseAndResumeTest.java, services-custom/s3-transfer-manager/src/test/java/software/amazon/awssdk/transfer/s3/internal/UploadDirectoryHelperTest.java, services/s3/pom.xml, services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/multipart/CancelledSubscriber.java, services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/multipart/KnownContentLengthAsyncRequestBodySubscriber.java, services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/multipart/MpuRequestContext.java, services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/multipart/MultipartUploadHelper.java, services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/multipart/PausableUpload.java, services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/multipart/SdkPojoConversionUtils.java, services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/multipart/UploadWithKnownContentLengthHelper.java, services/s3/src/main/java/software/amazon/awssdk/services/s3/multipart/PauseObservable.java, services/s3/src/main/java/software/amazon/awssdk/services/s3/multipart/S3PauseResumeExecutionAttribute.java, services/s3/src/main/java/software/amazon/awssdk/services/s3/multipart/S3ResumeToken.java, services/s3/src/test/java/software/amazon/awssdk/services/s3/internal/multipart/KnownContentLengthAsyncRequestBodySubscriberTest.java, services/s3/src/test/java/software/amazon/awssdk/services/s3/internal/multipart/MpuRequestContextTest.java, services/s3/src/test/java/software/amazon/awssdk/services/s3/internal/multipart/MpuTestUtils.java, services/s3/src/test/java/software/amazon/awssdk/services/s3/internal/multipart/SdkPojoConversionUtilsTest.java, services/s3/src/test/java/software/amazon/awssdk/services/s3/internal/multipart/UploadObjectHelperTest.java, services/s3/src/test/java/software/amazon/awssdk/services/s3/multipart/S3ResumeTokenTest.java
Merging feature branch into master
https://github.com/aws/aws-sdk-java-v2/pull/4908
Currently pausing/resuming a file upload with TransferManager is only supported with CRT S3 Client.
Adding support when using Java S3 Client with Multipart enabled.
added unit and integ tests
=> Pause/Resume Upload for Transfer Manager w/ Java S3Client w/ Multipart enabled

test/codegen-generated-classes-test/src/test/java/software/amazon/awssdk/services/BlockingAsyncRequestResponseBodyResourceManagementTest.java
=> Fix flaky tests

core/sdk-core/src/main/java/software/amazon/awssdk/core/client/config/SdkAdvancedAsyncClientOption.java
Using `Runnable::run` as future completion thread is dangerous if users send another SDK request in the completablefuture chain since the SDK may perform blocking calls.
Update documentation for `FUTURE_COMPLETION_EXECUTOR` to discourage the use of `Runnable::run`
=> Update documentation for FUTURE_COMPLETION_EXECUTOR

.brazil.json, buildspecs/release-javadoc.yml, buildspecs/release-to-maven.yml, codegen/src/main/java/software/amazon/awssdk/codegen/poet/auth/scheme/AuthSchemeInterceptorSpec.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/auth/scheme/query-auth-scheme-interceptor.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/auth/scheme/query-endpoint-auth-params-with-allowlist-auth-scheme-interceptor.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/auth/scheme/query-endpoint-auth-params-without-allowlist-auth-scheme-interceptor.java, core/http-auth-aws/src/main/java/software/amazon/awssdk/http/auth/aws/internal/scheme/DefaultAwsV4aAuthScheme.java, pom.xml, test/codegen-generated-classes-test/src/test/java/software/amazon/awssdk/services/AuthSchemeInterceptorTest.java, test/crt-unavailable-tests/pom.xml, test/crt-unavailable-tests/src/test/java/software/amazon/awssdk/auth/aws/AwsV4aAuthSchemeTest.java
This commit fixes the generated auth scheme selection mechanism by ensuring that auth scheme is able to provide a signer implementation (i.e. does not throw an exception) before selecting the auth scheme. This is useful in situations where the signer implementation relies on components thay may not be available at runtime, such as the AwsV4aAuthScheme, which relies on CRT which is an optional dependency.
Additional changes:
- introduce crt-unavailable-tests which is a good candidate for testing behavior of components that use CRT when CRT is not present.
- modify DefaultAwsV4aAuthScheme so that errors thrown during static initialization of the singleton holder for the Sigv4a signer are caught and thrown directly instead of resulting in ExceptionInInitializerError
- New unit tests
=> Choose next potential scheme if signer not found

.changes/next-release/bugfix-AWSSDKforJavav2-6454991.json, core/sdk-core/src/test/java/software/amazon/awssdk/core/internal/http/timers/HttpClientApiCallTimeoutTest.java, http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/internal/http2/Http2PingHandler.java, http-clients/netty-nio-client/src/test/java/software/amazon/awssdk/http/nio/netty/fault/PingTimeoutTest.java, http-clients/netty-nio-client/src/test/java/software/amazon/awssdk/http/nio/netty/fault/ServerNotRespondingTest.java, http-clients/netty-nio-client/src/test/java/software/amazon/awssdk/http/nio/netty/internal/http2/Http2PingHandlerTest.java
Current PING timeout logic doesnt work well when there are delays in scheduling or flushing to socket.
```
Scenario we want to avoid is shown below (NOTE: ptm - pingTimeoutMillis, Wx - Write Ping x, Fx - Flush Ping x, Rx - Receive ack x, T -Timeout)
When timer is scheduled periodically, even though ack2 comes < ptm after being flushed to the socket, we
will still timeout at 2ptm.        
0          1ptm       2ptm       3ptm
|----------|----------|----------|-------> time
W1F1 R1    W2      F2 T  R2
When timer is scheduled after flushing, we allow time for ack to come back and not prematurely timeout.
0            ptm1               ptm2
|-|----------|------|----------|-----------> time
W1F1 R1      W2     F2   R2    W3
```
The change prevents premature closing of the HTTP2 connection. …
=> Improve Http2 ping timeout logic

codegen/src/main/java/software/amazon/awssdk/codegen/AddMetadata.java, codegen/src/main/java/software/amazon/awssdk/codegen/AddOperations.java, codegen/src/main/java/software/amazon/awssdk/codegen/model/config/customization/CustomizationConfig.java, codegen/src/main/java/software/amazon/awssdk/codegen/model/service/AuthType.java, codegen/src/test/java/software/amazon/awssdk/codegen/model/service/AuthTypeTest.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/c2j/all-ops-with-auth-different-value/customization.config, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/c2j/all-ops-with-auth-same-value/customization.config, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/c2j/fine-grained-auth/customization.config, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/c2j/ops-with-no-auth/customization.config, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/c2j/service-with-no-auth/customization.config
Make conversion of multi-auth opt-in
Currently, `metadata.auth` and `operation.auth` are read although full
support for multi-auth is not implemented yet.
This change allows reading these `auth` values to be opt-in, especially
for `useSraAuth` tests.
Also, allows conversions of select smithy auth trait shape IDs into
`AuthType`s:
- `smithy.api#httpBearerAuth => BEARER`
- `smithy.api#noAuth => NONE`
- `aws.auth#sigv4 => V4`
Only read from `metadata.auth` and `operation.auth` if `useMultiAuth` is true in the customization config.
The tests using `auth` have their customization config `useMultiAuth` set to true.
In `AuthType::fromValue()`, allow converting smithy auth trait IDs to `AuthType`.
- `smithy.api#httpBearerAuth => BEARER`
- `smithy.api#noAuth => NONE`
- `aws.auth#sigv4 => V4`
Added …
=> Make conversion of multi-auth opt-in

.changes/next-release/bugfix-AWSSDKforJavav2-9bd9da8.json, http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/internal/http2/Http2PingHandler.java, http-clients/netty-nio-client/src/test/java/software/amazon/awssdk/http/nio/netty/internal/http2/Http2PingHandlerTest.java
Improve PING timeout logic to avoid premature closing of the connection that can occur due to delays in scheduling of writing PING frame to the channel and/or flushing it to the socket.
Current PING timeout logic doesnt work well when there are delays in scheduling or flushing to socket.
```
Scenario we want to avoid is shown below (NOTE: ptm - pingTimeoutMillis, Wx - Write Ping x, Fx - Flush Ping x, Rx - Receive ack x, T -Timeout)
When timer is scheduled periodically, even though ack2 comes < ptm after being flushed to the socket, we
will still timeout at 2ptm.        
0          1ptm       2ptm       3ptm
|----------|----------|----------|-------> time
W1F1 R1    W2      F2 T  R2
When timer is scheduled after flushing, we allow time for ack to come back and not prematurely timeout.
0 …
```
=> Improve HTTP2/PING timeout logic

http-clients/url-connection-client/src/main/java/software/amazon/awssdk/http/urlconnection/UrlConnectionHttpClient.java, http-clients/url-connection-client/src/test/java/software/amazon/awssdk/http/urlconnection/HeadersListTest.java
This reverts commit e715bb6c9554de9ee39a8e8c33f5c7a2626f4615.
X-ray has fixed a risk of customers double-adding the x-ray interceptor, and SQS will no longer reject requests with "invalid" x-ray trace IDs. It should be safe to re-release this URL connection fix for multi-value headers.
=> Revert "Revert "Handle header lists in URLConnection client (#4897)" (#4960)"

codegen/src/main/java/software/amazon/awssdk/codegen/docs/DocumentationBuilder.java, codegen/src/test/java/software/amazon/awssdk/codegen/model/intermediate/DocumentationBuilderTest.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/sra/test-aws-json-async-client-class.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/sra/test-json-async-client-class.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/sra/test-query-async-client-class.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/sra/test-xml-async-client-class.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/test-abstract-async-client-class.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/test-aws-json-async-client-class.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/test-aws-query-compatible-json-async-client-class.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/test-custompackage-async.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/test-customservicemetadata-async.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/test-endpoint-discovery-async.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/test-json-async-client-class.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/test-json-async-client-interface.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/test-query-async-client-class.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/test-xml-async-client-class.java
The exception returned by the SDK client is wrapped with `CompletionException` see below. We can't change it due to backwards compatibility reasons, so we are updating this doc to mention this behavior.
```
public static void main(String[] args) {
var sqs = SqsAsyncClient.create();
sqs.getQueueUrl(GetQueueUrlRequest.builder().queueName("invalidqueuename").build())
.whenComplete((url, e) -> {
System.out.println("Exception: " + e);
})
.join();
}
```
prints out
```
Exception: java.util.concurrent.CompletionException: software.amazon.awssdk.services.sqs.model.QueueDoesNotExistException: 
The specified queue does not exist for this wsdl version. (Service: Sqs, Status Code: 400, Request ID: xxxx)
```
Update documentation
=> Update javadoc regarding exception handling in async clients

services-custom/s3-transfer-manager/src/main/java/software/amazon/awssdk/transfer/s3/internal/GenericS3TransferManager.java, services-custom/s3-transfer-manager/src/main/java/software/amazon/awssdk/transfer/s3/internal/progress/ContentRangeParser.java, services-custom/s3-transfer-manager/src/main/java/software/amazon/awssdk/transfer/s3/internal/progress/TransferProgressUpdater.java, services-custom/s3-transfer-manager/src/test/java/software/amazon/awssdk/transfer/s3/internal/TransferProgressUpdaterTest.java, services-custom/s3-transfer-manager/src/test/java/software/amazon/awssdk/transfer/s3/internal/progress/ContentRangeParserTest.java
Change `TransferProgressUpdater` so it uses Content-Range header to determine the maximum number of bytes it tracks as part of the transfer progress listener.
For downloads, `TransferProgressUpdater` was expecting the totalBytes of the whole s3 object to be the value of the `Content-Length` header, when in fact the `Content-Length` header only contains the size of the current part. This cause the value of transferred bytes to exceed to the number total byte expected as soon as a 2nd part was dowloaded.
Add a `ContentRangeParser` class to extract the total object size from the `Content-Range` header, following the **[MDN refgerence](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Range)**. Only support `bytes` unit.
- Added unit tests.
- Manual testing with s3 object.
=> Use Content-Range in multipart download for totalBytes

test/s3-benchmarks/src/main/java/software/amazon/awssdk/s3benchmarks/NoOpResponseTransformer.java, test/s3-benchmarks/src/main/java/software/amazon/awssdk/s3benchmarks/TransferManagerDownloadBenchmark.java
Transfer Manager Benchmarks that download to memory with java-based client would hang because the result of the future in `NoOpResponseTransformer` is set to null. Eventually, this null reaches the **[CompletedFileDownload constructor](https://github.com/aws/aws-sdk-java-v2/blob/cfcfb6d48a65eaae6167bbe382ee14399a9976d6/services-custom/s3-transfer-manager/src/main/java/software/amazon/awssdk/transfer/s3/model/CompletedFileDownload.java#L36-L38)**  which assert that it must not be null. It is called from the **[generic transfer manager code path](https://github.com/aws/aws-sdk-java-v2/blob/cfcfb6d48a65eaae6167bbe382ee14399a9976d6/services-custom/s3-transfer-manager/src/main/java/software/amazon/awssdk/transfer/s3/internal/GenericS3TransferManager.java#L381-L384)**
During java-based …
=> s3-becnhmarks - Change NoopTransformer type-param to Object

build-tools/src/main/resources/software/amazon/awssdk/spotbugs-suppressions.xml, migration-tool/src/main/java/software/amazon/awssdk/migration/recipe/ChangeSdkType.java, migration-tool/src/main/java/software/amazon/awssdk/migration/recipe/utils/NamingConversionUtils.java
Fix checkstyle errors and suppress spotbug errors for ChangeSdkType
=> Fix checkstyle errors and suppress spotbug errors for ChangeSdkType

migration-tool/src/main/resources/META-INF/rewrite/change-region-types.yml, migration-tool/src/main/resources/META-INF/rewrite/change-sdk-core-types.yml, migration-tool/src/test/java/software/amazon/awssdk/migration/recipe/ChangeRegionTypesTest.java
Support Regions migration 
Support Regions migration 
v1
```
Regions region = Regions.fromName("us-east-1");
Regions region2 = Regions.US_EAST_1;
```
to v2
```
Region region = Region.of("us-east-1");
Region region2 = Region.US_EAST_1;
```
=> Support Regions migration

migration-tool/pom.xml, migration-tool/src/main/java/software/amazon/awssdk/migration/internal/recipe/NewV1ClassToBuilder.java, migration-tool/src/main/java/software/amazon/awssdk/migration/internal/recipe/V1SetterToV2.java, migration-tool/src/main/java/software/amazon/awssdk/migration/internal/utils/NamingConversionUtils.java, migration-tool/src/main/java/software/amazon/awssdk/migration/internal/utils/NamingUtils.java, migration-tool/src/main/java/software/amazon/awssdk/migration/internal/utils/SdkTypeUtils.java, migration-tool/src/main/java/software/amazon/awssdk/migration/recipe/ChangeSdkType.java, migration-tool/src/main/java/software/amazon/awssdk/migration/recipe/NewV1ModelClassToV2.java, migration-tool/src/main/resources/META-INF/rewrite/java-sdk-v1-to-v2.yml, migration-tool/src/test/java/software/amazon/awssdk/migration/internal/utils/NamingConversionUtilsTest.java, migration-tool/src/test/java/software/amazon/awssdk/migration/internal/utils/NamingUtilsTest.java, migration-tool/src/test/java/software/amazon/awssdk/migration/internal/utils/SdkTypeUtilsTest.java, migration-tool/src/test/java/software/amazon/awssdk/migration/recipe/NewV1ModelClassToV2Test.java, test/migration-tool-tests/src/test/resources/after/src/main/java/software/amazon/awssdk/migration/tool/Application.java, test/migration-tool-tests/src/test/resources/before/src/main/java/software/amazon/awssdk/migration/tool/Application.java
This recipe transforms the usage of a V1 request class using the `new`
keyword to using the V2 class and its builder.
This recipe migrates many common uses for making API calls using the V1
SDK:
Creating the request outside of the API call and then passing it in as a
name variable:
```
SendMessageRequest request = new SendMessage().withQueueUrl(..);
sqs.sendMessage(request);
```
or creating it inline
```
sqs.sendMessage(new SendMessageRequest().withQueueUrl(...));
```
=> Add NewV1ClassToBuilder recipe

services-custom/s3-transfer-manager/src/test/java/software/amazon/awssdk/transfer/s3/internal/S3TransferManagerTest.java, utils/src/main/java/software/amazon/awssdk/utils/CompletableFutureUtils.java, utils/src/test/java/software/amazon/awssdk/utils/CompletableFutureUtilsTest.java
When using `CompletableFutureUtils.forwardTransformedResultTo` if the provided function throws an exception, it would not be catch which can prevent the destination future to be completed and hang on a `.join()` call.
Discovered during perf testing multipart s3 async client, as one of the test returned a null value.
Surround the call to `Function.apply()` with a try-catch and complete the destination future with the caught exception.
Added unit test to CompletableUtils and TransferManager
=> Fix for threads hanging with forwardTransformedResultTo

codegen/src/main/java/software/amazon/awssdk/codegen/poet/rules/EndpointRulesSpecUtils.java, codegen/src/main/java/software/amazon/awssdk/codegen/poet/rules/RuleSetCreationSpec.java, codegen/src/main/java/software/amazon/awssdk/codegen/poet/rules2/EndpointProviderSpec2.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/auth/scheme/query-endpoint-auth-params-auth-scheme-default-params-without-allowlist.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/auth/scheme/query-endpoint-auth-params-auth-scheme-endpoint-provider-without-allowlist.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/auth/scheme/query-endpoint-auth-params-auth-scheme-params-without-allowlist.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/auth/scheme/query-endpoint-auth-params-without-allowlist-auth-scheme-interceptor.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/c2j/query/endpoint-rule-set.json, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/rules/endpoint-parameters.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/rules/endpoint-provider-class.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/rules/endpoint-provider-know-prop-override-class.java
- Generate Endpoint Params and Auth Scheme Params for StringArray type of parameters in  `endpoint-rule-set.json`
- Added case for StringArray parameter type
- Added Junits , 
- Generated a sample S3 code as below
```json
{
"version": "1.0",
"parameters": {
"Bucket": {
"required": false,
"documentation": "The S3 bucket used to send the request. This is an optional parameter that will be set automatically for operations that are scoped to an S3 bucket.",
"type": "String"
},
"DeleteObjectKeys": {
"required": false,
"documentation": "Need delete object keys",
"type": "StringArray"
},
"DefaultDeleteObjectKeys": {
"required": false,
"default": ["one", "two", "three"],
"type": "StringArray"
},
```
```java
@Generated("software.amazon.awssdk:codegen")
@SdkPublicApi
public final class …
```
=> feat(StringArrayEndpointParams) Codegen String Array Enpoint params and Auth schemes params based on end-point-rule-set.json.

test/migration-tool-tests/src/test/resources/run-test
Improve test script to log diff
=> Improve test script to log diff

codegen/src/main/java/software/amazon/awssdk/codegen/IntermediateModelBuilder.java, codegen/src/main/java/software/amazon/awssdk/codegen/model/config/customization/CustomizationConfig.java, codegen/src/test/java/software/amazon/awssdk/codegen/poet/ClientTestModels.java, codegen/src/test/java/software/amazon/awssdk/codegen/poet/rules/EndpointProviderInterfaceSpecTest.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/c2j/query/customization-with-duplicate-endpointparameter.config, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/c2j/query/customization.config, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/rules/endpoint-parameters.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/rules/endpoint-provider-class.java
Support Customization string array endpoint params for S3 access grants, until all SDKs add support for string array.
- S3 Access will not do model changes until StringArray is supported for all the SDKs.
- Thus we need to add Customization for S3
- Customization Config classes .
- Added Junits
=> Support Customization string array endpoint params for S3 access grants, until all SDKs add support for string array.

test/migration-tool-tests/src/test/resources/run-test
Use difflib's unified_diff to produce a unified diff between the
expected and actual file. This has the benefit of including the files
compared in the output which makes it easier to do further inspection on
them.
Add a bogus change to the expected `Application.java` file and check the output after running `mvn clean install -pl :migration-tool-tests`
Output:
```
Unexpected diffs found!
--- /Users/dongie/workspace/aws-sdk-java-v2/test/migration-tool-tests/src/test/resources/after/src/main/java/software/amazon/awssdk/migration/tool/Application.java
+++ /Users/dongie/workspace/aws-sdk-java-v2/test/migration-tool-tests/target/generated-test-sources/project/src/main/java/software/amazon/awssdk/migration/tool/Application.java
@@ -21,8 +21,6 @@
import …
```
=> Improve diff output when tests fail

codegen/src/main/java/software/amazon/awssdk/codegen/poet/paginators/PaginatorsClassSpec.java, codegen/src/main/java/software/amazon/awssdk/codegen/poet/paginators/customizations/SameTokenAsyncResponseClassSpec.java, codegen/src/main/java/software/amazon/awssdk/codegen/poet/paginators/customizations/SameTokenSyncResponseClassSpec.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/paginators/PaginatedOperationWithResultKeyAndMoreResultsIterable.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/paginators/PaginatedOperationWithResultKeyAndMoreResultsPublisher.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/paginators/paginators.json, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/paginators/service-2.json, test/codegen-generated-classes-test/pom.xml, test/codegen-generated-classes-test/src/main/resources/codegen-resources/customresponsemetadata/paginators-1.json, test/codegen-generated-classes-test/src/main/resources/codegen-resources/customresponsemetadata/service-2.json, test/codegen-generated-classes-test/src/test/java/software/amazon/awssdk/services/customresponsemetadata/MoreResultsIterableTest.java
Add null check for paginator `hasNextPage()`
Previous
```
@Override
public boolean hasNextPage(ListAliasesResponse previousPage) {
return previousPage.truncated().booleanValue();
}
```
Updated
```
@Override
public boolean hasNextPage(ListAliasesResponse previousPage) {
return previousPage.truncated() != null && previousPage.truncated().booleanValue();
}
```
=> Add null check for paginator hasNextPage

codegen/src/main/java/software/amazon/awssdk/codegen/AddOperations.java, codegen/src/main/java/software/amazon/awssdk/codegen/model/intermediate/OperationModel.java, codegen/src/main/java/software/amazon/awssdk/codegen/model/service/Operation.java, codegen/src/main/java/software/amazon/awssdk/codegen/model/service/OperationContextParam.java, codegen/src/main/java/software/amazon/awssdk/codegen/poet/rules/EndpointResolverInterceptorSpec.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/c2j/query/service-2.json, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/sra/test-query-async-client-class.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/sra/test-query-client-class.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/test-query-async-client-class.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/test-query-client-class.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/rules/endpoint-resolve-interceptor-preSra.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/rules/endpoint-resolve-interceptor.java
Codegeneration of OperationContextParams defined for a Operation.
Note : After JMesPathRuntime implementation , the JMESPath parsing of List will be added. For now I have added a TODO as a place holder.
- Added codegen in EndpointResolverInterceptorSpec to generate code for binding of OperationContext Params to StringArray Endpoint params
- Junit test cases
- Below is code Generated for S3ResolveEndpointInterceptor
- Junit added with a List structure similar to DeleteObjects Keys
```json
"DeleteObjects":{
"name":"DeleteObjects",
"http":{
"method":"POST",
"requestUri":"/{Bucket}?delete"
},
"input":{"shape":"DeleteObjectsRequest"},
"output":{"shape":"DeleteObjectsOutput"},
"documentationUrl":"http://docs.amazonwebservices.com/AmazonS3/latest/API/multiobjectdeleteapi.html", …
```
=> new(StringArrayEndpointParams) Codegeneration of OperationContextParams defined for a Operation.

migration-tool/pom.xml, migration-tool/src/main/java/software/amazon/awssdk/migration/internal/recipe/ConstructorToFluent.java, migration-tool/src/test/java/software/amazon/awssdk/migration/internal/recipe/ConstructorToFluentTest.java
The ConstructorToFluent recipe takes a convenience constructor like
new GetObjectRequest(myBucket, myKey)
and transforms it to use the fluent setter style instead:
new GetObjectRequest().withBucketName(myBucket).withKey(myKey)
This allows us to take advantage of other recipes that for example switch from using the fluent setters to using the V2-style builders.
=> Add ConstructorToFluent recipe

codegen/src/main/java/software/amazon/awssdk/codegen/IntermediateModelBuilder.java, codegen/src/main/java/software/amazon/awssdk/codegen/model/config/customization/CustomizationConfig.java, codegen/src/main/java/software/amazon/awssdk/codegen/model/service/CustomOperationContextParam.java, codegen/src/test/java/software/amazon/awssdk/codegen/poet/rules/EndpointProviderInterfaceSpecTest.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/c2j/query/customization-with-duplicate-operationcontextparams.config, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/c2j/query/customization-with-incorrectName-operationcontextparams.config, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/c2j/query/customization.config, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/c2j/query/service-2.json, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/sra/test-query-async-client-class.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/sra/test-query-client-class.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/test-query-async-client-class.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/test-query-client-class.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/rules/endpoint-resolve-interceptor-preSra.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/rules/endpoint-resolve-interceptor.java, services/s3/src/main/resources/codegen-resources/customization.config
- For S3 the Operation context will be added through Customization.
- This is done because other SDKs have not been updated for the Model changes for operationContextParams
- Add new Customization for OperationCOntextParams
- Added Junits
- Also generated S3 code and made sure it compiles with newly added code.
```java
private static void setOperationContextParams(S3EndpointParams.Builder params, String operationName, SdkRequest request) {
switch (operationName) {
case "DeleteObjects":
setOperationContextParams(params, (DeleteObjectsRequest) request);
break;
default:
break;
}
}
```
```java
private static void setOperationContextParams(S3EndpointParams.Builder params, DeleteObjectsRequest request) {
// TODO: Add JMESPathRuntime for Delete.Objects[*].key
params.deleteObjectKeys(new …
```
=> new(StringArrayEndpointParams) Customization of Operation Context params and adding customizations for S3

migration-tool/src/main/java/software/amazon/awssdk/migration/internal/recipe/V1SetterToV2.java, migration-tool/src/main/java/software/amazon/awssdk/migration/internal/utils/SdkTypeUtils.java, migration-tool/src/main/java/software/amazon/awssdk/migration/recipe/ChangeSdkType.java, migration-tool/src/main/java/software/amazon/awssdk/migration/recipe/V1BuilderVariationsToV2Builder.java, migration-tool/src/main/resources/META-INF/rewrite/java-sdk-v1-to-v2.yml, migration-tool/src/main/resources/META-INF/rewrite/upgrade-sdk-dependencies.yml, migration-tool/src/test/java/software/amazon/awssdk/migration/internal/utils/SdkTypeUtilsTest.java, migration-tool/src/test/java/software/amazon/awssdk/migration/recipe/V1BuilderVariationsToV2BuilderTest.java, test/migration-tool-tests/src/test/resources/after/src/main/java/foo/bar/Application.java, test/migration-tool-tests/src/test/resources/after/src/main/java/foo/bar/SdkClientsDependencyFactory.java, test/migration-tool-tests/src/test/resources/before/src/main/java/foo/bar/Application.java, test/migration-tool-tests/src/test/resources/before/src/main/java/foo/bar/SdkClientsDependencyFactory.java, test/migration-tool-tests/src/test/resources/run-test
This is part 1 of the client config mapping: map builder variations to the standard builder
```
AmazonSQSClientBuilder.standard().build();
```
to
```
SqsClient sqs = SqsClient.builder().build();
```
and 
```
AmazonSQSAsync sqs = AmazonSQSAsyncClient.asyncBuilder().build();
```
to
```
SqsAsyncClient sqs = SqsAsyncClient.builder().build();
```
=> Migration Tool Client Config Part 1: map builder variations to the standard builder

codegen/src/main/java/software/amazon/awssdk/codegen/poet/rules/EndpointProviderSpec.java, codegen/src/main/java/software/amazon/awssdk/codegen/poet/rules/EndpointRulesSpecUtils.java, codegen/src/main/resources/software/amazon/awssdk/codegen/rules/ParameterType.java.resource, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/rules/endpoint-provider-class.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/rules/endpoint-provider-know-prop-override-class.java, test/codegen-generated-classes-test/src/main/resources/codegen-resources/endpointproviders/customization.config, test/codegen-generated-classes-test/src/test/java/software/amazon/awssdk/services/endpointproviders/OperationContextParametersTest.java
The type of the endpoint param, `List<String>`, and the type required by the rules engine, `List<Value>`, are incompatible. Codegen Generated Classes Test cannot compile. 
- Changed the parameter assignment in the rules engine to a list of Value by streaming the endpoint parameter contents and converting each `String` using `Value.fromStr`
- Also added `stringarray` to `ParameterType` - required for Codegen Generated Classes Test tests to compile
=> Converts endpoint param list of string to list of value

core/aws-core/src/main/java/software/amazon/awssdk/awscore/retry/AwsRetryStrategy.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/http/pipeline/stages/utils/RetryableStageHelper2.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/retry/RetryPolicyAdapter.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/retry/SdkDefaultRetryStrategy.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/retry/RetryMode.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/retry/RetryPolicy.java, services/dynamodb/src/main/java/software/amazon/awssdk/services/dynamodb/DynamoDbRetryPolicy.java, services/dynamodb/src/test/java/software/amazon/awssdk/services/dynamodb/DynamoDbRetryPolicyTest.java, test/codegen-generated-classes-test/src/test/java/software/amazon/awssdk/services/retry/Adaptive2ModeCorrectnessTest.java, test/codegen-generated-classes-test/src/test/java/software/amazon/awssdk/services/retry/AsyncRetrySetupTest.java, test/codegen-generated-classes-test/src/test/java/software/amazon/awssdk/services/retry/BaseRetrySetupTest.java, test/codegen-generated-classes-test/src/test/java/software/amazon/awssdk/services/retry/SyncRetrySetupTest.java
This change is aimed to prevent breaking existing users of the legacy adaptive mode while introducing the means needed for new users to onboard and use the correct adaptive implementation.
This change introduces a new `RetryMode` constant, `ADAPTIVE_V2` and uses the legacy `ADAPTIVE` retry policy by adapting it to a retry strategy using the existing adapter when the `ADAPTIVE` mode is requested, either by using `AwsRetryStrategy.forRetryMode(RetryMode.ADAPTIVE)` call, or by setting the `retry_mode=adaptive` value in the profile file or by using the `aws.retryMode=ADAPTIVE` system setting.
Customers that need or want the *correct* adaptive mode will need to use instead `RetryMode.ADAPTIVE_V2`. This will reduce the risk of breaking customers that are using the legacy mode. …
=> Add ADAPTIVE_V2 retry mode to support the legacy behavior

migration-tool/src/main/java/software/amazon/awssdk/migration/internal/recipe/AddCommentToMethod.java, migration-tool/src/test/java/software/amazon/awssdk/migration/recipe/AddCommentToMethodTest.java
There are some methods that are removed in Java SDK v2 and for those changes, we'll not update the code and instead, just add a comment providing suggestions.
Add AddCommentToMethod recipe
Unit tests added
=> Add AddCommentToMethod recipe

migration-tool/src/main/java/software/amazon/awssdk/migration/internal/recipe/NumberToDuration.java, migration-tool/src/test/java/software/amazon/awssdk/migration/internal/recipe/NumberToDurationTest.java
In v1, request timeout and client execution timeout config take a integer and in v2, they take Duration, so we need to convert numeric type to wrap with Duration when we convert to v2 code. 
This change added `NumberToDuration` recipe to convert numeric type to Duration. The use of it will be in a separate PR.
```
clientConfiguration.setRequestTimeout(1000);
```
to
```
clientConfiguration.setRequestTimeout(Duration.ofMillis(1000));
```
=> Add NumberToDuration recipe to convert numeric type to Duration

migration-tool/src/main/java/software/amazon/awssdk/migration/internal/recipe/S3StreamingResponseToV2.java, migration-tool/src/main/java/software/amazon/awssdk/migration/internal/utils/IdentifierUtils.java, migration-tool/src/main/resources/META-INF/rewrite/upgrade-sdk-dependencies.yml, migration-tool/src/test/java/software/amazon/awssdk/migration/internal/recipe/S3StreamingResponseToV2Test.java, migration-tool/src/test/java/software/amazon/awssdk/migration/internal/utils/IdentifierUtilsTest.java
This recipe transforms usages of `s3.getObject(..)` such as
```
S3Object myObject = s3.getObject(request);
```
to the equivalent in v2:
```
ResponseInputStream<GetObjectResponse> myObject = s3.getOBject(request);
```
In addition, because of the inversion of streaming and non-streaming members when moving to ResponseInputStream, it further transforms usages of myObject so that calls in v1 that access the stream:
```
myObject.getObjectContent().close()
```
become
```
myObject.close()
```
Likewise, methods that access the non-streaming members
```
myObject.getKey();
```
become
```
myObject.response().getKey();
```
=> Add S3StreamingResponseToV2 Recipe

test/stability-tests/src/it/java/software/amazon/awssdk/stability/tests/s3/S3AsyncBaseStabilityTest.java, test/stability-tests/src/it/java/software/amazon/awssdk/stability/tests/s3/S3MultipartJavaBasedStabilityTest.java, test/stability-tests/src/it/java/software/amazon/awssdk/stability/tests/utils/StabilityTestRunner.java
Fix stability tests
- increase allowed thread threshold: S3 multipart client uses more threads because for large file uploads, it reads from different positions of the files at the same time, which will trigger more Java I/O threads to spin up
- not fail stability tests based on thread count because if one test has increased thread count, it'd affect other tests, which will make the assertion more or less useless.
=> Fix stability tests

migration-tool/src/main/java/software/amazon/awssdk/migration/internal/recipe/S3StreamingResponseToV2.java, migration-tool/src/main/resources/META-INF/rewrite/java-sdk-v1-to-v2.yml, migration-tool/src/main/resources/META-INF/rewrite/s3-getobject-constructor-to-fluent.yml, test/migration-tool-tests/pom.xml, test/migration-tool-tests/src/test/resources/after/pom.xml, test/migration-tool-tests/src/test/resources/after/src/main/java/foo/bar/Application.java, test/migration-tool-tests/src/test/resources/before/pom.xml, test/migration-tool-tests/src/test/resources/before/src/main/java/foo/bar/Application.java
=> Add S3StreamingResponseToV2 to migration recipe

services/sqs/src/main/java/software/amazon/awssdk/services/sqs/internal/MessageMD5ChecksumInterceptor.java
If MD5 calculation fails because there is no available algorithm in the underlying JVM, this could be because the SDK is executing in a FIPS environment, where MD5 is no longer allowed due to compliance reasons. 
In addition to disabling MD5 checks on SQS message responses if the flag `checksumValidationEnabled` flag is set to false (PR #4729), this PR informs users with failing calculations that the flag exists by extending the exception message.
=> Adding guidance to MD5 calculation exception message

.changes/next-release/bugfix-s3transfermanager-8ed72b5.json, services-custom/s3-transfer-manager/src/main/resources/META-INF/native-image/software/amazon/awssdk/s3-transfer-manager/reflect-config.json
Fixes https://github.com/aws/aws-sdk-java-v2/issues/5127
Added reflect-config.json for ApplyUserAgentInterceptor for s3-transfer-manager module like it is present for ApplyUserAgentInterceptor in dynamodb-enhanced
I added a reflect-config.json in my project with the same content like in this PR and performed a native-build with `-H:ReflectionConfigurationResources=META-INF/native-image/reflect-config.json`.
N/A
=> Add reflect-config.json to s3-transfer-manager

migration-tool/pom.xml, migration-tool/src/main/java/software/amazon/awssdk/migration/internal/recipe/AddCommentToMethod.java, migration-tool/src/main/java/software/amazon/awssdk/migration/internal/recipe/V1SetterToV2.java, migration-tool/src/main/java/software/amazon/awssdk/migration/internal/utils/SdkTypeUtils.java, migration-tool/src/main/resources/META-INF/rewrite/change-config-types.yml, migration-tool/src/main/resources/META-INF/rewrite/change-sdk-core-types.yml, migration-tool/src/main/resources/META-INF/rewrite/java-sdk-v1-to-v2.yml, migration-tool/src/main/resources/META-INF/rewrite/upgrade-sdk-dependencies.yml, migration-tool/src/test/java/software/amazon/awssdk/migration/recipe/AddCommentToMethodTest.java, migration-tool/src/test/java/software/amazon/awssdk/migration/recipe/ChangeConfigTypesTest.java, test/migration-tool-tests/src/test/resources/after/src/main/java/foo/bar/SdkClientsDependencyFactory.java, test/migration-tool-tests/src/test/resources/before/src/main/java/foo/bar/SdkClientsDependencyFactory.java
- Add mapping for non-HTTP config settings
- For settings that are not supported in v2, we will add comments providing guidance
Supported non-HTTP settings:
```
ClientConfiguration clientConfiguration = new ClientConfiguration()
.withRetryMode(RetryMode.STANDARD)
.withClientExecutionTimeout(5000)
.withRequestTimeout(1000)
.with
.withHeader("foo", "bar");
```
to
```
ClientOverrideConfiguration clientConfiguration = ClientOverrideConfiguration.builder()
.retryPolicy(RetryMode.STANDARD)
.apiCallTimeout(Duration.ofMillis(5000))
.apiCallAttemptTimeout(Duration.ofMillis(1000))
.putHeader("foo", "bar").build();
```
Unsupported settings:
```
ClientConfiguration clientConfiguration = new ClientConfiguration()"
.withCacheResponseMetadata(false);
```
```
ClientOverrideConfiguration …
```
=> Add mappping for non-HTTP config settings

pom.xml, utils/src/main/java/software/amazon/awssdk/utils/async/InputStreamSubscriber.java, utils/src/test/java/software/amazon/awssdk/utils/async/InputStreamSubscriberTest.java
IOExceptions such as closed socket are wrapped as [`UncheckedIOException` by the `StoringSubscriber`](https://github.com/aws/aws-sdk-java-v2/blob/master/utils/src/main/java/software/amazon/awssdk/utils/async/StoringSubscriber.java#L181).  They are then [wrapped as `SdkClientException` in the `CombinedResponseHandler`](https://github.com/aws/aws-sdk-java-v2/blob/master/core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/http/CombinedResponseHandler.java#L110), making them non-retryable. They should be retryable and not wrapped.
This can occur when the socket is closed by the server during a `GetObject` call.
```
software.amazon.awssdk.core.exception.SdkClientException: Unable to unmarshall response (java.io.IOException: software.amazon.awssdk.crt.http.HttpException: socket is …
```
=> Catch UncheckedIOException and throw as IOException

.brazil.json, buildspecs/release-javadoc.yml, buildspecs/release-to-maven.yml, migration-tool/pom.xml, migration-tool/src/main/resources/META-INF/rewrite/upgrade-sdk-dependencies.yml, test/migration-tool-tests/pom.xml, test/migration-tool-tests/src/test/resources/run-test
- Change package name for migration tool `AwsJavaSdk-MigrationTool` -> `AwsJavaSdk-Tooling-MigrationTool` to not cause potential naming conflicts in the future.
- Update dependencies
- Exclude `migration-tool-tests` from javadoc and deployment
=> Change package name for migration tool and update dependencies

services/sqs/src/test/java/software/amazon/awssdk/services/sqs/MessageMD5ChecksumValidationDisableTest.java
- Set explicit region in test clients
- Add type inference to HashMap
=> Fix SQS test

.brazil.json
Adds the `bundle-shading-tests` module to the excluded module in `.brazil.json`
=> Skip brazil import of bundle-shading-tests module

migration-tool/src/main/java/software/amazon/awssdk/migration/internal/recipe/NumberToDuration.java, migration-tool/src/test/java/software/amazon/awssdk/migration/internal/recipe/NumberToDurationTest.java
Fix NumberToDuraion recipe to handle variable, currently, the following exception will be thrown if the input is not a literal.
```
Caused by: java.lang.IllegalArgumentException: Template parameter 0 cannot be used in an untyped template substitution. Instead of "#{}", indicate the template parameter's type with "#{any(int)}".
```
=> Fix NumberToDuraion recipe to handle variable

pom.xml
Re-enable japicmp after temporarily disabling for change in https://github.com/aws/aws-sdk-java-v2/pull/5201
=> Re-enable japicmp for utils module

services-custom/s3-transfer-manager/src/main/java/software/amazon/awssdk/transfer/s3/model/UploadDirectoryRequest.java
Tiny PR to fix a typo on Javadoc.
You can see it [here](https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/transfer/s3/model/UploadDirectoryRequest.Builder.html#uploadFileRequestTransformer(java.util.function.Consumer))
Fix typo
Fix typo
Fix typo
=> Fix typo on S3 Transfer Manager Javadoc

codegen/src/main/java/software/amazon/awssdk/codegen/poet/rules/EndpointResolverInterceptorSpec.java, codegen/src/main/resources/software/amazon/awssdk/codegen/jmespath/JmesPathRuntime.java.resource, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/rules/endpoint-resolve-interceptor-preSra.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/rules/endpoint-resolve-interceptor.java, services/s3/src/main/resources/codegen-resources/customization.config, test/codegen-generated-classes-test/src/main/resources/codegen-resources/endpointproviders/customization.config, test/codegen-generated-classes-test/src/main/resources/codegen-resources/endpointproviders/service-2.json, test/codegen-generated-classes-test/src/test/java/software/amazon/awssdk/services/endpointproviders/OperationContextParametersTest.java, test/codegen-generated-classes-test/src/test/java/software/amazon/awssdk/services/jmespath/JmesPathRuntimeValueTest.java
- Modifies the `wildcard` function, which has existed in the runtime but never been used in waiters, to accept lists which is according to specs: https://jmespath.org/specification.html#wildcard-expressions
- Adds a `keys` function which can return the names of `SdkField` members in an `SdkPojo`
- [INCORRECT] Catches errors when evaluating OperationContextParams at runtime and returns null instead, logging errors. It's complex functionality especially when sourcing parameters from a customization config. We can re-evaluate this behavior when model traits are available. 
- Fixes a minor bug in `project` to filter null values from the result. Another alternative would be to just filter nulls when returning `stringValues` but I can't think of a Java use-case where we want to preserve the …
=> Supporting wildcard and keys fn in JmesPathRuntime

services/s3/src/test/java/software/amazon/awssdk/services/s3/internal/plugins/ListOfStringsAuthParamPluginTest.java
A functional test that verifies that List<String> auth (and endpoint) parameters are resolved correctly.
=> Adds functional tests for list of string auth params

core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/async/SplittingTransformer.java, core/sdk-core/src/test/java/software/amazon/awssdk/core/internal/async/SplittingTransformerTest.java, services-custom/s3-transfer-manager/src/it/java/software/amazon/awssdk/transfer/s3/S3TransferManagerCopyIntegrationTest.java, services-custom/s3-transfer-manager/src/it/java/software/amazon/awssdk/transfer/s3/S3TransferManagerDownloadDirectoryIntegrationTest.java, services-custom/s3-transfer-manager/src/it/java/software/amazon/awssdk/transfer/s3/S3TransferManagerUploadDirectoryIntegrationTest.java, services-custom/s3-transfer-manager/src/main/java/software/amazon/awssdk/transfer/s3/internal/GenericS3TransferManager.java, services-custom/s3-transfer-manager/src/main/java/software/amazon/awssdk/transfer/s3/internal/progress/TransferProgressUpdater.java, services-custom/s3-transfer-manager/src/test/java/software/amazon/awssdk/transfer/s3/internal/TransferProgressUpdaterTest.java, services/s3/src/test/java/software/amazon/awssdk/services/s3/internal/multipart/MultipartDownloaderSubscriberWiremockTest.java
The `S3TransferManagerDownloadPauseResumeIntegrationTest` was failing with S3 Multipart client for 2 reasons.
1. The downloads were not immediately stopped when calling `.pause()`
2. When resuming, the range get would have the whole object size as its content-length, making the TransferProgressUpdater report the wrong number of bytes.
This PR is to fix both of those issues.
Errors were raised during integration test execution.
Fix for the errors consist in 
- Forward cancellation from returnFuture in SplittingTransformer
- Use content-length for range-get in TransferProgressUpdater, when multipart is enabled. 
Failing integration test run locally.
Added unit test.
=> Fix for multipart integ test failure

core/sdk-core/src/main/java/software/amazon/awssdk/core/FileTransformerConfiguration.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/async/FileAsyncResponseTransformer.java, core/sdk-core/src/test/java/software/amazon/awssdk/core/FileTransformerConfigurationTest.java, core/sdk-core/src/test/java/software/amazon/awssdk/core/internal/async/FileAsyncResponseTransformerTest.java
Add a new option to `FileTransformerConfiguration` `WRITE_TO_POSITION` that will start writing the incoming data to the file at the specified byte position.
Required to implement the pause and resume logic for multipart download in the java-based s3 async client.
- Add a new Enum value to `FileTransformerConfiguration. FileWriteOption`
- Add a new configuration to FileTransformerConfiguration: `location`
Added unit test.
=> FileAsyncResponseTransformer - write to position

services-custom/s3-transfer-manager/src/main/java/software/amazon/awssdk/transfer/s3/internal/serialization/ResumableFileDownloadSerializer.java, services-custom/s3-transfer-manager/src/main/java/software/amazon/awssdk/transfer/s3/internal/serialization/TransferManagerJsonUnmarshaller.java, services-custom/s3-transfer-manager/src/main/java/software/amazon/awssdk/transfer/s3/model/ResumableFileDownload.java, services-custom/s3-transfer-manager/src/test/java/software/amazon/awssdk/transfer/s3/internal/serialization/ResumableFileDownloadSerializerTest.java, services-custom/s3-transfer-manager/src/test/java/software/amazon/awssdk/transfer/s3/internal/serialization/TransferManagerJsonUnmarshallerTest.java, services-custom/s3-transfer-manager/src/test/java/software/amazon/awssdk/transfer/s3/model/ResumableFileDownloadTest.java
Add `completedParts` field to `ResumableFileDownload` with required serialization and deserialization.
Needed to Multipart Pause/Resume logic. The `ResumableFileDownload` can be serialized to json and deserialized back into memory to resume a download for it. 
- Add new field to `ResumableFileDownload` + Builder
- Add a new `TransferManagerJsonUnmarshaller` for list of Integer
- Update marshalling/unmarshalling to include `completedParts` list
=> add completed to ResumableFileDownload ser/des

http-clients/apache-client/src/main/java/software/amazon/awssdk/http/apache/internal/conn/SdkTlsSocketFactory.java, http-clients/apache-client/src/main/java/software/amazon/awssdk/http/apache/internal/net/InputShutdownCheckingSslSocket.java
This commit adds a wrapper socket that ensures the read end of the socket is still open before performing a {@code write()}. In TLS 1.3, it is permitted for the connection to be in a half-closed state, which is dangerous for the Apache client because it can get stuck in a state where it continues to write to the socket and potentially end up a blocked state writing to the socket indefinitely.
=> Check if input is shut down before writing

migration-tool/src/main/java/software/amazon/awssdk/migration/internal/recipe/V1GetterToV2.java, migration-tool/src/main/java/software/amazon/awssdk/migration/internal/utils/NamingUtils.java, migration-tool/src/main/resources/META-INF/rewrite/java-sdk-v1-to-v2.yml, migration-tool/src/test/java/software/amazon/awssdk/migration/recipe/V1GetterToV2Test.java, test/migration-tool-tests/src/test/resources/after/src/main/java/foo/bar/Application.java, test/migration-tool-tests/src/test/resources/before/src/main/java/foo/bar/Application.java
Transform v1 getters to v2 fluent style, removing the `"get"`
=> Add V1GetterToV2 Recipe

core/aws-core/src/main/java/software/amazon/awssdk/awscore/retry/AwsRetryStrategy.java, core/retries/src/main/java/software/amazon/awssdk/retries/DefaultRetryStrategy.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/retry/RetryMode.java, core/sdk-core/src/test/java/software/amazon/awssdk/core/retry/RetryModeTest.java, services/dynamodb/src/test/java/software/amazon/awssdk/services/dynamodb/DynamoDbRetryPolicyTest.java, test/codegen-generated-classes-test/src/test/java/software/amazon/awssdk/services/retry/BaseRetrySetupTest.java
As discussed in the API review meeting, we need to keep the names in the profile and environment variables SDKs compatible, therefore we removed the resolution of the `adaptive_v2` name and the `adaptive` name now resolves to new retry mode `ADAPTIVE_V2`, meaning, users that have set this up to `adaptive` via either the profile or system setting or an environment variable will see a behavior change since they will get the "correct" adaptive behavior.
=> External names used for retry modes only support 'adaptive'

migration-tool/src/main/java/software/amazon/awssdk/migration/internal/utils/NamingConversionUtils.java, migration-tool/src/main/java/software/amazon/awssdk/migration/internal/utils/SdkTypeUtils.java, migration-tool/src/test/java/software/amazon/awssdk/migration/internal/utils/NamingConversionUtilsTest.java
Current behavior:
v1 `ResultConfiguration` -> v2 `ResponseConfiguration`
v1 `ResultConfigurationResult` -> v2 `ResponseConfigurationResponse`
Expected behavior:
v1 `ResultConfiguration` -> v2 `ResultConfiguration`
v1 `ResultConfigurationResult` -> v2 `ResultConfigurationResponse`
Added tests
=> Fix POJO class naming mapping

migration-tool/src/main/resources/META-INF/rewrite/change-auth-types.yml, migration-tool/src/test/java/software/amazon/awssdk/migration/recipe/ChangeAuthTypesTest.java
v1 `getCredentials` -> v2 `resolveCredentials`
v1 `getAWSAccessKeyId` ->  v2 `accessKeyId`
v1 `getAWSSecretKey` ->  v2 `secretAccessKey`
v1 `getSessionToken` ->  v2 `sessionToken`
=> Change auth type getters to fluent getters

migration-tool/src/main/java/software/amazon/awssdk/migration/internal/utils/NamingConversionUtils.java, migration-tool/src/main/resources/META-INF/rewrite/change-exception-types.yml, migration-tool/src/main/resources/META-INF/rewrite/change-sdk-core-types.yml, migration-tool/src/test/java/software/amazon/awssdk/migration/internal/utils/NamingConversionUtilsTest.java, migration-tool/src/test/java/software/amazon/awssdk/migration/recipe/ChangeExceptionTypesTest.java, migration-tool/src/test/java/software/amazon/awssdk/migration/recipe/ChangeSdkTypeTest.java, test/migration-tool-tests/src/test/resources/after/src/main/java/foo/bar/Application.java, test/migration-tool-tests/src/test/resources/before/src/main/java/foo/bar/Application.java
Add mapping for core exception types and getters in exception glasses
For example:
`exception.getRawResponse` -> `exception.rawResponse().asByteArray`
=> Add mapping for core exception types and getters

migration-tool/src/main/java/software/amazon/awssdk/migration/internal/recipe/WrapSdkClientBuilderRegionStr.java, migration-tool/src/main/resources/META-INF/rewrite/java-sdk-v1-to-v2.yml, test/migration-tool-tests/src/test/resources/after/src/main/java/foo/bar/SdkClientsDependencyFactory.java, test/migration-tool-tests/src/test/resources/before/src/main/java/foo/bar/SdkClientsDependencyFactory.java
Wrap region string with Region.of
```
SqsClient.builder()
.region("us-west-2")
.build();
```
to
```
SqsClient.builder()
.region(Region.of("us-west-2"))
.build();
```
=> Wrap region string with Region.of

migration-tool/src/main/java/software/amazon/awssdk/migration/internal/utils/NamingConversionUtils.java, migration-tool/src/main/java/software/amazon/awssdk/migration/recipe/ChangeSdkType.java, migration-tool/src/test/java/software/amazon/awssdk/migration/internal/utils/NamingConversionUtilsTest.java, migration-tool/src/test/java/software/amazon/awssdk/migration/recipe/ChangeSdkTypeTest.java
Currently, if wildcard imports such as `com.amazonaws.services.sqs.model.*`  and `com.amazonaws.services.sqs.*` are used, v1 types will not get converted to v2 types.
This change fixes wildcard imports in ChangeSdkType recipe
=> Handle wildcard imports in ChangeSdkType recipe

.changes/next-release/bugfix-AWSSDKforJavav2-a8d0992.json, core/retries-spi/src/main/java/software/amazon/awssdk/retries/api/BackoffStrategy.java, core/retries-spi/src/main/java/software/amazon/awssdk/retries/api/internal/backoff/ExponentialDelayWithHalfJitter.java, core/retries/src/main/java/software/amazon/awssdk/retries/DefaultRetryStrategy.java, core/retries/src/main/java/software/amazon/awssdk/retries/LegacyRetryStrategy.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/retry/backoff/EqualJitterBackoffStrategy.java
Introducing a new backoff strategy that is used in the `LegacyRetryStrategy` for backing off for throttling exceptions.
This change mimics the previous behavior in which the `EqualJitterBackoffStrategy` was used as the throttling backoff strategy for `RetryMode.LEGACY`. See [here](https://github.com/aws/aws-sdk-java-v2/blob/b8f136c7e1bedde1811dc20839ad78ff25b8e0da/core/sdk-core/src/main/java/software/amazon/awssdk/core/retry/backoff/BackoffStrategy.java#L69) and [here](https://github.com/aws/aws-sdk-java-v2/blob/b8f136c7e1bedde1811dc20839ad78ff25b8e0da/core/sdk-core/src/main/java/software/amazon/awssdk/core/retry/RetryPolicy.java#L383).
This backoff strategy differs from the full jitter exponential strategy on a cap used for the minimum delay time. The full jitter exponential backoff …
=> Add ExponentialDelayWithHalfJitter backoff strategy

migration-tool/src/main/java/software/amazon/awssdk/migration/internal/utils/NamingUtils.java, migration-tool/src/test/java/software/amazon/awssdk/migration/internal/utils/NamingUtilsTest.java, migration-tool/src/test/java/software/amazon/awssdk/migration/recipe/V1GetterToV2Test.java, test/migration-tool-tests/src/test/resources/after/src/main/java/foo/bar/Application.java, test/migration-tool-tests/src/test/resources/before/src/main/java/foo/bar/Application.java
Fix V1GetterToV2 to not change get method on a list member
`Message message = receiveMessage.getMessages().get(0)` -> `Message message = receiveMessage.message().(0)`
`Message message = receiveMessage.getMessages().get(0)` -> `Message message = receiveMessage.message().get(0)`
=> Fix V1GetterToV2 to not change get method

.changes/next-release/bugfix-AWSSDKforJavav2-1a76a6f.json, codegen/src/main/java/software/amazon/awssdk/codegen/poet/builder/BaseClientBuilderClass.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/builder/sra/test-client-builder-class.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/builder/sra/test-client-builder-endpoints-auth-params.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/builder/sra/test-composed-sync-default-client-builder.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/builder/sra/test-query-client-builder-class.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/builder/test-client-builder-class.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/builder/test-client-builder-endpoints-auth-params.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/builder/test-composed-sync-default-client-builder.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/builder/test-query-client-builder-class.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/client/config/ClientOverrideConfiguration.java, services/kinesis/src/test/java/software/amazon/awssdk/services/kinesis/KinesisClientCanOverrideDefaultRetryPolicy.java, services/kinesis/src/test/java/software/amazon/awssdk/services/kinesis/KinesisClientCanOverrideDefaultRetryPolicyTest.java, test/codegen-generated-classes-test/src/test/java/software/amazon/awssdk/services/retry/CanOverrideRetryStrategy.java
Currently this bug mostly affects Kinesis but might also affect other clients when there's an override for retry policy followed by an override for a retry strategy. 
Kinesis has a custom `RetryPolicy` that was not converted to a `RetryStrategy` due to their use of non-supported features, in particular they need to get from the request the specific operation to avoid retries on `subscribeToShard` calls. This is not supported by `RetryStrategy` that does not know anything about requests. 
To keep backwards compatibility, the retry stages look for a retry policy and if found it takes precedence over retry strategies. This means that if any user overrides a retry policy and then overrides a retry strategy the retry policy will still be used.
For the particular case of Kinesis this happens by …
=> Make sure that override plays well for retry policies and strategies

codegen/src/main/java/software/amazon/awssdk/codegen/AddMetadata.java, codegen/src/main/java/software/amazon/awssdk/codegen/internal/Constant.java, codegen/src/main/java/software/amazon/awssdk/codegen/model/config/customization/CustomizationConfig.java, codegen/src/main/java/software/amazon/awssdk/codegen/model/intermediate/Metadata.java, codegen/src/main/java/software/amazon/awssdk/codegen/naming/DefaultNamingStrategy.java, codegen/src/main/java/software/amazon/awssdk/codegen/naming/NamingStrategy.java, codegen/src/main/java/software/amazon/awssdk/codegen/poet/PoetExtension.java, codegen/src/main/java/software/amazon/awssdk/codegen/poet/client/AsyncClientClass.java, codegen/src/main/java/software/amazon/awssdk/codegen/poet/client/AsyncClientInterface.java, codegen/src/main/java/software/amazon/awssdk/codegen/poet/client/DelegatingAsyncClientClass.java, codegen/src/test/java/software/amazon/awssdk/codegen/poet/ClientTestModels.java, codegen/src/test/java/software/amazon/awssdk/codegen/poet/client/AsyncClientClassTest.java, codegen/src/test/java/software/amazon/awssdk/codegen/poet/client/AsyncClientInterfaceTest.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/c2j/batchmanager/customization.config, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/c2j/batchmanager/service-2.json, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/c2j/rest-json/customization.config, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/sra/test-aws-json-async-client-class.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/sra/test-json-async-client-class.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/test-abstract-async-client-class.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/test-batchmanager-async.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/test-json-async-client-class.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/test-json-async-client-interface-batchmanager.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/test-json-async-client-interface.java, services/sqs/src/main/java/software/amazon/awssdk/services/sqs/batchmanager/BatchOverrideConfiguration.java, services/sqs/src/main/java/software/amazon/awssdk/services/sqs/batchmanager/SqsAsyncBatchManager.java, services/sqs/src/main/java/software/amazon/awssdk/services/sqs/internal/batchmanager/BatchOverrideConfiguration.java, services/sqs/src/main/java/software/amazon/awssdk/services/sqs/internal/batchmanager/DefaultSqsAsyncBatchManager.java
PR similar to https://github.com/aws/aws-sdk-java-v2/pull/2666. But following are considered after design reviews
1. The BatchManager Implementation will be hand written , thus we donot need codegenrated BatchFunctions and code generated Default batch Manager.
2.  We will proivide batchManager() api only to AsyncClient , since returning  completable future for sync Api doesnot make sense for Sync API  , instead sync API can directly call send/recieve with custom BatchedRequest in its request.
Customization 
```json
"batchManagerSupported": true
```
Will result in code
1. Addition of scheduledExecutor similar to that of waiters()
2.  Java code as below
```java
@Override
public BatchManagerTestAsyncBatchManager batchManager() {
return …
```
=> Codegenerate BatchManager API under AsyncClient and Initail Interfaces for BatchManager

.changes/next-release/bugfix-AWSSDKforJavav2-ead1561.json, core/retries/src/main/java/software/amazon/awssdk/retries/internal/BaseRetryStrategy.java, core/retries/src/main/java/software/amazon/awssdk/retries/internal/circuitbreaker/TokenBucket.java, test/codegen-generated-classes-test/src/test/java/software/amazon/awssdk/services/retry/TokenBucketRecoversTest.java
The original implementation of the token bucket logic did not deposit back for successful invocations which means that once the buckets were exhausted it will no allow any more retries since there's no mechanism to recover from that state.
Customers using custom **`RetryPolicy`** instances or **Kinesis** are NOT affected by this bug.
=> Allow slow recovery of tokens in the token bucket

migration-tool/src/main/java/software/amazon/awssdk/migration/internal/utils/NamingConversionUtils.java, migration-tool/src/test/java/software/amazon/awssdk/migration/internal/utils/NamingConversionUtilsTest.java
Remove `v2` from `dynamodbv2` and `cloudsearchv2` imports
=> Account for v1 package service name differences

migration-tool/pom.xml, migration-tool/src/main/java/software/amazon/awssdk/migration/recipe/ChangeSdkType.java, migration-tool/src/main/resources/META-INF/rewrite/upgrade-sdk-dependencies.yml, migration-tool/src/main/resources/scripts/generate_upgrade_sdk_dependencies_recipe.py, migration-tool/src/test/java/software/amazon/awssdk/migration/recipe/ChangeSdkTypeTest.java, migration-tool/src/test/java/software/amazon/awssdk/migration/recipe/UpgradeSdkDependenciesTest.java
- Skip transformation for S3 Transfer Manager and DynamoDB mapper since they are not supported in the initial release.
- Only add HTTP client dependencies if `ClientConfiguration` is directly being used (http settings)
=> Skip transformation for S3 Transfer Manager and DynamoDB mapper

pom.xml
Bump CRT to 0.30.0. Fix https://github.com/aws/aws-sdk-java-v2/issues/5277
https://github.com/awslabs/aws-crt-java/releases/tag/v0.30.0
=> Bump CRT to 0.30.0

.changes/next-release/bugfix-AWSSDKforJavav2-a6340e4.json, core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/retry/SdkDefaultRetryStrategy.java, core/sdk-core/src/test/java/software/amazon/awssdk/core/retry/RetryStrategyMaxRetriesTest.java
Add missing support for `AWS_MAX_ATTEMPTS` in retry strategies.
Fixes https://github.com/aws/aws-sdk-java-v2/issues/5367
=> Add missing support for AWS_MAX_ATTEMPTS in retry strategies

migration-tool/src/main/resources/META-INF/rewrite/change-auth-types.yml, migration-tool/src/main/resources/META-INF/rewrite/change-exception-types.yml
Add `()` to method patterns in recipes to avoid warning logs:
`line 1:65 mismatched input '<EOF>' expecting {'(', '*'}`
=> Add parentheses to method patterns

build-tools/src/main/resources/software/amazon/awssdk/spotbugs-suppressions.xml, test/v2-migration-tests/src/test/resources/maven/after/pom.xml, test/v2-migration-tests/src/test/resources/maven/after/src/main/java/foo/bar/Enums.java, test/v2-migration-tests/src/test/resources/maven/before/pom.xml, test/v2-migration-tests/src/test/resources/maven/before/src/main/java/foo/bar/Enums.java, test/v2-migration-tests/src/test/resources/run-test, v2-migration/pom.xml, v2-migration/src/main/java/software/amazon/awssdk/v2migration/ChangeSdkType.java, v2-migration/src/main/java/software/amazon/awssdk/v2migration/EnumCasingToV2.java, v2-migration/src/main/resources/META-INF/rewrite/aws-sdk-java-v1-to-v2.yml, v2-migration/src/main/resources/META-INF/rewrite/change-enum-getters.yml, v2-migration/src/main/resources/META-INF/rewrite/upgrade-sdk-dependencies.yml, v2-migration/src/main/resources/generate-recipes, v2-migration/src/main/resources/scripts/generate_enum_transforms_recipe.py, v2-migration/src/main/resources/scripts/generate_upgrade_sdk_dependencies_recipe.py, v2-migration/src/main/resources/scripts/utils.py, v2-migration/src/test/java/software/amazon/awssdk/v2migration/EnumCasingToV2Test.java, v2-migration/src/test/java/software/amazon/awssdk/v2migration/EnumGettersToV2Test.java
Transform enums from v1 to v2
- Casing: [enum constants from pascal case to screaming snake case](https://github.com/aws/aws-sdk-java-v2/blob/master/codegen/src/main/java/software/amazon/awssdk/codegen/naming/DefaultNamingStrategy.java#L271)
- Getters: XXAsString(s) to return String instead of enum type
=> Add enum getters and casing transforms

core/sdk-core/src/main/java/software/amazon/awssdk/core/async/AsyncResponseTransformer.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/async/FileAsyncResponseTransformer.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/async/SplittingTransformer.java, core/sdk-core/src/test/java/software/amazon/awssdk/core/internal/async/FileAsyncResponseTransformerTest.java, services-custom/s3-transfer-manager/src/main/java/software/amazon/awssdk/transfer/s3/internal/utils/ResumableRequestConverter.java, services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/multipart/DownloadObjectHelper.java, services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/multipart/MultipartDownloadResumeContext.java
Addressing remaining PR comments in https://github.com/aws/aws-sdk-java-v2/pull/5164
=> PR 5164 remaining comments

test/v2-migration-tests/src/test/resources/maven/after/src/main/java/foo/bar/Application.java, test/v2-migration-tests/src/test/resources/maven/after/src/main/java/foo/bar/Enums.java, test/v2-migration-tests/src/test/resources/maven/before/src/main/java/foo/bar/Application.java, v2-migration/src/main/java/software/amazon/awssdk/v2migration/EnumCasingToV2.java, v2-migration/src/main/java/software/amazon/awssdk/v2migration/S3StreamingRequestToV2.java, v2-migration/src/main/resources/META-INF/rewrite/aws-sdk-java-v1-to-v2.yml, v2-migration/src/main/resources/META-INF/rewrite/s3-putbject-constructor-to-fluent.yml, v2-migration/src/test/java/software/amazon/awssdk/v2migration/EnumGettersToV2Test.java, v2-migration/src/test/java/software/amazon/awssdk/v2migration/S3StreamingRequestToV2Test.java
Continuation of https://github.com/aws/aws-sdk-java-v2/pull/5218 
The only change I made is https://github.com/aws/aws-sdk-java-v2/commit/5f17f9cfa6da74c08aeadcb8d37413e12a09065e
=> Transforming S3 PUT override

test/v2-migration-tests/src/test/resources/maven/after/src/main/java/foo/bar/Application.java, test/v2-migration-tests/src/test/resources/maven/before/src/main/java/foo/bar/Application.java, v2-migration/src/main/java/software/amazon/awssdk/v2migration/S3StreamingRequestToV2.java, v2-migration/src/test/java/software/amazon/awssdk/v2migration/S3StreamingRequestToV2Test.java
Transforming `putObject` overload for String payload:
`putObject(String bucketName, String key, String content)`
Added unit and end-to-end tests
=> S3 PutObject String overload

core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/async/FileAsyncResponseTransformer.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/async/SplittingTransformer.java, services-custom/s3-transfer-manager/src/main/java/software/amazon/awssdk/transfer/s3/internal/GenericS3TransferManager.java, services-custom/s3-transfer-manager/src/test/resources/log4j2.properties
Adding trace logs around multipart download to help troubleshoot future hanging
=> Add trace logs for debugging multipart download

.changes/next-release/feature-AWSSDKforJavav2-9cbba6f.json, core/auth/src/main/java/software/amazon/awssdk/auth/credentials/ContainerCredentialsProvider.java
Adding `create()` method for `ContainerCredentialsProvider`. Currently users must use `builder().build()`
=> Add create() method for ContainerCredentialsProvider

core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/async/SplittingTransformer.java, services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/multipart/MultipartDownloaderSubscriber.java
On single part download, s3 multipart client could hang and never terminates. This is the fix for that issue.
The culprit was the call to `logMulitpartComplete()`, when calling this method inside a synchronized block, the call to `log.debug()` within it would hang. The exact reason for the debug log call method to block is still uncertain. 
To prevent this issue, the synchronized block was remove as it was redundant. The call to `cancel()` is already synchronized in the publisher the multipart Subscriber subscribes to, and the call to `request()` already enforce mutual exclusion in the publisher through atomic booleans.
=> Prevent multipart download from hanging

test/v2-migration-tests/src/test/java/software/amazon/awssdk/v2migrationtests/GradleProjectTest.java, test/v2-migration-tests/src/test/java/software/amazon/awssdk/v2migrationtests/MavenProjectTest.java, test/v2-migration-tests/src/test/java/software/amazon/awssdk/v2migrationtests/TestUtils.java, test/v2-migration-tests/src/test/resources/software/amazon/awssdk/v2migrationtests/maven/after/pom.xml, test/v2-migration-tests/src/test/resources/software/amazon/awssdk/v2migrationtests/maven/before/pom.xml, v2-migration/pom.xml, v2-migration/src/main/resources/META-INF/rewrite/upgrade-sdk-dependencies.yml, v2-migration/src/test/java/software/amazon/awssdk/v2migration/UpgradeSdkDependenciesTest.java
Update to not generate `upgrade-sdk-dependencies` and `change-enum-getters` at build time because `change-enum-getters` is always the same and v1 has entered maintenance mode and we will not ship new services in v1.
I will create a separate PR to update our buildspec to update the SDK version in  `upgrade-sdk-dependencies` to the latest.
=> Update to not generate upgrade-sdk-dependencies and change-enum-getters

v2-migration/README.md, v2-migration/src/main/resources/META-INF/rewrite/change-enum-getters.yml, v2-migration/src/main/resources/scripts/generate_enum_transforms_recipe.py
- Add commonly used services to enum recipe: cloudwatchlogs, cloudwatch, kms, firehose, kinesis
- Update ReadMe to link to Dev Guide
=> Migration Tool: Add services to Enum recipe and update ReadMe

CHANGELOG.md
=> Fix spacing in Changelog

codegen/src/main/java/software/amazon/awssdk/codegen/AddEmptyInputShape.java, codegen/src/main/java/software/amazon/awssdk/codegen/internal/DefaultProtocolMetadataConstants.java, codegen/src/main/java/software/amazon/awssdk/codegen/internal/ProtocolMetadataConstants.java, codegen/src/main/java/software/amazon/awssdk/codegen/internal/ProtocolMetadataDefault.java, codegen/src/main/java/software/amazon/awssdk/codegen/internal/Utils.java, codegen/src/main/java/software/amazon/awssdk/codegen/model/intermediate/ShapeMarshaller.java, codegen/src/main/java/software/amazon/awssdk/codegen/poet/transform/protocols/CodegenSerializer.java, codegen/src/main/java/software/amazon/awssdk/codegen/poet/transform/protocols/CodegenSerializerResolver.java, codegen/src/main/java/software/amazon/awssdk/codegen/poet/transform/protocols/JsonMarshallerSpec.java, core/protocols/aws-json-protocol/src/main/java/software/amazon/awssdk/protocols/json/BaseAwsJsonProtocolFactory.java, core/protocols/aws-json-protocol/src/main/java/software/amazon/awssdk/protocols/json/internal/marshall/JsonProtocolMarshaller.java, core/protocols/protocol-core/src/main/java/software/amazon/awssdk/protocols/core/OperationMetadataAttribute.java, test/protocol-tests-core/src/main/resources/software/amazon/awssdk/protocol/suites/cases/smithy-rpcv2-input.json
*NOTE* Codgen tests will be added in a follow up PR, this task is already tracked.
Smithy RPCv2 protocol requires a different treatment for operations with empty input and not defined input. For not requests with no defined input types:
> Requests for operations with no defined input type (as in, they target the Unit shape) MUST NOT contain bodies in their HTTP requests. The Content-Type for the serialization format MUST NOT be set.
This change adds support for this requirement. 
1. Creates new `OperationMetadataAttribute` to control when to use a no-op JSON generator. This value can for this attribute key can be codegen per operation.
2. Changes the way we codegen `OperationInfo` to add metadata defaults
3. Reverts previously added, protocol specific, code to support adding the …
=> Support for operation without input defined

services/sqs/src/main/java/software/amazon/awssdk/services/sqs/batchmanager/SqsAsyncBatchManager.java, services/sqs/src/test/java/software/amazon/awssdk/services/sqs/BatchManager/BaseSqsBatchManagerTest.java, services/sqs/src/test/java/software/amazon/awssdk/services/sqs/BatchManager/SqsAsyncBatchManagerTest.java
Had a TODO in previous PR to add consumers for the API builders
- Added cunsumer builders to public API
- Updated the test cases to use consumer builder
=> Added Consumer builders args for existing APIs of BatchManager

pom.xml
Upgrade the crt version to 0.30.9. This release contains a memory leak fix.
https://github.com/awslabs/aws-crt-java/releases/tag/v0.30.9
=> Upgrade CRT version to 0.30.9

test/codegen-generated-classes-test/src/test/java/software/amazon/awssdk/services/IdentityResolutionOverrideTest.java
The motivation for these tests are to show how the SDK supports use cases where customers want to override credentials per request through execution interceptors.
=> Adding tests for overriding credentials or credentials providers 

core/json-utils/src/main/java/software/amazon/awssdk/protocols/jsoncore/JsonNodeParser.java, core/json-utils/src/main/java/software/amazon/awssdk/protocols/jsoncore/JsonValueNodeFactory.java, core/protocols/aws-json-protocol/src/main/java/software/amazon/awssdk/protocols/json/BaseAwsJsonProtocolFactory.java, core/protocols/aws-json-protocol/src/main/java/software/amazon/awssdk/protocols/json/internal/unmarshall/JsonProtocolUnmarshaller.java, core/protocols/protocol-core/src/main/java/software/amazon/awssdk/protocols/core/NumberToInstant.java, core/protocols/smithy-rpcv2-protocol/pom.xml, core/protocols/smithy-rpcv2-protocol/src/main/java/software/amazon/awssdk/protocols/rpcv2/SmithyRpcV2CborProtocolFactory.java, core/protocols/smithy-rpcv2-protocol/src/main/java/software/amazon/awssdk/protocols/rpcv2/internal/SdkRpcV2CborValueNodeFactory.java, test/sdk-benchmarks/src/main/java/software/amazon/awssdk/benchmark/apicall/protocol/JsonCodec.java, test/sdk-benchmarks/src/main/java/software/amazon/awssdk/benchmark/apicall/protocol/JsonMarshallerBenchmark.java
The current unmarshalling process is split into two phases. During the first phase the input is parsed into a `JsonNode` instance that represents the whole JSON input. The second phase uses this `JsonNode` to unmarshall the nodes into SDK pojos.
For a regular JSON input the input, numeric values are represented as strings (e.g., `3.14`, `"17"`), therefore we need to parse the strings to convert them into a numeric type. For Smithy RPCv2 we don't need this, the values in the CBOR payload are already encoded in a way that's a lot cheaper to convert than parsing the string.
This change makes it possible to read from the CBOR input the encoded values without having to convert them into strings and back into numbers. For that it changes the two phases of the unmarshalling process:
1. During …
=> Avoid parsing numbers when using RPCv2 protocol

services/sqs/src/main/java/software/amazon/awssdk/services/sqs/internal/batchmanager/ChangeMessageVisibilityBatchManager.java, services/sqs/src/main/java/software/amazon/awssdk/services/sqs/internal/batchmanager/DeleteMessageBatchManager.java, services/sqs/src/main/java/software/amazon/awssdk/services/sqs/internal/batchmanager/QueueAttributesManager.java, services/sqs/src/main/java/software/amazon/awssdk/services/sqs/internal/batchmanager/ReceiveSqsMessageHelper.java, services/sqs/src/main/java/software/amazon/awssdk/services/sqs/internal/batchmanager/SendMessageBatchManager.java, services/sqs/src/main/java/software/amazon/awssdk/services/sqs/internal/batchmanager/SqsMessageDefault.java, services/sqs/src/test/java/software/amazon/awssdk/services/sqs/batchmanager/BaseSqsBatchManagerTest.java, services/sqs/src/test/java/software/amazon/awssdk/services/sqs/batchmanager/ReceiveSqsMessageHelperTest.java, services/sqs/src/test/java/software/amazon/awssdk/services/sqs/batchmanager/SqsAsyncBatchManagerTest.java
- Calls made using High Level library should be identified as `hll/faturename`
- Update override configuration of request to send `hll/abm` in the request
- Junits for validate the header of user-agent
=> Add User Agent for Sqs Calls made using Automatic Batching Manager 

codegen/src/main/java/software/amazon/awssdk/codegen/poet/model/MemberCopierSpec.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/blobmaptypecopier.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/listofblobstypecopier.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/listofenumscopier.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/listofintegerscopier.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/listoflistoflistofstringscopier.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/listoflistofstringscopier.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/listofmapofenumtostringcopier.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/listofmapofstringtostructcopier.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/listofmapstringtostringcopier.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/listofsimplestructscopier.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/listofstringscopier.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/mapofenumtoenumcopier.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/mapofenumtolistofenumscopier.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/mapofenumtomapofstringtoenumcopier.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/mapofenumtosimplestructcopier.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/mapofenumtostringcopier.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/mapofstringtoenumcopier.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/mapofstringtointegerlistcopier.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/mapofstringtolistoflistofstringscopier.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/mapofstringtosimplestructcopier.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/mapofstringtostringcopier.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/recursivelisttypecopier.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/recursivemaptypecopier.java
Improves the performance of building collections by allocating the expected size beforehand instead of letting the collection grow as we add elements. This trivial change has small, but noticeable, performance improvements in the benchmarks for RPCv2, but will also benefit other protocols
**Before**
```
Benchmark                              (protocol)  (size)  Mode  Cnt      Score     Error  Units
JsonMarshallerBenchmark.unmarshall  smithy-rpc-v2   small  avgt    5   1944.436 ±  21.069  ns/op
JsonMarshallerBenchmark.unmarshall  smithy-rpc-v2  medium  avgt    5   3209.297 ± 259.975  ns/op
JsonMarshallerBenchmark.unmarshall  smithy-rpc-v2     big  avgt    5  11061.383 ± 187.669  ns/op
```
And flamegraph snippet below
**After**
```
Benchmark                              (protocol)  (size) …
```
=> Avoid growing copies of collections of known size

services/sqs/src/main/java/software/amazon/awssdk/services/sqs/internal/batchmanager/ReceiveBatchManager.java, services/sqs/src/main/java/software/amazon/awssdk/services/sqs/internal/batchmanager/ReceiveMessageBatchManager.java, services/sqs/src/test/java/software/amazon/awssdk/services/sqs/batchmanager/ReceiveBatchesMockTest.java, services/sqs/src/test/java/software/amazon/awssdk/services/sqs/batchmanager/ReceiveMessageBatchManagerTest.java
The key modification was ensuring that the same future passed to `receiveQueueBuffer.receiveMessage` is the one that gets completed, regardless of whether a timeout occurs.
Previously, a new future (timeoutFuture) was scheduled to complete after the timeout period, but this future was independent of the one added to the futures queue. Now, instead of creating a new timeout future, we directly complete the original future (receiveMessageFuture) if it hasn't already been completed before the timeout occurs.
The issue occurred because a new CompletableFuture (timeout future) was being created and completed during timeouts, rather than completing the original future added to the ReceiveBuffer. This left the original future uncompleted, causing the buffer to return empty responses.
The fix …
=> Fix issue where the Scheduled Timeout was incorrectly completing the futures with empty messages

services/sqs/src/it/java/software/amazon/awssdk/services/sqs/RequestBatchManagerSqsIntegrationTest.java, services/sqs/src/it/java/software/amazon/awssdk/services/sqs/ResponseBatchManagerSqsIntegrationTest.java
- Integ test for Automatic Request Batching
- Integ test is needed to make sure Batching feature is able to handle SQS service real time behaviour when it comes to sending and receieing message
This test class performs integration testing for AWS SQS batch manager, covering various message sending, receiving, and management scenarios using SQS.
1. **Basic Message Sending:**
- **`sendTenMessages`**: Sends 10 messages to a queue.
- **`sendTwentyMessages`**: Sends 20 messages to a queue.
2. **Batching and Scheduling:**
- **`scheduleSendFiveMessages`**: Sends 5 messages in a batch and checks batch processing time.
- **`scheduleTwoSendMessageBatches`**: Sends 10 messages in two batches and checks batch behavior.
3. **Multi-threaded Message Sending:**
- …
=> Integeration tests for SQS Automatic Request Batching

VERSIONING.md
-  Minor version is also updated  to let customers know that a new feature is released
- Update Minor versioning policy to make sure we do a minor version bup
=> Update Minor versioning policy to make sure we do a minor version bump for new features

v2-migration/src/main/java/software/amazon/awssdk/v2migration/internal/utils/NamingConversionUtils.java
Package diffs based on https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/migration-steps.html
Edge case client diff for KinesisFirehose (v1) -> Firehose (v2)
=> Migration tool mapping diffs

test/sdk-benchmarks/src/main/java/software/amazon/awssdk/benchmark/marshaller/dynamodb/V2DynamoDbAttributeValue.java
The `V2DynamoDbAttributeValue` benchmark currently fail with a NPE since the client configuration is missing. This change adds the client configuration to be fix this issue.
```
software.amazon.awssdk.core.exception.SdkClientException: Unable to marshall request to JSON: Cannot invoke "software.amazon.awssdk.core.client.config.SdkClientConfiguration.option(software.amazon.awssdk.core.client.config.ClientOption)" because "this.clientConfiguration" is null
at software.amazon.awssdk.core.exception.SdkClientException$BuilderImpl.build(SdkClientException.java:111)
at software.amazon.awssdk.services.dynamodb.transform.PutItemRequestMarshaller.marshall(PutItemRequestMarshaller.java:52)
at software.amazon.awssdk.benchmark.marshaller.dynamodb.V2DynamoDbAttributeValue.putItem(V2DynamoDbAttributeValu …
```
=> Add a client config to the client that is now needed

codegen/src/main/java/software/amazon/awssdk/codegen/IntermediateModelBuilder.java
Noticed during code generation there are warnings about not allowlisting certain operations as simple methods, but the warning doesn't actually apply because the methods *do* have required arguments.  
* Fixed an improperly negated conditional -- implementation of the conditional didn't match the variable name stating what it should have been.
* Unable to implement new testing due to the behavior being a logging-only behavior.  
* The modified code does not affect anything at runtime
Logged output
```
A potential simple method exists that isn't explicitly excluded or included: getThread
```
Applicable model snippet:
```
"GetThreadInput": {
"type": "structure",
"required": [
"threadId"
],
```
- Had environmental issues that prevented me from running successfully (running locally on a Mac …
=> Codegen: Fix flipped conditional for the simple method warning log

release-scripts/src/main/java/software/amazon/awssdk/release/CreateNewServiceModuleMain.java, release-scripts/src/main/java/software/amazon/awssdk/release/NewServiceMain.java, services/new-service-template/pom.xml
=> Add support for Smithy RPCv2 to the new service scripts

pom.xml
remove japicmp exclusion which was added yesterday, that was required for rds feature release
=> remove japicmp exclusion for rds InvalidMaxAcuException

core/protocols/aws-json-protocol/src/main/java/software/amazon/awssdk/protocols/json/internal/ProtocolFact.java, test/protocol-tests-core/src/main/resources/software/amazon/awssdk/protocol/suites/cases/smithy-rpcv2-input.json
RPCv2 needs the Accept header with value "application/cbor". See [this open PR](https://github.com/smithy-lang/smithy/pull/2417/).
=> Add the required Accept header for RPCv2

.changes/next-release/bugfix-AWSSDKforJavav2-8d6fb63.json, core/aws-core/src/main/java/software/amazon/awssdk/awscore/client/builder/AwsDefaultClientBuilder.java, core/retries/src/main/java/software/amazon/awssdk/retries/internal/BaseRetryStrategy.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/retry/SdkDefaultRetryStrategy.java, test/protocol-tests/src/test/java/software/amazon/awssdk/protocol/tests/retry/RetryStrategyBackfillsEmptyRetryConditions.java, test/protocol-tests/src/test/java/software/amazon/awssdk/protocol/tests/retry/RetryStrategyBackfillsEmtpyRetryConditions.java
This change adds the default retry conditions in the client builder if none are configured to behave similarly to retry policies that are configured behind the scenes without the users having to do that themselves. 
This will prevent customers using directly the retry strategies builders from `DefaultRetryStrategy` to end up with a no-op strategy.
=> Add retry conditions to the strategy if none is configured

core/http-auth-aws/src/main/java/software/amazon/awssdk/http/auth/aws/internal/signer/V4CanonicalRequest.java
Fix NPE thrown from signer when a header value is null by adding null check for the value.
=> Fix NPE thrown from signer when a header value is null

core/sdk-core/src/main/java/software/amazon/awssdk/core/ResponseInputStream.java
Clarification on the difference in behaviour of the close/abort method when using the Apache http client.
=> Response input stream javadoc improvement

.changes/next-release/bugfix-AWSSDKforJavav2-8c50ffa.json, core/retries/src/main/java/software/amazon/awssdk/retries/AdaptiveRetryStrategy.java, core/retries/src/main/java/software/amazon/awssdk/retries/DefaultRetryStrategy.java, core/retries/src/main/java/software/amazon/awssdk/retries/LegacyRetryStrategy.java, core/retries/src/main/java/software/amazon/awssdk/retries/StandardRetryStrategy.java
As reported offline the javadocs of the retries strategies do not match the defaults, in particular regarding the backoff strategies, since those are only applied in the static builders in `DefaultRetryStrategy` class. This change moves setting the default backoff strategies out of `DefaultRetryStrategy` and into the builders themselves.
=> Move default backoff strategies to the builders to match the docs

test/v2-migration-tests/src/test/java/software/amazon/awssdk/v2migrationtests/MavenProjectTest.java
Regression in rewrite-maven-plugin 5.44.0
Filed bug report
https://github.com/openrewrite/rewrite-maven-plugin/issues/894
Pin to previous working version 5.43.0
build passes locally
=> Pin rewrite-maven-plugin version for migration test

core/protocols/aws-json-protocol/src/main/java/software/amazon/awssdk/protocols/json/internal/marshall/JsonProtocolMarshaller.java
Smithy RPCv2 uses `application/vnd.amazon.eventstream` as its `Content-Type` for event streams. See [the requests section](https://smithy.io/2.0/additional-specs/protocols/smithy-rpc-v2.html#requests) of the spec.
This bit was missed when the protocol was added, and was found during testing.
=> Add AwsJsonProtocol.SMITHY_RPC_V2_CBOR to properly handle it

codegen/src/main/java/software/amazon/awssdk/codegen/poet/rules/EndpointRulesClientTestSpec.java, codegen/src/main/java/software/amazon/awssdk/codegen/poet/rules2/AssignTypesVisitor.java, codegen/src/main/java/software/amazon/awssdk/codegen/poet/rules2/CodeGeneratorVisitor.java, codegen/src/main/java/software/amazon/awssdk/codegen/poet/rules2/ExpressionParser.java, codegen/src/main/java/software/amazon/awssdk/codegen/poet/rules2/MemberAccessExpression.java, codegen/src/main/java/software/amazon/awssdk/codegen/poet/rules2/RewriteRuleExpressionVisitor.java, codegen/src/main/java/software/amazon/awssdk/codegen/poet/rules2/Tokenizer.java, codegen/src/test/java/software/amazon/awssdk/codegen/poet/rules2/TokenizerTest.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/c2j/query/customization-endpoint-know-prop.config, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/c2j/query/customization.config, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/c2j/query/endpoint-rule-set.json, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/c2j/query/endpoint-tests.json, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/c2j/query/service-2.json, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/sra/test-query-async-client-class.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/sra/test-query-client-class.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/test-query-async-client-class.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/test-query-client-class.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/rules/endpoint-parameters.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/rules/endpoint-provider-class.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/rules/endpoint-provider-know-prop-override-class.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/rules/endpoint-resolve-interceptor-preSra.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/rules/endpoint-resolve-interceptor.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/rules/endpoint-rules-test-class.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/rules2/endpoint-provider-class.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/rules2/endpoint-provider-know-prop-override-class.java
1) Add support for parsing direct index access in endpoint rules set, e.g., `[123]`
2) Add support for map MemberModel in client endpoint tests
Added codegen tests
Builds pass locally for new feature
=> Codegen direct index access and map member model

.changes/next-release/bugfix-AWSSDKforJavav2-c212259.json, http-clients/apache-client/src/main/java/software/amazon/awssdk/http/apache/internal/impl/ApacheHttpRequestFactory.java, http-clients/url-connection-client/src/test/java/software/amazon/awssdk/http/urlconnection/UrlConnectionHttpClientDefaultWireMockTest.java, test/http-client-tests/src/main/java/software/amazon/awssdk/http/SdkHttpClientDefaultTestSuite.java, test/protocol-tests-core/src/main/resources/software/amazon/awssdk/protocol/suites/cases/rest-json-contenttype.json
Though providing request bodies on these HTTP methods is uncommon, it is [not disallowed by the spec](https://www.rfc-editor.org/rfc/rfc9110.html#section-9.3.1-6), and is used in certain Elasticsearch/OpenSearch APIs. Authenticating with Amazon OpenSearch Service can be done via SigV4 and we re-use the SDK's signing logic to provide that in https://github.com/opensearch-project/opensearch-java.
We've received multiple bug reports of users having trouble making certain requests using the `ApacheHttpClient` (https://github.com/opensearch-project/opensearch-java/issues/712, https://github.com/opensearch-project/opensearch-java/issues/521), where the client itself doesn't complain or error but silently drops the request body resulting in a mismatched signature on the server.
The Netty & CRT …
=> Fix ApacheHttpClient's handling of request bodies on DELETE, GET, HEAD & OPTIONS requests

.changes/next-release/bugfix-DynamoDBEnhancedClient-4d6cb64.json, services-custom/dynamodb-enhanced/src/main/java/software/amazon/awssdk/enhanced/dynamodb/internal/converter/attribute/DurationAttributeConverter.java, services-custom/dynamodb-enhanced/src/test/java/software/amazon/awssdk/enhanced/dynamodb/internal/converter/attribute/DurationAttributeConverterTest.java
The `DurationAttributeConverter` class was incorrectly considering  every number past the decimal point as a nanosecond when de-serializing the duration attribute.
Added "0" padding of appropriate length before considering the decimals as nano-seconds, e.g. `0.01` becomes `0.010000000`  so that the amount of nanoseconds can be correctly set to `10,000,000`.
Added unit tests for `DurationAttributeConverter` class
=> Fix DurationAttributeConverter nano second deserialization

test/v2-migration-tests/src/test/resources/software/amazon/awssdk/v2migrationtests/maven/after/src/main/java/foo/bar/Application.java, test/v2-migration-tests/src/test/resources/software/amazon/awssdk/v2migrationtests/maven/after/src/main/java/foo/bar/S3.java, test/v2-migration-tests/src/test/resources/software/amazon/awssdk/v2migrationtests/maven/before/src/main/java/foo/bar/Application.java, test/v2-migration-tests/src/test/resources/software/amazon/awssdk/v2migrationtests/maven/before/src/main/java/foo/bar/S3.java, v2-migration/src/main/java/software/amazon/awssdk/v2migration/S3NonStreamingRequestToV2.java, v2-migration/src/main/java/software/amazon/awssdk/v2migration/internal/utils/NamingConversionUtils.java, v2-migration/src/main/resources/META-INF/rewrite/aws-sdk-java-v1-to-v2.yml, v2-migration/src/main/resources/META-INF/rewrite/change-s3-methods.yml, v2-migration/src/main/resources/META-INF/rewrite/s3-methods-constructor-to-fluent.yml, v2-migration/src/test/java/software/amazon/awssdk/v2migration/internal/utils/NamingConversionUtilsTest.java
Adding support for additional S3 non-streaming methods
- Support for all single String (bucket) and two-String args methods
- Transform S3 API / POJO name mismatches, e.g. GetObjectMetadata -> HeadObject, InitiateMpu -> CreateMpu
Added unit and end-to-end tests
=> Add recipes for S3 non-streaming methods

codegen/src/main/java/software/amazon/awssdk/codegen/model/service/AuthType.java, codegen/src/main/java/software/amazon/awssdk/codegen/poet/auth/scheme/AuthSchemeCodegenMetadataExt.java, codegen/src/test/java/software/amazon/awssdk/codegen/poet/ClientTestModels.java, codegen/src/test/java/software/amazon/awssdk/codegen/poet/auth/scheme/AuthSchemeSpecTest.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/auth/scheme/ops-auth-sigv4a-value-auth-scheme-default-provider.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/c2j/ops-with-auth-sigv4a-value/customization.config, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/c2j/ops-with-auth-sigv4a-value/service-2.json
Support `sigv4a` auth
```json
"metadata": {
"apiVersion": "2015-07-09",
"endpointPrefix": "foo",
"protocol": "rest-json",
"serviceFullName": "Amazon Foo Service",
"serviceId": "Foo",
"signatureVersion": "v4",
"auth": ["aws.auth#sigv4a" ,"aws.auth#sigv4"],
"uid": "foo-2015-07-09"
}
```
- Added new AuthType 
- Added Default Authscheme creation for sigv4a in codegen
Note : Separate PR will be created for operation with Sigv4a trait and unsignedPayload. This PR is sepcific just to service metadata
- Added Junits in codegen
=> Add support for Multi Auth Sigv4a for Service metadata

codegen/src/main/java/software/amazon/awssdk/codegen/poet/auth/scheme/AuthSchemeParamsSpec.java, codegen/src/main/java/software/amazon/awssdk/codegen/poet/auth/scheme/AuthSchemeSpecUtils.java, codegen/src/main/java/software/amazon/awssdk/codegen/poet/auth/scheme/DefaultAuthSchemeParamsSpec.java, codegen/src/main/java/software/amazon/awssdk/codegen/utils/AuthUtils.java, codegen/src/test/java/software/amazon/awssdk/codegen/poet/auth/scheme/AuthSchemeSpecTest.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/auth/scheme/ops-auth-sigv4a-value-auth-scheme-default-params.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/auth/scheme/ops-auth-sigv4a-value-auth-scheme-params.java
- Update AuthScemeParams with RegionSet for Sigv4a auth Scheme
- These regionSet parameter will be updated from ExecutionAttributes in the AuthScemeInterceptor (later PR)
- Updated `AuthSchemeParamsSpec` and `DefaultAuthSchemeParamsSpec` to generate code only if Sigv4a Auth is defined.
- Junits
=> Update AuthScemeParams with RegionSet for Sigv4a auth Scheme

.changes/next-release/bugfix-AWSSDKforJavav2MigrationTool-996edb5.json, test/v2-migration-tests/src/test/resources/software/amazon/awssdk/v2migrationtests/maven/after/src/main/java/foo/bar/SdkBytes.java, test/v2-migration-tests/src/test/resources/software/amazon/awssdk/v2migrationtests/maven/before/src/main/java/foo/bar/SdkBytes.java, v2-migration/src/main/java/software/amazon/awssdk/v2migration/SdkBytesToByteBuffer.java, v2-migration/src/main/resources/META-INF/rewrite/aws-sdk-java-v1-to-v2.yml
Java SDK v1 uses `ByteBuffer` to represent binary data while Java SDK v2 uses `SdkBytes`, so changing the method name is not sufficient for ByteBuffer getters and users will get compilation error.
Setter will be in a separate PR.
Convert SdkBytes to ByteBuffer for POJO getters
v1
```
ByteBuffer binaryValue = messageAttributeValue.getBinaryValue();
```
->
v2
```
ByteBuffer binaryValue = messageAttributeValue.binaryValue().asByteBuffer();
```
Added end to end tests.
Unit tests are not possible for `JavaTemplate` since it can't recognize the types.
=> Convert SdkBytes to ByteBuffer for POJO getters

.changes/2.30.0.json, .changes/next-release/feature-AmazonS3-c101d4d.json, CHANGELOG.md
=> Backfill changelog entry

codegen/src/main/java/software/amazon/awssdk/codegen/AddMetadata.java, codegen/src/main/java/software/amazon/awssdk/codegen/AddOperations.java, codegen/src/main/java/software/amazon/awssdk/codegen/model/config/customization/CustomizationConfig.java, codegen/src/main/java/software/amazon/awssdk/codegen/poet/auth/scheme/ModelAuthSchemeKnowledgeIndex.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/c2j/all-ops-with-auth-different-value/customization.config, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/c2j/all-ops-with-auth-same-value/customization.config, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/c2j/fine-grained-auth/customization.config, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/c2j/ops-with-auth-sigv4a-value/customization.config, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/c2j/ops-with-no-auth/customization.config, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/c2j/service-with-no-auth/customization.config, test/codegen-generated-classes-test/src/main/resources/codegen-resources/multiauth/customization.config
- Remove `useMultiAuth`  customization
- The feature/master/multi-auth is for supporting multi-auth by default , no need of additional customization since this branch will support `MultiAuth` feature.
- Removed customizaion for `useMultiAuth`
- Already present , note that tests associated with `test/codegen-generated-classes-test/src/main/resources/codegen-resources/multiauth/`  are passing even after removal of this customization since by default Multi auth is supported.
=> Remove `useMultiAuth`  customization

codegen/src/main/java/software/amazon/awssdk/codegen/CodeGenerator.java, codegen/src/main/java/software/amazon/awssdk/codegen/poet/client/traits/HttpChecksumTrait.java
Fix intermittent `ConcurrentModificationException` thrown from codegen
```
Failed to execute goal software.amazon.awssdk:codegen-maven-plugin:2.30.3-SNAPSHOT:generate (default) on project codegen-generated-classes-test: Execution default of goal software.amazon.awssdk:codegen-maven-plugin:2.30.3-SNAPSHOT:generate failed: Failed to generate code. Exception message : java.lang.RuntimeException: java.util.ConcurrentModificationException -> [Help 1]
```
The root cause is that we are sorting an ArrayList while iterating.
Updated the code to not sort the list while iterating
=> Fix intermittent ConcurrentModificationException thrown from codegen 

.changes/2.30.2.json, CHANGELOG.md
=> Backfill changelog

core/retries/src/main/java/software/amazon/awssdk/retries/AdaptiveRetryStrategy.java, core/retries/src/main/java/software/amazon/awssdk/retries/LegacyRetryStrategy.java, core/retries/src/main/java/software/amazon/awssdk/retries/StandardRetryStrategy.java
Removed an incorrect wording in the Java docs in the `AdaptiveRetryStrategy` as per offline report. The phrase removed was:
> Circuit breaking may prevent a first attempt in outage scenarios to protect the downstream service.
Circuit breaking won't prevent the first attempt ever.
While there, I also aligned the docs to use the same wording on this regard.
=> Rewrite the javadocs to align the wording

.changes/next-release/bugfix-AmazonS3-6b41d5e.json, services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/s3express/S3ExpressIdentityCache.java, services/s3/src/test/java/software/amazon/awssdk/services/s3/functionaltests/S3ExpressTest.java
This value already matched the service-side default, and was already not sent by most SDK languages.
=> Stop populating SessionMode by default for the SDK-created S3 express sessions.

.changes/next-release/feature-NettyNIOHTTPClient-8f8589d.json, http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/NettyNioAsyncHttpClient.java, http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/internal/ChannelPipelineInitializer.java, http-clients/netty-nio-client/src/test/java/software/amazon/awssdk/http/nio/netty/NettyClientAlpnTest.java, test/codegen-generated-classes-test/src/main/resources/codegen-resources/h2/service-2.json, test/codegen-generated-classes-test/src/test/java/software/amazon/awssdk/services/h2/AlpnHttpTest.java
Mock tests with h2 clients making requests to HTTP endpoints fail with [recent ALPN addition](https://github.com/aws/aws-sdk-java-v2/pull/5794)
Skip adding ALPN handler if request endpoint is HTTP and the default client setting is ALPN. This maintains previous behavior of prior knowledge protocol negotiation, and avoids breaking changes for existing generated clients with h2 protocol setting
Continue to throw error if request endpoint is HTTP and user configures ALPN on client
=> Skip ALPN if request is HTTP endpoint

codegen/src/main/java/software/amazon/awssdk/codegen/poet/auth/scheme/AuthSchemeInterceptorSpec.java, codegen/src/main/java/software/amazon/awssdk/codegen/poet/auth/scheme/EndpointBasedAuthSchemeProviderSpec.java, codegen/src/main/java/software/amazon/awssdk/codegen/poet/builder/BaseClientBuilderClass.java, codegen/src/main/java/software/amazon/awssdk/codegen/poet/builder/BaseClientBuilderInterface.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/builder/sra/test-client-builder-endpoints-auth-params.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/builder/sra/test-multi-auth-sigv4a-client-builder-class.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/builder/test-client-builder-endpoints-auth-params.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/builder/test-multi-auth-sigv4a-client-builder-interface.java, core/aws-core/src/main/java/software/amazon/awssdk/awscore/client/builder/AwsDefaultClientBuilder.java, test/codegen-generated-classes-test/src/test/java/software/amazon/awssdk/services/auth/Sigv4aSigningRegionSetTest.java, test/codegen-generated-classes-test/src/test/java/software/amazon/awssdk/services/multiauth/MultiAuthSigningPropertiesTest.java
After internal surface api review we decided to change `sigv4aRegionSet` to `sigv4aSigningRegionSet` to be consistent with environment variable  and configuration file property  as mentioned below in specs
```
This configuration must also be supported as an environment variable called AWS_SIGV4A_SIGNING_REGION_SET and as a configuration file property called sigv4a_signing_region_set
```
- renamed  sigv4aRegionSet to sigv4aSigningRegionSet
=> Renamed API name `sigv4aRegionSet` to `sigv4aSigningRegionSet` to be conssistent with Environment variable and System Property name for this option

v2-migration/src/main/java/software/amazon/awssdk/v2migration/internal/utils/SdkTypeUtils.java, v2-migration/src/test/java/software/amazon/awssdk/v2migration/internal/utils/SdkTypeUtilsTest.java
Skip transforming non-SDK libraries:
- Lambda runtime :https://docs.aws.amazon.com/lambda/latest/dg/java-handler.html
- Kinesis Client Library (KCL) : https://docs.aws.amazon.com/streams/latest/dev/kinesis-record-processor-implementation-app-java.html
- Kinesis Producer Library (KPL) : https://docs.aws.amazon.com/streams/latest/dev/developing-producers-with-kpl.html
=> Migration tool skip transforming non-SDK libraries

.changes/next-release/feature-AWSCRTHTTPClient-7ff47eb.json, http-clients/aws-crt-client/src/main/java/software/amazon/awssdk/http/crt/internal/AwsCrtConfigurationUtils.java, http-clients/aws-crt-client/src/test/java/software/amazon/awssdk/http/crt/internal/AwsCrtConfigurationUtilsTest.java, pom.xml
This change updates the default Post Quantum TLS policy in the AWS Common Runtime HTTP SDK Client. This new TLS policy adds support for `X25519MLKEM768` Hybrid Post-Quantum TLS key exchange algorithm. Support for older draft hybrid algorithms that use Kyber are still kept, but at lower priority. 
Updates the default Post Quantum TLS policy in the AWS Common Runtime HTTP SDK Client to the new policy added in https://github.com/awslabs/aws-crt-java/pull/865. The effect of this update is to add X25519MLKEM768 to the top of the TLS SupportedGroups preference list. All other TLS SupportedGroups are kept. Older draft PQ algorithms will be removed in a later PR.
Unit tests, CI tests, manual s2n-tls PQ tests against AWS TLS endpoints.
=> Add support for ML-KEM in Post-Quantum TLS Config

core/protocols/aws-json-protocol/src/main/java/software/amazon/awssdk/protocols/json/internal/marshall/JsonProtocolMarshaller.java
For RPCv2 we were unconditionally setting the `:content-type` header for each event to `application/vnd.amazon.eventstream` because we are first setting [that content-type on the request](https://github.com/aws/aws-sdk-java-v2/blob/6c74e87c0ef16472b33fb2dc33de6a18806dbe3a/core/aws-core/src/main/java/software/amazon/awssdk/awscore/eventstream/EventStreamInitialRequestInterceptor.java#L56) then [using it in the request content-type in the event stream](https://github.com/aws/aws-sdk-java-v2/blob/6c74e87c0ef16472b33fb2dc33de6a18806dbe3a/core/aws-core/src/main/java/software/amazon/awssdk/awscore/eventstream/EventStreamInitialRequestInterceptor.java#L81)
This change fixes this to properly use the given `:content-type`. Fixes #5894.
=> Properly set content-type for RPCv2 event streams

.changes/next-release/bugfix-AWSSDKforJavav2-ed80b40.json, core/auth/src/main/java/software/amazon/awssdk/auth/signer/internal/AbstractAws4Signer.java, core/auth/src/main/java/software/amazon/awssdk/auth/signer/internal/util/HeaderTransformsHelper.java, core/auth/src/test/java/software/amazon/awssdk/auth/signer/Aws4SignerTest.java, core/auth/src/test/java/software/amazon/awssdk/auth/signer/internal/util/HeaderTransformsHelperTest.java, core/http-auth-aws/src/main/java/software/amazon/awssdk/http/auth/aws/internal/signer/V4CanonicalRequest.java, core/http-auth-aws/src/test/java/software/amazon/awssdk/http/auth/aws/internal/signer/V4CanonicalRequestTest.java, test/codegen-generated-classes-test/src/test/java/software/amazon/awssdk/services/AsyncRequestCompressionTest.java
Currently, AWS SDKs sign the Transfer-Encoding chunked header during SigV4 authentication, causing signature validation failures in specific scenarios.
The issue occurs because Transfer-Encoding is a hop-by-hop header that intermediate proxies can modify. 
This change proposes to stop signing the Transfer-Encoding header in SigV4(a).
Note : for Sigv4a signers using CRT it is done in  crt side with https://github.com/awslabs/aws-c-auth/pull/261 
- Added Transfer-Encoding in list of `LIST_OF_HEADERS_TO_IGNORE_IN_LOWER_CASE` which already skips some of predefined headers
- Added Junits
- Added codegen-tst and checked Authorization doesnot have ` Transfer-Encoding`
=> Do not sign Transfer-Encoding Header  if present on the request

test/service-test-utils/src/main/java/software/amazon/awssdk/testutils/service/S3BucketUtils.java
S3 integration tests now often fails during release due to BucketAlreadyExistsException. I added epoch to the temporary bucket name to prevent the chance same bucket name occurs. If it still fails then it could be multiple execution of the same test class in parallel during the test run
added epoch to the temporary bucket name
=> add epoch to temp bucket name

test/v2-migration-tests/src/test/resources/software/amazon/awssdk/v2migrationtests/maven/after/src/main/java/foo/bar/S3.java, test/v2-migration-tests/src/test/resources/software/amazon/awssdk/v2migrationtests/maven/before/src/main/java/foo/bar/S3.java, v2-migration/src/main/java/software/amazon/awssdk/v2migration/S3NonStreamingRequestToV2Complex.java, v2-migration/src/main/resources/META-INF/rewrite/change-s3-methods.yml, v2-migration/src/main/resources/META-INF/rewrite/s3-methods-constructor-to-fluent.yml
Add transform for `CompleteMultipartUploadRequest` POJO
We cannot transform `.withPartETags()` setter that takes `UploadPartResult` because v1 has handwritten logic to add the part number to `UploadPartResult`, the part number is not returned by the server.
- `withPartETags(Collection<UploadPartResult> uploadPartResultsCollection)`
- `withPartETags(UploadPartResult... uploadPartResults)`
Added end-to-end tests
=> Migration tool CompleteMpuRequest transform

codegen/src/main/java/software/amazon/awssdk/codegen/emitters/CodeWriter.java
BufferedWriter is created in a try-with-resources, so it is always closed, but closing the writer does not actually flush the output stream; it just flushes the remaining data *buffered* in BufferedWriter to the stream:
https://github.com/openjdk/jdk/blob/3c72c04de7a43d265dae7160fe53baaaa8ae6f73/src/java.base/share/classes/java/io/BufferedWriter.java#L311-L322
We still need to call BufferedWriter#flush() explicitly so that the output stream is flushed:
https://github.com/openjdk/jdk/blob/3c72c04de7a43d265dae7160fe53baaaa8ae6f73/src/java.base/share/classes/java/io/BufferedWriter.java#L298-L308
This should hopefully fix issues where
CodeWriter#validateFileContentMatches fails when comparing contents because the file on disk is truncated.
=> Flush writer after writing generated code

services-custom/s3-transfer-manager/src/test/java/software/amazon/awssdk/transfer/s3/internal/S3JavaMultipartTransferProgressListenerTest.java
- S3JavaMultipartTransferProgressListenerTest failed  number of times in PR Codebuild check builds
```
[ERROR] Tests run: 12, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 9.115 s <<< FAILURE! -- in software.amazon.awssdk.transfer.s3.internal.S3JavaMultipartTransferProgressListenerTest
[ERROR] software.amazon.awssdk.transfer.s3.internal.S3JavaMultipartTransferProgressListenerTest.copyWithJavaBasedClient_listeners_reports_ProgressWhenSuccess_copy -- Time elapsed: 0.632 s <<< FAILURE!
org.opentest4j.AssertionFailedError: 
Expecting value to be true but was false
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
```
- Earlier the tets cases was waiting for 500 ms for CaptureListener to complete
- Added a finite pre-emptive assert to wait fort …
=> Fix Flaky S3JavaMultipartTransferProgressListenerTest test case

test/v2-migration-tests/src/test/java/software/amazon/awssdk/v2migrationtests/MavenNoCompileTest.java, test/v2-migration-tests/src/test/java/software/amazon/awssdk/v2migrationtests/MavenTestBase.java, test/v2-migration-tests/src/test/java/software/amazon/awssdk/v2migrationtests/MavenTransferManagerTest.java, test/v2-migration-tests/src/test/resources/software/amazon/awssdk/v2migrationtests/maven-nocompile/after/pom.xml, test/v2-migration-tests/src/test/resources/software/amazon/awssdk/v2migrationtests/maven-nocompile/after/src/main/java/foo/bar/S3Transforms.java, test/v2-migration-tests/src/test/resources/software/amazon/awssdk/v2migrationtests/maven-nocompile/before/pom.xml, test/v2-migration-tests/src/test/resources/software/amazon/awssdk/v2migrationtests/maven-nocompile/before/src/main/java/foo/bar/S3Transforms.java, test/v2-migration-tests/src/test/resources/software/amazon/awssdk/v2migrationtests/maven-tm/after/src/main/java/foo/bar/TransferManagerS3.java, test/v2-migration-tests/src/test/resources/software/amazon/awssdk/v2migrationtests/maven-tm/before/src/main/java/foo/bar/TransferManagerS3.java, test/v2-migration-tests/src/test/resources/software/amazon/awssdk/v2migrationtests/maven/after/src/main/java/foo/bar/S3Streaming.java, test/v2-migration-tests/src/test/resources/software/amazon/awssdk/v2migrationtests/maven/after/src/main/java/foo/bar/S3_Streaming.java, test/v2-migration-tests/src/test/resources/software/amazon/awssdk/v2migrationtests/maven/before/src/main/java/foo/bar/S3Streaming.java, test/v2-migration-tests/src/test/resources/software/amazon/awssdk/v2migrationtests/maven/before/src/main/java/foo/bar/S3_Streaming.java, v2-migration/src/main/java/software/amazon/awssdk/v2migration/ConstructorToFluent.java, v2-migration/src/main/java/software/amazon/awssdk/v2migration/HttpSettingsToHttpClient.java, v2-migration/src/main/java/software/amazon/awssdk/v2migration/S3NonStreamingRequestToV2.java, v2-migration/src/main/java/software/amazon/awssdk/v2migration/S3NonStreamingRequestToV2Complex.java, v2-migration/src/main/java/software/amazon/awssdk/v2migration/S3PutObjectRequestToV2.java, v2-migration/src/main/java/software/amazon/awssdk/v2migration/S3StreamingRequestToV2.java, v2-migration/src/main/java/software/amazon/awssdk/v2migration/S3StreamingResponseToV2.java, v2-migration/src/main/java/software/amazon/awssdk/v2migration/TransferManagerMethodsToV2.java, v2-migration/src/main/java/software/amazon/awssdk/v2migration/internal/utils/NamingConversionUtils.java, v2-migration/src/main/java/software/amazon/awssdk/v2migration/internal/utils/S3TransformUtils.java, v2-migration/src/main/java/software/amazon/awssdk/v2migration/internal/utils/SdkTypeUtils.java, v2-migration/src/main/resources/META-INF/rewrite/aws-sdk-java-v1-to-v2-with-tm.yml, v2-migration/src/main/resources/META-INF/rewrite/aws-sdk-java-v1-to-v2.yml, v2-migration/src/main/resources/META-INF/rewrite/change-s3-methods.yml, v2-migration/src/main/resources/META-INF/rewrite/s3-methods-constructor-to-fluent.yml
1.
Refactored common code to `S3TransformUtils` (separate commit)
2.
Transforms for `PutObjectRequest`:
- Constructors:
`PutObjectRequest(String bucketName, String key, File file)`
`PutObjectRequest(String bucketName, String key, String redirectLocation)`
- Setters:
`withFile` `setFile`
`withInputStream` `setInputStream`
`withRequesterPays`
`withBucketName`
`withCannedAcl`
3.
Transforms for `AmazonS3.putObject(PutObjectRequest)`
- If no payload set: `RequestBody.empty()`
- If `File` set: `RequestBody.fromFile()`
- If `InputStream` set: 
- If `Content-Length` provided: `RequestBody.fromInputStream(inputStream, contentLength)`
- Else: `RequestBody.fromContentProvider(() -> inputStream, "binary/octet-stream")` (comment will be added to tell users to specify length, and warn stream will be …
=> Migration Tool: PutObjectRequest File/InputStream transform

.changes/next-release/feature-AWSSDKforJavav2-8a464f3.json, core/imds/src/main/java/software/amazon/awssdk/imds/Ec2MetadataAsyncClient.java, core/imds/src/main/java/software/amazon/awssdk/imds/Ec2MetadataClient.java, core/imds/src/main/java/software/amazon/awssdk/imds/Ec2MetadataClientException.java, core/imds/src/main/java/software/amazon/awssdk/imds/internal/AsyncHttpRequestHelper.java, core/imds/src/main/java/software/amazon/awssdk/imds/internal/DefaultEc2MetadataClient.java, core/imds/src/test/java/software/amazon/awssdk/imds/internal/BaseEc2MetadataClientTest.java
* Creating EC2MetadataClientException for IMDS unsuccessful responses.
The IMDS client currently throws SdkClientException for all 4XX errors, contradicting AWS SDK guidelines which state that client exceptions should only be used when the client fails to make a service call. When IMDS returns a response (even 4XX), it means the call was successful but rejected by the service. This improper error classification prevents specific error handling. Users can't implement specific handling for such cases because the client discards the HTTP status code information, forcing all errors to be treated the same way.
Fixing https://github.com/aws/aws-sdk-java-v2/issues/5786
Created a new Ec2MetadataClientException extending SdkClientException that preserves HTTP status codes from IMDS responses.
The …
=> Create EC2MetadataClientException for IMDS 4XX errors (#5947)

core/sdk-core/src/main/java/software/amazon/awssdk/core/io/SdkFilterInputStream.java
Fix javadocs for `SdkFilterInputStream.abortIfNeeded()`
https://github.com/aws/aws-sdk-java-v2/issues/5979
=> Fix javadocs to clarify interrrupted status

test/v2-migration-tests/pom.xml, test/v2-migration-tests/src/test/resources/software/amazon/awssdk/v2migrationtests/maven/after/pom.xml, test/v2-migration-tests/src/test/resources/software/amazon/awssdk/v2migrationtests/maven/after/src/main/java/foo/bar/Application.java, test/v2-migration-tests/src/test/resources/software/amazon/awssdk/v2migrationtests/maven/before/pom.xml, test/v2-migration-tests/src/test/resources/software/amazon/awssdk/v2migrationtests/maven/before/src/main/java/foo/bar/Application.java, v2-migration/src/main/java/software/amazon/awssdk/v2migration/DateToInstant.java, v2-migration/src/main/resources/META-INF/rewrite/aws-sdk-java-v1-to-v2-with-tm.yml, v2-migration/src/main/resources/META-INF/rewrite/aws-sdk-java-v1-to-v2.yml
v1 takes `Date` args, while v2 takes `Instant` args
Added new recipe `DateToInstant` to append `toInstant()` to `Date` args
Added end to end tests
=> Migration tool - Date to Instant

test/v2-migration-tests/src/test/resources/software/amazon/awssdk/v2migrationtests/maven/after/src/main/java/foo/bar/S3.java, test/v2-migration-tests/src/test/resources/software/amazon/awssdk/v2migrationtests/maven/before/src/main/java/foo/bar/S3.java, v2-migration/src/main/java/software/amazon/awssdk/v2migration/S3UriToV2.java, v2-migration/src/main/java/software/amazon/awssdk/v2migration/internal/utils/S3TransformUtils.java, v2-migration/src/main/java/software/amazon/awssdk/v2migration/internal/utils/SdkTypeUtils.java, v2-migration/src/main/resources/META-INF/rewrite/aws-sdk-java-v1-to-v2-with-tm.yml, v2-migration/src/main/resources/META-INF/rewrite/aws-sdk-java-v1-to-v2.yml
Transform v1 `AmazonS3URI` to v2 `S3Uri`
https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/migration-s3-uri-parser.html
new recipe `S3UriToV2`
added end to end testing
=> Migration Tool AmazonS3URI transform

test/v2-migration-tests/src/test/resources/software/amazon/awssdk/v2migrationtests/maven-nocompile/after/src/main/java/foo/bar/S3Transforms.java, test/v2-migration-tests/src/test/resources/software/amazon/awssdk/v2migrationtests/maven-nocompile/before/src/main/java/foo/bar/S3Transforms.java, test/v2-migration-tests/src/test/resources/software/amazon/awssdk/v2migrationtests/maven/after/src/main/java/foo/bar/S3.java, test/v2-migration-tests/src/test/resources/software/amazon/awssdk/v2migrationtests/maven/before/src/main/java/foo/bar/S3.java, v2-migration/src/main/java/software/amazon/awssdk/v2migration/S3NonStreamingRequestToV2Complex.java, v2-migration/src/main/java/software/amazon/awssdk/v2migration/internal/utils/S3TransformUtils.java
Transforms for S3 `generatePresignedUrl()`
Does not cover `GeneratePresignedUrlRequest` POJO
Added to `S3NonStreamingRequestToV2Complex` recipe
End to end tests
=> Migration Tool : S3 generatePresignedUrl

test/v2-migration-tests/src/test/resources/software/amazon/awssdk/v2migrationtests/maven-nocompile/after/src/main/java/foo/bar/S3Transforms.java, test/v2-migration-tests/src/test/resources/software/amazon/awssdk/v2migrationtests/maven/after/src/main/java/foo/bar/Application.java, test/v2-migration-tests/src/test/resources/software/amazon/awssdk/v2migrationtests/maven/before/src/main/java/foo/bar/Application.java, v2-migration/src/main/java/software/amazon/awssdk/v2migration/DateToInstant.java, v2-migration/src/main/java/software/amazon/awssdk/v2migration/S3NonStreamingRequestToV2Complex.java, v2-migration/src/main/java/software/amazon/awssdk/v2migration/S3PutObjectRequestToV2.java, v2-migration/src/main/java/software/amazon/awssdk/v2migration/SettersToBuilderV2.java, v2-migration/src/main/java/software/amazon/awssdk/v2migration/V1SetterToV2.java, v2-migration/src/main/java/software/amazon/awssdk/v2migration/internal/utils/S3TransformUtils.java, v2-migration/src/main/resources/META-INF/rewrite/aws-sdk-java-v1-to-v2-with-tm.yml, v2-migration/src/main/resources/META-INF/rewrite/aws-sdk-java-v1-to-v2.yml
Transform v1 model POJO setters 
from:
`request.setXX(val);`
to: 
`request = request.toBuilder().XX(val).build();`
new recipe `SettersToBuilderV2`
Added end to end tests
=> Migration tool : Setters to toBuilder() setters

test/v2-migration-tests/src/test/resources/software/amazon/awssdk/v2migrationtests/maven-nocompile/after/src/main/java/foo/bar/S3Transforms.java, test/v2-migration-tests/src/test/resources/software/amazon/awssdk/v2migrationtests/maven-nocompile/before/src/main/java/foo/bar/S3Transforms.java, test/v2-migration-tests/src/test/resources/software/amazon/awssdk/v2migrationtests/maven/after/src/main/java/foo/bar/S3.java, test/v2-migration-tests/src/test/resources/software/amazon/awssdk/v2migrationtests/maven/after/src/main/java/foo/bar/S3Streaming.java, test/v2-migration-tests/src/test/resources/software/amazon/awssdk/v2migrationtests/maven/before/src/main/java/foo/bar/S3Streaming.java, v2-migration/src/main/java/software/amazon/awssdk/v2migration/S3PutObjectRequestToV2.java, v2-migration/src/main/java/software/amazon/awssdk/v2migration/internal/utils/NamingConversionUtils.java, v2-migration/src/main/java/software/amazon/awssdk/v2migration/internal/utils/S3TransformUtils.java, v2-migration/src/main/java/software/amazon/awssdk/v2migration/internal/utils/SdkTypeUtils.java, v2-migration/src/main/resources/META-INF/rewrite/change-s3-methods.yml, v2-migration/src/main/resources/META-INF/rewrite/s3-methods-constructor-to-fluent.yml
Adds support for S3 POJO transforms:
`ObjectTagging, AccessControlList`
Adds support for `PutObjectRequest` setters:
`redirectLocation, tagging`
Adds comments for `PutObjectRequest` unsupported setters:
`sseCustomerKey, sseAwsKeyManagementParams, accessControlList`
Adds type check for `ObjectMetadata` arg in `putObject(bucket, key, InputStream, ObjectMetadata)` , as user could pass in a non variable, e.g. empty `new ObjectMetadata()` or mock value `any(ObjectMetadata.class)`
Added end to end tests
=> Migration Tool - PutObjectRequest setters

test/v2-migration-tests/src/test/resources/software/amazon/awssdk/v2migrationtests/maven-nocompile/after/src/main/java/foo/bar/S3Transforms.java, test/v2-migration-tests/src/test/resources/software/amazon/awssdk/v2migrationtests/maven-nocompile/before/src/main/java/foo/bar/S3Transforms.java, test/v2-migration-tests/src/test/resources/software/amazon/awssdk/v2migrationtests/maven/after/src/main/java/foo/bar/S3.java, test/v2-migration-tests/src/test/resources/software/amazon/awssdk/v2migrationtests/maven/after/src/main/java/foo/bar/S3Pojos.java, test/v2-migration-tests/src/test/resources/software/amazon/awssdk/v2migrationtests/maven/after/src/main/java/foo/bar/S3RequestConstructor.java, test/v2-migration-tests/src/test/resources/software/amazon/awssdk/v2migrationtests/maven/after/src/main/java/foo/bar/S3Streaming.java, test/v2-migration-tests/src/test/resources/software/amazon/awssdk/v2migrationtests/maven/before/pom.xml, test/v2-migration-tests/src/test/resources/software/amazon/awssdk/v2migrationtests/maven/before/src/main/java/foo/bar/S3.java, test/v2-migration-tests/src/test/resources/software/amazon/awssdk/v2migrationtests/maven/before/src/main/java/foo/bar/S3Pojos.java, test/v2-migration-tests/src/test/resources/software/amazon/awssdk/v2migrationtests/maven/before/src/main/java/foo/bar/S3RequestConstructor.java, test/v2-migration-tests/src/test/resources/software/amazon/awssdk/v2migrationtests/maven/before/src/main/java/foo/bar/S3Streaming.java, v2-migration/src/main/java/software/amazon/awssdk/v2migration/S3NonStreamingRequestToV2Complex.java, v2-migration/src/main/java/software/amazon/awssdk/v2migration/internal/utils/NamingConversionUtils.java, v2-migration/src/main/java/software/amazon/awssdk/v2migration/internal/utils/S3TransformUtils.java, v2-migration/src/main/resources/META-INF/rewrite/change-s3-methods.yml, v2-migration/src/main/resources/META-INF/rewrite/s3-methods-constructor-to-fluent.yml
Additional transforms for S3
Methods:
```
setBucketVersioningConfiguration()
restoreObjectV2()
getObject(GetObjectRequest getObjectRequest, File destinationFile)
getRegionName()
```
Pojos
```
SetBucketLoggingConfigurationRequest
SetBucketVersioningConfigurationRequest
SetBucketNotificationConfigurationRequest
SetRequestPaymentConfigurationRequest
BucketVersioningConfiguration
Owner
PartitionedPrefix
RestoreObjectRequest
SetBucketPolicyRequest
GetObjectTaggingResult
GetObjectRequest(String bucketName, String key, boolean isRequesterPays) 
DeleteVersionRequest(String bucketName, String key, String versionId, MultiFactorAuthentication mfa) - MultiFactorAuthentication POJO to String transform not supported
```
Added end to end tests
=> Migration tool - S3 transforms

.changes/next-release/bugfix-AWSSDKforJavav2-8ca55d3.json, v2-migration/pom.xml
Changing how the OpenRewrite recipes defined in `v2-migration/` are compiled. Adding `-parameters` option to Java compiler.
Without it, OpenRewrite might fail with errors like:
```
[ERROR] Recipe validation error in AddCommentToMethod.methodPattern: is required
[ERROR] Recipe validation error in NumberToDuration.methodPattern: is required
```
or
```
java.lang.NullPointerException: Cannot invoke "String.length()" because "s" is null
at org.antlr.v4.runtime.CharStreams.fromString (CharStreams.java:222)
at org.antlr.v4.runtime.CharStreams.fromString (CharStreams.java:212)
at org.openrewrite.java.MethodMatcher.<init> (MethodMatcher.java:112)
at software.amazon.awssdk.v2migration.NumberToDuration$Visitor.<init> (NumberToDuration.java:76)
```
Without `-parameters`, the code defined in this repo …
=> Compile v2 migration OpenRewrite recipes with `-parameters`

.changes/next-release/bugfix-AWSSDKforJavav2-2256787.json, core/protocols/aws-json-protocol/src/main/java/software/amazon/awssdk/protocols/json/internal/unmarshall/JsonUnmarshallingParser.java, core/protocols/aws-json-protocol/src/test/java/software/amazon/awssdk/protocols/json/internal/unmarshall/JsonUnmarshallingParserTest.java, core/protocols/protocol-core/src/main/java/software/amazon/awssdk/protocols/core/NumberToInstant.java, core/protocols/protocol-core/src/test/java/software/amazon/awssdk/protocols/core/NumberToInstantTest.java
Fixes #6064 
Addresses code that is impacted by double to long casts incorrectly truncating a millisecond off of fractional seconds unix timestamp values which are rounded due to IEEE 754 double precision behavior when the source value is multiplied by 1_000d.
Updated current truncation behavior to utilize the configured unmarshaller that uses parses the textual using a `BigDecimal` that doesn't loose any precision.
Added to that, we fixed a bug, for collections, maps and lists, to select the correct unmarshaller we need to get the type of the value instead of the type of the collection. The bug was not discovered before because to trigger it the model would need to use a non-numeric serialization for timestamps, which none of the standard JSON protocols does by default.
Added tests for …
=> Fix timestamp unmarshalling off-by-one errors

.brazil.json, bom/pom.xml, http-clients/apache5-client/pom.xml, http-clients/apache5-client/src/main/java/software/amazon/awssdk/http/apache5/Apache5HttpClient.java, http-clients/pom.xml, pom.xml, test/architecture-tests/pom.xml, test/tests-coverage-reporting/pom.xml
- Setting up empty Apache5x module so that implementation can be added in future PRs
| Additions | Checkbox |
|------|----------|
| Automatic-Module-Name in pom.xml | ✅ |
| Add to tests-coverage-reporting pom.xml | ✅ |
| Add to aws-sdk-java pom.xml | ❌ |
| Add to architecture-tests pom.xml | ✅ |
| Add to bom pom.xml | ✅ |
| Update japicmp plugin config | ✅ |
| Add package name mapping in .brazil.json | ✅ |
- Added a new module
- Specs used
Business Metrics
- The [client name](https://github.com/aws/aws-sdk-java-v2/blob/fce580e7a233a0f15e728eee86dac54f4a2ea9a3/http-client-spi/src/main/java/software/amazon/awssdk/http/SdkHttpClient.java#L42-L54) will be Apache5
Module Details
- module name: apache5-client
- Brazil jsonname: AwsJavaSdk-HttpClient-Apache5Client
* root package: …
=> Add initial empty module for Apache5x for seting up package

.changes/next-release/bugfix-AWSSDKforJavav2-175fc73.json, codegen/src/main/resources/software/amazon/awssdk/codegen/rules/Parameter.java.resource
Remove restriction, to allow default values to be set for non builtIn endpoint parameters
Compiled `codegen` and `codegen-generated-classes-test` locally
=> Allow default values for non-builtIn endpoint params

.changes/next-release/bugfix-AWSSDKforJavav2-ca1c44c.json, CONTRIBUTING.md, codegen/src/main/java/software/amazon/awssdk/codegen/customization/processors/SmithyRpcV2CborProtocolProcessor.java, codegen/src/main/java/software/amazon/awssdk/codegen/model/service/Http.java, codegen/src/test/java/software/amazon/awssdk/codegen/customization/processors/SmithyRpcV2CborProtocolProcessorTest.java, codegen/src/test/resources/software/amazon/awssdk/codegen/customization/processors/rpcv2-service-2.json, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/c2j/rpcv2/service-2.json
Smithy RPC v2 CBOR does not allow for custom URIs. This PR removes functionality that
would utilize non-`/` paths if present in the service model.
This commit removes the possiblity to customize the HTTP URI for the Smithy RPC v2 CBOR protocol by setting a non-`/` value in the `http` property.
It also fixes some typos in the contributing document.
Updated the test model to remove the `http` field.
=> Fix RPC v2 URI resolution

codegen/src/main/java/software/amazon/awssdk/codegen/poet/builder/BaseClientBuilderClass.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/builder/sra/test-bearer-auth-client-builder-class.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/builder/sra/test-client-builder-class.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/builder/sra/test-client-builder-internal-defaults-class.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/builder/sra/test-composed-sync-default-client-builder.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/builder/sra/test-multi-auth-sigv4a-client-builder-class.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/builder/sra/test-no-auth-ops-client-builder-class.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/builder/sra/test-no-auth-service-client-builder-class.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/builder/test-bearer-auth-client-builder-class.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/builder/test-client-builder-class.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/builder/test-client-builder-internal-defaults-class.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/builder/test-composed-sync-default-client-builder.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/builder/test-h2-service-client-builder-class.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/builder/test-h2-usePriorKnowledgeForH2-service-client-builder-class.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/builder/test-no-auth-ops-client-builder-class.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/builder/test-no-auth-service-client-builder-class.java
This is a partial clean up of the fast unmarshalling dialup. This change only enables adding the client config to enable the fast unmarshalling codepath by default.
=> Enable the fast unmarshalling codepath by default

.changes/next-release/removal-AWSSDKforJavav2-c58118f.json, .github/workflows/codebuild-ci.yml, buildspecs/migration-test.yml, buildspecs/resources/ci.cloudformation.yml, pom.xml, test/v2-migration-tests/pom.xml
Add `migration-test` Maven profile and exclude`v2-migration-tests` in regular builds. This can reduce 20+ mins and speed up the build. A separate CB will be created to run those tests in parallel.
Previous changes for endpoint tests:
https://github.com/aws/aws-sdk-java-v2/pull/3553 & https://github.com/aws/aws-sdk-java-v2/pull/4860
Tested locally:
`mvn install -pl :v2-migration-tests`  -> tests skipped
`mvn install -pl :v2-migration-tests -P migration-test`  -> tests ran
Codebuild jobs passed
=> Separate migration tests from regular builds

.changes/next-release/feature-AWSSDKforJavav2-b051142.json, codegen/src/main/resources/software/amazon/awssdk/codegen/rules/Partition.java.resource, codegen/src/main/resources/software/amazon/awssdk/codegen/rules2/RulesFunctions.java.resource
Small optimization. Lazily compile the region pattern instead of parsing it every time. This will pay the penalty of parsing it just once at the cost of using a bit more of memory to keep the parsed pattern.
=> Use a compiled pattern instead of parsing it every time

.changes/next-release/bugfix-AWSSDKforJavav2-b6c94e2.json, codegen/src/main/java/software/amazon/awssdk/codegen/poet/client/specs/JsonProtocolSpec.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/sra/test-aws-json-async-client-class.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/sra/test-cbor-async-client-class.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/sra/test-json-async-client-class.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/sra/test-json-client-class.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/test-aws-json-async-client-class.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/test-aws-query-compatible-json-async-client-class.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/test-aws-query-compatible-json-sync-client-class.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/test-batchmanager-async.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/test-cbor-async-client-class.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/test-cbor-client-class.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/test-custompackage-async.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/test-custompackage-sync.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/test-customservicemetadata-async.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/test-customservicemetadata-sync.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/test-endpoint-discovery-async.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/test-endpoint-discovery-sync.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/test-json-async-client-class.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/test-json-client-class.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/test-rpcv2-async-client-class.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/test-rpcv2-sync.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/test-unsigned-payload-trait-async-client-class.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/test-unsigned-payload-trait-sync-client-class.java, services/kinesis/src/test/java/software/amazon/awssdk/services/kinesis/KinesisExceptionTest.java
Update non-streaming error unmarshalling with the new mapping function.
This change updates the non-streaming error unmarshalling to use the same mapping function that was previously implemented for streaming operations. This change deprecates BaseAwsJsonProtocolFactory#createErrorResponseHandler(JsonOperationMetadata). We have switched all usages in generated code to the replacement, createErrorResponseHandler(JsonOperationMetadata,Function).
- Updated non-streaming error unmarshalling to use exceptionMetadataMapper
- Removed registerModeledException calls from initProtocolFactory
- Updated codegen test files to match new exception mapping implementation
- Added a test in kinesis service and verified it unmarshalled correctly
- Ran integration tests
=> Update non-streaming error unmarshaller with the new mapping function

http-clients/apache-client/pom.xml, http-clients/apache-client/src/test/java/software/amazon/awssdk/http/apache/internal/RepeatableInputStreamRequestEntityTest.java, http-clients/apache5-client/src/main/java/software/amazon/awssdk/http/apache5/Apache5HttpClient.java, http-clients/apache5-client/src/main/java/software/amazon/awssdk/http/apache5/internal/RepeatableInputStreamRequestEntity.java, http-clients/apache5-client/src/test/java/software/amazon/awssdk/http/apache5/Apache5HttpClientWireMockTest.java, http-clients/apache5-client/src/test/java/software/amazon/awssdk/http/apache5/internal/RepeatableInputStreamRequestEntityTest.java
- HTTP authentication retry scenarios failing with: `Cannot retry non-repeatable request`
- Occurs when initial request receives 401 Unauthorized and retry attempt fails
- Authentication challenges not handled properly
- Test cases for HTTP 301/302 responses failing due to Apache 5.x auto-redirect behavior
- RepeatableInputStreamRequestEntity implementation not properly integrated with Apache 5.x
- Inconsistent repeatability detection logic
- Apache 5.x follows redirects by default, while Apache 4.x returns redirect responses to client
- Tests expect to receive 301/302 responses for validation
- Apache 5.x auto-follows redirects, preventing test validation
1. Improved Stream Repeatability
- Changed inheritance to implement HttpEntity directly
- Enhanced repeatability detection logic
- …
=> Fix HTTP authentication retry failures by improving RepeatableInputStreamRequestEntity repeatability

.changes/next-release/bugfix-AWSSDKforJavav2-30203bb.json, core/profiles/src/main/java/software/amazon/awssdk/profiles/ProfileFile.java, core/profiles/src/main/java/software/amazon/awssdk/profiles/ProfileFileSupplier.java, core/profiles/src/test/java/software/amazon/awssdk/profiles/ProfileFileSupplierTest.java, core/profiles/src/test/java/software/amazon/awssdk/profiles/ProfileFileTest.java
Fix NPE in `ProfileFileSupplier.defaultSupplier` when both credentials and config files do not exist.
Fixes #5635 
When neither credentials or config files exist, calling `ProfileFileSupplier.defaultSupplier()` will return a supplier that raises an NPE when the value is accessed through `get` because the `ProfileFile.Builder` requires that both content and type are set. Note that `ProfileFile.defaultProfileFile()` will effectively return an empty ProfileFile in this case.
* Adds a package private `ProfileFile.empty()` method to create empty profile files.
* When When neither credentials or config files exist, `defaultSupplier` will return a static supplier with an empty profileFile - matching the behavior of `ProfileFile.defaultProfileFile()`.
* Improve the error message in …
=> Fix NPE in ProfileFileSupplier.defaultSupplier

.changes/next-release/bugfix-AWSS3EventNotifications-3774889.json, services-custom/s3-event-notifications/src/main/java/software/amazon/awssdk/eventnotifications/s3/internal/DefaultS3EventNotificationReader.java, services-custom/s3-event-notifications/src/test/java/software/amazon/awssdk/eventnotifications/s3/model/S3EventNotificationReaderTest.java
Currently, `S3EventNotification::fromJson` throws an exception when `eventTime` is `null`. This is problematic, since the code intends to allow for this field to be `null`, but [it uses the wrong variable when performing a guard](https://github.com/aws/aws-sdk-java-v2/blob/cb7f5c5d692ecf657e9545a48b02e78d7a132b2c/services-custom/s3-event-notifications/src/main/java/software/amazon/awssdk/eventnotifications/s3/internal/DefaultS3EventNotificationReader.java#L104).
This patch fixes the `null` guard by using the correct variable, `eventTime`, before attempting to parse it as an `Instant`.
Built the project locally (couldn't build some modules locally, so I just built the one modified)
```shell
./mvnw --projects :s3-event-notifications --also-make install
```
N/A
=> Fix S3 event parsing when eventName is present but eventTime is not

.changes/next-release/bugfix-S3TransferManager-ad9d4c6.json, services-custom/s3-transfer-manager/src/main/java/software/amazon/awssdk/transfer/s3/config/DownloadFilter.java, services-custom/s3-transfer-manager/src/test/java/software/amazon/awssdk/transfer/s3/config/DownloadFilterTest.java
- Override Predicate default methods to return DownloadFilter
- Add comprehensive parameterized tests
DownloadFilter inherits from Predicate<S3Object> but doesn't override the default methods properly. This causes compilation errors when trying to chain filters because the default Predicate methods return Predicate<T> instead of DownloadFilter.
Example of current issue:
```java
DownloadFilter folder1Filter = s3Object -> s3Object.key().startsWith("folder1");
DownloadFilter folder3Filter = s3Object -> s3Object.key().startsWith("folder3");
DownloadDirectoryRequest.Builder builder = DownloadDirectoryRequest.builder();
builder.filter(folder1Filter.or(folder3Filter)); // Compilation error 
```
1. Modified DownloadFilter interface to override default methods:
Override and() to return …
=> Fix DownloadFilter interface to properly return DownloadFilter type

.changes/next-release/bugfix-AWSSDKforJavav2-c5cff7a.json, core/auth/src/main/java/software/amazon/awssdk/auth/credentials/DefaultCredentialsProvider.java
* Add deprecation notice to create() method
* Update documentation to clearly explain the risks
* Recommend using builder().build() instead
- Follows up on fix implemented in #6080 which addressed this for S3 CRT client
- The `create()` method currently returns a singleton instance which can cause issues when shared between clients
- If one client closes the provider, all other clients using the same instance will fail
- Need to guide users toward using `builder().build()` for safer credential provider management
- Added `@Deprecated` annotation to `DefaultCredentialsProvider.create()` method
- Updated Javadoc for `create()` method to:
- Clearly explain the singleton behavior
- Warn about risks of shared instance
- Recommend using `builder().build()` instead
No additional unit tests were …
=> Deprecate DefaultCredentialsProvider.create() due to singleton issues

core/auth/src/main/java/software/amazon/awssdk/auth/credentials/DefaultCredentialsProvider.java
Java doc for https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/auth/credentials/DefaultCredentialsProvider.html#create() not rendered correctly for the link used inside deprecated message.
- Changed to @code to simplify representation
=> Invalid link link in deprecated message of DefaultCredentialsProvider replaced to @code

.changes/next-release/bugfix-AWSSDKforJavaV2-a136845.json, core/checksums/src/main/java/software/amazon/awssdk/checksums/internal/ConstructorCache.java
Fix a bug in ConstructorCache when classes are GC'ed but not removed from cache
The ConstructorCache uses WeakReferences to hold Class objects, which can be garbage-collected, leading to Optional.empty() results even though the class may still be load-able.  The ConstructorCache is using a [WeakHashMap](https://docs.oracle.com/javase/8/docs/api/java/util/WeakHashMap.html) which handles GC of the keys only, but not when values (the class Objects in this case) are cleaned up.  
The current design of the constructor cache was introduced to store the classloader and class with a weak reference, so that we don't prevent them from being unloaded.  It was intended to follow We do something similar in DynamoDB enhanced's [BeanTableSchema](https://github.com/aws/aws-sdk-java-v2/blob/master/services …
=> Fix a bug in ConstructorCache when classes are GC'ed but not removed from cache

services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/presignedurl/DefaultPresignedUrlManager.java, services/s3/src/test/java/software/amazon/awssdk/services/s3/internal/presignedurl/DefaultPresignedUrlManagerTest.java
Add DefaultPresignedUrlManager getObject implementation for S3 pre-signed URL
Implement the DefaultPresignedUrlManager class to enable GET operations using pre-signed URLs, allowing clients to perform operations skipping the signing and endpoint resolution.
Added DefaultPresignedUrlManager implementation that supports getObject operations with custom ResponseTransformers. Added TODO to deprecate IS_DISCOVERED_ENDPOINT attribute and replace with SKIP_ENDPOINT_RESOLUTION for better semantics. Added TODO to discuss if the Operation name for the metrics collector has to be changed. This can be addressed after the surface API Review.
Added comprehensive unit tests for DefaultPresignedUrlManager covering core functionality, error handling, range headers, resolved endpoint null, metric publisher …
=> Add DefaultPresignedUrlManager getObject implementation for S3 pre-signed URL

.changes/next-release/feature-AWSSDKforJavav2-960b6f3.json, .changes/next-release/feature-AWSSDKforJavav2-b405876.json, .changes/next-release/feature-AWSSDKforJavav2-f6d5c46.json, build-tools/src/main/resources/software/amazon/awssdk/spotbugs-suppressions.xml, codegen/src/main/java/software/amazon/awssdk/codegen/model/config/customization/CustomizationConfig.java, codegen/src/main/java/software/amazon/awssdk/codegen/poet/rules2/CodeGeneratorVisitor.java, codegen/src/main/java/software/amazon/awssdk/codegen/poet/rules2/EndpointProviderSpec2.java, codegen/src/test/java/software/amazon/awssdk/codegen/poet/ClientTestModels.java, codegen/src/test/java/software/amazon/awssdk/codegen/poet/rules/EndpointProviderCompiledRulesClassSpecTest.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/c2j/query/customization-uri-cache.config, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/rules2/endpoint-provider-uri-cache-class.java, core/auth-crt/src/main/java/software/amazon/awssdk/authcrt/signer/internal/CrtHttpRequestConverter.java, core/aws-core/src/main/java/software/amazon/awssdk/awscore/endpoint/AwsClientEndpointProvider.java, core/http-auth-aws/src/main/java/software/amazon/awssdk/http/auth/aws/crt/internal/util/CrtHttpRequestConverter.java, core/regions/src/main/java/software/amazon/awssdk/regions/internal/util/ServiceMetadataUtils.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/util/MetricUtils.java, http-client-spi/src/main/java/software/amazon/awssdk/http/SdkHttpRequest.java, http-clients/apache-client/src/main/java/software/amazon/awssdk/http/apache/internal/impl/ApacheHttpRequestFactory.java, http-clients/aws-crt-client/src/main/java/software/amazon/awssdk/http/crt/AwsCrtHttpClientBase.java, http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/NettyNioAsyncHttpClient.java, services/dynamodb/src/main/resources/codegen-resources/dynamodb/customization.config, utils/pom.xml, utils/src/main/java/software/amazon/awssdk/utils/cache/bounded/BoundedCache.java, utils/src/main/java/software/amazon/awssdk/utils/uri/SdkUri.java, utils/src/main/java/software/amazon/awssdk/utils/uri/internal/UriConstructorArgs.java, utils/src/test/java/software/amazon/awssdk/utils/SdkUriTest.java
Add caching for account id based endpoint in front of the URI constructors
Continuation of https://github.com/aws/aws-sdk-java-v2/pull/6087 and https://github.com/aws/aws-sdk-java-v2/pull/6228
- Replacing `LruCache` with a random-eviction `BoundedCache` in `SdkUri`
- Cache size of 150
- When full, performs batch eviction of 10 entries (arbitrarily chosen)
- Added a SdkURI class which caches calls to the various URI constructors methods.
- Added customization configuration to codegen to enable usage of SdkURI class in generated endpoint resolution code.
- Enabled this config only for DynamoDB.
- Unit test
- Performance tests and profiling
- Canary tests
=> URI Cache for DynamoDB Account Id based Endpoints

services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/presignedurl/DefaultAsyncPresignedUrlManager.java, services/s3/src/main/java/software/amazon/awssdk/services/s3/presignedurl/AsyncPresignedUrlManager.java, services/s3/src/test/java/software/amazon/awssdk/services/s3/internal/presignedurl/DefaultAsyncPresignedUrlManagerTest.java
Implements `DefaultAsyncPresignedUrlManager` to support asynchronous GetObject operations using presigned URLs.
Enables async S3 GetObject operations via presigned URLs, addressing the need for non-blocking presigned URL operations.
Added  async API `AsyncPresignedUrlManager` and its implementation `DefaultAsyncPresignedUrlManager` 
Added comprehensive unit tests covering success responses, error handling, request configuration with range headers, and invalid URL scenarios using MockAsyncHttpClient.
=> Add AsyncPresignedUrlManager for S3 GetObject operations with presigned URLs

.changes/next-release/feature-AWSSDKforJavav2-838b5da.json, codegen/src/main/java/software/amazon/awssdk/codegen/naming/DefaultNamingStrategy.java, codegen/src/main/java/software/amazon/awssdk/codegen/poet/paginators/PaginatorsClassSpec.java, codegen/src/main/java/software/amazon/awssdk/codegen/validation/ValidationErrorId.java, codegen/src/test/java/software/amazon/awssdk/codegen/poet/paginators/PaginatorsClassSpecTest.java
Converts some codegen exceptions to ModelInvalidException.
Related previous change: https://github.com/aws/aws-sdk-java-v2/pull/new/alexwoo/model-validations
There are a number of places we raise NPE or IllegalArgumentException, ect when there are issues with customization config or the model - this PR converts those exceptions to the new ModelInvalidException.
existing test cases
=> Convert some codegen exceptions to ModelInvalidException

release-scripts/src/main/java/software/amazon/awssdk/release/CreateNewServiceModuleMain.java, release-scripts/src/main/java/software/amazon/awssdk/release/NewServiceMain.java
Fix dependency generation for new smithy-rpc-v2-cbor services
Generation of new smithy-rpc-v2-cbor services is failing with:
```
[WARNING] Used undeclared dependencies found:
[WARNING]    software.amazon.awssdk:aws-json-protocol:jar:2.32.4-SNAPSHOT:compile
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:3.1.1:analyze-only (default) on project arcregionswitch: Dependency problems found
```
While the `aws-cbor-protocol` module does define a dependency on aws-json-protocol, the code generation *also* generates code into the service module that has direct dependencies on aws-json-protocol, causing the undeclared dependencies issue above.
* Adds a static map of additional dependencies per protocol that are added to …
=> Fix dependency generation for new smithy-rpc-v2-cbor services

codegen/src/main/java/software/amazon/awssdk/codegen/poet/rules/EndpointResolverInterceptorSpec.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/rules/endpoint-resolve-interceptor-preSra.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/rules/endpoint-resolve-interceptor-with-endpointsbasedauth.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/rules/endpoint-resolve-interceptor-with-multiauthsigv4a.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/rules/endpoint-resolve-interceptor.java, services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/presignedurl/DefaultAsyncPresignedUrlManager.java, services/s3/src/main/java/software/amazon/awssdk/services/s3/presignedurl/AsyncPresignedUrlManager.java, services/s3/src/test/java/software/amazon/awssdk/services/s3/internal/presignedurl/DefaultAsyncPresignedUrlManagerTest.java, services/s3/src/test/java/software/amazon/awssdk/services/s3/presignedurl/AsyncPresignedUrlManagerTest.java
Added distinct operation name for pre-signed URL requests to prevent ClassCastException, 
implemented null check for resolvedEndpoint to avoid NullPointerException, 
and enhanced `AsyncPresignedUrlManager` API with GetObject methods.
When using `AsyncPresignedUrlManager` with presigned URLs, a ClassCastException occurs because the S3 endpoint resolution interceptor attempts to cast PresignedUrlGetObjectRequestWrapper to GetObjectRequest. 
NullPointerExceptions are thrown for presigned url get operations when resolvedEndpoint is null in the endpoint interceptor.
1. Added Distinct Operation Name for Pre-signed URL
• Changed operation name from "GetObject" to "PresignedUrlGetObject" in `DefaultAsyncPresignedUrlManager`
• Prevents invalid casting in the S3 endpoint resolution interceptor
2. …
=>  Modify Operation Name for Presigned URL, add  Null Check for ResolvedEndpoint, enhance AsyncPresignedUrlManager API

docs/design/core/presignedURL-Get/DecisionLog.md, docs/design/core/presignedURL-Get/Design.md
Related to Design Document added as part of PR https://github.com/aws/aws-sdk-java-v2/pull/6203.
Update design document with final API naming decisions from surface area review and scope implementation to async client only
Updated S3 pre-signed URL GET design with final API naming (`AsyncPresignedUrlExtension`, `PresignedUrlDownloadRequest`) and moved sync client implementation to future work
=> Update S3 pre-signed URL GET design with final API naming

http-clients/apache5-client/src/main/java/software/amazon/awssdk/http/apache5/Apache5HttpClient.java, http-clients/apache5-client/src/main/java/software/amazon/awssdk/http/apache5/internal/Apache5HttpRequestConfig.java, http-clients/apache5-client/src/main/java/software/amazon/awssdk/http/apache5/internal/impl/Apache5HttpRequestFactory.java, http-clients/apache5-client/src/main/java/software/amazon/awssdk/http/apache5/internal/utils/Apache5Utils.java, http-clients/apache5-client/src/test/java/software/amazon/awssdk/http/apache5/Apache5HttpClientWireMockTest.java, http-clients/apache5-client/src/test/java/software/amazon/awssdk/http/apache5/MetricReportingTest.java, http-clients/apache5-client/src/test/java/software/amazon/awssdk/http/apache5/internal/impl/ApacheHttpRequestFactoryTest.java
This change addresses the use of deprecated APIs in Apache HttpClient 5. The `setConnectTimeout()` method in `RequestConfig.Builder` is deprecated and should be replaced with proper connection-level timeout configuration via `ConnectionConfig`.
In Apache HttpClient 5, the architecture separates:
- **Connection-level timeouts** (connect timeout, socket timeout, TTL) → configured via `ConnectionConfig`  
- **Request-level timeouts** (connection request timeout, response timeout) → configured via `RequestConfig`
This change aligns our implementation with Apache HttpClient 5's recommended practices and eliminates deprecated API usage warnings.
- **Removed `connectionTimeout` from `Apache5HttpRequestConfig`** - This timeout is now managed at the connection manager level
- **Added …
=> Move connection timeout configuration from RequestConfig to ConnectionConfig in Apache HttpClient 5

services-custom/dynamodb-enhanced/src/it/java/software/amazon/awssdk/enhanced/dynamodb/CrudWithResponseIntegrationTest.java, services/s3/src/it/java/software/amazon/awssdk/services/s3/S3ListObjectsV2IntegrationTest.java
```
Java.lang.NullPointerException
at software.amazon.awssdk.services.s3.S3ListObjectsV2IntegrationTest.assertS3ObjectSummariesAreValid(S3ListObjectsV2IntegrationTest.java:335)
at software.amazon.awssdk.services.s3.S3ListObjectsV2IntegrationTest.testListWithFetchOwner(S3ListObjectsV2IntegrationTest.java:262)
at java.lang.reflect.Method.invoke(Method.java:498)
```
https://docs.aws.amazon.com/AmazonS3/latest/API/API_Owner.html
- based on this
```
Between July 15, 2025 and October 1, 2025, you will begin to see an increasing rate of missing DisplayName in the Owner object.
```
- Remove the usage of `DisplayName` API in iteg test , we already do check on the owner.`id` api
=> Remove usage of `DisplayName` API from S3 integ test as S3 no longer sends it

.changes/next-release/bugfix-AmazonS3-6522f77.json, bom-internal/pom.xml, pom.xml, services/s3/pom.xml, services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/multipart/KnownContentLengthAsyncRequestBodySubscriber.java, services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/multipart/MpuRequestContext.java, services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/multipart/MultipartUploadHelper.java, services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/multipart/UploadWithKnownContentLengthHelper.java, services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/multipart/UploadWithUnknownContentLengthHelper.java, services/s3/src/test/java/software/amazon/awssdk/services/s3/internal/multipart/KnownContentLengthAsyncRequestBodySubscriberTest.java, services/s3/src/test/java/software/amazon/awssdk/services/s3/internal/multipart/MpuRequestContextTest.java, services/s3/src/test/java/software/amazon/awssdk/services/s3/internal/multipart/S3MultipartClientPutObjectWiremockTest.java, services/s3/src/test/java/software/amazon/awssdk/services/s3/internal/multipart/UploadWithUnknownContentLengthHelperTest.java, test/ruleset-testing-core/pom.xml
The S3 multipart upload client lacked proper validation of upload parameters, which could lead to runtime failures or incorrect behavior when publishers provide malformed data. This addresses potential issues where:
• AsyncRequestBody parts lack content length information
• Individual parts exceed the configured part size
• The actual number of parts doesn't match expected calculations
• Publisher implementations continue sending data after completion
• **Content Length Validation**: Ensure all AsyncRequestBody parts have content length present
• **Part Size Validation**: Verify each part (except the last) matches the expected part size exactly
• **Last Part Size Validation**: Validate the final part size matches the calculated remainder or full part size
• **Part Count Validation**: …
=> Add validations for upload in s3 mulitpart client

.changes/next-release/feature-AWSSDKforJavav2-9f69c81.json, core/http-auth-aws/src/main/java/software/amazon/awssdk/http/auth/aws/crt/internal/util/CrtUtils.java, core/http-auth-aws/src/test/java/software/amazon/awssdk/http/auth/aws/crt/internal/signer/DefaultAwsCrtV4aHttpSignerTest.java
This change enables host header override functionality for SigV4a signing, bringing it to parity with SigV4 signing behavior. 
**Background:** In PR #5608, we fixed SigV4 signing to respect pre-existing Host headers rather than always overriding them. This was necessary for use cases like:
- Transparent proxies that rely on the Host header for routing
- Custom routing scenarios where the Host header differs from the endpoint
**Current issue:** The same fix was not applied to the SigV4a signing path, causing host header overrides to be ignored when using SigV4a.
**Impact:**  Enhance SigV4a support such that customers expect host header override to work consistently across both signing algorithms.
- Added host header existence check in `CrtUtils.java` before setting the host header in …
=> SigV4a: Add host header only when not already provided

.changes/next-release/bugfix-AmazonS3-61abc5c.json, core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/async/SplittingTransformer.java, services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/multipart/MultipartDownloaderSubscriber.java, services/s3/src/test/java/software/amazon/awssdk/services/s3/internal/multipart/S3MultipartClientGetObjectWiremockTest.java
This PR fixes a bug in the Java-based multipart S3 client (MultipartS3AsyncClient) that causes duplicate request logging when a retryable error occurs during many concurrent GetObject operations 
Currently, when a retryable error, e.g., 503 Slowdown, is returned by S3, the SDK may do one of two things:
1. Fail the request right away instead of retrying
2. Retry the error, but incorrectly process subsequent responses. A successful 200 response returned by the sever will be ignored. Instead, the SDK will log the initial error, and continue to retry until retry attempts are exhausted. This may happen instead of scenario 1 (failing right away), if many concurrent requests are in progress and a race condition occurs.
This PR fixes 2), a follow up PR will fix 1)
`SplittingTransformer`
- When …
=> Fix bug in MultipartS3AsyncClient GetObject

.changes/next-release/documentation-AWSSDKforJavav2-6b16da2.json, core/aws-core/src/main/java/software/amazon/awssdk/awscore/eventstream/EventStreamResponseHandler.java
Improve `EventStreamResponseHandler.Builder.onError` javadoc to mention that the callback may be called multiple time, similarly to the exceptionOccurred method.
The default implementation of the `exceptionOccurred` simply calls the consumer passed to the `onError(Consumer)` method of the builder. The `exceptionOccurred` already mentions that it can be called multiple time, but the `onError` method of the builder was not.
=> Event stream response handler builder onError documentation improvement

core/sdk-core/src/main/java/software/amazon/awssdk/core/exception/SdkException.java
Javadocs for SdkException state: Base class for all exceptions thrown by the SDK.
However for some errors such as SocketException we throw UncheckedIOException , which leads to issues if customers rely on catching SdkException to retry. We can't make changes due to backwards compatibility, this pr is to make the Java doc more accurate
=> SdkException java doc changed

.changes/next-release/feature-AWSSDKforJavav2-d4e19d2.json, core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/async/ByteArrayAsyncResponseTransformer.java
Currently `ByteArrayAsyncResponseTransformer` invokes `ResponseBytes.fromByteArray()` once all the data is downloaded, which copies the contents of the byte array when creating `ResponseBytes`
replace `ResponseBytes.fromByteArray()` with `ResponseBytes.fromByteArrayUnsafe()`, which creates `ResponseBytes` without copying the contents of the byte array
Performance tests showed increased throughput and decrease in latency
=> Avoid extra byte array copying when downloading to memory with AsyncResponseTransformer

services/s3/src/test/java/software/amazon/awssdk/services/s3/internal/multipart/S3MultipartClientGetObjectRetryBehaviorWiremockTest.java, services/s3/src/test/java/software/amazon/awssdk/services/s3/internal/multipart/S3MultipartClientGetObjectWiremockTest.java
Fix flakey S3 Multipart GET tests
S3MultipartClientGetObjectRetryBehaviorWiremockTest
- Add `Status Code: ` to assertions as UUID may contain the error code
S3MultipartClientGetObjectWiremockTest
- Increase invocation count cap from 1 to 2
=> Fix flakey S3 Multipart tests

.changes/next-release/bugfix-AWSSDKforJavav2-17f90b1.json, utils/src/test/java/software/amazon/awssdk/utils/async/StoringSubscriberTest.java
The stochastic_subscriberSeemsThreadSafe test in StoringSubscriberTest is flaky and gives 
```
[ERROR]   StoringSubscriberTest.stochastic_subscriberSeemsThreadSafe:188 » Execution org.opentest4j.AssertionFailedError: 
expected: 0
but was: 1
```
The reason seems to be that the onSubscribe() likely triggers an initial request(n) call, the Producer immediately starts sending messages (0, 1, 2...). However,  consumer thread starts later and may miss message 0 .
Start consumer first and then call the onSubscribe()
=> Flaky test fix for StoringSubscriberTest

.changes/next-release/bugfix-AmazonDynamoDBEnhancedClient-18f50d7.json, services-custom/dynamodb-enhanced/src/main/java/software/amazon/awssdk/enhanced/dynamodb/internal/document/JsonStringFormatHelper.java
Provide optimizations for `EnhancedDocument.toJson()`
When escaping characters, check that escaping is actually needed before entering switch flow. Else, skip the switch flow and append the char as-is to the `StringBuilder`.
If no characters need escaping, return input String as-is without initializing `StringBuilder`
Current unit tests for escape characters pass
- https://github.com/aws/aws-sdk-java-v2/blob/master/services-custom/dynamodb-enhanced/src/test/java/software/amazon/awssdk/enhanced/dynamodb/document/EnhancedDocumentTest.java
- https://github.com/aws/aws-sdk-java-v2/blob/master/services-custom/dynamodb-enhanced/src/test/java/software/amazon/awssdk/enhanced/dynamodb/document/ParameterizedDocumentTest.java#L48
=> Optimizations for EnhancedDocument.toJson()
