aws/aws-sdk-java-v2

services/s3/src/it/java/software/amazon/awssdk/services/s3/SingleStringResponseOperationsIntegrationTest.java, services/s3/src/main/java/software/amazon/awssdk/services/s3/handlers/SingleStringResponseHandler.java, services/s3/src/main/resources/software/amazon/awssdk/services/s3/request.handler2s
Most S3 operations return a structure wrapped in an outer XML element with two exceptions
- GetBucketLocation which returns `<LocationConstraint>region</LocationConstraint>`
- GetBucketPolicy which returns a raw JSON document representing the policy
The Sax unmarshaller used for S3 is expecting this outer wrapper. This response handler modifies the responses of these operations to include the required XML wrappers.
=> Correcting S3 unmarshalling for a couple of operations

http-clients/netty-nio-client/src/it/java/software/amazon/awssdk/http/nio/netty/NettyNioAsyncHttpClientIntegrationTest.java, http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/NettyNioAsyncHttpClient.java
If the configured EventLoopGroup is not an instance of
DelegatingEventLoopGroup, then resolveSocketChannelClass always returns
NioSocketChannel which is incorrect.
=> Move check for epoll group outside of loop

core/src/main/java/software/amazon/awssdk/AwsSystemSetting.java, core/src/main/java/software/amazon/awssdk/auth/ElasticContainerCredentialsProvider.java, core/src/test/java/software/amazon/awssdk/auth/ElasticContainerCredentialsProviderTest.java
=> Fix issue #135

core/src/main/java/software/amazon/awssdk/protocol/json/JsonContent.java, pom.xml
Prior to 2.9.1 `jackson-jr-objects` has backticks in the
jar manifest which hits a bug in jdk9. For more details
see FasterXML/jackson-jr#55.
This change also ensure that the jackson versions are
the all the same:
**Before**
```
$ mvn --projects core dependency:tree -Dincludes=*:jackson-*::*
...
[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ core ---
[INFO] software.amazon.awssdk:core:jar:2.0.0-preview-3-SNAPSHOT
[INFO] +- com.fasterxml.jackson.core:jackson-databind:jar:2.8.8:compile
[INFO] |  +- com.fasterxml.jackson.core:jackson-annotations:jar:2.8.8:compile
[INFO] |  \- com.fasterxml.jackson.core:jackson-core:jar:2.8.8:compile
[INFO] +- com.fasterxml.jackson.jr:jackson-jr-objects:jar:2.9.0.pr4:compile
[INFO] +- com.fasterxml.jackson.dataformat:jackson-dataformat-cbor:jar:2. …
```
=> update to jackson 2.9.1

core/src/main/java/software/amazon/awssdk/async/AsyncRequestProvider.java, core/src/main/java/software/amazon/awssdk/async/SingleByteArrayAsyncRequestProvider.java, core/src/test/java/software/amazon/awssdk/async/AsyncRequestProviderTest.java
Can be used (for example) for uploading to s3:
```java
S3AsyncClient s3 = ...;
s3.putObject(PutObjectRequest.builder().bucket("bucket-name").key("some-key.txt").build(),
AsyncRequestProvider.fromString("hello world!!!"));
```
=> Adding a helper that exposes an async string request provider

core/src/main/java/software/amazon/awssdk/runtime/transform/SimpleTypeCborUnmarshallers.java, services/kinesis/src/it/java/software/amazon/awssdk/services/kinesis/KinesisIntegrationTests.java
=> Treat CBOR instants as milliseconds since the linux epoch, not seconds.

core/src/main/java/software/amazon/awssdk/core/auth/Aws4Signer.java, core/src/main/java/software/amazon/awssdk/core/http/DefaultErrorResponseHandler.java, core/src/main/java/software/amazon/awssdk/core/http/pipeline/stages/MakeAsyncHttpRequestStage.java, core/src/main/java/software/amazon/awssdk/core/http/pipeline/stages/ReportRequestContentLengthStage.java, core/src/test/java/software/amazon/awssdk/core/auth/Aws4SignerTest.java, core/src/test/java/software/amazon/awssdk/core/http/AmazonHttpClientTest.java, http-client-spi/src/main/java/software/amazon/awssdk/http/SdkHttpFullRequest.java, http-client-spi/src/main/java/software/amazon/awssdk/http/SdkHttpFullResponse.java, http-client-spi/src/main/java/software/amazon/awssdk/http/SdkHttpHeaders.java, http-clients/apache-client/src/main/java/software/amazon/awssdk/http/apache/internal/RepeatableInputStreamRequestEntity.java, http-clients/url-connection-client/src/it/java/software/amazon/awssdk/http/urlconnection/UrlConnectionHttpClientIntegrationTest.java, services/glacier/src/it/java/software/amazon/awssdk/services/glacier/ServiceIntegrationTest.java, services/glacier/src/main/java/software/amazon/awssdk/services/glacier/internal/GlacierExecutionInterceptor.java, services/s3/src/main/java/software/amazon/awssdk/services/s3/AwsS3V4Signer.java, services/s3/src/test/java/software/amazon/awssdk/services/s3/handlers/PutObjectInterceptorTest.java, test/protocol-tests/src/test/java/software/amazon/awssdk/protocol/tests/ExecutionInterceptorTest.java
This was requested in https://github.com/aws/aws-sdk-java-v2/pull/178
=> Added alias for SdkHttpUtils.firstMatchingHeader utility method to the HTTP request/response objects and builders.

http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/DefaultEventLoopGroupFactory.java
Realised that getenv could throw a security exception and I don't really want to blow-up because we couldn't determine we're on lambda. Adding a try-catch so that we assume we're not on Lambda if we get an exception.
Follow-up to https://github.com/aws/aws-sdk-java-v2/pull/208
=> Adding a try-catch around the getenv call for safety.

services/kms/pom.xml
Make test-utils a test scoped dependency in KMS
Do not want to pull in test dependencies
In SDK project:
$ mvn install
In my project:
$ mvn dependency:tree
no longer shows test-util (and other transitive dependencies like junit) in the tree
Strictly, this could be a breaking change for users that inappropriately relied on dependencies of test-util e.g. Guice
=> Make test-utils a test scoped dependency in KMS

core/src/main/java/software/amazon/awssdk/core/http/pipeline/stages/AsyncRetryableStage.java, core/src/main/java/software/amazon/awssdk/core/http/pipeline/stages/RetryableStage.java, core/src/main/java/software/amazon/awssdk/core/retry/RetryHandler.java, core/src/main/java/software/amazon/awssdk/core/util/ClockSkewUtil.java, core/src/test/java/software/amazon/awssdk/core/http/RetryCountInUserAgentTest.java
All tests (unit and integration) pass and provide good coverage over this logic.
=> Refactoring retry logic out to separate class

codegen/src/main/java/software/amazon/awssdk/codegen/poet/common/EnumClass.java, codegen/src/main/resources/templates/common/enum-class.ftl, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/common/test-enum-class.java
A common way to get all enum values and do something with them is Enum.values() - but there are probably cases where customers only really care about the 'known' enum values (ie: not the `UNKNOWN_TO_SDK_VERSION` one).
Add a new static method to each enum called `knownTypes()` returns all enum values except the `UNKNOWN_TO_SDK_VERSION` value.
See above
Updated poet unit tests
=> Adding knownValues static to enum generation

codegen/src/main/java/software/amazon/awssdk/codegen/internal/ClassLoaderHelper.java, core/src/main/java/software/amazon/awssdk/core/interceptor/ClasspathInterceptorChainFactory.java, core/src/main/java/software/amazon/awssdk/core/util/ClassLoaderHelper.java
Running via AWS Lambda on Async causes the following stack trace during construction of FirehoseAsyncClient
```
java.lang.NullPointerException: Failed to load the classloader for the current thread.
at software.amazon.awssdk.utils.Validate.notNull(Validate.java:118)
at software.amazon.awssdk.handlers.ClasspathInterceptorChainFactory.classLoader(ClasspathInterceptorChainFactory.java:129)
at software.amazon.awssdk.handlers.ClasspathInterceptorChainFactory.createExecutionInterceptorsFromClasspath(ClasspathInterceptorChainFactory.java:62)
at software.amazon.awssdk.handlers.ClasspathInterceptorChainFactory.getInterceptors(ClasspathInterceptorChainFactory.java:50)
at software.amazon.awssdk.config.defaults.ServiceBuilderConfigurationDefaults.lambda$applyOverrideDefaults$1(ServiceBuilderConfigurat …
```
=> Attempting to fix class-loader exception raised on gitter.

.travis.yml
Adds Travis config to only build `master` branch.
Adds Travis config to only build `master` branch.
Team members push feature branches to the repo that are getting auto built blocking builds of `master`.
N/A.
=> Build only master branch

services/pom.xml, services/sqs/src/main/java/software/amazon/awssdk/services/sqs/buffered/SendQueueBuffer.java
The SQS clock skew test is consistently failing in Jenkins CI. Adding wire-logging to assist debugging. (Also fixes NPE bug in the SQS buffered client.
mvn clean verify -Pintegration-tests -pl :sqs
=> Adding logging for SQS tests

http-clients/pom.xml, pom.xml, services/pom.xml, test/dynamodbdocument-v1/pom.xml, test/dynamodbmapper-v1/pom.xml, test/protocol-tests-core/pom.xml, test/protocol-tests/pom.xml, test/service-test-utils/pom.xml, test/test-utils/pom.xml
A "root.offset" system property had to be added to force all tests to
write to the same jacoco output file. There's no easy way in maven to
get the root module directory.
=> Add cross-module test coverage to sonar.

http-clients/apache-client/pom.xml, http-clients/apache-client/src/main/java/software/amazon/awssdk/http/apache/internal/conn/SdkTlsSocketFactory.java, http-clients/apache-client/src/test/java/software/amazon/awssdk/http/apache/ApacheHttpClientWireMockTest.java, http-clients/url-connection-client/pom.xml, http-clients/url-connection-client/src/test/java/software/amazon/awssdk/http/urlconnection/UrlConnectionHttpClientWireMockTest.java, pom.xml, test/http-client-tests/pom.xml, test/http-client-tests/src/main/java/software/amazon/awssdk/http/SdkHttpClientTestSuite.java
This package includes a suite of tests to validate the functionality of all HTTP client implementations.
Initially this has only been populated with the tests that were already in the URL connection implementation plus one additional test to validate that untrusted certificate issuers fail the request.
In the future, we could add:
1. Tests for HTTPS endpoints (requires implementations to support disabling SSL validation)
2. Tests for async clients
3. Integration tests that call badssl.com for validating a multitude of invalid server certificates
4. More comprehensive testing scenarios (the ones currently in place are very limited "happy case" tests)
=> Created http-client-tests package.

codegen/src/main/resources/jp-to-ast.py
Remove `jp-to-ast.py`
File is not needed.
`mvn install`
Cleanup
=> Delete old jmespath AST script

bundle/pom.xml
Adding missing dependencies to bundle pom.
Make the bundle usable.
Used the bundle in an application
- [x ] Bug fix (non-breaking change which fixes an issue)
- [ x] I have read the **CONTRIBUTING** document
- [ x] Local run of `mvn install` succeeds
- [ x] My code follows the code style of this project
- [x ] I have read the **README** document
- [x ] All new and existing tests passed
- [x ] I confirm that this pull request can be released under the Apache 2 license
=> Fixing bundle exports

services/dynamodb/src/main/java/software/amazon/awssdk/services/dynamodb/model/Item.java, services/dynamodb/src/test/java/software/amazon/awssdk/services/dynamodb/model/ItemTest.java
Creating `AttributeValues` is very verbose for such a simple data-type, these helpers allow creating item maps and attribute values from simple method calls.
Added new unit tests
=> Adding some helpers for being able to create DyanmoDB AttributeValues.

codegen/src/main/java/software/amazon/awssdk/codegen/model/intermediate/MemberModel.java, codegen/src/main/java/software/amazon/awssdk/codegen/poet/model/AbstractMemberSetters.java, codegen/src/main/java/software/amazon/awssdk/codegen/poet/model/ListSetters.java, codegen/src/main/java/software/amazon/awssdk/codegen/poet/model/MapSetters.java, codegen/src/main/java/software/amazon/awssdk/codegen/poet/model/NonCollectionSetters.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/alltypesrequest.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/alltypesresponse.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/recursivestructtype.java
Allows providing a `Consumer<Builder>` to complex fluent models setters to avoid having to create the appropriate builder yourself. As an example SES send message goes from:
```java
client.sendEmail(SendEmailRequest.builder()
.destination(Destination.builder()
.toAddresses("kiiadi@gmail.com")
.build())
.message(Message.builder().body(Body.builder()
.text(Content.builder().data("Crud").charset("UTF-8").build())
.build())
.subject(Content.builder().data("Hello").build())
.build())
.build());
```
to a:
```java
client.sendEmail(SendEmailRequest.builder()
.destination(d -> d.toAddresses("kiiadi@gmail.com"))
.message(m -> m.body(b -> b.text(t -> t.data("Crud").charset("UTF-8")))
.subject(s -> s.data("Hello")))
.build());
```
Allows customers who dislike the verbose …
=> Implementing Consumer<Builder> fluent setters on model builders.

codegen/src/main/java/software/amazon/awssdk/codegen/docs/AsyncOperationDocProvider.java, codegen/src/main/java/software/amazon/awssdk/codegen/docs/OperationDocProvider.java, codegen/src/main/java/software/amazon/awssdk/codegen/docs/SimpleMethodOverload.java, codegen/src/main/java/software/amazon/awssdk/codegen/model/intermediate/OperationModel.java, codegen/src/main/java/software/amazon/awssdk/codegen/poet/client/AsyncClientInterface.java, codegen/src/main/java/software/amazon/awssdk/codegen/poet/client/SyncClientInterface.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/test-json-async-client-interface.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/test-json-client-interface.java, test/dynamodbmapper-v1/src/it/java/software/amazon/awssdk/services/dynamodb/datamodeling/BatchLoadIntegrationTest.java, test/dynamodbmapper-v1/src/test/java/software/amazon/awssdk/services/dynamodb/mapper/MapperQueryExpressionTest.java
see https://github.com/aws/aws-sdk-java-v2/pull/278
=> Implementing Consumer<Builder> client operations

core/src/main/java/software/amazon/awssdk/core/client/builder/AsyncClientBuilder.java, core/src/main/java/software/amazon/awssdk/core/client/builder/ClientAsyncHttpConfiguration.java, http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/NettySdkHttpClientFactory.java
Instead of having to do this:
```java
DynamoDBAsyncClient.builder().asyncHttpConfiguration(
ClientAsyncHttpConfiguration.builder()
.httpClientFactory(NettySdkHttpClientFactory.builder()
.maxConnectionsPerEndpoint(MAX_CONNECTIONS)
.build())
.build())
.build();
```
we can do :
```java
DynamoDBAsyncClient.builder().asyncHttpConfiguration(
b -> b.httpClientFactory(NettySdkHttpClientFactory.builder()
.maxConnectionsPerEndpoint(MAX_CONNECTIONS)))
.build();
```
=> Making it easier to supply async http configuration.

core/src/main/java/software/amazon/awssdk/core/client/builder/ClientBuilder.java, core/src/test/java/software/amazon/awssdk/core/client/builder/DefaultClientBuilderTest.java
Additional helper builder that can be used to configure overrideConfiguration.
=> Adding Consumer<Builder> to overrideConfiguration on ClientBuilder

codegen/src/main/java/software/amazon/awssdk/codegen/poet/model/ModelMethodOverrides.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/alltypesrequest.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/alltypesresponse.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/basetype.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/nestedcontainersrequest.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/nestedcontainersresponse.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/recursivestructtype.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/simplestruct.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/structwithnestedblobtype.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/structwithtimestamp.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/subtypeone.java
Use `java.util.Objects` to implements `equals()` and `hashCode()`.
Should cut down on generated file size.
Updated reference tests.
=> Use java.util.Objects to implement equals, hashCode

services/iam/src/it/java/software/amazon/awssdk/services/iam/UserIntegrationTest.java, services/lambda/src/it/java/software/amazon/awssdk/services/lambda/IntegrationTestBase.java, services/lambda/src/it/java/software/amazon/awssdk/services/lambda/ServiceIntegrationTest.java, services/waf/src/it/java/software/amazon/awssdk/services/waf/WafIntegrationTest.java, test/test-utils/src/main/java/software/amazon/awssdk/testutils/Waiter.java
The waiter can execute a function multiple times until the function's response meets a desired state. This is useful for dealing with eventually consistent APIs without having to use arbitrary sleep durations.
Also:
1. Fixed error in lambda test where function was not being uploaded, but test expected it.
2. Retry WAF delete-ip-set multiple times in case the IPs had not yet been deleted on the service side.
=> Added a primitive "waiter" class for simplifying poll-until-condition-is-met behavior.

pom.xml, services/ses/pom.xml
`mvn clean install -pl :ses -am`
Ran SES integration tests locally
=> Removing unnecessary javax.mail dependency

http-client-spi/src/main/java/software/amazon/awssdk/http/ConfigurationProvider.java
It's not clear that we actually need this, and it bloats our Http SPI
=> Marking ConfigurationProvider as @ReviewBeforeRelease

core/src/main/java/software/amazon/awssdk/core/config/ClientOverrideConfiguration.java, services/waf/src/it/java/software/amazon/awssdk/services/waf/WafIntegrationTest.java
Our integration tests keep getting rate exceeded exceptions.
=> Changing retry-policy for WAF so that we back-off more aggressively

pom.xml
- Removing unused dependency that was causing exceptions during javadoc generation
- Don't include dependent sources in our javadoc list (eg: slf4j)
=> Fixes for javadoc generation.

.changes/next-release/bugfix-AmazonS3-4392508.json, codegen/src/main/resources/templates/rest-xml/s3/ExceptionUnmarshaller.ftl, core/src/main/java/software/amazon/awssdk/core/runtime/transform/StandardErrorUnmarshaller.java, services/s3/src/it/java/software/amazon/awssdk/services/s3/ExceptionUnmarshallingIntegrationTest.java, services/s3/src/main/java/software/amazon/awssdk/services/s3/transform/S3ExceptionUnmarshaller.java, services/s3/src/main/resources/codegen-resources/customization.config
S3 exception unmarshalling. 
Fixes #297 #123 #147
**Note**: 
this will only fix exception unmarshalling for s3 error responses that are actually containing the error details such as `getObject`, `getObjectAcl`,
for operations such as `headObject`, `headBucket`, since s3 is not returning us any error details, we can't marshal it to the correct exceptions. we need to find a way to remove the exception from the javadoc.
Added integration tests
=> Fix S3 exception unmarshalling #297

pom.xml
Keeps all Jackson dependencies running on the same version.
Fixes #387 
mvn clean install
=> Keeping jackson and jackson-jr in sync

core/src/it/java/software/amazon/awssdk/core/util/EC2MetadataUtilsIntegrationTest.java, core/src/test/java/software/amazon/awssdk/core/regions/providers/InstanceProfileRegionProviderTest.java, core/src/test/java/software/amazon/awssdk/core/util/EC2MetadataUtilsServer.java
Update EC2MetadataUtilServer to only accept localhost address
=> Update EC2MetadataUtilServer to only accept localhost address

core/src/test/java/software/amazon/awssdk/core/http/DefaultErrorResponseHandlerTest.java, core/src/test/resources/jetty-logging.properties, services/glacier/src/test/resources/log4j.properties
DefaultErrorResponseHandlerTest uses LogCaptor and sets the level of the
root logger to DEBUG but never resets it; this has the effect of making
all subsequent tests be at DEBUG as well. When combined with tests that
also happens to use WireMock, which spits out a ton of debug messages,
this results in lots of unnecessary debug log statements.
This also adds a jetty-logging.properties test resource to core so that
even when we need to temporarily set the root logger to DEBUG, we don't
log anything from Jetty/WireMock.
Finally, fix some test logging configs that were too verbose.
Fixes #396 
Fix #396 
`mvn clean install > build.out 2>&1` and check the file size.
=> Reduce DEBUG logging when running tests

.changes/next-release/bugfix-NettyNIOAsyncHTTPClient-e5d4229.json, http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/internal/ResponseHandler.java
HttpStreamsClientHandler ignores the LastHttpContent decoded by the HTTP
codec when we get an empty response from the service, but if the channel
gets released (which causes the streams handler to get removed) before
the last content message comes through and is ignored by the handler,
the new HttpStreamsHandler (added by RunnableRquest) will not be in a
state to anticipate and ignore the LastHttpContent and will instead do
the wrong thing and attempt to remove a non-existent handler.
This commit fixes that race condition by explicitly replacing the
HttpStreamsClientHandler in the pipeline with a new handler that ignores
the next message read in the pipeline if it's a LastHttpContent.
Fixes #202
Fix #202
=> Fix race codition between read and finalizeRequest

.changes/next-release/bugfix-AWSSDKforJavav2-635a047.json, core/src/main/java/software/amazon/awssdk/core/util/UserAgentUtils.java, core/src/test/java/software/amazon/awssdk/core/util/UserAgentUtilsTest.java
Update default user agent to comply with [RFC 7231](https://tools.ietf.org/html/rfc7231#section-5.5.3)
after the change, user-agent would be something like this
`aws-sdk-java/2.0.0-preview-9-SNAPSHOT Mac_OS_X/10.11.6 Java_HotSpot_TM__64-Bit_Server_VM/25.151-b12 Java/1.8.0_151`
fix #80 
=> Fix default user agent to comply with RFC 7231

bom/pom.xml
Partial revert of the #404 
Without the parent element, pom.xml of bom module doesn't satisfy the requirements for publishing to maven. To unblock the releases, adding back the parent element. This reintroduces the issue #295 
To fix #295, we have couple of options:
1) Remove parent element from BOM's pom file and add all the required elements to satisfy maven publish rules
2) Remove dependency management from parent pom and add it to a different module which can be added as a dependency to all other modules. For example, move the dependencies in parent pom to core pom file. Then add core as dependency to other modules which need those dependencies.
I would prefer to go with Option 2. This is a bit similar to v1. This options needs a bit refactoring to entire project. I will reopen the …
=> Adding back parent element in bom pom.xml

.changes/next-release/feature-AWSSDKforJavav2-6ec70c4.json, core/src/main/java/software/amazon/awssdk/core/auth/AwsCredentialsProviderChain.java, core/src/test/java/software/amazon/awssdk/core/auth/AwsCredentialsProviderChainTest.java
This PR modifies the exception path of `AWSCredentialsProviderChain.getCredentials` to include all root causes in the exception message.
Before this PR, when all providers in an `AWSCredentialsProviderChain` fail to provide credentials, the exception gives no hint of the underlying exceptions. That makes troubleshooting difficult unless your log level is already set to DEBUG, which is rarely the case in production.
A new unit test case is included.
=> Make AWSCredentialsProviderChain exceptions easier to troubleshoot

http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/NettyNioAsyncHttpClient.java, http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/NettySdkHttpClientFactory.java, http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/internal/NettyConfiguration.java, http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/internal/RunnableRequest.java, http-clients/netty-nio-client/src/test/java/software/amazon/awssdk/http/nio/netty/NettyNioAsyncHttpClientWireMockTest.java
Change exception message when high amount of requests made using async clients.
Netty returns the following exceptions in these cases:
**TimeoutException: Acquire operation took longer then configured maximum time**
Scenarios: 
When connection acquire timeout is too low to acquire a connection. 
Or there are too many requests waiting for a connection while the max number of connections in the pool is less
**IllegalStateException: Too many outstanding acquire operations**
NettyNioAsyncHttpClient class has the maxPendingAcquires value set to 10_000. So the max amount of requests waiting for a connection can be 10_000. If the request rate is too high and number of requests in greater than 10_000, the queue gets filled up quickly and Netty throws this exception.
=> Improve exception message for high burst traffic using netty client

.changes/next-release/feature-AWSSDKforJavav2-0a2ffb3.json, core/src/main/java/software/amazon/awssdk/core/internal/CredentialsEndpointProvider.java, core/src/test/java/software/amazon/awssdk/core/internal/HttpCredentialsUtilsTest.java
Adds the sending of a User-Agent other than default User-Agent in Java when making requests to metadata service
Similar to AWS Golang SDK and Ruby SDK, send a User-Agent other than the default User-Agent when making requests to the EC2 metadata for credentials.
https://github.com/aws/aws-sdk-java/pull/1562 for aws-sdk-java addresses this also.  PR #1445 for botocore implements this too.
This will enable protection of AWS credentials from Server Side Request Forgery (SSRF) vectors by being able to use a metadata proxy to block requests that do not have the right User-Agent set.  User-Agent is not controllable by an attacker via SSRF.
Set default headers in the `CredentialsEndpointProvider` interface
This will enable protection of AWS credentials from Server Side Request Forgery (SSRF) …
=> CredentialsEndpointProvider.java: Adds the sending of a User-Agent other than default User-Agent to the metadata service

core/src/main/java/software/amazon/awssdk/core/client/BaseClientHandler.java, core/src/main/java/software/amazon/awssdk/core/config/ClientOverrideConfiguration.java, core/src/main/java/software/amazon/awssdk/core/config/defaults/GlobalClientConfigurationDefaults.java, core/src/main/java/software/amazon/awssdk/core/config/defaults/ServiceBuilderConfigurationDefaults.java, core/src/main/java/software/amazon/awssdk/core/interceptor/ExecutionInterceptor.java, core/src/test/java/software/amazon/awssdk/core/config/ImmutableClientConfigurationTest.java, services/glacier/src/it/java/software/amazon/awssdk/services/glacier/ServiceIntegrationTest.java, services/s3/src/it/java/software/amazon/awssdk/services/s3/GetObjectAsyncIntegrationTest.java, services/s3/src/it/java/software/amazon/awssdk/services/s3/GetObjectIntegrationTest.java, services/sqs/src/it/java/software/amazon/awssdk/services/sqs/MessageAttributesIntegrationTest.java, test/protocol-tests/src/test/java/software/amazon/awssdk/protocol/tests/ExecutionInterceptorTest.java
Renamed `ClientConfiguration#lastExecutionInterceptors` to `executionInterceptor`. Order shouldn't matter and the last name was awkward. Marked ExecutionInterceptor as internal for now. We have some changes we want to make, so we'd like to discourage people from implementing it.
=> Renamed ClientConfiguration#lastExecutionInterceptors to executionInterceptors. Marked ExecutionInterceptor as internal.

.changes/next-release/removal-AWSSDKforJavav2-1b4f69d.json, aws-core/src/test/java/software/amazon/awssdk/awscore/client/config/AwsImmutableClientConfigurationTest.java, aws-core/src/test/java/software/amazon/awssdk/awscore/client/utils/HttpTestUtils.java, core/src/it/java/software/amazon/awssdk/core/http/timers/client/AbortedExceptionClientExecutionTimerIntegrationTest.java, core/src/it/java/software/amazon/awssdk/core/http/timers/client/DummyErrorResponseServerIntegrationTests.java, core/src/it/java/software/amazon/awssdk/core/http/timers/client/DummySuccessfulResponseServerIntegrationTests.java, core/src/it/java/software/amazon/awssdk/core/http/timers/client/UnresponsiveServerIntegrationTests.java, core/src/main/java/software/amazon/awssdk/core/RequestOverrideConfig.java, core/src/main/java/software/amazon/awssdk/core/config/ClientOverrideConfiguration.java, core/src/main/java/software/amazon/awssdk/core/http/AmazonSyncHttpClient.java, core/src/main/java/software/amazon/awssdk/core/http/pipeline/stages/ClientExecutionTimedStage.java, core/src/main/java/software/amazon/awssdk/core/http/pipeline/stages/MakeHttpRequestStage.java, core/src/test/java/software/amazon/awssdk/core/config/ImmutableClientConfigurationTest.java, core/src/test/java/software/amazon/awssdk/core/http/pipeline/stages/ClientExecutionTimedStageTest.java, core/src/test/java/software/amazon/awssdk/core/internal/http/timers/client/MockedClientTests.java, core/src/test/java/utils/HttpTestUtils.java, services/s3/src/it/java/software/amazon/awssdk/services/s3/GetObjectFaultIntegrationTest.java
Remove httpRequestTimeout and executionTimeout
=> Remove httpRequestTimeout and executionTimeout features

regions/src/main/resources/software/amazon/awssdk/regions/internal/region/endpoints.json, services/s3/src/main/java/software/amazon/awssdk/services/s3/handlers/CreateBucketInterceptor.java, services/s3/src/main/java/software/amazon/awssdk/services/s3/handlers/EndpointAddressInterceptor.java, services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/BucketUtils.java, services/s3/src/main/resources/software/amazon/awssdk/services/s3/bucketaddressingsep/VirtualAddressingSepTestCases.json, services/s3/src/test/java/software/amazon/awssdk/services/s3/bucketaddressingsep/VirtualHostAddressingSepTest.java
* SDKs should use path style addressing for bucket names containing periods and using Https, but we currently use virtual style. This PR fixes the behavior by using path style.
I am using path style for both Https and Http endpoints to make the behavior less confusing. If we have a strong reason to use virtual style when using Http, I can change that.
* The new test covers all cases in SEP except for cases where bucket acceleration and path style are both enabled.
Unit tests
=> Use path style addressing for bucket names containing period

services/dynamodb/src/it/java/software/amazon/awssdk/services/dynamodb/SignersIntegrationTest.java, services/dynamodb/src/test/java/utils/test/util/DynamoDBTestBase.java, services/s3/src/it/java/software/amazon/awssdk/services/s3/signer/AwsS3V4SignerIntegrationTest.java
=> Use TestBase resources for signer integ tests

.changes/next-release/feature-AWSSDKforJavav2-4db5696.json, auth/src/main/java/software/amazon/awssdk/auth/signer/AbstractAws4Signer.java, auth/src/main/java/software/amazon/awssdk/auth/signer/QueryStringSigner.java, auth/src/main/java/software/amazon/awssdk/auth/signer/internal/AbstractAwsSigner.java, auth/src/test/java/software/amazon/awssdk/auth/signer/AbstractAws4SignerTest.java, auth/src/test/java/software/amazon/awssdk/auth/signer/Aws4SignerTest.java, auth/src/test/java/software/amazon/awssdk/auth/signer/QueryStringSignerTest.java, codegen/src/main/java/software/amazon/awssdk/codegen/poet/builder/BaseClientBuilderClass.java, services/dynamodb/src/it/java/software/amazon/awssdk/services/dynamodb/SignersIntegrationTest.java, services/s3/src/it/java/software/amazon/awssdk/services/s3/S3IntegrationTestBase.java, services/s3/src/it/java/software/amazon/awssdk/services/s3/signer/AwsS3V4SignerIntegrationTest.java, services/s3/src/main/java/software/amazon/awssdk/services/s3/auth/AwsChunkedEncodingInputStream.java
Changes:
* Moved abstract classes to internal package
* Added builder for QueryStringSigner
* Fix integ tests that was using default credential provider chain
* Added changelog for signer refactor
=> Minor fixes as follow to signer refactor PR

codegen/src/main/java/software/amazon/awssdk/codegen/poet/model/AwsServiceModel.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/alltypesrequest.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/alltypesresponse.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/basetype.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/emptymodeledexception.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/enumtype.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/nestedcontainersrequest.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/nestedcontainersresponse.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/operationwithnoinputoroutputrequest.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/operationwithnoinputoroutputresponse.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/recursivestructtype.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/simplestruct.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/streaminginputoperationrequest.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/streaminginputoperationresponse.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/streamingoutputoperationrequest.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/streamingoutputoperationresponse.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/structwithnestedblobtype.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/structwithtimestamp.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/subtypeone.java, test/dynamodbmapper-v1/src/test/java/software/amazon/awssdk/services/dynamodb/datamodeling/BatchLoadRetryStrategyTest.java
Making all model classes (including request/response shapes) final
One use case that might be broken is testing that mocked the request/response classes. Mockito doesn't support mocking final classes. One of our mapper tests is broken and I comment it out as we don't support mapper yet. If we get requests from customers to relax the restriction on request/response shapes, we can consider removing final modifier for these shapes.
=> Make all generated model classes final

regions/src/main/java/software/amazon/awssdk/regions/providers/AwsProfileRegionProvider.java, regions/src/main/java/software/amazon/awssdk/regions/providers/AwsRegionProvider.java, regions/src/main/java/software/amazon/awssdk/regions/providers/AwsRegionProviderChain.java, regions/src/main/java/software/amazon/awssdk/regions/providers/InstanceProfileRegionProvider.java, regions/src/main/java/software/amazon/awssdk/regions/providers/SystemSettingsRegionProvider.java, regions/src/test/java/software/amazon/awssdk/regions/providers/AwsProfileRegionProviderTest.java, regions/src/test/java/software/amazon/awssdk/regions/providers/AwsRegionProviderChainTest.java, regions/src/test/java/software/amazon/awssdk/regions/providers/InstanceProfileRegionProviderTest.java
=> Make AwsRegionProviders throw exceptions like AwsCredentialsProviders

.changes/next-release/feature-AWSSDKforJavav2-1cb94c1.json, auth/src/it/java/software/amazon/awssdk/auth/credentials/InstanceProfileCredentialsProviderIntegrationTest.java, auth/src/main/java/software/amazon/awssdk/auth/credentials/HttpCredentialsProvider.java, auth/src/main/java/software/amazon/awssdk/auth/credentials/InstanceProfileCredentialsProvider.java, core/src/main/java/software/amazon/awssdk/core/SdkSystemSetting.java, regions/src/it/java/software/amazon/awssdk/regions/util/EC2MetadataUtilsIntegrationTest.java, regions/src/main/java/software/amazon/awssdk/regions/providers/InstanceProfileRegionProvider.java, regions/src/main/java/software/amazon/awssdk/regions/util/EC2MetadataUtils.java, regions/src/test/java/software/amazon/awssdk/regions/providers/InstanceProfileRegionProviderTest.java
Add support to disable EC2 instance metadata service usage (v1 parity)
fix #430
=> Add support to disable EC2 instance metadata service usage

scripts/changelog/model.py, scripts/changelog/util.py
Issue was comparing preview version strings 
In old code,
preview-2 > preview-10 as cmp() functions checks one character at a time. So checks 2 > 1 and decides preview-2 is greater. This PR fixes it by parsing the "preview-" string and comparing the integer values
=> Fix changelog sorting issue with preview versions

.changes/next-release/feature-AWSSDKforJavav2-61af032.json, CONTRIBUTING.md, core/pom.xml, core/src/main/java/software/amazon/awssdk/core/async/AsyncResponseTransformer.java, core/src/main/java/software/amazon/awssdk/core/async/ByteArrayAsyncRequestBody.java, core/src/main/java/software/amazon/awssdk/core/async/ByteArrayAsyncResponseTransformer.java, core/src/main/java/software/amazon/awssdk/core/async/FileAsyncRequestBody.java, core/src/main/java/software/amazon/awssdk/core/async/FileAsyncResponseTransformer.java, core/src/main/java/software/amazon/awssdk/core/internal/async/ByteArrayAsyncResponseTransformer.java, core/src/main/java/software/amazon/awssdk/core/internal/async/FileAsyncResponseTransformer.java, core/src/main/java/software/amazon/awssdk/core/internal/http/async/SimpleRequestProvider.java, core/src/main/java/software/amazon/awssdk/core/pagination/async/PaginatedItemsPublisher.java, core/src/main/java/software/amazon/awssdk/core/pagination/async/PaginationSubscription.java, core/src/main/java/software/amazon/awssdk/core/util/async/NoopSubscription.java, core/src/test/java/software/amazon/awssdk/core/async/FileAsyncRequestPublisherTckTest.java, core/src/test/java/software/amazon/awssdk/core/async/SimpleSubscriberTckTest.java, core/src/test/java/software/amazon/awssdk/core/async/SingleByteArrayAsyncRequestProviderTckTest.java, core/src/test/java/software/amazon/awssdk/core/internal/async/BaosSubscriberTckTest.java, core/src/test/java/software/amazon/awssdk/core/internal/async/FileSubscriberTckTest.java, core/src/test/java/software/amazon/awssdk/core/internal/http/async/SimpleRequestProviderTckTest.java, core/src/test/java/software/amazon/awssdk/core/pagination/async/PaginatedItemsPublisherTckTest.java, http-client-spi/pom.xml, http-client-spi/src/main/java/software/amazon/awssdk/http/async/SimpleSubscriber.java, http-clients/netty-nio-client/pom.xml, http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/internal/ResponseHandler.java, http-clients/netty-nio-client/src/test/java/software/amazon/awssdk/http/nio/netty/internal/FullResponseContentPublisherTckTest.java, pom.xml
Add TCK tests for reactive streams implementations.
Builds off #407 from @ktoso.
Add TCK tests for reactive streams implementations. This PR also adds a snippet in `CONTRIBUTING.md` to make it a requirement for all future PR's to include necessary TCK tests if it includes reactive streams implementations.
In order to ensure proper interoperability with other reactive streams libraries, we should ensure that our implementations of the interfaces follow the spec.
Add TCK tests for all current implementations.
=> Add TCK tests for reactive streams implementations

aws-core/src/main/java/software/amazon/awssdk/awscore/config/options/AwsAdvancedClientOption.java, core/src/main/java/software/amazon/awssdk/core/SdkSystemSetting.java, core/src/main/java/software/amazon/awssdk/core/config/options/SdkAdvancedClientOption.java, http-client-spi/src/main/java/software/amazon/awssdk/http/SdkHttpConfigurationOption.java, http-clients/apache-client/src/main/java/software/amazon/awssdk/http/apache/internal/Defaults.java
**All current options in following classes are advanced**
AwsAdvancedClientOption
SdkAdvancedClientOption
SdkAdvancedAsyncClientOption
**All default values match the values used in v1.** I don't remember any discussion on changing these values.
https://github.com/aws/aws-sdk-java-v2/blob/master/http-client-spi/src/main/java/software/amazon/awssdk/http/SdkHttpConfigurationOption.java#L81-L88
https://github.com/aws/aws-sdk-java-v2/blob/master/http-clients/apache-client/src/main/java/software/amazon/awssdk/http/apache/internal/Defaults.java
**Other Changes**
Removed unused option in SdkSystemSetting class
=> Verifying the http default values

http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/internal/ResponseHandler.java
- Allow multiple subscribers
- Flip to done before signaling onError/onComplete to prevent infinite
recursion if the subscription is called again synchronously from
within those methods
=> Add fixes for FullResponseContentPublisher

http-client-spi/src/main/java/software/amazon/awssdk/http/SdkHttpConfigurationOption.java, http-clients/apache-client/src/main/java/software/amazon/awssdk/http/apache/ApacheHttpClient.java, http-clients/apache-client/src/test/java/software/amazon/awssdk/http/apache/ApacheHttpClientWireMockTest.java, http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/NettyNioAsyncHttpClient.java, http-clients/netty-nio-client/src/test/java/software/amazon/awssdk/http/nio/netty/NettyNioAsyncHttpClientWireMockTest.java, test/http-client-tests/src/main/java/software/amazon/awssdk/http/SdkHttpClientTestSuite.java
Using SdkHttpConfigurationOption#TRUST_ALL_CERTIFICATES option to disable cert validation and strict host name verification. This option is disabled by default. Customers can enable it in httpClients by passing it to buildWithDefaults() method
=> Expose option to trust all certs in Apache client

codegen/src/main/resources/macros/marshaller/ec2/MemberMarshallerMacro.ftl, codegen/src/main/resources/macros/marshaller/query/MemberMarshallerMacro.ftl, codegen/src/main/resources/macros/marshaller/rest-xml/MemberMarshallerMacro.ftl, services/rds/src/test/java/software/amazon/awssdk/services/rds/PresignRequestHandlerTest.java, services/s3/src/it/java/software/amazon/awssdk/services/s3/BucketAnalyticsConfigurationIntegrationTest.java, services/s3/src/it/java/software/amazon/awssdk/services/s3/BucketInventoryConfigurationIntegrationTest.java, test/protocol-tests/src/main/resources/codegen-resources/query/customization.config, test/protocol-tests/src/main/resources/codegen-resources/restxml/customization.config
Correctly handle autoconstruct lists for non-JSON protocol marshallers.
Correctly handle autoconstruct lists for non-JSON protocol marshallers.
Verified:
- `mvn clean install`
- `mvn clean verify -Dskip.unit.tests -P integration-tests -Dfindbugs.skip -Dcheckstyle.skip -pl !:dynamodbmapper-v1 -Dfailsafe.rerunFailingTestsCount=1`
=> Handle autoconstruct lists in non-JSON protocols

.changes/next-release/feature-AWSSDKforJavav2-deb2963.json, core/src/main/java/software/amazon/awssdk/core/util/XpathUtils.java
Caching XPathFactory to improve performance of exception handling for services using xml protocol
v1 parity
=> Caching XPathFactory

bundle/pom.xml
- Relocate Netty
- Correctly include and relocate Ion
I also changed the naming conventions a little to just prepend `software.amazon.awssdk.thirdparty` to the original package name. This results in slightly longer package names but is more predictable.
=> Add bundle relocation fixes

.changes/next-release/bugfix-NettyNIOAsyncHTTPClient-2a5d0da.json, http-clients/netty-nio-client/pom.xml, http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/internal/RunnableRequest.java, http-clients/netty-nio-client/src/test/java/software/amazon/awssdk/http/nio/netty/NettyNioAsyncHttpClientWireMockTest.java
Stop publishing after Content-Length bytes
Fixes #460
Stop publishing after Content-Length bytes
Fixes #460
Fix #460
`mvn clean install` with new unit test.
=> Stop publishing after Content-Length bytes

core/src/main/java/software/amazon/awssdk/core/async/FileAsyncRequestBody.java, core/src/main/java/software/amazon/awssdk/core/sync/RequestBody.java, core/src/main/java/software/amazon/awssdk/core/util/Mimetype.java, core/src/test/java/software/amazon/awssdk/core/async/AsyncRequestBodyTest.java, core/src/test/java/software/amazon/awssdk/core/sync/RequestBodyTest.java
There are several places in public API of aws-sdk where both `java.io.File` and `java.nio.file.Path` are supported. Usually only the variant that accepts `Path` contains concrete implementation and the other calls `method(file.toPath(), ...)`, but there are few places where things are done the other way around (and thus `path.toFile()` is called). Unfortunately `path -> file` conversion is not possible for paths that exist on non-default filesystem (like already used here in tests in-memory [Jimfs](https://github.com/google/jimfs) filesystem). Avoiding `path -> file` conversion makes API more test friendly (among other things).
- It makes possible to create request body from files from non-default filesystem.
- It makes API more test friendly.
I extended existing tests so that methods …
=> Avoid path.toFile calls

http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/internal/ResponseHandler.java
Additionally, move the setting of the 'SUBSCRIBER_KEY' value out of the
onNext call, I'm not sure why it was there initially.
=> Move assignment of subscriber to top

codegen/src/main/java/software/amazon/awssdk/codegen/poet/client/AsyncClientClass.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/test-async-client-class.java, core/src/main/java/software/amazon/awssdk/core/client/handler/BaseAsyncClientHandler.java, core/src/main/java/software/amazon/awssdk/core/client/handler/SdkAsyncClientHandler.java, core/src/main/java/software/amazon/awssdk/core/util/CompletableFutures.java, core/src/test/java/software/amazon/awssdk/core/client/AsyncClientHandlerExceptionTest.java, core/src/test/java/software/amazon/awssdk/core/client/AsyncClientHandlerInterceptorExceptionTest.java
Upon calling BaseAsyncClientHandler#execute, any exceptions that get
thrown over the lifetime of the request are signaled through to
CompletableFuture returned to the caller.
Fixes #436
So that users only need to worry about one mechanism for dealing with exceptions on async requests instead of 2.
`mvn clean install` with new unit tests.
=> Signal exceptions through CompletableFuture

http-clients/apache-client/src/main/java/software/amazon/awssdk/http/apache/ProxyConfiguration.java
Removing password from toString method. (Similar to what we do for Credentials classes where we don't use secret key in toString).
=> Don't use proxy password in toString method

core/src/main/java/software/amazon/awssdk/core/internal/protocol/json/JsonErrorUnmarshaller.java, services/rds/src/main/java/software/amazon/awssdk/services/rds/CopyDbSnapshotPresignInterceptor.java, services/rds/src/main/java/software/amazon/awssdk/services/rds/CreateDbInstanceReadReplicaPresignInterceptor.java, services/rds/src/main/java/software/amazon/awssdk/services/rds/RdsPresignInterceptor.java, test/dynamodbmapper-v1/src/it/java/software/amazon/awssdk/services/dynamodb/mapper/GenerateCreateTableRequestIntegrationTest.java, test/dynamodbmapper-v1/src/test/java/software/amazon/awssdk/services/dynamodb/ImmutableObjectUtils.java, test/dynamodbmapper-v1/src/test/java/software/amazon/awssdk/services/dynamodb/datamodeling/StandardModelFactories.java
* Move ImmutableObjectUtils to test/dynamodbmapper module as it uses reflection to set object values. I don't think we want to expose it (yet)
* **Main change:** 
We don't modify the RDS original requests anymore to set the preSignedUrl parameter. Presigning still works as we send the value correctly to the service. I think this is acceptable change as it is not mentioned in the SEP that we need to modify the original request.
=> Move ImmutableObjectUtils to mapper module

.changes/next-release/removal-AWSSDKforJavav2-3225a54.json, codegen/src/main/java/software/amazon/awssdk/codegen/poet/paginators/AsyncResponseClassSpec.java, codegen/src/main/java/software/amazon/awssdk/codegen/poet/paginators/PaginatorsClassSpec.java, codegen/src/main/java/software/amazon/awssdk/codegen/poet/paginators/SyncResponseClassSpec.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/paginators/PaginatedOperationWithResultKeyIterable.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/paginators/PaginatedOperationWithResultKeyPublisher.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/paginators/PaginatedOperationWithoutResultKeyIterable.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/paginators/PaginatedOperationWithoutResultKeyPublisher.java, services/dynamodb/src/it/java/software/amazon/awssdk/services/dynamodb/ScanPaginatorIntegrationTest.java, services/s3/src/it/java/software/amazon/awssdk/services/s3/ListObjectsV2PaginatorsIntegrationTest.java
- Updated `resume` methods to private.
- removed `final` modifier from methods parameters to be consistent with other generated methods.
=> Make paginator resume method private

.changes/next-release/feature-AmazonDynamoDB-d1378b3.json, services/dynamodb/src/main/java/software/amazon/awssdk/services/dynamodb/DynamoDbRetryPolicy.java
Update DDB default max retry count to 8
related to #431
=> Update DDB default max retry count to 8

build-tools/src/main/java/software/amazon/awssdk/buildtools/checkstyle/SdkPublicMethodNameCheck.java, build-tools/src/main/resources/software/amazon/awssdk/checkstyle.xml, pom.xml, test/test-utils/src/main/java/software/amazon/awssdk/testutils/retry/RetryRule.java
Add method name checkstyle to make sure we are not using kotlin function names as public method name.
The `SdkPublicMethodNameCheck` will only check against `public` methods within classes annoted with`@SdkPublicApi`
=> add method name checkstyle

build-tools/src/main/java/software/amazon/awssdk/buildtools/checkstyle/MissingSdkAnnotationCheck.java, build-tools/src/main/resources/software/amazon/awssdk/checkstyle-suppressions.xml, build-tools/src/main/resources/software/amazon/awssdk/checkstyle.xml, core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/http/UnreliableTestConfig.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/util/CompletableFutures.java
Add MissingSdkAnnotationCheck to make sure all non-test classes are marked with sdk annotation
Reduce manual review effort
=> Add MissingSdkAnnotationCheck 

.changes/next-release/feature-AWSWAFRegional-6c8fb6b.json, .changes/next-release/feature-AmazonDynamoDBStreams-d03b835.json, codegen-maven-plugin/src/main/java/software/amazon/awssdk/codegen/maven/plugin/GenerationMojo.java, codegen/src/main/java/software/amazon/awssdk/codegen/emitters/tasks/SharedModelsTaskParamsValidator.java, codegen/src/main/java/software/amazon/awssdk/codegen/model/config/customization/CustomizationConfig.java, codegen/src/main/java/software/amazon/awssdk/codegen/model/config/customization/ShareModelConfig.java, codegen/src/main/java/software/amazon/awssdk/codegen/naming/DefaultNamingStrategy.java, codegen/src/test/java/software/amazon/awssdk/codegen/naming/DefaultNamingStrategyTest.java, services/dynamodb/src/it/java/software/amazon/awssdk/services/dynamodb/streams/StreamsIntegrationTest.java, services/dynamodb/src/main/resources/codegen-resources/dynamodbstreams/customization.config, services/waf/src/it/java/software/amazon/awssdk/services/waf/regional/WafRegionalIntegrationTest.java, services/waf/src/main/resources/codegen-resources/waf-regional/customization.config
Make sure each module has a dedicated package root.
If a service is sharing models with other service, the package root of that service is going to be within that shared service package.
eg:
dynamodb -> `software.amazon.awssdk.services.dynamodb`
dynamodbstreams -> `software.amazon.awssdk.services.dynamodb.dynamodbstreams`
waf -> `software.amazon.awssdk.services.waf`
waf-regional: -> `software.amazon.awssdk.services.waf.wafregional`
=> Make sure each module has a dedicated package root.

.changes/next-release/feature-AWSSDKforJavav2-3867989.json, codegen/src/main/java/software/amazon/awssdk/codegen/naming/DefaultNamingStrategy.java, codegen/src/test/java/software/amazon/awssdk/codegen/naming/DefaultNamingStrategyTest.java, services/elasticloadbalancing/src/it/java/software/amazon/awssdk/services/elasticloadbalancing/ElbIntegrationTest.java, services/machinelearning/src/it/java/software/amazon/awssdk/services/machinelearning/AmazonMachineLearningIntegrationTest.java, services/machinelearning/src/main/java/software/amazon/awssdk/services/machinelearning/internal/RandomIdInterceptor.java, services/rds/src/main/java/software/amazon/awssdk/services/rds/CopyDbSnapshotPresignInterceptor.java, services/rds/src/main/java/software/amazon/awssdk/services/rds/CreateDbInstanceReadReplicaPresignInterceptor.java, services/rds/src/test/java/software/amazon/awssdk/services/rds/PresignRequestHandlerTest.java, services/sts/src/main/java/software/amazon/awssdk/services/sts/auth/StsAssumeRoleWithSamlCredentialsProvider.java, services/sts/src/test/java/software/amazon/awssdk/services/sts/auth/StsAssumeRoleWithSamlCredentialsProviderTest.java, services/waf/src/it/java/software/amazon/awssdk/services/waf/WafIntegrationTest.java, services/waf/src/it/java/software/amazon/awssdk/services/waf/regional/WafRegionalIntegrationTest.java
- Update all service models to follow V2 naming convention. i.e. `FooBarRequest` rather than `FOOBARRequest`
- Fixed the bug where we adding space between camel cased words when the string is `"TestByIndex"`, it will become `"Test ByIndex"`
=> Update all service models to follow V2 naming convention

core/sdk-core/src/main/java/software/amazon/awssdk/core/client/handler/BaseSyncClientHandler.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/exception/NonRetryableException.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/retry/conditions/RetryOnExceptionsCondition.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/sync/ResponseTransformer.java, core/sdk-core/src/test/java/software/amazon/awssdk/core/retry/RetryOnExceptionsConditionTest.java, test/protocol-tests/src/test/java/software/amazon/awssdk/protocol/tests/ResponseTransformerTest.java
Modify `RetryOnExceptionsCondition` to consider subclasses of exception defined in `exceptionsToRetryOn`, e.g. `SSLException` will be retried because it's a subclass of `IOException` if `IOException` is in `exceptionsToRetryOn`
#585 
Added unit test for this behaviour.
=> Fix #585 RetryOnExceptions should consider subclasses of exceptions.

codegen/src/main/java/software/amazon/awssdk/codegen/poet/client/AsyncClientClass.java, codegen/src/main/java/software/amazon/awssdk/codegen/poet/client/ClientClassUtils.java, codegen/src/main/java/software/amazon/awssdk/codegen/poet/client/SyncClientClass.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/test-async-client-class.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/test-json-client-class.java, core/aws-core/src/main/java/software/amazon/awssdk/awscore/AwsRequestOverrideConfiguration.java, services/dynamodb/src/test/java/software/amazon/awssdk/services/dynamodb/PaginatorInUserAgentTest.java, services/dynamodb/src/test/resources/log4j.properties
This is how the generated codes look like:
```java
@Override
public BatchGetItemIterable batchGetItemPaginator(BatchGetItemRequest batchGetItemRequest)
throws ProvisionedThroughputExceededException, ResourceNotFoundException, InternalServerErrorException,
AwsServiceException, SdkClientException, DynamoDbException {
return new BatchGetItemIterable(this, applyPaginatorUserAgent(batchGetItemRequest));
}
private <T extends DynamoDbRequest> T applyPaginatorUserAgent(T request) {
Consumer<AwsRequestOverrideConfiguration.Builder> userAgentApplier = b -> b.addApiName(ApiName.builder()
.version(VersionInfo.SDK_VERSION).name("SDKPaginator").build());
AwsRequestOverrideConfiguration overrideConfiguration = request.overrideConfiguration()
.map(c -> …
```
=> Add paginator user agent

services/s3/src/main/java/software/amazon/awssdk/services/s3/transform/S3ExceptionUnmarshaller.java
AwsErrorDetails is always null so adding in the null check for the S3 exception unmarshaller.
=> Fixing s3 unmarshalling

bundle/pom.xml
These are part of the public API so if we relocate them it makes it difficult for customers to interop the publishers/subscribers with other libraries like RxJava.
=> Don't relocate reactivestreams in bundle

services/cloudformation/src/it/java/software/amazon/awssdk/services/cloudformation/StackIntegrationTest.java, services/cloudformation/src/it/java/software/amazon/awssdk/services/cloudformation/TemplateIntegrationTest.java
These tests work in Intellij. But they fail running through command line due to issues with loading resource files using classloader. Ignoring the tests for now to unblock the next preview release.
=> Ignore tests failing due to issues with loading resource files

http-clients/netty-nio-client/src/test/java/software/amazon/awssdk/http/nio/netty/NettyNioAsyncHttpClientWireMockTest.java
We should be returning a new instance rather than the same instance from
the mock to comply with the interface.
=> Return new instance for newChannel

.changes/2.0.0-preview-2.json, .changes/2.0.0-preview-4.json, CHANGELOG.md, codegen/src/main/java/software/amazon/awssdk/codegen/docs/DocumentationBuilder.java, core/auth/src/main/java/software/amazon/awssdk/auth/credentials/ContainerCredentialsProvider.java, core/aws-core/src/main/java/software/amazon/awssdk/awscore/protocol/xml/StaxUnmarshallerContext.java, core/regions/src/main/java/software/amazon/awssdk/regions/internal/model/Service.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/protocol/json/SdkCborGenerator.java, core/sdk-core/src/test/java/software/amazon/awssdk/core/util/XpathUtilsTest.java, docs/UseOfCompletableFuture.md, http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/SdkEventLoopGroup.java, services/appsync/src/main/resources/codegen-resources/service-2.json, services/autoscaling/src/it/java/software/amazon/awssdk/services/autoscaling/AutoScalingIntegrationTest.java, services/dynamodb/src/it/java/software/amazon/awssdk/services/dynamodb/DynamoServiceIntegrationTest.java, services/stepfunctions/src/main/java/software/amazon/awssdk/services/stepfunctions/builder/internal/validation/Problem.java, test/dynamodbdocument-v1/src/it/java/software/amazon/awssdk/services/dynamodb/document/UpdateItemIntegrationTest.java, test/dynamodbmapper-v1/src/it/java/software/amazon/awssdk/services/dynamodb/datamodeling/BatchLoadIntegrationTest.java, test/dynamodbmapper-v1/src/test/java/software/amazon/awssdk/services/dynamodb/datamodeling/DynamoDbMappingException.java, test/dynamodbmapper-v1/src/test/java/software/amazon/awssdk/services/dynamodb/datamodeling/DynamoDbMarshaller.java, test/dynamodbmapper-v1/src/test/java/software/amazon/awssdk/services/dynamodb/datamodeling/DynamoDbMarshalling.java, test/dynamodbmapper-v1/src/test/java/software/amazon/awssdk/services/dynamodb/datamodeling/DynamoDbScalarAttribute.java, test/dynamodbmapper-v1/src/test/java/software/amazon/awssdk/services/dynamodb/datamodeling/DynamoDbTypeConverterFactory.java, test/dynamodbmapper-v1/src/test/java/software/amazon/awssdk/services/dynamodb/datamodeling/DynamoDbTyped.java, test/dynamodbmapper-v1/src/test/java/software/amazon/awssdk/services/dynamodb/datamodeling/StandardModelFactoriesTest.java, test/test-utils/src/main/java/software/amazon/awssdk/core/auth/policy/internal/JsonPolicyReader.java, test/test-utils/src/main/java/software/amazon/awssdk/core/waiters/WaiterAcceptor.java
This pull request fixes typos in this repository. Although I am not a native English speaker, [misspell](https://github.com/client9/misspell) detected obvious mistakes for us. I've fixed them except for false positives.
```
$ find . -name *.java | xargs misspell
./http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/SdkEventLoopGroup.java:121:72: "succesful" is a misspelling of "successful"
./core/aws-core/src/main/java/software/amazon/awssdk/awscore/protocol/xml/StaxUnmarshallerContext.java:151:22: "psuedo" is a misspelling of "pseudo"
./core/aws-core/src/main/java/software/amazon/awssdk/awscore/protocol/xml/StaxUnmarshallerContext.java:168:22: "psuedo" is a misspelling of "pseudo"
./core/regions/src/main/java/software/amazon/awssdk/regions/internal/model/Serv …
```
=> Fix the several typos detected by github.com/client9/misspell

.changes/next-release/bugfix-AWSSDKforJavav2-b093be5.json, core/sdk-core/src/main/java/software/amazon/awssdk/core/retry/RetryPolicy.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/retry/backoff/EqualJitterBackoffStrategy.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/retry/backoff/FixedDelayBackoffStrategy.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/retry/backoff/FullJitterBackoffStrategy.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/retry/conditions/AndRetryCondition.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/retry/conditions/MaxNumberOfRetriesCondition.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/retry/conditions/OrRetryCondition.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/retry/conditions/RetryOnExceptionsCondition.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/retry/conditions/RetryOnStatusCodeCondition.java, core/sdk-core/src/test/java/software/amazon/awssdk/core/retry/RetryPolicyTest.java, test/protocol-tests/src/test/java/software/amazon/awssdk/protocol/tests/retry/AwsJsonRetryTest.java
- fix #646 
- added `toString()`, `hashcode`, `equals` methods to retry policy related classes.
- Make `RetryPolicy.none()` truly none retry policy. 
Currently, `RetryPolicy.none().retryCondition().toString()` resolves to: 
```
AndRetryCondition(conditions=[MaxNumberOfRetriesCondition(maxNumberOfRetries=3), MaxNumberOfRetriesCondition(maxNumberOfRetries=0)])
```
and it should be 
```
MaxNumberOfRetriesCondition(maxNumberOfRetries=0)
```
- added more tests.
=> Fix retrypolicy bug, see issue #646

codegen/src/main/java/software/amazon/awssdk/codegen/AddExceptionShapes.java, codegen/src/main/java/software/amazon/awssdk/codegen/poet/client/specs/JsonProtocolSpec.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/test-async-client-class.java, core/aws-core/src/main/java/software/amazon/awssdk/awscore/eventstream/EventStreamAsyncResponseTransformer.java, core/aws-core/src/main/java/software/amazon/awssdk/awscore/eventstream/EventStreamExceptionJsonUnmarshaller.java, core/aws-core/src/main/java/software/amazon/awssdk/awscore/internal/protocol/json/JsonErrorCodeParser.java, core/aws-core/src/main/java/software/amazon/awssdk/awscore/protocol/json/AwsJsonErrorMessageParser.java, core/aws-core/src/test/java/software/amazon/awssdk/awscore/eventstream/EventStreamAsyncResponseTransformerTest.java, services/kinesis/src/test/java/software/amazon/awssdk/services/kinesis/SubscribeToShardUnmarshallingTest.java
* Add support for modeled exceptions in event streams
* Fix bug in AddExceptionShapes class where we only generate exceptions declared in operations. But event shapes can have modeled exceptions as members.
=> Support modeled exceptions in event streams

buildspecs/build.yml, buildspecs/integ-test.yml, services/devicefarm/src/it/java/software/amazon/awssdk/services/devicefarm/DeviceFarmIntegrationTest.java
add codebuild buildspec files so that we don't need to copy paste the same command again and again..
also, updated device farm integ test to clean up resource
=> add codebuild buildspec files 

pom.xml
The spotbugs plugin doesn't recognize the findbugs flag.
=> Replace findbugs.skip with spotbugs.skip

buildspecs/update-snapshot-version.yml
Add Codebuild buildspec file for updateSnapshotversion after release.
It will do the following:
- Bump up snapshot version
- Generate changelogs
- Update README file to point to the latest release version
- Push to master
testing branch: https://github.com/aws/aws-sdk-java-v2/compare/zoewang-testing
=> Add Codebuild buildspec file for updateSnapshotversion after release

.changes/next-release/bugfix-AWSSDKforJavav2-532f520.json, codegen/src/main/java/software/amazon/awssdk/codegen/poet/paginators/PaginatorsClassSpec.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/paginators/PaginatedOperationWithResultKeyIterable.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/paginators/PaginatedOperationWithResultKeyPublisher.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/paginators/PaginatedOperationWithoutResultKeyIterable.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/paginators/PaginatedOperationWithoutResultKeyPublisher.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/util/PaginatorUtils.java, core/sdk-core/src/test/java/software/amazon/awssdk/core/util/PaginatorUtilsTest.java, services/dynamodb/src/it/java/software/amazon/awssdk/services/dynamodb/PaginatorIntegrationTest.java, utils/src/test/java/software/amazon/awssdk/utils/CollectionUtilsTest.java
Fix paginated response iterable hasNextPage to check if the output token is non null or non empty if it is a collection or map type. 
`Dynamodb.batchGetItem` returns empty `unprocessedKeys` when there is no unprocessedKeys.
`"{"Responses":{"zoewang-TestTable":[{"attribute_foo":{"S":"test"},"hash":{"N":"0"}}]},"UnprocessedKeys":{}}"`
So unprocessedKeys is an empty map and not an instance of `SdkAutoConstructMap`. (we only create the `SdkAutoConstructMap` when it is null)
Currently, the `hasNextPage` checks if the output token is not null AND it is not instance of SdkAutoConstructMap AND not an instance of SdkAutoConstructList. So `hasNextPage` will always return true for empty list or map, which is not expected.
Fixes #677
`mvn clean install` local integration test.
Note: I didn't create …
=> Fix paginated response iterable hasNextPage

.changes/next-release/feature-AWSSDKforJavav2.json, http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/NettyNioAsyncHttpClient.java, http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/internal/SdkChannelOptions.java, http-clients/netty-nio-client/src/test/java/software/amazon/awssdk/http/nio/netty/internal/SdkChannelOptionsTest.java
Allow clients to set custom socket options
Original Pull Request - https://github.com/aws/aws-sdk-java-v2/pull/656
Advanced clients may want to set up custom socket options for cases which suit their requirement. An example of this is SO_LINGER is a socket option which clients may want to set up if they want to open a large number of ports. 
Issue - https://github.com/aws/aws-sdk-java-v2/issues/564
mvn install
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 11:47 min
[INFO] Finished at: 2018-08-10T16:30:07-04:00
- [x ] New feature (non-breaking change which adds functionality)
- [x ] I have read the **CONTRIBUTING** document
- [ x] Local …
=> Allow Clients to set Socket channel option

codegen/src/main/java/software/amazon/awssdk/codegen/poet/client/AsyncClientInterface.java, codegen/src/main/java/software/amazon/awssdk/codegen/poet/client/SyncClientInterface.java
PoetUtils.addJavadoc takes care of escaping any '$' characters present in the
javadoc which would otherwise be interpreted as a placeholder by Poet.
=> Use PoetUtils to set javadoc

services/applicationdiscovery/src/main/resources/codegen-resources/customization.config, services/devicefarm/src/main/resources/codegen-resources/customization.config, services/ec2/src/main/resources/codegen-resources/customization.config, services/iot/src/main/resources/codegen-resources/customization.config, services/shield/src/main/resources/codegen-resources/customization.config
The code generator whitelists some simple method candidate methods by
default based on the verb used, but these methods fail the generated
integration tests.
Fix integration tests.
=> Blacklist failing simple methods

http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/internal/ResponseHandler.java
Current behavior is we close the connection and release it to pool ([here](https://github.com/aws/aws-sdk-java-v2/blob/5f8d7182150fc4256102f3dad4def0a8a24cc63e/http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/internal/ResponseHandler.java#L145-L148)) which is the desired behavior.
=> Cleanup TODO in ResponseHandler

core/sdk-core/src/test/java/software/amazon/awssdk/core/internal/http/timers/AsyncHttpClientApiCallTimeoutTests.java, http-clients/apache-client/pom.xml, http-clients/apache-client/src/main/java/software/amazon/awssdk/http/apache/ApacheHttpClient.java, http-clients/apache-client/src/main/java/software/amazon/awssdk/http/apache/ProxyConfiguration.java, http-clients/apache-client/src/main/java/software/amazon/awssdk/http/apache/internal/ApacheHttpRequestConfig.java, http-clients/apache-client/src/main/java/software/amazon/awssdk/http/apache/internal/SdkProxyRoutePlanner.java, http-clients/apache-client/src/main/java/software/amazon/awssdk/http/apache/internal/impl/ApacheHttpRequestFactory.java, http-clients/apache-client/src/main/java/software/amazon/awssdk/http/apache/internal/utils/ApacheUtils.java, http-clients/apache-client/src/test/java/software/amazon/awssdk/http/apache/ProxyConfigurationTest.java, http-clients/apache-client/src/test/java/software/amazon/awssdk/http/apache/internal/SdkProxyRoutePlannerTest.java, utils/src/main/java/software/amazon/awssdk/utils/ProxySystemSetting.java
* Current Apache [configuration options](https://github.com/aws/aws-sdk-java-v2/blob/32ea7e74844975dcbb38e99967fa2a0e7b6d9db5/http-clients/apache-client/src/main/java/software/amazon/awssdk/http/apache/ApacheHttpClient.java#L263-L307) and [default values](https://github.com/aws/aws-sdk-java-v2/blob/32ea7e74844975dcbb38e99967fa2a0e7b6d9db5/http-clients/apache-client/src/main/java/software/amazon/awssdk/http/apache/internal/DefaultConfiguration.java) seems fine (matches v1)
* Includes changes to support nonProxyHosts proxy configuration ([v1 reference](https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-core/src/main/java/com/amazonaws/http/apache/SdkProxyRoutePlanner.java))
=> Apache configuration cleanup

core/aws-core/src/main/java/software/amazon/awssdk/awscore/eventstream/EventStreamAsyncResponseTransformer.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/http/HttpResponseHandler.java
=> Including extended request id in event stream response

.changes/next-release/feature-AWSSecurityTokenService-cdd6371.json, services/sts/src/main/java/software/amazon/awssdk/services/sts/auth/StsAssumeRoleWithSamlCredentialsProvider.java, services/sts/src/test/java/software/amazon/awssdk/services/sts/auth/StsAssumeRoleWithSamlCredentialsProviderTest.java, services/sts/src/test/java/software/amazon/awssdk/services/sts/auth/StsCredentialsProviderTestBase.java
Added new Sts credential provider class that auto renews a SAML assertion
Created interface that can be implemented to provide functionality to CredentialProvider
When using the StsAssumeRoleWithSamlCredentialProvider, a non expired saml assertion is needed before the AWS credentials can be refreshed.  Currently, the SDK doesn't provide a way to handle renewing the saml assertion before calling the STS service to obtain new AWS credentials.  This pull requests implements a generic solution for this.
It's possible that the new class could be merged into the current StsAssumeRoleWithSamlCredentialProvider, but I wasn't sure if that would be the best way to handle it.
Added unit tests for the new class. 
- [ X] New feature (non-breaking change which adds functionality)
- [ X ] I have read …
=> Create AutoRenewable STS/SAML credentialsProvider

core/sdk-core/pom.xml
The core bundle does the actual loading through ServiceLoader so it should
declare the requirement on the capability.
#607.
Create a bundle that uses Kinesis and attempt to make a service call.
=> Require HTTP service cap from core

codegen/src/main/java/software/amazon/awssdk/codegen/model/intermediate/ShapeModel.java, http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/internal/NettyRequestExecutor.java
- Fix hasPayloadMembers() to ensure that the shape is an event before checking
for unbound event members. Otherwise, the test will always return true for
any shape that has member.
- For non full duplex requests, continue to perform a channel.read() call only
after writing the request to avoid ReadTimeoutExceptions.
Bug fixes.
Run integration tests.
=> Fix marshalling and Netty async bugs

http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/internal/NettyRequestExecutor.java
For full duplex operations, execution will always go to `else` block and close the channel even if wirecall is successful.
=> Fix bug where full duplex requests are closed when wirecall is success

codegen/src/main/java/software/amazon/awssdk/codegen/naming/DefaultNamingStrategy.java, codegen/src/test/java/software/amazon/awssdk/codegen/naming/DefaultNamingStrategyTest.java
This ports the same fix added to DefaultNamingStrategy from V1.
Related to #693.
Update service models.
`mvn clean install`, also ported over tests.
=> Filter blanks in getJavaClassName

codegen/src/main/java/software/amazon/awssdk/codegen/poet/model/TypeProvider.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/alltypesrequest.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/alltypesresponse.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/listofmapstringtostringcopier.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/nonautoconstructcontainers/alltypesrequest.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/nonautoconstructcontainers/alltypesresponse.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/nonautoconstructcontainers/listofmapstringtostringcopier.java
Related to #693.
Update service models.
=> Allow subtypes of Map for Collection elements

codegen/src/main/java/software/amazon/awssdk/codegen/poet/paginators/AsyncResponseClassSpec.java, codegen/src/main/java/software/amazon/awssdk/codegen/poet/paginators/SyncResponseClassSpec.java
It's possible for the `result_key` member to be something other than a List or Map. How we do item level iteration for those types will be done in a separate PR.
Update service models. Related to #693.
=> Don't generate item paginator for non-containers

flow/src/main/java/software/amazon/eventstream/Message.java, flow/src/main/java/software/amazon/eventstream/MessageDecoder.java, flow/src/test/java/software/amazon/eventstream/MessageDecoderTest.java
Update flow module with latest internal changes
=> Add Message#encodeHeaders

.changes/next-release/feature-ApacheHTTPClient-fa9710f.json, http-clients/apache-client/src/main/java/software/amazon/awssdk/http/apache/ApacheHttpClient.java, http-clients/apache-client/src/main/java/software/amazon/awssdk/http/apache/internal/conn/IdleConnectionReaper.java, http-clients/apache-client/src/test/java/software/amazon/awssdk/http/apache/internal/conn/IdleConnectionReaperTest.java
=> Enable idle connection reaper for Apache client

core/auth/src/main/java/software/amazon/awssdk/auth/signer/AwsS3V4Signer.java, core/auth/src/main/java/software/amazon/awssdk/auth/signer/internal/AbstractAws4Signer.java, core/auth/src/main/java/software/amazon/awssdk/auth/signer/internal/AbstractAwsSigner.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/RequestOption.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/http/async/SimpleHttpContentPublisher.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/http/pipeline/stages/AsyncRetryableStage.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/http/pipeline/stages/MakeAsyncHttpRequestStage.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/http/pipeline/stages/RetryableStage.java, core/sdk-core/src/test/java/software/amazon/awssdk/core/internal/http/async/SimpleRequestProviderTckTest.java, utils/src/main/java/software/amazon/awssdk/utils/IoUtils.java
This is a fairly low level configuration that we don't foresee many customers
using; can be added back in if requested.
For now, when marking, we set the read limit to the max value of
Integer#MAX_VALUE.
=> Remove read limit option

core/sdk-core/src/main/java/software/amazon/awssdk/core/client/handler/BaseSyncClientHandler.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/exception/RetryableException.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/sync/ResponseTransformer.java, core/sdk-core/src/test/java/software/amazon/awssdk/core/client/handler/SyncClientHandlerTest.java
- Move the logic in `RepsonseTransformer.apply` to `BaseSyncClientHandler`  so that the behavior would not be lost if that method is overriden. 
- Remove the apply method
will run integration tests
=> Refactor RepsonseTransformer.apply

core/auth/src/main/java/software/amazon/awssdk/auth/signer/params/AwsS3V4SignerParams.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/interceptor/ExecutionAttributes.java, services/s3/src/main/java/software/amazon/awssdk/services/s3/S3Configuration.java, services/s3/src/main/java/software/amazon/awssdk/services/s3/handlers/EnableChunkedEncodingInterceptor.java, services/s3/src/test/java/software/amazon/awssdk/services/s3/handlers/EnableChunkedEncodingInterceptorTest.java
Other operations e.g. PutObjectTagging do not support it.
Only really make sense for these two operations anyway, where the payload can
potentially very large so avoiding a pass over the entire stream to calculate
the content SHA is very desirable.
~~Will run integration tests.~~ Integration tests.
=> Default chunked signing just PutObject/UploadPart

buildspecs/build.yml, buildspecs/integ-test.yml, buildspecs/on-demand-integ-test.yml, http-clients/apache-client/pom.xml, pom.xml, protocols/aws-ion-protocol/pom.xml, test/module-path-tests/README.md, test/module-path-tests/pom.xml, test/module-path-tests/src/main/java/module-info.java, test/module-path-tests/src/main/java/software/amazon/awssdk/modulepath/tests/IntegTestsRunner.java, test/module-path-tests/src/main/java/software/amazon/awssdk/modulepath/tests/MockTestsRunner.java, test/module-path-tests/src/main/java/software/amazon/awssdk/modulepath/tests/integtests/BaseApiCall.java, test/module-path-tests/src/main/java/software/amazon/awssdk/modulepath/tests/integtests/S3ApiCall.java, test/module-path-tests/src/main/java/software/amazon/awssdk/modulepath/tests/mocktests/BaseMockApiCall.java, test/module-path-tests/src/main/java/software/amazon/awssdk/modulepath/tests/mocktests/JsonProtocolApiCall.java, test/module-path-tests/src/main/java/software/amazon/awssdk/modulepath/tests/mocktests/MockAyncHttpClient.java, test/module-path-tests/src/main/java/software/amazon/awssdk/modulepath/tests/mocktests/MockHttpClient.java, test/module-path-tests/src/main/java/software/amazon/awssdk/modulepath/tests/mocktests/XmlProtocolApiCall.java, test/protocol-tests/pom.xml, test/service-test-utils/pom.xml
This PR is to make sure we cover the module path testing for Java 9+. The existing tests we will only run on the class path and we cannot guarantee it will work on module path.
- Created `module-path-test` module and add functional and integration tests for module path
- mock tests: calling xml/json prococol sync/async clients using mock http clients. (I tried Wiremock but there are split packages in wiremock and it throws errors when running in module path)
- integ tests: calling `S3Client` using `UrlConnectionHttpClient` and `ApacheHttpClient`. (Netty client is not currently working because of two root packages)
- Updated CodeBuild buildspec files to run the tests only when the Java version is 9+
**Note**
- The reason that the "tests" are actually in the main methods and are not Junit …
=> Add functional and integration tests for module path

codegen/src/main/java/software/amazon/awssdk/codegen/poet/builder/BaseClientBuilderClass.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/builder/test-client-builder-class.java
**Current Behavior**
H2 protocol is ignored if service http defaults are set
**New Behavior**
H2 protocol will be added to AttributeMap if service defaults is missing the `PROTOCOL` attribute
=> Add h2 protocol even when service defaults are set

codegen/src/main/java/software/amazon/awssdk/codegen/model/intermediate/IntermediateModel.java, codegen/src/main/java/software/amazon/awssdk/codegen/poet/client/AsyncClientClass.java, codegen/src/main/java/software/amazon/awssdk/codegen/poet/client/ClientClassUtils.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/test-async-client-class.java
* By default, use EventStreamAws4Signer for signing APIs with input events
* If service doesn't not want to sign a particular API, it can be exposed through a c2j trait
=> Use EventStreamAws4Signer by default for APIs with input event stream

codegen-lite-maven-plugin/src/main/java/software/amazon/awssdk/codegen/lite/maven/plugin/RegionGenerationMojo.java, codegen-lite/src/main/java/software/amazon/awssdk/codegen/lite/regions/PartitionMetadataGenerator.java, codegen-lite/src/main/java/software/amazon/awssdk/codegen/lite/regions/PartitionMetadataProviderGenerator.java, codegen-lite/src/main/java/software/amazon/awssdk/codegen/lite/regions/ServiceMetadataGenerator.java, codegen-lite/src/test/java/software/amazon/awssdk/codegen/lite/regions/RegionGenerationTest.java, codegen-lite/src/test/resources/software/amazon/awssdk/codegen/lite/regions/partition-metadata-provider.java, codegen-lite/src/test/resources/software/amazon/awssdk/codegen/lite/regions/partition-metadata.java, codegen-lite/src/test/resources/software/amazon/awssdk/codegen/lite/regions/s3-service-metadata.java, core/regions/src/main/java/software/amazon/awssdk/regions/DefaultServiceMetadata.java, core/regions/src/main/java/software/amazon/awssdk/regions/MetadataLoader.java, core/regions/src/main/java/software/amazon/awssdk/regions/PartitionMetadata.java, core/regions/src/main/java/software/amazon/awssdk/regions/PartitionMetadataProvider.java, core/regions/src/main/java/software/amazon/awssdk/regions/ServiceMetadata.java, services/sts/src/it/java/software/amazon/awssdk/services/sts/IntegrationTestBase.java
Adds additional resiliency to endpoint creation. Partially fixes STS situation but I also moved those tests to use us-east-1 while we wait for STS to fix their configuration in endpoints.json
Fixes broken integ/unit tests
Ran all unit tests. Ran failing STS integ tests and those now pass.
=> Updating to add additional resiliency to endpoint creation

test/module-path-tests/src/main/java/software/amazon/awssdk/modulepath/tests/mocktests/JsonProtocolApiCall.java
Enable module path tests for json error scenarios because reflection is gone (Yay!)
=> Enable module path tests for json error scenarios

buildspecs/build.yml, buildspecs/integ-test.yml, buildspecs/on-demand-integ-test.yml, buildspecs/update-snapshot-version.yml, test/module-path-tests/pom.xml
Fix update-snapsot-version to check master to avoid detached HEAD
=> Fix update-snapshot-version yml

http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/internal/NettyRequestExecutor.java, http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/internal/ResponseHandler.java
- Wrap Netty `ReadTimeoutException` and `WriteTimeoutException` in ResponseHandler so they can be retried
- Update logging level from "error" to "debug"  because some errors are retryable and unretryable errors will be logged again in the upper layer.
=> Wrap ReadTimeoutException and WriteTimeoutException in ResponseHandler

core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/async/FileAsyncResponseTransformer.java
Fix race condition in FileAsyncResponseTransformer where future can be completed before last bytebuffer is written to the file
=> Fix race condition in FileAsyncResponseTransformer

.changes/next-release/bugfix-NettyNIOAsyncHTTPClient-3e595bb.json, http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/internal/ChannelAttributeKey.java, http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/internal/HandlerRemovingChannelPool.java, http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/internal/NettyRequestExecutor.java, http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/internal/ResponseHandler.java
Not fireExceptionCaught if the channel is released back to the pool to avoid warning messages showing up like the following.
```
2018-11-16 15:13:30,347 [aws-java-sdk-NettyEventLoop-1-3] WARN  io.netty.channel.DefaultChannelPipeline - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
software.amazon.awssdk.http.nio.netty.internal.FutureCancelledException: java.io.IOException: Server failed to send complete response"
```
see https://github.com/aws/aws-sdk-java-v2/issues/452
Tested with the the example code customer provided in the above issue: sending s3 request every 60s
=> Not fireExceptionCaught if the channel was released back to the pool

core/regions/src/main/resources/software/amazon/awssdk/regions/internal/region/endpoints.json, services/dynamodb/src/it/java/software/amazon/awssdk/services/dynamodb/SignersIntegrationTest.java, services/fms/src/main/resources/codegen-resources/customization.config, services/iot1clickdevices/src/main/resources/codegen-resources/customization.config, services/iotanalytics/src/main/resources/codegen-resources/customization.config, services/kinesisvideoarchivedmedia/src/main/resources/codegen-resources/customization.config, services/macie/src/main/resources/codegen-resources/customization.config, services/pinpointemail/src/main/resources/codegen-resources/customization.config, services/route53resolver/src/main/resources/codegen-resources/customization.config
Alternatively, could undo having the container object with SdkHttpRequest & Stream and go back to just SdkHttpFullRequest.
=> Fixing signers integration tests

services/s3/src/it/java/software/amazon/awssdk/services/s3/GetObjectAsyncIntegrationTest.java, services/s3/src/it/java/software/amazon/awssdk/services/s3/GetObjectIntegrationTest.java, services/s3/src/main/java/software/amazon/awssdk/services/s3/checksums/ChecksumConstant.java, services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/handlers/AsyncChecksumValidationInterceptor.java, services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/handlers/EnableTrailingChecksumInterceptor.java, services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/handlers/SyncChecksumValidationInterceptor.java, services/s3/src/main/resources/software/amazon/awssdk/services/s3/execution.interceptors
Updates the content-length on responses to be the content-length minus the trailing checksum size when trailing checksums are enabled.
=> Updating content length when trailing checksums enabled

buildspecs/integ-test.yml, buildspecs/on-demand-integ-test.yml, pom.xml, test/module-path-tests/pom.xml, test/module-path-tests/src/main/java/software/amazon/awssdk/modulepath/tests/integtests/S3ApiCall.java
so that we don't need to update the parent version for it manually after each release like this https://github.com/aws/aws-sdk-java-v2/commit/9baf986499cae160b2cdaa720b55247ffa1a8fd7#diff-a0ceec564b5bf60c5b3da61928510ad3
The version update will be handled automatically in udpate-snapshot-version step.
=> Make module-path-tests child module of the parent pom 

core/aws-core/src/main/java/software/amazon/awssdk/awscore/client/handler/AwsClientHandlerUtils.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/client/handler/BaseClientHandler.java
Not sure why we were only setting it after finalizeSdkRequest but now it gets set for reading by all interceptors.
=> Plumbing through service name to execution interceptors

.changes/next-release/bugfix-AWSSDKforJavaV2-7ae0927.json, core/protocols/aws-json-protocol/src/main/java/software/amazon/awssdk/protocols/json/internal/dom/SdkEmbeddedObject.java, core/protocols/aws-json-protocol/src/main/java/software/amazon/awssdk/protocols/json/internal/dom/SdkJsonNode.java, core/protocols/aws-json-protocol/src/main/java/software/amazon/awssdk/protocols/json/internal/unmarshall/JsonProtocolUnmarshaller.java, pom.xml
Fixing Issue #864 
CBOR doesn't Base64 bytes and can unmarshall them directly.
Fixes Kinesis GetRecords
Actually running the integ test we have for Kinesis.
=> Fixing CBOR unmarshalling of blobs and running Kinesis integ test

.changes/next-release/bugfix-AWSSDKforJavav2-f82a8d4.json, http-client-spi/src/main/java/software/amazon/awssdk/http/AbortableInputStream.java, services/s3/src/main/java/software/amazon/awssdk/services/s3/checksums/ChecksumValidatingInputStream.java, services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/handlers/SyncChecksumValidationInterceptor.java, test/protocol-tests/src/test/java/software/amazon/awssdk/protocol/tests/ResponseTransformerTest.java
=> Make ChecksumValidatingInputStream implement close(). Preserve abort semantics through interceptor modification.

.changes/next-release/bugfix-AWSOrganizations-e9534c7.json, aws-sdk-java/pom.xml
fixes #872 
Will find an automatic way to add the missing service modules.
=> add organizations to aws-sdk-java module

.changes/next-release/bugfix-AWSSDKforJavav2-89a97c3.json, services/s3/src/it/java/software/amazon/awssdk/services/s3/GetObjectIntegrationTest.java, services/s3/src/main/java/software/amazon/awssdk/services/s3/checksums/ChecksumValidatingInputStream.java
Add checksumValidated flag to ChecksumValidatingInputStream to make s we don't validate twice
Fixes #873 
All s3 integ tests passed
=> Add  flag to make sure we don't validate checksum twice

.changes/next-release/bugfix-AWSSDKforJavav2-135b2d9.json, codegen/src/main/java/software/amazon/awssdk/codegen/docs/PaginationDocs.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/test-async-client-class.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/test-json-async-client-interface.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/paginators/PaginatedOperationWithResultKeyPublisher.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/paginators/PaginatedOperationWithoutResultKeyPublisher.java
`SdkPublisher#forEach` was renamed to `SdkPublisher#subscribe` and we should update the javadoc accordingly.
=> Fix Javadocs on async paginators

.changes/next-release/bugfix-NettyNIOAsyncHTTPClient-5b20e7b.json, http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/internal/NettyRequestExecutor.java
Related to #459 
For `PutObjectRequest`, we are sending `Expect: 100-continue` header and waiting for the service to return "100 Continue" before streaming request. `ChannelOption.AUTO_READ` is disabled, so sometimes it's possible no channel read is triggered to read that message and the request is forever "blocked" waiting for the "100 Continue" response.
The fix is explicitly call `channel.read()` if the request contains "Expect: 100-continue" header
Tested with the sample code provided by customer in #459 and verified it worked after the fix.
=> Fix the issue where putobject requests sometimes is hanging

.changes/next-release/bugfix-AmazonS3-b7ad196.json, .changes/next-release/feature-AWSSDKforJavav2-aca5ef8.json, core/aws-core/src/main/java/software/amazon/awssdk/awscore/exception/AwsErrorDetails.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/interceptor/ExecutionInterceptor.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/interceptor/ExecutionInterceptorChain.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/http/pipeline/stages/AsyncExecutionFailureExceptionReportingStage.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/http/pipeline/stages/ExecutionFailureExceptionReportingStage.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/http/pipeline/stages/utils/ExceptionReportingUtils.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/interceptor/DefaultFailedExecutionContext.java, core/sdk-core/src/test/java/software/amazon/awssdk/core/internal/http/pipeline/stages/ExceptionReportingUtilsTest.java, core/sdk-core/src/test/java/utils/ValidSdkObjects.java, services/s3/src/it/java/software/amazon/awssdk/services/s3/ExceptionUnmarshallingIntegrationTest.java, services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/handlers/ExceptionTranslationInterceptor.java, services/s3/src/main/resources/software/amazon/awssdk/services/s3/execution.interceptors, services/s3/src/test/java/software/amazon/awssdk/services/s3/internal/handlers/ExceptionTranslationInterceptorTest.java, test/protocol-tests/src/test/java/software/amazon/awssdk/protocol/tests/ExecutionInterceptorTest.java
- Translate S3Exception for headObject and headBucket via interceptor
Throw `NoSuchKey` exception for headObject and `NoSuchBucket` exception for headBucket for 404 status code.
- Added `modifyException` interceptor method
All S3 integration tests passed
=> Translate S3Exception for headObject and headBucket

.changes/next-release/bugfix-AWSSDKforJavav2-a5e899c.json, codegen/src/main/java/software/amazon/awssdk/codegen/poet/model/MemberCopierSpec.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/blobmaptypecopier.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/mapofenumtoenumcopier.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/mapofenumtosimplestructcopier.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/mapofenumtostringcopier.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/mapofstringtoenumcopier.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/mapofstringtointegerlistcopier.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/mapofstringtolistoflistofstringscopier.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/mapofstringtosimplestructcopier.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/mapofstringtostringcopier.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/nonautoconstructcontainers/blobmaptypecopier.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/nonautoconstructcontainers/mapofenumtoenumcopier.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/nonautoconstructcontainers/mapofenumtosimplestructcopier.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/nonautoconstructcontainers/mapofenumtostringcopier.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/nonautoconstructcontainers/mapofstringtoenumcopier.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/nonautoconstructcontainers/mapofstringtointegerlistcopier.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/nonautoconstructcontainers/mapofstringtolistoflistofstringscopier.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/nonautoconstructcontainers/mapofstringtosimplestructcopier.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/nonautoconstructcontainers/mapofstringtostringcopier.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/nonautoconstructcontainers/recursivemaptypecopier.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/recursivemaptypecopier.java, test/codegen-generated-classes-test/src/test/java/software/amazon/awssdk/services/codegenerationjsonrpccustomized/model/MapCopierTest.java
While trying out the lexruntime sdk I noticed an issue. The server responds with a json containing `"slots": {"City": null}`, which should be converted to a `Map<String,String>`. However this causes a NullPointerException in `StringMapCopier.copy`. It tries to copy a hashmap by doing an `.entrySet().stream().collect(toMap)`. This fails on null values, there is an old issue logged in the jdk: https://bugs.openjdk.java.net/browse/JDK-8148463 
Instead of using `collect(toMap)`, I would copy the map as follows: `mapOfStringToStringParam.entrySet().stream().collect(HashMap::new, (m, e) -> m.put(e.getKey(), e.getValue()), HashMap::putAll)`. This still allows generating variants of `XXCopier.copy(e.getValue())`
It fixes a NullPointerException that occurs if the server sends a null value in a …
=> Fix nullpointerexception in case a map has null values.

.changes/next-release/bugfix-AmazonS3-22d85db.json, services/s3/src/it/java/software/amazon/awssdk/services/s3/AsyncServerSideEncryptionIntegrationTest.java, services/s3/src/it/java/software/amazon/awssdk/services/s3/SyncServerSideEncryptionIntegrationTest.java, services/s3/src/main/java/software/amazon/awssdk/services/s3/checksums/ChecksumConstant.java, services/s3/src/main/java/software/amazon/awssdk/services/s3/checksums/ChecksumsEnabledValidator.java, services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/handlers/AsyncChecksumValidationInterceptor.java, services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/handlers/SyncChecksumValidationInterceptor.java
S3 trailing checksums don't support SSE either.
=> Turning off trailing checksums for SSE

.changes/next-release/feature-AWSSDKforJavav2-cea02db.json, core/sdk-core/src/main/resources/software/amazon/awssdk/core/util/mime.types, services/s3/src/test/java/software/amazon/awssdk/services/s3/internal/handlers/PutObjectHeaderTest.java
Fix https://github.com/aws/aws-sdk-java-v2/issues/899
Official list at [iana](https://www.iana.org/assignments/media-types/media-types.xhtml) doesn't have the .gz extension. So hand editing the file to add .gz and .gzip
=> Update mime types to add gz and gzip extensions

README.md, build-tools/src/main/java/software/amazon/awssdk/buildtools/checkstyle/MissingSdkAnnotationCheck.java, core/aws-core/src/main/java/software/amazon/awssdk/awscore/eventstream/EventStreamResponseHandler.java, core/protocols/aws-json-protocol/src/main/java/software/amazon/awssdk/protocols/json/internal/dom/SdkJsonNode.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/http/TransformingAsyncResponseHandler.java
- Add sample code link to README 
- fix MissingSdkAnnotationCheck to check interface as well.
=> Add sample code link to README and fix MissingSdkAnnotationCheck 

.changes/next-release/bugfix-AmazonS3-e1a5575.json, codegen/src/main/java/software/amazon/awssdk/codegen/customization/processors/DefaultCustomizationProcessor.java, services/s3/src/main/resources/codegen-resources/customization.config
Fix https://github.com/aws/aws-sdk-java-v2/issues/917
* Move RenameShapesProcessor before other shape modifiers as it removes the original shape from the list of available shapes. If RenameShapesProcessor is not run first, it causes build issues in other shape modifiers.
* Change Size type from Integer -> Long
The change is breaking to applications who are using the `size` method currently. We have decided to make the breaking change as this is a bug and breaking change will force the customers to know about this change and update the applications which have incorrect behavior for large objects
=> Modify S3Object#Size member type from integer to long

.changes/next-release/bugfix-AmazonS3-5df5cc4.json, http-clients/url-connection-client/pom.xml, http-clients/url-connection-client/src/it/java/software/amazon/awssdk/http/urlconnection/S3WithUrlHttpClientIntegrationTest.java, services/s3/src/main/java/software/amazon/awssdk/services/s3/checksums/ChecksumCalculatingInputStream.java
Fix https://github.com/aws/aws-sdk-java-v2/issues/941
**Bug Description**
When request has content stream, [UrlConnectionHttpClient](https://github.com/aws/aws-sdk-java-v2/blob/8128c9922ce1e3516a33e8c29f383bfc852fe456/http-clients/url-connection-client/src/main/java/software/amazon/awssdk/http/urlconnection/UrlConnectionHttpClient.java#L109) copies the content stream to the connection output stream using [IoUtils.copy](https://github.com/aws/aws-sdk-java-v2/blob/8128c9922ce1e3516a33e8c29f383bfc852fe456/utils/src/main/java/software/amazon/awssdk/utils/IoUtils.java#L101-L111) method. The copy methods writes to the outputStream until the endOfStream is reached ie., _in.read method returns -1_. As [ChecksumCalculatingInputStream](https://github.com/aws/aws-sdk-java-v2/blob/8128c9922ce1e3516a33 …
=> Fix bug in ChecksumCalculatingInputStream

.changes/next-release/feature-AWSSDKforJavav2-20b9756.json, codegen/src/main/java/software/amazon/awssdk/codegen/poet/client/specs/JsonProtocolSpec.java, codegen/src/main/java/software/amazon/awssdk/codegen/poet/client/specs/QueryProtocolSpec.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/test-async-client-class.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/test-json-client-class.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/test-query-client-class.java, core/aws-core/src/main/java/software/amazon/awssdk/awscore/client/handler/AwsClientHandlerUtils.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/client/handler/ClientExecutionParams.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/interceptor/SdkExecutionAttribute.java
Adds the operation name of the calling API to the ExecutionContext class. This exposes a way to get the API name from within an ExecutionInterceptor.
Also exposes the `OPERATION_NAME` attribute as an `SdkExecutionAttribute` attribute.
I'm not sure if I've properly documented the feature, I tried to copy what was already existing.
This provides a way to get the operation name from within an `ExecutionInterceptor`. Currently to get the operation name, you have to reflect on the request object and trim `Request` from the name.
I updated the unit tests that check the generated clients and ran mvn install. I do see the protocol tests failing due to a missing JSON file on my local copy of the repo, but that was happening prior to this change as well and is unrelated.
=> feat(core): Adds OperationName to the ExecutionContext class

bom/pom.xml
The artifact for AWS Athena is missing in the BOM.
=> Add Athena artifact to BOM

http-clients/netty-nio-client/src/test/java/software/amazon/awssdk/http/nio/netty/internal/http2/Http2MultiplexedChannelPoolTest.java
Tests behavior that is not being enforced. Forgot to remove from #950
=> Remove unnecessary test

.changes/next-release/bugfix-AmazonS3-98da78b.json, services/s3/src/main/java/software/amazon/awssdk/services/s3/checksums/ChecksumValidatingInputStream.java, services/s3/src/main/java/software/amazon/awssdk/services/s3/checksums/ChecksumValidatingPublisher.java, services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/handlers/AsyncChecksumValidationInterceptor.java, services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/handlers/SyncChecksumValidationInterceptor.java
Fix SyncChecksumValidationInterceptor and AsyncChecksumValidationInter to use `long` for `contentLength`
See #963
=> Fix ChecksumValidationInterceptor to use long for contentLength

.changes/next-release/bugfix-URLConnectionHTTPClient-2357bd0.json, http-clients/url-connection-client/src/main/java/software/amazon/awssdk/http/urlconnection/UrlConnectionHttpClient.java, test/http-client-tests/src/main/java/software/amazon/awssdk/http/SdkHttpClientTestSuite.java
* Also include a Location header if the request is 3xx in SdkHttpClientTestSuite
Always disable following redirects in UrlConnectionHttpClient since SDK handles redirects manually.
Fixes #975 
Fixed unit tests not adding in Location header, which caused software.amazon.awssdk.http.SdkHttpClientTestSuite#supportsResponseCode302 to fail
=> Disable following redirects on UrlConnectionHttpClient

.changes/next-release/feature-AWSSDKforJavav2-7e0d23d.json, core/protocols/aws-cbor-protocol/src/main/java/software/amazon/awssdk/protocols/cbor/AwsCborProtocolFactory.java, core/protocols/aws-json-protocol/src/main/java/software/amazon/awssdk/protocols/json/BaseAwsJsonProtocolFactory.java, core/protocols/aws-json-protocol/src/main/java/software/amazon/awssdk/protocols/json/internal/unmarshall/HeaderUnmarshaller.java, core/protocols/aws-json-protocol/src/main/java/software/amazon/awssdk/protocols/json/internal/unmarshall/JsonProtocolUnmarshaller.java, core/protocols/protocol-core/src/main/java/software/amazon/awssdk/protocols/core/StringToInstant.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/traits/TimestampFormatTrait.java, services/kinesis/src/it/java/software/amazon/awssdk/services/kinesis/KinesisIntegrationTests.java, utils/src/main/java/software/amazon/awssdk/utils/DateUtils.java
Dates were being unmarshalled as epoch seconds for CBOR but it uses epoch millis on the wire.
Date unmarshalling is broken for Kinesis.
Amended existing integ test to assert on date. Failed before change, passes after.
N/A
=> Fixing date unmarshalling for CBOR protocol. See ticket P19810053

.changes/next-release/bugfix-AWSSTS-1b6f264.json, services/sts/src/it/java/software/amazon/awssdk/services/sts/AssumeRoleIntegrationTest.java, services/sts/src/main/java/software/amazon/awssdk/services/sts/internal/StsProfileCredentialsProviderFactory.java
1. Check for a `region` property in the same profile as the `role_arn` definition.
2. Check the default region chain.
3. Fall back to the global endpoint and `us-east-1` signing. Fixes #988.
=> Changed the region resolution logic for role_arn-based profiles.

.changes/next-release/bugfix-AWSSDKforJavav2-70dee34.json, services/s3/src/main/java/software/amazon/awssdk/services/s3/checksums/ChecksumValidatingPublisher.java, services/s3/src/test/java/software/amazon/awssdk/services/s3/checksums/ChecksumValidatingPublisherTest.java
… of incoming data
- fixes issue #965 (https://github.com/aws/aws-sdk-java-v2/issues/965)
- Unit test added
Instead of assuming the checksum will be tacked onto an existing data packet (and incorrectly re-allocating the checksum array), the fixed code simply populates the checksum array with bytes that belong to the checksum, and only sends to the wrapped Subscriber the bytes that belong to the user data
Solves issue #965 
Unit test added that:
- sends a single packet of data
- sends two packets of data with varying boundary (1 and (N-1); 2 and (N-2); 3 and (N-3); ...; (N-1) and 1)
- sends data in tiny packets: 1 byte each; 2 bytes each; ...; 15 bytes each
- checks special behavior for publishers that do not know what is the expected content length (this is a use case from the …
=> ChecksumValidatingPublisher deals with any packetization

buildspecs/better-integ-test.yml, scripts/run-integ-test
Add `better-integ-test` buildspec to only trigger integ tests that are related to the changed files so that we can make integ tests as part of PR process.
- Changes in `core`, `codegen` -> minimal required integ tests (`s3`, `dynamodb`, `sqs`). I chose those three services because they can cover `xml`, `json`, `query` protocols respectively. This is open to discussion. 
- Changes in `netty-nio-client` -> `kinesis`, `s3`, `netty-nio-client`
- Changes in `url-connection-client` -> `url-connection-client`
- Changes in `apache-client` -> `apache-client`, `s3`
- Changes in individual service changes -> integ test in that service module
We can add more complex logic in the future as needed. 
Tested it using CodeBuild and verified the core change in this PR I made triggered the minimal required …
=> Add better-integ-test buildspec 

core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/http/pipeline/stages/HandleResponseStage.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/http/pipeline/stages/MakeAsyncHttpRequestStage.java, core/sdk-core/src/test/java/software/amazon/awssdk/core/http/AmazonHttpClientTest.java, http-clients/apache-client/src/main/java/software/amazon/awssdk/http/apache/ApacheHttpClient.java, http-clients/apache-client/src/main/java/software/amazon/awssdk/http/apache/internal/ApacheHttpRequestConfig.java, http-clients/apache-client/src/test/java/software/amazon/awssdk/http/apache/ApacheHttpClientWireMockTest.java, http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/NettyNioAsyncHttpClient.java, http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/internal/ResponseHandler.java, http-clients/netty-nio-client/src/test/java/software/amazon/awssdk/http/nio/netty/NettyNioAsyncHttpClientWireMockTest.java, http-clients/url-connection-client/src/main/java/software/amazon/awssdk/http/urlconnection/UrlConnectionHttpClient.java, test/protocol-tests/src/test/java/software/amazon/awssdk/protocol/tests/connection/SyncClientConnectionTest.java, test/protocol-tests/src/test/java/software/amazon/awssdk/protocol/tests/exception/AwsJsonExceptionTest.java, test/protocol-tests/src/test/java/software/amazon/awssdk/protocol/tests/exception/Ec2ExceptionTests.java, test/protocol-tests/src/test/java/software/amazon/awssdk/protocol/tests/exception/QueryExceptionTests.java, test/protocol-tests/src/test/java/software/amazon/awssdk/protocol/tests/exception/RestJsonExceptionTests.java, test/protocol-tests/src/test/java/software/amazon/awssdk/protocol/tests/exception/RestXmlExceptionTests.java, test/protocol-tests/src/test/java/software/amazon/awssdk/protocol/tests/util/ClosableStringInputStream.java, test/protocol-tests/src/test/java/software/amazon/awssdk/protocol/tests/util/MockHttpClient.java, test/protocol-tests/src/test/java/software/amazon/awssdk/protocol/tests/util/exception/ExceptionTestUtils.java
Reviewed all use of connection closure and verified the resources are being properly released/closed/shutdown after each request as well as after invoke `client#close`.
This PR added more tests to verify the correctness and did some small code cleanup.
- Sync  path:
Sockets are being closed by closing the underlying `InputStream` via [HandleResponseStage#closeInputStreamIfNeeded](https://github.com/aws/aws-sdk-java-v2/blob/7eb85a23ca9e3df49989d605c60b519828ef1ff1/core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/http/pipeline/stages/HandleResponseStage.java#L62)  unless `needsConnectionLeftOpen` is true (default to false).
For streaming requests, if a customized `ResponseHandler` is provided with `needsConnectionLeftOpen` overriden to true, the underlying connection will …
=> Add more tests to verify connection closure and small code clean up

.changes/next-release/bugfix-AWSSDKforJavav2-6e2fe73.json, core/aws-core/src/main/java/software/amazon/awssdk/awscore/eventstream/EventStreamAsyncResponseTransformer.java, core/aws-core/src/test/java/software/amazon/awssdk/awscore/eventstream/EventStreamAsyncResponseTransformerTest.java, services/kinesis/src/it/java/software/amazon/awssdk/services/kinesis/SubscribeToShardIntegrationTest.java
Fix the deadlock issue in event streaming operations triggered in an edge case where `request` and `onComplete` are signalled at the same time.
Added unit test. `Kinesis` integ tests passed
=> Fix the deadlock issue in event streaming operations

.changes/next-release/bugfix-AWSSDKforJavav2-476c34f.json, http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/internal/ChannelPipelineInitializer.java, http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/internal/UnusedChannelExceptionHandler.java, http-clients/netty-nio-client/src/test/java/software/amazon/awssdk/http/nio/netty/internal/UnusedChannelExceptionHandlerTest.java
Reduced netty client logging noise, by logging at a DEBUG level (instead of WARN) when encountering IO errors on channels not currently in use and not logging the whole stack trace.
Fixes #900 
Fixes #1039
=> Reduced netty client logging noise.

core/aws-core/src/main/java/software/amazon/awssdk/awscore/eventstream/EventStreamAsyncResponseTransformer.java
Move the `isDone` reset to `prepare()` which we guarantee is called before each request attempt.
Code cleanup.
=> Move isDone reset to prepare()

.changes/next-release/bugfix-AWSSDKforJavav2-a03ec88.json, http-client-spi/src/main/java/software/amazon/awssdk/http/SdkHttpClient.java, http-client-spi/src/main/java/software/amazon/awssdk/http/async/SdkAsyncHttpClient.java, http-clients/apache-client/src/main/java/software/amazon/awssdk/http/apache/ApacheHttpClient.java, http-clients/apache-client/src/test/java/software/amazon/awssdk/http/apache/ApacheHttpClientTest.java
This change is up for debate, but it doesn't make much sense that zero defaults are applied when a client is built, and will be prone to cause issues in the future where customers might assume some type of default would be applied, like is true for every other build() method in the SDK.
=> Fix an issue where an exception could be raised when configuring the idle connection reaper in the apache HTTP client.

http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/NettyNioAsyncHttpClient.java, http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/SdkEventLoopGroup.java, http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/internal/ChannelPipelineInitializer.java, http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/internal/FutureCancelHandler.java, http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/internal/http2/Http2SettingsFrameHandler.java, http-clients/netty-nio-client/src/test/java/software/amazon/awssdk/http/nio/netty/internal/MockChannel.java, http-clients/netty-nio-client/src/test/java/software/amazon/awssdk/http/nio/netty/internal/http2/Http2SettingsFrameHandlerTest.java
- Fanout `Http2SettingsFrameHandler`
- Add tests
- Update javadocs
=> Various code clean up on async code

.changes/next-release/bugfix-AWSSDKforJavav2-d33383e.json, .changes/next-release/feature-AWSSDKforJavav2-63c04be.json, .changes/next-release/feature-AWSSDKforJavav2-6c062f1.json, core/auth/src/main/java/software/amazon/awssdk/auth/credentials/DefaultCredentialsProvider.java, core/auth/src/main/java/software/amazon/awssdk/auth/credentials/ProfileCredentialsProvider.java, core/auth/src/main/java/software/amazon/awssdk/auth/credentials/internal/LazyAwsCredentialsProvider.java, core/auth/src/test/java/software/amazon/awssdk/auth/credentials/ProfileCredentialsProviderTest.java, core/auth/src/test/java/software/amazon/awssdk/auth/credentials/internal/LazyAwsCredentialsProviderTest.java, core/aws-core/src/main/java/software/amazon/awssdk/awscore/client/builder/AwsDefaultClientBuilder.java, core/regions/src/main/java/software/amazon/awssdk/regions/providers/LazyAwsRegionProvider.java, core/regions/src/test/java/software/amazon/awssdk/regions/providers/LazyAwsRegionProviderTest.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/client/config/SdkClientConfiguration.java
The default credentials provider chain and region provider chains will no longer be loaded until they are first used. Further, the profile credentials provider will never raise an exception when it is created. The exception won't be raised until it is first used.
Fixes #1030, #1014, #749
=> Make default region and credential loading lazy.

.changes/next-release/bugfix-AWSS3-3112634.json, services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/handlers/AsyncChecksumValidationInterceptor.java, services/s3/src/test/java/software/amazon/awssdk/services/s3/internal/handlers/AsyncChecksumValidationInterceptorTest.java, services/s3/src/test/java/software/amazon/awssdk/services/s3/utils/InterceptorTestUtils.java
The check in `putObjectChecksumEnabled` in [AsyncChecksumValidationInterceptor](https://github.com/aws/aws-sdk-java-v2/blob/a0379920f54cba715773f821ac5d237be8a47985/services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/handlers/AsyncChecksumValidationInterceptor.java#L82) should use request headers, rather than response headers, to determine if the put request is a SSE KMS request. 
Fix for https://github.com/aws/aws-sdk-java-v2/issues/1035 
Added unit tests for `afterUnmarshalling`
=> Fix #1035: Skip Etag validation for upload of KMS encrypted objects 

.changes/next-release/bugfix-NettyNioHTTPClient-6558564.json, build-tools/src/main/java/software/amazon/awssdk/buildtools/checkstyle/PluralEnumNames.java, http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/NettyNioAsyncHttpClient.java, http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/internal/DelegatingEventLoopGroup.java, http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/internal/NettyConfiguration.java, http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/internal/NonManagedEventLoopGroup.java, http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/internal/SharedSdkEventLoopGroup.java, http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/internal/utils/NettyUtils.java, http-clients/netty-nio-client/src/test/java/software/amazon/awssdk/http/nio/netty/NettyNioAsyncHttpClientWireMockTest.java
Awaits `EventLoopGroup#shutdownGracefully` to complete when closing Netty client.
Fun fact: `EventLoopGroup#shutdownGracefully` is also asynchronous.
unit tests and manually triggered smart integ tests.
=> Awaits EventLoopGroup Shutdown when closing Netty client

.changes/next-release/bugfix-AWSSDKforJavav2-dbb2456.json, core/aws-core/src/main/java/software/amazon/awssdk/awscore/eventstream/EventStreamAsyncResponseTransformer.java, core/aws-core/src/main/java/software/amazon/awssdk/awscore/eventstream/EventStreamResponseHandler.java, services/kinesis/src/it/java/software/amazon/awssdk/services/kinesis/SubscribeToShardIntegrationTest.java
Attach `extendedRequestId` to the response metadata for event streaming operations so that customers can retrieve it for debugging from response metadata.
`extendedRequestId` header is only present in `DefaultHttp2Headers` and not the event messages.
When we firstly receive `DefaultHttp2Headers`, `EventStreamAsyncResponseTransformer#onResponse` is being invoked and we retrieve the extendedRequestId from the header and store it.
https://github.com/aws/aws-sdk-java-v2/blob/6464a2d2105da423300180bd9cb9b9062f10e57a/core/aws-core/src/main/java/software/amazon/awssdk/awscore/eventstream/EventStreamAsyncResponseTransformer.java#L193-L201
Once we receive the event, we need to attach it to the response in `adaptMessageToResponse` https://github.com/aws/aws-sdk-java-v2/pull/1079/files#diff-41f82e2c7 …
=> Attach extendedRequestId for event streaming operations

core/aws-core/src/main/java/software/amazon/awssdk/awscore/client/handler/AwsClientHandlerUtils.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/client/handler/BaseAsyncClientHandler.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/client/handler/BaseClientHandler.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/interceptor/ExecutionInterceptorChain.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/http/async/AsyncAfterTransmissionInterceptorCallingResponseHandler.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/http/async/AsyncResponseHandler.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/http/async/AsyncStreamingResponseHandler.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/http/pipeline/stages/AsyncRetryableStage.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/http/pipeline/stages/MakeAsyncHttpRequestStage.java
Code clean up in SDK/AWS Core Interop with async client for streaming and non-streaming operations.
- Moved inner classes in `BaseAsyncClientHandler` to separate classes
- `UnmarshallingSdkHttpResponseHandler`  -> `AsyncStreamingResponseHandler`
- `InterceptorCallingHttpResponseHandler` -> `AsyncAfterTransmissionInterceptorCallingResponseHandler`
- Renamed `SyncResponseHandlerAdapter` to `AsyncResponseHandler`
- Unified streaming and non-streaming methods in `BaseAsyncClientHandler#`
- Renamed method, added javadoc and comment to make it more clear
- Moved clockskew adjustment before retry check
- Fixed awkward logging `retryiesAttempt:-1`
- Renamed variables of completeFuture, added javadoc.
Unit tests. ~~Will run whole integ tests suite.~~ Integration tests passed
=> Clean up core async code path

.changes/next-release/bugfix-AmazonS3-241dcc9.json, services/s3/src/it/java/software/amazon/awssdk/services/s3/ExceptionUnmarshallingIntegrationTest.java, services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/handlers/GetBucketPolicyInterceptor.java, services/s3/src/test/java/software/amazon/awssdk/services/s3/internal/handlers/GetBucketPolicyInterceptorTest.java, services/s3/src/test/java/software/amazon/awssdk/services/s3/utils/InterceptorTestUtils.java
Fixed the issue where `NoSuchBucketException` is not unmarshalled correctly for `s3#getBucketPolicy`
Fix #1088 
Added unit tests and integ test.
=> Fixed the issue where NoSuchBucketException is not unmarshalled

.changes/next-release/bugfix-AWSSDKforJavav2-92cb879.json, core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/http/pipeline/stages/MakeAsyncHttpRequestStage.java, services/transcribestreaming/src/it/java/software/amazon/awssdk/services/transcribestreaming/TranscribeStreamingIntegrationTest.java
Fix contentLength check
Fix #1099
transcribestreaming integ test
=> Fix contentLength check

.changes/next-release/bugfix-AWSSDKForJavav2-0076c08.json, .changes/next-release/bugfix-NettyNIOHTTPClient-1969be2.json, codegen/src/main/java/software/amazon/awssdk/codegen/poet/client/specs/JsonProtocolSpec.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/test-async-client-class.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/test-endpoint-discovery-async.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/client/handler/BaseAsyncClientHandler.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/http/pipeline/RequestPipelineBuilder.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/http/pipeline/stages/AsyncApiCallTimeoutTrackingStage.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/http/pipeline/stages/AsyncExecutionFailureExceptionReportingStage.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/http/pipeline/stages/AsyncRetryableStage.java, http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/NettyNioAsyncHttpClient.java, http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/internal/CancellableAcquireChannelPool.java, http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/internal/NettyRequestExecutor.java, http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/internal/RequestContext.java, http-clients/netty-nio-client/src/test/java/software/amazon/awssdk/http/nio/netty/internal/CancellableAcquireChannelPoolTest.java, http-clients/netty-nio-client/src/test/java/software/amazon/awssdk/http/nio/netty/internal/FutureCancelHandlerTest.java, http-clients/netty-nio-client/src/test/java/software/amazon/awssdk/http/nio/netty/internal/NettyRequestExecutorTest.java, test/codegen-generated-classes-test/pom.xml, test/codegen-generated-classes-test/src/main/resources/codegen-resources/query/service-2.json, test/codegen-generated-classes-test/src/main/resources/codegen-resources/xml/service-2.json, test/codegen-generated-classes-test/src/test/java/software/amazon/awssdk/services/protocolquery/AsyncOperationCancelTest.java, test/codegen-generated-classes-test/src/test/java/software/amazon/awssdk/services/protocolrestjson/AsyncOperationCancelTest.java, test/codegen-generated-classes-test/src/test/java/software/amazon/awssdk/services/protocolrestxml/AsyncOperationCancelTest.java, utils/src/main/java/software/amazon/awssdk/utils/CompletableFutureUtils.java, utils/src/test/java/software/amazon/awssdk/utils/CompletableFutureUtilsTest.java
- Correctly pass along the cancelled signal down to the async client if the
future returned for an async operation is cancelled.
- Don't wait for acquire to finish to cancel; instead fail the promise if not
complete yet
CancellableAcquireChannelPool added to take care of closing and releasing a
cancelled acquire.
Bug fix.
Added/updated tests in `codegen`, `codegen-generated-classes-test`, and `netty-nio-client`.
=> Fix async request cancellation

.changes/next-release/bugfix-NettyNIOHTTPClient-2e50373.json, http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/NettyNioAsyncHttpClient.java, http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/internal/http2/HttpOrHttp2ChannelPool.java, http-clients/netty-nio-client/src/test/java/software/amazon/awssdk/http/nio/netty/internal/http2/HttpOrHttp2ChannelPoolTest.java
The access to protocolImpl#close() could happen before it's assigned to, leading
to a NullPointerException.
Also, `protocolImpl` is not volatile or accessed in a threadafe manner, so
it's possible the thread calling `HttpOrHttp2ChannelPool#close` has a stale value.
Bug fix.
=> Fix possible NPE in HttpOrHttp2ChannelPool

.changes/next-release/bugfix-AWSSDKforJavav2-f8f1130.json, core/protocols/aws-xml-protocol/src/main/java/software/amazon/awssdk/protocols/xml/internal/unmarshall/HeaderUnmarshaller.java, services/s3/src/it/java/software/amazon/awssdk/services/s3/UserMetadataIntegrationTest.java, services/s3/src/test/java/software/amazon/awssdk/services/s3/internal/handlers/PutObjectHeaderTest.java, test/protocol-tests-core/src/main/resources/software/amazon/awssdk/protocol/suites/cases/rest-xml-output.json, test/protocol-tests/src/main/resources/codegen-resources/restxml/service-2.json, utils/src/main/java/software/amazon/awssdk/utils/StringUtils.java, utils/src/test/java/software/amazon/awssdk/utils/StringUtilsTest.java
Fix xml `HeaderUnmarshaller#MAP` to compare headers ignoring cases. Checked Json HeaderUnmarshaller and it doesn't have MAP type.
Fixes #1091 
Added unit tests and integ tests
=> Fix HeaderUnmarshaller to compare headers ignoring cases

services/s3/src/it/java/software/amazon/awssdk/services/s3/BucketAccelerateIntegrationTest.java, services/s3/src/it/java/software/amazon/awssdk/services/s3/UploadLargeObjectIntegrationTest.java
Fixed TemplateIntegrationTest by moving resources in #1103 
Modified BucketAccelerateIntegrationTest to verify that we can enable/disable accelerate and that other operations use the accelerate endpoint.
Removed ignore annotation from UploadLargeObjectIntegrationTest. This test takes about 3 minutes to run from my desktop. Should presumably be faster in CodeBuild since it will be uploading to S3 within region. Don't think it's an issue to just run this test always.
=> More integration tests cleanup

docs/design/services/s3/transfermanager/README.md
Initial goals/tenets document for S3 TransferManager. Feedback requested!
=> [Discussion] Add initial design tenets/goals for S3 TransferManager

build-tools/pom.xml, build-tools/src/main/java/software/amazon/awssdk/buildtools/checkstyle/MissingSdkAnnotationCheck.java, build-tools/src/main/java/software/amazon/awssdk/buildtools/checkstyle/SdkPublicMethodNameCheck.java, build-tools/src/main/java/software/amazon/awssdk/buildtools/checkstyle/UnnecessaryFinalOnLocalVariableCheck.java, build-tools/src/main/resources/software/amazon/awssdk/checkstyle.xml, core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/http/pipeline/stages/ApiCallAttemptTimeoutTrackingStage.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/http/pipeline/stages/ApiCallTimeoutTrackingStage.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/http/pipeline/stages/MakeAsyncHttpRequestStage.java, pom.xml
Upgrade checkstyle version per https://nvd.nist.gov/vuln/detail/CVE-2019-9658
~~Hopefully it still builds~~
Had to remove a bunch of broken checkstyles.
=> Upgrade checkstyle version

docs/LaunchChangelog.md
Used links (unlike other entries) as the replacement APIs are not in the low-level client
=> Update 1.11.x to 2.0 changelog to include S3 getUrl API

.changes/next-release/bugfix-AmazonS3-7601ea5.json, services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/handlers/CreateMultipartUploadRequestInterceptor.java, services/s3/src/test/java/software/amazon/awssdk/services/s3/MultipartUploadTest.java, services/s3/src/test/java/software/amazon/awssdk/services/s3/internal/handlers/CreateMultipartUploadRequestInterceptorTest.java, services/s3/src/test/java/software/amazon/awssdk/services/s3/utils/InterceptorTestUtils.java
We should honor request overriden content type for S3 createMultipartUpload request and only set default content type if it's absent.
Added unit test
=> Honor request overriden content type for S3 createMultipartUpload req

.changes/next-release/feature-AWSSDKforJavav2-caed172.json, core/auth/src/test/java/software/amazon/awssdk/auth/credentials/ContainerCredentialsProviderTest.java, core/auth/src/test/java/software/amazon/awssdk/auth/credentials/HttpCredentialsProviderTest.java, core/regions/src/main/java/software/amazon/awssdk/regions/util/ResourcesEndpointProvider.java, core/regions/src/test/java/software/amazon/awssdk/regions/util/HttpCredentialsUtilsTest.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/util/UserAgentUtils.java, core/sdk-core/src/test/java/software/amazon/awssdk/core/internal/util/UserAgentUtilsTest.java, utils/src/main/java/software/amazon/awssdk/utils/JavaSystemSetting.java
Adds Java vendor to the user agent:
aws-sdk-java/2.5.1-SNAPSHOT Mac_OS_X/10.12.6 Java_HotSpot_TM__64-Bit_Server_VM/25.202-b08 Java/1.8.0_202 vendor/Oracle_Corporation
aws-sdk-java/2.5.1-SNAPSHOT Mac_OS_X/10.12.6 OpenJDK_64-Bit_Server_VM/25.202-b08 Java/1.8.0_202 vendor/Amazon.com_Inc.
Updated/added tests
=> Adding Java vendor to user agent and using it everywhere

core/sdk-core/src/main/java/software/amazon/awssdk/core/SdkBytes.java
Fixed param validation. See issue #1145.
In line 80 of SdkBytes.java there is a param validation that does not correspond to the actual param to validate. As of seen in version 2.5.10
=> Bugfix #1145

README.md
Add maven commands in README so that customers are aware that they can skip tests and not blocked for failed tests.
=> Add maven commands in README

.changes/next-release/bugfix-AmazonCloudSearchDomain-dbd5983.json, services/cloudsearchdomain/src/main/java/software/amazon/awssdk/services/cloudsearchdomain/internal/SwitchToPostInterceptor.java, services/cloudsearchdomain/src/test/java/software/amazon/awssdk/cloudsearchdomain/SearchRequestUnitTest.java
Fixes #1151 
* Use application/x-www-form-urlencoded content type for search api in CloudSearch Domain service. 
* Verified locally that actual API call works
=> Fix for #1151

.changes/next-release/bugfix-URLConnectionHttpClient-8ae3a85.json, http-clients/url-connection-client/src/main/java/software/amazon/awssdk/http/urlconnection/UrlConnectionHttpClient.java, http-clients/url-connection-client/src/test/java/software/amazon/awssdk/http/urlconnection/UrlConnectionHttpClientWireMockTest.java
Bypass SSL validation when `TRUST_ALL_CERTIFICATES` is set to true in `UrlConnectionHttpClient`
fix #1163 
=> Bypass SSL validation when TRUST_ALL_CERTIFICATES is set to true

.changes/next-release/bugfix-NettyNIOHTTPClient-99565b4.json, http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/NettyNioAsyncHttpClient.java, http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/internal/ChannelPipelineInitializer.java, services/pinpoint/src/it/java/software/amazon/awssdk/services/pinpoint/PinpointIntegTest.java
Fix a bug where SNI was not enabled in Netty NIO Async Client for TLS and caused the requests to fail of handshake_failure in some services.
See #1171 
Added integ tests.
~~Running the whole integ tests suites now.~~ All integ tests passed
=> Fix SslHandler in Netty client

.changes/next-release/bugfix-AWSSDKforJavav2-03971fc.json, core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/http/pipeline/stages/AsyncApiCallTimeoutTrackingStage.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/http/pipeline/stages/MakeAsyncHttpRequestStage.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/http/timers/AsyncTimeoutTask.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/http/timers/TimerUtils.java
Delay the creation of `ApiCallTimeoutException` and `ApiCallAttemptTimeoutException` as they are not necessary and costly to create. This would improve performance in async path.
Benchmark comparison (throughput ops/s)
Benchmark  |  before | after |     
------------ | -------------  | -----------                              
NettyClientH1NonTlsBenchmark.concurrentApiCall  |  7119 | 8453
NettyClientH1NonTlsBenchmark.sequentialApiCall |  2303 | 2393
NettyHttpClientH1Benchmark.concurrentApiCall (jdk) |  6390 | 7260
NettyHttpClientH1Benchmark.sequentialApiCall (jdk) |  1775 |  1827
NettyHttpClientH2Benchmark.concurrentApiCall (jdk) | 4513 | 4655
NettyHttpClientH2Benchmark.sequentialApiCall (jdk) | 1687 | 1723
=> Lazily initializing exceptions

.changes/next-release/bugfix-AWSSDKforJavav2-0d76926.json, http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/NettyNioAsyncHttpClient.java, http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/internal/HealthCheckedChannelPool.java, http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/internal/NettyRequestExecutor.java, http-clients/netty-nio-client/src/test/java/software/amazon/awssdk/http/nio/netty/internal/HealthCheckedChannelPoolTest.java
If a service closes a connection between when a channel is acquired and handlers are attached, channel writes could disappear and the response future would never be completed. This change introduces health checks and retries for channel acquisition to fix the majority of cases without failing requests, as well as one last check after handlers are added to ensure the channel hasn't been closed since the channel pool health check. Fixes #1207.
=> Fixed a bug in the netty client, where a future may not always be completed.

.changes/next-release/feature-AWSSDKforJavav2-914cded.json, core/sdk-core/src/main/java/software/amazon/awssdk/core/BytesWrapper.java
=> Make `BytesWrapper`, parent of `SdkBytes` and `ResponseBytes`, public.

.changes/next-release/feature-AWSSDKforJavav2-d140ae2.json, core/auth/src/main/java/software/amazon/awssdk/auth/credentials/internal/CredentialSourceType.java, core/auth/src/main/java/software/amazon/awssdk/auth/credentials/internal/ProfileCredentialsUtils.java, core/auth/src/test/java/software/amazon/awssdk/auth/credentials/internal/ProfileCredentialsUtilsTest.java, core/profiles/src/main/java/software/amazon/awssdk/profiles/ProfileProperty.java, services/sts/src/it/java/software/amazon/awssdk/services/sts/AssumeRoleIntegrationTest.java
This pull request adds support for the `credential_source` property in profile files.
See [AWS CLI documentation](https://docs.aws.amazon.com/cli/latest/topic/config-vars.html#using-aws-iam-roles) for the same feature on AWS CLI.
Changed profile file parsing to understand the `credential_source` property.
If `credential_source` is `Environment`, the SDK looks at both environment variables and system in that order.
I expect the profile `credential_source` to work similarly to the AWS CLI. See also feature request #1169.
There is an integration test under STS integration tests. Code changes are in profile/auth.
=> Add support for credential_source property on profile

.changes/next-release/bugfix-NettyNIOAsyncHttpClient-91fa618.json, http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/NettyNioAsyncHttpClient.java, http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/internal/AwaitCloseChannelPoolMap.java, http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/internal/BetterSimpleChannelPool.java, http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/internal/NettyConfiguration.java, http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/internal/SdkChannelPoolMap.java, http-clients/netty-nio-client/src/test/java/software/amazon/awssdk/http/nio/netty/NettyNioAsyncHttpClientWireMockTest.java, http-clients/netty-nio-client/src/test/java/software/amazon/awssdk/http/nio/netty/internal/AwaitCloseChannelPoolMapTest.java
Update `NettyNioAsyncHttpClient#close` to wait for `pools#close` before shutting down eventloop
The root cause is a race condition in Netty where the event loop gets terminated before channel is closed so `globalEventExecutor` will be stuck forever waiting for eventloop to notify the `channel.close` future.
```
"globalEventExecutor-1-1" #62 prio=5 os_prio=31 tid=0x00007ff34abb8800 nid=0x8c0b in Object.wait() [0x0000700003023000]
java.lang.Thread.State: WAITING (on object monitor)
at java.lang.Object.wait(Native Method)
- waiting on <0x000000076b1b6a30> (a io.netty.channel.DefaultChannelPromise)
at java.lang.Object.wait(Object.java:502)
at io.netty.util.concurrent.DefaultPromise.awaitUninterruptibly(DefaultPromise.java:253)
- locked <0x000000076b1b6a30> (a …
```
=> Workaround to fix eventloop.shutdownGracefully hanging issue

services/transcribestreaming/src/it/java/software/amazon/awssdk/services/transcribestreaming/TestResponseHandlers.java, services/transcribestreaming/src/it/java/software/amazon/awssdk/services/transcribestreaming/TestSubscription.java, services/transcribestreaming/src/it/java/software/amazon/awssdk/services/transcribestreaming/TranscribeStreamingIntegrationTest.java, utils/src/main/java/software/amazon/awssdk/utils/async/BufferingSubscriber.java, utils/src/main/java/software/amazon/awssdk/utils/async/FlatteningSubscriber.java, utils/src/test/java/software/amazon/awssdk/utils/async/BufferingSubscriberTest.java
**Bugs**
* BufferingSubscriber doesn't request data when current size is less than buffer size. So the application sits idle until ReadTimeoutException is thrown
* FlatteningSubscriber decrements the demand even when buffer is empty
* FlatteningSubscriber was bit complex to add unit test, so updated an integ test to use the response handler variant that was reported in the original issue (internal)
=> Fix bugs in BufferingSubscriber and FlatteningSubscriber

.changes/next-release/bugfix-AWSSDKforJavav2-f0e1099.json, core/auth/src/main/java/software/amazon/awssdk/auth/signer/AwsS3V4Signer.java, core/auth/src/main/java/software/amazon/awssdk/auth/signer/internal/AbstractAws4Signer.java, core/auth/src/main/java/software/amazon/awssdk/auth/signer/internal/Aws4SignerRequestParams.java, core/auth/src/main/java/software/amazon/awssdk/auth/signer/internal/Aws4SignerUtils.java, core/auth/src/main/java/software/amazon/awssdk/auth/signer/internal/BaseEventStreamAsyncAws4Signer.java, core/auth/src/test/java/software/amazon/awssdk/auth/signer/Aws4EventStreamSignerTest.java, core/auth/src/test/java/software/amazon/awssdk/auth/signer/internal/Aws4SignerRequestParamsTest.java
Events should be signed with the current time (as provided by the Clock), not
the initial request time.
Updated unit test, ran `TranscribeStreamingIntegrationTest` to verify against service.
=> Sign events with current signing Clock time

codegen/src/main/java/software/amazon/awssdk/codegen/AddOperations.java, codegen/src/main/java/software/amazon/awssdk/codegen/AddShapes.java, codegen/src/main/java/software/amazon/awssdk/codegen/model/intermediate/OperationModel.java, codegen/src/main/java/software/amazon/awssdk/codegen/model/intermediate/ParameterHttpMapping.java, codegen/src/main/java/software/amazon/awssdk/codegen/model/intermediate/ShapeModel.java, codegen/src/main/java/software/amazon/awssdk/codegen/model/service/Member.java, codegen/src/main/java/software/amazon/awssdk/codegen/model/service/Shape.java, codegen/src/main/java/software/amazon/awssdk/codegen/poet/client/SyncClientClass.java, codegen/src/main/java/software/amazon/awssdk/codegen/poet/client/specs/Ec2ProtocolSpec.java, codegen/src/main/java/software/amazon/awssdk/codegen/poet/client/specs/JsonProtocolSpec.java, codegen/src/main/java/software/amazon/awssdk/codegen/poet/client/specs/ProtocolSpec.java, codegen/src/main/java/software/amazon/awssdk/codegen/poet/client/specs/QueryProtocolSpec.java, codegen/src/main/java/software/amazon/awssdk/codegen/poet/client/specs/XmlProtocolSpec.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/test-async-client-class.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/test-json-client-class.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/interceptor/ExecutionInterceptorChain.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/transform/AbstractStreamingRequestMarshaller.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/runtime/transform/AsyncStreamingRequestMarshaller.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/runtime/transform/StreamingRequestMarshaller.java, core/sdk-core/src/test/java/software/amazon/awssdk/core/runtime/transform/AsyncStreamingRequestMarshallerTest.java, core/sdk-core/src/test/java/software/amazon/awssdk/core/runtime/transform/SyncStreamingRequestMarshallerTest.java, http-client-spi/src/main/java/software/amazon/awssdk/http/Header.java, services/mediastoredata/pom.xml, services/mediastoredata/src/it/java/software/amazon/awssdk/services/mediastoredata/MediaStoreDataIntegrationTest.java, services/mediastoredata/src/it/resources/log4j.properties, test/protocol-tests-core/src/main/resources/software/amazon/awssdk/protocol/suites/cases/query-input.json, test/protocol-tests-core/src/main/resources/software/amazon/awssdk/protocol/suites/cases/rest-json-input.json, test/protocol-tests/src/main/resources/codegen-resources/query/service-2.json, test/protocol-tests/src/main/resources/codegen-resources/restjson/service-2.json, test/protocol-tests/src/test/java/software/amazon/awssdk/protocol/tests/ExecutionInterceptorTest.java
~~**This is a draft. Ignore any missing tests, formatting issues**~~
PR is ready for review.
* Support requiresLength trait for streaming payloads. 
* Set request headers based on requiresLength and authType trait
* Core logic is in `StreamingRequestMarshaller` and `AsyncStreamingRequestMarshaller`
**Header resolution logic:** 
-  If content-length is present, always use Content-Length header
- If content-length is not present:
- If `requiresLength` is present, throw an exception to fail-fast and let user know Content-Length is required. This can only happen for async requests when custom publisher is used. Based on our team discussion, we didn't want to compute the Content-Length in this case to avoid complexity of wrapping publisher and computing content-length
- If `transferEncoding` …
=> Support requiresLength trait for streaming payloads. 

pom.xml
Increase javadoc max memory config, fixing `javadoc: error - java.lang.OutOfMemoryError: Please increase memory.`
=> Increase javadoc max memory config

.changes/next-release/bugfix-AWSSDKforJavav2-4d27b93.json, core/aws-core/src/main/java/software/amazon/awssdk/awscore/eventstream/EventStreamAsyncResponseTransformer.java, core/aws-core/src/test/java/software/amazon/awssdk/awscore/eventstream/EventStreamAsyncResponseTransformerTest.java
Fix a bug in EventStreamAsyncResponseTransformer where the subscriber ref is not
reset between calls to prepare(), causing retries to fail when the
EventStreamResponseHandler attempts to subscribe to a new stream on a request
retry.
New unit test.
=> Reset subscriberRef in prepare

.changes/next-release/bugfix-AmazonS3-31779a7.json, services/s3/src/main/resources/codegen-resources/customization.config
Modify the types of `ObjectVersion#Size` and `Part#Size` from Integer to Long.
`S3Object`, `ObjectVersion` and `Part` are the only shapes using `Size`.
Related to #1299
=> Modify the types of ObjectVersion#Size and Part#Size

.changes/next-release/bugfix-ApacheHttpClient-d9de03d.json, .changes/next-release/feature-AWSSDKforJavav2-f344377.json, http-clients/apache-client/src/main/java/software/amazon/awssdk/http/apache/internal/impl/ApacheHttpRequestFactory.java, http-clients/apache-client/src/main/java/software/amazon/awssdk/http/apache/internal/utils/ApacheUtils.java, pom.xml, services/s3/src/it/java/software/amazon/awssdk/services/s3/S3ListObjectsV2IntegrationTest.java
* Disable Apache normalization to handle breaking change introduced in v4.5.7
* Update `httpcomponents.httpclient.version` to `4.5.9`
See https://github.com/aws/aws-sdk-java/issues/1919 for more details.
=> Disable Apache normalization

buildspecs/release-to-maven.yml
Update release-to-maven to exclude stability-tests module
=> Update release-to-maven to exclude stability-tests module

pom.xml, test/stability-tests/src/it/java/software/amazon/awssdk/stability/tests/exceptions/StabilityTestsRetryableException.java, test/stability-tests/src/it/java/software/amazon/awssdk/stability/tests/kinesis/KinesisStabilityTest.java, test/stability-tests/src/it/java/software/amazon/awssdk/stability/tests/s3/S3AsyncStabilityTest.java, test/stability-tests/src/it/java/software/amazon/awssdk/stability/tests/sqs/SqsAsyncStabilityTest.java, test/stability-tests/src/it/java/software/amazon/awssdk/stability/tests/transcribestreaming/TranscribeStreamingStabilityTest.java, test/stability-tests/src/it/java/software/amazon/awssdk/stability/tests/utils/RetryableTest.java, test/stability-tests/src/it/java/software/amazon/awssdk/stability/tests/utils/RetryableTestExtension.java, test/stability-tests/src/it/java/software/amazon/awssdk/stability/tests/utils/StabilityTestRunner.java
- Make kinesis stability tests more reliable by increasing the waiter time and decreasing consumer count
- Create `@RetriableTest` annotation to automatically retry test if failing of certain exception
=> Make kinsis stability tests more reliable

.changes/next-release/bugfix-NettyNIOHTTPClient-0780cf4.json, http-clients/netty-nio-client/pom.xml, http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/internal/ResponseHandler.java, http-clients/netty-nio-client/src/test/java/software/amazon/awssdk/http/nio/netty/internal/PublisherAdapterTest.java, test/stability-tests/src/it/java/software/amazon/awssdk/stability/tests/s3/S3AsyncStabilityTest.java, test/stability-tests/src/it/java/software/amazon/awssdk/stability/tests/s3/S3BaseStabilityTest.java, test/stability-tests/src/it/java/software/amazon/awssdk/stability/tests/utils/StabilityTestRunner.java
Fix the issue where the sdk can invoke channel#read twice per request demand. When the subscriber invokes `subscription#request`, the underlying `HandlerPublisher` would trigger `ChannelHandlerContext#read`; the SDK was invoking `ChannelHandlerContext#read` again in `PublisherAdapter#onNext`. 
This would be an issue with "slow" subscriber such as `FileAsyncResponseTransformer` and cause unnecessary message buffering.
See #1122 
Added stability tests. (verified the test failed before the fix and succeeded after the fix.)
Tested downloading a 2g object on an instance with NVMe local storage.
=> Fix the issue where the sdk can invoke channel#read twice per request demand

test/stability-tests/README.md, test/stability-tests/pom.xml, test/stability-tests/src/it/assembly/assembly.xml, test/stability-tests/src/it/java/software/amazon/awssdk/stability/tests/TestRunner.java, test/stability-tests/src/it/java/software/amazon/awssdk/stability/tests/kinesis/KinesisStabilityTest.java, test/stability-tests/src/it/java/software/amazon/awssdk/stability/tests/s3/S3AsyncStabilityTest.java, test/stability-tests/src/it/java/software/amazon/awssdk/stability/tests/s3/S3BaseStabilityTest.java
- Add new profile to build tests jar in stability-tests module to make it easier to run tests on a remote instance.
- Kinesis tests: Only verify data if all events have been received.
-  S3 tests: create bucket and object instead of reusing existing one.
Some issue can only be reproduced when running on a larger ec2 instance, and this will be handy to generate the tests jar and run the tests there.
=> Add new profile to build tests jar in stability-tests module

.changes/next-release/bugfix-AWSSDKforJavav2-95ddbd0.json, codegen/src/main/java/software/amazon/awssdk/codegen/poet/client/specs/JsonProtocolSpec.java, codegen/src/main/java/software/amazon/awssdk/codegen/poet/client/specs/ProtocolSpec.java, codegen/src/main/java/software/amazon/awssdk/codegen/poet/client/specs/QueryProtocolSpec.java, codegen/src/test/java/software/amazon/awssdk/codegen/poet/client/PoetClientFunctionalTests.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/c2j/query/service-2.json, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/test-async-client-class.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/test-query-async-client-class.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/test-query-client-class.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/async/AsyncResponseTransformer.java, services/s3/src/it/java/software/amazon/awssdk/services/s3/AsyncGetObjectFaultIntegrationTest.java, test/protocol-tests/src/main/resources/codegen-resources/query/service-2.json, test/protocol-tests/src/test/java/software/amazon/awssdk/protocol/tests/AsyncResponseTransformerTest.java
Generating code to notify error for streaming operations.
```
executeFuture.whenComplete((r, e) -> {
if (e != null) {
runAndLogError(log, "Exception thrown in exceptionOccurred callback, ignoring",
() -> asyncResponseTransformer.exceptionOccurred(e));
}
});
```
Per docs,
https://github.com/aws/aws-sdk-java-v2/blob/5a799393ce9f34b07625ca5d614e5f6367ec7780/core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/http/pipeline/stages/AsyncRetryableStage.java#L167-L170
we should invoke `AsyncResponseTransformer#exceptionOccurred` in the generated client code; we were only generating the code in json services previously, so the fix is to add the generated code for xml services.
added codegen tests, unit tests, integ tests.
=> Generate code to notify error for streaming operations

services/sts/src/main/java/software/amazon/awssdk/services/sts/internal/StsWebIdentityCredentialsProviderFactory.java
Fixes travis build failure from #1320 by default to the STS global endpoint if one isn't available via the chain.
This matches the other STS provider.
=> Defaulting to STS global if necessary

codegen-lite-maven-plugin/pom.xml, codegen-maven-plugin/pom.xml, core/aws-core/pom.xml, core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/async/ByteArrayAsyncRequestBody.java, core/sdk-core/src/test/java/software/amazon/awssdk/core/client/AsyncClientHandlerExceptionTest.java, core/sdk-core/src/test/java/software/amazon/awssdk/core/client/AsyncClientHandlerInterceptorExceptionTest.java, core/sdk-core/src/test/java/software/amazon/awssdk/core/client/handler/AsyncClientHandlerTransformerVerificationTest.java, http-client-spi/src/main/java/software/amazon/awssdk/http/SdkHttpConfigurationOption.java, http-clients/java-nio-client/pom.xml, http-clients/java-nio-client/src/main/java/software/amazon/awssdk/http/nio/java/JavaHttpClientNioAsyncHttpClient.java, http-clients/java-nio-client/src/main/java/software/amazon/awssdk/http/nio/java/JavaSdkAsyncHttpService.java, http-clients/java-nio-client/src/main/java/software/amazon/awssdk/http/nio/java/internal/JavaHttpClientConfiguration.java, http-clients/java-nio-client/src/main/java/software/amazon/awssdk/http/nio/java/internal/JavaHttpRequestExecutor.java, http-clients/java-nio-client/src/main/java/software/amazon/awssdk/http/nio/java/internal/JavaHttpRequestFactory.java, http-clients/java-nio-client/src/main/java/software/amazon/awssdk/http/nio/java/internal/JavaHttpResponseBodyHandler.java, http-clients/java-nio-client/src/main/java/software/amazon/awssdk/http/nio/java/internal/ListToByteBufferProcessor.java, http-clients/java-nio-client/src/test/java/software/amazon/awssdk/http/nio/java/JavaHttpClientNioAsyncHttpClientWireMockTest.java, http-clients/java-nio-client/src/test/java/software/amazon/awssdk/http/nio/java/RecordingResponseHandler.java, http-clients/java-nio-client/src/test/java/software/amazon/awssdk/http/nio/java/internal/JavaHttpRequestExecutorTest.java, http-clients/java-nio-client/src/test/java/software/amazon/awssdk/http/nio/java/internal/JavaHttpResponseBodyHandlerTest.java, http-clients/java-nio-client/src/test/java/software/amazon/awssdk/http/nio/java/internal/ListToByteBufferProcessorTest.java, http-clients/java-nio-client/src/test/java/software/amazon/awssdk/http/nio/java/internal/S3JavaHttpClientIntegratedTest.java, http-clients/java-nio-client/src/test/resources/jetty-logging.properties, http-clients/java-nio-client/src/test/resources/log4j.properties, http-clients/netty-nio-client/src/test/java/software/amazon/awssdk/http/nio/netty/internal/CancellableAcquireChannelPoolTest.java, http-clients/netty-nio-client/src/test/java/software/amazon/awssdk/http/nio/netty/internal/HealthCheckedChannelPoolTest.java, http-clients/netty-nio-client/src/test/java/software/amazon/awssdk/http/nio/netty/internal/NettyRequestExecutorTest.java, pom.xml
First of all, the name of JavaNioAsyncHttpClient has been changed into JavaHttoClientNioAsyncHttpClient.
Then in this pull request, unit tests and functional tests to the basic version of JavaHttpClientNioAsyncHttpClient implementation were added, through which the methods and integrated functionality of the basic implementation are tested. And a new class named JavaHttpResponseBodyHandler is added.
New features(configurations) are added, including: connectionTimeout, protocol, configureSsl and responseTimeout. Tests for these configurations are also added.
A new class named JavaHttpResponseBodyHandler is added, in this class the BodyHandler of the JavaHttpClientNioAsyncHttpClient is defined based on the HttpResponse.BodyHandler provided by Jdk 11. And descriptions related to the tests …
=> Added tests to the new JavaHttpClientNioAsyncHttpClient and Implemented new configurations

.changes/next-release/bugfix-AWSSDKforJavav2-05caf1d.json, codegen/src/main/java/software/amazon/awssdk/codegen/poet/eventstream/EventStreamUtils.java, codegen/src/main/java/software/amazon/awssdk/codegen/poet/transform/protocols/EventStreamJsonMarshallerSpec.java, codegen/src/main/java/software/amazon/awssdk/codegen/poet/transform/protocols/JsonMarshallerSpec.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/transform/eventonemarshaller.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/transform/eventstreamoperationrequestmarshaller.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/transform/eventstreamoperationwithonlyinputrequestmarshaller.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/transform/eventthreemarshaller.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/transform/eventtwomarshaller.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/transform/inputeventmarshaller.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/transform/inputeventtwomarshaller.java, core/protocols/aws-json-protocol/src/main/java/software/amazon/awssdk/protocols/json/internal/marshall/JsonProtocolMarshaller.java, core/protocols/protocol-core/src/main/java/software/amazon/awssdk/protocols/core/OperationInfo.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/util/Mimetype.java, services/transcribestreaming/src/it/java/software/amazon/awssdk/services/transcribestreaming/TranscribeStreamingIntegrationTest.java
Setting `Content-Type` to `application/vnd.amazon.eventstream` for APIs accepting input event streams.
Added unit tests and integ tests
=> Set correct Content-Type for APIs support input event streams.

services-custom/s3-transfermanager/src/main/java/software/amazon/awssdk/custom/s3/transfer/internal/MultiPartUploadManager.java, services-custom/s3-transfermanager/src/main/java/software/amazon/awssdk/custom/s3/transfer/internal/RequestConversionUtils.java, services-custom/s3-transfermanager/src/test/java/software/amazon/awssdk/custom/s3/transfer/internal/UploadManagerTest.java
Remove ListPartRequest when cleaning up resources for multipart upload.
`listParts` after `abortMultipart` will actually throw exception.
unit tests
=> Remove ListPartRequest when cleaning up resources for multipart upload

.changes/next-release/feature-NettyNIOHTTPClient-8d0be28.json, http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/NettyNioAsyncHttpClient.java, http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/ProxyConfiguration.java, http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/internal/AwaitCloseChannelPoolMap.java, http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/internal/Http1TunnelConnectionPool.java, http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/internal/ProxyTunnelInitHandler.java, http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/internal/SimpleChannelPoolAwareChannelPool.java, http-clients/netty-nio-client/src/test/java/software/amazon/awssdk/http/nio/netty/NettyNioAsyncHttpClientWireMockTest.java, http-clients/netty-nio-client/src/test/java/software/amazon/awssdk/http/nio/netty/ProxyConfigurationTest.java, http-clients/netty-nio-client/src/test/java/software/amazon/awssdk/http/nio/netty/ProxyWireMockTest.java, http-clients/netty-nio-client/src/test/java/software/amazon/awssdk/http/nio/netty/RecordingNetworkTrafficListener.java, http-clients/netty-nio-client/src/test/java/software/amazon/awssdk/http/nio/netty/internal/AwaitCloseChannelPoolMapTest.java, http-clients/netty-nio-client/src/test/java/software/amazon/awssdk/http/nio/netty/internal/Http1TunnelConnectionPoolTest.java, http-clients/netty-nio-client/src/test/java/software/amazon/awssdk/http/nio/netty/internal/ProxyTunnelInitHandlerTest.java
Enable HTTP proxying for Netty client.
New feature. See #858.
New unit tests, manual testing against proxy server.
=> Enable HTTP proxying for Netty client

http-clients/aws-crt-client/src/main/java/software/amazon/awssdk/http/crt/AwsCrtAsyncHttpClient.java
Don't leak Native CrtResources if error occurs during close.
=> Don't leak Native CrtResources if error occurs during close

core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/http/pipeline/stages/ApiCallAttemptTimeoutTrackingStage.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/http/pipeline/stages/ApiCallTimeoutTrackingStage.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/http/timers/ApiCallTimeoutTracker.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/http/timers/SyncTimeoutTask.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/http/timers/TimeoutTask.java, core/sdk-core/src/test/java/software/amazon/awssdk/core/http/InterruptFlagAlwaysClearsTest.java, core/sdk-core/src/test/java/software/amazon/awssdk/core/internal/http/timers/SyncTimeoutTaskTest.java
Fix a bug where the interrupted flag set by the API call and attempt timers can
leak outside of the client if the timeout is very small and approximately equal
to the response latency.
See description.
New unit tests, also ran stability tests and benchmarks.
=> Fix race condition in sync client timers

.changes/next-release/bugfix-AWSSDKforJavav2-045e79c.json, core/sdk-core/src/main/java/software/amazon/awssdk/core/client/builder/SdkDefaultClientBuilder.java, test/stability-tests/src/it/java/software/amazon/awssdk/stability/tests/TestResult.java, test/stability-tests/src/it/java/software/amazon/awssdk/stability/tests/s3/S3AsyncStabilityTest.java, test/stability-tests/src/it/java/software/amazon/awssdk/stability/tests/sqs/SqsAsyncStabilityTest.java, test/stability-tests/src/it/java/software/amazon/awssdk/stability/tests/transcribestreaming/TranscribeStreamingStabilityTest.java, test/stability-tests/src/it/java/software/amazon/awssdk/stability/tests/utils/RetryableTestExtension.java, test/stability-tests/src/it/java/software/amazon/awssdk/stability/tests/utils/StabilityTestRunner.java
- Reduce the pool size for asyncFutureCompletionPool 
- Add peak thread count validation in stability tests.
#994 
#1251 
Before the change
```json
[
{
testName: "KinesisStabilityTest.putRecords",
totalRequestCount: 36,
peakThreadCount: 65,
heapMemoryAfterGCUsage: 0.027188731896831263
},
{
testName: "KinesisStabilityTest.subscribeToShard",
totalRequestCount: 36,
peakThreadCount: 66,
heapMemoryAfterGCUsage: 0.1505862277410477
},
{
testName: "SqsAsyncStabilityTest.sendMessage",
totalRequestCount: 5000,
peakThreadCount: 67,
heapMemoryAfterGCUsage: 0.15713969063604177
},
{
testName: "SqsAsyncStabilityTest.receiveMessage",
totalRequestCount: 5000,
peakThreadCount: 67,
heapMemoryAfterGCUsage: 0.16292251659230597
},
{
testName: "TranscribeStreamingStabilityTest.startTranscription", …
```
=> Reduce the pool size for asyncFutureCompletionPool 

test/stability-tests/src/it/java/software/amazon/awssdk/stability/tests/kinesis/KinesisStabilityTest.java
Fix flaky KinesisStabilityTest by only verifying received data if it's not empty. 
It is possible the received data is empty because there is no record at the position event with TRIM_HORIZON per https://aws.amazon.com/kinesis/data-streams/faqs/
=> Fix flaky KinesisStabilityTest

test/sdk-benchmarks/src/main/resources/software/amazon/awssdk/benchmark/baseline.json
Looks like the jdk version change (`1.8.0_212` -> `1.8.0_222`) has increased the throughput a lot.
Might be related to https://bugs.openjdk.java.net/browse/JDK-8222206
=> Update baseline due to jdk version change

codegen-lite/src/main/java/software/amazon/awssdk/codegen/lite/regions/RegionGenerator.java, codegen-lite/src/test/resources/software/amazon/awssdk/codegen/lite/regions/regions.java, core/aws-core/src/test/java/software/amazon/awssdk/awscore/client/builder/DefaultAwsClientBuilderTest.java, core/regions/src/test/java/software/amazon/awssdk/regions/RegionTest.java
Region.of(...) will now URL encode the argument passed as the 'id' of the instantiated Region.
Added unit tests, ran all existing unit tests.
=> Core: Region 'id' is now URL encoded

.changes/next-release/feature-AWSSDKforJavav2-461c622.json, core/regions/src/it/java/software/amazon/awssdk/regions/util/EC2MetadataUtilsIntegrationTest.java, core/regions/src/main/java/software/amazon/awssdk/regions/internal/util/EC2MetadataUtils.java, core/regions/src/test/java/software/amazon/awssdk/regions/internal/util/EC2MetadataUtilsServer.java
A method was added in aws-sdk-java to help retrieve instance identify signature. Here is a pull request to port it to v2.
See https://github.com/aws/aws-sdk-java/pull/1653
=> Expose instance signature through EC2MetadataUtils

.changes/next-release/feature-AWSSDKforJavav2-8b6e7d4.json, core/arns/pom.xml, core/arns/src/main/java/software/amazon/awssdk/arns/Arn.java, core/arns/src/main/java/software/amazon/awssdk/arns/ArnResource.java, core/arns/src/test/java/software/amazon/awssdk/arns/ArnResourceTest.java, core/arns/src/test/java/software/amazon/awssdk/arns/ArnTest.java, core/pom.xml, utils/src/main/java/software/amazon/awssdk/utils/StringUtils.java, utils/src/test/java/software/amazon/awssdk/utils/StringUtilsTest.java
Implement arn parser functions. Basically same as v1. 
The only differences are:
- Add more javadocs
- Make it follow v2 pattern
- Make `ArnResource` return `Optional<String> resourceType()` and ` Optional<String> qualifier()` since they are optional.
Same tests copied from v1. changed assertions to use assertj
=> Implement arn parser functions

.changes/next-release/bugfix-NettyNIOHttpClient-9894ee4.json, http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/internal/ChannelAttributeKey.java, http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/internal/HealthCheckedChannelPool.java, http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/internal/ResponseHandler.java, http-clients/netty-nio-client/src/test/java/software/amazon/awssdk/http/nio/netty/internal/HealthCheckedChannelPoolTest.java
Update `HealthCheckedChannelPool` to check `KEEP_ALIVE` when acquiring a channel from the pool to avoid soon-to-be inactive channels being picked up by a new request. This should reduce the frequency of `IOException: Server failed to complete response` errors. See #1380 #1466
- Added unit tests.
- Manual tests 
Disabled retry and set maxIdleConnectionTimeout = 1 mins on purpose to expose the errors:
Before
```
CloudWatchAsyncStabilityTest: totalRequestCount: 4000, ioExceptionCount: 34
Based on the logs, 28 of ioExceptions were because the connections that were not reusable got picked up
```
After 
```
CloudWatchAsyncStabilityTest:, totalRequestCount: 4000, ioExceptionCount: 0
```
=> Update HealthCheckedChannelPool to check KEEP_ALIVE attribute

.changes/next-release/bugfix-NettyNIOHttpClient-5af2afd.json, http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/internal/ChannelAttributeKey.java, http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/internal/HandlerRemovingChannelPool.java, http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/internal/LastHttpContentHandler.java, http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/internal/NettyRequestExecutor.java, http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/internal/ResponseHandler.java, http-clients/netty-nio-client/src/test/java/software/amazon/awssdk/http/nio/netty/internal/LastHttpContentHandlerTest.java, http-clients/netty-nio-client/src/test/java/software/amazon/awssdk/http/nio/netty/internal/NettyRequestExecutorTest.java, http-clients/netty-nio-client/src/test/java/software/amazon/awssdk/http/nio/netty/internal/ResponseCompletionTest.java
Add `LastHttpContentHandler` to flag if the LastHttpContent has been received and don't throw "server failed to complete response" error if the content is buffered.
Added unit tests and function tests
Tested with long running canaries tests
Integ tests and stability tests passed
=> Add LastHttpContentHandler

.changes/next-release/bugfix-AWSSDKforJavav2-9a322a2.json, http-clients/aws-crt-client/pom.xml, http-clients/aws-crt-client/src/it/java/software/amazon/awssdk/http/crt/AwsCrtClientCallingPatternIntegrationTest.java, http-clients/aws-crt-client/src/it/java/software/amazon/awssdk/http/crt/AwsCrtClientKmsIntegrationTest.java, http-clients/aws-crt-client/src/it/java/software/amazon/awssdk/http/crt/AwsCrtClientS3IntegrationTest.java, http-clients/aws-crt-client/src/main/java/software/amazon/awssdk/http/crt/AwsCrtAsyncHttpClient.java, http-clients/aws-crt-client/src/main/java/software/amazon/awssdk/http/crt/internal/AwsCrtAsyncHttpStreamAdapter.java, http-clients/aws-crt-client/src/main/java/software/amazon/awssdk/http/crt/internal/AwsCrtResponseBodyPublisher.java, http-clients/aws-crt-client/src/test/java/software/amazon/awssdk/http/crt/AwsCrtHttpClientSpiVerificationTest.java, http-clients/aws-crt-client/src/test/java/software/amazon/awssdk/http/crt/AwsCrtResponseBodyPublisherReactiveStreamCompatTest.java, test/sdk-benchmarks/pom.xml
Update the version of the CRT with their latest changes.
This is required to to upgrade past the memory leak in the earlier versions of the CRT.
`mvn install`
=> Update to 0.3.35 of the CRT with minor API changes

services/kinesis/src/it/java/software/amazon/awssdk/services/kinesis/SubscribeToShardIntegrationTest.java, test/stability-tests/src/it/java/software/amazon/awssdk/stability/tests/utils/StabilityTestRunner.java
Fix flaky tests and print thread info when thread count exceeds threshold
=> Fix flaky tests and print thread info when thread count exceeds

.changes/next-release/feature-AmazonPolly-022a93f.json, services/polly/src/it/java/software/amazon/awssdk/services/polly/internal/presigner/DefaultPollyPresignerIntegrationTest.java, services/polly/src/main/java/software/amazon/awssdk/services/polly/internal/presigner/DefaultPollyPresigner.java, services/polly/src/main/java/software/amazon/awssdk/services/polly/internal/presigner/model/transform/SynthesizeSpeechRequestMarshaller.java, services/polly/src/main/java/software/amazon/awssdk/services/polly/presigner/PollyPresigner.java, services/polly/src/main/java/software/amazon/awssdk/services/polly/presigner/model/PresignedSynthesizeSpeechRequest.java, services/polly/src/main/java/software/amazon/awssdk/services/polly/presigner/model/SynthesizeSpeechPresignRequest.java, services/polly/src/test/java/software/amazon/awssdk/services/polly/internal/presigner/DefaultPollyPresignerTest.java, services/polly/src/test/java/software/amazon/awssdk/services/polly/internal/presigner/model/transform/SynthesizeSpeechRequestMarshallerTest.java
Supports presigning for SynthesizeSpeechRequest.
Part of #203 
Unit and integration tests.
=> Add support for Polly presigning

.changes/next-release/bugfix-AWSKinesis-717c642.json, .changes/next-release/feature-NettyNIOHTTPClient-dcedcab.json, http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/internal/ChannelAttributeKey.java, http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/internal/ChannelPipelineInitializer.java, http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/internal/NettyConfiguration.java, http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/internal/NettyRequestExecutor.java, http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/internal/http2/Http2FrameExceptionHandler.java, http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/internal/http2/Http2MultiplexedChannelPool.java, http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/internal/http2/Http2PingFrameHandler.java, http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/internal/http2/Http2ToHttpInboundAdapter.java, http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/internal/http2/MultiplexedChannelRecord.java, http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/internal/http2/PingTracker.java, http-clients/netty-nio-client/src/test/java/software/amazon/awssdk/http/nio/netty/fault/GoAwayTest.java, http-clients/netty-nio-client/src/test/java/software/amazon/awssdk/http/nio/netty/fault/ServerNotRespondingTest.java, http-clients/netty-nio-client/src/test/java/software/amazon/awssdk/http/nio/netty/internal/http2/Http2FrameExceptionHandlerTest.java, http-clients/netty-nio-client/src/test/java/software/amazon/awssdk/http/nio/netty/internal/http2/Http2MultiplexedChannelPoolTest.java, http-clients/netty-nio-client/src/test/java/software/amazon/awssdk/http/nio/netty/internal/http2/Http2PingFrameHandlerTest.java, http-clients/netty-nio-client/src/test/java/software/amazon/awssdk/http/nio/netty/internal/http2/MultiplexedChannelRecordTest.java, services/kinesis/src/it/java/log4j.properties, services/kinesis/src/main/java/software/amazon/awssdk/services/kinesis/internal/KinesisHttpConfigurationOptions.java, services/kinesis/src/main/resources/codegen-resources/customization.config
Implement PING health check for HTTP2 connections that encounter Read/WrtieTimeoutException
Added functional tests, unit tests.
~~will run~~ integ tests, stability tests and long-running canaries tests passed
=> Implement PING health check for HTTP2 connections 

CHANGELOG.md, core/profiles/src/main/java/software/amazon/awssdk/profiles/internal/ProfileFileReader.java, core/profiles/src/test/java/software/amazon/awssdk/profiles/ProfileFileTest.java
#389 is really annoying me. The issue has been open long enough that we should have a full set of characters.
Fixes #389
Unit tests
n/a
=> #389: Allow period, solidus, at-sign, and percent-sign in profile names

.changes/next-release/feature-AWSSDKforJavav2-a67e196.json, codegen/src/main/java/software/amazon/awssdk/codegen/AddShapes.java, codegen/src/main/java/software/amazon/awssdk/codegen/internal/DocumentationUtils.java, codegen/src/main/java/software/amazon/awssdk/codegen/model/intermediate/MemberModel.java, codegen/src/main/java/software/amazon/awssdk/codegen/naming/DefaultNamingStrategy.java, codegen/src/main/java/software/amazon/awssdk/codegen/naming/NamingStrategy.java, codegen/src/main/java/software/amazon/awssdk/codegen/poet/model/AwsServiceModel.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/alltypesrequest.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/alltypesresponse.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/existencechecknamingrequest.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/existencechecknamingresponse.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/nestedcontainersrequest.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/nestedcontainersresponse.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/nonautoconstructcontainers/alltypesrequest.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/nonautoconstructcontainers/alltypesresponse.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/nonautoconstructcontainers/existencechecknamingrequest.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/nonautoconstructcontainers/existencechecknamingresponse.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/nonautoconstructcontainers/nestedcontainersrequest.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/nonautoconstructcontainers/nestedcontainersresponse.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/nonautoconstructcontainers/recursivestructtype.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/recursivestructtype.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/service-2.json
Add an existence check method for Lists and Maps. 
Adds a getter method, `hasX` for every member that is a list or map type. Adds a NamingStrategy for this type of method.
Fixes #867 
There is no single way for SDK consumers to identify if a collection might be an empty list or null without exposing the AutoConstruct types. This fix provides the existence check.
protocol tests caught an issue in the naming.
other fixes were caught by the parameterized tests.
=> Add list/map existence check (#867)

.changes/next-release/bugfix-AWSSDKforJavav2-02a12c9.json, core/sdk-core/src/main/java/software/amazon/awssdk/core/sync/RequestBody.java, core/sdk-core/src/test/java/software/amazon/awssdk/core/sync/RequestBodyTest.java
Fixes #1544
Makes `RequestBody.fromInputStream`'s `InputStream#reset` call conditional on `markSupported()` in the same way that `IoUtils.markStreamWithMaxReadLimit` is.
Fixes #1544 
New unit test added.
=> Making the reset on RequestBody conditional on markSupported

.changes/next-release/feature-AmazonS3-ebadcff.json, codegen/src/main/java/software/amazon/awssdk/codegen/AddShapes.java, codegen/src/main/java/software/amazon/awssdk/codegen/customization/processors/ShapeModifiersProcessor.java, codegen/src/main/java/software/amazon/awssdk/codegen/model/config/customization/ModifyModelShapeModifier.java, codegen/src/main/java/software/amazon/awssdk/codegen/model/intermediate/MemberModel.java, codegen/src/main/java/software/amazon/awssdk/codegen/model/service/Member.java, codegen/src/main/java/software/amazon/awssdk/codegen/poet/model/AbstractMemberSetters.java, codegen/src/main/java/software/amazon/awssdk/codegen/poet/model/AccessorsFactory.java, codegen/src/main/java/software/amazon/awssdk/codegen/poet/model/AwsServiceModel.java, codegen/src/main/java/software/amazon/awssdk/codegen/poet/model/ListSetters.java, codegen/src/main/java/software/amazon/awssdk/codegen/poet/model/MapSetters.java, codegen/src/main/java/software/amazon/awssdk/codegen/poet/model/MemberSetters.java, codegen/src/main/java/software/amazon/awssdk/codegen/poet/model/ModelBuilderSpecs.java, codegen/src/main/java/software/amazon/awssdk/codegen/poet/model/NonCollectionSetters.java, codegen/src/test/java/software/amazon/awssdk/codegen/poet/model/DeprecatedNameTest.java, codegen/src/test/java/software/amazon/awssdk/codegen/poet/model/XmlNamespaceModelTest.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/customization.config, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/deprecatedname/enumdeprecationfailure.customization, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/deprecatedname/enumdeprecationfailure.json, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/deprecatedname/listdeprecationfailure.customization, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/deprecatedname/listdeprecationfailure.json, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/deprecatedname/mapdeprecationfailure.customization, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/deprecatedname/mapdeprecationfailure.json, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/deprecatedrenamerequest.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/deprecatedrenameresponse.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/service-2.json, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/xmlnamespace/customization.config, core/sdk-core/src/test/java/software/amazon/awssdk/core/internal/util/ResponseHandlerTestUtils.java, services/s3/src/main/resources/codegen-resources/customization.config
When renaming properties via customization.config, the existing names can be deprecated. 
On S3 CopyObjectRequest, deprecates `bucket` in favor of `destinationBucket` and `key` in favor of `destinationKey`.
This covers half of the requests in #1313 .
Added tests for deprecation
Validated resulting CopyObjectResult class
n/a
=> Support ability to rename fields and deprecate existing names; does so for S3

.changes/next-release/bugfix-AmazonS3-61d34b5.json, services/s3/pom.xml, services/s3/src/it/java/software/amazon/awssdk/services/s3/AsyncServerSideEncryptionIntegrationTest.java, services/s3/src/it/java/software/amazon/awssdk/services/s3/ServerSideEncryptionIntegrationTestBase.java, services/s3/src/it/java/software/amazon/awssdk/services/s3/SyncServerSideEncryptionIntegrationTest.java, services/s3/src/main/java/software/amazon/awssdk/services/s3/checksums/ChecksumsEnabledValidator.java, services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/handlers/AsyncChecksumValidationInterceptor.java, services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/handlers/SyncChecksumValidationInterceptor.java, services/s3/src/test/java/software/amazon/awssdk/services/s3/checksums/ChecksumsEnabledValidatorTest.java, services/s3/src/test/java/software/amazon/awssdk/services/s3/internal/handlers/AsyncChecksumValidationInterceptorTest.java, services/s3/src/test/java/software/amazon/awssdk/services/s3/internal/handlers/SyncChecksumValidationInterceptorTest.java
Previously this was only done when the customer reported this in their request.
=> Do not validate checksums when the service reports it is using customer-managed keys with server-side encryption.

.changes/next-release/bugfix-NettyNIOHttpClient-699dfbc.json, http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/internal/http2/HttpOrHttp2ChannelPool.java, http-clients/netty-nio-client/src/test/java/software/amazon/awssdk/http/nio/netty/NettyNioAsyncHttpClientWireMockTest.java, http-clients/netty-nio-client/src/test/java/software/amazon/awssdk/http/nio/netty/internal/http2/HttpOrHttp2ChannelPoolTest.java
Fix an issue where exceptions thrown from initializing BetterFixedChannelPool gets swallowed
=> Propagate exceptions properly when protocol configuration fails

CONTRIBUTING.md
The aws/aws-cla repo has been removed so this link 404's now.
Fixes #1536
=> Remove CLA link

pom.xml
New version bumps the version 4.1.43.Final.
Older version depends on older Netty version, tripping some security scans, such as #1524.
`mvn clean install`. Running integ tests just to be sure as well, but there don't look to be any code changes (aside from tests) since 2.0.3.
=> Update netty reactive streams version

http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/internal/HandlerRemovingChannelPool.java, http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/internal/NettyRequestExecutor.java, http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/internal/http2/FlushOnReadHandler.java, http-clients/netty-nio-client/src/test/java/software/amazon/awssdk/http/nio/netty/internal/http2/FlushOnReadTest.java, services/kinesis/src/it/java/software/amazon/awssdk/services/kinesis/SubscribeToShardIntegrationTest.java
It's possible that WINDOW_UPDATE in the outbound buffer is not be written in a
timely manner to the socket, causing subsequent read()'s to hang until the
remote endpoint sees the local window increase.
New unit and integ tests. Running full integ and benchmark suites.
=> Flush parent before reading on H2 connection

.changes/next-release/feature-AWSSDKforJavav2-e8d7ec5.json, core/sdk-core/src/main/java/software/amazon/awssdk/core/sync/RequestBody.java, core/sdk-core/src/test/java/software/amazon/awssdk/core/sync/RequestBodyTest.java, utils/src/main/java/software/amazon/awssdk/utils/BinaryUtils.java, utils/src/test/java/software/amazon/awssdk/utils/BinaryUtilsTest.java
=> Add RequestBody.fromRemainingByteBuffer()

.changes/next-release/feature-AWSStepFunctions-26702fe.json, services/sfn/src/it/java/software/amazon/awssdk/services/sfn/SfnIntegrationTest.java, services/sfn/src/main/java/software/amazon/awssdk/services/sfn/internal/SfnHttpConfigurationOptions.java, services/sfn/src/main/resources/codegen-resources/customization.config
Add sfn specific http configs because Sfn has long polling APIs such as getActivityTask that could take up to 60 seconds to respond and the default sdk socket timeout would not work. See #1325 
Added integ test
=> Add sfn specific http configs

.changes/next-release/bugfix-AmazonEC2-b80e04f.json, services/ec2/src/main/java/software/amazon/awssdk/services/ec2/transform/internal/GeneratePreSignUrlInterceptor.java, services/ec2/src/test/java/software/amazon/awssdk/services/ec2/transform/internal/GeneratePreSignUrlInterceptorTest.java
Fixes #1564
Bug fix.
New unit test, integ tests.
=> Add scheme to destination region endpoint

.travis.yml
Fixes the strange compile error for JDK 11 on Precise.
=> Update to use Xenial, OpenJDK 8 for Travis builds

.changes/next-release/feature-AmazonS3-7700da3.json, services/s3/src/it/java/software/amazon/awssdk/services/s3/ObjectTaggingIntegrationTest.java, services/s3/src/main/resources/codegen-resources/customization.config
Add support for tagging builder in createMultipartUploadRequest.
I've verified there are no other existing models that have `Tagging` field
See #1440 
Added integ tests
=> Add support for tagging builder in createMultipartUploadRequest

.changes/next-release/bugfix-NettyNIOHTTPClient-f222168.json, http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/internal/AwaitCloseChannelPoolMap.java
This forces the Netty client use InetAddress.getByName/getAllByName for each
connect() request, which will delegate to the JVM's DNS lookup and caching
mechanism
Bugfix
Working on testing this manually
=> Create Bootstrap with unresolved address

services-custom/dynamodb-enhanced/README.md
The documentation for the dynamodb-enhanced module had fallen out of sync with the changes being made to the interface. This is to correct that and bring it up to date.
=> Updated README.md to match current design iteration of interface

.changes/next-release/bugfix-NettyNIOHTTPClient-037932d.json, http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/internal/http2/MultiplexedChannelRecord.java, http-clients/netty-nio-client/src/test/java/software/amazon/awssdk/http/nio/netty/internal/http2/MultiplexedChannelRecordTest.java
…s picked up at the same time it gets closed
- ~~Reduce the chances of the race condition where an HTTP2 connection gets reused at the same time it gets inactive~~
- Throw `IOException` instead of `IllegalStatementException` so the failed requests can be retried.
=> Throws IOException for an h2 connection acquiring race condition

.changes/next-release/bugfix-AmazonS3-9bf1df7.json, services/s3/src/it/java/software/amazon/awssdk/services/s3/UrlEncodingIntegrationTest.java, services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/handlers/DecodeUrlEncodedResponseInterceptor.java, services/s3/src/test/java/software/amazon/awssdk/services/s3/internal/handlers/DecodeUrlEncodedResponseInterceptorTest.java
Fixed an issue where fields in `ListObjectVersionsResponse` and `ListMultipartUploadsResponse` are not decoded correctly when encodingType is specified as url. See #1601 
Added unit tests and integ tests.
=> Fixed s3 decoding response for ListObjectsVersion and ListMultipartUploads

.changes/next-release/bugfix-NettyNIOHTTPClient-dba3e80.json, http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/internal/ChannelPipelineInitializer.java, http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/internal/http2/GoAwayException.java, http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/internal/http2/MultiplexedChannelRecord.java, http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/internal/http2/PingFailedException.java, http-clients/netty-nio-client/src/test/java/software/amazon/awssdk/http/nio/netty/fault/GoAwayTest.java, http-clients/netty-nio-client/src/test/java/software/amazon/awssdk/http/nio/netty/fault/PingTimeoutTest.java, http-clients/netty-nio-client/src/test/java/software/amazon/awssdk/http/nio/netty/fault/ServerCloseConnectionTest.java, http-clients/netty-nio-client/src/test/java/software/amazon/awssdk/http/nio/netty/fault/ServerNotRespondingTest.java, http-clients/netty-nio-client/src/test/java/software/amazon/awssdk/http/nio/netty/internal/http2/MultiplexedChannelRecordTest.java
- Fix the issue where publisher signals onComplete if the stream is closed as a result of outbound GOAWAY. The root cause is that when `PingFailedException` is fired, `UnusedChannelExceptionHandler` is handling it instead of `ReleaseOnExceptionHandler`. `UnusedChannelExceptionHandler` only closes h2 connections. As a result, the exception would not be delivered to child channels as expected.
- ~~Change `UnusedChannelExceptionHandler` to a per-request handler because it doesn't really make sense to attach it to connection channel pipeline since we never set `IN_USE` attribute key on it.~~ Only attach `UnusedChannelExceptionHandler` to h2 stream channels and h1 channels.
- When delivering a connection exception to a child channel, wrap it with a more descriptive exception.
Previously, if a …
=> h2 connection exception handling 

services/s3/src/it/java/software/amazon/awssdk/services/s3/CreateBucketIntegrationTest.java
Integ test was failing because getBucketLocation was returning a NoSuchBucketException due to eventual consistency. Added a waiter to the call so that it will retry a few times before failing.
=> Updating getBucketLocation call to use Waiter for eventual consistency

services-custom/dynamodb-enhanced/src/main/java/software/amazon/awssdk/enhanced/dynamodb/AttributeValues.java, services-custom/dynamodb-enhanced/src/main/java/software/amazon/awssdk/enhanced/dynamodb/mapper/AttributeTypes.java, services-custom/dynamodb-enhanced/src/main/java/software/amazon/awssdk/enhanced/dynamodb/mapper/Attributes.java, services-custom/dynamodb-enhanced/src/main/java/software/amazon/awssdk/enhanced/dynamodb/mapper/BeanTableSchema.java, services-custom/dynamodb-enhanced/src/test/java/software/amazon/awssdk/enhanced/dynamodb/functionaltests/models/FakeItemWithBinaryKey.java, services-custom/dynamodb-enhanced/src/test/java/software/amazon/awssdk/enhanced/dynamodb/mapper/BeanTableSchemaTest.java, services-custom/dynamodb-enhanced/src/test/java/software/amazon/awssdk/enhanced/dynamodb/mapper/StaticTableSchemaTest.java, services-custom/dynamodb-enhanced/src/test/java/software/amazon/awssdk/enhanced/dynamodb/mapper/testbeans/CommonTypesBean.java, services-custom/dynamodb-enhanced/src/test/java/software/amazon/awssdk/enhanced/dynamodb/mapper/testbeans/SetBean.java
Changed all representations of binary data (for dynamoDB) to use SdkBytes instead of ByteBuffer. This better matches the interface of the SDK and is easier for customers to use.
Relates to https://github.com/aws/aws-sdk-java-v2/issues/35
=> DynamoDb Enhanced Client: all uses of 'ByteBuffer' changed to 'SdkBytes'

services-custom/dynamodb-enhanced/pom.xml, services-custom/dynamodb-enhanced/src/test/java/software/amazon/awssdk/enhanced/dynamodb/mocktests/AsyncBatchGetItemTest.java, services-custom/dynamodb-enhanced/src/test/java/software/amazon/awssdk/enhanced/dynamodb/mocktests/BatchGetItemTest.java, services-custom/dynamodb-enhanced/src/test/java/software/amazon/awssdk/enhanced/dynamodb/mocktests/BatchGetTestUtils.java
Add tests against mock server to test paginating the results of batchGetItem operation with unprocessed keys.
Currently we don't have any tests to verify batchGetItem with unprocessed keys.
=> Add tests for dynamodb enhanced client batchGetItem operation

.changes/next-release/bugfix-AWSSDKforJavav2-11b8422.json, core/sdk-core/src/main/java/software/amazon/awssdk/core/RequestOverrideConfiguration.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/client/config/ClientOverrideConfiguration.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/http/pipeline/stages/MergeCustomHeadersStage.java, core/sdk-core/src/test/java/software/amazon/awssdk/core/internal/http/pipeline/stages/MergeCustomHeadersStageTest.java, utils/src/main/java/software/amazon/awssdk/utils/http/SdkHttpUtils.java
Use the last seen HTTP/1.1 header value for headers defined to only appear once in an HTTP message instead of merging them all into a list. The order in which header values are inspected is: headers set on the request, overridden headers set on the client, then finally overridden headers set on an SDK request. See https://tools.ietf.org/html/rfc2616#section-4.2 for more information.
Bug fix.
`mvn clean install`. Will run integ tests.
=> Fix merging of single value headers

services-custom/dynamodb-enhanced/src/main/java/software/amazon/awssdk/enhanced/dynamodb/TableSchema.java, services-custom/dynamodb-enhanced/src/test/java/software/amazon/awssdk/enhanced/dynamodb/TableSchemaTest.java
Making it easier for customers to discover the different implementations of TableSchema.
=> DynamoDB Enhanced: Added static constructors to TableSchema interface

services-custom/dynamodb-enhanced/src/main/java/software/amazon/awssdk/enhanced/dynamodb/AttributeConverter.java, services-custom/dynamodb-enhanced/src/main/java/software/amazon/awssdk/enhanced/dynamodb/internal/extensions/ChainExtension.java, services-custom/dynamodb-enhanced/src/main/java/software/amazon/awssdk/enhanced/dynamodb/mapper/StaticTableSchema.java
- Fix stale javadocs 
- Remove unnecessary use of `AtomicReference`
=> Fix stale javadocs and remove unnecessary use of AtomicReference

services-custom/dynamodb-enhanced/src/main/java/software/amazon/awssdk/enhanced/dynamodb/Key.java, services-custom/dynamodb-enhanced/src/main/java/software/amazon/awssdk/enhanced/dynamodb/internal/conditional/SingleKeyItemConditional.java, services-custom/dynamodb-enhanced/src/main/java/software/amazon/awssdk/enhanced/dynamodb/model/QueryConditional.java, services-custom/dynamodb-enhanced/src/test/java/software/amazon/awssdk/enhanced/dynamodb/KeyTest.java, services-custom/dynamodb-enhanced/src/test/java/software/amazon/awssdk/enhanced/dynamodb/functionaltests/AsyncBasicQueryTest.java, services-custom/dynamodb-enhanced/src/test/java/software/amazon/awssdk/enhanced/dynamodb/functionaltests/AsyncIndexQueryTest.java, services-custom/dynamodb-enhanced/src/test/java/software/amazon/awssdk/enhanced/dynamodb/functionaltests/BasicQueryTest.java, services-custom/dynamodb-enhanced/src/test/java/software/amazon/awssdk/enhanced/dynamodb/functionaltests/IndexQueryTest.java, services-custom/dynamodb-enhanced/src/test/java/software/amazon/awssdk/enhanced/dynamodb/internal/operations/QueryOperationConditionalTest.java, services-custom/dynamodb-enhanced/src/test/java/software/amazon/awssdk/enhanced/dynamodb/internal/operations/QueryOperationTest.java, services-custom/dynamodb-enhanced/src/test/java/software/amazon/awssdk/enhanced/dynamodb/model/QueryEnhancedRequestTest.java
- rename: `equalTo` -> `keyEqualTo`
- add sort prefix to all other sort query conditional methods, eg: `greaterThan` -> `sortGreaterThan`
- add `partitionKey` validation in `Key`
=> Rename QueryConditional methods

.changes/next-release/bugfix-AWSSDKforJavav2-ba3be37.json, core/auth/src/main/java/software/amazon/awssdk/auth/signer/internal/AbstractAws4Signer.java, core/auth/src/main/java/software/amazon/awssdk/auth/signer/internal/BaseAsyncAws4Signer.java, core/auth/src/main/java/software/amazon/awssdk/auth/signer/internal/BaseEventStreamAsyncAws4Signer.java, core/auth/src/main/java/software/amazon/awssdk/auth/signer/internal/SignerKey.java, core/auth/src/test/java/software/amazon/awssdk/auth/signer/EventStreamAws4SignerTest.java, core/auth/src/test/java/software/amazon/awssdk/auth/signer/internal/SignerKeyTest.java
Fix an issue where the signing key is created only once at the start of the
request for event streaming requests. This causes requests that span two more
more days to have signing errors once the date changes because the signing key
was derived only once using the date at the beginning of the request.
Bug fix.
- `mvn clean install`
- ~~Running integ tests~~ integ test
=> Use signing date when deriving signing key

services-custom/dynamodb-enhanced/src/main/java/software/amazon/awssdk/enhanced/dynamodb/DynamoDbAsyncTable.java, services-custom/dynamodb-enhanced/src/main/java/software/amazon/awssdk/enhanced/dynamodb/DynamoDbTable.java, services-custom/dynamodb-enhanced/src/main/java/software/amazon/awssdk/enhanced/dynamodb/internal/client/DefaultDynamoDbAsyncTable.java, services-custom/dynamodb-enhanced/src/main/java/software/amazon/awssdk/enhanced/dynamodb/internal/client/DefaultDynamoDbTable.java, services-custom/dynamodb-enhanced/src/main/java/software/amazon/awssdk/enhanced/dynamodb/model/ReadBatch.java, services-custom/dynamodb-enhanced/src/main/java/software/amazon/awssdk/enhanced/dynamodb/model/TransactGetItemsEnhancedRequest.java, services-custom/dynamodb-enhanced/src/main/java/software/amazon/awssdk/enhanced/dynamodb/model/TransactWriteItemsEnhancedRequest.java, services-custom/dynamodb-enhanced/src/main/java/software/amazon/awssdk/enhanced/dynamodb/model/WriteBatch.java, services-custom/dynamodb-enhanced/src/test/java/software/amazon/awssdk/enhanced/dynamodb/functionaltests/AsyncBasicCrudTest.java, services-custom/dynamodb-enhanced/src/test/java/software/amazon/awssdk/enhanced/dynamodb/functionaltests/AsyncTransactGetItemsTest.java, services-custom/dynamodb-enhanced/src/test/java/software/amazon/awssdk/enhanced/dynamodb/functionaltests/AsyncTransactWriteItemsTest.java, services-custom/dynamodb-enhanced/src/test/java/software/amazon/awssdk/enhanced/dynamodb/functionaltests/BasicCrudTest.java, services-custom/dynamodb-enhanced/src/test/java/software/amazon/awssdk/enhanced/dynamodb/functionaltests/TransactGetItemsTest.java, services-custom/dynamodb-enhanced/src/test/java/software/amazon/awssdk/enhanced/dynamodb/functionaltests/TransactWriteItemsTest.java, services-custom/dynamodb-enhanced/src/test/java/software/amazon/awssdk/enhanced/dynamodb/internal/operations/BatchGetItemOperationTest.java, services-custom/dynamodb-enhanced/src/test/java/software/amazon/awssdk/enhanced/dynamodb/internal/operations/BatchWriteItemOperationTest.java, services-custom/dynamodb-enhanced/src/test/java/software/amazon/awssdk/enhanced/dynamodb/internal/operations/TransactGetItemsOperationTest.java, services-custom/dynamodb-enhanced/src/test/java/software/amazon/awssdk/enhanced/dynamodb/internal/operations/TransactWriteItemsOperationTest.java, services-custom/dynamodb-enhanced/src/test/java/software/amazon/awssdk/enhanced/dynamodb/model/TransactGetItemsEnhancedRequestTest.java, services-custom/dynamodb-enhanced/src/test/java/software/amazon/awssdk/enhanced/dynamodb/model/TransactWriteItemsEnhancedRequestTest.java
Adding the new KeyItem/Item shortcut form to TransactGetItems and TransactWriteItems enhanced requests caused ambiguity resolving the difference between that overloaded method and the method that takes a consumer builder. We decided that keyItem was the more convenient of the two convenience methods so chopped the consumer builder version just from those operations.
=> DDB Enhanced: Add support for a 'key item' in operations that take a key

services-custom/dynamodb-enhanced/README.md, services-custom/dynamodb-enhanced/src/main/java/software/amazon/awssdk/enhanced/dynamodb/DynamoDbEnhancedAsyncClient.java, services-custom/dynamodb-enhanced/src/main/java/software/amazon/awssdk/enhanced/dynamodb/DynamoDbEnhancedClient.java, services-custom/dynamodb-enhanced/src/main/java/software/amazon/awssdk/enhanced/dynamodb/internal/client/DefaultDynamoDbEnhancedAsyncClient.java, services-custom/dynamodb-enhanced/src/main/java/software/amazon/awssdk/enhanced/dynamodb/internal/client/DefaultDynamoDbEnhancedClient.java, services-custom/dynamodb-enhanced/src/main/java/software/amazon/awssdk/enhanced/dynamodb/model/BatchGetResultPage.java, services-custom/dynamodb-enhanced/src/main/java/software/amazon/awssdk/enhanced/dynamodb/model/BatchGetResultPageIterable.java, services-custom/dynamodb-enhanced/src/main/java/software/amazon/awssdk/enhanced/dynamodb/model/BatchGetResultPagePublisher.java, services-custom/dynamodb-enhanced/src/test/java/software/amazon/awssdk/enhanced/dynamodb/functionaltests/AsyncBatchGetItemTest.java, services-custom/dynamodb-enhanced/src/test/java/software/amazon/awssdk/enhanced/dynamodb/functionaltests/BatchGetItemTest.java, services-custom/dynamodb-enhanced/src/test/java/software/amazon/awssdk/enhanced/dynamodb/functionaltests/LocalDynamoDbAsyncTestBase.java, services-custom/dynamodb-enhanced/src/test/java/software/amazon/awssdk/enhanced/dynamodb/internal/operations/BatchGetItemOperationTest.java, services-custom/dynamodb-enhanced/src/test/java/software/amazon/awssdk/enhanced/dynamodb/mocktests/AsyncBatchGetItemTest.java, services-custom/dynamodb-enhanced/src/test/java/software/amazon/awssdk/enhanced/dynamodb/mocktests/BatchGetItemTest.java
- sync batchGetItem returns`BatchGetItemPageIterable` that allows customers to iterate through flattened results via `BatchGetItemIterable#resultsForTable`
- async batchGetItem returns `BatchGetItemPagePublisher` that allows customers to subscribe to flattened results via `BatchGetItemPagePublisher#resultsForTable`
- renamed `getResutlsForTable` -> `resultsForTable`
~~- add `unprocessedKeys` in `BatchGetItemPage` so that it's consistent with `Page`~~
=> DDB Enhanced client: flattened batch get items

.changes/next-release/bugfix-AWSSDKforJavav2-fbcd9ee.json, core/aws-core/src/main/java/software/amazon/awssdk/awscore/internal/AwsErrorCode.java
=> Remove LimitExceededException as throttling error

core/sdk-core/src/main/java/software/amazon/awssdk/core/interceptor/ExecutionInterceptor.java
Javadoc for `afterTransmission` points to `beforeTransmission`, which is when the request is finalized, when it means to actually point to where the response is finalized (currently it is going back in time). `beforeUnmarshalling` seems correct.
Fixes confusion caused by pointing at an incorrect method.
Just doc change
```
[ERROR] Tests run: 12, Failures: 0, Errors: 7, Skipped: 0, Time elapsed: 0.014 s <<< FAILURE! - in software.amazon.awssdk.core.retry.RetryPolicyMaxRetriesTest
[ERROR] differentCombinationOfConfigs_shouldResolveCorrectly[1](software.amazon.awssdk.core.retry.RetryPolicyMaxRetriesTest)  Time elapsed: 0 s  <<< ERROR!
java.nio.file.InvalidPathException: Illegal char <:> at index 2: /C:/tools/msys64/home/Anuraag/git/aws-sdk-java-v2/core/sdk-core/target/test-classes/software/am …
```
=> Fix javadoc to point to correct method.

services-custom/dynamodb-enhanced/README.md
Adds sections for the StaticTableSchema and BeanTableSchema, including usage of
- AttributeConverterProviders
- AttributeConverters
- Flattning and extending beans
- Ignoring and including bean attributes
=> DDB Enhanced: updates README with bean examples

services-custom/dynamodb-enhanced/src/main/java/software/amazon/awssdk/enhanced/dynamodb/AttributeConverterProvider.java, services-custom/dynamodb-enhanced/src/main/java/software/amazon/awssdk/enhanced/dynamodb/DefaultAttributeConverterProvider.java, services-custom/dynamodb-enhanced/src/main/java/software/amazon/awssdk/enhanced/dynamodb/internal/converter/ChainConverterProvider.java, services-custom/dynamodb-enhanced/src/main/java/software/amazon/awssdk/enhanced/dynamodb/internal/converter/ConverterProviderResolver.java, services-custom/dynamodb-enhanced/src/main/java/software/amazon/awssdk/enhanced/dynamodb/mapper/BeanTableSchema.java, services-custom/dynamodb-enhanced/src/main/java/software/amazon/awssdk/enhanced/dynamodb/mapper/StaticTableSchema.java, services-custom/dynamodb-enhanced/src/main/java/software/amazon/awssdk/enhanced/dynamodb/mapper/annotations/DynamoDbBean.java, services-custom/dynamodb-enhanced/src/test/java/software/amazon/awssdk/enhanced/dynamodb/internal/converter/ChainConverterProviderTest.java, services-custom/dynamodb-enhanced/src/test/java/software/amazon/awssdk/enhanced/dynamodb/internal/converter/ConverterProviderResolverTest.java, services-custom/dynamodb-enhanced/src/test/java/software/amazon/awssdk/enhanced/dynamodb/mapper/BeanTableSchemaTest.java, services-custom/dynamodb-enhanced/src/test/java/software/amazon/awssdk/enhanced/dynamodb/mapper/StaticTableSchemaTest.java, services-custom/dynamodb-enhanced/src/test/java/software/amazon/awssdk/enhanced/dynamodb/mapper/testbeans/EmptyConverterProvidersInvalidBean.java, services-custom/dynamodb-enhanced/src/test/java/software/amazon/awssdk/enhanced/dynamodb/mapper/testbeans/EmptyConverterProvidersValidBean.java, services-custom/dynamodb-enhanced/src/test/java/software/amazon/awssdk/enhanced/dynamodb/mapper/testbeans/MultipleConverterProvidersBean.java, services-custom/dynamodb-enhanced/src/test/java/software/amazon/awssdk/enhanced/dynamodb/mapper/testbeans/NoConstructorConverterProvidersBean.java, services-custom/dynamodb-enhanced/src/test/java/software/amazon/awssdk/enhanced/dynamodb/mapper/testbeans/SingleConverterProvidersBean.java
- Adds a 'chained' `AttributeConverterProvider` that can hold any number of user-supplied AttributeConverterProviders and will match converters using strict precedence, first-come-first-served. 
- It's also possible to supply an empty list to completely override the default AttributeConverterProvider provided by the library, in which case the user must add an `AttributeConverter` for each attribute in the schema
- Both features available for `StaticTableSchema` and for `DynamoDbBeans` (`BeanTableSchema`). 
For reference: [Issue 35](https://github.com/aws/aws-sdk-java-v2/issues/35)
Note: README updated separately in [PR 1731](https://github.com/aws/aws-sdk-java-v2/pull/1731).
* Consistent behavior over both bean and static table schema
* User-friendly syntax for bean
Unit tested
=> DDB Enhanced adding ChainConverterProvider

CHANGELOG.md, services-custom/dynamodb-enhanced/src/main/java/software/amazon/awssdk/enhanced/dynamodb/internal/operations/QueryOperation.java, services-custom/dynamodb-enhanced/src/main/java/software/amazon/awssdk/enhanced/dynamodb/internal/operations/ScanOperation.java, services-custom/dynamodb-enhanced/src/main/java/software/amazon/awssdk/enhanced/dynamodb/model/QueryEnhancedRequest.java, services-custom/dynamodb-enhanced/src/main/java/software/amazon/awssdk/enhanced/dynamodb/model/ScanEnhancedRequest.java, services-custom/dynamodb-enhanced/src/test/java/software/amazon/awssdk/enhanced/dynamodb/functionaltests/BasicQueryTest.java, services-custom/dynamodb-enhanced/src/test/java/software/amazon/awssdk/enhanced/dynamodb/functionaltests/BasicScanTest.java, services-custom/dynamodb-enhanced/src/test/java/software/amazon/awssdk/enhanced/dynamodb/internal/operations/QueryOperationTest.java, services-custom/dynamodb-enhanced/src/test/java/software/amazon/awssdk/enhanced/dynamodb/internal/operations/ScanOperationTest.java, services-custom/dynamodb-enhanced/src/test/java/software/amazon/awssdk/enhanced/dynamodb/model/QueryEnhancedRequestTest.java, services-custom/dynamodb-enhanced/src/test/java/software/amazon/awssdk/enhanced/dynamodb/model/ScanEnhancedRequestTest.java
Added missing support for projection expression into `QueryEnhancedRequest` and `ScanEnhancedRequest` classes.
At the moment, there is no way how to obtain just a portion of the data from DynamoDB in OOP manner.
The tests have been updated to reflect the change.
=> DDB Enhanced: Added support for projection expression

core/metrics-spi/src/main/java/software/amazon/awssdk/metrics/meter/DefaultTimer.java, core/metrics-spi/src/test/java/software/amazon/awssdk/metrics/meter/DefaultTimerTest.java
Fixed the bug of endTime not modified by plusNanos() by reassigning the modified result to itself;
Added corresponding test to test if the change works;
Modified the stub of mockClock.instant() to make it pass all the tests.
The reason why stubbing mockClock.instant() is moved ahead of creating timer is that while creating the timer there are two calls of mockClock.instant(). In original version, these two calls were ignored so the startTime and endTime were null and the new added test will fail to this. After changing the position of the stubbing and adding two more values to the stub, all the tests are able to pass.
=> Fixed the endTime not modified bug to pass sonar cloud tests.

.changes/next-release/feature-AmazonDynamoDBEnhancedClient-3ec9346.json, services-custom/dynamodb-enhanced/README.md, services-custom/dynamodb-enhanced/pom.xml, test/sdk-benchmarks/pom.xml, test/tests-coverage-reporting/pom.xml
=> Launching the DynamoDB Enhanced Client

.changes/next-release/bugfix-AWSSDKforJavav2-97280b7.json, codegen/src/main/java/software/amazon/awssdk/codegen/naming/DefaultNamingStrategy.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/alltypesrequest.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/alltypesresponse.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/nonautoconstructcontainers/alltypesrequest.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/nonautoconstructcontainers/alltypesresponse.java, test/codegen-generated-classes-test/src/test/java/software/amazon/awssdk/services/ModelSerializationTest.java
To follow the bean standard, the setter names should match the getter names, which isn't the case. This caused issues when marshalling request/response objects containing enums. This change ensures the bean setter always matches the bean getter.
=> Ensure bean-style setter method names match getter method names for modeled structures.

.changes/next-release/feature-AWSSDKforJavav2-49d3cd6.json, core/auth/src/main/java/software/amazon/awssdk/auth/signer/internal/AbstractAws4Signer.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/RequestOverrideConfiguration.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/client/config/ClientOverrideConfiguration.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/http/pipeline/stages/utils/RetryableStageHelper.java, http-client-spi/src/main/java/software/amazon/awssdk/http/DefaultSdkHttpFullRequest.java, http-client-spi/src/main/java/software/amazon/awssdk/http/DefaultSdkHttpFullResponse.java, http-client-spi/src/test/java/software/amazon/awssdk/http/SdkHttpRequestResponseTest.java, utils/src/main/java/software/amazon/awssdk/utils/CollectionUtils.java, utils/src/main/java/software/amazon/awssdk/utils/StringUtils.java, utils/src/main/java/software/amazon/awssdk/utils/UnmodifiableMapOfLists.java, utils/src/main/java/software/amazon/awssdk/utils/http/SdkHttpUtils.java, utils/src/test/java/software/amazon/awssdk/utils/CollectionUtilsTest.java
=> Various performance improvements.

services-custom/dynamodb-enhanced/src/main/java/software/amazon/awssdk/enhanced/dynamodb/mapper/StaticAttribute.java, services-custom/dynamodb-enhanced/src/test/java/software/amazon/awssdk/enhanced/dynamodb/mapper/StaticAttributeTest.java
=> Fix StaticAttribute#toBuilder() to include 'attributeConverter'

bom/pom.xml
The dynamodb-enhanced mapper is missing from the bom.  So it cannot easily be imported unlike the other components.
Line up his new module with the others.
No code change
=> Add dynamodb-enhanced to bom

.changes/next-release/bugfix-AWSSDKforJavav2-66d1f62.json, codegen/src/main/java/software/amazon/awssdk/codegen/poet/eventstream/EventStreamUtils.java, codegen/src/main/java/software/amazon/awssdk/codegen/poet/model/AwsServiceModel.java, codegen/src/test/java/software/amazon/awssdk/codegen/poet/model/SharedStreamAwsModelSpecTest.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/eventstream.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/inputeventstream.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/inputeventstreamtwo.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/sharedstream/eventstream.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/sharedstream/person.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/sharedstream/service-2.json, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/sharedstream/streambirthsrequest.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/sharedstream/streambirthsresponse.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/sharedstream/streamdeathsrequest.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/sharedstream/streamdeathsresponse.java
Event streams do not have to be 1:1 with operations, but the generation of event stream model types selects the first operation linked with an event stream when generating.  This change adds support for all associated operations to event stream interfaces and event types.
This brings event stream client generation closer to the models allowed by the event stream specification.
I added a generation test for a model that shares an event stream between two operations, and performed an end-to-end test offline with a test service that reuses event stream structures.
=> Support event streams that are shared between two operations.

.changes/next-release/feature-AmazonRDS-fb062ac.json, services/rds/src/main/java/software/amazon/awssdk/services/rds/internal/CopyDbClusterSnapshotPresignInterceptor.java, services/rds/src/main/java/software/amazon/awssdk/services/rds/internal/CreateDbClusterPresignInterceptor.java, services/rds/src/main/java/software/amazon/awssdk/services/rds/internal/RdsPresignInterceptor.java, services/rds/src/main/resources/codegen-resources/customization.config, services/rds/src/main/resources/software/amazon/awssdk/services/rds/execution.interceptors, services/rds/src/test/java/software/amazon/awssdk/services/rds/internal/PresignRequestHandlerTest.java, services/rds/src/test/java/software/amazon/awssdk/services/rds/internal/PresignRequestWireMockTest.java, services/rds/src/test/java/software/amazon/awssdk/services/rds/internal/RdsPresignInterceptorIntegrationTest.java
As with CopyDBSnapshot and CreateDBInstanceReadReplica, specifying this field will automatically populate the PresignedURL field with a valid value.
=> Add SourceRegion to CopyDBClusterSnapshot and CreateDBCluster operations.

.changes/next-release/feature-AWSSDKforJavav2-00d47cf.json, core/aws-core/src/main/java/software/amazon/awssdk/awscore/exception/AwsServiceException.java, core/protocols/aws-json-protocol/src/main/java/software/amazon/awssdk/protocols/json/internal/unmarshall/AwsJsonProtocolErrorUnmarshaller.java, core/protocols/aws-json-protocol/src/main/java/software/amazon/awssdk/protocols/json/internal/unmarshall/JsonResponseHandler.java, core/protocols/aws-query-protocol/src/main/java/software/amazon/awssdk/protocols/query/internal/unmarshall/AwsXmlErrorUnmarshaller.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/exception/SdkServiceException.java, test/protocol-tests/src/test/java/software/amazon/awssdk/protocol/tests/exception/AwsJsonExceptionTest.java, test/protocol-tests/src/test/java/software/amazon/awssdk/protocol/tests/exception/QueryExceptionTests.java, test/protocol-tests/src/test/java/software/amazon/awssdk/protocol/tests/exception/RestJsonExceptionTests.java, test/protocol-tests/src/test/java/software/amazon/awssdk/protocol/tests/exception/RestXmlExceptionTests.java
Adds a new `extendedRequestId` property to the `SdkServiceException` class and includes it in the contents of AwsServiceException messages.
Currently the only way to access this information from the exception is via the headers supplied by the `SdkHttpResponse` in the exception's `errorDetails`.  However when the AWS client is automatically retrying and causing my Lambda function to timeout due to the added time it takes to retry, I have no way to access this information.  AWS support requires this information in order to deep dive issues for some services such as S3.
Ran mvn clean install and the build succeeded.
=> Expose the extendedRequestId from SdkServiceException

pom.xml
Added AWS SDK for Java version number to the v2 API docs via POM configuration. (Also cleaned up the formatting of the footer, and made its year permanently up-to-date.)
Customers often come across a code snippet for the SDK for Java that links off to the API Reference materials. However, they don't know which version of the SDK it's for (v1 or v2) because only the main overview page shows this detail.
Local build
=> Add SDK version number to all API Reference doc pages

.changes/next-release/bugfix-AWSSDKforJavav2-5ba8894.json, codegen/src/main/java/software/amazon/awssdk/codegen/AddEmptyInputShape.java, codegen/src/main/java/software/amazon/awssdk/codegen/AddEmptyOutputShape.java, codegen/src/main/java/software/amazon/awssdk/codegen/naming/DefaultNamingStrategy.java, codegen/src/test/java/software/amazon/awssdk/codegen/IntermediateModelBuilderTest.java, codegen/src/test/java/software/amazon/awssdk/codegen/naming/DefaultNamingStrategyTest.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/c2j/collision/service-2.json
If a 'FooService' contains an operation named 'Foo', the generator will attempt to generate a 'FooRequest' that extends an abstract 'FooRequest'.  This adds 'Default' to the concrete class names only in cases where there is an operation with a clashing name.
Some simpler microservices do not adhere to the standard naming guidelines.  This allows clients to be generated for them.
This should only impact models for which non-compiling code would be generated today.  This was tested with a simple unit test, and out-of-band against a similar service model end-to-end.
=> Fix generation for services that contain operations with the same name as the service

.changes/next-release/bugfix-AWSSDKforJavav2-eb912cc.json, codegen/src/main/java/software/amazon/awssdk/codegen/IntermediateModelBuilder.java, codegen/src/main/java/software/amazon/awssdk/codegen/internal/Utils.java, codegen/src/main/java/software/amazon/awssdk/codegen/poet/eventstream/EventStreamUtils.java, codegen/src/main/java/software/amazon/awssdk/codegen/poet/model/AwsServiceModel.java, codegen/src/main/java/software/amazon/awssdk/codegen/poet/transform/protocols/EventStreamJsonMarshallerSpec.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/sharedstream/getrandompersonrequest.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/sharedstream/getrandompersonresponse.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/sharedstream/service-2.json
Event is just a marker that a structure can be used as an event; it does not limit its use outside of stream contexts.
Without this change, it is harder to add event streams to existing services and reuse existing structures defined for non-streaming operations.
I added unit tests, and ran this generator against a service that uses an event structure as an output for a non-streaming API.
=> Allow event structures to be used as operation outputs outside of streaming contexts.

.changes/next-release/bugfix-AmazonS3-74e484e.json, services/s3/src/it/java/software/amazon/awssdk/services/s3/GetObjectIntegrationTest.java, services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/handlers/GetObjectInterceptor.java, services/s3/src/main/resources/software/amazon/awssdk/services/s3/execution.interceptors
We're still investigating this issue (S3 behaving inconsistently) internally, but this issue has lingered for long enough. No reason for people to suffer while we try to sort out the laundry. 
Fixes #1209.
=> Check the x-amz-content-range header for GetObject responses when the Content-Range header is not returned by the service.

core/metrics-spi/pom.xml, core/metrics-spi/src/main/java/software/amazon/awssdk/metrics/MetricCategory.java, core/metrics-spi/src/main/java/software/amazon/awssdk/metrics/MetricCollection.java, core/metrics-spi/src/main/java/software/amazon/awssdk/metrics/MetricCollector.java, core/metrics-spi/src/main/java/software/amazon/awssdk/metrics/MetricPublisher.java, core/metrics-spi/src/main/java/software/amazon/awssdk/metrics/MetricRecord.java, core/metrics-spi/src/main/java/software/amazon/awssdk/metrics/SdkMetric.java, core/metrics-spi/src/main/java/software/amazon/awssdk/metrics/internal/DefaultMetricCollection.java, core/metrics-spi/src/main/java/software/amazon/awssdk/metrics/internal/DefaultMetricCollector.java, core/metrics-spi/src/main/java/software/amazon/awssdk/metrics/internal/DefaultMetricRecord.java, core/metrics-spi/src/main/java/software/amazon/awssdk/metrics/internal/DefaultSdkMetric.java, core/metrics-spi/src/main/java/software/amazon/awssdk/metrics/internal/util/MetricUtil.java, core/metrics-spi/src/test/java/software/amazon/awssdk/metrics/internal/DefaultMetricCollectionTest.java, core/metrics-spi/src/test/java/software/amazon/awssdk/metrics/internal/DefaultMetricCollectorTest.java, core/metrics-spi/src/test/java/software/amazon/awssdk/metrics/internal/DefaultSdkMetricRecordTest.java, core/metrics-spi/src/test/java/software/amazon/awssdk/metrics/internal/DefaultSdkMetricTest.java, core/pom.xml, docs/design/core/metrics/prototype/SdkMetric.java
=> Add default impls of SPI classes

.changes/next-release/feature-AWSMavenLambdaArchetype-6cb01fa.json, archetypes/archetype-lambda/README.md, archetypes/archetype-lambda/src/main/resources/META-INF/maven/archetype-metadata.xml, archetypes/archetype-lambda/src/main/resources/archetype-resources/pom.xml, archetypes/archetype-lambda/src/main/resources/archetype-resources/src/main/java/DependencyFactory.java, archetypes/archetype-lambda/src/test/resources/projects/apachehttpclient/archetype.properties, archetypes/archetype-lambda/src/test/resources/projects/apachehttpclient/reference/pom.xml, archetypes/archetype-lambda/src/test/resources/projects/apachehttpclient/reference/src/main/java/software/amazonaws/test/DependencyFactory.java, archetypes/archetype-lambda/src/test/resources/projects/dynamodbstreamsclient/reference/pom.xml, archetypes/archetype-lambda/src/test/resources/projects/nettyclient/reference/pom.xml, archetypes/archetype-lambda/src/test/resources/projects/urlhttpclient/reference/pom.xml, archetypes/archetype-lambda/src/test/resources/projects/wafregionalclient/reference/pom.xml
- Update the sdk client to use region from environment variable
- Fix module-info.class warning when compiling the generated project
- Fix README
```java
public static DynamoDbClient dynamoDbClient() {
return DynamoDbClient.builder()
.credentialsProvider(EnvironmentVariableCredentialsProvider.create())
.region(Region.of(System.getenv(SdkSystemSetting.AWS_REGION.environmentVariable())))
.httpClientBuilder(ApacheHttpClient.builder())
.build();
}
```
=> Update archetype-lambda 

http-client-spi/pom.xml, http-client-spi/src/main/java/software/amazon/awssdk/http/HttpExecuteRequest.java, http-client-spi/src/main/java/software/amazon/awssdk/http/HttpMetric.java, http-clients/apache-client/pom.xml, http-clients/apache-client/src/main/java/software/amazon/awssdk/http/apache/ApacheHttpClient.java, http-clients/apache-client/src/main/java/software/amazon/awssdk/http/apache/internal/NoOpMetricCollector.java, http-clients/apache-client/src/test/java/software/amazon/awssdk/http/apache/MetricReportingTest.java
=> Add apache HTTP request stats

.changes/next-release/bugfix-AWSSDKforJavav2-795fee6.json, core/auth/src/main/java/software/amazon/awssdk/auth/credentials/AwsBasicCredentials.java
[This page](https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/auth/credentials/AwsBasicCredentials.html) in the v2 javadocs mentions "AWS session token" in annotations but AwsBasicCredentials doesn't seem to support this (i.e. it only accepts two parameters, accessKeyId and secretAccessKey):
Removed the two mentions of the session token.
Incorrect information/confusing. V209538068
=> Update javadoc for AwsBasicCredentials

codegen/pom.xml, codegen/src/main/java/software/amazon/awssdk/codegen/poet/client/AsyncClientInterface.java, codegen/src/main/java/software/amazon/awssdk/codegen/poet/client/SyncClientClass.java, codegen/src/main/java/software/amazon/awssdk/codegen/poet/client/specs/JsonProtocolSpec.java, codegen/src/main/java/software/amazon/awssdk/codegen/poet/client/specs/QueryProtocolSpec.java, codegen/src/main/java/software/amazon/awssdk/codegen/poet/client/specs/XmlProtocolSpec.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/test-async-client-class.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/test-endpoint-discovery-async.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/test-endpoint-discovery-sync.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/test-json-async-client-interface.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/test-json-client-class.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/test-query-async-client-class.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/test-query-client-class.java, core/aws-core/pom.xml, core/aws-core/src/main/java/software/amazon/awssdk/awscore/metrics/AwsCoreMetric.java, core/sdk-core/pom.xml, core/sdk-core/src/main/java/software/amazon/awssdk/core/client/builder/SdkDefaultClientBuilder.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/client/config/SdkClientOption.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/client/handler/ClientExecutionParams.java, services/pom.xml, test/codegen-generated-classes-test/pom.xml, test/protocol-tests/pom.xml
Part of Implementing core metrics. This PR adds code to set up the metric collection and publishing for sync API calls.
=> Add setup code for API call metrics for sync

build-tools/src/main/resources/software/amazon/awssdk/checkstyle.xml, http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/internal/ChannelAttributeKey.java, http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/internal/Http1TunnelConnectionPool.java, http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/internal/ReleaseOnceChannelPool.java, http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/internal/http2/Http2MultiplexedChannelPool.java, http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/internal/utils/NettyUtils.java, http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/internal/utils/OrderedWriteChannelHandlerContext.java, http-clients/netty-nio-client/src/test/java/software/amazon/awssdk/http/nio/netty/internal/utils/NettyUtilsTest.java
This commit prevents the Netty client from throwing an exception in cases where
it tries to declare an attribute key and the key already exists. This can happen
when separate instances of the SDK are loaded by different classloaders, but the
Netty classes loaded by a third and shared by the other classloaders.
Fixes #1886
=> Safely declare Netty AttributeKeys

.changes/next-release/bugfix-AWSSDKforJavav2-9e5b030.json, core/sdk-core/pom.xml, core/sdk-core/src/main/java/software/amazon/awssdk/core/async/AsyncRequestBody.java, core/sdk-core/src/test/java/software/amazon/awssdk/core/async/AsyncRequestBodyTest.java
=> Remove unnecessary copy

core/metrics-spi/src/main/java/software/amazon/awssdk/metrics/internal/DefaultMetricCollection.java, core/metrics-spi/src/main/java/software/amazon/awssdk/metrics/internal/DefaultMetricRecord.java, http-client-spi/src/main/java/software/amazon/awssdk/http/Http2Metric.java, http-client-spi/src/main/java/software/amazon/awssdk/http/HttpMetric.java, http-clients/apache-client/src/main/java/software/amazon/awssdk/http/apache/ApacheHttpClient.java, http-clients/apache-client/src/test/java/software/amazon/awssdk/http/apache/MetricReportingTest.java, http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/internal/ChannelAttributeKey.java, http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/internal/IdleConnectionCountingChannelPool.java, http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/internal/NettyRequestExecutor.java, http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/internal/NettyRequestMetrics.java, http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/internal/http2/Http2MultiplexedChannelPool.java, http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/internal/http2/HttpOrHttp2ChannelPool.java, http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/internal/http2/MultiplexedChannelRecord.java, http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/internal/utils/BetterFixedChannelPool.java, http-clients/netty-nio-client/src/test/java/software/amazon/awssdk/http/nio/netty/Http2MetricsTest.java, http-clients/netty-nio-client/src/test/java/software/amazon/awssdk/http/nio/netty/NettyNioAsyncHttpClientWireMockTest.java, http-clients/netty-nio-client/src/test/java/software/amazon/awssdk/http/nio/netty/internal/IdleConnectionCountingChannelPoolTest.java, http-clients/netty-nio-client/src/test/java/software/amazon/awssdk/http/nio/netty/internal/http2/Http2MultiplexedChannelPoolTest.java, http-clients/netty-nio-client/src/test/java/software/amazon/awssdk/http/nio/netty/internal/http2/HttpOrHttp2ChannelPoolTest.java, http-clients/netty-nio-client/src/test/java/software/amazon/awssdk/http/nio/netty/internal/utils/BetterFixedChannelPoolTest.java
Updated existing HTTP metrics to specify that they are "concurrency", not "connections". For HTTP/2, we can't calculate the maximum number of connections, and concurrency is more useful to customers anyway.
Fixed the AVAILABLE_CONCURRENCY in Netty to actually be the number of established but idle concurrency, not the difference between max concurrency and leased concurrency.
=> Added support for HTTP/2 metrics to Netty.

core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/util/MetricUtils.java, services/transcribestreaming/src/it/java/software/amazon/awssdk/services/transcribestreaming/TranscribeStreamingIntegrationTest.java, test/codegen-generated-classes-test/src/test/java/software/amazon/awssdk/services/metrics/async/AsyncEventStreamingCoreMetricsTest.java, test/codegen-generated-classes-test/src/test/java/software/amazon/awssdk/services/metrics/async/BaseAsyncCoreMetricsTest.java
Add functional and integ tests to verify async core metrics for event streaming operation
=> Async core metrics part3: add tests to verify async core metrics for event streaming apis

.changes/next-release/bugfix-AmazonDynamoDBEnhancedClient-01e66f6.json, services-custom/dynamodb-enhanced/src/main/java/software/amazon/awssdk/enhanced/dynamodb/internal/converter/attribute/OptionalAttributeConverter.java, services-custom/dynamodb-enhanced/src/test/java/software/amazon/awssdk/enhanced/dynamodb/internal/converter/attribute/OptionalAttributeValueConverterTest.java, services-custom/dynamodb-enhanced/src/test/java/software/amazon/awssdk/enhanced/dynamodb/model/TransactWriteItemsEnhancedRequestTest.java
=> Fix NPE in OptionalAttributeValueConverter

core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/util/Mimetype.java, core/sdk-core/src/test/java/software/amazon/awssdk/core/internal/util/MimetypeTest.java
Fixed wrong Mimetype result for null fileName to keep consistency with our API contract;
Deleted wrongly pasted javadocs;
#1811 
There is no newly added unit test for this change because it's impossible to set the fileName as null here in the path.
=> Fixed wrong Mimetype result for null fileName and deleted wrongly pasted javadocs

.changes/next-release/bugfix-AWSSDKforJavav2-410cf46.json, codegen/src/main/java/software/amazon/awssdk/codegen/poet/client/AsyncClientClass.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/test-async-client-class.java
This is another case of SDK code generation failing when the event's structure name and the structure member name are not identical.
This is similar to https://github.com/aws/aws-sdk-java-v2/pull/1821 which fixed the problem for output event streams.
This fixes generation for services that do not align their structure member names and structure type names when modelling event streams.
I modified the existing unit tests.  The previously generated client appears to be nonfunctional, as it references an `InputEventOne` class and an `InputEventOneMarshaller` class, but the [C2JModel](https://github.com/aws/aws-sdk-java-v2/blob/f6e3d9f6172368eafd7a0d2cfcd871d83e754372/codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/c2j/json/service-2.json#L445) only contains shapes …
=> Fix event marshaller binding for input event streams.

codegen/src/main/java/software/amazon/awssdk/codegen/poet/client/AsyncClientClass.java, codegen/src/main/java/software/amazon/awssdk/codegen/poet/client/SyncClientClass.java, codegen/src/main/java/software/amazon/awssdk/codegen/poet/client/specs/ProtocolSpec.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/test-async-client-class.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/test-endpoint-discovery-async.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/test-endpoint-discovery-sync.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/test-json-client-class.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/test-query-async-client-class.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/test-query-client-class.java, core/aws-core/src/main/java/software/amazon/awssdk/awscore/client/handler/AwsClientHandlerUtils.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/RequestOverrideConfiguration.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/client/builder/SdkDefaultClientBuilder.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/client/config/ClientOverrideConfiguration.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/client/config/SdkClientOption.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/http/pipeline/stages/AsyncApiCallMetricCollectionStage.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/util/MetricUtils.java, core/sdk-core/src/test/java/software/amazon/awssdk/core/RequestOverrideConfigurationTest.java, core/sdk-core/src/test/java/software/amazon/awssdk/core/client/config/ClientOverrideConfigurationTest.java, core/sdk-core/src/test/java/software/amazon/awssdk/core/internal/http/timers/AsyncHttpClientApiCallTimeoutTests.java, core/sdk-core/src/test/java/software/amazon/awssdk/core/internal/util/MetricUtilsTest.java, services/transcribestreaming/src/it/java/software/amazon/awssdk/services/transcribestreaming/TranscribeStreamingIntegrationTest.java, test/codegen-generated-classes-test/src/test/java/software/amazon/awssdk/services/metrics/CoreMetricsTest.java, test/codegen-generated-classes-test/src/test/java/software/amazon/awssdk/services/metrics/SyncClientMetricPublisherResolutionTest.java, test/codegen-generated-classes-test/src/test/java/software/amazon/awssdk/services/metrics/async/AsyncClientMetricPublisherResolutionTest.java, test/codegen-generated-classes-test/src/test/java/software/amazon/awssdk/services/metrics/async/AsyncCoreMetricsTest.java, test/codegen-generated-classes-test/src/test/java/software/amazon/awssdk/services/metrics/async/AsyncEventStreamingCoreMetricsTest.java, test/codegen-generated-classes-test/src/test/java/software/amazon/awssdk/services/metrics/async/AsyncStreamingCoreMetricsTest.java, test/codegen-generated-classes-test/src/test/java/software/amazon/awssdk/services/metrics/async/BaseAsyncCoreMetricsTest.java
- Allow lists of publishers to be set.
Allow setting of metric pubishers to be set on the client of request override
rather than a single publisher, making using multiple MetricPublishers per
client or request easier.
- Remove any non-core usage of MetricUtils.
- Fix metrics test in TranscribeStreamIntegrationTest.
=> Mutiple metrics fixes

core/annotations/src/main/java/software/amazon/awssdk/annotations/SdkPreviewApi.java, core/metrics-spi/src/main/java/software/amazon/awssdk/metrics/LoggingMetricPublisher.java, core/metrics-spi/src/main/java/software/amazon/awssdk/metrics/MetricCategory.java, core/metrics-spi/src/main/java/software/amazon/awssdk/metrics/MetricCollection.java, core/metrics-spi/src/main/java/software/amazon/awssdk/metrics/MetricCollector.java, core/metrics-spi/src/main/java/software/amazon/awssdk/metrics/MetricLevel.java, core/metrics-spi/src/main/java/software/amazon/awssdk/metrics/MetricPublisher.java, core/metrics-spi/src/main/java/software/amazon/awssdk/metrics/NoOpMetricCollector.java, core/metrics-spi/src/main/java/software/amazon/awssdk/metrics/SdkMetric.java, core/metrics-spi/src/main/java/software/amazon/awssdk/metrics/package-info.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/RequestOverrideConfiguration.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/client/config/ClientOverrideConfiguration.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/metrics/CoreMetric.java, http-client-spi/src/main/java/software/amazon/awssdk/http/Http2Metric.java, http-client-spi/src/main/java/software/amazon/awssdk/http/HttpMetric.java, metric-publishers/cloudwatch-metric-publisher/src/main/java/software/amazon/awssdk/metrics/publishers/cloudwatch/CloudWatchMetricPublisher.java, metric-publishers/cloudwatch-metric-publisher/src/main/java/software/amazon/awssdk/metrics/publishers/cloudwatch/package-info.java
Create `@SdkPreviewApi` annotation and mark metrics related classes and methods.
=> Add preview annotations

.changes/next-release/feature-AmazonDynamoDBEnhancedClient-532841e.json, services-custom/dynamodb-enhanced/src/main/java/software/amazon/awssdk/enhanced/dynamodb/internal/converter/attribute/AtomicBooleanAttributeConverter.java, services-custom/dynamodb-enhanced/src/main/java/software/amazon/awssdk/enhanced/dynamodb/internal/converter/attribute/BooleanAttributeConverter.java, services-custom/dynamodb-enhanced/src/test/java/software/amazon/awssdk/enhanced/dynamodb/converters/attribute/BooleanAttributeConvertersTest.java
The 1.11.x DynamoDB mapper persisted booleans as 0s and 1s (in the 'number' type). For backwards-compatibility, we should be able to read these values. The values will be converted to boolean types if they are written back to DynamoDB.
Fixes #1912
=> Updated DynamoDBEnhancedClient to support '0' and '1' as valid boolean values

codegen/src/main/java/software/amazon/awssdk/codegen/poet/client/specs/JsonProtocolSpec.java, codegen/src/main/java/software/amazon/awssdk/codegen/poet/client/specs/QueryProtocolSpec.java, codegen/src/main/java/software/amazon/awssdk/codegen/poet/client/specs/XmlProtocolSpec.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/test-async-client-class.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/test-endpoint-discovery-async.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/test-query-async-client-class.java
Return whenComplete's result, so that it's easier to say that "when the execute
future completes, metrics have been published".
=> Return post-metric publish stage

services-custom/dynamodb-enhanced/README.md
Fix the example about a flat map
I want to live in a better world.
Tested by looking into it.
Yes.
=> Fix return type in the example

.changes/next-release/feature-AWSSDKforJavav2-67e3ac4.json, build-tools/src/main/resources/software/amazon/awssdk/spotbugs-suppressions.xml, core/sdk-core/src/main/java/software/amazon/awssdk/core/BytesWrapper.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/ResponseBytes.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/SdkBytes.java, core/sdk-core/src/test/java/software/amazon/awssdk/core/ResponseBytesTest.java, core/sdk-core/src/test/java/software/amazon/awssdk/core/SdkBytesTest.java
Reduced the number of payload data copies on some code paths.
Fixes #1959.
=> Added an "unsafe" way to retrieve a byte array from `SdkBytes` and `ResponseBytes` without copying the data.

.changes/next-release/bugfix-AmazonDynamoDBStreamingClient-1095bd2.json, services/dynamodb/src/main/resources/codegen-resources/dynamodbstreams/customization.config
Enable CRC to work correctly with gzipped http responses in the DynamoDBStreaming client. This had already been enabled in the DynamoDB client.
A customer was not able to successfully read compressed responses received using the DynamoDBStreaming client.
Had client test this fix.
=> DynamoDbStreaming: Fix for CRC of compressed responses

.changes/next-release/bugfix-AWSSDKforJavav2-75385bc.json, CONTRIBUTING.md, codegen/src/test/java/software/amazon/awssdk/codegen/TestStringUtils.java, codegen/src/test/java/software/amazon/awssdk/codegen/emitters/PoetGeneratorTaskIntegrationTest.java, codegen/src/test/java/software/amazon/awssdk/codegen/model/intermediate/DocumentationBuilderTest.java
Adding convenience method that allows to replace '\n' characters with the platform-dependent ones and applying it to affected test data.
Partial fix for #986. Namely for the issue [described in this comment](https://github.com/aws/aws-sdk-java-v2/issues/986#issuecomment-452976266).
Re-run `software.amazon.awssdk.codegen.model.intermediate.DocumentationBuilderTest` and `software.amazon.awssdk.codegen.emitters.PoetGeneratorTaskIntegrationTest`, which were failing previously.
=> #986 Fixing codegen's unit- and integration tests on Windows systems

http-clients/apache-client/src/main/java/software/amazon/awssdk/http/apache/ApacheHttpClient.java, http-clients/apache-client/src/test/java/software/amazon/awssdk/http/apache/ApacheHttpClientDefaultWireMockTest.java, http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/NettyNioAsyncHttpClient.java, http-clients/netty-nio-client/src/test/java/software/amazon/awssdk/http/nio/netty/NettyNioAsyncHttpClientDefaultWireMockTest.java, http-clients/url-connection-client/src/test/java/software/amazon/awssdk/http/urlconnection/UrlConnectionHttpClientDefaultWireMockTest.java, test/http-client-tests/src/main/java/software/amazon/awssdk/http/SdkHttpClientDefaultTestSuite.java
Add create method for Apache and Netty HttpClient.
=> Add create method for Apache and Netty HttpClient

http-clients/aws-crt-client/src/main/java/software/amazon/awssdk/http/crt/AwsCrtAsyncHttpClient.java, http-clients/aws-crt-client/src/main/java/software/amazon/awssdk/http/crt/internal/CrtRequestContext.java, http-clients/aws-crt-client/src/main/java/software/amazon/awssdk/http/crt/internal/CrtRequestExecutor.java, http-clients/aws-crt-client/src/test/java/software/amazon/awssdk/http/crt/CrtHttpClientTestUtils.java, http-clients/aws-crt-client/src/test/java/software/amazon/awssdk/http/crt/internal/CrtRequestExecutorTest.java, http-clients/aws-crt-client/src/test/resources/jetty-logging.properties, test/http-client-tests/pom.xml, test/http-client-tests/src/main/java/software/amazon/awssdk/http/HttpTestUtils.java, test/http-client-tests/src/main/java/software/amazon/awssdk/http/RecordingNetworkTrafficListener.java, test/http-client-tests/src/main/java/software/amazon/awssdk/http/RecordingResponseHandler.java
- Refactoring - moving the request execution logic to a separate class 
- Invoke `responseHandler#onError` when the request future is cancelled
There are two commits, easier to review one by one
Added test
=> Refactoring and request future cancellation

http-clients/aws-crt-client/src/it/java/software/amazon/awssdk/http/crt/AwsCrtClientCallingPatternIntegrationTest.java, http-clients/aws-crt-client/src/it/java/software/amazon/awssdk/http/crt/AwsCrtClientKmsIntegrationTest.java, http-clients/aws-crt-client/src/it/java/software/amazon/awssdk/http/crt/AwsCrtClientS3IntegrationTest.java, http-clients/aws-crt-client/src/main/java/software/amazon/awssdk/http/crt/AwsCrtAsyncHttpClient.java, http-clients/aws-crt-client/src/test/java/software/amazon/awssdk/http/crt/AwsCrtHttpClientSpiVerificationTest.java, http-clients/aws-crt-client/src/test/java/software/amazon/awssdk/http/crt/AwsCrtHttpClientWireMockTest.java, http-clients/aws-crt-client/src/test/java/software/amazon/awssdk/http/crt/H1ServerBehaviorTest.java, http-clients/aws-crt-client/src/test/java/software/amazon/awssdk/http/crt/ProxyWireMockTest.java, pom.xml, test/sdk-benchmarks/pom.xml, test/sdk-benchmarks/src/main/java/software/amazon/awssdk/benchmark/apicall/httpclient/async/BaseCrtBenchmark.java, test/stability-tests/pom.xml, test/stability-tests/src/it/java/software/amazon/awssdk/stability/tests/cloudwatch/CloudWatchCrtAsyncStabilityTest.java, test/stability-tests/src/it/java/software/amazon/awssdk/stability/tests/s3/S3CrtAsyncStabilityTest.java, test/stability-tests/src/it/java/software/amazon/awssdk/stability/tests/sqs/SqsCrtAsyncStabilityTest.java
- Bump up CRT version
- Remove eventLoopGroup and hostResolver configs. A static event loop group and host resolver will be used.
We will add customized elg config back once we figure out if we can/want to create an `SdkEventLoopGroup` w/o exposing the underlying EventLoopGroup
=> Remove eventLoopGroup and hostResolver configs

.changes/next-release/feature-AmazonSTS-289d9e7.json, services/sts/src/main/java/software/amazon/awssdk/services/sts/auth/StsCredentialsProvider.java, services/sts/src/test/java/software/amazon/awssdk/services/sts/auth/StsCredentialsProviderTestBase.java
Allow clients to specify the time (relative to expiration) for when to refresh STS session tokens.
The default STSCredentialsProvider's strategy for refreshing STS sessions is to wait until the session is almost stale and to refresh it either 5 minutes (prefetch) or 1 minute (stale) before it expires. This works great for most use cases. However, it doesn't work well for pre-signed S3 urls. For example, let's say I want to pre-sign an s3 URL that will be good for 90 minutes AND I'm signing the URL with an assumed STS role's credentials. The URL's effective expiration is the min(url expiration, sts session expiration). In other words, if you have STS session credentials that last for 60 minutes, and you want to hand out a URL that will last for 30 minutes, any URLs signed with said session …
=> Make STSCredentialsProvider prefetch and stale times configurable

.changes/next-release/bugfix-AWSS3Control-1ad7752.json, services/s3control/pom.xml, services/s3control/src/main/resources/codegen-resources/customization.config, services/s3control/src/test/java/software/amazon/awssdk/services/s3control/functionaltests/CreateJobFunctionalTest.java, services/s3control/src/test/resources/log4j.properties
Changes the definition of the document error root to what is used in AWS S3, so that errors are fully parsed. 
To this point, errors returned from S3Control have lost their XML content and only the error type has been returned, showing null: 
~~~
software.amazon.awssdk.services.s3control.model.S3ControlException: null
~~~
With this change, errors are parsed correctly as:
~~~
software.amazon.awssdk.services.s3control.model.S3ControlException: Missing role arn 
(Service: S3Control, Status Code: 400, Request ID: 4T5H9GEV7H3K9MCJ, Extended Request ID: USkN9APZoEVT0...)
~~~
- Unit tests and functional tests
=> Parse XML errors like in S3

codegen/src/main/java/software/amazon/awssdk/codegen/poet/waiters/BaseWaiterClassSpec.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/waiters/query-async-waiter-class.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/waiters/query-sync-waiter-class.java, services/autoscaling/src/it/java/software/amazon/awssdk/services/autoscaling/waiters/AutoScalingWaiterTest.java, services/dynamodb/src/test/java/software/amazon/awssdk/services/dynamodb/WaitersUserAgentTest.java, services/ecs/src/it/java/software/amazon/awssdk/services/ecs/waiters/EcsWaiterTest.java
Currently, there is no signs for Waiters in the ```User-Agent``` header, and to track the usage of waiters, we should append a specific user agent for waiters in the header.
The ```codegen``` module is modified, adding the method appending userAgent for waiters in all the operations related to the waiters.
The generated dynamodb client is tested with the waiters. There are two WireMock tests verifying if the requests triggered by the waiters include the ```WAITERS``` user agent in them.
=> Append User-Agent for Waiters operations

codegen/src/main/java/software/amazon/awssdk/codegen/docs/WaiterDocs.java, codegen/src/main/java/software/amazon/awssdk/codegen/poet/waiters/BaseWaiterInterfaceSpec.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/waiters/query-async-waiter-interface.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/waiters/query-sync-waiter-interface.java
- Add consumer builder overload for waiter methods and pollingStrategy
- add static create method in service waiters
updated codegen tests.
=> Add consumer builder overload methods

buildspecs/noop.yml
Runtimes aren't needed, and the runtimes available depend on the image, so we shouldn't depend on any specific runtime so that we can use the no-op buildspec on any image.
=> Remove runtime from no-op buildspec.

.changes/next-release/bugfix-AWSSDKforJavav2-985054b.json, .changes/next-release/bugfix-AWSSDKforJavav2-9917e4a.json, core/protocols/aws-json-protocol/src/main/java/software/amazon/awssdk/protocols/json/internal/unmarshall/JsonProtocolUnmarshaller.java, core/protocols/aws-xml-protocol/src/main/java/software/amazon/awssdk/protocols/xml/internal/unmarshall/XmlProtocolUnmarshaller.java, test/protocol-tests-core/src/main/resources/software/amazon/awssdk/protocol/suites/cases/rest-core-output.json
Previously, REST-XML services would treat missing payloads as empty payloads, and REST-JSON services would throw a NullPointerException.
=> Fixed the behavior of REST-XML and REST-JSON services that respond with no payload.

codegen/src/main/java/software/amazon/awssdk/codegen/docs/WaiterDocs.java, codegen/src/main/java/software/amazon/awssdk/codegen/poet/client/AsyncClientClass.java, codegen/src/main/java/software/amazon/awssdk/codegen/poet/waiters/AsyncWaiterClassSpec.java, codegen/src/main/java/software/amazon/awssdk/codegen/poet/waiters/AsyncWaiterInterfaceSpec.java, codegen/src/main/java/software/amazon/awssdk/codegen/poet/waiters/BaseWaiterClassSpec.java, codegen/src/main/java/software/amazon/awssdk/codegen/poet/waiters/BaseWaiterInterfaceSpec.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/test-query-async-client-class.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/waiters/query-async-waiter-class.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/waiters/query-async-waiter-interface.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/waiters/query-sync-waiter-class.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/waiters/query-sync-waiter-interface.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/waiters/AsyncWaiterExecutor.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/waiters/DefaultAsyncWaiter.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/waiters/DefaultWaiter.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/waiters/DefaultWaiterResponse.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/waiters/WaiterConfiguration.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/waiters/WaiterExecutor.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/waiters/WaiterExecutorHelper.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/waiters/WaiterBuilder.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/waiters/WaiterOverrideConfiguration.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/waiters/WaiterResponse.java, core/sdk-core/src/test/java/software/amazon/awssdk/core/internal/waiters/DefaultWaiterResponseTest.java, core/sdk-core/src/test/java/software/amazon/awssdk/core/internal/waiters/WaiterConfigurationTest.java, core/sdk-core/src/test/java/software/amazon/awssdk/core/waiters/AsyncWaiterTest.java, core/sdk-core/src/test/java/software/amazon/awssdk/core/waiters/BaseWaiterTest.java, core/sdk-core/src/test/java/software/amazon/awssdk/core/waiters/WaiterOverrideConfigurationTest.java, core/sdk-core/src/test/java/software/amazon/awssdk/core/waiters/WaiterTest.java, services/autoscaling/src/it/java/software/amazon/awssdk/services/autoscaling/waiters/AutoScalingWaiterTest.java, services/ecs/src/it/java/software/amazon/awssdk/services/ecs/waiters/EcsWaiterTest.java, test/codegen-generated-classes-test/src/test/java/software/amazon/awssdk/services/waiters/WaiterResourceTest.java
- rename `{Service}Waiter.Builder#executorService` -> `{Service}Waiter.Builder#scheduledExecutorService` 
- rename `PollingStratege` -> `WaiterOverrideConfiguration` and `Waiter.Builder#pollingStrategy` -> `Waiter.Builder#overrideConfiguration`
- rename `WaiterResponse#responseOrExecption` -> `WaiterResponse#matched`
- provide default values for `waiterOverrideConfiguration`
- rename `maxWaitTime` -> `waitTimeout`
=> Various renaming and provide default values for waiterOverrideConfiguration

services/dynamodb/src/it/java/software/amazon/awssdk/services/dynamodb/WaitersIntegrationTest.java, test/codegen-generated-classes-test/src/test/java/software/amazon/awssdk/services/waiters/WaitersAsyncFunctionalTest.java, test/codegen-generated-classes-test/src/test/java/software/amazon/awssdk/services/waiters/WaitersSyncFunctionalTest.java
Add integration tests for DynamoDB Waiters;
Add functional tests for RestJsonWithWaiters Waiters;
=> Add functional tests and integration tests for Waiters

codegen/src/main/java/software/amazon/awssdk/codegen/docs/WaiterDocs.java, codegen/src/main/java/software/amazon/awssdk/codegen/poet/waiters/BaseWaiterClassSpec.java, codegen/src/main/java/software/amazon/awssdk/codegen/poet/waiters/BaseWaiterInterfaceSpec.java, codegen/src/main/resources/software/amazon/awssdk/codegen/waiters/WaitersRuntime.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/waiters/query-async-waiter-class.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/waiters/query-async-waiter-interface.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/waiters/query-sync-waiter-class.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/waiters/query-sync-waiter-interface.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/waiters/AsyncWaiterExecutor.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/waiters/DefaultAsyncWaiter.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/waiters/DefaultWaiter.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/waiters/WaiterExecutor.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/waiters/AsyncWaiter.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/waiters/Waiter.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/waiters/WaiterOverrideConfiguration.java, core/sdk-core/src/test/java/software/amazon/awssdk/core/waiters/AsyncWaiterTest.java, core/sdk-core/src/test/java/software/amazon/awssdk/core/waiters/WaiterOverrideConfigurationTest.java, core/sdk-core/src/test/java/software/amazon/awssdk/core/waiters/WaiterTest.java, test/codegen-generated-classes-test/src/main/resources/codegen-resources/waiters/waiters-2.json, test/codegen-generated-classes-test/src/test/java/software/amazon/awssdk/services/waiters/WaitersAsyncFunctionalTest.java, test/codegen-generated-classes-test/src/test/java/software/amazon/awssdk/services/waiters/WaitersRuntimeDefaultAcceptorsTest.java, test/codegen-generated-classes-test/src/test/java/software/amazon/awssdk/services/waiters/WaitersSyncFunctionalTest.java
- add per request waiterOverrideConfiguration overloaded waiter operation
- remove `throwOnUnmatchedExceptionWaiter` from `WaitersRuntime` because it would cause async waiter future to hang. unmatched exception is handled in the generic waiter implementations
- add try-catch in generic async waiter `whenComplete` block to fix the issue where any exception thrown there could cause the future to hang
- add more functional tests
=> add per request waiterOverrideConfiguration overloaded waiter operation

codegen/src/main/java/software/amazon/awssdk/codegen/docs/WaiterDocs.java, codegen/src/main/java/software/amazon/awssdk/codegen/poet/client/AsyncClientInterface.java, codegen/src/main/java/software/amazon/awssdk/codegen/poet/client/SyncClientInterface.java, codegen/src/main/java/software/amazon/awssdk/codegen/poet/waiters/BaseWaiterInterfaceSpec.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/waiters/query-async-waiter-interface.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/waiters/query-sync-waiter-interface.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/waiters/DefaultWaiterResponse.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/waiters/ResponseOrException.java, services/dynamodb/src/it/java/software/amazon/awssdk/services/dynamodb/WaitersIntegrationTest.java, test/codegen-generated-classes-test/src/main/resources/codegen-resources/waiters/waiters-2.json, test/codegen-generated-classes-test/src/test/java/software/amazon/awssdk/services/waiters/WaitersAsyncFunctionalTest.java, test/codegen-generated-classes-test/src/test/java/software/amazon/awssdk/services/waiters/WaitersSyncFunctionalTest.java
- Fix javadocs
- add more tests
- remove unnecessary methods
=> Fix javadocs, add more tests, remove unnecessary methods

services/s3control/src/it/java/software.amazon.awssdk.services.s3control/S3ControlIntegrationTest.java
Remove flaky integ test that is testing service and not the SDK
=> Remove flaky integ test

.changes/next-release/bugfix-ApacheHTTPClient-3ccb50d.json, http-clients/apache-client/src/main/java/software/amazon/awssdk/http/apache/internal/impl/ApacheHttpRequestFactory.java, http-clients/apache-client/src/test/java/software/amazon/awssdk/http/apache/internal/impl/ApacheHttpRequestFactoryTest.java, services/s3/src/it/java/software/amazon/awssdk/services/s3/KeysWithLeadingSlashIntegrationTest.java
Fixed an issue in Apache HTTP client where a request with path parameter as a single slash threw invalid host name error.
**Root case:**
In previous implementation, all occurrences of `//` were replaced with `/%2F`, including the one right after the http scheme, causing `http://localhost/%2F` -> `http:/%2Flocalhost/%2F`
Added integ tests and unit tests
=> Fix slash path parameter in apache http client

.changes/next-release/bugfix-AWSLambdaMavenArchetype-9037fcf.json, archetypes/archetype-lambda/pom.xml
Fixed an issue where archetype generation failed with latest maven-archetype-plugin by
copying the global.vm to archetype resources folder because it's no longer global any more ¯\_(ツ)_/¯
I tried other ways such as using relative path and none of them worked. 
#1981 
Unit tests passed.
Tried using both new version of old version of archetype plugin to generate a new project and both worked.
=> Fix archetype-lambda

.travis.yml
Remove openjdk11 because the openjdk11 job took longer than 50 mins, which is a hard limit on Travis for public repos.
```
The job exceeded the maximum time limit for jobs, and has been terminated.
```
=> Remove openjdk11 because the build exceeds the allowed time limit

codegen/src/main/java/software/amazon/awssdk/codegen/customization/processors/DefaultCustomizationProcessor.java, codegen/src/main/java/software/amazon/awssdk/codegen/customization/processors/ExcludeEventNameFromVisitMethodProcessor.java, codegen/src/main/java/software/amazon/awssdk/codegen/model/config/customization/CustomizationConfig.java, codegen/src/main/java/software/amazon/awssdk/codegen/poet/eventstream/EventStreamResponseHandlerSpec.java, codegen/src/main/java/software/amazon/awssdk/codegen/poet/eventstream/EventStreamUtils.java, codegen/src/main/java/software/amazon/awssdk/codegen/poet/eventstream/EventStreamVisitorBuilderImplSpec.java, codegen/src/main/java/software/amazon/awssdk/codegen/poet/eventstream/EventStreamVisitorBuilderInterfaceSpec.java, codegen/src/main/java/software/amazon/awssdk/codegen/poet/eventstream/EventStreamVisitorInterfaceSpec.java, codegen/src/test/java/software/amazon/awssdk/codegen/customization/processors/ExcludeEventNameFromVisitMethodProcessorTest.java, codegen/src/test/resources/software/amazon/awssdk/codegen/emitters/customizations/processors/excludeventnamefromvisitor/happy-case-customization.config, codegen/src/test/resources/software/amazon/awssdk/codegen/emitters/customizations/processors/excludeventnamefromvisitor/multiple-event-types-same-shape.config, codegen/src/test/resources/software/amazon/awssdk/codegen/emitters/customizations/processors/excludeventnamefromvisitor/service-2.json, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/c2j/json/customization.config, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/test-async-client-class.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/eventstream/test-response-handler.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/eventstream/test-visitor-builder.java, services/kinesis/src/main/resources/codegen-resources/customization.config, services/transcribestreaming/src/main/resources/codegen-resources/customization.config
This commit fixes event visitor method generation by including the *event type*
in the visitor name. Note that event type here is actually the member name in
the encompassing eventstream structure, *not* the Java class of the event.
For example, in the example below, "Foo" is the event type.
```json
"MyEventStream": {
"type": "structure",
"eventstream": true,
"members": {
"Foo": {
"shape": "Bar"
}
}
}
```
To ensure that this change is backwards compatible with existing services that
have event streams (Transcribe Streaming and Kinesis), we also include a
customization to supress this behavior keep the method name as "visit".
Note that by sheer luck, the existing consumer method setters, e.g.
```java
Builder onSubscribeToShardEvent(Consumer<SubscribeToShardEvent>);
```
are unaffected by …
=> Include event type in visitor name

test/stability-tests/src/it/java/software/amazon/awssdk/stability/tests/utils/StabilityTestRunner.java
This maximum was being exceeded by an expected set of threads. Also named the threads created by `FileAsyncRequestBody` and `FileAsyncResponseTransformer` for more easy identification.
=> Increased maximum threads allowed by stability tests.

.changes/next-release/bugfix-AWSSDKforJavav2-f7960d9.json, core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/http/loader/DefaultSdkAsyncHttpClientBuilder.java
Current error message combines string on multiple lines without a space between words resulting in a message that reads:
```
... from any provider in thechain. You ...
```
=> Add spaces between new lines in ClientBuilder error message

.changes/next-release/feature-AWSSingleSignon-9e785be.json, core/annotations/src/main/java/software/amazon/awssdk/annotations/SdkInternalApi.java, core/auth/src/main/java/software/amazon/awssdk/auth/credentials/ProfileCredentialsProviderFactory.java, core/auth/src/main/java/software/amazon/awssdk/auth/credentials/internal/ProfileCredentialsUtils.java, core/profiles/src/main/java/software/amazon/awssdk/profiles/ProfileFileLocation.java, core/profiles/src/main/java/software/amazon/awssdk/profiles/ProfileProperty.java, services/sso/pom.xml, services/sso/src/main/java/software/amazon/awssdk/services/sso/auth/ExpiredTokenException.java, services/sso/src/main/java/software/amazon/awssdk/services/sso/auth/SsoCredentialsProvider.java, services/sso/src/main/java/software/amazon/awssdk/services/sso/auth/SsoProfileCredentialsProviderFactory.java, services/sso/src/main/java/software/amazon/awssdk/services/sso/internal/SessionCredentialsHolder.java, services/sso/src/main/java/software/amazon/awssdk/services/sso/internal/SsoAccessTokenProvider.java, services/sso/src/main/java/software/amazon/awssdk/services/sso/internal/SsoTokenFileUtils.java, services/sso/src/test/java/software/amazon/awssdk/services/sso/auth/SsoCredentialsProviderTest.java, services/sso/src/test/java/software/amazon/awssdk/services/sso/auth/SsoProfileCredentialsProviderFactoryTest.java, services/sso/src/test/java/software/amazon/awssdk/services/sso/auth/SsoProfileTest.java, services/sso/src/test/java/software/amazon/awssdk/services/sso/internal/SsoAccessTokenProviderTest.java, services/sso/src/test/java/software/amazon/awssdk/services/sso/internal/SsoTokenFileUtilsTest.java, utils/src/main/java/software/amazon/awssdk/utils/UserHomeDirectoryUtils.java, utils/src/test/java/software/amazon/awssdk/testutils/EnvironmentVariableHelper.java, utils/src/test/java/software/amazon/awssdk/utils/UserHomeDirectoryUtilsTest.java
Add support for SSO Credentials Provider.
In this pr, a credential provider that exchanges a resolved SSO login token for temporary AWS credentials is added. Besides, several new classes and tests are added to enable this credentials provider.
Main Updates since the first review:
1. Merged the `SsoCredentialsProvider` into part of the `ProfileCredentialsProvider` so the profile addressing part can be better taken care of;
2. Separate the generation of cached token path and resolution of access token to make it more flexible;
3. Updated all the tests to make them match the current code and achieve better coverage;
Besides the main changes for SSO, there are also some small changes to the code:
1. Corrected the javadocs of annotation `SdkInternalApi` to make it more accurate;
2. Moved the …
=> Add support for SSO credentials provider

build-tools/src/main/resources/software/amazon/awssdk/checkstyle-suppressions.xml, build-tools/src/main/resources/software/amazon/awssdk/checkstyle.xml, http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/internal/ChannelPipelineInitializer.java, http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/internal/Http1TunnelConnectionPool.java, http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/internal/utils/NettyUtils.java, http-clients/netty-nio-client/src/test/java/software/amazon/awssdk/http/nio/netty/NettyClientTlsAuthTest.java, http-clients/netty-nio-client/src/test/java/software/amazon/awssdk/http/nio/netty/internal/Http1TunnelConnectionPoolTest.java, http-clients/netty-nio-client/src/test/java/software/amazon/awssdk/http/nio/netty/internal/utils/NettyUtilsTest.java
Ignore proxyRequest_noKeyManagerGiven_notAbleToSendConnect tests when using Java 8+ to unblock sonarcloud build.
Will fix the issue in another PR.
=> Ignore proxyRequest_noKeyManagerGiven_notAbleToSendConnect tests 

codegen/src/main/java/software/amazon/awssdk/codegen/poet/client/specs/JsonProtocolSpec.java, codegen/src/main/java/software/amazon/awssdk/codegen/poet/model/AwsServiceModel.java, codegen/src/main/java/software/amazon/awssdk/codegen/poet/model/EventStreamSpecHelper.java, codegen/src/main/java/software/amazon/awssdk/codegen/poet/transform/protocols/EventStreamJsonMarshallerSpec.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/test-async-client-class.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/transform/eventonemarshaller.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/transform/eventthreemarshaller.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/transform/eventtwomarshaller.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/transform/inputeventmarshaller.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/transform/inputeventtwomarshaller.java
Fixes event marshalling and unmarshalling:
- Fix unmarshalling by mapping event type to the correct builder static
constructor on the eventstream interface.
- Fix marshalling by retrieving the value for the :event-type header from the
event using getSdkEventType()
Builds off #2176.
Bug fix.
Updated `codegen` reference files.
=>   Event transformation based on type

services/transcribestreaming/src/main/resources/codegen-resources/customization.config
MedicalTranscriptResultStream$TrancriptEvent was released with the existing code
generation scheme so it needs to be customized.
=> Add legacy gen for MedicalTranscriptResultStream

codegen/src/main/java/software/amazon/awssdk/codegen/customization/processors/DefaultCustomizationProcessor.java, codegen/src/main/java/software/amazon/awssdk/codegen/customization/processors/NewAndLegacyEventStreamProcessor.java
Validation is only for Kinesis, Transcribe Streaming, since they have existing
streams generated with the old style.
Remove streams from the Kinesis and Transcribe Stream mappings and attempt to generate.
=> Add validation for new streams

buildspecs/release-javadoc.yml, scripts/doc_crosslinks/crosslink_redirect.html, scripts/doc_crosslinks/generate_cross_link_data.py
- Adding Crosslink redirect for API reference document
- As of now we donot have Links to Java Doc link for API reference
- This PR will will create a static page which will extract the ClientName and service name from the API refenence and redirect to the s3 location where we have Java V2 docs,
-  this loops through all the services service-2.json  and gets the service name and client name
- The python code is same as Java code where we generate the [DefaultNamingStrategy-Link](https://github.com/aws/aws-sdk-java-v2/blob/35c5f89ae29b3e5bbf3ab711c1b7b7024b76bd97/codegen/src/main/java/software/amazon/awssdk/codegen/naming/DefaultNamingStrategy.java#L116-L130)
- This will redirect the SPI refernced link via Java Scripts the maps are populated during publish java docs from above python …
=> Adding Crosslink redirect for API reference document

codegen/src/main/java/software/amazon/awssdk/codegen/poet/eventstream/EventStreamVisitorBuilderImplSpec.java, codegen/src/main/java/software/amazon/awssdk/codegen/poet/eventstream/EventStreamVisitorBuilderInterfaceSpec.java, codegen/src/main/java/software/amazon/awssdk/codegen/poet/eventstream/EventStreamVisitorInterfaceSpec.java, codegen/src/main/java/software/amazon/awssdk/codegen/poet/model/EventStreamSpecHelper.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/c2j/json/customization.config, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/c2j/json/service-2.json, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/test-async-client-class.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/eventstream/test-response-handler.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/eventstream/test-visitor-builder.java, test/codegen-generated-classes-test/src/main/resources/codegen-resources/eventstreams/service-2.json, test/codegen-generated-classes-test/src/test/java/software/amazon/awssdk/services/eventstreams/EventDispatchTest.java
Legacy generation uses the shape name as the event name. Transcribe Streaming
has a member event named "TranscriptEvent", but its shape is
"MedicalTranscriptEvent". This only affected interfaces, marshalling/marshalling
is okay.
Bug fix.
Added a new test.
Checked the diffs:
- Transcribe Streaming diff with `2.15.51`: https://gist.github.com/dagnir/8a7578648433595ede76d998081ad749#file-transcribestreaming-diff-with-2-15-51-diff
- Transcribe Streaming diff with `2.15.35`. This is the first time `MedicalTransciptEvent` is introduced: https://gist.github.com/dagnir/8a7578648433595ede76d998081ad749#file-transcribestreaming-diff-with-2-15-35-diff
- Kinesis diff with `2.15.51`: https://gist.github.com/dagnir/8a7578648433595ede76d998081ad749#file-kinesis-diff-with-2-15-51-diff
=> Fix eventstream legacy generation

buildspecs/release-to-maven.yml, buildspecs/update-master-from-release.yml, pom.xml
Add japicmp plugin to validate source and binary compatibility
Made a couple of breaking changes to public APIs locally and verified that the build failed.
Also verified the build did not fail when the changes were in internal APIs
=> Add japicmp plugin to validate source and binary compatibility

.changes/next-release/feature-AmazonS3-deae2cc.json, services/s3/src/main/java/software/amazon/awssdk/services/s3/S3Utilities.java, services/s3/src/main/java/software/amazon/awssdk/services/s3/model/GetUrlRequest.java, services/s3/src/test/java/software/amazon/awssdk/services/s3/S3UtilitiesTest.java
Support versionId in S3Utilities#getUrl
#2224 
Added new unit tests
=> Support versionId in S3Utilities#getUrl

.changes/next-release/bugfix-NettyNIOHTTPClient-dd43cf4.json, .changes/next-release/feature-NettyNIOHTTPClient-e7d2844.json, http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/internal/AwaitCloseChannelPoolMap.java, http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/internal/SslContextProvider.java, http-clients/netty-nio-client/src/test/java/software/amazon/awssdk/http/nio/netty/internal/AwaitCloseChannelPoolMapTest.java, http-clients/netty-nio-client/src/test/java/software/amazon/awssdk/http/nio/netty/internal/SslContextProviderTest.java
- 4a18e52 Refactor: extract sslContext logic to a separate class.
- f063861 Correctly select the cipher suites based on the HTTP protocol. 
All requests use Http2SecurityUtil.CIPHERS cipher suites
`HTTP/2`: [Http2SecurityUtil.CIPHERS](https://github.com/netty/netty/blob/0dc246eb129796313b58c1dbdd674aa289f72cad/codec-http2/src/main/java/io/netty/handler/codec/http2/Http2SecurityUtil.java)
`HTTP/1.1`: the [default cipher suites](https://github.com/netty/netty/blob/0dc246eb129796313b58c1dbdd674aa289f72cad/handler/src/main/java/io/netty/handler/ssl/SslUtils.java#L115-L141) provided by netty 
#2159 
Integration tests and stability tests passed
=> Correctly select the cipher suites based on the HTTP protocol

services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/presigner/DefaultS3Presigner.java
Change the default value of `checksumValidationEnabled` as `false` to achieve parity between presigners with the default S3Configuration and no S3Cofiguration, to avoid `signatureNotMatched` error while using the presigned url in browser with the default S3Configuration.
#2154 
Unit tests added.
=> Fix inconsistency of checksunValidationEnabled between default S3Configuration and no S3Configuration

.changes/next-release/bugfix-AWSSDKforJavav2-da92594.json, core/aws-core/src/main/java/software/amazon/awssdk/awscore/eventstream/EventStreamAsyncResponseTransformer.java
Reverting  #1971 as after this fix there was latency seen in test canaries.
- Checked the thread dump saw lot of instances when the isCompletedOrDeliverEvent and onNext are waiting as onComplete has already acquired the lock.
-  Tested on Canaries and saw that latency disappeared after the fix was reverted.
```
"aws-java-sdk-NettyEventLoop-1-9" #46 daemon prio=5 os_prio=0 tid=0x00007f3f5003f800 nid=0x2998 runnable [0x00007f3fcc77e000]
java.lang.Thread.State: RUNNABLE
at java.lang.Thread.setPriority0(Native Method)
at java.lang.Thread.setPriority(Thread.java:1099)
at java.lang.Thread.init(Thread.java:418)
at java.lang.Thread.init(Thread.java:350)
at java.lang.Thread.<init>(Thread.java:679)
at java.util.concurrent.Executors$DefaultThreadFactory.newThread(Executors.java:613)
at …
```
=> Reverting #1971 as it was causing latency issues in test canaries

pom.xml
After the code triggering japicmp is released, we do not need the exclusions
=> removing excludes not needed since this code is released

.changes/next-release/feature-AWSRDS-e6fec25.json, codegen/src/main/java/software/amazon/awssdk/codegen/model/config/customization/UtilitiesMethod.java, codegen/src/main/java/software/amazon/awssdk/codegen/poet/client/AsyncClientClass.java, codegen/src/main/java/software/amazon/awssdk/codegen/poet/client/SyncClientClass.java, docs/LaunchChangelog.md, services/rds/src/main/java/software/amazon/awssdk/services/rds/DefaultRdsUtilities.java, services/rds/src/main/java/software/amazon/awssdk/services/rds/RdsUtilities.java, services/rds/src/main/java/software/amazon/awssdk/services/rds/model/GenerateAuthenticationTokenRequest.java, services/rds/src/main/resources/codegen-resources/customization.config, services/rds/src/test/java/software/amazon/awssdk/services/rds/DefaultRdsUtilitiesTest.java
Add a new Rds Utilities class that can generate the auth token.
V1 Parity feature
More info: https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.IAMDBAuth.Connecting.AWSCLI.html
Utilities pattern is used instead of Presigner due to this is a pseudo request. There does not exist a modeled API call so it does not make sense to make a presigner for it.
Upstream this code out of the AWS Toolkit for JetBrains
#1157
Need to write the tests
=> Add a RdsUtilities with the ability to generate an IAM auth token

.changes/next-release/bugfix-AWSS3-3df5a2e.json, services/s3/src/main/java/software/amazon/awssdk/services/s3/S3Utilities.java, services/s3/src/test/java/software/amazon/awssdk/services/s3/S3UtilitiesTest.java
This pr is to fix #2266.
Fix the bug that `getUrl` method in `S3Utilities` ignores the client level override endpoint.
A unit test testing when there is the client level overriding endpoint but no request level overriding endpoint, the client level overriding endpoint would be used for the `getUrl` method.
=> Fix the bug of client endpoint override being ignored

services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/DefaultS3CrtAsyncClient.java, services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/DefaultS3CrtClientBuilder.java, services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/S3CrtUtils.java, services/s3/src/test/java/software/amazon/awssdk/services/s3/internal/S3CrtUtilsTest.java
Add support for adapting the sdk configurations to crt configurations.
The java sdk configurations are not exactly the same as the crt configurations, so we need to adapt the sdk configurations to the crt configurations.
A unit test testing if the crt credentials provider can be created correctly is added in this pr.
=> Add support for adapting the sdk configurations to crt configurations.

.changes/next-release/feature-AWSSDKforJavav2-e6a3a04.json, services/dynamodb/src/main/java/software/amazon/awssdk/services/dynamodb/DynamoDbRetryPolicy.java, services/dynamodb/src/test/java/software/amazon/awssdk/services/dynamodb/DynamoDbRetryPolicyTest.java
Change STANDARD mode retry count for DynamoDB to match LEGACY same as in V1
- DynamoDB is concerned of the lower  value in STANDARD  which was a lower value (2 in case of V2) and asked to set it to higher value as legacy mode.
- In-order to keep this consistent with V1 setting the retry count to 8 same as LEGACY_RETRY_COUNT.
=> Change STANDARD mode retry count for DynamoDB to match LEGACY as V1

services/s3/pom.xml, services/s3/src/it/java/software/amazon/awssdk/services/s3/CrtClientIntegrationTest.java, services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/DefaultS3CrtAsyncClient.java, services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/S3CrtUtils.java, services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/s3crt/RequestDataSupplierAdapter.java, services/s3/src/test/java/software/amazon/awssdk/services/s3/internal/s3crt/RequestDataSupplierAdapterTckTest.java, services/s3/src/test/java/software/amazon/awssdk/services/s3/internal/s3crt/RequestDataSupplierAdapterTest.java, services/s3/src/test/java/software/amazon/awssdk/services/s3/utils/ChecksumUtils.java
=> CRT S3 Client PutObject

services-custom/s3-transfermanager/pom.xml, services-custom/s3-transfermanager/src/main/java/software/amazon/awssdk/custom/s3/transfer/DownloadRequest.java, services-custom/s3-transfermanager/src/main/java/software/amazon/awssdk/custom/s3/transfer/TransferRequest.java, services-custom/s3-transfermanager/src/main/java/software/amazon/awssdk/custom/s3/transfer/UploadRequest.java, services-custom/s3-transfermanager/src/main/java/software/amazon/awssdk/custom/s3/transfer/internal/DefaultS3TransferManager.java, services-custom/s3-transfermanager/src/test/java/software/amazon/awssdk/custom/s3/transfer/util/S3IntegrationTestBase.java, services/s3/src/main/java/software/amazon/awssdk/services/s3/S3CrtAsyncClientBuilder.java, services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/s3crt/DefaultS3CrtClientBuilder.java
Update TransferManager download APIs
Javadocs will be added in a followup PR
=> Update TransferManager download APIs

services/s3/src/main/java/software/amazon/awssdk/services/s3/S3CrtAsyncClientBuilder.java, services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/s3crt/DefaultS3CrtAsyncClient.java, services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/s3crt/DefaultS3CrtClientBuilder.java
- Return the correct type from builder methods
- Make max thorughput and part size nullable
=> Fix CRT client builder

docs/LaunchChangelog.md
Updated the 1.11 to 2.0 Changelog: 
- Added DynamoDB Enhanced client and Waiters
- Updated the status of S3 Presigned URLs
Keep the changelog up-to-date.
=> Adding high-level libraries to the changelog

.changes/next-release/bugfix-AWSSDKforJavav2-d65637f.json, core/sdk-core/src/main/resources/META-INF/native-image/software.amazon.awssdk/sdk-core/native-image.properties
Removes `--report-unsupported-elements-at-runtime` from `native-image.properties`
As described in https://github.com/oracle/graal/issues/1725#issuecomment-547570158 this option is not meant to be used in production and under certain circumstances it may cause https://github.com/oracle/graal/issues/1725 to appear as in https://github.com/quarkusio/quarkus/issues/16139.
cc @zoewangg 
Tested with:
```
mvn clean install -pl :sdk-native-image-test -P quick --am
mvn clean install -pl :bom-internal,:bom
cd test/sdk-native-image-test
export JAVA_HOME=/opt/jvms/graalvm-ce-java11-21.0.0
mvn clean package -P native-image
```
=> Remove --report-unsupported-elements-at-runtime from native-image.properties

services-custom/dynamodb-enhanced/src/main/java/software/amazon/awssdk/enhanced/dynamodb/DefaultAttributeConverterProvider.java, services-custom/dynamodb-enhanced/src/main/java/software/amazon/awssdk/enhanced/dynamodb/internal/converter/attribute/ByteBufferAttributeConverter.java, services-custom/dynamodb-enhanced/src/test/java/software/amazon/awssdk/enhanced/dynamodb/converters/attribute/BinaryAttributeConvertersTest.java, services-custom/dynamodb-enhanced/src/test/java/software/amazon/awssdk/enhanced/dynamodb/functionaltests/models/FakeItemWithByteBufferKey.java, services-custom/dynamodb-enhanced/src/test/java/software/amazon/awssdk/enhanced/dynamodb/internal/operations/CreateTableOperationTest.java
Add support ByteBuffer as an an attribute type.
The DynamoDBType already lists it as a standard type.
The DynamoDBType  mentions it as a standard type, but it was not supported.
Added test
=> Add support for ByteBufferAttributeConverter

core/protocols/aws-xml-protocol/src/main/java/software/amazon/awssdk/protocols/xml/internal/marshall/XmlWriter.java, test/protocol-tests-core/src/main/resources/software/amazon/awssdk/protocol/suites/cases/rest-xml-input.json
XML entity encoding for carriage return and line feed
The \r and \n didnot have xml encoding.
- Added protocol test cases
=>  XML entity encoding for carriage return and line feed

.changes/next-release/feature-DynamoDBEnhancedClient-ddec09e.json, services-custom/dynamodb-enhanced/src/main/java/software/amazon/awssdk/enhanced/dynamodb/model/BatchGetResultPage.java, services-custom/dynamodb-enhanced/src/test/java/software/amazon/awssdk/enhanced/dynamodb/internal/operations/BatchGetItemOperationTest.java
DynamoDB returns keys that could not be processed in a BatchGetItem result, however there was no way to get at these values
through the enhanced client. Inferring which keys were not processed by subtracting the results list from the inputs was not
sufficient because if any of the items were missing from the results, it would be impossible to know if they were not included in
the result set because they were not processed or if they were actually missing.
At least one customer has asked for this functionality. DynamoDbMapper provides this functionality by throwing an exception and providing the partial results and the unprocessed keys in that exception, so this is also a feature parity issue.
Unit tests.
=> Adding unprocessedKeysForTable to BatchGetItem results object

codegen/src/main/java/software/amazon/awssdk/codegen/poet/client/specs/JsonProtocolSpec.java, codegen/src/main/java/software/amazon/awssdk/codegen/poet/transform/protocols/EventStreamJsonMarshallerSpec.java, codegen/src/test/java/software/amazon/awssdk/codegen/poet/ClientTestModels.java, codegen/src/test/java/software/amazon/awssdk/codegen/poet/builder/BuilderClassTest.java, codegen/src/test/java/software/amazon/awssdk/codegen/poet/client/PoetClientFunctionalTests.java, codegen/src/test/java/software/amazon/awssdk/codegen/poet/eventstream/EventStreamFunctionalTests.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/c2j/json/customization.config, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/c2j/json/paginators.json, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/c2j/json/service-2.json, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/test-aws-json-async-client-class.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/transform/eventonemarshaller.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/transform/eventthreemarshaller.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/transform/eventtwomarshaller.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/transform/inputeventtwomarshaller.java, core/aws-core/src/main/java/software/amazon/awssdk/awscore/client/handler/AwsClientHandlerUtils.java, core/aws-core/src/main/java/software/amazon/awssdk/awscore/eventstream/EventStreamInitialRequestInterceptor.java, core/aws-core/src/main/resources/META-INF/native-image/software.amazon.awssdk/aws-core/reflect-config.json, core/aws-core/src/main/resources/software/amazon/awssdk/global/handlers/execution.interceptors, core/aws-core/src/test/java/software/amazon/awssdk/awscore/eventstream/EventStreamInitialRequestInterceptorTest.java, core/protocols/aws-json-protocol/src/main/java/software/amazon/awssdk/protocols/json/BaseAwsJsonProtocolFactory.java, core/protocols/aws-json-protocol/src/main/java/software/amazon/awssdk/protocols/json/internal/marshall/JsonProtocolMarshaller.java, core/protocols/aws-json-protocol/src/main/java/software/amazon/awssdk/protocols/json/internal/marshall/JsonProtocolMarshallerBuilder.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/client/handler/ClientExecutionParams.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/interceptor/SdkInternalExecutionAttribute.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/async/AsyncStreamPrepender.java, core/sdk-core/src/test/java/software/amazon/awssdk/core/internal/async/AsyncStreamPrependerTest.java, core/sdk-core/src/test/java/software/amazon/awssdk/core/internal/async/AyncStreamPrependerTckTest.java
This commit adds support for RPC services that use client->server or
bidirectional event streaming. In the RPC formats (i.e. AWS JSON), the
marshalled request and response objects are sent as the first event in
the request and response stream respectively. This is different from the
REST formats, such as REST JSON, which bind the request and response
fields to non-payload positions (headers, URI, method, status code,
query string) when event streaming is used.
The implementation of this feature is mainly performed by a new global
interceptor, `EventStreamInitialRequestInterceptor`. The interceptor
detects when an `initial-request` event needs to be sent and transforms
the async response body by constructing the `initial-request` message
and prepending it to the event stream. Due to the …
=> Add support for event stream requests over RPC

pom.xml
Revert Japicmp version bump
It seems starting from `0.15.0`, japicmp doesn't honor `ignoreMissingOldVersion` anymore, so the build would fail when the recently released version is not available on Maven.
=> Revert Japicmp version bump because of regression

.changes/next-release/bugfix-AWSS3-c21fe33.json, services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/endpoints/S3AccessPointEndpointResolver.java, services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/endpoints/S3EndpointUtils.java, services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/resource/S3AccessPointBuilder.java, services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/resource/S3ObjectLambdaEndpointBuilder.java, services/s3/src/test/java/software/amazon/awssdk/services/s3/S3EndpointResolutionTest.java, services/s3/src/test/java/software/amazon/awssdk/services/s3/internal/endpoints/S3AccessPointEndpointResolverTest.java, services/s3/src/test/java/software/amazon/awssdk/services/s3/internal/endpoints/S3EndpointUtilsTest.java, services/s3/src/test/java/software/amazon/awssdk/services/s3/internal/handlers/EndpointAddressInterceptorTest.java, services/s3/src/test/java/software/amazon/awssdk/services/s3/internal/resource/S3AccessPointBuilderTest.java, services/s3control/src/main/java/software/amazon/awssdk/services/s3control/internal/interceptors/EndpointAddressInterceptor.java, services/s3control/src/test/java/software/amazon/awssdk/services/s3control/internal/functionaltests/arns/S3OutpostAccessPointArnTest.java, services/s3control/src/test/java/software/amazon/awssdk/services/s3control/internal/functionaltests/arns/S3OutpostBucketArnTest.java
Do not allow cross-region requests for Fips Enabled Client Regions
Below are the cross region scenario and their expected behavior
|ScenarioNo.|ClientRegion | ArnSourceRgion | useArnRegionFlag | ExpectedBehvior |
|-|-|-|-|-|
|1| Region.AWS_GLOBAL| us-east-1 |true | Success |
|2|Region.AWS_GLOBAL|us-east-1 | false |illegalArgumentException|
|3|s3-external-1 | us-east-1|true | Success| 
|4|s3-external-1 | us-east-1|false | illegalArgumentException| 
|5|fips-us-gov-east-1 | fips-us-gov-east-1|true | illegalArgumentException| 
|6|us-gov-east-1 | fips-us-gov-west-1|true | illegalArgumentException| 
|7|fips-us-gov-east-1 | us-gov-west-1|false | illegalArgumentException| 
|8|fips-us-gov-east-1 | us-gov-east-1|true | Success| 
|ScenarioNo.|OldEndPoint | NewEndpoint | 
|-|-|-|
|1| …
=> Do not allow cross-region requests for S3 client with Fips Region.

.changes/next-release/bugfix-AWSSDKforJavav2-b9a56b9.json, core/protocols/aws-json-protocol/src/main/java/software/amazon/awssdk/protocols/json/internal/marshall/SimpleTypeJsonMarshaller.java, test/protocol-tests-core/src/main/resources/software/amazon/awssdk/protocol/suites/cases/json-core-input.json, test/protocol-tests-core/src/main/resources/software/amazon/awssdk/protocol/suites/cases/json-core-output.json, test/protocol-tests/src/main/resources/codegen-resources/awsjson/service-2.json, test/protocol-tests/src/main/resources/codegen-resources/restjson/service-2.json
- NullPointerException from SimpleTypeJsonMarshaller while Unmarshailling Timestamps
- This was happening because the SdkField is not passed for  List Of Timestamps Refer [JsonMarshallerContext](https://github.com/aws/aws-sdk-java-v2/blob/cdfb7d3f6a7dafb37be84f6e95e49feb0d0af273/core/protocols/aws-json-protocol/src/main/java/software/amazon/awssdk/protocols/json/internal/marshall/JsonMarshallerContext.java#L80) which is called from [LIST Marshaller](https://github.com/aws/aws-sdk-java-v2/blob/cdfb7d3f6a7dafb37be84f6e95e49feb0d0af273/core/protocols/aws-json-protocol/src/main/java/software/amazon/awssdk/protocols/json/internal/marshall/SimpleTypeJsonMarshaller.java#L146)
- We are keeping the behaviuor same as V1 where we default to unixTimeStamp if MarshellerInfo is not found for TimeStamp …
=> Fix for Marshalling List/Map of TimeStamps

.changes/next-release/bugfix-AWSSDKforJavav2-3f3c0e0.json, codegen/src/main/java/software/amazon/awssdk/codegen/model/config/customization/MetadataConfig.java, codegen/src/main/java/software/amazon/awssdk/codegen/poet/client/specs/JsonProtocolSpec.java, codegen/src/test/java/software/amazon/awssdk/codegen/poet/ClientTestModels.java, codegen/src/test/java/software/amazon/awssdk/codegen/poet/client/PoetClientFunctionalTests.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/c2j/customservicemetadata/customization.config, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/c2j/customservicemetadata/service-2.json, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/test-customservicemetadata-async.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/test-customservicemetadata-sync.java, core/protocols/aws-json-protocol/src/main/java/software/amazon/awssdk/protocols/json/AwsJsonProtocolMetadata.java, core/protocols/aws-json-protocol/src/main/java/software/amazon/awssdk/protocols/json/BaseAwsJsonProtocolFactory.java, services/wellarchitected/src/main/resources/codegen-resources/customization.config, test/protocol-tests/src/main/resources/codegen-resources/awsjson/customized/customization.config, test/protocol-tests/src/test/java/software/amazon/awssdk/protocol/tests/customservicemetadata/CustomServiceMetaDataServiceTest.java
- Support customization of contentTypeOverride for Header ContentType
- By default the ContentType Header for Json type is set to  ```application/x-amz-json-1.1``` for json protocol.
- While wellarchitected accepted  ```application/json```  ContentType Header.
- These changes will add a customization for services which accept ```application/json```ContentType header.
Why is this change required? What problem does it solve? 
- Customization required for  ```application/json```ContentType header. Else the API calls to Services which accept  ```application/json```ContentType header will not be successful.
If it fixes an open issue, please link to the issue here  :  PR #2510 
contentType attribute is populated only if CustomizationConfig is set. If not then we look for …
=> Support customization of contentTypeOverride for Header ContentType

services-custom/dynamodb-enhanced/README.md
Fixing documentation for DynamoDB enhanced client index.query().
Fixing issue requested as requested in [issue 2185](https://github.com/aws/aws-sdk-java-v2/issues/2185)
Just fixing documentation, does not affect any areas of code.
=> Fixing DynamoDB enhanced client index.query documentation

pom.xml, services-custom/s3-transfer-manager/src/main/java/software/amazon/awssdk/transfer/s3/S3ClientConfiguration.java, services-custom/s3-transfer-manager/src/test/java/software/amazon/awssdk/transfer/s3/S3ClientConfigurationTest.java, utils/src/main/java/software/amazon/awssdk/utils/Validate.java, utils/src/test/java/software/amazon/awssdk/utils/ValidateTest.java
- Add validation in S3ClientConfiguration
- Add equals and hashcode 
- Add more tests
=> Add validation in S3ClientConfiguration

services-custom/s3-transfer-manager/src/it/java/software/amazon/awssdk/transfer/s3/S3TransferManagerDownloadIntegrationTest.java, services-custom/s3-transfer-manager/src/main/java/software/amazon/awssdk/transfer/s3/internal/CrtCredentialsProviderAdapter.java, services-custom/s3-transfer-manager/src/main/java/software/amazon/awssdk/transfer/s3/internal/DefaultS3CrtAsyncClient.java, services-custom/s3-transfer-manager/src/main/java/software/amazon/awssdk/transfer/s3/internal/S3CrtPojoConversion.java, services-custom/s3-transfer-manager/src/main/java/software/amazon/awssdk/transfer/s3/internal/S3NativeClientConfiguration.java, services-custom/s3-transfer-manager/src/test/java/software/amazon/awssdk/transfer/s3/internal/CrtCredentialProviderAdapterTest.java, services-custom/s3-transfer-manager/src/test/java/software/amazon/awssdk/transfer/s3/internal/S3CrtPojoConversionTest.java
Update to use CRT DelegateCredentialsProvider
=> Update to use CRT DelegateCredentialsProvider

services-custom/s3-transfer-manager/src/it/java/software/amazon/awssdk/transfer/s3/S3TransferManagerUploadIntegrationTest.java, services-custom/s3-transfer-manager/src/main/java/software/amazon/awssdk/transfer/s3/internal/DefaultS3CrtAsyncClient.java, services-custom/s3-transfer-manager/src/main/java/software/amazon/awssdk/transfer/s3/internal/RequestDataSupplierAdapter.java, services-custom/s3-transfer-manager/src/main/java/software/amazon/awssdk/transfer/s3/internal/S3CrtPojoConversion.java, services-custom/s3-transfer-manager/src/test/java/software/amazon/awssdk/transfer/s3/internal/S3CrtPojoConversionTest.java
Provide HTTP request-level data in PutObjectResponse
=> Provide HTTP request-level data in PutObjectResponse

core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/async/FileAsyncRequestBody.java, test/stability-tests/src/it/java/software/amazon/awssdk/stability/tests/s3/S3BaseStabilityTest.java, test/stability-tests/src/it/java/software/amazon/awssdk/stability/tests/s3/S3CrtAsyncClientStabilityTest.java, test/stability-tests/src/it/java/software/amazon/awssdk/stability/tests/s3/S3NettyAsyncStabilityTest.java, test/stability-tests/src/it/java/software/amazon/awssdk/stability/tests/s3/S3WithCrtAsyncHttpClientStabilityTest.java
Fix a race condition in FileAsyncRequestBody where a request demand comes in at the same time reading is progress, which causes the request to hang.
=> Fix a race condition in FileAsyncRequestBody

pom.xml, services-custom/s3-transfer-manager/src/main/java/software/amazon/awssdk/transfer/s3/internal/DefaultS3CrtAsyncClient.java, services-custom/s3-transfer-manager/src/main/java/software/amazon/awssdk/transfer/s3/internal/DefaultS3TransferManager.java, services-custom/s3-transfer-manager/src/main/java/software/amazon/awssdk/transfer/s3/internal/S3NativeClientConfiguration.java, services-custom/s3-transfer-manager/src/test/java/software/amazon/awssdk/transfer/s3/internal/DefaultS3CrtAsyncClientTest.java, services-custom/s3-transfer-manager/src/test/java/software/amazon/awssdk/transfer/s3/internal/S3TransferManagerTest.java
Add request cancellation logic and tests
=> Add request cancellation logic and tests

core/sdk-core/src/main/java/software/amazon/awssdk/core/client/builder/SdkDefaultClientBuilder.java, services-custom/s3-transfer-manager/src/it/java/software/amazon/awssdk/transfer/s3/S3CrtClientPutObjectIntegrationTest.java, services-custom/s3-transfer-manager/src/it/java/software/amazon/awssdk/transfer/s3/S3CrtGetObjectIntegrationTest.java, services-custom/s3-transfer-manager/src/main/java/software/amazon/awssdk/transfer/s3/S3ClientConfiguration.java, services-custom/s3-transfer-manager/src/main/java/software/amazon/awssdk/transfer/s3/internal/CrtCredentialsProviderAdapter.java, services-custom/s3-transfer-manager/src/main/java/software/amazon/awssdk/transfer/s3/internal/DefaultS3CrtAsyncClient.java, services-custom/s3-transfer-manager/src/main/java/software/amazon/awssdk/transfer/s3/internal/DefaultS3TransferManager.java, services-custom/s3-transfer-manager/src/main/java/software/amazon/awssdk/transfer/s3/internal/S3CrtAsyncClient.java, services-custom/s3-transfer-manager/src/main/java/software/amazon/awssdk/transfer/s3/internal/S3NativeClientConfiguration.java, services-custom/s3-transfer-manager/src/test/java/software/amazon/awssdk/transfer/s3/S3ClientConfigurationTest.java, services-custom/s3-transfer-manager/src/test/java/software/amazon/awssdk/transfer/s3/internal/DefaultS3CrtAsyncClientTest.java, services-custom/s3-transfer-manager/src/test/java/software/amazon/awssdk/transfer/s3/internal/S3NativeClientConfigurationTest.java, utils/src/main/java/software/amazon/awssdk/utils/CompletableFutureUtils.java, utils/src/test/java/software/amazon/awssdk/utils/CompletableFutureUtilsTest.java
Offload completion of execution future to a separate thread to prevent the CRT threads being blocked by complex operations in the completion chain of a completable future
=> Offload completion of execution future to a separate thread

services-custom/s3-transfer-manager/src/main/java/software/amazon/awssdk/transfer/s3/internal/CrtErrorHandler.java, services-custom/s3-transfer-manager/src/main/java/software/amazon/awssdk/transfer/s3/internal/CrtResponseDataConsumerAdapter.java, services-custom/s3-transfer-manager/src/main/java/software/amazon/awssdk/transfer/s3/internal/DefaultS3CrtAsyncClient.java, services-custom/s3-transfer-manager/src/test/java/software/amazon/awssdk/transfer/s3/internal/CrtErrorHandlerTest.java, services-custom/s3-transfer-manager/src/test/java/software/amazon/awssdk/transfer/s3/internal/CrtExceptionTransformationIntegrationTest.java, services-custom/s3-transfer-manager/src/test/java/software/amazon/awssdk/transfer/s3/internal/DefaultS3CrtAsyncClientTest.java
- Wrap CrtS3RuntimeException to SdkServiceException
- Currently CrtClient throws CrtS3RuntimeException whenever there is S3 Service side exceptions.
- We need to Wrap these exception indicating these are Service side exceptions
- Added Integration test
- Added Junits
=> Wrap CrtS3RuntimeException to SdkServiceException

scripts/doc_crosslinks/generate_cross_link_data.py
Updated javadocs release cross-linking script to catch all services
Cross-links for DynamoDB/DynamoDB Streams and WAF currently redirect customers to javadocs home page instead of the page for the specific class/method/interface.
Ran the script for several services and all redirected as expected to specific javadocs pages
=> Update javadocs release cross-linking script

pom.xml, services-custom/s3-transfer-manager/src/it/java/software/amazon/awssdk/transfer/s3/CrtExceptionTransformationIntegrationTest.java, services-custom/s3-transfer-manager/src/main/java/software/amazon/awssdk/transfer/s3/internal/CrtCredentialsProviderAdapter.java
- Bump up CRT version
- clean up resources in tests
- fix credential adapter TODO. CRT has fixed the issue via https://github.com/awslabs/aws-crt-java/pull/339
=> Various minor updates

services/s3control/src/it/java/software.amazon.awssdk.services.s3control/S3AccessPointsIntegrationTest.java, services/s3control/src/it/java/software.amazon.awssdk.services.s3control/S3AsyncAccessPointsIntegrationTest.java
Tear down for Accesspointsintegrationtest was not deleting buckets as it was failing with below exception
```
Failed to delete bucket: s3asyncaccesspointsintegrationtest
software.amazon.awssdk.services.s3.model.S3Exception: Bucket has access points attached and cannot be deleted. (Service: S3, Status Code: 400
```
Integration test buckets deletion failed as it had attached access points.
Changed the order where Access point is deleted before the bucket is deleted.
Verified in local workspace. Without the fix the exception is logged at the end of the test. 
With the fix we donot get failure exception
=> Integration test buckets deletion failed as it had attached access points

buildspecs/release-javadoc.yml
This fixes an error where release-javadoc.yml fails with "Error creating shaded jar: duplicate entry: META-INF/services/software.amazon.awssdk.thirdparty.jackson.core.JsonFactory"
=> Clean before building javadocs, because third-party-jackson-core's mvn package is not idempotent.

pom.xml, services-custom/s3-transfer-manager/src/main/java/software/amazon/awssdk/transfer/s3/internal/CrtResponseDataConsumerAdapter.java, services-custom/s3-transfer-manager/src/test/java/software/amazon/awssdk/transfer/s3/internal/CrtResponseDataConsumerAdapterTest.java
- Bump up crt version
- Remove buffer copy because it's no longer needed. https://github.com/awslabs/aws-crt-java/pull/352
=> Remove buffer copy since it's no longer needed

.changes/next-release/bugfix-AWSSDKforJavav2-0da2191.json, core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/async/FileAsyncRequestBody.java, core/sdk-core/src/test/java/software/amazon/awssdk/core/internal/async/FileAsyncRequestBodyTest.java
In FileAsyncRequestBody, the file was not being closed until a request()
read past the end of the file without ready any bytes; i.e. if a read()
call reads up to the end of the file, it would not complete the
subscription on the subsequent request() signal. This fixes this issue
by signaling complete if we know we've reached the end.
This PR fixes the behavior by tracking how much of the file is has been read, closing the file as soon as we've read it entirely.
New tests, ran integ tests.
=> Fix fd remaining open longer than necessary

.changes/next-release/documentation-AmazonS3-259552c.json, services/s3/src/main/resources/codegen-resources/customization.config
In https://github.com/aws/aws-sdk-java-v2/pull/2612 we recently
introduced replacement parameters for the S3 CopySource parameter.
However, we did not officially deprecate it since our codegen tooling
lacked support for deprecated members at the time. With
https://github.com/aws/aws-sdk-java-v2/pull/2622 we have since added
support for deprecated members to both models and model modifications
via customization.config files.
Now that this feature is fully supported, we should deprecate the
CopySource parameter to increase visibility and improve discoverability
of the new parameters that are offered. This will make users more likely
to discover the new parameters, allowing them to simplify their
application code accordingly.
* Annotate the CopySource parameter as deprecated for both …
=> Deprecate S3 CopySource parameter for CopyObject & UploadPartCopy

.changes/next-release/bugfix-AWSSDKforJavav2-764e546.json, core/auth/src/main/java/software/amazon/awssdk/auth/signer/internal/AbstractAws4Signer.java, core/auth/src/test/java/software/amazon/awssdk/auth/signer/Aws4SignerTest.java
The current AbstractAws4Signer does not correctly handle multi-value
headers. When creating the canonical header string to sign, it was
placing each value on a separate line, when the documentation requires
that they be comma-separated (even if the actual headers are serialized
on the wire as multiple header fields).
> Build the canonical headers list by sorting the (lowercase) headers by character code and then iterating through the header names. Construct each header according to the following rules:
> 
>* Append the lowercase header name followed by a colon.
> 
>* Append a comma-separated list of values for that header. Do not sort the values in headers that have multiple values.
> 
>* Append a new line ('\n').
https://docs.aws.amazon.com/general/latest/gr/sigv4-create-canonical-request …
=> Correctly handle multi-value headers in Aws4Signer

core/regions/src/it/java/software/amazon/awssdk/regions/util/EC2MetadataUtilsIntegrationTest.java, core/regions/src/main/java/software/amazon/awssdk/regions/internal/util/EC2MetadataUtils.java, core/regions/src/test/java/software/amazon/awssdk/regions/internal/util/Ec2MetadataUtilsTt0049160280Test.java
…until #61 can be completed, at which time it will have to go away again.
=> Temporarily restore EC2MetadataUtils.getInstanceInfo for #2625

.changes/next-release/bugfix-AWSSDKforJavav2-64dd59e.json, core/auth/src/main/java/software/amazon/awssdk/auth/credentials/internal/SystemSettingsCredentialsProvider.java
An empty session token would never be valid. In the case that certain environmental conditions may produce an empty session token (rather than null), don't attempt to use it.
This change also moves from using `StringUtils.isEmpty()` to `StringUtils.isBlank()`, as a form of precaution, but there is no functional change introduced by this commit on the other fields (accessKey and secretKey) because we are already calling `trim()` on all fields.
=> Don't attempt to use empty session tokens

.changes/next-release/bugfix-AWSSDKforJavav2-885b171.json, .gitignore
We do not store IntelliJ project files in git, but local workspaces
automatically create an aws-sdk-java-pom.ipr file, which shows up under
the default version control changelist.
=> Add IntelliJ .ipr project files to gitignore

.changes/next-release/documentation-AWSSDKforJavav2-45b31c6.json, .gitignore, .idea/inspectionProfiles/AWS_Java_SDK_2_0.xml, .idea/inspectionProfiles/profiles_settings.xml, docs/GettingStarted.md
Similar to how https://github.com/aws/aws-sdk-java-v2/pull/2652 recently
moved our code style & copyright configuration files to the
project-level, we can also do the same for IntelliJ inspections. This
has the benefit of keeping inspections in sync for all users, as well as
automatically informing new users of our expected coding best practices.
We do not currently have an existing inspection profile, so we will take
this opportunity to start with a new, blank inspection profile. Users
may then propose customizing the inspections via PRs, subject to the
normal review process. Over time we will gravitate towards a shared
inspection profile that we can all agree on.
* Create a new, blank "AWS Java SDK 2.0" inspection profile
* Update profiles_settings.xml to make users use this profile
* …
=> Create a shared, project-level IntelliJ inspection profile

services-custom/s3-transfer-manager/README.md
Just fixing a typo.
Related to https://github.com/aws/aws-sdk-java-v2/issues/37. I followed the link to this README from that ticket.
n/a
n/a
=> Fix a typo in the new S3TransferManager README

buildspecs/release-javadoc.yml
- Redirection of Java doc stopped working after #2591
- The 2591 fix started using pathlib.Path(r'./services') to get all the service2.json files. However, when we run mvn install we generate target build files which started affecting the scripts output.
- Thus thus this script must be run before we do any mvn install.
- Updated the release-javadoc.yml to run generate_cross_link_data before we start the mvn install.
- Tested by running this in internally and making sure the redirects are working.
=> Script generate_cross_link_data should be run before mvn install 

core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/batchmanager/BatchAndSend.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/batchmanager/BatchingMap.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/batchmanager/DefaultBatchManager.java, core/sdk-core/src/test/java/software/amazon/awssdk/core/internal/batchmanager/BatchManagerTest.java, services/sqs/src/it/java/software/amazon/awssdk/services/sqs/BatchManagerSqsIntegrationTest.java, services/sqs/src/main/java/software/amazon/awssdk/services/sqs/batchmanager/SqsBatchManager.java, services/sqs/src/main/java/software/amazon/awssdk/services/sqs/internal/batchmanager/DefaultSqsBatchManager.java, services/sqs/src/main/java/software/amazon/awssdk/services/sqs/internal/batchmanager/SqsBatchConfiguration.java, services/sqs/src/main/java/software/amazon/awssdk/services/sqs/internal/batchmanager/SqsBatchFunctions.java, services/sqs/src/test/java/software/amazon/awssdk/services/sqs/SqsBatchFunctionsTest.java, services/sqs/src/test/java/software/amazon/awssdk/services/sqs/SqsBatchManagerTest.java
Hand coding the `SqsBatchManager` for the sync client to demonstrate how a code generated service batch manager might look like and interact with the core batch manager.
In this PR, I am implementing a `DefaultSqsBatchManager` that is created when customers want to use client-side buffering and automatic request batching in SQS. Some small changes were also made to the core batch manager to clean up some bugs as well as fix some naming issues to be more consistent. 
The integration test was modified to now use the `SqsBatchManager` instead of the core `BatchManager`. Additional tests were also added to test the behavior of other batchable Apis (in addition to `sendMessage`, there is `deleteMessage`, and `changeMessageVisibility`). Furthermore, unit tests and wire mock tests were also …
=> Adding SqsBatchManager for sync client

core/sdk-core/src/main/java/software/amazon/awssdk/core/batchmanager/BatchManagerBuilder.java, services/sqs/src/main/java/software/amazon/awssdk/services/sqs/batchmanager/SqsAsyncBatchManager.java, services/sqs/src/main/java/software/amazon/awssdk/services/sqs/batchmanager/SqsBatchManager.java, services/sqs/src/main/java/software/amazon/awssdk/services/sqs/internal/batchmanager/DefaultSqsAsyncBatchManager.java, services/sqs/src/main/java/software/amazon/awssdk/services/sqs/internal/batchmanager/DefaultSqsBatchManager.java, services/sqs/src/main/java/software/amazon/awssdk/services/sqs/internal/batchmanager/SqsBatchFunctions.java, services/sqs/src/test/java/software/amazon/awssdk/services/sqs/BaseSqsBatchManagerTest.java, services/sqs/src/test/java/software/amazon/awssdk/services/sqs/SqsAsyncBatchManagerTest.java, services/sqs/src/test/java/software/amazon/awssdk/services/sqs/SqsBatchFunctionsTest.java, services/sqs/src/test/java/software/amazon/awssdk/services/sqs/SqsBatchManagerTest.java
Hand coding the `SqsAsyncBatchManager` for the async client to demonstrate how a code generated service batch manager might look like and interact with the core batch manager.
In this PR, I am implementing a `DefaultSqsAsyncBatchManager` that is created when customers want to use client-side buffering and automatic request batching with SQS' async client. A lot of the changes involved refactoring existing code used by the sync `SqsBatchManager` to be usable by the async client as well. 
Tests for the sync `BatchManager` were refactored into a base abstract class. The tests for the `SqsAsyncBatchManager` leverages this base class and differs from the  tests for the sync `BatchManager` by passing in a `SqsAsyncClient` and `SqsAsyncBatchManager`
=> Adding SqsBatchManager for Async client

core/sdk-core/src/main/java/software/amazon/awssdk/core/batchmanager/BatchAndSend.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/batchmanager/BatchKeyMapper.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/batchmanager/BatchManagerBuilder.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/batchmanager/BatchOverrideConfiguration.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/batchmanager/BatchResponseMapper.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/batchmanager/IdentifiableMessage.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/batchmanager/BatchBuffer.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/batchmanager/BatchConfiguration.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/batchmanager/BatchingMap.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/batchmanager/DefaultBatchManager.java, core/sdk-core/src/test/java/software/amazon/awssdk/core/BatchOverrideConfigurationTest.java, core/sdk-core/src/test/java/software/amazon/awssdk/core/internal/batchmanager/BatchManagerTest.java, core/sdk-core/src/test/java/software/amazon/awssdk/core/internal/batchmanager/IdentifiableMessageTest.java, services/sqs/src/main/java/software/amazon/awssdk/services/sqs/internal/batchmanager/SqsBatchFunctions.java, services/sqs/src/test/java/software/amazon/awssdk/services/sqs/BaseSqsBatchManagerTest.java, services/sqs/src/test/java/software/amazon/awssdk/services/sqs/SqsBatchFunctionsTest.java
Currently failures in a batch entry are handled by returning an empty response of the same type as a successful response. Instead, we want to be able to handle failed batch entries by filling the returned response with an appropriate exception. Separately, the core `BatchManager` currently allows for an unlimited number of `batchKey`s and an unlimited number of requests to be buffered for each `batchKey`. We should limit this to prevent excessive memory usage and give customers the option to override these limits with a configurable value.
In this PR, I am modifying the `SqsBatchFunctions` to return an exception for each batch entry that failed. The core `BatchManager` now either expects a normal response or an Exception, and when it encounters an exception, it completes the corresponding …
=> Refactoring the core BatchManager to change how it handles batch entry failures.

.changes/next-release/feature-AWSSDKforJavav2-35b961d.json, core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/http/pipeline/stages/AsyncRetryableStage.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/http/pipeline/stages/RetryableStage.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/http/pipeline/stages/utils/RetryableStageHelper.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/retry/RateLimitingTokenBucket.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/retry/SdkDefaultRetrySetting.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/retry/RetryMode.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/retry/RetryPolicy.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/retry/backoff/BackoffStrategy.java, core/sdk-core/src/test/java/software/amazon/awssdk/core/internal/http/pipeline/stages/AsyncRetryableStageAdaptiveModeTest.java, core/sdk-core/src/test/java/software/amazon/awssdk/core/internal/http/pipeline/stages/RetryableStageAdaptiveModeTest.java, core/sdk-core/src/test/java/software/amazon/awssdk/core/internal/retry/RateLimitingTokenBucketCubicTest.java, core/sdk-core/src/test/java/software/amazon/awssdk/core/internal/retry/RateLimitingTokenBucketEndToEndTest.java, core/sdk-core/src/test/java/software/amazon/awssdk/core/internal/retry/RateLimitingTokenBucketTest.java, core/sdk-core/src/test/java/software/amazon/awssdk/core/retry/RetryModeTest.java, core/sdk-core/src/test/java/software/amazon/awssdk/core/retry/RetryPolicyTest.java
This PR introduces support for `ADAPTIVE` retry mode.
ADAPTIVE retry mode builds on top of STANDARD retry mode and includes rate
limiting of requests when the client is throttled.
Implement ADAPTIVE retry mode. ADAPTIVE mode builds on STANDARD retry mode and adds rate limiting of requests when the client is throttled.
Adaptive retry mode dynamically limits the rate of AWS requests to maximize success rate. This may be at the expense of request latency. Adaptive retry mode is not recommended when predictable latency is important.
- New unit tests
- ~~Running~~ integ tests
- ~~Running~~ stability tests
=> Implement ADAPTIVE Retry Mode

codegen/src/main/java/software/amazon/awssdk/codegen/model/config/customization/BatchManagerMethod.java, codegen/src/main/java/software/amazon/awssdk/codegen/model/config/customization/CustomizationConfig.java, codegen/src/main/java/software/amazon/awssdk/codegen/poet/client/AsyncClientClass.java, codegen/src/main/java/software/amazon/awssdk/codegen/poet/client/AsyncClientInterface.java, codegen/src/main/java/software/amazon/awssdk/codegen/poet/client/ClientClassUtils.java, codegen/src/main/java/software/amazon/awssdk/codegen/poet/client/SyncClientClass.java, codegen/src/main/java/software/amazon/awssdk/codegen/poet/client/SyncClientInterface.java, codegen/src/test/java/software/amazon/awssdk/codegen/poet/ClientTestModels.java, codegen/src/test/java/software/amazon/awssdk/codegen/poet/client/PoetClientFunctionalTests.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/c2j/batchmanager/customization.config, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/c2j/batchmanager/service-2.json, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/test-batchmanager-async-class.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/test-batchmanager-async-interface.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/test-batchmanager-sync-class.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/test-batchmanager-sync-interface.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/batchmanager/BatchOverrideConfiguration.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/batchmanager/BatchBuffer.java, services/sqs/src/main/java/software/amazon/awssdk/services/sqs/batchmanager/SqsAsyncBatchManager.java, services/sqs/src/main/java/software/amazon/awssdk/services/sqs/batchmanager/SqsBatchManager.java, services/sqs/src/main/java/software/amazon/awssdk/services/sqs/internal/batchmanager/DefaultSqsAsyncBatchManager.java, services/sqs/src/main/java/software/amazon/awssdk/services/sqs/internal/batchmanager/DefaultSqsBatchManager.java, services/sqs/src/main/java/software/amazon/awssdk/services/sqs/internal/batchmanager/SqsBatchFunctions.java, services/sqs/src/main/resources/codegen-resources/customization.config, services/sqs/src/test/java/software/amazon/awssdk/services/sqs/SqsAsyncBatchManagerTest.java, services/sqs/src/test/java/software/amazon/awssdk/services/sqs/SqsBatchManagerTest.java
Users should have the option to be able to create a `batchManager()` directly from a low level sqs client as outlined in the design document. Changes also had to be made to the generated clients to ensure that they contained the necessary executor/scheduledExecutor that would be used by the `batchManager`.
Added some changes to how the sync and async clients (as well as their corresponding interfaces) are generated. Specifically added in the `batchManager()` method to create a `batchManager` for that service. `Executors` and `ScheduledExecutors` were also added to the underlying clients if they supported the `batchManager()` method.
Added some codegen tests to check the generated classes and interfaces matched expectations. Also modified existing SqsBatchManager tests to use the client's …
=> Adding batchManager() method into code generated sync and async clients

.changes/next-release/bugfix-AWSSDKforJavav2-f2c1771.json, core/sdk-core/src/main/java/software/amazon/awssdk/core/retry/RetryPolicy.java, core/sdk-core/src/test/java/software/amazon/awssdk/core/retry/RetryPolicyTest.java
=> Fix NPE in RetryPolicy.hashCode()

core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/async/AsyncStreamPrepender.java, core/sdk-core/src/test/java/software/amazon/awssdk/core/internal/async/AsyncStreamPrependerTest.java
Before this change, the AsyncStreamPrepender (a Publisher) does not support multiple subscribe calls, but each attempt makes a new subscribe call. Because of this, if a retry is encountered, backpressure is miscalculated and the initial-request
is not sent for the retries.
=> Fixed an issue in JSON-RPC event stream services (none exist yet) where retries excluded the initial-request event.

core/sdk-core/src/main/java/software/amazon/awssdk/core/batchmanager/BatchAndSend.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/batchmanager/BatchManagerBuilder.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/batchmanager/BatchResponseMapper.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/batchmanager/BatchBuffer.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/batchmanager/BatchingExecutionContext.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/batchmanager/BatchingMap.java, services/sqs/src/it/java/software/amazon/awssdk/services/sqs/BatchManagerSqsIntegrationTest.java
There were a few javadocs/comments that needed to be fixed/made consistent. Also removed some methods that were not needed and removed a synchronized lock that wasn't needed as well.
As mentioned above, just cleaning up some code.
Changes made were mostly to javadocs/comments. Code changes were covered in tests already implemented in sdk-core.
=> Just cleaning up the batch manager code.

core/aws-core/pom.xml, core/aws-core/src/main/java/software/amazon/awssdk/awscore/eventstream/EventStreamAsyncResponseTransformer.java, core/aws-core/src/test/java/software/amazon/awssdk/awscore/eventstream/EventStreamAsyncResponseTransformerTest.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/async/SdkPublisher.java, pom.xml, services/kinesis/src/test/java/software/amazon/awssdk/services/kinesis/SubscribeToShardUnmarshallingTest.java, utils/pom.xml, utils/src/main/java/software/amazon/awssdk/utils/async/DelegatingSubscriber.java, utils/src/main/java/software/amazon/awssdk/utils/async/EventListeningSubscriber.java, utils/src/main/java/software/amazon/awssdk/utils/async/FlatteningSubscriber.java, utils/src/main/java/software/amazon/awssdk/utils/async/SequentialSubscriber.java, utils/src/test/java/software/amazon/awssdk/utils/async/FlatteningSubscriberTckTest.java, utils/src/test/java/software/amazon/awssdk/utils/async/FlatteningSubscriberTest.java
https://github.com/aws/aws-sdk-java-v2/pull/2684 had to be rolled back because of a failed integration test. This rolls back that rollback and fixes the test failure.
The test failure fix has been put into a separate commit to make it easy to skip code that has already been reviewed.
=> Fixed an issue where event streams might fail with ClassCastException or NoSuchElementException.

.changes/next-release/feature-S3TransferManager-a6fd00b.json, services-custom/s3-transfer-manager/src/main/java/software/amazon/awssdk/transfer/s3/DownloadRequest.java, services-custom/s3-transfer-manager/src/main/java/software/amazon/awssdk/transfer/s3/UploadRequest.java, services-custom/s3-transfer-manager/src/test/java/software/amazon/awssdk/transfer/s3/DownloadRequestTest.java, services-custom/s3-transfer-manager/src/test/java/software/amazon/awssdk/transfer/s3/UploadRequestTest.java
Add file overload to DownloadRequest and UploadRequest to be consistent with `FileRequetBody` which also accepts both `File` and `Path`
Added test
=> Add file overload to DownloadRequest and UploadRequest

buildspecs/release-to-maven.yml, buildspecs/resources/release-settings.xml
This moves the storage used by the push-to-maven step from S3 to secrets manager.
=> Update release-to-maven buildspec.

.changes/next-release/feature-DynamoDBEnhancedClient-002cc20.json, services-custom/dynamodb-enhanced/pom.xml, services-custom/dynamodb-enhanced/src/it/java/software/amazon/awssdk/enhanced/dynamodb/AsyncPutItemWithResponseIntegrationTest.java, services-custom/dynamodb-enhanced/src/it/java/software/amazon/awssdk/enhanced/dynamodb/DynamoDbEnhancedIntegrationTestBase.java, services-custom/dynamodb-enhanced/src/it/java/software/amazon/awssdk/enhanced/dynamodb/PutItemWithResponseIntegrationTest.java, services-custom/dynamodb-enhanced/src/main/java/software/amazon/awssdk/enhanced/dynamodb/DynamoDbAsyncTable.java, services-custom/dynamodb-enhanced/src/main/java/software/amazon/awssdk/enhanced/dynamodb/DynamoDbTable.java, services-custom/dynamodb-enhanced/src/main/java/software/amazon/awssdk/enhanced/dynamodb/internal/client/DefaultDynamoDbAsyncTable.java, services-custom/dynamodb-enhanced/src/main/java/software/amazon/awssdk/enhanced/dynamodb/internal/client/DefaultDynamoDbTable.java, services-custom/dynamodb-enhanced/src/main/java/software/amazon/awssdk/enhanced/dynamodb/internal/operations/PutItemOperation.java, services-custom/dynamodb-enhanced/src/main/java/software/amazon/awssdk/enhanced/dynamodb/model/PutItemEnhancedRequest.java, services-custom/dynamodb-enhanced/src/main/java/software/amazon/awssdk/enhanced/dynamodb/model/PutItemEnhancedResponse.java, services-custom/dynamodb-enhanced/src/test/java/software/amazon/awssdk/enhanced/dynamodb/functionaltests/AsyncPutItemWithResponseTest.java, services-custom/dynamodb-enhanced/src/test/java/software/amazon/awssdk/enhanced/dynamodb/functionaltests/EmptyBinaryTest.java, services-custom/dynamodb-enhanced/src/test/java/software/amazon/awssdk/enhanced/dynamodb/functionaltests/EmptyStringTest.java, services-custom/dynamodb-enhanced/src/test/java/software/amazon/awssdk/enhanced/dynamodb/functionaltests/LocalDynamoDbSyncTestBase.java, services-custom/dynamodb-enhanced/src/test/java/software/amazon/awssdk/enhanced/dynamodb/functionaltests/PutItemWithResponseTest.java, services-custom/dynamodb-enhanced/src/test/java/software/amazon/awssdk/enhanced/dynamodb/internal/operations/PutItemOperationTest.java, services-custom/dynamodb-enhanced/src/test/java/software/amazon/awssdk/enhanced/dynamodb/model/PutItemEnhancedRequestTest.java, services-custom/dynamodb-enhanced/src/test/java/software/amazon/awssdk/enhanced/dynamodb/model/PutItemEnhancedResponseTest.java
Requested feature.
This commit introduces DynamoDbTable#putItemWithResponse() that allows customers
to specify additional parameters on the request such as ReturnValues to get
additional information the service response.
Relates to #1918
- Unit tests
- Integration tests
=> Implement return values for enhanced PutItem

buildspecs/update-master-from-release.yml
This fixes an issue where running the script when master is already on a 'SNAPSHOT' version will update the version to '1.0'.
=> Update update-master-from-release.yml to only update SNAPSHOT version if we're not already on a SNAPSHOT version.

.changes/next-release/feature-DynamoDBEnhancedClient-9086c03.json, services-custom/dynamodb-enhanced/src/it/java/software/amazon/awssdk/enhanced/dynamodb/AsyncDeleteItemWithResponseIntegrationTest.java, services-custom/dynamodb-enhanced/src/it/java/software/amazon/awssdk/enhanced/dynamodb/DeleteItemWithResponseIntegrationTest.java, services-custom/dynamodb-enhanced/src/main/java/software/amazon/awssdk/enhanced/dynamodb/DynamoDbAsyncTable.java, services-custom/dynamodb-enhanced/src/main/java/software/amazon/awssdk/enhanced/dynamodb/DynamoDbTable.java, services-custom/dynamodb-enhanced/src/main/java/software/amazon/awssdk/enhanced/dynamodb/internal/client/DefaultDynamoDbAsyncTable.java, services-custom/dynamodb-enhanced/src/main/java/software/amazon/awssdk/enhanced/dynamodb/internal/client/DefaultDynamoDbTable.java, services-custom/dynamodb-enhanced/src/main/java/software/amazon/awssdk/enhanced/dynamodb/internal/operations/DeleteItemOperation.java, services-custom/dynamodb-enhanced/src/main/java/software/amazon/awssdk/enhanced/dynamodb/model/DeleteItemEnhancedRequest.java, services-custom/dynamodb-enhanced/src/main/java/software/amazon/awssdk/enhanced/dynamodb/model/DeleteItemEnhancedResponse.java, services-custom/dynamodb-enhanced/src/test/java/software/amazon/awssdk/enhanced/dynamodb/functionaltests/AsyncDeleteItemWithResponseTest.java, services-custom/dynamodb-enhanced/src/test/java/software/amazon/awssdk/enhanced/dynamodb/functionaltests/DeleteItemWithResponseTest.java, services-custom/dynamodb-enhanced/src/test/java/software/amazon/awssdk/enhanced/dynamodb/internal/operations/DeleteItemOperationTest.java, services-custom/dynamodb-enhanced/src/test/java/software/amazon/awssdk/enhanced/dynamodb/internal/operations/PutItemOperationTest.java, services-custom/dynamodb-enhanced/src/test/java/software/amazon/awssdk/enhanced/dynamodb/model/DeleteItemEnhancedRequestTest.java, services-custom/dynamodb-enhanced/src/test/java/software/amazon/awssdk/enhanced/dynamodb/model/DeleteItemEnhancedResponseTest.java
Requested feature request.
This commit introduces DynamoDbTable#deleteItemWithResponse() that allows
customers to specify additional parameters on the request such as
ReturnConsumedCapacity to get additional information the service response.
Similar to https://github.com/aws/aws-sdk-java-v2/pull/2710.
Relates to #1918.
- Unit tests
- Integration tests
=> Implement return values on DeleteItem

.changes/next-release/bugfix-AWSSDKforJavav2-3312616.json, core/auth-crt/src/main/java/software/amazon/awssdk/authcrt/signer/internal/SigningUtils.java, core/auth-crt/src/test/java/software/amazon/awssdk/authcrt/signer/AwsCrtV4aSignerTest.java
The signed host header must match the host header sent on the wire. HTTP clients append the port to the host header if the port is non-standard for the protocol being used. The current Sigv4a signer only adds the host, not the port, to the host header. This means that endpoints with non-standard ports for the protocol (e.g. an HTTPS service on port 8443) would get a signature validation failure, because the HTTP client will change the host header. 
The Sigv4 signer handles this by adding the host header and port before calculating the signature. This PR adds that same logic to the Sigv4a signer.
=> Fix Sigv4a-signed requests to endpoints with non-standard ports.

.changes/next-release/bugfix-S3TransferManager-1dee8e5.json, services-custom/s3-transfer-manager/src/main/java/software/amazon/awssdk/transfer/s3/internal/DefaultS3TransferManager.java, services-custom/s3-transfer-manager/src/test/java/software/amazon/awssdk/transfer/s3/internal/S3TransferManagerTest.java
Fix NPE thrown when creating a default transfer manager
Added unit test
=> Fix NPE thrown when creating a default transfer manager

pom.xml
- The number of service clients increase  gradually with time , this caused Out Of Memory exception while running public-javadoc profile.
- 
Increasing the max memory for public-javadoc profile  by 50%.
=> Increasing the max memory for public-javadoc profile

docs/design/services/s3/transfermanager/listener/DecisionLog.md, docs/design/services/s3/transfermanager/listener/README.md
=> Add design & decision log for Transfer Manager Progress Listeners

.changes/next-release/feature-AWSSDKforJavav2-69eb988.json, core/aws-core/src/main/java/software/amazon/awssdk/awscore/client/builder/AwsDefaultClientBuilder.java, core/aws-core/src/main/resources/software/amazon/awssdk/global/handlers/execution.interceptors, core/sdk-core/src/main/java/software/amazon/awssdk/core/client/builder/SdkDefaultClientBuilder.java, core/sdk-core/src/main/resources/software/amazon/awssdk/global/handlers/execution.interceptors
This reduces the need for customers to use a special transformer for execution.interceptors files when they are creating an uber-jar of all SDK modules. Customers should still consider using such an appender, in case other libraries rely on execution.interceptors files.
=> Move SDK-provided global execution.interceptors to a hard-coded list.

.changes/next-release/bugfix-AWSSDKforJavav2-bd6fc5c.json, core/protocols/aws-json-protocol/src/main/java/software/amazon/awssdk/protocols/json/internal/marshall/JsonProtocolMarshaller.java, core/protocols/aws-json-protocol/src/main/java/software/amazon/awssdk/protocols/json/internal/unmarshall/JsonProtocolUnmarshaller.java, test/codegen-generated-classes-test/src/main/resources/codegen-resources/documenttype/service-2.json, test/codegen-generated-classes-test/src/test/java/software/amazon/awssdk/services/documenttype/DocumentTypeTest.java, test/protocol-tests-core/src/main/java/software/amazon/awssdk/protocol/reflect/ShapeModelReflector.java
1. DocumentType was not handled for explicit payload member.
2. In doMarshall() the Documents were getting Marshalled in below snippet whenever the Payload type was explicit payload
3. Explicit payload member are shapes where we Explicitly define the Payload member using "payload key"
```
if (val != null && field.containsTrait(PayloadTrait.class)) {
jsonGenerator.writeStartObject();
doMarshall((SdkPojo) val);
jsonGenerator.writeEndObject();
}
```
1. Fixed by adding specific check for DocumentType and calling its corresponding marshaling Type 
1. Added J-units for Explicit and Implicit payload
2. Note : test cases added in codegen-test because in protocol test there is an additional layer where the suite.json files gets marshalled , to make sure we test end-to-end added test in …
=> Bug Fix to support Document Type for Explicit Payload members

services-custom/s3-transfer-manager/src/test/java/software/amazon/awssdk/transfer/s3/internal/S3TransferManagerListenerTest.java
We already join on this future on line 185:
https://github.com/aws/aws-sdk-java-v2/blob/9832a7c3f3f71c58f538951694803b05909f667b/services-custom/s3-transfer-manager/src/test/java/software/amazon/awssdk/transfer/s3/internal/S3TransferManagerListenerTest.java#L185
This second join is redundant and will result in an exception being thrown.
=> Remove redundant join from unit test

codegen/src/main/java/software/amazon/awssdk/codegen/model/intermediate/ShapeModel.java, codegen/src/main/java/software/amazon/awssdk/codegen/poet/transform/protocols/EventStreamJsonMarshallerSpec.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/transform/eventonemarshaller.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/transform/eventthreemarshaller.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/transform/eventtwomarshaller.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/transform/inputeventmarshaller.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/transform/inputeventtwomarshaller.java, test/protocol-tests/src/main/resources/codegen-resources/restjson/contenttype/service-2.json, test/protocol-tests/src/test/java/software/amazon/awssdk/protocol/tests/RestJsonEventStreamProtocolTest.java
Bug fix.
Correctly propagate the existence of implicit event members down to the
marshaller.
- New unit tests
- ~~Running~~ integ tests
=> Fix rest-json marshalling for events

.changes/next-release/feature-NettyNIOHTTPClient-9406031.json, http-client-spi/src/main/java/software/amazon/awssdk/http/SdkHttpConfigurationOption.java, http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/NettyNioAsyncHttpClient.java, http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/internal/AwaitCloseChannelPoolMap.java, http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/internal/ChannelPipelineInitializer.java, http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/internal/Http1TunnelConnectionPool.java, http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/internal/NettyConfiguration.java, http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/internal/utils/NettyUtils.java, http-clients/netty-nio-client/src/test/java/software/amazon/awssdk/http/nio/netty/NettyNioAsyncHttpClientWireMockTest.java, http-clients/netty-nio-client/src/test/java/software/amazon/awssdk/http/nio/netty/internal/Http1TunnelConnectionPoolTest.java, http-clients/netty-nio-client/src/test/java/software/amazon/awssdk/http/nio/netty/internal/utils/NettyUtilsTest.java, http-clients/url-connection-client/src/main/java/software/amazon/awssdk/http/urlconnection/UrlConnectionHttpClient.java
This is to utilize the tlsNegotiationTimeout from the future `sdk-default-configuration.json`
Apache HTTP client 4.x and URLConnection currently don't support handshake timeout
Expose tlsNegotiationTimeout for netty client to allow users configure it.
=> Expose tlsNegotiationTimeout for netty client

codegen-lite-maven-plugin/src/main/java/software/amazon/awssdk/codegen/lite/maven/plugin/DefaultsModeGenerationMojo.java, codegen-lite/src/main/java/software/amazon/awssdk/codegen/lite/defaultsmode/DefaultsModeConfigurationGenerator.java, codegen-lite/src/test/java/software/amazon/awssdk/codegen/lite/defaultsmode/DefaultsModeGenerationTest.java, codegen-lite/src/test/resources/software/amazon/awssdk/codegen/lite/defaultsmode/defaults-mode-configuration.java, core/aws-core/src/main/java/software/amazon/awssdk/awscore/client/builder/AwsDefaultClientBuilder.java, core/aws-core/src/main/java/software/amazon/awssdk/awscore/internal/defaultsmode/AutoDefaultsModeDiscovery.java, core/aws-core/src/test/java/software/amazon/awssdk/awscore/client/builder/DefaultAwsClientBuilderTest.java, core/aws-core/src/test/java/software/amazon/awssdk/awscore/client/builder/DefaultsModeTest.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/client/builder/SdkDefaultClientBuilder.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/client/config/ClientOverrideConfiguration.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/client/config/SdkClientConfiguration.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/client/config/SdkClientOption.java, core/sdk-core/src/test/java/software/amazon/awssdk/core/client/config/SdkClientConfigurationTest.java, core/sdk-core/src/test/java/software/amazon/awssdk/core/internal/defaultsmode/DefaultsModeConfigurationTest.java, http-client-spi/src/main/java/software/amazon/awssdk/http/SdkHttpClient.java, http-client-spi/src/main/java/software/amazon/awssdk/http/async/SdkAsyncHttpClient.java, test/codegen-generated-classes-test/src/test/java/software/amazon/awssdk/services/defaultsmode/AsyncClientDefaultsModeTest.java, test/codegen-generated-classes-test/src/test/java/software/amazon/awssdk/services/defaultsmode/ClientDefaultsModeTestSuite.java, test/codegen-generated-classes-test/src/test/java/software/amazon/awssdk/services/defaultsmode/SyncClientDefaultsModeTest.java, utils/src/main/java/software/amazon/awssdk/utils/AttributeMap.java
- adding codegen change for `DefaultConfigurationConfiguration` which contains the default settings for each mode
- adding defaults from defaults mode to the configuration resolution chain
=> [Default Configuration Part 3]: add defaults from defaults mode to the configuration resolution chain

codegen-lite/src/main/java/software/amazon/awssdk/codegen/lite/defaultsmode/DefaultsLoader.java, codegen-lite/src/main/java/software/amazon/awssdk/codegen/lite/defaultsmode/DefaultsModeConfigurationGenerator.java, codegen-lite/src/test/resources/software/amazon/awssdk/codegen/lite/defaultsmode/defaults-mode-configuration.java, codegen-lite/src/test/resources/software/amazon/awssdk/codegen/lite/defaultsmode/defaults-mode.java
`tlsNegotiationTimeout` is supported in one of the http clients as part of #2806 
Support tlsNegotiationTimeout in default configuration
Updated generated files
=> [Default Configuration Part 4]: Add tlsNegotiationTimeout

.idea/inspectionProfiles/AWS_Java_SDK_2_0.xml, codegen/src/main/java/software/amazon/awssdk/codegen/AddOperations.java, codegen/src/main/java/software/amazon/awssdk/codegen/poet/client/specs/JsonProtocolSpec.java, codegen/src/main/java/software/amazon/awssdk/codegen/poet/client/specs/ProtocolSpec.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/http/pipeline/stages/ApplyUserAgentStage.java, http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/internal/NettyRequestExecutor.java, http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/internal/ResponseHandler.java, http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/internal/SslContextProvider.java, services-custom/dynamodb-enhanced/src/main/java/software/amazon/awssdk/enhanced/dynamodb/extensions/VersionedRecordExtension.java, services-custom/dynamodb-enhanced/src/main/java/software/amazon/awssdk/enhanced/dynamodb/mapper/StaticTableMetadata.java, services-custom/s3-transfer-manager/src/main/java/software/amazon/awssdk/transfer/s3/internal/S3CrtDataPublisher.java, services/s3/src/main/java/software/amazon/awssdk/services/s3/checksums/ChecksumsEnabledValidator.java, services/s3control/src/main/java/software/amazon/awssdk/services/s3control/internal/interceptors/PayloadSigningInterceptor.java, test/sdk-benchmarks/src/main/java/software/amazon/awssdk/benchmark/BenchmarkResultProcessor.java
Reports `equals()` calls on enum constants.
Such calls can be replaced by an identity comparison (`==`) because two
enum constants are equal only when they have the same identity.
A quick-fix is available to change the call to a comparison.
Example:
```
boolean foo(MyEnum value) {
return value.equals(MyEnum.FOO);
}
```
After the quick-fix is applied:
```
boolean foo(MyEnum value) {
return value == MyEnum.FOO;
}
```
=> Enable & fix inspection: `equals()` called on enum value

.idea/inspectionProfiles/AWS_Java_SDK_2_0.xml, codegen-lite/src/main/java/software/amazon/awssdk/codegen/lite/emitters/UnusedImportRemover.java, codegen/src/main/java/software/amazon/awssdk/codegen/emitters/UnusedImportRemover.java, codegen/src/main/java/software/amazon/awssdk/codegen/internal/DocumentationUtils.java, codegen/src/main/java/software/amazon/awssdk/codegen/model/intermediate/ListModel.java, codegen/src/main/java/software/amazon/awssdk/codegen/model/intermediate/VariableModel.java, codegen/src/main/java/software/amazon/awssdk/codegen/poet/PoetUtils.java, codegen/src/main/java/software/amazon/awssdk/codegen/poet/client/specs/JsonProtocolSpec.java, core/protocols/aws-json-protocol/src/main/java/software/amazon/awssdk/protocols/json/internal/unmarshall/JsonErrorCodeParser.java, core/protocols/protocol-core/src/main/java/software/amazon/awssdk/protocols/core/ProtocolUtils.java, services/glacier/src/main/java/software/amazon/awssdk/services/glacier/internal/GlacierExecutionInterceptor.java, services/route53/src/main/java/software/amazon/awssdk/services/route53/internal/Route53IdInterceptor.java, test/protocol-tests-core/src/main/java/software/amazon/awssdk/protocol/asserts/marshalling/UriAssertion.java
Reports single character strings being used as an argument in String.indexOf() and String.lastIndexOf() calls.
A quick-fix is suggested to replace such string literals with equivalent character literals, gaining some performance enhancement.
Example:
```
return s.indexOf("x");
```
After the quick-fix is applied:
```
return s.indexOf('x');
```
=> Enable & fix inspection: Single character string argument in `String.indexOf()` call

.changes/next-release/feature-AWSSDKforJavav2-7936e4e.json, core/profiles/src/main/java/software/amazon/awssdk/profiles/ProfileProperty.java
Added `duration_seconds` to the list of standard profile property keys as defined in https://docs.aws.amazon.com/cli/latest/topic/config-vars.html#using-aws-iam-roles
=> Add duration_seconds to list of profile properties

.idea/inspectionProfiles/AWS_Java_SDK_2_0.xml, core/profiles/src/main/java/software/amazon/awssdk/profiles/ProfileFileLocation.java, core/profiles/src/main/java/software/amazon/awssdk/profiles/internal/ProfileFileReader.java, core/protocols/aws-query-protocol/src/main/java/software/amazon/awssdk/protocols/query/internal/unmarshall/AwsXmlErrorUnmarshaller.java, core/protocols/aws-query-protocol/src/main/java/software/amazon/awssdk/protocols/query/internal/unmarshall/QueryProtocolUnmarshaller.java, http-client-spi/src/main/java/software/amazon/awssdk/http/SystemPropertyTlsKeyManagersProvider.java, http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/SdkEventLoopGroup.java, services-custom/s3-transfer-manager/src/main/java/software/amazon/awssdk/transfer/s3/internal/CrtErrorHandler.java, services-custom/s3-transfer-manager/src/main/java/software/amazon/awssdk/transfer/s3/internal/TransferManagerConfiguration.java, services/s3/src/main/java/software/amazon/awssdk/services/s3/checksums/ChecksumCalculatingAsyncRequestBody.java
Reports method calls that accept a non-trivial expression and can be replaced with an equivalent method call which accepts a lambda instead.
Converting an expression to a lambda ensures that the expression won't be evaluated if it's not used inside the method. For example, `optional.orElse(createDefaultValue())` can be converted to `optional.orElseGet(this::createDefaultValue)`.
=> Enable & fix inspection: Explicit argument can be lambda

.idea/inspectionProfiles/AWS_Java_SDK_2_0.xml, core/sdk-core/src/main/java/software/amazon/awssdk/core/document/internal/BooleanDocument.java, http-client-spi/src/main/java/software/amazon/awssdk/http/DefaultSdkHttpFullResponse.java, services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/endpoints/S3EndpointResolverContext.java
Reports construction of (temporary) new objects inside equals(),
hashCode(), compareTo(), and Comparator.compare() methods.
Besides constructor invocations, new objects can also be created by
autoboxing or iterator creation inside a foreach statement. This can
cause performance problems, for example, when objects are added to a Set
or Map, where these methods will be called often.
The inspection will not report when the objects are created in a throw
or assert statement.
Example:
```
class Person {
private String name;
private int age;
public boolean equals(Object o) {
return Arrays.equals(new Object[] {name, age}, new Object[] {((Foo)o).name, ((Foo)o).age});
}
public int hashCode() {
return (name + age).hashCode();
}
}
```
In this example, two additional arrays are created inside …
=> Enable & fix inspection: Object instantiation inside `equals()` or `hashCode()`

codegen-lite/src/main/java/software/amazon/awssdk/codegen/lite/defaultsmode/DefaultsModeConfigurationGenerator.java, codegen-lite/src/test/resources/software/amazon/awssdk/codegen/lite/defaultsmode/defaults-mode-configuration.java, core/aws-core/src/main/java/software/amazon/awssdk/awscore/client/builder/AwsDefaultClientBuilder.java, core/aws-core/src/main/java/software/amazon/awssdk/awscore/endpoint/DefaultServiceEndpointBuilder.java, core/aws-core/src/test/java/software/amazon/awssdk/awscore/client/builder/DefaultsModeTest.java, core/aws-core/src/test/java/software/amazon/awssdk/awscore/client/endpoint/DefaultServiceEndpointBuilderTest.java, core/regions/src/main/java/software/amazon/awssdk/regions/ServiceMetadataAdvancedOption.java, core/regions/src/main/java/software/amazon/awssdk/regions/ServiceMetadataConfiguration.java, core/regions/src/main/java/software/amazon/awssdk/regions/servicemetadata/EnhancedS3ServiceMetadata.java, core/regions/src/test/java/software/amazon/awssdk/regions/servicemetadata/EnhancedS3ServiceMetadataTest.java, core/regions/src/test/resources/profileconfig/s3_regional_config_profile_mixed_case.tst, core/regions/src/test/resources/profileconfig/s3_regional_config_profile_non_regional.tst, services/s3/src/test/java/software/amazon/awssdk/services/s3/S3EndpointResolutionTest.java
- Add `ServiceMetadataAdvancedOption` to support configuring s3 use us-east-1 regional setting
- Apply default s3 us-east-1 regional setting
=> [Default Configuration Part 6]: apply default s3 us-east-1 regional setting

buildspecs/build.yml, buildspecs/integ-test.yml, buildspecs/stability-test.yml
Easier and faster identification of failed tests in builds.
Trawling through the logs looking for the tests that failed is time consuming,
especially because tests are run in parallel, making the logs harder to follow.
This uses the test result dashboarding feature from CodeBuild to make it much
easier and faster to find tests that failed during a release.
Tested the buildspecs in personal account using the SDK v2.
=> Add reporting for release CodeBuild jobs

codegen/src/main/java/software/amazon/awssdk/codegen/poet/client/specs/JsonProtocolSpec.java, codegen/src/main/java/software/amazon/awssdk/codegen/poet/client/specs/QueryProtocolSpec.java, codegen/src/main/java/software/amazon/awssdk/codegen/poet/client/specs/XmlProtocolSpec.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/test-async-client-class.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/test-aws-json-async-client-class.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/test-customservicemetadata-async.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/test-endpoint-discovery-async.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/test-query-async-client-class.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/test-xml-async-client-class.java
Remove unused variable in the generated code
```
AwsRequestOverrideConfiguration requestOverrideConfig = streamingInputOutputOperationRequest.overrideConfiguration()
.orElse(null);
```
=> Remove unused var

.changes/next-release/bugfix-AWSSDKforJavav2-c20ef41.json, core/sdk-core/src/main/java/software/amazon/awssdk/core/RequestOverrideConfiguration.java, core/sdk-core/src/test/java/software/amazon/awssdk/core/RequestOverrideConfigurationTest.java, test/codegen-generated-classes-test/src/main/resources/codegen-resources/customresponsemetadata/paginators-1.json, test/codegen-generated-classes-test/src/main/resources/codegen-resources/customresponsemetadata/service-2.json, test/codegen-generated-classes-test/src/test/java/software/amazon/awssdk/services/metrics/CoreMetricsTest.java, test/codegen-generated-classes-test/src/test/java/software/amazon/awssdk/services/metrics/async/AsyncCoreMetricsTest.java
When a `requestOverrideConfiguration` is modified from an existing instance all values of existing fields should be copied. For instance, `metricPublishers` was missing, leading to the paginated operations code path missing metric publishers added as a request override and no metrics are published. 
Updated the `BuilderImpl` constructor that takes a `RequestOverrideConfiguration` as an argument. 
- Added unit tests to cover minimal and maximal cases of converting to builder and back
- Added functional test to verify usage of publishers
=> Adds all fields in RequestOverrideConfiguration in toBuilder

pom.xml
Update japicmp check to only run against certain modules including core modules, http clients, high level libraries as well as a few heavily customized services
=> Update japicmp check to only run against certain modules

pom.xml, services/pom.xml, services/s3/pom.xml, services/s3/src/it/java/software/amazon/awssdk/services/BlockHoundInstalledTest.java, test/service-test-utils/pom.xml, test/service-test-utils/src/main/java/software/amazon/awssdk/testutils/service/AwsIntegrationTestBase.java, test/service-test-utils/src/main/java/software/amazon/awssdk/testutils/service/AwsTestBase.java, test/stability-tests/pom.xml, test/stability-tests/src/it/java/software/amazon/awssdk/stability/tests/BlockHoundIntegrationTest.java
This PR enables [BlockHound](https://github.com/reactor/BlockHound) for the SDK integration test and stability tests. BlockHound can be used to detect blocking behavior in threads that must be treated as non-blocking, like Netty's EventLoop threads.
If BlockHound detects an illegal blocking operation being performed, it will throw a BlockingOperationError. Doing so in an integration test would typically fail the integration test and allow us to investigate the behavior.
This PR enables BlockHound by leveraging BlockHound's provided [BlockHoundTestExecutionListener](https://github.com/reactor/BlockHound/blob/2071ca8dbb06eba9ffa65596f327e3182d3b9730/junit-platform/src/main/java/reactor/blockhound/junit/platform/BlockHoundTestExecutionListener.java), which uses `@AutoService` to …
=> Enable BlockHound for integration tests and stability tests

core/auth/src/test/java/software/amazon/awssdk/auth/credentials/internal/Ec2MetadataConfigProviderEndpointModeTest.java, core/sdk-core/src/test/java/software/amazon/awssdk/core/internal/http/pipeline/stages/MergeCustomHeadersStageTest.java, core/sdk-core/src/test/java/software/amazon/awssdk/core/retry/RetryModeTest.java, core/sdk-core/src/test/java/software/amazon/awssdk/core/retry/RetryPolicyMaxRetriesTest.java
JUnit 4 -> 5 migrations are often done in a 3-step process:
1. Update dependencies to JUnit 5, including the vintage module, causing all tests to leverage the new JUnit 5 Platform
2. Incrementally migrate JUnit 4 tests to JUnit 5 tests
3. Once no JUnit 4 usage remains, remove the dependency on the vintage module
This PR continues step 2 by migrating some parameterized tests to JUnit 5.
=> [JUnit 5] Migrate some parameterized tests to JUnit 5

.changes/next-release/bugfix-AWSSDKforJavav2-66cf80a.json, core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/retry/RateLimitingTokenBucket.java, core/sdk-core/src/test/java/software/amazon/awssdk/core/internal/retry/RateLimitingTokenBucketTest.java
When the requested number of tokens is greater than the current available tokens, the code sets the capacity to `0` and then sleeps the required amount of time to accumulate the remaining amount; however that amount slept is not reflected in the last recorded refill time of the bucket. Refilling the bucket is time based, and each call to `acquire()` refills the bucket, using the difference between the current time and the last recorded refill time. In this case, the next call to `refill()` will the bucket with more tokens than intended.
Rather than setting the amount fo `0`, we should just let it go into the negative.
```
_TokenBucketAcquire(amount)
if not enabled
return
_TokenBucketRefill()
if amount <= current_capacity
current_capacity = current_capacity - amount
else
sleep((amount - …
```
=> Fix to correctly set TokenBucket capacity when requested amount greater than capacity

.changes/next-release/bugfix-nettynioclient-0fb07b2.json, http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/internal/http2/HttpOrHttp2ChannelPool.java, http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/internal/utils/NettyUtils.java, http-clients/netty-nio-client/src/test/java/software/amazon/awssdk/http/nio/netty/internal/http2/HttpOrHttp2ChannelPoolTest.java, http-clients/netty-nio-client/src/test/java/software/amazon/awssdk/http/nio/netty/internal/utils/NettyUtilsTest.java
Reverts aws/aws-sdk-java-v2#2895
Merging back https://github.com/aws/aws-sdk-java-v2/pull/2882
- The sanity test failed because of operational event.
=>  Merging back PR #2882

services/kinesis/src/it/java/software/amazon/awssdk/services/kinesis/KinesisIntegrationTests.java
It seems like this test started to fail because Kinesis changed the way merging shards worked - with records not being lost in merging. That makes sense, but we relied on the old behavior. Instead of just updating the assertions, updated the test to test less of the service's behavior without testing much less of the SDK behavior.
=> Fix @Ignored kinesis integration test to not test service behavior.

services-custom/dynamodb-enhanced/src/main/java/software/amazon/awssdk/enhanced/dynamodb/update/AddUpdateAction.java, services-custom/dynamodb-enhanced/src/main/java/software/amazon/awssdk/enhanced/dynamodb/update/DeleteUpdateAction.java, services-custom/dynamodb-enhanced/src/main/java/software/amazon/awssdk/enhanced/dynamodb/update/RemoveUpdateAction.java, services-custom/dynamodb-enhanced/src/main/java/software/amazon/awssdk/enhanced/dynamodb/update/SetUpdateAction.java, services-custom/dynamodb-enhanced/src/main/java/software/amazon/awssdk/enhanced/dynamodb/update/UpdateAction.java, services-custom/dynamodb-enhanced/src/main/java/software/amazon/awssdk/enhanced/dynamodb/update/UpdateExpression.java, services-custom/dynamodb-enhanced/src/test/java/software/amazon/awssdk/enhanced/dynamodb/update/AddUpdateActionTest.java, services-custom/dynamodb-enhanced/src/test/java/software/amazon/awssdk/enhanced/dynamodb/update/DeleteUpdateActionTest.java, services-custom/dynamodb-enhanced/src/test/java/software/amazon/awssdk/enhanced/dynamodb/update/RemoveUpdateActionTest.java, services-custom/dynamodb-enhanced/src/test/java/software/amazon/awssdk/enhanced/dynamodb/update/SetUpdateActionTest.java, services-custom/dynamodb-enhanced/src/test/java/software/amazon/awssdk/enhanced/dynamodb/update/UpdateExpressionTest.java
In order to support DynamoDB UpdateExpressions we need a representation of these concepts in the public API. 
https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Expressions.UpdateExpressions.html
Adding a set of classes to represent UpdateExpression actions, and an UpdateExpression class to contain them. See separate design document for motivation and architecture.
Unit tested.
=> UpdateExpression API

.changes/next-release/feature-NettyNIOHTTPClient-b9f6080.json, http-client-spi/src/main/java/software/amazon/awssdk/http/HttpMetric.java, http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/internal/NettyRequestExecutor.java, http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/internal/NettyRequestMetrics.java, http-clients/netty-nio-client/src/test/java/software/amazon/awssdk/http/nio/netty/Http2MetricsTest.java
The time taken to acquire a new channel from a channel pool can be both
non-trivial and highly variable, depending upon whether a new connection
needs to be established, and depending upon the overhead of new
connection establishment (including TLS handshakes). Due to the high
variability, having an explicit metric can be helpful to give a better
picture of latency sources in impacted requests.
=> Add "ConcurrencyAcquireDuration" metric for netty-nio-client

services-custom/dynamodb-enhanced/src/test/java/software/amazon/awssdk/enhanced/dynamodb/internal/operations/UpdateItemOperationTest.java
It's a big class and we'll need to add more tests.
=> Pure refactoring of UpdateItemOperation tests

.changes/next-release/feature-ApacheHTTPClient-2ecc813.json, http-client-spi/src/main/java/software/amazon/awssdk/http/HttpMetric.java, http-clients/apache-client/src/main/java/software/amazon/awssdk/http/apache/ApacheHttpClient.java, http-clients/apache-client/src/main/java/software/amazon/awssdk/http/apache/internal/conn/ClientConnectionManagerFactory.java, http-clients/apache-client/src/main/java/software/amazon/awssdk/http/apache/internal/conn/ClientConnectionRequestFactory.java, http-clients/apache-client/src/test/java/software/amazon/awssdk/http/apache/ApacheMetricsTest.java, http-clients/apache-client/src/test/java/software/amazon/awssdk/http/apache/internal/conn/ClientConnectionManagerFactoryTest.java
The time taken to acquire a new channel from a channel pool can be both non-trivial and highly variable, depending upon whether a new connection needs to be established, and depending upon the overhead of new connection establishment (including TLS handshakes).
The same metric was recently added for netty-nio-client: https://github.com/aws/aws-sdk-java-v2/pull/2903
Ideally we would avoid the use of `ThreadLocal`, but the Apache interfaces make it very difficult to expose a request-level `MetricsCollector` to the connection acquire call. While we can easily wrap a `HttpClientConnectionManager` to include metrics, the `HttpClientConnectionManager`, is declared at the Apache-client-level, meaning we would need to create (not just wrap) a new Apache client instance for every request. Apache …
=> Add "ConcurrencyAcquireDuration" metric for apache-client

.changes/next-release/feature-MetricsSPI-9675089.json, core/metrics-spi/pom.xml, core/metrics-spi/src/main/java/software/amazon/awssdk/metrics/LoggingMetricPublisher.java, core/metrics-spi/src/test/java/software/amazon/awssdk/metrics/LoggingMetricPublisherTest.java, core/metrics-spi/src/test/resources/log4j.properties, pom.xml, utils/src/main/java/software/amazon/awssdk/utils/Logger.java
LoggingMetricPublisher provides a convenient way to emit and inspect metrics via standard logging. The default log format is concise and perhaps difficult to read when looking for particular values. For users that wish to log metrics purely for debugging purposes, we should offer a more readable and user-friendly format. This PR introduces `PLAIN` and `PRETTY` format options to LoggingMetricPublisher.
`PLAIN` example (default/original behavior):
```
Metrics published: MetricCollection(name=ApiCall, metrics=[MetricRecord(metric=MarshallingDuration, value=PT0.000202197S),
MetricRecord(metric=RetryCount, value=0), MetricRecord(metric=ApiCallSuccessful, value=true),
MetricRecord(metric=OperationName, value=HeadObject), MetricRecord(metric=ApiCallDuration, value=PT0.468369S), …
```
=> Add pretty-format support to LoggingMetricPublisher

.idea/codeStyles/Project.xml
Enabling this setting allows IntelliJ's auto-format to take care of
wrapping JavaDoc comments to match our configured row width. When
writing length comments/descriptions, we can simply auto-format to have
every row formatted to fit to the correct width.
=> Enable "wrap at right margin" in JavaDoc code style settings

.changes/next-release/bugfix-AWSSDKforJavav2-7564897.json, codegen/src/main/java/software/amazon/awssdk/codegen/poet/client/specs/XmlProtocolSpec.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/test-xml-async-client-class.java, services/s3/src/it/java/software/amazon/awssdk/services/SelectObjectContentIntegrationTest.java, test/protocol-tests/src/test/java/software/amazon/awssdk/protocol/tests/RestXmlEventStreamProtocolTest.java
Bug fix.
Fix an issue where the code generator does not set the error response handler
when generating code for handling an eventstream response for XML protocol
services.
- New integration and protocol tests
- Verified diff of generated source
Checked the diffs of the 3 `REST-XML` services, S3, CloudFront, Route53, before and after the fix. Only `DefaultAmazonS3AsyncClient.java` had any diffs, which is expected.
```
diff -qr pre-fix post-fix
Files pre-fix/sdk/software/amazon/awssdk/services/s3/DefaultS3AsyncClient.java and post-fix/sdk/software/amazon/awssdk/services/s3/DefaultS3AsyncClient.java differ
```
```
diff pre-fix/sdk/software/amazon/awssdk/services/s3/DefaultS3AsyncClient.java post-fix/sdk/software/amazon/awssdk/services/s3/DefaultS3AsyncClient.java
```
```diff …
```
=> Set response handler for eventstream request

.changes/next-release/bugfix-ApacheHTTPClient-414635a.json, http-clients/apache-client/src/main/java/software/amazon/awssdk/http/apache/ApacheHttpClient.java, http-clients/apache-client/src/main/java/software/amazon/awssdk/http/apache/internal/SdkConnectionReuseStrategy.java, http-clients/url-connection-client/src/test/java/software/amazon/awssdk/http/urlconnection/UrlConnectionHttpClientWireMockTest.java, http-clients/url-connection-client/src/test/java/software/amazon/awssdk/http/urlconnection/UrlConnectionHttpClientWithCustomCreateWireMockTest.java, test/http-client-tests/src/main/java/software/amazon/awssdk/http/SdkHttpClientTestSuite.java
This was already the behavior for Netty, and cannot be made the behavior for the URL connection client.
=> Update Apache to not reuse connections if they received a 5xx error.

.changes/next-release/bugfix-AmazonS3-4bca731.json, core/aws-core/src/main/java/software/amazon/awssdk/awscore/internal/AwsErrorCode.java, services/s3/src/test/java/software/amazon/awssdk/services/s3/functionaltests/RetriesOn200Test.java
This fixes an issue where 200s followed by a failure were not retried for S3.
=> Retry on InternalError error codes.

.changes/next-release/bugfix-AWSSDKforJavav2-820a3eb.json, services-custom/dynamodb-enhanced/src/main/java/software/amazon/awssdk/enhanced/dynamodb/internal/extensions/ChainExtension.java, services-custom/dynamodb-enhanced/src/test/java/software/amazon/awssdk/enhanced/dynamodb/extensions/ChainExtensionTest.java
DynamoDB Enhanced Client allows custom extensions to be installed. However, the behavior of the meta extension ChainExtension differs when providing a `DefaultDynamoDbExtensionContext` to each extension's invocation of `afterRead`. The [default behavior](https://github.com/aws/aws-sdk-java-v2/blob/620c4c5690d5109a26940262d988ddb35cf7ecc1/services-custom/dynamodb-enhanced/src/main/java/software/amazon/awssdk/enhanced/dynamodb/internal/EnhancedClientUtils.java#L78) for a single extension (by ways of `VersionRecordExtension`) passes in the table schema to the builder. However, when two or more extensions are specified, `ChainExtension` omits the table schema entirely when it does the delegation. This breaks any custom extension that might require inferring the table schema in a read …
=> Set tableSchema to chained extensions read context

http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/internal/ChannelAttributeKey.java, http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/internal/ChannelDiagnostics.java, http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/internal/ChannelPipelineInitializer.java, http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/internal/NettyRequestExecutor.java, http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/internal/ResponseHandler.java, http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/internal/http2/MultiplexedChannelRecord.java, http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/internal/utils/NettyUtils.java, http-clients/netty-nio-client/src/test/java/software/amazon/awssdk/http/nio/netty/NettyClientTlsAuthTest.java, http-clients/netty-nio-client/src/test/java/software/amazon/awssdk/http/nio/netty/fault/DelegatingSslEngine.java, http-clients/netty-nio-client/src/test/java/software/amazon/awssdk/http/nio/netty/fault/ServerConnectivityErrorMessageTest.java, http-clients/netty-nio-client/src/test/java/software/amazon/awssdk/http/nio/netty/internal/PublisherAdapterTest.java, services/pom.xml, test/http-client-tests/src/main/java/software/amazon/awssdk/http/SdkAsyncHttpClientH1TestSuite.java
#2957 was rolled back because it did not account for HEAD responses, and broke for S3 integration tests. This fixes that issue: Do not validate content-length for 304 and HEAD responses.
This PR is separated into two different commits so it's easier to ignore the previously-reviewed code and the fixes to that code.
=> Revert the rollback of #2957

codegen/src/main/java/software/amazon/awssdk/codegen/AddOperations.java, codegen/src/main/java/software/amazon/awssdk/codegen/model/intermediate/OperationModel.java, codegen/src/main/java/software/amazon/awssdk/codegen/model/service/Operation.java, codegen/src/main/java/software/amazon/awssdk/codegen/poet/client/AsyncClientInterface.java, codegen/src/main/java/software/amazon/awssdk/codegen/poet/client/ClientClassUtils.java, codegen/src/main/java/software/amazon/awssdk/codegen/poet/client/SyncClientInterface.java, codegen/src/main/java/software/amazon/awssdk/codegen/poet/model/DeprecationUtils.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/c2j/rest-json/service-2.json, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/test-json-async-client-interface.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/test-json-client-interface.java
This change generates the @Deprecated annotation for all APIs marked as deprecated in the C2J model.
This adds clear guidance for deprecated APIs in the IDE.
N/A
Modifies the code generator to add the @Deprecated annotation to client/interface methods that correspond to a deprecated API.
Added deprecated trait to one of the existing poet test models and modified expected generation files.
- [ x] New feature (non-breaking change which adds functionality)
- [ x] I have read the [CONTRIBUTING](https://github.com/aws/aws-sdk-java-v2/blob/master/CONTRIBUTING.md) document
- [x ] Local run of `mvn install` succeeds
- [x ] My code follows the code style of this project
- [x ] I have added tests to cover my changes
- [x ] All new and existing tests passed
- [x ] I confirm that this pull request …
=> Adding @Deprecated annotation when API is marked as deprecated

.changes/next-release/bugfix-S3TransferManager-2f34394.json, services-custom/s3-transfer-manager/src/main/java/software/amazon/awssdk/transfer/s3/CompletedDirectoryDownload.java, services-custom/s3-transfer-manager/src/main/java/software/amazon/awssdk/transfer/s3/CompletedDirectoryTransfer.java, services-custom/s3-transfer-manager/src/main/java/software/amazon/awssdk/transfer/s3/CompletedDirectoryUpload.java, services-custom/s3-transfer-manager/src/main/java/software/amazon/awssdk/transfer/s3/DownloadDirectoryOverrideConfiguration.java, services-custom/s3-transfer-manager/src/main/java/software/amazon/awssdk/transfer/s3/UploadDirectoryOverrideConfiguration.java, services-custom/s3-transfer-manager/src/main/java/software/amazon/awssdk/transfer/s3/internal/UploadDirectoryHelper.java, services-custom/s3-transfer-manager/src/test/java/software/amazon/awssdk/transfer/s3/DownloadDirectoryOverrideConfigurationTest.java
1. `CompletedDirectoryUpload#failedTransfers` now returns `List<FailedFileUpload>` instead of `Collection<FailedFileUpload>`. 
2. `UploadDirectoryOverrideConfiguration#uploadFileRequestTransformer` now returns `Consumer<UploadFileRequest.Builder>` instead of `Optional<Consumer<UploadFileRequest.Builder>>` it will be no-op if no uploadFileRequestTransformer is provided
=> A couple of minor refactoring on the S3TransferManager

.changes/next-release/feature-AWSSDKforJavav2-d9ba0a4.json, core/aws-core/src/main/java/software/amazon/awssdk/awscore/exception/AwsServiceException.java, core/aws-core/src/test/java/software/amazon/awssdk/awscore/exception/AwsServiceExceptionTest.java
Currently, every `AwsServiceException` message contains a field for the `"Extended Request ID"`, even though only a minority of services actually utilize two request IDs. Explicitly mentioning `"Extended Request ID: null"` may cause it to appear like the extended request ID is missing, even if it was not expected in the response. Beyond being potentially misleading, it also contributes to making the core exception wording more verbose than it needs to be.
=> Only include non-null Extended Request IDs in exception messages

.changes/next-release/documentation-AWSSDKforJavav2-af5702d.json, core/sdk-core/src/main/java/software/amazon/awssdk/core/client/config/SdkAdvancedAsyncClientOption.java
This enhances the documentation around `SdkAdvancedAsyncClientOption#FUTURE_COMPLETION_EXECUTOR` to more clearly explain its usage and to warn of potential negative side effects if it is misconfigured or misused.
=> Improve documentation & add warnings for FUTURE_COMPLETION_EXECUTOR

services/s3/src/main/java/software/amazon/awssdk/services/s3/presigner/S3Presigner.java
Clarify somewhat confusing behavior.
Javadoc update to clarify that checksum validation makes URL browser incompatible.
N/A javadoc update.
=> Clarify what makes URL browser incompatible

.changes/next-release/bugfix-NettyNIOAsyncHTTPClient-b5e47f7.json, http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/internal/FutureCancelHandler.java, http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/internal/NettyRequestExecutor.java, http-clients/netty-nio-client/src/test/java/software/amazon/awssdk/http/nio/netty/internal/FutureCancelHandlerTest.java
Fix NPE in netty client where a future got cancelled before the execution id was attached to the channel
Add null check in `FutureCancelHandler` to handle the edge case
=> Fix NPE in netty client

core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/http/pipeline/stages/MakeAsyncHttpRequestStage.java, test/protocol-tests/src/test/java/software/amazon/awssdk/protocol/tests/AsyncResponseThreadingTest.java, test/protocol-tests/src/test/java/software/amazon/awssdk/protocol/tests/retry/AsyncAwsJsonRetryTest.java, test/protocol-tests/src/test/resources/jetty-logging.properties
Fixed the issue where the SDK did not offload future completion to the future completion executor
**Happy case workflow** (Always complete on futureCompletionExecutor)
- `responseFuture` gets completed by `futureCompletionExecutor` after the future in the `AsyncResponseHandler#prepare` gets completed
https://github.com/aws/aws-sdk-java-v2/blob/e4c4612fe3c6250ed6995de2f71a11cfbc79b2bb/core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/http/pipeline/stages/MakeAsyncHttpRequestStage.java#L210-L216
- `toReturn` future gets completed after  `responseFuture` gets completed. This will happen in the `futureCompletionExecutor`.
https://github.com/aws/aws-sdk-java-v2/blob/e4c4612fe3c6250ed6995de2f71a11cfbc79b2bb/core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/http/pipe …
=> Fixed the issue where the SDK did not offload future completion

.changes/next-release/feature-AWSSDKforJavav2-21e4b73.json, core/sdk-core/src/main/java/software/amazon/awssdk/core/client/builder/SdkClientBuilder.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/client/builder/SdkDefaultClientBuilder.java, core/sdk-core/src/test/java/software/amazon/awssdk/core/client/builder/DefaultClientBuilderTest.java
Want to change client configuration overrides in multiple locations in code.
#3023 
Add new method to `SdkClientBuilder` interface and `SdkDefaultClientBuilder` 
Created new test methods to ensure the returned `ClientOverrideConfiguration` matches what is input
=> Add ClientOverrideConfiguration getter to SdkClientBuilder. (#3023)

.changes/next-release/bugfix-URLConnectionHTTPClient-5e986d3.json, http-clients/url-connection-client/pom.xml, http-clients/url-connection-client/src/main/java/software/amazon/awssdk/http/urlconnection/UrlConnectionHttpClient.java, http-clients/url-connection-client/src/test/java/software/amazon/awssdk/http/urlconnection/Expect100ContinueTest.java, http-clients/url-connection-client/src/test/java/software/amazon/awssdk/http/urlconnection/UrlConnectionHttpClientWireMockTest.java
HTTPURLConnection currently throws a ProtocolException if the service returns anything other than a 100 or 417 response code to an expect-100-continue request. S3 sometimes triggers this behavior. This change catches this exception and treats it according to its response code, assuming that it can verify that no information was lost (e.g. because of a response payload being included in the response). If it still fails, it instructs the customer that the apache HTTP client could be a true solution to the problem.
=> Improved Expect: 100-continue response handling in the URL connection client.

services-custom/dynamodb-enhanced/src/main/java/software/amazon/awssdk/enhanced/dynamodb/internal/update/UpdateExpressionConverter.java, services-custom/dynamodb-enhanced/src/main/java/software/amazon/awssdk/enhanced/dynamodb/internal/update/UpdateExpressionUtils.java, services-custom/dynamodb-enhanced/src/main/java/software/amazon/awssdk/enhanced/dynamodb/update/AddAction.java, services-custom/dynamodb-enhanced/src/main/java/software/amazon/awssdk/enhanced/dynamodb/update/DeleteAction.java, services-custom/dynamodb-enhanced/src/main/java/software/amazon/awssdk/enhanced/dynamodb/update/RemoveAction.java, services-custom/dynamodb-enhanced/src/main/java/software/amazon/awssdk/enhanced/dynamodb/update/SetAction.java, services-custom/dynamodb-enhanced/src/main/java/software/amazon/awssdk/enhanced/dynamodb/update/UpdateExpression.java, services-custom/dynamodb-enhanced/src/test/java/software/amazon/awssdk/enhanced/dynamodb/extensions/ChainExtensionTest.java, services-custom/dynamodb-enhanced/src/test/java/software/amazon/awssdk/enhanced/dynamodb/functionaltests/UpdateExpressionTest.java, services-custom/dynamodb-enhanced/src/test/java/software/amazon/awssdk/enhanced/dynamodb/functionaltests/models/RecordForUpdateExpressions.java, services-custom/dynamodb-enhanced/src/test/java/software/amazon/awssdk/enhanced/dynamodb/internal/operations/UpdateItemOperationTest.java, services-custom/dynamodb-enhanced/src/test/java/software/amazon/awssdk/enhanced/dynamodb/internal/update/UpdateExpressionConverterTest.java, services-custom/dynamodb-enhanced/src/test/java/software/amazon/awssdk/enhanced/dynamodb/update/AddActionTest.java, services-custom/dynamodb-enhanced/src/test/java/software/amazon/awssdk/enhanced/dynamodb/update/DeleteActionTest.java, services-custom/dynamodb-enhanced/src/test/java/software/amazon/awssdk/enhanced/dynamodb/update/RemoveActionTest.java, services-custom/dynamodb-enhanced/src/test/java/software/amazon/awssdk/enhanced/dynamodb/update/SetActionTest.java, services-custom/dynamodb-enhanced/src/test/java/software/amazon/awssdk/enhanced/dynamodb/update/UpdateExpressionTest.java
Adding copyable builders helps users write fluent code. Renaming action names and removing the `Update` will also hopefully feel more natural and less ambiguous, ie. going from `AddUpdateAction` to `AddAction`. 
- Added copyable builder
- Renamed UpdateAction classes
- Updated the functional tests
Reran all functional tests, refactored and added more test cases.
=> Change action names and add copyable builders

services-custom/s3-transfer-manager/src/main/java/software/amazon/awssdk/transfer/s3/S3ClientConfiguration.java, services-custom/s3-transfer-manager/src/main/java/software/amazon/awssdk/transfer/s3/internal/DefaultS3CrtAsyncClient.java, services-custom/s3-transfer-manager/src/main/java/software/amazon/awssdk/transfer/s3/internal/DefaultS3TransferManager.java, services-custom/s3-transfer-manager/src/main/java/software/amazon/awssdk/transfer/s3/internal/S3CrtAsyncClient.java, services-custom/s3-transfer-manager/src/main/java/software/amazon/awssdk/transfer/s3/internal/S3CrtAsyncHttpClient.java, services-custom/s3-transfer-manager/src/main/java/software/amazon/awssdk/transfer/s3/internal/S3NativeClientConfiguration.java, services-custom/s3-transfer-manager/src/test/java/software/amazon/awssdk/transfer/s3/S3ClientConfigurationTest.java, services-custom/s3-transfer-manager/src/test/java/software/amazon/awssdk/transfer/s3/internal/S3CrtAsyncHttpClientTest.java
Allow setting endpointOverride for the S3TransferManager
https://github.com/aws/aws-sdk-java-v2/issues/2740
https://github.com/aws/aws-sdk-java-v2/issues/2945
The S3AsyncClient offers the ability to set the endpointOverride as follows:
```
S3AsyncClient.builder().endpointOverride(URI("http://minio-s3:9000"))
```
This change adds the endpointOverride feature to the S3TransferManager.
Enhance the `S3TransferManager` `S3ClientConfiguration` with the ability to set the `endpointOverride(URI)`. This feature requires the following enhancement provided in aws-crt-java v0.15.20: https://github.com/awslabs/aws-crt-java/commit/f5a7955989d3b2701d923631886666e6d41bcd23.
I executed all s3-transfer-manager unit and integration tests with these changes applied using "isolated" S3 test buckets. I also …
=> Expose S3TransferManager property S3ClientConfiguration.endpointOverride

services-custom/s3-transfer-manager/pom.xml, services-custom/s3-transfer-manager/src/it/java/software/amazon/awssdk/transfer/s3/S3TransferManagerUploadDirectoryUnicodeIntegrationTest.java
=> Add Transfer Manager integ tests for local dirs with Unicode characters

.changes/next-release/feature-AWSSDKforJavav2-1ee4d61.json, .changes/next-release/feature-S3TransferManagerDevelperPreview-55da0f7.json, core/sdk-core/src/main/java/software/amazon/awssdk/core/FileTransformerConfiguration.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/async/AsyncResponseTransformer.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/async/FileAsyncResponseTransformer.java, core/sdk-core/src/test/java/software/amazon/awssdk/core/FileTransformerConfigurationTest.java, core/sdk-core/src/test/java/software/amazon/awssdk/core/internal/async/FileAsyncResponseTransformerTest.java, core/sdk-core/src/test/java/software/amazon/awssdk/core/internal/async/FileSubscriberTckTest.java, services-custom/s3-transfer-manager/src/it/java/software/amazon/awssdk/transfer/s3/S3TransferManagerDownloadIntegrationTest.java, services-custom/s3-transfer-manager/src/main/java/software/amazon/awssdk/transfer/s3/internal/DefaultS3TransferManager.java, services/s3/src/it/java/software/amazon/awssdk/services/s3/GetObjectAsyncIntegrationTest.java
#3108 
#2300 
- Expose an option to overwrite an existing file in `FileAsyncResponseTransformer`.
- Note that it's not added to `FileResponseTransformer` right now because it's not trivial to do so. I will create a backlog item for it.
Added unit tests and integ tests
=> [TM DownloadFile Pause and Resume] Part 1: Add configuration to enable overwriting existing files

.changes/next-release/bugfix-AWSSDKforJavav2-edfb037.json, codegen/src/main/java/software/amazon/awssdk/codegen/poet/model/MemberCopierSpec.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/listofmapofstringtostructcopier.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/listofsimplestructscopier.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/mapofenumtosimplestructcopier.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/mapofstringtosimplestructcopier.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/recursivelisttypecopier.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/recursivemaptypecopier.java, test/codegen-generated-classes-test/src/test/java/software/amazon/awssdk/services/ModelSerializationTest.java
Fix NPE thrown from serializing/deserializing a structure that has map type with null values
Added unit test
=> Fix NPE thrown from serializing/deserializing a structure that has map type with null values

.changes/next-release/bugfix-AWSSDKforJavav2-d839c10.json, core/auth/src/main/java/software/amazon/awssdk/auth/credentials/InstanceProfileCredentialsProvider.java, core/auth/src/test/java/software/amazon/awssdk/auth/credentials/InstanceProfileCredentialsProviderTest.java
Intended to address #3142. It hasn't been verified to work, but it should address any issues until we can figure out why the previous strategy did not work.
=> Refresh IMDS credentials more aggressively.

.changes/next-release/feature-AWSSDKforJavav2-ff80eee.json, core/auth/src/main/java/software/amazon/awssdk/auth/credentials/InstanceProfileCredentialsProvider.java, utils/src/main/java/software/amazon/awssdk/utils/cache/CachedSupplier.java, utils/src/main/java/software/amazon/awssdk/utils/cache/NonBlocking.java, utils/src/test/java/software/amazon/awssdk/utils/cache/CachedSupplierTest.java
Today, if customers have async credential refreshes enabled, refreshes only kicked off when new credentials are requested. This causes an issue for very low-traffic credential providers, because they may never refresh credentials until those credentials are actually needed, and then it's too late.
With this change, we periodically prime all CachedSuppliers configured with a NonBlocking prefetch strategy and stale credentials.
One additional change was made to simplify the prefetch timings of InstanceProfileCredentialsProvider so they are easier to understand and reason about.
=> Automatically refresh async credential sources in the background.

.changes/next-release/bugfix-AWSSDKforJavav2-61bbbf3.json, core/protocols/aws-json-protocol/src/main/java/software/amazon/awssdk/protocols/json/internal/marshall/HeaderMarshaller.java, core/protocols/aws-xml-protocol/src/main/java/software/amazon/awssdk/protocols/xml/internal/marshall/HeaderMarshaller.java, test/protocol-tests-core/src/main/resources/software/amazon/awssdk/protocol/suites/cases/rest-json-input.json, test/protocol-tests-core/src/main/resources/software/amazon/awssdk/protocol/suites/cases/rest-xml-input.json
-  Empty strings in list of strings  to be ignored while marshalling this list to a header field.
- Test cases for inputs with double quotes , single quotes and empty string were missing.
- Added skipPredicateMap that will skip Marshlling of of String element if its empty,
- Added new test cases with special characters like comma, double quotes and single quotes
- Added Junits.
=> Fix to ignore empty strings while marshalling list of strings in header field

.changes/next-release/feature-AWSSDKforJavav2-019753e.json, pom.xml, services-custom/s3-transfer-manager/src/main/java/software/amazon/awssdk/transfer/s3/internal/S3CrtAsyncHttpClient.java
Bump CRT version to 0.16.10, which contains M1 support #2942
~~Running test suites now~~ integ tests and stability tests passed
=> Bump CRT version to 0.16.10, which contains M1 support #2942

.github/workflows/closed-issue-message.yml, .github/workflows/stale-issue.yml
Github Actions don't get write permission by default anymore. This PR explicitly gives write permission to issues and pull-requests scopes to the `Close Stale Issues` action and `Comment on closed issues` action.
Additionally, included the `help wanted` label to the list of exempt labels.
For more info on GH Action permissions: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
=> Give permissions to Github Actions

.changes/next-release/feature-AWSSTS-e86cc0d.json, bom-internal/pom.xml, core/auth/src/main/java/software/amazon/awssdk/auth/credentials/WebIdentityTokenFileCredentialsProvider.java, pom.xml, services/sts/pom.xml, services/sts/src/main/java/software/amazon/awssdk/services/sts/auth/StsWebIdentityTokenFileCredentialsProvider.java, services/sts/src/main/java/software/amazon/awssdk/services/sts/internal/AssumeRoleWithWebIdentityRequestSupplier.java, services/sts/src/main/java/software/amazon/awssdk/services/sts/internal/StsWebIdentityCredentialsProviderFactory.java, services/sts/src/test/java/software/amazon/awssdk/services/sts/auth/StsCredentialsProviderTestBase.java, services/sts/src/test/java/software/amazon/awssdk/services/sts/auth/StsWebIdentityTokenCredentialProviderTest.java, services/sts/src/test/java/software/amazon/awssdk/services/sts/auth/StsWebIdentityTokenCredentialsProviderBaseTest.java
Extension of [PR #2488](https://github.com/aws/aws-sdk-java-v2/pull/2488)
Adding New WebIdentityTokenFileCredentialsProvider  in sts that accepts STSClient
- Currently the WebIdentityTokenFileCredentialsProvider is in core module and it creates AwsCredentialsProvider with Default Sts Client.
- We cannot modify the [WebIdentityTokenCredentialsProviderFactory](https://github.com/aws/aws-sdk-java-v2/blob/584ccb59e770177aeaa4c3b6bda4e24015b8ece9/core/auth/src/main/java/software/amazon/awssdk/auth/credentials/WebIdentityTokenCredentialsProviderFactory.java) because  the interface is marked as @FunctionalInterface  and also StsClient is not available in core package so would need to pass SdkClient which would be confusing.
- Thus we have added a new WebIdentityTokenFileCredentialsProvider in …
=> Adding New StsWebIdentityTokenFileCredentialsProvider in sts module that accepts STSClien

codegen/src/main/java/software/amazon/awssdk/codegen/model/config/customization/AdditionalBuilderMethod.java, codegen/src/main/java/software/amazon/awssdk/codegen/model/config/customization/CustomizationConfig.java, codegen/src/main/java/software/amazon/awssdk/codegen/poet/client/AsyncClientInterface.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/c2j/rest-json/customization.config, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/test-json-async-client-interface.java, services/s3/src/it/java/software/amazon/awssdk/services/s3/crt/S3CrtGetObjectIntegrationTest.java, services/s3/src/main/resources/codegen-resources/customization.config
- Provide API in  S3AsyncClient to create instance of  S3CrtAsyncClient .
```json
"additionalBuilderMethods": [
{
"methodName": "crtBuilder",
"clientTypes": ["async"],
"instanceType": "software.amazon.awssdk.services.s3.internal.crt.S3CrtAsyncClient",
"returnType": "software.amazon.awssdk.services.s3.internal.crt.S3CrtAsyncClient.S3CrtAsyncClientBuilder"
}
],
```
```java
/**
* Create a builder that can be used to configure and create a {@link S3CrtAsyncClient}
*/
static S3CrtAsyncClientBuilder crtBuilder() {
return S3CrtAsyncClient.builder();
}
```
- Added custom config in codegen to generate additional builders if specified.
- Junits
- Integ test updated with the new builder.
=> Added customization in codegen to generate additional builder methods

pom.xml, services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/crt/S3CrtResponseHandlerAdapter.java, services/s3/src/test/java/software/amazon/awssdk/services/s3/internal/crt/S3CrtResponseHandlerAdapterTest.java
CRT changed the API as part of https://github.com/awslabs/aws-crt-java/pull/458 
This PR bumps up the CRT version and fixes the compilation error
Running test suites now
=> Bump CRT to 0.16.16

core/imds/pom.xml, core/imds/src/main/java/software/amazon/awssdk/imds/Ec2Metadata.java, core/imds/src/main/java/software/amazon/awssdk/imds/internal/DefaultEc2Metadata.java, core/imds/src/main/java/software/amazon/awssdk/imds/internal/EndpointMode.java, core/imds/src/test/java/software/amazon/awssdk/imds/Ec2MetadataTest.java
Created a Client Class . Implemented the Builder Interface and the entire build functionality to create client Objects.
Implemented the Builder Interface and the entire build functionality to create client Objects. 
Implemented the Builder Interface and the entire build functionality to create client Objects.
Wrote Unit cases to test the multiple methods
- [X ] New feature (non-breaking change which adds functionality)
- [ X] I have read the [CONTRIBUTING](https://github.com/aws/aws-sdk-java-v2/blob/master/CONTRIBUTING.md) document
- [ X] Local run of `mvn install` succeeds
- [ X] My code follows the code style of this project
- [ X] I have added tests to cover my changes
- [ X] All new and existing tests passed
- [ X] I confirm that this pull request can be released under the Apache 2 …
=>  Created the Configuration class for Ec2Metadata

.changes/next-release/bugfix-AWSSDKforJavav2-52c39b2.json, codegen/src/main/java/software/amazon/awssdk/codegen/poet/client/specs/JsonProtocolSpec.java, codegen/src/main/java/software/amazon/awssdk/codegen/poet/client/specs/QueryProtocolSpec.java, codegen/src/main/java/software/amazon/awssdk/codegen/poet/client/specs/XmlProtocolSpec.java, codegen/src/main/java/software/amazon/awssdk/codegen/poet/client/traits/NoneAuthTypeRequestTrait.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/c2j/json/service-2.json, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/c2j/query/service-2.json, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/c2j/xml/service-2.json, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/test-aws-json-async-client-class.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/test-query-async-client-class.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/test-query-client-class.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/test-xml-async-client-class.java, codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/test-xml-client-class.java, core/aws-core/src/main/java/software/amazon/awssdk/awscore/internal/AwsExecutionContextBuilder.java, core/sdk-core/src/main/java/software/amazon/awssdk/core/interceptor/SdkInternalExecutionAttribute.java, test/codegen-generated-classes-test/src/main/resources/codegen-resources/customresponsemetadata/service-2.json, test/codegen-generated-classes-test/src/main/resources/codegen-resources/xml/service-2.json, test/codegen-generated-classes-test/src/test/java/software/amazon/awssdk/services/NoneAuthTypeRequestTest.java
```json
"SignUp":{
"name":"SignUp",
"http":{
"method":"POST",
"requestUri":"/"
},
"input":{"shape":"SignUpRequest"},
"output":{"shape":"SignUpResponse"},
"errors":[
{"shape":"ResourceNotFoundException"},
],
"authtype":"none"
},
```
Operations as above explicitly mentions that the `authtype` should be `none`. In such cases the requests should not be authorized and credentials should not be resolved for such requests.
- Added a new executionAttribute to mark the operations which are authtype as none.
- This executionAttribute is then used while assigning signers and credentials.
- Note that signer is assigned as Null because if we assign a Dumy or NoOp signer its still a signer and should be considered in merics collection, thus to avoid unecessary metrics collection its best to allocate …
=> Skip Signing of requests which are defined with authtype as none

.changes/next-release/feature-AWSSDKforJavav2-36b8c47.json, .changes/next-release/feature-AWSSDKforJavav2-8f6d13b.json, .changes/next-release/feature-AWSSDKforJavav2-d28e3ad.json, core/auth/src/main/java/software/amazon/awssdk/auth/credentials/HttpCredentialsProvider.java, core/auth/src/main/java/software/amazon/awssdk/auth/credentials/InstanceProfileCredentialsProvider.java, core/auth/src/main/java/software/amazon/awssdk/auth/credentials/ProcessCredentialsProvider.java, core/auth/src/test/java/software/amazon/awssdk/auth/credentials/InstanceProfileCredentialsProviderTest.java, services/sso/src/main/java/software/amazon/awssdk/services/sso/auth/SsoCredentialsProvider.java, services/sts/src/main/java/software/amazon/awssdk/services/sts/auth/StsAssumeRoleCredentialsProvider.java, services/sts/src/main/java/software/amazon/awssdk/services/sts/auth/StsAssumeRoleWithSamlCredentialsProvider.java, services/sts/src/main/java/software/amazon/awssdk/services/sts/auth/StsAssumeRoleWithWebIdentityCredentialsProvider.java, services/sts/src/main/java/software/amazon/awssdk/services/sts/auth/StsCredentialsProvider.java, services/sts/src/main/java/software/amazon/awssdk/services/sts/auth/StsGetFederationTokenCredentialsProvider.java, services/sts/src/main/java/software/amazon/awssdk/services/sts/auth/StsGetSessionTokenCredentialsProvider.java, services/sts/src/main/java/software/amazon/awssdk/services/sts/auth/StsWebIdentityTokenFileCredentialsProvider.java, utils/pom.xml, utils/src/main/java/software/amazon/awssdk/utils/ComparableUtils.java, utils/src/main/java/software/amazon/awssdk/utils/cache/CachedSupplier.java, utils/src/main/java/software/amazon/awssdk/utils/cache/NonBlocking.java, utils/src/test/java/software/amazon/awssdk/utils/cache/CachedSupplierTest.java, utils/src/test/resources/log4j2.properties
Fixes #3259.
1. Share thread pools across async credential providers (anything using CachedSupplier's NonBlocking prefetch strategy).
2. Log a warning if an extreme number of concurrent refreshes are happening, to help users detect when they're not closing their credential providers.
Even though this is an increase in resource sharing, it should not cause increased availability risks. Because these threads are only used for background refreshes, if one particular type of credential provider has availability problems (e.g. SSO or STS high latency), it only disables background refreshes, not prefetches or synchronous fetches.
=> Reduced resource consumption of async credential providers.

.changes/next-release/bugfix-URLConnectionClient-98f14e7.json, http-client-spi/src/main/java/software/amazon/awssdk/http/Header.java, http-clients/url-connection-client/src/main/java/software/amazon/awssdk/http/urlconnection/UrlConnectionHttpClient.java, http-clients/url-connection-client/src/test/java/software/amazon/awssdk/http/urlconnection/UrlConnectionHttpClientWireMockTest.java, test/http-client-tests/src/main/java/software/amazon/awssdk/http/SdkHttpClientTestSuite.java
Set the `Accept` header for `UrlConnectionHttpClient` because the default one does not comply with RFC 7231. See https://bugs.openjdk.org/browse/JDK-8163921
The change upstream has only been released in JDK 19.  https://github.com/openjdk/jdk/commit/28796cbd1d15de678b80295418f5d1f9f59176a6
=> Set Accept header for UrlConnectionHttpClient

core/imds/src/main/java/software/amazon/awssdk/imds/Ec2Metadata.java, core/imds/src/main/java/software/amazon/awssdk/imds/Ec2MetadataRetryPolicy.java, core/imds/src/main/java/software/amazon/awssdk/imds/internal/DefaultEc2Metadata.java, core/imds/src/test/java/software/amazon/awssdk/imds/Ec2MetadataTest.java
Implemented Retries functionality and wrote test cases.
Implemented Retries functionality and wrote test cases.
Implemented Retries functionality and wrote test cases. Wrote new class for Retry Policy.
Wrote test cases and ran in IDE.
- [X ] I have read the [CONTRIBUTING](https://github.com/aws/aws-sdk-java-v2/blob/master/CONTRIBUTING.md) document
- [ X] Local run of `mvn install` succeeds
- [ X] My code follows the code style of this project
- [X ] My change requires a change to the Javadoc documentation
- [ X] I have updated the Javadoc documentation accordingly
- [ X] I have added tests to cover my changes
- [ X] All new and existing tests passed
- [X ] I confirm that this pull request can be released under the Apache 2 license
=>  Implemented Retries functionality

services/dynamodb/src/test/java/software/amazon/awssdk/services/dynamodb/WaitersUserAgentTest.java
```
[ERROR] Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 1.175 s <<< FAILURE! - in software.amazon.awssdk.services.dynamodb.WaitersUserAgentTest
[ERROR] software.amazon.awssdk.services.dynamodb.WaitersUserAgentTest.syncWaiters_shouldHaveWaitersUserAgent  Time elapsed: 1.15 s  <<< ERROR!
com.github.tomakehurst.wiremock.common.FatalStartupException: java.lang.RuntimeException: java.io.IOException: Failed to bind to /0.0.0.0:8080
Caused by: java.lang.RuntimeException: java.io.IOException: Failed to bind to /0.0.0.0:8080
Caused by: java.io.IOException: Failed to bind to /0.0.0.0:8080
Caused by: java.net.BindException: Address already in use
```
Attaching to dynamic port to prevent the above mentioned exception
=> mockServer in WaitersUserAgentTest attached to dynamicPort to prevent failed to bind 8080 exceptions
