aws/aws-sdk-java-v2

core/src/test/java/software/amazon/awssdk/http/RetryCountInUserAgentTest.java
services/api-gateway/src/it/java/software/amazon/awssdk/services/apigateway/ServiceIntegrationTest.java
services/ecs/src/it/java/software/amazon/awssdk/services/ecs/EC2ContainerServiceIntegrationTest.java
services/lambda/src/test/java/software/amazon/awssdk/services/lambda/invoke/LambdaInvokerFactoryTest.java
test/protocol-tests/src/test/java/software/amazon/awssdk/protocol/tests/crc32/AwsJsonCrc32ChecksumTests.java
test/protocol-tests/src/test/java/software/amazon/awssdk/protocol/tests/crc32/RestJsonCrc32ChecksumTests.java
test/protocol-tests/src/test/java/software/amazon/awssdk/protocol/tests/exception/RestJsonExceptionTests.java

These instances were added for debugging as far as I can tell.

Remove unneeded uses of BasicConfigurator

---

core/src/main/java/software/amazon/awssdk/http/pipeline/stages/ClientExecutionTimedStage.java
core/src/main/java/software/amazon/awssdk/util/SdkRuntime.java

Not actually sure if this is the correct fix but tests were failing without it...
cc: @shorea

Handle unrethrown interrupted exception

---

codegen/src/main/java/software/amazon/awssdk/codegen/poet/model/ListSetters.java
codegen/src/main/java/software/amazon/awssdk/codegen/poet/model/NonCollectionSetters.java
codegen/src/test/java/software/amazon/awssdk/codegen/poet/model/AwsModelSpecTest.java
codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/alltypesrequest.java
codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/alltypesresponse.java
codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/enumtype.java
codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/nestedcontainersrequest.java
codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/nestedcontainersresponse.java
codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/recursivestructtype.java
codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/service-2.json

so that we don't have setter overloads. Fixes #122

Removing var-args and enum methods for bean-style setters

---

codegen/src/main/java/software/amazon/awssdk/codegen/poet/model/ModelMethodOverrides.java
codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/alltypesrequest.java
codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/alltypesresponse.java
codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/basetype.java
codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/enumtype.java
codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/nestedcontainersrequest.java
codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/nestedcontainersresponse.java
codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/operationwithnoinputoroutputrequest.java
codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/operationwithnoinputoroutputresponse.java
codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/recursivestructtype.java
codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/simplestruct.java
codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/streaminginputoperationrequest.java
codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/streaminginputoperationresponse.java
codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/streamingoutputoperationrequest.java
codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/streamingoutputoperationresponse.java
codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/structwithnestedblobtype.java
codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/structwithtimestamp.java
codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/subtypeone.java

Old PR: https://github.com/aws/aws-sdk-java-v2/pull/134
I rebased from mainline and has to delete the old branch which closed the PR. Didn't see an option to reopen it.

Fix toString method

---

codegen/src/main/java/software/amazon/awssdk/codegen/docs/DocumentationBuilder.java
codegen/src/main/java/software/amazon/awssdk/codegen/docs/OperationDocProvider.java
core/src/main/java/software/amazon/awssdk/http/pipeline/stages/AfterTransmissionExecutionInterceptorsStage.java
core/src/main/java/software/amazon/awssdk/http/pipeline/stages/HttpResponseAdaptingStage.java
core/src/main/java/software/amazon/awssdk/http/pipeline/stages/MakeHttpRequestStage.java
utils/src/main/java/software/amazon/awssdk/utils/Pair.java
utils/src/test/java/software/amazon/awssdk/utils/PairTest.java

Implement hashCode, equals and toString
Added a factory method instead of the constructor

Making Pair a fully-fledged data class

---

codegen/src/main/java/software/amazon/awssdk/codegen/poet/model/AwsServiceModel.java
codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/alltypesrequest.java
codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/alltypesresponse.java
codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/basetype.java
codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/enumtype.java
codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/nestedcontainersrequest.java
codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/nestedcontainersresponse.java
codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/operationwithnoinputoroutputrequest.java
codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/operationwithnoinputoroutputresponse.java
codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/recursivestructtype.java
codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/simplestruct.java
codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/streaminginputoperationrequest.java
codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/streaminginputoperationresponse.java
codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/streamingoutputoperationrequest.java
codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/streamingoutputoperationresponse.java
codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/structwithnestedblobtype.java
codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/structwithtimestamp.java
codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/subtypeone.java
core/src/main/java/software/amazon/awssdk/SdkRequest.java
core/src/main/java/software/amazon/awssdk/SdkResponse.java
services/s3/src/main/java/software/amazon/awssdk/services/s3/handlers/EndpointAddressInterceptor.java
services/s3/src/test/java/software/amazon/awssdk/services/s3/handlers/S3Test.java

Basically code generating reflection instead of using reflection.

Potential solution for getting field values from request/response pojos

---

core/src/main/java/software/amazon/awssdk/core/http/pipeline/stages/HandleResponseStage.java

We already hide failures to close if the request failed, and if it succeeded, why not return the success and just log the connection-closing problem? (Sonar Fix)

Do not throw an exception if we couldn't close the connection to the service.

---

http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/DefaultEventLoopGroupFactory.java

Epoll is not currently supported in Lambda - customers trying to use Async in lambda are reporting that it blows up. This change falls back to NioEventLoopGroup/NioSocketChannel if we detect that we're running in a Lambda environment.

Adding hook so that we don't enable epoll by default on Lambda

---

CHANGELOG.md

Preview 5 change log

---

services/lambda/src/it/java/software/amazon/awssdk/services/lambda/IntegrationTestBase.java
services/lambda/src/test/resources/log4j.properties

And also create break so that it doesn't loop forever.

Fix lambda test that hangs

---

services/cloudsearch/src/it/java/software/amazon/awssdk/services/cloudsearch/CloudSearchv2IntegrationTest.java
test/service-test-utils/src/main/java/software/amazon/awssdk/testutils/service/AwsTestBase.java

Couple of integration test fixes.
Ran the failing test to check hamcrest matcher worked.

fixing integration tests

---

.travis.yml

Master build only

---

http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/internal/ResponseHandler.java

Suspect this is what is causing the SQS integration test to fail.
`mvn clean install verify -pl :sqs -am -Pintegration-tests`

Setting response complete before attempting to close/release the channel

---

http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/DefaultEventLoopGroupFactory.java

Need to understand why this is causing a problem.

Temporarily disabling epoll so that we can get a build out.

---

services/sqs/src/it/java/software/amazon/awssdk/services/sqs/auth/policy/SqsPolicyIntegrationTest.java

Updates SqsPolicyIntegrationTest to use the sync client
Queue was not getting deleted
Test passes

Updating test to use sync client

---

http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/internal/ChannelAttributeKeys.java

Fix Sonar reported vulnerability.

Fix Sonar vulnerability

---

core/src/main/java/software/amazon/awssdk/core/http/HttpClientDependencies.java

Call doClose in HttpClientDependencies#close method

---

core/src/main/java/software/amazon/awssdk/core/client/builder/ClientHttpConfiguration.java
http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/EventLoopGroupConfiguration.java
utils/src/main/java/software/amazon/awssdk/utils/Either.java
utils/src/test/java/software/amazon/awssdk/utils/EitherTest.java

This removes some code duplication.

Adding helper to Either that allows construction from two possibly null values

---

core/src/main/java/software/amazon/awssdk/core/client/builder/ClientAsyncHttpConfiguration.java

Another place we can use `Either.fromNullable`

---

services/cloudwatch/src/main/resources/codegen-resources/customization.config
services/directconnect/src/main/resources/codegen-resources/customization.config
services/dms/src/main/resources/codegen-resources/customization.config
services/organizations/src/main/resources/codegen-resources/customization.config
services/servicecatalog/src/main/resources/codegen-resources/customization.config
services/ssm/src/main/resources/codegen-resources/customization.config

Fix integration test failures related to SimpleMethods
Tested the **integration-tests** profile by changing it to only run SimpleMethodsIntegrationTest class

Fix SimpleMethods integration tests

---

pom.xml
services/cloudformation/src/it/java/software/amazon/awssdk/services/cloudformation/StackIntegrationTests.java
services/cloudwatch/src/it/java/software/amazon/awssdk/services/cloudwatch/CloudWatchIntegrationTest.java
services/dynamodb/src/it/java/software/amazon/awssdk/services/dynamodb/DynamoServiceIntegrationTest.java
services/dynamodb/src/test/java/utils/resources/TestResourceUtils.java
services/iam/src/it/java/software/amazon/awssdk/services/iam/GroupIntegrationTest.java
services/iam/src/it/java/software/amazon/awssdk/services/iam/IntegrationTestBase.java
services/machinelearning/src/it/java/software/amazon/awssdk/services/machinelearning/AmazonMachineLearningIntegrationTest.java
services/s3/src/test/java/software/amazon/awssdk/services/s3/handlers/CreateBucketInterceptorTest.java
services/sts/src/it/java/software/amazon/awssdk/services/sts/AssumeRoleIntegrationTest.java
services/sts/src/it/java/software/amazon/awssdk/services/sts/IntegrationTestBase.java
services/waf/src/it/java/software/amazon/awssdk/services/waf/WafIntegrationTest.java
test/dynamodbmapper-v1/src/it/java/software/amazon/awssdk/services/dynamodb/datamodeling/BatchLoadIntegrationTest.java
test/dynamodbmapper-v1/src/it/java/software/amazon/awssdk/services/dynamodb/datamodeling/DynamoDbMapperExpressionsIntegrationTest.java
test/dynamodbmapper-v1/src/it/java/software/amazon/awssdk/services/dynamodb/datamodeling/JsonIntegrationTest.java
test/dynamodbmapper-v1/src/test/java/utils/resources/TestResourceUtils.java
test/dynamodbmapper-v1/src/test/java/utils/test/util/DynamoDBTestBase.java
test/test-utils/src/main/java/software/amazon/awssdk/testutils/Waiter.java

No longer run checkstyle, findbugs or unit tests when using the integration test profile.

Switched some integration test Thread.sleep implementations to use the new waiter.

---

services/cloudwatch/src/it/java/software/amazon/awssdk/services/cloudwatch/CloudWatchIntegrationTest.java

Couldn't understand what each test was doing - move it to functional stream style and used concise builders, fixed assertions - hoping this will fix the flakiness of the integration test run.

Refactored cloudwatch integration test so that it's clearer

---

services/appsync/src/main/resources/codegen-resources/customization.config

verified with service owner that this should work with no-args for whitelisted accounts

Verify simple method for AppSync

---

codegen/src/main/java/software/amazon/awssdk/codegen/emitters/tasks/SyncClientGeneratorTasks.java
codegen/src/main/java/software/amazon/awssdk/codegen/model/intermediate/IntermediateModel.java
codegen/src/main/java/software/amazon/awssdk/codegen/poet/client/ClientSimpleMethodsIntegrationTests.java

Suppress creation of simple methods tests when they're not required

---

core/src/main/java/software/amazon/awssdk/core/sync/RequestBody.java
core/src/test/java/software/amazon/awssdk/core/sync/RequestBodyTest.java

Fixes #180
Fixes #180
New unit test.

Use len of UTF8 str for RequestBody.of(String)

---

.changes/2.0.0-preview-1.json
.changes/2.0.0-preview-2.json
.changes/2.0.0-preview-4.json
.changes/2.0.0-preview-5.json
CHANGELOG.md

Backport the handwritten changes to the changelog system.
- __N/A__ Changelog changes.

Backport handwritten changelog to change entry sets

---

.changes/2.0.0-preview-4.json
CHANGELOG.md
scripts/changelog/writer.py
scripts/new-change

Probably not something that'll get used after GA but during developer preview it comes up a lot.

Adding support for removals in change-log

---

.changes/next-release/feature-AWSSDKforJava-f236f16.json
.changes/next-release/removal-AWSSDKforJava-61a1006.json
scripts/new-change

Fixed AWS SDK for Java v2 category to be consistent

---

pom.xml

Run with `mvn clean install -Pquick`
Skips 
- tests
- checkstyle
- findbugs
- dependency analysis

Adding profile for quick builds

---

.changes/next-release/bugfix-NettyNIOAsyncHTTPClient-0cfd089.json
http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/internal/NettyConfiguration.java
http-clients/netty-nio-client/src/test/java/software/amazon/awssdk/http/nio/netty/internal/NettyConfigurationTest.java

Fixes logic in computing connection acquisition time.
Fixes Issue #340 
New unit tests.
- [x ] Bug fix (non-breaking change which fixes an issue)
- [ x] I have read the **CONTRIBUTING** document
- [x ] Local run of `mvn install` succeeds
- [ x] My code follows the code style of this project
- [ x] I have added tests to cover my changes
- [ x] All new and existing tests passed
- [ x] I confirm that this pull request can be released under the Apache 2 license

Fixing Issue #340

---

scripts/new-change

Small change to fix the repo name in the `new-change` script.
Small change to fix the repo name in the `new-change` script.
Create a test entry and check the output.

Fix repo name

---

scripts/new-change

So that it doesn't match issues that are already linked (i.e. start with a '[').
Avoids duplicating already linked issues/prs.
Manually tested locally.

Making issue replacement regex a bit smarter

---

.changes/2.0.0-preview-7.json
CHANGELOG.md

Entries probably created before the linkify fix in #354

Fix changelog links

---

scripts/changelog/git.py

previous command gave a warning in older versions of git.

Fix so that deleted files are added also - 

---

core/src/main/java/software/amazon/awssdk/core/internal/http/response/JsonErrorResponseHandler.java
core/src/main/java/software/amazon/awssdk/core/protocol/json/JsonContent.java
http-clients/apache-client/src/main/java/software/amazon/awssdk/http/apache/ApacheHttpClientFactory.java

Found more info logs in non-testing classes.

Update logging level to DEBUG

---

core/src/main/java/software/amazon/awssdk/core/http/StaxResponseHandler.java
core/src/main/java/software/amazon/awssdk/core/util/XpathUtils.java
services/simpledb/src/test/java/software/amazon/awssdk/services/simpledb/transform/DomainMetadataResultUnmarshallerTest.java
services/simpledb/src/test/java/software/amazon/awssdk/services/simpledb/transform/GetAttributesResultUnmarshallerTest.java
services/simpledb/src/test/java/software/amazon/awssdk/services/simpledb/transform/ListDomainsResultUnmarshallerTest.java
services/simpledb/src/test/java/software/amazon/awssdk/services/simpledb/transform/SelectResultUnmarshallerTest.java
test/protocol-tests-core/src/main/java/software/amazon/awssdk/protocol/asserts/marshalling/XmlAsserts.java
utils/src/main/java/software/amazon/awssdk/utils/XmlUtils.java

- set secure processing property to xml factory and parser
- port xml utils changes from v1.

Set secure processing property to XML factory 

---

core/src/test/java/software/amazon/awssdk/core/regions/providers/AwsProfileRegionProviderTest.java

This was causing test failures on my machine because whilst the config file did not exist in a valid location, credential did - and it contained a "default" profile.

Fix profile test so that it doesn't pick up the credentials file

---

core/src/main/java/software/amazon/awssdk/core/http/StreamManagingStage.java
core/src/test/java/software/amazon/awssdk/core/auth/EC2MetadataServiceMock.java
core/src/test/java/software/amazon/awssdk/core/auth/HttpCredentialsProviderTest.java
core/src/test/java/software/amazon/awssdk/core/http/SdkHttpFullResponseAdapterTest.java
core/src/test/java/software/amazon/awssdk/core/http/server/MockServer.java
core/src/test/java/software/amazon/awssdk/core/internal/io/ResettableInputStreamTest.java
core/src/test/java/software/amazon/awssdk/core/util/ClassesTest.java
core/src/test/java/software/amazon/awssdk/core/util/EC2MetadataUtilsServer.java
core/src/test/java/utils/http/SocketUtils.java
http-clients/apache-client/src/test/java/software/amazon/awssdk/http/apache/internal/conn/SdkTlsSocketFactoryTest.java
services/s3/src/test/java/software/amazon/awssdk/services/s3/handlers/PutObjectHeaderTest.java
test/protocol-tests-core/src/main/java/software/amazon/awssdk/protocol/asserts/marshalling/XmlAsserts.java

- Make sure all resources are released (**ALL** changes are in **Unit Tests**)
- Fix null dereference by updating
```
private Optional<InputStream> nonCloseableInputStream(Optional<InputStream> toBeClosed) {
return toBeClosed.map(is -> ReleasableInputStream.wrap(is).disableClose());
} 
```
to return optional 

Release all resources used in tests

---

pom.xml
services/pom.xml

Moving to more active repo for spotbugs
https://mvnrepository.com/artifact/com.github.spotbugs/spotbugs/3.1.1

Update SpotBugs plugin to a active repo

---

CHANGELOG.md

Fix changelog for version 2.0.0-preview-9

---

codegen/src/main/java/software/amazon/awssdk/codegen/poet/model/ModelBuilderSpecs.java
codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/alltypesrequest.java
codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/nestedcontainersrequest.java
codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/operationwithnoinputoroutputrequest.java
codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/streaminginputoperationrequest.java
codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/streamingoutputoperationrequest.java

Add override method for config consumer method
Add override method for config consumer method
Return the correct type.
Spec test files updated.

Add override method for config consumer method

---

.changes/next-release/feature-AWSSecretsManager-8640096.json
services/pom.xml
services/secretsmanager/pom.xml
services/secretsmanager/src/main/resources/codegen-resources/codegen.config
services/secretsmanager/src/main/resources/codegen-resources/customization.config
services/secretsmanager/src/main/resources/codegen-resources/examples-1.json
services/secretsmanager/src/main/resources/codegen-resources/service-2.json

Add AWS Secrets Manager

---

codegen/pom.xml

upgrade Javapoet to latest version (1.11.1)
- [ x] I have read the **CONTRIBUTING** document
- [ x] Local run of `mvn install` succeeds
- [ x] I have read the **README** document
- [ x] I have added tests to cover my changes
- [ x] All new and existing tests passed
- [ x] I confirm that this pull request can be released under the Apache 2 license

Javapoet 1.11.1

---

CHANGELOG.md

2.0.0-preview-10 was added in the end, moved it to the front..

Fix Changlog

---

core/src/main/java/software/amazon/awssdk/core/sync/RequestBody.java

I only found RequestBody class that takes in input stream via public APIs

Dont close input stream passed to public APIs

---

auth/src/main/java/software/amazon/awssdk/auth/AwsExecutionAttributes.java
auth/src/main/java/software/amazon/awssdk/auth/signer/AbstractAws4Signer.java
auth/src/main/java/software/amazon/awssdk/auth/signer/params/Aws4PresignerParams.java
auth/src/test/java/software/amazon/awssdk/auth/signer/SignerTestUtils.java

Use Instant instead of Date in Presigner params

---

build-tools/pom.xml
pom.xml

This upgrade resolves a potential security vulnerability
https://maven.apache.org/security-plexus-archiver.html

maven-dependency-plugin 3.1.1

---

pom.xml

This upgrade resolves a security vulnerability
https://maven.apache.org/security-plexus-archiver.html

maven-javadoc-plugin 3.0.1

---

auth/src/main/java/software/amazon/awssdk/auth/signer/AbstractAws4Signer.java
auth/src/main/java/software/amazon/awssdk/auth/signer/internal/Aws4SignerRequestParams.java
auth/src/main/java/software/amazon/awssdk/auth/signer/params/Aws4PresignerParams.java
auth/src/main/java/software/amazon/awssdk/auth/signer/params/Aws4SignerParams.java
aws-core/src/main/java/software/amazon/awssdk/awscore/endpoint/DefaultServiceEndpointBuilder.java
aws-core/src/main/java/software/amazon/awssdk/awscore/internal/EndpointUtils.java
core/src/main/java/software/amazon/awssdk/core/RequestExecutionContext.java
core/src/main/java/software/amazon/awssdk/core/RequestOverrideConfiguration.java
core/src/main/java/software/amazon/awssdk/core/ResponseBytes.java
core/src/main/java/software/amazon/awssdk/core/ResponseInputStream.java
core/src/main/java/software/amazon/awssdk/core/client/builder/SdkDefaultClientBuilder.java
core/src/main/java/software/amazon/awssdk/core/client/config/ClientOverrideConfiguration.java
core/src/main/java/software/amazon/awssdk/core/protocol/json/SdkJsonErrorUnmarshaller.java
core/src/main/java/software/amazon/awssdk/core/protocol/json/SdkJsonProtocolFactory.java
core/src/main/java/software/amazon/awssdk/core/retry/RetryHandler.java
core/src/test/java/software/amazon/awssdk/core/http/AmazonHttpClientTest.java
core/src/test/java/software/amazon/awssdk/core/protocol/json/SdkJsonErrorUnmarshallerTest.java
http-client-spi/src/main/java/software/amazon/awssdk/http/DefaultSdkHttpFullResponse.java
services/sqs/src/main/java/software/amazon/awssdk/services/sqs/MessageMD5ChecksumInterceptor.java

- Remove usage of Optional in fields
-  Return optional for getters with optional values.
- Add validation for non-optional fields in the constructors.

standardize optional usage

---

core/src/main/java/software/amazon/awssdk/core/internal/http/pipeline/stages/MoveParametersToBodyStage.java
services/simpledb/src/main/resources/codegen-resources/customization.config

Fix simpledb test

---

codegen/src/main/java/software/amazon/awssdk/codegen/emitters/tasks/SyncClientGeneratorTasks.java
codegen/src/main/java/software/amazon/awssdk/codegen/model/config/customization/CustomizationConfig.java

To disable sync client generation for kinesis
For kinesis, will create a new branch and trying to keep it in sync with master

Customization config to disable sync client generation

---

core/regions/src/main/java/software/amazon/awssdk/regions/Region.java
core/regions/src/main/resources/software/amazon/awssdk/regions/internal/region/endpoints.json

- add new region `EU_WEST_3`
- update `endpoints.json`

Add new region and update endpoints.json

---

codegen/src/main/java/software/amazon/awssdk/codegen/poet/model/AwsServiceModel.java
codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/alltypesrequest.java
codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/alltypesresponse.java
codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/basetype.java
codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/nestedcontainersrequest.java
codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/nestedcontainersresponse.java
codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/nonautoconstructcontainers/alltypesrequest.java
codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/nonautoconstructcontainers/alltypesresponse.java
codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/nonautoconstructcontainers/nestedcontainersrequest.java
codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/nonautoconstructcontainers/nestedcontainersresponse.java
codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/nonautoconstructcontainers/recursivestructtype.java
codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/recursivestructtype.java
codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/simplestruct.java
codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/structwithnestedblobtype.java
codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/structwithtimestamp.java
codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/subtypeone.java
test/codegen-generated-classes-test/src/test/java/software/amazon/awssdk/services/codegenerationjsonrpccustomized/model/GetValueForFieldTest.java

Optional.of() will throw NullPointerException if the argument is null.
Optional.of() will throw NullPointerException if the argument is null.
New unit tests.

Use ofNullable in getValueForField

---

core/aws-core/src/main/java/software/amazon/awssdk/awscore/client/builder/AwsDefaultClientBuilder.java
core/aws-core/src/main/java/software/amazon/awssdk/awscore/retry/AwsRetryPolicy.java
core/aws-core/src/main/java/software/amazon/awssdk/awscore/retry/conditions/RetryOnErrorCodeCondition.java
core/aws-core/src/test/java/software/amazon/awssdk/awscore/client/utils/HttpTestUtils.java
core/aws-core/src/test/java/software/amazon/awssdk/awscore/retry/AwsRetryPolicyTest.java
core/aws-core/src/test/java/software/amazon/awssdk/awscore/retry/RetryOnErrorCodeConditionTest.java
core/sdk-core/src/it/java/software/amazon/awssdk/core/http/AmazonHttpClientSslHandshakeTimeoutIntegrationTest.java
core/sdk-core/src/it/java/software/amazon/awssdk/core/http/ConnectionPoolMaxConnectionsIntegrationTest.java
core/sdk-core/src/main/java/software/amazon/awssdk/core/client/builder/SdkDefaultClientBuilder.java
core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/retry/RetryHandler.java
core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/retry/SdkDefaultRetrySetting.java
core/sdk-core/src/main/java/software/amazon/awssdk/core/retry/RetryPolicy.java
core/sdk-core/src/main/java/software/amazon/awssdk/core/retry/RetryPolicyContext.java
core/sdk-core/src/main/java/software/amazon/awssdk/core/retry/backoff/BackoffStrategy.java
core/sdk-core/src/main/java/software/amazon/awssdk/core/retry/backoff/EqualJitterBackoffStrategy.java
core/sdk-core/src/main/java/software/amazon/awssdk/core/retry/backoff/FullJitterBackoffStrategy.java
core/sdk-core/src/main/java/software/amazon/awssdk/core/retry/conditions/RetryCondition.java
core/sdk-core/src/main/java/software/amazon/awssdk/core/retry/conditions/RetryOnExceptionsCondition.java
core/sdk-core/src/main/java/software/amazon/awssdk/core/retry/conditions/RetryOnStatusCodeCondition.java
core/sdk-core/src/test/java/software/amazon/awssdk/core/client/AsyncClientHandlerExceptionTest.java
core/sdk-core/src/test/java/software/amazon/awssdk/core/client/AsyncClientHandlerInterceptorExceptionTest.java
core/sdk-core/src/test/java/software/amazon/awssdk/core/client/handler/AsyncClientHandlerTest.java
core/sdk-core/src/test/java/software/amazon/awssdk/core/client/handler/SyncClientHandlerTest.java
core/sdk-core/src/test/java/software/amazon/awssdk/core/internal/http/timers/client/MockedClientTests.java
core/sdk-core/src/test/java/software/amazon/awssdk/core/retry/DefaultRetryConditionTest.java
core/sdk-core/src/test/java/software/amazon/awssdk/core/retry/RetryOnStatusCodeConditionTest.java
core/sdk-core/src/test/java/software/amazon/awssdk/core/retry/RetryPolicyTest.java
core/sdk-core/src/test/java/utils/HttpTestUtils.java
services/dynamodb/src/main/java/software/amazon/awssdk/services/dynamodb/DynamoDbRetryPolicy.java

Minor refactoring to retry policy code. 
All existing tests updated and pass.

Refactoring retry policy code

---

pom.xml

Updates Jackson to version 2.9.6.

Updating Jackson version

---

codegen/src/main/java/software/amazon/awssdk/codegen/poet/paginators/PaginatorsClassSpec.java
codegen/src/test/resources/software/amazon/awssdk/codegen/poet/paginators/PaginatedOperationWithResultKeyIterable.java
codegen/src/test/resources/software/amazon/awssdk/codegen/poet/paginators/PaginatedOperationWithResultKeyPublisher.java
codegen/src/test/resources/software/amazon/awssdk/codegen/poet/paginators/PaginatedOperationWithoutResultKeyIterable.java
codegen/src/test/resources/software/amazon/awssdk/codegen/poet/paginators/PaginatedOperationWithoutResultKeyPublisher.java
services/dynamodb/src/it/java/software/amazon/awssdk/services/dynamodb/DynamoServiceIntegrationTest.java
services/dynamodb/src/it/java/software/amazon/awssdk/services/dynamodb/SecondaryIndexesIntegrationTest.java
services/dynamodb/src/main/resources/codegen-resources/dynamodb/customization.config
services/dynamodb/src/main/resources/codegen-resources/dynamodbstreams/customization.config
test/dynamodbdocument-v1/src/it/java/software/amazon/awssdk/services/dynamodb/NestedJsonDocumentIntegrationTest.java
test/dynamodbdocument-v1/src/test/java/software/amazon/awssdk/services/dynamodb/document/ExpectedTest.java
test/dynamodbdocument-v1/src/test/java/software/amazon/awssdk/services/dynamodb/document/FilterConditionTest.java
test/dynamodbdocument-v1/src/test/java/software/amazon/awssdk/services/dynamodb/document/internal/InternalUtilsTest.java
test/dynamodbmapper-v1/src/it/java/software/amazon/awssdk/services/dynamodb/datamodeling/JsonIntegrationTest.java
test/dynamodbmapper-v1/src/it/java/software/amazon/awssdk/services/dynamodb/mapper/BinaryAttributesIntegrationTest.java
test/dynamodbmapper-v1/src/it/java/software/amazon/awssdk/services/dynamodb/mapper/GenerateCreateTableRequestIntegrationTest.java
test/dynamodbmapper-v1/src/test/java/software/amazon/awssdk/services/dynamodb/datamodeling/DynamoDbMapper.java
test/dynamodbmapper-v1/src/test/java/software/amazon/awssdk/services/dynamodb/datamodeling/PaginatedQueryList.java
test/dynamodbmapper-v1/src/test/java/software/amazon/awssdk/services/dynamodb/datamodeling/PaginatedScanList.java
test/dynamodbmapper-v1/src/test/java/software/amazon/awssdk/services/dynamodb/datamodeling/StandardModelFactoriesV2UnconvertTest.java
test/dynamodbmapper-v1/src/test/java/software/amazon/awssdk/services/dynamodb/mapper/GenerateCreateTableRequestTest.java

- Check for auto construct containers on paginator termination
condition
- Enable autoconstruct list for DDB
- Fix broken tests
Add auto construct container fixes
Integration test fixes.
unit and integration tests (minus the mapper for integration tests).

Add auto construct container fixes

---

test/codegen-generated-classes-test/pom.xml
test/dynamodbdocument-v1/pom.xml
test/dynamodbmapper-v1/pom.xml
test/http-client-tests/pom.xml
test/protocol-tests-core/pom.xml
test/protocol-tests/pom.xml
test/service-test-utils/pom.xml
test/test-utils/pom.xml

skip maven releases for test modules

skip maven releases for test modules

---

bundle/pom.xml
test/codegen-generated-classes-test/pom.xml
test/dynamodbdocument-v1/pom.xml
test/dynamodbmapper-v1/pom.xml
test/http-client-tests/pom.xml
test/protocol-tests-core/pom.xml
test/protocol-tests/pom.xml
test/service-test-utils/pom.xml
test/test-utils/pom.xml

Revert changes in dcbda80 and try to fix javadoc in bundle module

Revert changes in dcbda80 and try to fix javadoc 

---

.changes/next-release/feature-AWSSDKforJavav2-dfce555.json
core/profiles/src/main/java/software/amazon/awssdk/profiles/ProfileProperty.java

Add `mfa_serial` as defined here: https://docs.aws.amazon.com/cli/latest/topic/config-vars.html#using-aws-iam-roles
Adds standardized key to list of profile properties
`mvn install`

Add the mfa_serial profile property

---

README.md

Update javadoc site

---

.changes/2.0.0-preview-11.json
CHANGELOG.md

Add changelog entry for autoconstruct containers

Add changelog entry for autoconstruct containers

---

.changes/next-release/bugfix-runtime-d31e357.json
pom.xml

Netty 4.1.26.Final -> 4.1.28.Final
Netty 4.1.26.Final -> 4.1.28.Final
Unit test suite.

Netty 4.1.26.Final -> 4.1.28.Final

---

core/aws-core/src/main/java/software/amazon/awssdk/awscore/http/response/DefaultErrorResponseHandler.java

remove obsolete TODO as we discussed

remove obsolete TODO

---

services/kinesis/src/it/java/software/amazon/awssdk/services/kinesis/SubscribeToShardIntegrationTest.java

fix integration tests: create new stream per test so that we don't get `software.amazon.awssdk.services.kinesis.model.ResourceInUseException`

fix integration tests: create new stream per test

---

README.md

add codebuild badge

---

core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/http/loader/DefaultSdkHttpClientBuilder.java

fix whitepsace in DefaultSdkHttpClientBuilder.java

---

services/batch/src/main/resources/codegen-resources/customization.config

`listJobs` contains required members.

Blacklist listJobs in batch service

---

services/batch/src/main/resources/codegen-resources/customization.config

Fix typo in `customization.config` for Batch.
Correctly suppress bad simple method.
Integration tests on `batch` module.

Fix blacklist typo

---

services/waf/src/main/resources/codegen-resources/waf-regional/customization.config
services/waf/src/main/resources/codegen-resources/waf/customization.config

These worked on my desktop but are failing in CodeBuild for some reason. Disabling for now.
Fix Integration tests.

Blacklist simple methods in WAF(-Regional)

---

.changes/next-release/feature-AWSSDKforJavav2-8138f04.json

Changelog for service model update.

Add service update changelog

---

services/mediastoredata/src/main/resources/codegen-resources/customization.config

Blacklist listItems

---

buildspecs/update-snapshot-version.yml

Add execution permission to the scripts in update-snapshot-version.

Add execution permission to the scripts in update-snapshot-version

---

codegen/src/main/java/software/amazon/awssdk/codegen/docs/SyncOperationDocProvider.java
codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/test-json-client-class.java
codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/test-json-client-interface.java

Fix Javadoc issue #706

---

core/profiles/src/main/java/software/amazon/awssdk/profiles/ProfileFileLocation.java

Want to use the SDK's logic for resolving credential/configuration paths - even if they don't exist yet.
Want to create a getting started experience for the AWS Toolkit for Jetbrains (https://github.com/aws/aws-toolkit-jetbrains)

Exposing utility methods to get credential/config file paths

---

.changes/next-release/bugfix-core-33ab264.json
pom.xml

Netty 4.1.28 -> 4.1.30
latest version of Netty

Netty 4.1.28 -> 4.1.30

---

.changes/next-release/feature-core-8700261.json
pom.xml

Apache HttpClient 4.5.5 -> 4.5.6
latest version of library

Apache HttpClient 4.5.5 -> 4.5.6

---

.changes/next-release/bugfix-AWSSDKforJavav2-fe9f4e3.json
pom.xml

maven-bundle-plugin 4.0.0
latest plugin version

maven-bundle-plugin 4.0.0

---

core/aws-core/src/main/java/software/amazon/awssdk/awscore/eventstream/EventStreamAsyncResponseTransformer.java

Dummy PR to trigger a internal pull
This is already fixed in master branch

Remove comment

---

core/aws-core/src/main/java/software/amazon/awssdk/awscore/eventstream/EventStreamAsyncResponseTransformer.java

Reverting the last commit
(Had issue with pulling the source internally. Fixed it and retrying based on this merge)

Revert "Remove comment"

---

core/sdk-core/src/main/resources/software/amazon/awssdk/core/util/VersionInfo.java.vm

Update Generated annotation import. Missed this file when I first did the generated annotation update.

Update Generated Annotation import

---

core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/http/async/SimpleHttpContentPublisher.java
http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/internal/ResponseHandler.java
protocols/aws-cbor-protocol/pom.xml
protocols/aws-ion-protocol/pom.xml
protocols/aws-json-protocol/pom.xml
protocols/aws-query-protocol/pom.xml
protocols/protocol-core/pom.xml

- Fix `Publisher.subscribe` running check 
- add the metadata information such as name, description to the protocol poms

Fix Publisher.subscribe running check and add module name to poms

---

core/auth/pom.xml
core/auth/src/main/java/software/amazon/awssdk/auth/signer/EventStreamAws4Signer.java
core/auth/src/main/java/software/amazon/awssdk/auth/signer/internal/AbstractAws4Signer.java
core/auth/src/main/java/software/amazon/awssdk/auth/signer/internal/AsyncSigV4SubscriberAdapter.java
core/auth/src/main/java/software/amazon/awssdk/auth/signer/internal/BaseAsyncAws4Signer.java
core/auth/src/main/java/software/amazon/awssdk/auth/signer/internal/BaseEventStreamAsyncAws4Signer.java
core/auth/src/test/java/software/amazon/awssdk/auth/signer/Aws4EventStreamSignerTest.java
core/auth/src/test/java/software/amazon/awssdk/auth/signer/Aws4SignerTest.java
core/auth/src/test/java/software/amazon/awssdk/auth/signer/internal/SignerTestUtils.java
core/aws-core/pom.xml
core/sdk-core/src/main/java/software/amazon/awssdk/core/client/handler/BaseAsyncClientHandler.java
core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/http/AmazonAsyncHttpClient.java
core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/http/RequestExecutionContext.java
core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/http/pipeline/stages/MakeAsyncHttpRequestStage.java
core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/http/pipeline/stages/SigningStage.java
core/sdk-core/src/main/java/software/amazon/awssdk/core/signer/AsyncRequestBodySigner.java
flow/pom.xml
http-client-spi/src/main/java/software/amazon/awssdk/http/async/SdkHttpContentPublisher.java
http-clients/netty-nio-client/src/test/java/software/amazon/awssdk/http/nio/netty/NettyNioAsyncHttpClientSpiVerificationTest.java
pom.xml
services/kinesis/pom.xml

event streaming SigV4 signing

---

.changes/next-release/bugfix-AmazonS3-13e2ee3.json
services/s3/src/main/java/software/amazon/awssdk/services/s3/handlers/EndpointAddressInterceptor.java
services/s3/src/test/java/software/amazon/awssdk/services/s3/handlers/EndpointAddressInterceptorTest.java
services/s3/src/test/java/software/amazon/awssdk/services/s3/utils/S3EndpointResolutionTest.java

- Update EndpointAddressInterceptor to honor request protocol 
- add tests for` EndpointAddressInterceptor`
`mvn clean install` succeeded and s3 integration tests passed

Update EndpointAddressInterceptor to honor request protocol 

---

core/protocols/aws-json-protocol/src/main/java/software/amazon/awssdk/protocols/json/internal/unmarshall/JsonProtocolUnmarshaller.java
test/protocol-tests-core/src/main/java/software/amazon/awssdk/protocol/reflect/ShapeModelReflector.java
test/protocol-tests-core/src/main/resources/software/amazon/awssdk/protocol/suites/cases/json-core-input.json
test/protocol-tests-core/src/main/resources/software/amazon/awssdk/protocol/suites/cases/json-core-output.json
test/protocol-tests/src/main/resources/codegen-resources/awsjson/customization.config
test/protocol-tests/src/main/resources/codegen-resources/awsjson/service-2.json
test/protocol-tests/src/main/resources/codegen-resources/restjson/service-2.json

Tested with making a DescribeBudget call

Add bigdecimal unmarshaller for json protocol

---

http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/NettyNioAsyncHttpClient.java

Fix typo in writeTimeout.

---

codegen/src/main/java/software/amazon/awssdk/codegen/AddExceptionShapes.java
codegen/src/main/java/software/amazon/awssdk/codegen/model/intermediate/ShapeModel.java
codegen/src/main/java/software/amazon/awssdk/codegen/poet/client/specs/JsonProtocolSpec.java
codegen/src/main/java/software/amazon/awssdk/codegen/poet/client/specs/ProtocolSpec.java
codegen/src/main/java/software/amazon/awssdk/codegen/poet/client/specs/QueryProtocolSpec.java
codegen/src/main/java/software/amazon/awssdk/codegen/poet/transform/protocols/EventStreamJsonMarshallerSpec.java
codegen/src/test/java/software/amazon/awssdk/codegen/poet/transform/MarshallerSpecTest.java
codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/test-async-client-class.java
codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/test-json-client-class.java
codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/test-query-client-class.java
codegen/src/test/resources/software/amazon/awssdk/codegen/poet/transform/eventonemarshaller.java
codegen/src/test/resources/software/amazon/awssdk/codegen/poet/transform/eventtwomarshaller.java
codegen/src/test/resources/software/amazon/awssdk/codegen/poet/transform/inputeventmarshaller.java
codegen/src/test/resources/software/amazon/awssdk/codegen/poet/transform/inputeventtwomarshaller.java
core/aws-core/src/main/java/software/amazon/awssdk/awscore/eventstream/EventStreamAsyncResponseTransformer.java
core/protocols/aws-ion-protocol/pom.xml
core/protocols/aws-ion-protocol/src/test/java/software/amazon/awssdk/protocols/ion/AwsStructuredIonFactoryTest.java
core/protocols/aws-json-protocol/src/main/java/software/amazon/awssdk/protocols/json/BaseAwsJsonProtocolFactory.java
core/protocols/aws-json-protocol/src/main/java/software/amazon/awssdk/protocols/json/internal/unmarshall/AwsJsonProtocolErrorUnmarshaller.java
core/protocols/aws-json-protocol/src/main/java/software/amazon/awssdk/protocols/json/internal/unmarshall/JsonErrorCodeParser.java
core/protocols/aws-json-protocol/src/test/java/software/amazon/awssdk/protocols/json/JsonErrorCodeParserTest.java
core/protocols/aws-query-protocol/src/main/java/software/amazon/awssdk/protocols/query/AwsQueryProtocolFactory.java
core/protocols/aws-query-protocol/src/main/java/software/amazon/awssdk/protocols/query/unmarshall/AwsXmlErrorProtocolUnmarshaller.java
core/protocols/aws-xml-protocol/src/main/java/software/amazon/awssdk/protocols/xml/AwsXmlProtocolFactory.java
core/protocols/protocol-core/src/main/java/software/amazon/awssdk/protocols/core/ErrorMetadata.java
core/protocols/protocol-core/src/main/java/software/amazon/awssdk/protocols/core/ExceptionMetadata.java
http-client-spi/src/main/java/software/amazon/awssdk/http/DefaultSdkHttpFullResponse.java
test/sdk-benchmarks/pom.xml
test/sdk-benchmarks/src/main/java/software/amazon/awssdk/benchmark/dynamodb/V2DynamoDbAttributeValue.java

* Use http status code in c2j for modeled exceptions. If not, use 500
* Fix marshaller generation for h2 events

Use status code from c2j model for modeled exceptions instead of 500

---

codegen/src/main/java/software/amazon/awssdk/codegen/customization/processors/OperationModifiersProcessor.java
codegen/src/main/java/software/amazon/awssdk/codegen/model/config/customization/OperationModifier.java
services/s3/src/main/resources/codegen-resources/customization.config
services/s3/src/main/resources/codegen-resources/service-2.json

* Skip shape generation when excludeShape is set. If operation is excluded but input shape is not excluded from model, we get exception when trying the find the requestUri for the input shape
* Skip event stream API generation for S3

Skip event stream API generation for S3

---

.changes/next-release/feature-core-9feb71e.json
pom.xml

upgrade to Netty 4.1.31.Final
latest version
Unit tests.

Netty 4.1.31.Final

---

pom.xml

Remove flow from parent module to exclude it from next release

Remove flow from parent module

---

services/appstream/src/main/resources/codegen-resources/customization.config
services/servicecatalog/src/main/resources/codegen-resources/customization.config
services/ssm/src/main/resources/codegen-resources/customization.config

Blacklist bad simple methods for new operations.

Blacklist bad new simple methods

---

codegen/src/main/java/software/amazon/awssdk/codegen/AddOperations.java
codegen/src/main/java/software/amazon/awssdk/codegen/IntermediateModelBuilder.java
codegen/src/main/java/software/amazon/awssdk/codegen/model/config/customization/CustomizationConfig.java
services/applicationdiscovery/src/main/resources/codegen-resources/customization.config
services/cloudtrail/src/main/resources/codegen-resources/customization.config
services/directconnect/src/main/resources/codegen-resources/customization.config
services/elastictranscoder/src/main/resources/codegen-resources/customization.config
services/emr/src/main/resources/codegen-resources/customization.config
services/iot/src/main/resources/codegen-resources/customization.config
services/lambda/src/main/resources/codegen-resources/customization.config
services/mediapackage/src/main/resources/codegen-resources/customization.config
services/rds/src/main/resources/codegen-resources/customization.config
services/route53/src/main/resources/codegen-resources/customization.config
services/s3/src/main/resources/codegen-resources/customization.config
services/shield/src/main/resources/codegen-resources/customization.config

Removes deprecated shapes and operations.

Removing deprecated shapes and operations

---

.changes/next-release/feature-core-141e598.json
pom.xml
test/sdk-benchmarks/pom.xml

Jackson 2.9.6 -> 2.9.7
latest version of Jackson
mvn clean install

Jackson 2.9.6 -> 2.9.7

---

.changes/next-release/feature-AWSSDKforJavav2-8de6f6c.json
aws-sdk-java/pom.xml
services/cloudwatchevents/src/main/resources/codegen-resources/service-2.json
services/elasticloadbalancingv2/src/main/resources/codegen-resources/service-2.json
services/kafka/pom.xml
services/kafka/src/main/resources/codegen-resources/paginators-1.json
services/kafka/src/main/resources/codegen-resources/service-2.json
services/lambda/src/main/resources/codegen-resources/service-2.json
services/pom.xml
services/s3/src/main/resources/codegen-resources/service-2.json
services/serverlessapplicationrepository/src/main/resources/codegen-resources/paginators-1.json
services/serverlessapplicationrepository/src/main/resources/codegen-resources/service-2.json
services/sfn/src/main/resources/codegen-resources/service-2.json
services/xray/src/main/resources/codegen-resources/service-2.json

Updated to the latest service models.
Running `mvn clean verify -P simple-method-integration-tests`

Updated to the latest service models.

---

http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/internal/NettyRequestExecutor.java

Following up on #889 
Reusing ReadTimeoutHandler for 100continueExpected request

Reusing ReadTimeoutHandler for 100continueExpected request

---

.changes/next-release/feature-core-d7ed82f.json
pom.xml

latest version of Netty (4.1.32.Final)
latest version of Netty (4.1.32.Final)
mvn clean install

netty 4.1.32.Final

---

services/cloudsearchdomain/src/main/java/software/amazon/awssdk/services/cloudsearchdomain/internal/SwitchToPostInterceptor.java
services/cloudsearchdomain/src/test/java/software/amazon/awssdk/cloudsearchdomain/SearchRequestUnitTest.java

See https://github.com/aws/aws-sdk-java-v2/issues/923

Fixing cloudsearchdomains marshalling

---

.changes/next-release/bugfix-AWSSDKforJavav2-508ab51.json
core/sdk-core/src/main/java/software/amazon/awssdk/core/interceptor/ClasspathInterceptorChainFactory.java
core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/http/loader/SdkServiceLoader.java
core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/util/ClassLoaderHelper.java
core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/util/Mimetype.java
services/sts/src/main/java/software/amazon/awssdk/services/sts/auth/StsAssumeRoleWithSamlCredentialsProvider.java

Use the class loader that loaded the SDK to load the HTTP implementations. See #56

Update SdkServiceLoader loading

---

.changes/next-release/feature-URLConnectionHTTPClient-777a68c.json
http-clients/url-connection-client/src/main/java/software/amazon/awssdk/http/urlconnection/UrlConnectionFactory.java
http-clients/url-connection-client/src/main/java/software/amazon/awssdk/http/urlconnection/UrlConnectionHttpClient.java
http-clients/url-connection-client/src/test/java/software/amazon/awssdk/http/urlconnection/UrlConnectionHttpClientWithCustomCreateWireMockTest.java

Customers require the ability to control how a URL connection gets created - but still want to take advantage of other SDK features (such as setting timeout, building the request parameters etc). See https://github.com/aws/aws-toolkit-jetbrains/issues/685 for an example use case.
Ran unit tests

Adding the ability to control how a HttpURLConnection gets created.

---

services/s3/pom.xml
services/s3/src/it/java/software/amazon/awssdk/services/s3/UploadMultiplePartIntegrationTest.java

Add test for abortMultipartUpload
tested locally

Add test for abortMultipartUpload

---

.travis.yml
core/aws-core/pom.xml
core/sdk-core/pom.xml
pom.xml

integrate with codecov

---

.changes/next-release/feature-core-0acb726.json
pom.xml
test/sdk-benchmarks/pom.xml

Jackson 2.9.7 -> 2.9.8
latest version of Jackson
https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.9.8

Jackson 2.9.7 -> 2.9.8

---

core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/http/async/SyncResponseHandlerAdapter.java

Use same thread composition in SyncResponseHandlerAdaptor. See #994

---

pom.xml

maven-jar-plugin 3.1.1
latest version
mvn clean package

maven-jar-plugin 3.1.1

---

buildspecs/build.yml
test/test-utils/src/main/java/software/amazon/awssdk/testutils/EnvironmentVariableHelper.java

Fixing `EnvironmentVariableHelperTest` for windows.

Fix build for windows

---

services/s3/src/main/java/software/amazon/awssdk/services/s3/S3Configuration.java

Just fixing a typo in the JavaDoc

Fix incorrect JavaDoc see tag

---

.changes/next-release/bugfix-AWSSDKforJavav2-1ebeee5.json

Forgot the changelog in #1041.

Changelog for SslCloseCompletionEventHandler

---

core/aws-core/src/test/java/software/amazon/awssdk/awscore/eventstream/EventStreamAsyncResponseTransformerTest.java

- EventStreamResponseHandler#exceptionOccurred is not signaled if following a complete()
- EventStreamResponseHandler#exceptionOccurred is not signaled if following a previous exceptionOcurred()
- EventStreamResponseHandler#prepare() returns a new future instance
Add more testing.

Add tests for EventStreamAsyncResponseTransformer

---

http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/internal/LastHttpContentSwallower.java
http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/internal/ResponseHandler.java
http-clients/netty-nio-client/src/test/java/software/amazon/awssdk/http/nio/netty/internal/LastHttpContentSwallowerTest.java

Netty client cleanup.
Added tests.

Factor out LastHttpContentSwallower and add tests

---

http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/internal/ChannelPipelineInitializer.java
http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/internal/FutureCancelHandler.java
http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/internal/SslCloseCompletionEventHandler.java
http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/internal/UnusedChannelExceptionHandler.java
http-clients/netty-nio-client/src/test/java/software/amazon/awssdk/http/nio/netty/internal/FutureCancelHandlerTest.java
http-clients/netty-nio-client/src/test/java/software/amazon/awssdk/http/nio/netty/internal/SslCloseCompletionEventHandlerTest.java
http-clients/netty-nio-client/src/test/java/software/amazon/awssdk/http/nio/netty/internal/UnusedChannelExceptionHandlerTest.java

Make handlers that can be shared `@Sharable`.
Code cleanup, minor optimization.

Sharable handlers

---

build-tools/pom.xml
pom.xml

Fix maven warning logs by 
- Removing duplicate dependencies declaration
- Add missing version

Fix maven warning logs

---

release-scripts/src/main/java/software/amazon/awssdk/release/UpdateServiceMain.java

Don't change the given service module name, and just use the value given by the
caller. Use the new serviceId option to decide if models go in a subdirectory
under 'codegen-resources'.

Use module name as-is, service-id as sub dir

---

release-scripts/src/main/java/software/amazon/awssdk/release/UpdateServiceMain.java

Fix service id switch

---

.changes/next-release/bugfix-NettyNioHTTPClient-d52b8f6.json
http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/internal/NettyRequestExecutor.java
http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/internal/ResponseHandler.java
http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/internal/UnusedChannelExceptionHandler.java
http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/internal/utils/ExceptionHandlingUtils.java
http-clients/netty-nio-client/src/test/java/software/amazon/awssdk/http/nio/netty/internal/utils/ExceptionHandlingUtilsTest.java

- Added try catch in various places to prevent uncompleted future 
- Other small fixes
running existing tests.

Added try catch in various places to prevent uncompleted future

---

.codecov.yml

- Ignore test files for code coverage

Configuring Codecov

---

.changes/next-release/bugfix-AWSSDKforJavav2-4c7acf5.json
bom/pom.xml

Add missing non-service modules to bom
Fixes #1063

Add missing non-service modules to bom

---

.changes/next-release/bugfix-AWSSDKforJavav2-5718f4e.json
codegen-lite/src/main/java/software/amazon/awssdk/codegen/lite/regions/ServiceMetadataGenerator.java
codegen-lite/src/test/java/software/amazon/awssdk/codegen/lite/regions/RegionGenerationTest.java
codegen-lite/src/test/resources/software/amazon/awssdk/codegen/lite/regions/sts-service-metadata.java

Fix generated service metadata for services that have overridden endpoints.
Currently, it shows 
```
[ERROR] private static final Map<String, String> PARTITION_OVERRIDDEN_ENDPOINTS = ImmutableMap.<String, String> builder()
[ERROR] .put("software.amazon.awssdk.codegen.lite.regions.model.Partition@cc5c483", "sts.amazonaws.com").build();
[ERROR]
```
added test

Fix generated service metadata 

---

.changes/next-release/feature-AmazonS3-f2cd9dd.json
codegen/src/main/java/software/amazon/awssdk/codegen/model/config/customization/CustomizationConfig.java
codegen/src/main/java/software/amazon/awssdk/codegen/model/config/customization/UtilitiesMethod.java
codegen/src/main/java/software/amazon/awssdk/codegen/poet/client/AsyncClientClass.java
codegen/src/main/java/software/amazon/awssdk/codegen/poet/client/AsyncClientInterface.java
codegen/src/main/java/software/amazon/awssdk/codegen/poet/client/SyncClientClass.java
codegen/src/main/java/software/amazon/awssdk/codegen/poet/client/SyncClientInterface.java
codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/c2j/json/customization.config
codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/test-async-client-class.java
codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/test-json-async-client-interface.java
codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/test-json-client-class.java
codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/test-json-client-interface.java
core/sdk-core/src/main/java/software/amazon/awssdk/core/exception/SdkException.java
services/s3/src/main/java/software/amazon/awssdk/services/s3/S3Utilities.java
services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/S3EndpointUtils.java
services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/handlers/EndpointAddressInterceptor.java
services/s3/src/main/java/software/amazon/awssdk/services/s3/model/GetUrlRequest.java
services/s3/src/main/resources/codegen-resources/customization.config
services/s3/src/test/java/software/amazon/awssdk/services/s3/S3UtilitiesTest.java

* Add `S3Utilities` class with `getUrl` method
* Add `utilites()` method in low-level client that returns an instance of `S3Utilities` with the configuration set on the client
* Added unit tests for `getUrl` method

Add getUrl method

---

.changes/next-release/bugfix-AWSSDKforJavav2-7165ae9.json
.changes/next-release/bugfix-AmazonS3-5374636.json
core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/http/StreamManagingStage.java
core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/sync/FileContentStreamProvider.java
core/sdk-core/src/main/java/software/amazon/awssdk/core/sync/RequestBody.java
core/sdk-core/src/test/java/software/amazon/awssdk/core/http/ContentStreamProviderWireMockTest.java
core/sdk-core/src/test/java/software/amazon/awssdk/core/internal/sync/FileContentStreamProviderTest.java
http-client-spi/src/main/java/software/amazon/awssdk/http/ContentStreamProvider.java
services/s3/src/it/java/software/amazon/awssdk/services/s3/PutObjectIntegrationTest.java
services/s3/src/main/java/software/amazon/awssdk/services/s3/checksums/ChecksumCalculatingInputStream.java
services/s3/src/test/java/software/amazon/awssdk/services/s3/checksums/ChecksumCalculatingInputStreamTest.java

Fixes #1138
Fixes #1138
New unit tests. Running integ tests.

Close stream in StreamManagingStage

---

services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/S3EndpointUtils.java

Fixing SonarQube reported issue

Use restricted variable access for constant in S3EndpointUtils class

---

README.md
docs/BestPractices.md

Add best practices doc.
~~It might be controversial to add `Prefer high level libraries` section because there is no HLL in v2 yet. ┑(￣Д ￣)┍~~ (Removed)

Add best practices doc

---

.changes/next-release/feature-AWSSDKforJavav2-a2a6331.json
core/auth/src/main/java/software/amazon/awssdk/auth/credentials/ProcessCredentialsProvider.java
core/auth/src/main/java/software/amazon/awssdk/auth/credentials/internal/ProfileCredentialsUtils.java
core/auth/src/test/java/software/amazon/awssdk/auth/credentials/ProcessCredentialsProviderTest.java
core/auth/src/test/java/software/amazon/awssdk/auth/credentials/internal/ProfileCredentialsUtilsTest.java
core/auth/src/test/resources/resources/process/linux-credentials-script.sh
core/auth/src/test/resources/resources/process/windows-credentials-script.bat
core/profiles/src/main/java/software/amazon/awssdk/profiles/ProfileProperty.java
core/sdk-core/src/main/java/software/amazon/awssdk/core/util/json/JacksonUtils.java
utils/src/main/java/software/amazon/awssdk/utils/IoUtils.java
utils/src/main/java/software/amazon/awssdk/utils/Platform.java
utils/src/main/java/software/amazon/awssdk/utils/Validate.java

Lift-and-shift support from V1 and switch to using V2 utils and conventions
To unblock AWS Toolkit for JetBrains customers
Fixes #455
Need to do more testing, but feel free to review.

Port credential_process support from Java SDK V1

---

.changes/next-release/bugfix-AmazonS3-611f9db.json
core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/async/FileAsyncResponseTransformer.java
services/s3/src/main/java/software/amazon/awssdk/services/s3/checksums/ChecksumValidatingPublisher.java

Should help reduce #1122 with S3.

Reduced the frequency of 'server failed to send complete response' exceptions when using S3AsyncClient.

---

core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/async/FileAsyncResponseTransformer.java

Fix NPE 
```
Caused by: software.amazon.awssdk.core.exception.SdkClientException
at software.amazon.awssdk.core.exception.SdkClientException$BuilderImpl.build(SdkClientException.java:97)
at software.amazon.awssdk.core.internal.util.ThrowableUtils.asSdkException(ThrowableUtils.java:98)
... 74 more
Caused by: java.lang.NullPointerException
at software.amazon.awssdk.core.internal.async.FileAsyncResponseTransformer.exceptionOccurred(FileAsyncResponseTransformer.java:81)
at software.amazon.awssdk.core.internal.http.async.AsyncStreamingResponseHandler.onError(AsyncStreamingResponseHandler.java:67)
at software.amazon.awssdk.core.internal.http.async.AsyncAfterTransmissionInterceptorCallingResponseHandler.onError(AsyncAfterTransmissionInterceptorCallingResponseHandler.java:72)
at …
```

Add null check for fileChannel in  to avoid NPE

---

.travis.yml
README.md
buildspecs/release-javadoc.yml
buildspecs/release-to-maven.yml
pom.xml
test/tests-coverage-reporting/pom.xml

Add integ test code coverage support and cross module code coverage
a new module `tests-coverage-reporting` is added to aggregate the testing reports so we can see the cross module tests coverage

Add integ test code coverage support and cross module code coverage

---

buildspecs/stability-test.yml
pom.xml
test/stability-tests/README.md
test/stability-tests/pom.xml
test/stability-tests/src/it/java/software/amazon/awssdk/stability/tests/ExceptionCounter.java
test/stability-tests/src/it/java/software/amazon/awssdk/stability/tests/TestResult.java
test/stability-tests/src/it/java/software/amazon/awssdk/stability/tests/s3/S3AsyncStabilityTest.java
test/stability-tests/src/it/java/software/amazon/awssdk/stability/tests/s3/S3BaseStabilityTest.java
test/stability-tests/src/it/java/software/amazon/awssdk/stability/tests/utils/StabilityTestUtils.java
test/stability-tests/src/main/resources/log4j.properties

- Add stability-tests module
- Add s3 stability tests
`mvn clean install -P stability-tests -pl :stability-tests`

Add stability-tests module, add s3 stability tests

---

.changes/next-release/bugfix-AWSSDKforJavav2-791e1e5.json
codegen/src/main/java/software/amazon/awssdk/codegen/poet/eventstream/EventStreamVisitorBuilderImplSpec.java
codegen/src/main/java/software/amazon/awssdk/codegen/poet/model/ShapeModelSpec.java
codegen/src/test/resources/software/amazon/awssdk/codegen/poet/eventstream/test-visitor-builder.java
codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/inputeventtwo.java
codegen/src/test/resources/software/amazon/awssdk/codegen/poet/transform/eventthreemarshaller.java
codegen/src/test/resources/software/amazon/awssdk/codegen/poet/transform/service-2.json
test/protocol-tests/src/main/resources/codegen-resources/restjson/service-2.json
test/protocol-tests/src/test/java/software/amazon/awssdk/protocol/tests/EventTransformTest.java

Fix header marshalling for Events
Bug fix.
New marshalling/unmarshalling test in `protocol-tests`.

Fix header marshalling for Events

---

.changes/next-release/bugfix-AWSSDKforJavav2-5194589.json
core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/async/FileAsyncResponseTransformer.java
core/sdk-core/src/test/java/software/amazon/awssdk/core/internal/async/FileAsyncResponseTransfomerTest.java
core/sdk-core/src/test/java/software/amazon/awssdk/core/internal/async/FileSubscriberTckTest.java

Fixes #1279
Bug fix.
New unit test added.

Call exceptionOcurred in case of stream error

---

core/sdk-core/src/test/java/software/amazon/awssdk/core/client/handler/SyncClientHandlerTest.java

Fix spelling in test

---

README.md

Re-arrange pom snippet
Discourage importing the whole SDK.

Re-arrange pom snippet

---

http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/internal/ResponseHandler.java
http-clients/netty-nio-client/src/test/java/software/amazon/awssdk/http/nio/netty/internal/PublisherAdapterTest.java

Work around to make KEEP_ALIVE private and update name space

Work around to make KEEP_ALIVE not private and update name space

---

services/s3/src/it/java/software/amazon/awssdk/services/s3/KeysWithLeadingSlashIntegrationTest.java
test/stability-tests/pom.xml

- Delete buckets after test
- Exclude Junit4 dependency in stability-tests

Couple of test fixes

---

services/s3/src/it/java/software/amazon/awssdk/services/s3/KeysWithLeadingSlashIntegrationTest.java

Use AssertJ lib for assertion.
Run test.

Change to use AssertJ assertion

---

core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/async/FileAsyncRequestBody.java
services-custom/s3-transfermanager/src/it/java/software/amazon/awssdk/custom/s3/transfer/TransferManagerTestUtils.java
services-custom/s3-transfermanager/src/it/java/software/amazon/awssdk/custom/s3/transfer/UploadIntegrationTest.java
services-custom/s3-transfermanager/src/main/java/software/amazon/awssdk/custom/s3/transfer/DownloadObjectSpecification.java
services-custom/s3-transfermanager/src/main/java/software/amazon/awssdk/custom/s3/transfer/DownloadRequest.java
services-custom/s3-transfermanager/src/main/java/software/amazon/awssdk/custom/s3/transfer/S3TransferManager.java
services-custom/s3-transfermanager/src/main/java/software/amazon/awssdk/custom/s3/transfer/TransferSpecification.java
services-custom/s3-transfermanager/src/main/java/software/amazon/awssdk/custom/s3/transfer/UploadObjectSpecification.java
services-custom/s3-transfermanager/src/main/java/software/amazon/awssdk/custom/s3/transfer/UploadRequest.java
services-custom/s3-transfermanager/src/main/java/software/amazon/awssdk/custom/s3/transfer/internal/ApiRequestUploadObjectSpecification.java
services-custom/s3-transfermanager/src/main/java/software/amazon/awssdk/custom/s3/transfer/internal/DefaultS3TransferManager.java
services-custom/s3-transfermanager/src/main/java/software/amazon/awssdk/custom/s3/transfer/internal/DownloadManager.java
services-custom/s3-transfermanager/src/main/java/software/amazon/awssdk/custom/s3/transfer/internal/FileTransferRequestBody.java
services-custom/s3-transfermanager/src/main/java/software/amazon/awssdk/custom/s3/transfer/internal/MultiPartUploadManager.java
services-custom/s3-transfermanager/src/main/java/software/amazon/awssdk/custom/s3/transfer/internal/MultipartUploadContext.java
services-custom/s3-transfermanager/src/main/java/software/amazon/awssdk/custom/s3/transfer/internal/RequestConversionUtils.java
services-custom/s3-transfermanager/src/main/java/software/amazon/awssdk/custom/s3/transfer/internal/SinglePartUploadContext.java
services-custom/s3-transfermanager/src/main/java/software/amazon/awssdk/custom/s3/transfer/internal/SinglePartUploadManager.java
services-custom/s3-transfermanager/src/main/java/software/amazon/awssdk/custom/s3/transfer/internal/TransferRequestBody.java
services-custom/s3-transfermanager/src/main/java/software/amazon/awssdk/custom/s3/transfer/internal/UploadManager.java
services-custom/s3-transfermanager/src/test/java/software/amazon/awssdk/custom/s3/transfer/internal/UploadManagerTest.java
utils/src/main/java/software/amazon/awssdk/utils/CompletableFutureUtils.java
utils/src/test/java/software/amazon/awssdk/utils/CompletableFutureUtilsTest.java

Implement s3 transfermanager upload object

Implement s3 transfermanager upload object

---

.changes/next-release/bugfix-AWSSDKforJavav2-1b88003.json
core/sdk-core/src/test/java/software/amazon/awssdk/core/internal/async/ByteArrayAsyncRequestBodyTest.java

A new change file was added for the bug fix of redundant requests issue.
A new change file was added.
Added the change file to indicate that redundant requests issue has been fixed in last update.
Used two threads to send request concurrently to test whether the change really works.

Added test for bug-fix and updated change log

---

codegen-lite-maven-plugin/pom.xml
codegen-maven-plugin/pom.xml

maven-plugin-plugin 3.6.0

---

http-clients/aws-crt-client/pom.xml
http-clients/aws-crt-client/src/main/java/software/amazon/awssdk/http/crt/AwsCrtAsyncHttpClient.java
http-clients/aws-crt-client/src/main/java/software/amazon/awssdk/http/crt/internal/AwsCrtAsyncHttpStreamAdapter.java
test/sdk-benchmarks/pom.xml

Update to new API

---

.changes/next-release/feature-AWSSDKforJavav2-959855c.json

Bad json in release notes is causing build to fail. 
Manually ran script to compile release notes. Was first able to repro problem, then with fix to prove it should now work.

Fixed json in release notes to unblock release

---

core/sdk-core/src/test/resources/log4j.properties

Change test log level to fix travis build failure.

Change test log level

---

core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/http/pipeline/stages/ApiCallTimeoutTrackingStage.java
core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/http/timers/SyncTimeoutTask.java

Remove some comments that aren't necessary.
N/A, comment cleanup.

Remove unnecessary comments

---

test/sdk-benchmarks/src/main/resources/software/amazon/awssdk/benchmark/baseline.json

Update benchmark baseline because of performance improvement from #1436

Update benchmark baseline because of performance improvement from #1436 

---

.changes/next-release/feature-AmazonS3Control-371969c.json

Adds changelog for #1449 that I forgot to include.

Adding changelog for S3 control

---

core/auth/src/main/java/software/amazon/awssdk/auth/credentials/InstanceProfileCredentialsProvider.java
core/auth/src/test/java/software/amazon/awssdk/auth/credentials/InstanceProfileCredentialsProviderTest.java
core/regions/src/main/java/software/amazon/awssdk/regions/internal/util/ConnectionUtils.java
core/regions/src/main/java/software/amazon/awssdk/regions/util/HttpResourcesUtils.java
core/regions/src/test/java/software/amazon/awssdk/regions/util/HttpCredentialsUtilsTest.java

Add support for IMDS token

---

core/auth/src/main/java/software/amazon/awssdk/auth/credentials/InstanceProfileCredentialsProvider.java
core/auth/src/test/java/software/amazon/awssdk/auth/credentials/EC2MetadataServiceMock.java
core/auth/src/test/java/software/amazon/awssdk/auth/credentials/InstanceProfileCredentialsProviderTest.java
core/regions/src/main/java/software/amazon/awssdk/regions/internal/util/ConnectionUtils.java
core/regions/src/main/java/software/amazon/awssdk/regions/util/HttpResourcesUtils.java
core/regions/src/test/java/software/amazon/awssdk/regions/util/HttpCredentialsUtilsTest.java

Revert the IMDS token feature removal and fix the issues.
IMDS token feature.
New unit tests and ran integ tests.

Revert IMDS revert + fixes

---

services/polly/src/test/java/software/amazon/awssdk/services/polly/internal/presigner/DefaultPollyPresignerTest.java

Fix test for Travis build

---

docs/design/ClientConfiguration.md
docs/design/FavorStaticFactoryMethods.md
docs/design/NamingConventions.md
docs/design/README.md
docs/design/UseOfCompletableFuture.md
docs/design/UseOfOptional.md
docs/design/core/presigners/README.md

* Updated design documents to clarify that 'Complete' features are actually just 'Released', because features are never complete.
* Update design documents to mark request presigners as 'Released'.

Update design statuses.

---

.changes/next-release/bugfix-AWSSDKforJavav2-00b4b93.json
core/protocols/aws-query-protocol/src/main/java/software/amazon/awssdk/protocols/query/unmarshall/XmlDomParser.java
core/protocols/aws-query-protocol/src/main/java/software/amazon/awssdk/protocols/query/unmarshall/XmlElement.java
core/protocols/aws-query-protocol/src/test/java/software/amazon/awssdk/protocols/query/XmlDomParserTest.java
core/protocols/aws-xml-protocol/src/main/java/software/amazon/awssdk/protocols/xml/internal/unmarshall/XmlProtocolUnmarshaller.java
services/s3/src/it/java/software/amazon/awssdk/services/s3/AclIntegrationTest.java
services/s3/src/test/java/software/amazon/awssdk/services/s3/AclTest.java

Fix unmarshalling for models with xml attributes
Related to #1488 
Added function tests, unit tests and integration tests

Fix unmarshalling for models with xml attributes

---

core/aws-core/src/main/java/software/amazon/awssdk/awscore/internal/AwsErrorCode.java

Add additional retry error codes
Better retry behavior.

Add additional retry error codes

---

pom.xml

Guava 28.2

---

http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/Http2Configuration.java
http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/NettyNioAsyncHttpClient.java
http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/internal/AwaitCloseChannelPoolMap.java
http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/internal/ChannelPipelineInitializer.java
http-clients/netty-nio-client/src/test/java/software/amazon/awssdk/http/nio/netty/internal/http2/PingTimeoutTest.java

Make the PING health check period configurable

---

http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/Http2Configuration.java
http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/internal/ChannelPipelineInitializer.java
http-clients/netty-nio-client/src/test/java/software/amazon/awssdk/http/nio/netty/internal/http2/PingTimeoutTest.java

Make 0 the disable value for ping duration

---

.changes/2.10.60.json
CHANGELOG.md

Remove changelog entry for reverted change

Remove changelog entry for reverted change

---

build-tools/src/main/resources/software/amazon/awssdk/intellij-copyright-profile.xml

Update intellij copyrihgt profile

Update intellij copyright profile

---

.github/ISSUE_TEMPLATE/bug-report.md
.github/ISSUE_TEMPLATE/feature-request.md
.github/ISSUE_TEMPLATE/general-issue.md

Creating 3 different templates for issues: bug, feature request and general issue.
Standardizing the use of templates among SDK repos and help in labeling automation.
For more details about github issue templates see [here ](https://help.github.com/en/github/building-a-strong-community/about-issue-and-pull-request-templates).

New github issue templates

---

services-custom/dynamodb-enhanced/src/main/java/software/amazon/awssdk/enhanced/dynamodb/Expression.java
services-custom/dynamodb-enhanced/src/main/java/software/amazon/awssdk/enhanced/dynamodb/internal/extensions/ChainExtension.java
services-custom/dynamodb-enhanced/src/main/java/software/amazon/awssdk/enhanced/dynamodb/internal/operations/PutItemOperation.java
services-custom/dynamodb-enhanced/src/main/java/software/amazon/awssdk/enhanced/dynamodb/internal/operations/QueryOperation.java
services-custom/dynamodb-enhanced/src/main/java/software/amazon/awssdk/enhanced/dynamodb/internal/operations/UpdateItemOperation.java
services-custom/dynamodb-enhanced/src/test/java/software/amazon/awssdk/enhanced/dynamodb/ExpressionTest.java
services-custom/dynamodb-enhanced/src/test/java/software/amazon/awssdk/enhanced/dynamodb/internal/operations/PutItemOperationTest.java

Coalesce was actually a misnomer and will confuse people.

DynamoDB Enhanced: Renamed Expression.coalesce to Expression.join

---

services-custom/dynamodb-enhanced/src/main/java/software/amazon/awssdk/enhanced/dynamodb/DynamoDbEnhancedClientExtension.java
services-custom/dynamodb-enhanced/src/main/java/software/amazon/awssdk/enhanced/dynamodb/DynamoDbExtensionContext.java
services-custom/dynamodb-enhanced/src/main/java/software/amazon/awssdk/enhanced/dynamodb/extensions/VersionedRecordExtension.java
services-custom/dynamodb-enhanced/src/main/java/software/amazon/awssdk/enhanced/dynamodb/internal/EnhancedClientUtils.java
services-custom/dynamodb-enhanced/src/main/java/software/amazon/awssdk/enhanced/dynamodb/internal/extensions/ChainExtension.java
services-custom/dynamodb-enhanced/src/main/java/software/amazon/awssdk/enhanced/dynamodb/internal/extensions/DefaultDynamoDbExtensionContext.java
services-custom/dynamodb-enhanced/src/main/java/software/amazon/awssdk/enhanced/dynamodb/internal/operations/PutItemOperation.java
services-custom/dynamodb-enhanced/src/main/java/software/amazon/awssdk/enhanced/dynamodb/internal/operations/UpdateItemOperation.java
services-custom/dynamodb-enhanced/src/test/java/software/amazon/awssdk/enhanced/dynamodb/extensions/ChainExtensionTest.java
services-custom/dynamodb-enhanced/src/test/java/software/amazon/awssdk/enhanced/dynamodb/extensions/VersionedRecordExtensionTest.java
services-custom/dynamodb-enhanced/src/test/java/software/amazon/awssdk/enhanced/dynamodb/internal/DefaultDocumentTest.java
services-custom/dynamodb-enhanced/src/test/java/software/amazon/awssdk/enhanced/dynamodb/internal/client/ExtensionResolverTest.java
services-custom/dynamodb-enhanced/src/test/java/software/amazon/awssdk/enhanced/dynamodb/internal/operations/BatchGetItemOperationTest.java
services-custom/dynamodb-enhanced/src/test/java/software/amazon/awssdk/enhanced/dynamodb/internal/operations/BatchWriteItemOperationTest.java
services-custom/dynamodb-enhanced/src/test/java/software/amazon/awssdk/enhanced/dynamodb/internal/operations/DeleteItemOperationTest.java
services-custom/dynamodb-enhanced/src/test/java/software/amazon/awssdk/enhanced/dynamodb/internal/operations/GetItemOperationTest.java
services-custom/dynamodb-enhanced/src/test/java/software/amazon/awssdk/enhanced/dynamodb/internal/operations/PutItemOperationTest.java
services-custom/dynamodb-enhanced/src/test/java/software/amazon/awssdk/enhanced/dynamodb/internal/operations/QueryOperationTest.java
services-custom/dynamodb-enhanced/src/test/java/software/amazon/awssdk/enhanced/dynamodb/internal/operations/ScanOperationTest.java
services-custom/dynamodb-enhanced/src/test/java/software/amazon/awssdk/enhanced/dynamodb/internal/operations/UpdateItemOperationTest.java

Create wrapper class for ddb enhanced extension input parameters
Updated tests

Create wrapper class for ddb enhanced extension input parameters

---

services-custom/dynamodb-enhanced/src/main/java/software/amazon/awssdk/enhanced/dynamodb/DynamoDbAsyncIndex.java
services-custom/dynamodb-enhanced/src/main/java/software/amazon/awssdk/enhanced/dynamodb/DynamoDbAsyncTable.java
services-custom/dynamodb-enhanced/src/main/java/software/amazon/awssdk/enhanced/dynamodb/DynamoDbIndex.java
services-custom/dynamodb-enhanced/src/main/java/software/amazon/awssdk/enhanced/dynamodb/DynamoDbTable.java
services-custom/dynamodb-enhanced/src/main/java/software/amazon/awssdk/enhanced/dynamodb/model/QueryConditional.java
services-custom/dynamodb-enhanced/src/test/java/software/amazon/awssdk/enhanced/dynamodb/functionaltests/AsyncBasicQueryTest.java
services-custom/dynamodb-enhanced/src/test/java/software/amazon/awssdk/enhanced/dynamodb/internal/client/DefaultDynamoDbEnhancedAsyncClientTest.java
services-custom/dynamodb-enhanced/src/test/java/software/amazon/awssdk/enhanced/dynamodb/internal/client/DefaultDynamoDbEnhancedClientTest.java

Remove flaky tests and fix javadocs
All occurrences of `QueryConditional` in the comments should reference the correct method names now

Remove flaky tests and fix javadocs

---

core/auth/src/main/java/software/amazon/awssdk/auth/signer/internal/BaseEventStreamAsyncAws4Signer.java
core/auth/src/test/java/software/amazon/awssdk/auth/signer/internal/BaseEventStreamAsyncAws4SignerTest.java

In case of future bugs related to event stream signing, this should help in
debuggging to see the contents of the message in an easier to read format.
Nice to have for future debugging.

Log signed event for easier debugging

---

test/sdk-benchmarks/src/main/java/software/amazon/awssdk/benchmark/BenchmarkResultProcessor.java

Should make it easier to add new benchmarks and get baseline numbers for them.
Easier addition of new benchmarks.

Log result data when no baseline found

---

archetypes/archetype-lambda/pom.xml

Fix windows build

---

http-client-spi/src/main/java/software/amazon/awssdk/http/SdkHttpResponse.java

Fixes incorrect javadoc.
Makes Javadoc easier to understand by actually reflecting the method.
Just doc change no testing

Fix typo in javadoc: query parameters -> http headers

---

.changes/next-release/feature-AWSSDJforJavav2-1086367.json
bom-internal/pom.xml
pom.xml

Upgrade Jackson version and unify Jackson-annotations and Jackson

Upgrade Jackson version and unify Jackson-annotations and Jackson

---

.github/workflows/stale-issue.yml

Removing the dry-run state and changing schedule to run every 30 minutes.

Stale issue action: removing dry-run state

---

services-custom/dynamodb-enhanced/src/main/java/software/amazon/awssdk/enhanced/dynamodb/model/TransactWriteItemsEnhancedRequest.java

Add javadoc for ClientRequestToken in TransactWriteItemsEnhancedRequest

Add javadoc for ClientRequestToken in TransactWriteItemsEnhancedRequest

---

codegen/src/main/java/software/amazon/awssdk/codegen/poet/client/SyncClientClass.java
codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/test-endpoint-discovery-sync.java
codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/test-json-client-class.java
codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/test-query-client-class.java
core/sdk-core/src/main/java/software/amazon/awssdk/core/metrics/CoreMetric.java
test/codegen-generated-classes-test/src/test/java/software/amazon/awssdk/services/metrics/CoreMetricsTest.java

- move ServiceId and OperationName reporting into try block
- ServiceName -> ServiceId
- Fix typo in test

Minor metrics fixes

---

test/codegen-generated-classes-test/src/test/java/software/amazon/awssdk/services/metrics/CoreMetricsTest.java

Additional tests to ensure IOE's caught during request exception are reported in metrics.

Additional tests for IOException for core metrics

---

core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/http/pipeline/stages/MakeAsyncHttpRequestStage.java
core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/http/pipeline/stages/MakeHttpRequestStage.java
core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/util/MetricUtils.java
core/sdk-core/src/test/java/software/amazon/awssdk/core/internal/http/pipeline/stages/MakeAsyncHttpRequestStageTest.java
core/sdk-core/src/test/java/software/amazon/awssdk/core/internal/http/pipeline/stages/MakeHttpRequestStageTest.java
test/codegen-generated-classes-test/src/test/java/software/amazon/awssdk/services/metrics/CoreMetricsTest.java
test/codegen-generated-classes-test/src/test/java/software/amazon/awssdk/services/metrics/async/BaseAsyncCoreMetricsTest.java

Add HttpClient collector to HTTP request

---

metric-publishers/cloudwatch-metric-publisher/pom.xml
metric-publishers/pom.xml
test/tests-coverage-reporting/pom.xml

Update CW Publisher to PREVIEW

---

http-clients/netty-nio-client/src/test/java/software/amazon/awssdk/http/nio/netty/Http2MetricsTest.java
test/codegen-generated-classes-test/src/test/java/software/amazon/awssdk/services/metrics/CoreMetricsTest.java
test/codegen-generated-classes-test/src/test/java/software/amazon/awssdk/services/metrics/async/AsyncCoreMetricsTest.java

- Init test clients with mock credentials provider
- Account for asynchrony for local stream window size

Fix metrics tests

---

core/metrics-spi/src/main/java/software/amazon/awssdk/metrics/NoOpMetricCollector.java
core/metrics-spi/src/main/java/software/amazon/awssdk/metrics/internal/EmptyMetricCollection.java

Remove unsupported exception from No op collector

---

README.md

This is a work to standardize the support guidelines throughout SDKs.

Updated Giving Feedback section in README

---

pom.xml

Update CRT http client to latest published CRT
The crt http client now uses a per-stream windowing implementation.
All Crt Stability Tests
Crt Performance Tests
- [ x ] Bug fix (non-breaking change which fixes an issue)
- [ x ] New feature (non-breaking change which adds functionality)

Update CRT http client to latest published CRT

---

http-clients/aws-crt-client/src/main/java/software/amazon/awssdk/http/crt/AwsCrtAsyncHttpClient.java
http-clients/aws-crt-client/src/main/java/software/amazon/awssdk/http/crt/internal/AwsCrtAsyncHttpStreamAdapter.java
http-clients/aws-crt-client/src/main/java/software/amazon/awssdk/http/crt/internal/AwsCrtRequestBodySubscriber.java
http-clients/aws-crt-client/src/main/java/software/amazon/awssdk/http/crt/internal/AwsCrtResponseBodyPublisher.java
http-clients/aws-crt-client/src/test/java/software/amazon/awssdk/http/crt/AwsCrtHttpClientSpiVerificationTest.java
http-clients/aws-crt-client/src/test/java/software/amazon/awssdk/http/crt/H1ServerBehaviorTest.java
http-clients/aws-crt-client/src/test/java/software/amazon/awssdk/http/crt/ProxyWireMockTest.java
http-clients/aws-crt-client/src/test/resources/log4j.properties
http-clients/netty-nio-client/src/test/java/software/amazon/awssdk/http/nio/netty/fault/H1ServerErrorTest.java
test/http-client-tests/src/main/java/software/amazon/awssdk/http/HttpTestUtils.java
test/http-client-tests/src/main/java/software/amazon/awssdk/http/SdkAsyncHttpClientH1TestSuite.java
test/stability-tests/src/it/java/software/amazon/awssdk/stability/tests/utils/StabilityTestRunner.java

Various refactoring of crt branch

---

http-clients/aws-crt-client/src/main/java/software/amazon/awssdk/http/crt/AwsCrtAsyncHttpClient.java
http-clients/aws-crt-client/src/main/java/software/amazon/awssdk/http/crt/ConnectionHealthChecksConfiguration.java
http-clients/aws-crt-client/src/test/java/software/amazon/awssdk/http/crt/AwsCrtHttpClientSpiVerificationTest.java
http-clients/aws-crt-client/src/test/java/software/amazon/awssdk/http/crt/ConnectionHealthChecksConfigurationTest.java

create `ConnectionHealthChecksConfiguration` and expose it in the crt client builder
https://github.com/aws/aws-sdk-java-v2/blob/master/docs/design/http-clients/aws-crt-client/DecisionLog.md#82420

create connection health checks configuration

---

build-tools/src/main/resources/software/amazon/awssdk/spotbugs-suppressions.xml
core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/waiters/AsyncWaiterExecutor.java
core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/waiters/DefaultAsyncWaiter.java
core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/waiters/DefaultWaiter.java
core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/waiters/DefaultWaiterResponse.java
core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/waiters/ResponseOrException.java
core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/waiters/WaiterExecutor.java
core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/waiters/WaiterExecutorHelper.java
core/sdk-core/src/main/java/software/amazon/awssdk/core/waiters/AsyncWaiter.java
core/sdk-core/src/main/java/software/amazon/awssdk/core/waiters/PollingStrategy.java
core/sdk-core/src/main/java/software/amazon/awssdk/core/waiters/Waiter.java
core/sdk-core/src/main/java/software/amazon/awssdk/core/waiters/WaiterAcceptor.java
core/sdk-core/src/main/java/software/amazon/awssdk/core/waiters/WaiterBuilder.java
core/sdk-core/src/main/java/software/amazon/awssdk/core/waiters/WaiterResponse.java
core/sdk-core/src/main/java/software/amazon/awssdk/core/waiters/WaiterState.java
core/sdk-core/src/test/java/software/amazon/awssdk/core/internal/waiters/DefaultWaiterResponseTest.java
core/sdk-core/src/test/java/software/amazon/awssdk/core/waiters/AsyncWaiterTest.java
core/sdk-core/src/test/java/software/amazon/awssdk/core/waiters/BaseWaiterTest.java
core/sdk-core/src/test/java/software/amazon/awssdk/core/waiters/WaiterAcceptorTest.java
core/sdk-core/src/test/java/software/amazon/awssdk/core/waiters/WaiterTest.java
utils/src/main/java/software/amazon/awssdk/utils/Either.java
utils/src/test/java/software/amazon/awssdk/utils/EitherTest.java

Implement generic Waiter functionality

Implement generic Waiter functionality

---

docs/README.md

- Whenever clicked on Contribution Guide Link provided in [ReadMe file](https://github.com/aws/aws-sdk-java-v2/blob/master/docs/README.md) it used to land up in 404 page not found.
- No open issue.
- Tested by pushing it to local branch and then accessing the link in GitHub.
- After clicking on the link after the pushed changes it landed up in right Contribution Guide page.

Correcting Typo error in Contribution Guide mentioned in docs/README.md

---

http-clients/aws-crt-client/src/main/java/software/amazon/awssdk/http/crt/AwsCrtAsyncHttpClient.java
http-clients/aws-crt-client/src/main/java/software/amazon/awssdk/http/crt/AwsCrtSdkHttpService.java
http-clients/aws-crt-client/src/main/java/software/amazon/awssdk/http/crt/ConnectionHealthChecksConfiguration.java
http-clients/aws-crt-client/src/main/java/software/amazon/awssdk/http/crt/ProxyConfiguration.java

Add preview API annotations

---

codegen/src/main/java/software/amazon/awssdk/codegen/IntermediateModelBuilder.java
codegen/src/main/java/software/amazon/awssdk/codegen/emitters/GeneratorPathProvider.java
codegen/src/main/java/software/amazon/awssdk/codegen/emitters/tasks/WaitersGeneratorTasks.java
codegen/src/main/java/software/amazon/awssdk/codegen/model/intermediate/IntermediateModel.java
codegen/src/main/java/software/amazon/awssdk/codegen/model/intermediate/Metadata.java
codegen/src/main/java/software/amazon/awssdk/codegen/model/service/Acceptor.java
codegen/src/main/java/software/amazon/awssdk/codegen/model/service/Waiters.java
codegen/src/main/java/software/amazon/awssdk/codegen/poet/waiters/WaitersClassSpec.java

Add waiter generator task

---

services-custom/dynamodb-enhanced/src/main/java/software/amazon/awssdk/enhanced/dynamodb/internal/mapper/MetaTableSchema.java

chore: fix javadoc

---

.changes/next-release/bugfix-AWSSDKforJavav2-fcb421f.json
codegen/src/main/java/software/amazon/awssdk/codegen/poet/client/AsyncClientClass.java
codegen/src/main/java/software/amazon/awssdk/codegen/poet/client/ClientClassUtils.java
codegen/src/main/java/software/amazon/awssdk/codegen/poet/client/specs/JsonProtocolSpec.java
codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/test-async-client-class.java
codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/test-endpoint-discovery-async.java
codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/test-query-async-client-class.java
core/auth/src/main/java/software/amazon/awssdk/auth/signer/AsyncAws4Signer.java
core/auth/src/main/java/software/amazon/awssdk/auth/signer/internal/AbstractAws4Signer.java
core/auth/src/main/java/software/amazon/awssdk/auth/signer/internal/DigestComputingSubscriber.java
core/auth/src/test/java/software/amazon/awssdk/auth/signer/NonStreamingAsyncBodyAws4SignerTest.java
core/auth/src/test/java/software/amazon/awssdk/auth/signer/internal/DigestComputingSubscriberTest.java
core/sdk-core/src/main/java/software/amazon/awssdk/core/client/builder/SdkDefaultClientBuilder.java
core/sdk-core/src/main/java/software/amazon/awssdk/core/client/config/SdkClientOption.java
core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/http/AmazonAsyncHttpClient.java
core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/http/pipeline/stages/AsyncBeforeTransmissionExecutionInterceptorsStage.java
core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/http/pipeline/stages/AsyncSigningStage.java
core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/http/pipeline/stages/MakeAsyncHttpRequestStage.java
core/sdk-core/src/main/java/software/amazon/awssdk/core/signer/AsyncSigner.java
core/sdk-core/src/test/java/software/amazon/awssdk/core/internal/http/pipeline/stages/MakeAsyncHttpRequestStageTest.java
services/glacier/src/it/java/software/amazon/awssdk/services/glacier/UploadArchiveIntegrationTest.java
services/s3/src/it/java/software/amazon/awssdk/services/s3/SignedAsyncRequestBodyUploadIntegrationTest.java
test/codegen-generated-classes-test/src/test/java/software/amazon/awssdk/services/AsyncSignerOverrideTest.java
test/codegen-generated-classes-test/src/test/java/software/amazon/awssdk/services/protocolquery/AsyncOperationCancelTest.java

This fixes a bug where the SHA-256 of the request body is not included in the
SigV4 calculation for async, streaming (note: not event streaming) requests.
This fixes streaming operations for both CloudSearch Domain and and Glacier.
Bug fix.
- New unit tests
- Tested UploadDocument for CloudSearch Domain and UploadArchive for Glacier.
- Ran integ tests

Don't omit body hash during async signing

---

codegen/src/main/java/software/amazon/awssdk/codegen/jmespath/component/Expression.java
codegen/src/main/java/software/amazon/awssdk/codegen/poet/waiters/AsyncWaiterClassSpec.java
codegen/src/test/resources/software/amazon/awssdk/codegen/poet/waiters/query-async-waiter-class.java
core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/waiters/AsyncWaiterExecutor.java
core/sdk-core/src/main/java/software/amazon/awssdk/core/waiters/AsyncWaiter.java
core/sdk-core/src/main/java/software/amazon/awssdk/core/waiters/Waiter.java

…ore number, fix javadocs, remove unnecessary logs
- change the default scheduled executor service core number to 1
- fix Javadocs
- remove unnecessary logging

Various small fixes 

---

codegen/src/main/java/software/amazon/awssdk/codegen/docs/WaiterDocs.java
codegen/src/test/resources/software/amazon/awssdk/codegen/poet/waiters/query-async-waiter-interface.java
core/sdk-core/src/main/java/software/amazon/awssdk/core/waiters/WaiterOverrideConfiguration.java

Revisited the Waiters related javadocs and did some small modifications.

Adjust the Waiters related javadocs

---

docs/design/core/waiters/DecisionLog.md

Add decision log for waiters

---

docs/design/core/waiters/README.md

Update design doc

---

test/codegen-generated-classes-test/src/test/java/software/amazon/awssdk/services/metrics/async/BaseAsyncCoreMetricsTest.java

Increase test delay to reduce flakiness

Increase test delay to reduce flakiness

---

scripts/changelog/model.py
scripts/changelog/util.py
scripts/changelog/writer.py
scripts/new-change

add an option in the changelog entry script to provide github username to be mentioned in the CHANGELOG
Sample changelog
- ### Features
- test
- Contributed by: @awesomecontributor1 
- ### Features
- test
- Contributed by: @awesomecontributor2
- ### Features
- test1
Special thanks to the following contributors to this release: 
@awesomecontributor1, @awesomecontributor2.

Add an option to provide github username to be mentioned 

---

scripts/changelog/model.py
scripts/changelog/util.py
scripts/changelog/writer.py
scripts/new-change

Fix script

---

codegen/src/main/java/software/amazon/awssdk/codegen/poet/client/specs/XmlProtocolSpec.java
codegen/src/test/java/software/amazon/awssdk/codegen/poet/ClientTestModels.java
codegen/src/test/java/software/amazon/awssdk/codegen/poet/client/PoetClientFunctionalTests.java
codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/c2j/xml/customization.config
codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/c2j/xml/service-2.json
codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/test-xml-async-client-class.java
codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/test-xml-client-class.java
services/s3control/src/it/java/software.amazon.awssdk.services.s3control/S3AsyncAccessPointsIntegrationTest.java

Fix a bug where host prefix was not added for services with xml protocol

Fix a bug where host prefix was not added for services with xml protocol

---

bom/pom.xml

Add the metrics-spi to the bom.
I was missing this in the bom when writing a custom metrics publisher.
ran a mvn install

Add metrics-spi to bom

---

.changes/next-release/feature-AWSSDKforJavav2-04977cd.json
pom.xml

Upgrade `org.apache.httpcomponents:httpclient` version to `4.5.13`

Upgrade Apache Http client version

---

README.md

Added links to AWS SDKs and Tools maintenance policy documentation and version support matrix to the main README.

Add links to Maintenance Policy to README

---

bom-internal/pom.xml
build-tools/pom.xml
pom.xml
services-custom/dynamodb-enhanced/src/main/java/software/amazon/awssdk/enhanced/dynamodb/internal/operations/CreateTableOperation.java

Upgrade com.puppycrawl.tools to 8.38
Upgrading to address 
- https://snyk.io/vuln/SNYK-JAVA-COMGOOGLEGUAVA-1015415
- Also addressed a failing checkstyle error in CreateTableOperation

Upgrade com.puppycrawl.tools to 8.38

---

.changes/next-release/bugfix-AWSSDKforJavav2-cb2c62e.json
bom-internal/pom.xml
pom.xml
test/sdk-benchmarks/pom.xml

Upgrading jackson.databind.version to 2.10.5.1 for Issue #2207
https://github.com/aws/aws-sdk-java-v2/issues/2207
- mvn clean install

Upgrading jackson.databind.version to 2.10.5.1 for Issue #2207

---

.changes/2.15.25.json
.changes/2.15.40.json
scripts/changelog/writer.py
scripts/new-change

Enable links to contributors' github pages

Enable links to contributors' github pages

---

codegen/src/main/java/software/amazon/awssdk/codegen/poet/client/AsyncClientClass.java
codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/test-async-client-class.java
test/codegen-generated-classes-test/pom.xml
test/codegen-generated-classes-test/src/main/resources/codegen-resources/eventstreams/service-2.json
test/codegen-generated-classes-test/src/test/java/software/amazon/awssdk/services/eventstreams/EventMarshallingTest.java

Use the correct classes for the class -> marshaller mapper for new style
generated event streams.
Bug fix.
New tests.

Fix event marshalling

---

.changes/next-release/feature-AWSCommontRuntimeHTTPClient-536d33d.json
pom.xml

Upgrade `aws-crt` to version `0.9.3`

Bump up crt version

---

.changes/next-release/feature-AmazonDocumentDBwithMongoDBcompatibility-d9dcc83.json
.changes/next-release/feature-AmazonNeptune-44c95a1.json
services/docdb/src/main/java/software/amazon/awssdk/services/docdb/internal/CopyDbClusterSnapshotPresignInterceptor.java
services/docdb/src/main/java/software/amazon/awssdk/services/docdb/internal/CreateDbClusterPresignInterceptor.java
services/docdb/src/main/java/software/amazon/awssdk/services/docdb/internal/RdsPresignInterceptor.java
services/docdb/src/main/resources/codegen-resources/customization.config
services/docdb/src/main/resources/software/amazon/awssdk/services/docdb/execution.interceptors
services/docdb/src/test/java/software/amazon/awssdk/services/docdb/internal/PresignRequestHandlerTest.java
services/docdb/src/test/java/software/amazon/awssdk/services/docdb/internal/PresignRequestWireMockTest.java
services/neptune/src/main/java/software/amazon/awssdk/services/neptune/internal/CopyDbClusterSnapshotPresignInterceptor.java
services/neptune/src/main/java/software/amazon/awssdk/services/neptune/internal/CreateDbClusterPresignInterceptor.java
services/neptune/src/main/java/software/amazon/awssdk/services/neptune/internal/RdsPresignInterceptor.java
services/neptune/src/main/resources/codegen-resources/customization.config
services/neptune/src/main/resources/software/amazon/awssdk/services/neptune/execution.interceptors
services/neptune/src/test/java/software/amazon/awssdk/services/neptune/internal/PresignRequestHandlerTest.java
services/neptune/src/test/java/software/amazon/awssdk/services/neptune/internal/PresignRequestWireMockTest.java

Cross-Region Copying Pre-Signer for DocDB and Neptune
**Neptune** (As of today, `PreSignedUrl` for both operations are not currently supported)
* `CopyDBClusterSnapshot`
* `CreateDBCluster`
**DocDB** (As of today, `PreSignedUrl` for both operations are not currently supported)
* `CopyDBClusterSnapshot`
* `CreateDBCluster`
- JUnits Added

Cross-Region Copying Pre-Signer for DocDB and Neptune

---

scripts/changelog/writer.py
scripts/new-change

Add documentation category in the change log

Add documentation category in changelog

---

pom.xml

netty.version upgrade to 4.1.59.Final

netty.version upgrade to 4.1.59.Final

---

README.md
services/s3/src/test/java/software/amazon/awssdk/services/s3/EndpointOverrideEndpointResolutionTest.java
services/s3control/src/test/java/software/amazon/awssdk/services/s3control/EndpointOverrideEndpointResolutionTest.java

Fix Travis build

---

services/s3/src/it/java/software/amazon/awssdk/services/s3/HeadObjectIntegrationTest.java

Added AfterClass method to cleanUp Bucket after test in HeadObjectIntegrationTest.
- Integration test failed after 100 buckets were created.

Delete Test bucket after completion HeadObjectIntegrationTest

---

NOTICE.txt

https://github.com/apache/commons-lang/blob/5689c91cf2a3a27f0a3a8a362857f2cf0919d4f6/NOTICE.txt
Fixes #2285

Add Apache Commons Lang NOTICE

---

buildspecs/release-to-maven.yml

Needs to be included because it's a dependency of the archetypes.

Don't exclude archetype-tools from Maven release

---

pom.xml

Revert japicmp exclusion after release

---

test/http-client-tests/src/main/java/software/amazon/awssdk/http/SdkHttpClientTestSuite.java

This attempts to guard against multiple subclasses of SdkHttpClientTestSuite
running parallel attempting to bind to the same port on startup.

Add retry attempts for creating wiremock server

---

http-clients/url-connection-client/src/main/java/software/amazon/awssdk/http/urlconnection/UrlConnectionHttpClient.java

Simple log output fix.
Fix incorrect log.
No tests related.

Fix misleading log output

---

pom.xml
services/s3/pom.xml
services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/CrtResponseDataConsumerAdapter.java
services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/DefaultS3CrtAsyncClient.java
services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/S3CrtDataPublisher.java
services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/S3CrtUtils.java
services/s3/src/test/java/software/amazon/awssdk/services/s3/crt/S3CrtGetObjectIntegrationTest.java
services/s3/src/test/java/software/amazon/awssdk/services/s3/internal/S3CrtDataPublisherTckTest.java
services/s3/src/test/java/software/amazon/awssdk/services/s3/internal/S3CrtDataPublisherTest.java
test/stability-tests/src/it/java/software/amazon/awssdk/stability/tests/s3/S3CrtAsyncClientStabilityTest.java
test/stability-tests/src/it/java/software/amazon/awssdk/stability/tests/s3/S3CrtAsyncStabilityTest.java

Implement getObject in S3CrtAsyncClient
~~This depends on https://github.com/awslabs/aws-crt-java/pull/292~~
~~Still need to do more testing and clean up unnecessary the logging statements~~
The change in CRT https://github.com/awslabs/aws-crt-java/pull/296 has been merged, but it hasn't been released yet. So the build will fail because `aws-crt-java: 1.0.0-SNAPSHOT` is not available in Maven

Implement getObject in S3CrtAsyncClient

---

services/s3/src/main/java/software/amazon/awssdk/services/s3/S3CrtAsyncClient.java
services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/s3crt/CrtResponseDataConsumerAdapter.java
services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/s3crt/DefaultS3CrtAsyncClient.java
services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/s3crt/DefaultS3CrtClientBuilder.java
services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/s3crt/RequestDataSupplierAdapter.java
services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/s3crt/S3CrtDataPublisher.java
services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/s3crt/S3CrtUtils.java
services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/s3crt/S3NativeClientConfiguration.java
services/s3/src/test/java/software/amazon/awssdk/services/s3/internal/S3CrtDataPublisherTckTest.java
services/s3/src/test/java/software/amazon/awssdk/services/s3/internal/S3CrtDataPublisherTest.java
services/s3/src/test/java/software/amazon/awssdk/services/s3/internal/S3CrtUtilsTest.java
test/stability-tests/src/it/java/software/amazon/awssdk/stability/tests/s3/S3CrtAsyncClientStabilityTest.java
test/stability-tests/src/it/java/software/amazon/awssdk/stability/tests/s3/S3WithCrtAsyncHttpClientStabilityTest.java

- Fix checkstyle errors
- Add stability tests
- Move crt related classes to s3crt package

Various fixes

---

pom.xml
services/s3/pom.xml

Upgrade crt to 0.11.5

---

services-custom/s3-transfermanager/pom.xml
services-custom/s3-transfermanager/src/it/java/software/amazon/awssdk/custom/s3/transfer/S3TransferManagerUploadIntegrationTest.java
services-custom/s3-transfermanager/src/main/java/software/amazon/awssdk/custom/s3/transfer/CompletedUpload.java
services-custom/s3-transfermanager/src/main/java/software/amazon/awssdk/custom/s3/transfer/UploadRequest.java
services-custom/s3-transfermanager/src/main/java/software/amazon/awssdk/custom/s3/transfer/internal/DefaultCompletedUpload.java
services-custom/s3-transfermanager/src/main/java/software/amazon/awssdk/custom/s3/transfer/internal/DefaultS3TransferManager.java
services-custom/s3-transfermanager/src/main/java/software/amazon/awssdk/custom/s3/transfer/internal/DefaultUpload.java
services-custom/s3-transfermanager/src/test/java/software/amazon/awssdk/custom/s3/transfer/DefaultUploadRequestTest.java
services-custom/s3-transfermanager/src/test/java/software/amazon/awssdk/custom/s3/transfer/S3TransferManagerUploadTest.java
services-custom/s3-transfermanager/src/test/java/software/amazon/awssdk/custom/s3/transfer/util/ChecksumUtils.java

Implement S3TransferManager#upload

---

buildspecs/release-to-maven.yml
pom.xml
services-custom/s3-transfermanager/src/it/java/software/amazon/awssdk/custom/s3/transfer/S3IntegrationTestBase.java
services-custom/s3-transfermanager/src/it/java/software/amazon/awssdk/custom/s3/transfer/S3TransferManagerDownloadIntegrationTest.java
services-custom/s3-transfermanager/src/it/java/software/amazon/awssdk/custom/s3/transfer/S3TransferManagerUploadIntegrationTest.java
services-custom/s3-transfermanager/src/main/java/software/amazon/awssdk/custom/s3/transfer/DownloadRequest.java
services-custom/s3-transfermanager/src/main/java/software/amazon/awssdk/custom/s3/transfer/internal/DefaultCompletedDownload.java
services-custom/s3-transfermanager/src/main/java/software/amazon/awssdk/custom/s3/transfer/internal/DefaultS3TransferManager.java
services-custom/s3-transfermanager/src/test/java/software/amazon/awssdk/custom/s3/transfer/DownloadRequestTest.java
services-custom/s3-transfermanager/src/test/java/software/amazon/awssdk/custom/s3/transfer/S3TransferManagerTest.java
services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/s3crt/CrtResponseDataConsumerAdapter.java
services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/s3crt/S3NativeClientConfiguration.java
test/s3-benchmarks/README.md
test/s3-benchmarks/pom.xml
test/s3-benchmarks/src/main/java/software/amazon/awssdk/s3benchmarks/BaseTransferManagerBenchmark.java
test/s3-benchmarks/src/main/java/software/amazon/awssdk/s3benchmarks/BenchmarkRunner.java
test/s3-benchmarks/src/main/java/software/amazon/awssdk/s3benchmarks/NoOpResponseTransformer.java
test/s3-benchmarks/src/main/java/software/amazon/awssdk/s3benchmarks/TransferManagerBenchmark.java
test/s3-benchmarks/src/main/java/software/amazon/awssdk/s3benchmarks/TransferManagerBenchmarkConfig.java
test/s3-benchmarks/src/main/java/software/amazon/awssdk/s3benchmarks/TransferManagerDownloadBenchmark.java
test/s3-benchmarks/src/main/java/software/amazon/awssdk/s3benchmarks/TransferManagerUploadBenchmark.java
test/s3-benchmarks/src/main/resources/log4j.properties
test/tests-coverage-reporting/pom.xml

- Implement TransferManager download 
- Add s3-benchmarks module

Implement TransferManager download and add s3-benchmarks module

---

.changes/next-release/feature-NettyNIOHTTPClient-af58a9c.json
pom.xml

Update Netty to 4.1.61.Final

---

buildspecs/release-javadoc.yml
buildspecs/release-to-maven.yml

Pin CLI version in buildspecs

---

.all-contributorsrc
README.md

Backfill all contributors

---

http-client-spi/src/main/java/software/amazon/awssdk/http/async/SdkAsyncHttpResponseHandler.java

Annotate `SdkAsyncHttpResponseHandler` as public api

Annotate `SdkAsyncHttpResponseHandler` as public api

---

services/cloudformation/src/it/java/software/amazon/awssdk/services/cloudformation/SendEmptyListIntegrationTest.java

Use SDK waiter in the cf integ test

Use SDK waiter in the cf integ test

---

.changes/next-release/feature-AmazonDynamoDB-1607a75.json
services-custom/dynamodb-enhanced/src/main/java/software/amazon/awssdk/enhanced/dynamodb/DynamoDbAsyncTable.java
services-custom/dynamodb-enhanced/src/main/java/software/amazon/awssdk/enhanced/dynamodb/DynamoDbTable.java
services-custom/dynamodb-enhanced/src/main/java/software/amazon/awssdk/enhanced/dynamodb/internal/client/DefaultDynamoDbAsyncTable.java
services-custom/dynamodb-enhanced/src/main/java/software/amazon/awssdk/enhanced/dynamodb/internal/client/DefaultDynamoDbTable.java
services-custom/dynamodb-enhanced/src/main/java/software/amazon/awssdk/enhanced/dynamodb/internal/operations/DeleteTableOperation.java
services-custom/dynamodb-enhanced/src/test/java/software/amazon/awssdk/enhanced/dynamodb/internal/operations/DeleteTableAsyncTest.java
services-custom/dynamodb-enhanced/src/test/java/software/amazon/awssdk/enhanced/dynamodb/internal/operations/DeleteTableOperationTest.java
services-custom/dynamodb-enhanced/src/test/java/software/amazon/awssdk/enhanced/dynamodb/internal/operations/DeleteTableSyncTest.java

- DDBEnhanced - Support delete-table operation
- As of now deleteTable API was not available in DynamoDBTable interface. Added this new API and its default implementation
#1966 requested this operation
- Added JUnit test cases using DDBLocals and Mocks.

DDBEnhanced - Support delete-table operation

---

services-custom/s3-transfermanager/pom.xml
services-custom/s3-transfermanager/src/it/java/software/amazon/awssdk/custom/s3/transfer/S3TransferManagerDownloadIntegrationTest.java
services-custom/s3-transfermanager/src/main/java/software/amazon/awssdk/custom/s3/transfer/internal/CrtResponseDataConsumerAdapter.java
services-custom/s3-transfermanager/src/main/java/software/amazon/awssdk/custom/s3/transfer/internal/DefaultS3CrtAsyncClient.java
services-custom/s3-transfermanager/src/main/java/software/amazon/awssdk/custom/s3/transfer/internal/RequestDataSupplierAdapter.java
services-custom/s3-transfermanager/src/main/java/software/amazon/awssdk/custom/s3/transfer/internal/ResponseHeadersHandler.java
services-custom/s3-transfermanager/src/main/java/software/amazon/awssdk/custom/s3/transfer/internal/S3CrtDataPublisher.java
services-custom/s3-transfermanager/src/main/java/software/amazon/awssdk/custom/s3/transfer/internal/S3CrtUtils.java
services-custom/s3-transfermanager/src/test/java/software/amazon/awssdk/custom/s3/transfer/internal/CrtResponseDataConsumerAdapterTest.java
services-custom/s3-transfermanager/src/test/java/software/amazon/awssdk/custom/s3/transfer/internal/ResponseHeadersHandlerTest.java
services-custom/s3-transfermanager/src/test/java/software/amazon/awssdk/custom/s3/transfer/internal/S3CrtUtilsTest.java

- Add requestLogger and requestIdLogger
- Adjust logging level for some logs
- Add tests

Add requestLogger and requestIdLogger

---

metric-publishers/cloudwatch-metric-publisher/src/main/java/software/amazon/awssdk/metrics/publishers/cloudwatch/CloudWatchMetricPublisher.java

Fix javadocs

---

core/auth/src/main/java/software/amazon/awssdk/auth/credentials/InstanceProfileCredentialsProvider.java
core/auth/src/test/java/software/amazon/awssdk/auth/credentials/ContainerCredentialsProviderTest.java
core/auth/src/test/java/software/amazon/awssdk/auth/credentials/HttpCredentialsProviderTest.java
core/auth/src/test/java/software/amazon/awssdk/auth/credentials/InstanceProfileCredentialsProviderTest.java
core/regions/src/main/java/software/amazon/awssdk/regions/internal/util/EC2MetadataUtils.java
core/regions/src/main/java/software/amazon/awssdk/regions/internal/util/InstanceProviderTokenEndpointProvider.java
core/regions/src/main/java/software/amazon/awssdk/regions/util/ResourcesEndpointProvider.java
core/regions/src/test/java/software/amazon/awssdk/regions/util/HttpCredentialsUtilsTest.java
core/sdk-core/src/main/java/software/amazon/awssdk/core/client/builder/SdkDefaultClientBuilder.java
core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/http/pipeline/stages/ApplyUserAgentStage.java
core/sdk-core/src/main/java/software/amazon/awssdk/core/util/SdkUserAgent.java
core/sdk-core/src/test/java/software/amazon/awssdk/core/util/SdkUserAgentTest.java
services-custom/s3-transfermanager/src/main/java/software/amazon/awssdk/custom/s3/transfer/S3TransferManager.java
services-custom/s3-transfermanager/src/main/java/software/amazon/awssdk/custom/s3/transfer/internal/S3CrtUtils.java
services-custom/s3-transfermanager/src/test/java/software/amazon/awssdk/custom/s3/transfer/internal/S3CrtUtilsTest.java

Add user agent for transfer manager

Add user agent for transfer manager

---

services-custom/s3-transfer-manager/src/main/java/software/amazon/awssdk/transfer/s3/DownloadRequest.java
services-custom/s3-transfer-manager/src/main/java/software/amazon/awssdk/transfer/s3/S3ClientConfiguration.java
services-custom/s3-transfer-manager/src/main/java/software/amazon/awssdk/transfer/s3/UploadRequest.java
services-custom/s3-transfer-manager/src/main/java/software/amazon/awssdk/transfer/s3/internal/DefaultS3CrtAsyncClient.java
services-custom/s3-transfer-manager/src/main/java/software/amazon/awssdk/transfer/s3/internal/DefaultS3TransferManager.java
services-custom/s3-transfer-manager/src/main/java/software/amazon/awssdk/transfer/s3/internal/S3CrtAsyncClient.java
services-custom/s3-transfer-manager/src/main/java/software/amazon/awssdk/transfer/s3/internal/S3NativeClientConfiguration.java
services-custom/s3-transfer-manager/src/test/java/software/amazon/awssdk/transfer/s3/DefaultUploadRequestTest.java
services-custom/s3-transfer-manager/src/test/java/software/amazon/awssdk/transfer/s3/DownloadRequestTest.java
test/s3-benchmarks/src/main/java/software/amazon/awssdk/s3benchmarks/BaseTransferManagerBenchmark.java

`targetThroughputGbps` -> `targetThroughputInGbps`
`DownloadRequest.builder().apiRequest` -> `DownloadRequest.builder().getObjectRequest`
`UploadRequest.builder().apiRequest` → `UploadRequest.builder().putObjectRequest`

Various renaming

---

docs/LaunchChangelog.md

Added information on how to configure tcpKeepAlive to V1 to V2 Changelog.
Closes #1219.

Added tcpKeepAlive config info to Changelog

---

services-custom/s3-transfer-manager/README.md

Add README for S3TransferManager

Add README for S3TransferManager

---

services-custom/s3-transfer-manager/src/main/java/software/amazon/awssdk/transfer/s3/internal/CrtResponseDataConsumerAdapter.java
services-custom/s3-transfer-manager/src/main/java/software/amazon/awssdk/transfer/s3/internal/DefaultS3CrtAsyncClient.java
services-custom/s3-transfer-manager/src/test/java/software/amazon/awssdk/transfer/s3/internal/CrtResponseDataConsumerAdapterTest.java
services-custom/s3-transfer-manager/src/test/java/software/amazon/awssdk/transfer/s3/internal/DefaultS3CrtAsyncClientTest.java

Fixed an issue where the future gets stuck when upload fails

Fixed an issue where the future gets stuck when upload fails

---

services-custom/s3-transfer-manager/src/it/java/software/amazon/awssdk/transfer/s3/S3CrtClientPutObjectIntegrationTest.java
services-custom/s3-transfer-manager/src/it/java/software/amazon/awssdk/transfer/s3/S3CrtGetObjectIntegrationTest.java
services-custom/s3-transfer-manager/src/it/java/software/amazon/awssdk/transfer/s3/S3IntegrationTestBase.java
services-custom/s3-transfer-manager/src/it/java/software/amazon/awssdk/transfer/s3/S3TransferManagerDownloadIntegrationTest.java
services-custom/s3-transfer-manager/src/it/java/software/amazon/awssdk/transfer/s3/S3TransferManagerUploadIntegrationTest.java
services-custom/s3-transfer-manager/src/main/java/software/amazon/awssdk/transfer/s3/internal/S3NativeClientConfiguration.java
services-custom/s3-transfer-manager/src/test/java/software/amazon/awssdk/transfer/s3/internal/S3NativeClientConfigurationTest.java
test/stability-tests/pom.xml
test/stability-tests/src/it/java/software/amazon/awssdk/stability/tests/s3/S3CrtAsyncClientStabilityTest.java

Update s3 crt client tests to verify resources are closed properly
`CrtResource.waitForNoResources();` will time out if there are remaining resources after 1 min

Update s3 crt client tests to verify resources are closed properly

---

services-custom/s3-transfer-manager/src/it/java/software/amazon/awssdk/transfer/s3/CrtExceptionTransformationIntegrationTest.java
services-custom/s3-transfer-manager/src/main/java/software/amazon/awssdk/transfer/s3/internal/CrtErrorHandler.java
services-custom/s3-transfer-manager/src/main/java/software/amazon/awssdk/transfer/s3/internal/CrtResponseDataConsumerAdapter.java
services-custom/s3-transfer-manager/src/main/java/software/amazon/awssdk/transfer/s3/internal/DefaultS3CrtAsyncClient.java
services-custom/s3-transfer-manager/src/test/java/software/amazon/awssdk/transfer/s3/internal/CrtErrorHandlerTest.java
services-custom/s3-transfer-manager/src/test/java/software/amazon/awssdk/transfer/s3/internal/DefaultS3CrtAsyncClientTest.java
utils/src/main/java/software/amazon/awssdk/utils/CompletableFutureUtils.java

- Wrap CrtS3RuntimeException to S3ServiceException
- Currently CrtClient throws CrtS3RuntimeException whenever there is S3 Service side exceptions.
- We need to Wrap these exception indicating these are Service side exceptions
- Added Integration test
- Added Junits

Wrap CrtS3RuntimeException to S3ServiceException

---

docs/design/core/batch-utilities/DecisionLog.md

Updating design log for the Batch Utilities.
Updating decision log to keep track of design decisions made on 7/13/2021 meeting.
Just editing a markdown document, this does not affect any areas of code.
- [] Bug fix (non-breaking change which fixes an issue)
- [] New feature (non-breaking change which adds functionality)

Updating batch utilities decision log

---

services-custom/s3-transfer-manager/src/main/java/software/amazon/awssdk/transfer/s3/internal/RequestDataSupplierAdapter.java
services-custom/s3-transfer-manager/src/test/java/software/amazon/awssdk/transfer/s3/internal/RequestDataSupplierAdapterTest.java

If the data supplier gets the `onFinished` and `onException` signals, cancel the subscription.

Cancel sub on finish and exception

---

core/auth/src/test/java/software/amazon/awssdk/auth/credentials/internal/Ec2MetadataConfigProviderEndpointOverrideTest.java
core/auth/src/test/java/software/amazon/awssdk/auth/credentials/internal/Ec2MetadataConfigProviderEndpointResolutionTest.java

Avoids picking up values that were set by other tests using the same env
variables and system properties.
Also use AssertJ matchers in tests.
`mvn clean install` to make sure the tests pass.

Clear env vars, sys props before test

---

pom.xml

Release with the breaking change complete.

Undo codebuild bypass

---

pom.xml

Change for frauddetector has been released.

Undo frauddetector japicmp bypass

---

core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/http/pipeline/stages/utils/RetryableStageHelper.java
pom.xml
test/codegen-generated-classes-test/src/test/java/software/amazon/awssdk/services/retry/AsyncRetryHeaderTest.java
test/codegen-generated-classes-test/src/test/java/software/amazon/awssdk/services/retry/SyncRetryHeaderTest.java

Updated the test retry mode to STANDARD (from LEGACY) instead of updating the assertion from 3 attempts to 4.

Fix the maximum retry count send to the service (was off by 1)

---

core/auth-crt/src/main/java/software/amazon/awssdk/authcrt/signer/internal/CrtHttpRequestConverter.java
core/aws-core/src/main/java/software/amazon/awssdk/awscore/internal/AwsExecutionContextBuilder.java
core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/handler/BaseClientHandler.java

None of the TODOs should remain in the code base, since there is no proposed current or future actions associated with any of the comments.

Removes TODOs that aren't needed

---

.changes/next-release/feature-AWSSDKforJavav2-3dc34f6.json
pom.xml

Upgrade Netty to 4.1.68
~~Will run our test suites.~~
Integ tests and stability tests passed

Upgrade Netty to 4.1.68

---

buildspecs/release-to-maven.yml
buildspecs/resources/release-settings.xml

This reverts commit d87d6d72937ea995336963c0b2e0c450d0dec41c.
Here's the diff that was made to fix this:
```
-            awk 'BEGIN { var=ENVIRON["SDK_SIGNING_GPG_PASSPHRASE"] } { gsub("\\$SDK_SIGNING_GPG_PASSPHRASE", var, $0); print }' > \
+            awk 'BEGIN { var=ENVIRON["SDK_SIGNING_GPG_PASSPHRASE"] } { gsub("\\$SDK_SIGNING_GPG_PASSPHRASE", var, $0); print }' | \
```
Note: | vs >

Revert and fix "Revert "Update release-to-maven buildspec. (#2716)""

---

release-scripts/src/main/java/software/amazon/awssdk/release/PomTransformer.java
test/protocol-tests-core/src/main/java/software/amazon/awssdk/protocol/asserts/marshalling/XmlAsserts.java
test/sdk-benchmarks/src/main/java/software/amazon/awssdk/benchmark/utils/BenchmarkUtils.java

https://sonarcloud.io/project/issues?id=aws_aws-sdk-java-v2&resolved=false&types=VULNERABILITY

Fix some sonarcloud warnings.

---

core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/async/ByteArrayAsyncRequestBody.java
utils/src/main/java/software/amazon/awssdk/utils/http/SdkHttpUtils.java

https://sonarcloud.io/project/security_hotspots?id=aws_aws-sdk-java-v2

Fix more sonarcloud warnings.

---

bom-internal/pom.xml
codegen-lite-maven-plugin/pom.xml
codegen-maven-plugin/pom.xml
pom.xml

Update `plexus-utils` from  1.5.15 to 3.0.24

Update plexus-utils 1.5.15 -> 3.0.24

---

core/sdk-core/src/main/java/software/amazon/awssdk/core/SdkNumber.java

Fix typo in SdkNumber.java

---

.changes/next-release/bugfix-NettyNIOHTTPClient-457eb71.json
pom.xml

Bugfix native lib loading issues.
`mvn clean install -pl :netty-nio-client` on a Mac, which was failing to load with the previous version.

Update tcnative to 2.0.43.Final

---

docs/design/UseOfOptional.md

Update optional guideline

---

pom.xml

The release that contained these changes is complete so this is no longer needed.

Revert japicmp temp additions

---

pom.xml

Revert temporary japicmp exclusions.
Version that included these changes has been released.

Revert temp japicmp exclusions

---

services/transcribestreaming/src/it/java/software/amazon/awssdk/services/transcribestreaming/TranscribeStreamingIntegrationTest.java
test/stability-tests/src/it/java/software/amazon/awssdk/stability/tests/transcribestreaming/TranscribeStreamingStabilityTest.java

Temporarily disable TranscribeStreaming integration tests

---

.changes/next-release/bugfix-AmazonS3-3b61c48.json
services/s3/src/it/java/software/amazon/awssdk/services/s3/ListBucketsIntegrationTest.java
services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/endpoints/S3BucketEndpointResolver.java
services/s3/src/test/java/software/amazon/awssdk/services/s3/InvalidRegionTest.java

Fixed an issue that resulted in a NullPointerException when an invalid or global region was used on an S3 client.

---

.changes/next-release/feature-AWSSDKforJavav2-2bce622.json
pom.xml

Upgrade jackson libraries `2.12.3` -> `2.13.1`
Running all test suites now

Upgrade jackson libraries to 2.13.1

---

core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/async/FileAsyncRequestBody.java

The future got stuck (never complete) with the following error when I ran the test(compiled using JDK 11) with JDK 8.
```
Exception in thread "Thread-5" java.lang.NoSuchMethodError: java.nio.ByteBuffer.flip()Ljava/nio/ByteBuffer;
at software.amazon.awssdk.core.internal.async.FileAsyncRequestBody$FileSubscription$1.completed(FileAsyncRequestBody.java:264)
at software.amazon.awssdk.core.internal.async.FileAsyncRequestBody$FileSubscription$1.completed(FileAsyncRequestBody.java:260)
at sun.nio.ch.Invoker.invokeUnchecked(Invoker.java:126)
at sun.nio.ch.SimpleAsynchronousFileChannelImpl$2.run(SimpleAsynchronousFileChannelImpl.java:335)
```
Add try-catch in FileAsyncRequestBody to handle errors more elegantly

Add try-catch in FileAsyncRequestBody to handle errors more elegantly

---

http-clients/aws-crt-client/pom.xml
http-clients/aws-crt-client/src/it/java/software/amazon/awssdk/http/crt/AwsCrtClientCallingPatternIntegrationTest.java

- Presence of  unused package imports in AwsCrtClientCallingPatternIntegrationTest was affecting integ test.
- - Removed unused package imports cased from AwsCrtClientCallingPatternIntegrationTest
-

Removing unused libraries from AwsCrtClientCallingPatternIntegrationTest and update ThreadCount setting for test cases in aws-crt-client

---

services-custom/dynamodb-enhanced/src/main/java/software/amazon/awssdk/enhanced/dynamodb/model/CreateTableEnhancedRequest.java
services-custom/dynamodb-enhanced/src/test/java/software/amazon/awssdk/enhanced/dynamodb/model/CreateTableEnhancedRequestTest.java

Add consumer-builder methods to DDB-Enh CreateTableEnhancedRequest.

---

http-clients/aws-crt-client/pom.xml
http-clients/aws-crt-client/src/it/java/software/amazon/awssdk/http/crt/AwsCrtClientCallingPatternIntegrationTest.java

- Removing @Theory annotated test cases since that annotation is experimental. This was causing integ test case to be stuck while test were getting loaded.
- Also reverting the temp fix done as part of PR#2984
- Added timeout to detect any deadlocks.
- Added Parameterized test case.
- [x I confirm that this pull request can be released under the Apache 2 license

Replacing @Theory annotated test case to @Parameterized test case

---

services/s3/src/it/java/software/amazon/awssdk/services/s3/checksum/HttpChecksumIntegrationTest.java
services/s3/src/main/java/software/amazon/awssdk/services/s3/checksums/ChecksumsEnabledValidator.java
services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/handlers/GetObjectInterceptor.java
services/s3/src/test/java/software/amazon/awssdk/services/s3/S3SignerTest.java
services/s3/src/test/java/software/amazon/awssdk/services/s3/functionaltests/GetObjectWithChecksumTest.java
services/s3/src/test/java/software/amazon/awssdk/services/s3/utils/CaptureChecksumValidationInterceptor.java

- Custom changes for HttpChecksum validation for S3
- Older Validation of checksum needs to be skipped if new HttpChecksum is enabled
- Getobject interceptor for customization of Getobject responses with part number.
- Done builds internally and it passed

Custom changes for HttpChecksum validation for S3

---

pom.xml
services-custom/s3-transfer-manager/src/it/java/software/amazon/awssdk/transfer/s3/S3IntegrationTestBase.java

- Created crt-tests profile to make it easier to run all CRT related e2e tests.
- Updated the test to wait for a bucket to be created

Create crt-tests profile 

---

.changes/2.17.150.json

Remove earlier CRT bump in same release

---

.changes/next-release/feature-AWSSDKforJavav2-a830079.json
pom.xml

Upgrade jackson libraries `2.13.1` -> `2.13.2`
Running all test suites now

Upgrade jackson libraries to 2.13.2

---

.changes/next-release/feature-AmazonDynamoDBEnhancedClient-9a7e440.json
docs/design/services/dynamodb/high-level-library/README.md
docs/design/services/dynamodb/high-level-library/UpdateExpression.md
services-custom/dynamodb-enhanced/README.md

- Added design document for UpdateExpression to docs
- Modified enhanced client README
- Added Change note

Documentation update for UpdateExpression

---

pom.xml

- Adding  back the rds package in japicmp checks

Adding  back the rds package in japicmp checks

---

services-custom/s3-transfer-manager/src/main/java/software/amazon/awssdk/transfer/s3/internal/S3CrtResponseHandlerAdapter.java

Update TM to provide better error message

Update TM to provide better error message

---

.changes/next-release/feature-AWSSDKforJavav2-b03c8f5.json
pom.xml
services-custom/s3-transfer-manager/src/it/java/software/amazon/awssdk/transfer/s3/S3TransferManagerUploadIntegrationTest.java

Bump crt version to 0.16.7, which contains fixes for #3168 
Will run test suites

Bump crt version to 0.16.7

---

core/regions/src/main/java/software/amazon/awssdk/regions/internal/util/EC2MetadataUtils.java

Removed an extra comment in the Code
TODO  CleanUp is no longer required.

Removed Todo:CleanUp Comment

---

.github/workflows/codebuild-ci.yml
buildspecs/resources/ci.cloudformation.yml

Set up GH actions for CI

---

.github/workflows/codebuild-ci.yml
buildspecs/resources/ci.cloudformation.yml

Add sonarcloud build action

---

core/auth/src/main/java/software/amazon/awssdk/auth/credentials/DefaultCredentialsProvider.java

Create an create -> create an instance (x2)

DefaultCredentialsProvider: Minor create() documentation fix.

---

pom.xml

Bump crt to 0.16.15
~~Running test suites now~~ Tests passed

Bump crt to 0.16.15

---

bom/pom.xml
core/imds/pom.xml
core/imds/src/main/java/software/amazon/awssdk/imds/Ec2Metadata.java
core/imds/src/main/java/software/amazon/awssdk/imds/internal/DefaultEc2Metadata.java
core/imds/src/test/java/software/amazon/awssdk/imds/Ec2MetadataTest.java
core/pom.xml
pom.xml

Added the core/imds module along with Unit Tests.
This creates the module for the Ec2Metadata client.
- [ X] Local run of `mvn install` succeeds
- [ X] My code follows the code style of this project
- [ X] I have added tests to cover my changes
- [ X] All new and existing tests passed
- [ X] I confirm that this pull request can be released under the Apache 2 license

Create imds module structure. Added a unit test to check the flow

---

core/imds/pom.xml
core/imds/src/main/java/software/amazon/awssdk/imds/internal/DefaultEc2Metadata.java
core/imds/src/main/java/software/amazon/awssdk/imds/internal/EndpointMode.java
core/imds/src/main/java/software/amazon/awssdk/imds/internal/EndpointProvider.java
core/imds/src/main/resources/profileconfig/test-profiles.tst
core/imds/src/test/java/software/amazon/awssdk/imds/EndpointProviderTest.java

Endpoint resolution functionality added with parameterized tests
Endpoint resolution functionality for endpoint and endpoint mode.
Endpoint resolution functionality added with parameterized tests
Wrote parameterized tests for all test cases mentioned in the SEP and ran them in IDE

 Endpoint resolution functionality added with parameterized tests

---

services-custom/s3-transfer-manager/src/it/java/software/amazon/awssdk/transfer/s3/S3TransferManagerDownloadDirectoryIntegrationTest.java

Fix broken integ test

---

http-clients/aws-crt-client/src/main/java/software/amazon/awssdk/http/crt/AwsCrtAsyncHttpClient.java
test/sdk-benchmarks/pom.xml
test/sdk-benchmarks/src/main/java/software/amazon/awssdk/benchmark/BenchmarkRunner.java
test/sdk-benchmarks/src/main/java/software/amazon/awssdk/benchmark/apicall/httpclient/async/AwsCrtClientH2Benchmark.java
test/service-test-utils/pom.xml

adapt new interface and add benchmark for http2 crt client

---

test/sdk-benchmarks/src/main/java/software/amazon/awssdk/benchmark/utils/MockH2Server.java

fix h2 server

---

core/imds/pom.xml
core/imds/src/test/java/software/amazon/awssdk/imds/Ec2MetadataWithApacheClientTest.java

Added Apache Client tests
Test Pluggability Stretch Goal
Added Apache Client tests
Wrote tests and ran in IDE
- [ X] New feature (non-breaking change which adds functionality)
- [ X] I have read the [CONTRIBUTING](https://github.com/aws/aws-sdk-java-v2/blob/master/CONTRIBUTING.md) document
- [ X] Local run of `mvn install` succeeds
- [ X] My code follows the code style of this project
- [X ] I have added tests to cover my changes
- [X ] All new and existing tests passed
- [ X] I confirm that this pull request can be released under the Apache 2 license

 Added Apache Client tests

---

services-custom/s3-transfer-manager/src/main/java/software/amazon/awssdk/transfer/s3/S3TransferManager.java
services-custom/s3-transfer-manager/src/main/java/software/amazon/awssdk/transfer/s3/internal/model/DefaultFileUpload.java
services-custom/s3-transfer-manager/src/main/java/software/amazon/awssdk/transfer/s3/model/FileUpload.java
services-custom/s3-transfer-manager/src/main/java/software/amazon/awssdk/transfer/s3/model/ResumableFileDownload.java
services-custom/s3-transfer-manager/src/main/java/software/amazon/awssdk/transfer/s3/model/ResumableFileUpload.java
services-custom/s3-transfer-manager/src/main/java/software/amazon/awssdk/transfer/s3/model/ResumableTransfer.java
services-custom/s3-transfer-manager/src/test/java/software/amazon/awssdk/transfer/s3/model/ResumableFileUploadTest.java

Add POJO class for upload pause/resume

[Upload Pause/Resume Part1] Add POJO class

---

core/sdk-core/src/main/java/software/amazon/awssdk/core/rules/EndpointRuleset.java
core/sdk-core/src/main/java/software/amazon/awssdk/core/rules/Identifier.java
core/sdk-core/src/main/java/software/amazon/awssdk/core/rules/RuleEngine.java
core/sdk-core/src/main/java/software/amazon/awssdk/core/rules/Value.java

This ports the public interface of the rules engine from the internal package.

Add public interfaces for Rules evaluation

---

pom.xml

Bump CRT version

---

services-custom/dynamodb-enhanced/src/main/java/software/amazon/awssdk/enhanced/dynamodb/mapper/annotations/DynamoDbAttribute.java
services-custom/dynamodb-enhanced/src/main/java/software/amazon/awssdk/enhanced/dynamodb/mapper/annotations/DynamoDbBean.java
services-custom/dynamodb-enhanced/src/main/java/software/amazon/awssdk/enhanced/dynamodb/mapper/annotations/DynamoDbIgnore.java
services-custom/dynamodb-enhanced/src/main/java/software/amazon/awssdk/enhanced/dynamodb/mapper/annotations/DynamoDbImmutable.java
services-custom/dynamodb-enhanced/src/main/java/software/amazon/awssdk/enhanced/dynamodb/mapper/annotations/DynamoDbPartitionKey.java
services-custom/dynamodb-enhanced/src/main/java/software/amazon/awssdk/enhanced/dynamodb/mapper/annotations/DynamoDbSortKey.java

Add sample code for DDB enhanced client

Add sample code for DDB enhanced client

---

core/aws-core/src/main/java/software/amazon/awssdk/awscore/client/builder/AwsClientBuilder.java
core/aws-core/src/main/java/software/amazon/awssdk/awscore/presigner/SdkPresigner.java
services-custom/s3-transfer-manager/src/main/java/software/amazon/awssdk/transfer/s3/S3ClientConfiguration.java

It's accurate
Changed the javadoc to the correct property
- [ x] Bug fix (non-breaking change which fixes an issue)
- [ x] I have updated the Javadoc documentation accordingly
- [ x] I confirm that this pull request can be released under the Apache 2 license

Change aws.secretKey to aws.secretAccessKey

---

services/s3/src/it/java/software/amazon/awssdk/services/s3/crt/CrtExceptionTransformationIntegrationTest.java
services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/crt/S3CrtAsyncHttpClient.java
services/s3/src/test/java/software/amazon/awssdk/services/s3/internal/crt/S3CrtAsyncHttpClientTest.java

- Fix flexible checksum implementation
- Only validate response checksum if the operation supports it
- Only calculate request checksum  if the operation supports it
- Add more tests
- Change to use JUnit5 for testing
- Disable CrtExceptionTransformationIntegrationTest due to crt bug
- [] I have added a changelog entry. Adding a new entry must be accomplished by running the `scripts/new-change` script and following the instructions. Commit the new file created by the script in `.changes/next-release` with your changes.

Fix flexible checksum implementation

---

codegen/src/main/java/software/amazon/awssdk/codegen/poet/rules/EndpointProviderSpec.java

RuleEngine is not threadsafe, so create a new one per evaluation.

New RuleEngine per eval

---

.changes/next-release/bugfix-AWSSDKforJavav2-ff8f07d.json
core/sdk-core/src/main/java/software/amazon/awssdk/core/async/AsyncRequestBody.java
core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/util/Mimetype.java
core/sdk-core/src/main/java/software/amazon/awssdk/core/sync/RequestBody.java
core/sdk-core/src/test/java/software/amazon/awssdk/core/async/AsyncRequestBodyTest.java
core/sdk-core/src/test/java/software/amazon/awssdk/core/internal/async/ChecksumCalculatingAsyncRequestBodyTest.java
core/sdk-core/src/test/java/software/amazon/awssdk/core/sync/RequestBodyTest.java
test/codegen-generated-classes-test/src/test/java/software/amazon/awssdk/services/AsyncRequestBodyFlexibleChecksumInTrailerTest.java

https://github.com/aws/aws-sdk-java-v2/issues/3396

Update RequestBody/AsyncRequestBody.fromString(String, Charset) to use the provided charset in the content-type.

---

.changes/next-release/bugfix-S3TransferManager-f1c2208.json
services-custom/s3-transfer-manager/src/main/java/software/amazon/awssdk/transfer/s3/internal/DefaultS3TransferManager.java

Refactor handleException() and format changelog for S3 Transfer Manager bugfix
Fixing earlier PR - https://github.com/aws/aws-sdk-java-v2/pull/3433
Removed additional SdkException wrapping of exception, and correctly formatted changelog entry

Refactor handleException() and format changelog - Do not wrap errors - S3 Transfer Manager

---

services/s3/src/it/java/software/amazon/awssdk/services/s3/S3IntegrationTestBase.java
services/s3/src/it/java/software/amazon/awssdk/services/s3/crt/S3CrtClientCopyIntegrationTest.java
services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/crt/CopyRequestConversionUtils.java
services/s3/src/test/java/software/amazon/awssdk/services/s3/internal/crt/CopyRequestConversionUtilsTest.java

Fixed an issue where SSEC params were not correctly passed in copy operation
Fixed request conversion to correctly pass all params
Updated unit tests and added integ tests

Fixed an issue where SSEC params were not correctly passed in copy

---

core/sdk-core/src/main/java/software/amazon/awssdk/core/signer/NoOpSigner.java
pom.xml
test/codegen-generated-classes-test/src/test/java/software/amazon/awssdk/services/ProfileFileConfigurationTest.java

Mark NoOpSigner as a final class because it's not intended to be extended

Mark NoOpSigner as a final class

---

.changes/next-release/feature-AWSSDKforJavav2-f42484d.json
pom.xml

Upgrade jackson-databind to 2.13.4.2.
Addresses:
[CVE-2022-42003](https://github.com/advisories/GHSA-jjjh-jjxp-wpff)
[CVE-2022-42004](https://github.com/advisories/GHSA-rgv9-q543-rqg4)
local `mvn clean install`

Upgrade jackson-databind to 2.13.4.2

---

pom.xml

Re-include service modules for japicmp check

Re-include service modules for japicmp check

---

http-clients/aws-crt-client/pom.xml
http-clients/aws-crt-client/src/main/java/software/amazon/awssdk/http/crt/AwsCrtAsyncHttpClient.java
http-clients/aws-crt-client/src/main/java/software/amazon/awssdk/http/crt/internal/CrtRequestContext.java
http-clients/aws-crt-client/src/main/java/software/amazon/awssdk/http/crt/internal/CrtRequestExecutor.java
http-clients/aws-crt-client/src/main/java/software/amazon/awssdk/http/crt/internal/response/CrtResponseAdapter.java
http-clients/aws-crt-client/src/test/java/software/amazon/awssdk/http/crt/AwsCrtHttpClientSpiVerificationTest.java
http-clients/aws-crt-client/src/test/java/software/amazon/awssdk/http/crt/AwsCrtHttpClientWireMockTest.java
pom.xml

Continuation of #3482 
- Add client metrics for the CRT HTTP SPI implementation
- Wrap CRT HttpException with IOException
- Fix checkstyle errors and add tests
Note that the first two items have been reviewed as part of #3482 
Added unit tests and verified they were passing

Add client metrics for the CRT HTTP SPI implementation and wrap CRT HttpException with IOException

---

.changes/next-release/bugfix-AWSSDKforJavav2-73c904b.json
services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/handlers/CopySourceInterceptor.java
services/s3/src/test/java/software/amazon/awssdk/services/s3/internal/handlers/CopySourceInterceptorTest.java

Remove leading slash in header value for ARNs in CopySourceInterceptor

---

services/s3/src/test/java/software/amazon/awssdk/services/s3/internal/resource/OutpostAccessPointArnEndpointResolutionTest.java
test/protocol-tests/src/test/java/software/amazon/awssdk/protocol/tests/endpoint/EndpointTraitTest.java

Re-enable and fix tests

---

codegen/src/main/java/software/amazon/awssdk/codegen/poet/builder/BaseClientBuilderClass.java
codegen/src/test/resources/software/amazon/awssdk/codegen/poet/builder/test-query-client-builder-class.java
test/codegen-generated-classes-test/src/test/java/software/amazon/awssdk/services/protocolquery/MoveQueryParamsToBodyTest.java

Remove unintended reordering.
- Added new unit test.
- Running integ tests.

Move QueryParametersToBodyInterceptor to after custom interceptors

---

services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/crt/CopyObjectHelper.java

Minor refactoring in CopyObjectHelper, mainly around method extraction

Minor refactoring in CopyObjectHelper

---

test/s3-benchmarks/pom.xml
test/s3-benchmarks/src/main/java/software/amazon/awssdk/s3benchmarks/BaseTransferManagerBenchmark.java
test/s3-benchmarks/src/main/java/software/amazon/awssdk/s3benchmarks/BenchmarkRunner.java
test/s3-benchmarks/src/main/java/software/amazon/awssdk/s3benchmarks/BenchmarkUtils.java
test/s3-benchmarks/src/main/java/software/amazon/awssdk/s3benchmarks/TransferManagerBenchmark.java
test/s3-benchmarks/src/main/java/software/amazon/awssdk/s3benchmarks/TransferManagerBenchmarkConfig.java
test/s3-benchmarks/src/main/java/software/amazon/awssdk/s3benchmarks/TransferManagerCopyBenchmark.java
test/s3-benchmarks/src/main/java/software/amazon/awssdk/s3benchmarks/TransferManagerDownloadBenchmark.java
test/s3-benchmarks/src/main/java/software/amazon/awssdk/s3benchmarks/TransferManagerDownloadDirectoryBenchmark.java
test/s3-benchmarks/src/main/java/software/amazon/awssdk/s3benchmarks/TransferManagerUploadBenchmark.java
test/s3-benchmarks/src/main/java/software/amazon/awssdk/s3benchmarks/TransferManagerUploadDirectoryBenchmark.java
test/s3-benchmarks/src/main/java/software/amazon/awssdk/s3benchmarks/V1BaseTransferManagerBenchmark.java
test/s3-benchmarks/src/main/java/software/amazon/awssdk/s3benchmarks/V1TransferManagerCopyBenchmark.java
test/s3-benchmarks/src/main/java/software/amazon/awssdk/s3benchmarks/V1TransferManagerDownloadBenchmark.java
test/s3-benchmarks/src/main/java/software/amazon/awssdk/s3benchmarks/V1TransferManagerDownloadDirectoryBenchmark.java
test/s3-benchmarks/src/main/java/software/amazon/awssdk/s3benchmarks/V1TransferManagerUploadDirectoryBenchmark.java

Add benchmarks for copy, uploadDirectory and downloadDirectory
Tested on an EC2 instance

Add benchmarks for copy, uploadDirectory and downloadDirectory

---

pom.xml
services/s3/src/it/java/software/amazon/awssdk/services/s3/crt/CrtExceptionTransformationIntegrationTest.java
services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/crt/CrtChecksumUtils.java
services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/crt/S3CrtAsyncHttpClient.java
services/s3/src/test/java/software/amazon/awssdk/services/s3/internal/crt/CrtChecksumUtilsTest.java
services/s3/src/test/java/software/amazon/awssdk/services/s3/internal/crt/S3CrtAsyncHttpClientTest.java

Integrate with the latest CRT checksum API: https://github.com/awslabs/aws-crt-java/pull/546
Updated existing tests. Will run integ tests

Integrate with CRT checksum fix

---

services/cloudfront/src/main/java/software/amazon/awssdk/services/cloudfront/CloudFrontUtilities.java
services/cloudfront/src/test/java/software/amazon/awssdk/services/cloudfront/CloudFrontUtilitiesIntegrationTest.java
services/cloudfront/src/test/java/software/amazon/awssdk/services/cloudfront/CloudFrontUtilitiesTest.java
services/cloudfront/src/test/java/software/amazon/awssdk/services/cloudfront/cookie/SignedCookieTest.java
services/cloudfront/src/test/java/software/amazon/awssdk/services/cloudfront/url/SignedUrlTest.java

Adding code snippets and tests for CloudFrontUtilities
Snippets were missing, code coverage was low

CloudFront Signers Add Snippets and Tests

---

services-custom/s3-transfer-manager/src/main/java/software/amazon/awssdk/transfer/s3/S3TransferManager.java
services-custom/s3-transfer-manager/src/main/java/software/amazon/awssdk/transfer/s3/model/DownloadRequest.java
services-custom/s3-transfer-manager/src/test/java/software/amazon/awssdk/transfer/s3/internal/S3TransferManagerTest.java

Remove download consumer builder method because it's confusing to use.

Remove download consumer builder method

---

services-custom/s3-transfer-manager/src/main/java/software/amazon/awssdk/transfer/s3/internal/AsyncBufferingSubscriber.java
utils/src/main/java/software/amazon/awssdk/utils/async/ByteBufferStoringSubscriber.java
utils/src/main/java/software/amazon/awssdk/utils/async/DemandIgnoringSubscription.java
utils/src/main/java/software/amazon/awssdk/utils/async/StoringSubscriber.java

Minor refactoring: use `StoringSubscriber` in `AsyncBufferingSubscriber`

Use StoringSubscriber in AsyncBufferingSubscriber

---

pom.xml

Pin version for maven archetype plugin to 3.2.1
Making sure we are pinning versions for all plugins used

Pin version for maven archetype plugin

---

codegen/src/main/java/software/amazon/awssdk/codegen/poet/builder/BaseClientBuilderClass.java
codegen/src/test/resources/software/amazon/awssdk/codegen/poet/builder/test-client-builder-class.java
services/s3/src/main/java/software/amazon/awssdk/services/s3/S3Configuration.java
services/s3control/src/main/java/software/amazon/awssdk/services/s3control/S3ControlConfiguration.java

API updates for enabling passing `Supplier<ProfileFile>`
Modified test-client-builder-class.java

ProfileFile updates to BaseClientBuilderClass, other S3 classes

---

services-custom/dynamodb-enhanced/src/main/java/software/amazon/awssdk/enhanced/dynamodb/document/EnhancedDocument.java

- Added Document API similar to that of V1 [Item.java](https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-dynamodb/src/main/java/com/amazonaws/services/dynamodbv2/document/Item.java)
- Added new Interface to access DDB items as documents.
- Junit will be added in DefaultEnhancedDocument implementation PR.

Adding new Interface EnhancedDocument

---

http-clients/aws-crt-client/src/main/java/software/amazon/awssdk/http/crt/AwsCrtAsyncHttpClient.java

PR in support for CRT HTTP/1 GA - Surface Area Updates. This PR updates the documentation to specify that health checks are not enabled by default.
Updated Javadoc.
No new tests added.

CRT HTTP/1 GA - Surface Area Updates - Health Checks

---

.changes/next-release/feature-AWSSDKforJavav2-4a07ee0.json
.changes/next-release/feature-AWSSDKforJavav2-65b1d43.json

fix IMDS changelog

---

.changes/next-release/feature-AWSCRTbasedS3Client-dcd8e15.json
pom.xml
services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/crt/S3CrtAsyncHttpClient.java
services/s3/src/test/java/software/amazon/awssdk/services/s3/functionaltests/GetBucketPolicyFunctionalTest.java
services/s3/src/test/java/software/amazon/awssdk/services/s3/internal/crt/S3CrtAsyncHttpClientTest.java

Fixed an issue where port number was not added to host header.
Closes #3721 #3682 
Add port to the host number
Running integ tests and stability tests

Fixed an issue where port number was not added to host header.

---

.brazil.json

add the `imds` module to brazil package mapping

brazil package mapping for IMDS module

---

codegen/src/main/java/software/amazon/awssdk/codegen/poet/client/SyncClientClass.java
codegen/src/main/java/software/amazon/awssdk/codegen/poet/client/SyncClientInterface.java

Implementing TODO, make SyncClientClass similar to AsyncClientClass

Make SyncClientClass extend SyncClientInterface

---

.brazil.json

Bump JavaPoet to 1.13x

---

services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/crt/CopyObjectHelper.java
services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/crt/DefaultS3CrtAsyncClient.java
services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/crt/S3NativeClientConfiguration.java
services/s3/src/test/java/software/amazon/awssdk/services/s3/internal/crt/CopyObjectHelperTest.java

Fixed the thread safety issue with CRT based S3 client

Fixed the thread safety issue with CRT based S3 client

---

docs/design/README.md

Fix typo in docs/design/README.md
Fix typo in list of conventions in docs/design/README.md. There was an extra `*` where it just needed to be new line.
N/A

Fix typo in list of conventions in docs/design/README.md

---

.changes/2.20.31.json
CHANGELOG.md

- Missed out to enter change logs while committing the changes for Document API for DDB
- Manually added the change logs md and json file

Change logs for release of Document API for DDB items

---

services-custom/s3-transfer-manager/src/it/java/software/amazon/awssdk/transfer/s3/S3IntegrationTestBase.java

Bucket failed to delete because it still had buckets in it during a test run.

Add waiter when deleting objects to fix occasional flakiness

---

pom.xml

Bump crt version to 0.21.12

---

docs/design/core/sra-identity-auth/DecisionLog.md

Add decision log for items discussed in API surface area review of Identity changes.
Let me know if the style of the content is ok.  
Also where should this live. We can refactor later too, for now I've created it under `sra-identity-auth` directory. If there is more to add in this project, it can go there too.   
Also, I'm not sure if I got the attendees correct based on who all actually attended. And I wasn't sure if I should add Manuel/Steven who were observers mostly.
Add decision log for items discussed in API surface area review of Identity changes.

Add decision log for SRA Identity changes

---

.changes/2.20.62.json
CHANGELOG.md

update release notes

---

core/identity-spi/pom.xml
core/identity-spi/src/main/java/software/amazon/awssdk/identity/spi/IdentityProperty.java
core/identity-spi/src/main/java/software/amazon/awssdk/identity/spi/ResolveIdentityRequest.java
core/identity-spi/src/test/java/software/amazon/awssdk/identity/spi/IdentityPropertyTest.java

Some minor changes based on comments in similar changes in Signer interfaces in https://github.com/aws/aws-sdk-java-v2/pull/3967
* Made interfaces @SdkPublicApi
* Added test for equals and hashCode

Minor updates to identity-spi

---

core/http-auth-spi/src/main/java/software/amazon/awssdk/http/auth/spi/internal/DefaultHttpSignRequest.java
core/http-auth-spi/src/main/java/software/amazon/awssdk/http/auth/spi/internal/DefaultSignedHttpRequest.java

Minor updates to https://github.com/aws/aws-sdk-java-v2/pull/3967
* Changed className to be the interface name instead of internal default implementation.
* Removed commented out code.

Fixed toString in Default implementations

---

.changes/next-release/documentation-AWSSDKforJavav2-9718507.json
core/sdk-core/src/main/java/software/amazon/awssdk/core/SdkNumber.java
core/sdk-core/src/main/java/software/amazon/awssdk/core/async/AsyncRequestBody.java
core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/http/pipeline/stages/ApiCallAttemptTimeoutTrackingStage.java
core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/io/AwsChunkedEncodingInputStream.java
core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/retry/RateLimitingTokenBucket.java
core/sdk-core/src/main/java/software/amazon/awssdk/core/retry/backoff/BackoffStrategy.java
core/sdk-core/src/main/java/software/amazon/awssdk/core/traits/Trait.java

This change fixes all the current javadoc warnings in the sdk-core package. This was done to avoid introducing new ones in my upcoming changes.
Removed all the current warnings by fixing some incorrect uses of javadocs, such as
* Use of literal < instead of the `&lt;` entity.
* Add imports for unknown classes referenced in `{@link …}`
* Avoid using `@see` when the doc meant to use `{@link …}`
* Avoid links to private fields, instead rephrase the intent

Fix javadocs warnings in the sdk-core package

---

.github/workflows/stale-issue.yml

Update ancient issue time so that we are not automatically closing old GitHub issues.
N/A

chore: update ancient issue time

---

.changes/next-release/bugfix-AWSSDKforJavav2-b1d7d7f.json
pom.xml

Updates CRT version from 0.21.16 to 0.21.17

---

core/http-auth-spi/src/main/java/software/amazon/awssdk/http/auth/spi/internal/DefaultSignRequest.java
core/http-auth-spi/src/main/java/software/amazon/awssdk/http/auth/spi/internal/DefaultSignedRequest.java

Minor refactoring
Use Optional.ofNullable instead of explicit null check

Use Optional.ofNullable instead of null check

---

test/tests-coverage-reporting/pom.xml

Coverage in Sonar cloud for code in these modules was showing up as 0.
Add new modules to test coverage reporting

Add new modules to test coverage reporting

---

pom.xml

Upgrade CRT version to 0.22.2 , this version has updates for S3ClientOptions to pass AwsSigning Config

Upgrade CRT version

---

core/aws-core/src/main/java/software/amazon/awssdk/awscore/internal/AwsExecutionContextBuilder.java
core/aws-core/src/test/java/software/amazon/awssdk/awscore/internal/AwsExecutionContextBuilderTest.java

Support request level override of IdentityProvider.
When setting up the IDENTITY_PROVIDER_CONFIGURATION ExecutionAttribute, if the request provides an identity provider, it overrides the one configured on the client. Currently only AwsCredentialsIdentity can be specified as request override.

Use IdentityProvider from request override

---

.changes/next-release/bugfix-AWSSingleSignon-5691a92.json
services/sso/src/main/java/software/amazon/awssdk/services/sso/internal/SsoAccessTokenProvider.java
services/sso/src/test/java/software/amazon/awssdk/services/sso/internal/SsoAccessTokenProviderTest.java

Fix with  for  [Issue#3679](https://github.com/aws/aws-sdk-java-v2/issues/3679)
- Removed the addition of 15 minutes during expiration check.
Added Junits

Fixed issue with SsoAccessTokenProvider prematurely throwing ExpiredTokenException

---

core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/http/pipeline/stages/SigningStage.java

Fix bug introduced in https://github.com/aws/aws-sdk-java-v2/pull/4144 and other small changes to SRA SigningStage
* Fixed bug missing `!` in shouldSign
* Wrap with updateInterceptorContext
* Added metric for signing duration
Double checked that AwsCertficateManagerIntegrationTest succeeds.

Bugfix and other small changes to SRA SigningStage

---

core/aws-core/src/main/java/software/amazon/awssdk/awscore/AwsResponseMetadata.java
services/s3/src/it/java/software/amazon/awssdk/services/s3/crt/S3CrossRegionCrtIntegrationTest.java
services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/multipart/SdkPojoConversionUtils.java

- Handle null response metadata
- Remove TODO in `SdkPojoConversionUtils`

Handle null response metadata

---

core/http-auth-aws-crt/src/main/java/software/amazon/awssdk/http/auth/aws/crt/AwsCrtS3V4aAuthScheme.java
core/http-auth-aws-crt/src/main/java/software/amazon/awssdk/http/auth/aws/crt/AwsCrtV4aAuthScheme.java
core/http-auth/src/main/java/software/amazon/awssdk/http/auth/AwsV4AuthScheme.java
core/http-auth/src/main/java/software/amazon/awssdk/http/auth/BearerAuthScheme.java

Noticed copy-paste errors in original commit.
Note, the S3 specific CRT signer/scheme are planned to be deleted with signer changes @haydenbaker is working on, but this fixes it for both files that exist right now.
Fix the schemeId.
Fix the javadoc for S3 specific signer.

Fix sigv4a schemeId and javadocs in sigv4a AuthSchemes

---

codegen/src/main/java/software/amazon/awssdk/codegen/poet/auth/scheme/AuthSchemeInterceptorSpec.java
codegen/src/main/java/software/amazon/awssdk/codegen/poet/rules/EndpointResolverInterceptorSpec.java
codegen/src/test/java/software/amazon/awssdk/codegen/poet/auth/scheme/AuthSchemeSpecTest.java
codegen/src/test/resources/software/amazon/awssdk/codegen/poet/auth/scheme/query-endpoint-auth-params-with-allowlist-auth-scheme-interceptor.java
codegen/src/test/resources/software/amazon/awssdk/codegen/poet/auth/scheme/query-endpoint-auth-params-without-allowlist-auth-scheme-interceptor.java
codegen/src/test/resources/software/amazon/awssdk/codegen/poet/rules/endpoint-resolve-interceptor.java

Add support for auth scheme params based on endpoints params. For this use the already existing endpoint param class and logic to be populated and then just read the needed values into the auth scheme params.
* Added unit tests

Add support for auth scheme interceptor with endpoint params

---

core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/http/pipeline/stages/AsyncSigningStage.java
core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/http/pipeline/stages/SigningStage.java
core/sdk-core/src/test/java/software/amazon/awssdk/core/internal/http/pipeline/stages/AsyncSigningStageTest.java
core/sdk-core/src/test/java/software/amazon/awssdk/core/internal/http/pipeline/stages/SigningStageTest.java

When SRA logic was added to SigningStage and AsyncSigningStage, unit tests weren't added. No unit tests existed for these classes prior to SRA either.
Added unit tests for SigningStage and AsyncSigningStage.

Add unit tests for (Async)SigningStage

---

docs/LaunchChangelog.md

Update LaunchChangelog.md to add IAM Policy Builder

Update LaunchChangelog.md to add IAM Policy Builder

---

services-custom/dynamodb-enhanced/src/main/java/software/amazon/awssdk/enhanced/dynamodb/mapper/annotations/DynamoDbBean.java

Corrected a minor JavaDoc typo in the DynamoDbBean class.
- Type error reported by a user corrected in this PR

Corrected a minor JavaDoc typo in the DynamoDbBean class.

---

pom.xml

The SDK currently uses reactive-streams 1.0.3 which was licensed under CC0. 1.0.4 was re-licensed under MIT-0 which is an OSI approved license. CC0 is not universally considered acceptable due to patent issues, so I believe it would be better to declare a transitive dependency on 1.0.4.
There appear to be no other changes in the the interfaces of note.
https://github.com/reactive-streams/reactive-streams-jvm/issues/438
https://github.com/reactive-streams/reactive-streams-jvm/blob/v1.0.4/RELEASE-NOTES.md#version-104-released-on-2022-05-20
Minor dependency API library version bump.
Assume existing regression tests will be sufficient; and have run them.

Bump reactive-streams from 1.0.3 to 1.0.4

---

codegen/src/main/java/software/amazon/awssdk/codegen/poet/auth/scheme/AuthSchemeParamsSpec.java
core/auth/src/main/java/software/amazon/awssdk/auth/token/credentials/internal/TokenUtils.java
core/aws-core/src/main/java/software/amazon/awssdk/awscore/internal/AwsExecutionContextBuilder.java
core/sdk-core/src/main/java/software/amazon/awssdk/core/SelectedAuthScheme.java

Was touching AwsExecutionContextBuilder in another PR and noticed some TODOs that could be removed and updated with the sra-identity-and-auth tag. Saw a few other ones to update and remove, so went ahead with a few. It's not exhaustive, so don't try to review for completeness, just some baby step towards cleanup.
* Cleanup TODOs in AwsExecutionContextBuilder.
* Remove some TODO in codegen by fixing code to reference class that now exists instead of hardcoding string.
* Tag TODO for sra-identity-and-auth in some places.
* Remove TODO for SelectedAuthScheme location as it seems appropriate.

Some TODO cleanup and removal

---

bom/pom.xml

Add `auth-crt` to the bom file.

Add auth-crt to bom

---

core/arns/src/main/java/software/amazon/awssdk/arns/ArnResource.java
core/arns/src/test/java/software/amazon/awssdk/arns/ArnResourceTest.java
core/arns/src/test/java/software/amazon/awssdk/arns/ArnTest.java
services/s3/src/test/java/software/amazon/awssdk/services/s3/internal/resource/S3ArnUtilsTest.java

Reverts aws/aws-sdk-java-v2#4317

Revert "Modify ArnResource to handle more variants of resources"

---

codegen/src/main/java/software/amazon/awssdk/codegen/poet/auth/scheme/AuthSchemeSpecUtils.java
codegen/src/test/resources/software/amazon/awssdk/codegen/poet/builder/test-bearer-auth-client-builder-class.java
codegen/src/test/resources/software/amazon/awssdk/codegen/poet/builder/test-client-builder-class.java
codegen/src/test/resources/software/amazon/awssdk/codegen/poet/builder/test-client-builder-internal-defaults-class.java
codegen/src/test/resources/software/amazon/awssdk/codegen/poet/builder/test-composed-sync-default-client-builder.java

This change adds the `NoAuthAuthScheme` to the list of available auth schemes to all services.

Configure client with NoAuthAuthScheme by default

---

core/http-auth-aws-crt/src/main/java/software/amazon/awssdk/http/auth/aws/crt/AwsCrtS3V4aAuthScheme.java
core/http-auth-aws-crt/src/main/java/software/amazon/awssdk/http/auth/aws/crt/AwsCrtS3V4aHttpSigner.java
core/http-auth-aws-crt/src/main/java/software/amazon/awssdk/http/auth/aws/crt/AwsCrtV4aAuthScheme.java
core/http-auth-aws-crt/src/main/java/software/amazon/awssdk/http/auth/aws/crt/AwsCrtV4aHttpSigner.java
core/http-auth-aws-crt/src/main/java/software/amazon/awssdk/http/auth/aws/crt/internal/signer/DefaultAwsCrtV4aHttpSigner.java
core/http-auth-aws/src/main/java/software/amazon/awssdk/http/auth/aws/AwsS3V4HttpSigner.java
core/http-auth-aws/src/main/java/software/amazon/awssdk/http/auth/aws/AwsV4aAuthScheme.java
core/http-auth-aws/src/main/java/software/amazon/awssdk/http/auth/aws/AwsV4aHttpSigner.java
core/http-auth-aws/src/main/java/software/amazon/awssdk/http/auth/aws/internal/signer/SignerLoader.java
services/s3/pom.xml
services/s3/src/test/java/software/amazon/awssdk/services/s3/S3PresignerTest.java
services/s3/src/test/java/software/amazon/awssdk/services/s3/functionaltests/MultiRegionAccessPointSigningFunctionalTest.java
services/s3/src/test/java/software/amazon/awssdk/services/s3/internal/resource/MultiRegionAccessPointEndpointResolutionTest.java

Wire up the signer loader to enable sigv4a using the CRT.

Wire up the CRT signer loader

---

core/aws-core/src/main/java/software/amazon/awssdk/awscore/internal/authcontext/AwsCredentialsAuthorizationStrategy.java
core/aws-core/src/main/java/software/amazon/awssdk/awscore/internal/authcontext/TokenAuthorizationStrategy.java
core/http-auth-aws/src/main/java/software/amazon/awssdk/http/auth/aws/internal/chunkedencoding/ChunkedEncodedInputStream.java
core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/http/pipeline/stages/SigningStage.java

Add a marker to identity and auth TODOs

---

pom.xml

Fix test coverage
- Upgrade jacoco to 0.8.10 
- Upgrade surefire plugin
- Remove unnecessary argLine

Upgrade jacoco to 0.8.10

---

.changes/next-release/feature-AWSSDKforJavav2-b858043.json
pom.xml
third-party/third-party-jackson-core/pom.xml

- Kicked off integ tests in addition to normal GitHub checks.

Update Jackson to 2.15.2

---

core/http-auth-aws/src/main/java/software/amazon/awssdk/http/auth/aws/internal/chunkedencoding/ChunkedEncodedInputStream.java
core/http-auth-aws/src/main/java/software/amazon/awssdk/http/auth/aws/internal/signer/AwsChunkedV4PayloadSigner.java
core/http-auth-aws/src/main/java/software/amazon/awssdk/http/auth/aws/internal/signer/DefaultAwsV4HttpSigner.java
core/http-auth-aws/src/main/java/software/amazon/awssdk/http/auth/aws/util/SignerUtils.java
core/http-auth-aws/src/test/java/software/amazon/awssdk/http/auth/aws/internal/signer/AwsChunkedV4PayloadSignerTest.java

Similar to https://github.com/aws/aws-sdk-java-v2/pull/4362 but more were added recently in a parallel merge.
Add label

Add label to SRA identity and auth TODOs

---

buildspecs/update-master-from-release.yml

CodeBuild fails silently when `mvn versions:set` fails with connection reset.
Recent PR to use `trap` command failed during CodeBuild run.
Check return status code of `mvn versions:set` instead of using `trap`
Ran test CodeBuild project

Check return status code of mvn versions:set

---

services/eventbridge/pom.xml

While checking whether eventbridge integ test works, noticed that we needed to update the crt signer dependency from auth-crt (old Signer) to http-auth-aws-crt (new HttpSigner).
Updated dependency
`mvn clean install -Dskip.unit.tests -P integration-tests -Dfindbugs.skip -Dcheckstyle.skip -T1C -pl :eventbridge` - ran successfully after this change.

Add http-auth-aws-crt test dependency for eventbridge integ test

---

codegen/src/main/java/software/amazon/awssdk/codegen/poet/model/ModelBuilderSpecs.java
codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/alltypesrequest.java
codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/deprecatedrenamerequest.java
codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/eventstreamoperationrequest.java
codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/eventstreamoperationwithonlyinputrequest.java
codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/existencechecknamingrequest.java
codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/nestedcontainersrequest.java
codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/operationwithdeprecatedmemberrequest.java
codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/operationwithnoinputoroutputrequest.java
codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/queryparameteroperationrequest.java
codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/sharedstream/getrandompersonrequest.java
codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/sharedstream/streambirthsrequest.java
codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/sharedstream/streambirthsresponse.java
codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/sharedstream/streamdeathsrequest.java
codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/sharedstream/streamdeathsresponse.java
codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/streaminginputoperationrequest.java
codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/streamingoutputoperationrequest.java
codegen/src/test/resources/software/amazon/awssdk/codegen/poet/model/xmlnamespace/testxmlnamespacerequest.java
core/aws-core/src/main/java/software/amazon/awssdk/awscore/AwsRequest.java
core/aws-core/src/test/java/software/amazon/awssdk/awscore/client/builder/DefaultAwsClientBuilderTest.java
core/sdk-core/src/main/java/software/amazon/awssdk/core/SdkPlugin.java
core/sdk-core/src/main/java/software/amazon/awssdk/core/SdkRequest.java
core/sdk-core/src/main/java/software/amazon/awssdk/core/client/builder/SdkClientBuilder.java
core/sdk-core/src/main/java/software/amazon/awssdk/core/client/builder/SdkDefaultClientBuilder.java
core/sdk-core/src/test/java/software/amazon/awssdk/core/client/builder/DefaultClientBuilderTest.java

Adds support for adding plugins that allows customers to customize the SDK, both at client build time and at request execution time.

Add SdkPlugin interface and use

---

services/transcribestreaming/pom.xml

Add missing dependency for transcribestreaming

Add missing depenendcy for transcribestreaming

---

core/http-auth-aws/src/main/java/software/amazon/awssdk/http/auth/aws/internal/signer/util/OptionalDependencyLoaderUtil.java

Noticed the incorrect error message while testing
Fixed order of parameters

Fix order of parameters in exception message

---

test/codegen-generated-classes-test/src/test/java/software/amazon/awssdk/services/SraIdentityResolutionTest.java
test/codegen-generated-classes-test/src/test/java/software/amazon/awssdk/services/SraIdentityResolutionUsingPluginsTest.java

Follow up change to [#4506](https://github.com/aws/aws-sdk-java-v2/pull/4506), that changes the tests to assert that the exception thrown by the execution is what we expect instead of just ignoring the exception.

Update the tests to assert that we get the expected exception

---

services/eventbridge/src/it/java/software/amazon/awssdk/services/eventbridge/EventBridgeMultiRegionEndpointIntegrationTest.java

Previously, the test would wait for the endpoint state to be active, but this did not mean that the SDK could resolve the DNS entry for the endpoint. Now, we wait for the DNS entry to be resolvable. This won't appreciably affect the time it takes to run the test, but can avoid false positive failures when the test is run on a new account for the first time.

Make EventBridgeMultiRegionEndpointIntegrationTest reliable on the first run.

---

services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/crt/DefaultS3CrtAsyncClient.java

In CRT based S3 client, how checksum is handled depends on the type of the requests. For putObject and getObject, it's done in CRT. For other requests, it's done in `HttpChecksumStage`. Since in the new SRA path, checksum is done as part of the signer, we need to explicitly disable SRA in CRT based S3 client in order to continue to use `HttpChecksumStage` for checksumming for requests other than putObject and getObject.
Disable SRA in CRT S3 client
`ChecksumIntegrationTest` passed locally

Disable SRA in CRT S3 client

---

core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/http/pipeline/stages/AsyncSigningStage.java
core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/http/pipeline/stages/SigningStage.java

To help debugging, useful to know if we are doing SRA signing or not.
Add log debug statement in (Async)SigningStage.

Add log debug to signing stages to know approach

---

buildspecs/release-to-maven.yml

…
- Updating build spec for release to Maven since the build was failing with python lib issues
- This is a temporary fix until we get gpg working on latest images or solve the python build issue

Updating build spec for release to Maven since the build was failing with python lib issues

---

core/aws-core/src/main/java/software/amazon/awssdk/awscore/internal/authcontext/AwsCredentialsAuthorizationStrategy.java
core/aws-core/src/main/java/software/amazon/awssdk/awscore/internal/authcontext/TokenAuthorizationStrategy.java
core/sdk-core/src/main/java/software/amazon/awssdk/core/SelectedAuthScheme.java

Use joinLikeSync for better exception handling for join
* Change to joinLikeSync. Added TODO to move async clients to not need joins.
* Also removed some irrelevant TODOs.

Use joinLikeSync instead of join (and TODO cleanup)

---

.changes/next-release/feature-AWSSDKforJavav2-691394d.json

Change log added for https://github.com/aws/aws-sdk-java-v2/pull/4467

Added changelog for PR #4467

---

buildspecs/release-javadoc.yml

missing comma in list of excluded modules

fix typo in release-javadoc.yml

---

pom.xml

With move to SRA Identity & Auth, most clients won't need a dependency on auth module. But cannot remove it from services/pom.xml until all services have switched.
Right now the feature/master/sra-identity-auth-testing branch fails because of this - https://github.com/aws/aws-sdk-java-v2/actions/runs/6512780114/job/17691098594?pr=4478. 
```
2023-10-13T20:41:15.3125267Z [WARNING] Unused declared dependencies found:
2023-10-13T20:41:15.3126264Z [WARNING]    software.amazon.awssdk:auth:jar:2.21.1-SNAPSHOT:compile
```
Testing the fix in this branch first, but we'll want to merge this to `master` before we start switching services to useSraAuth=true in `master`.
Add ignore for the auth module.
Tested locally that one package that fails before this change, now passes.

Ignore auth maven-dependency-plugin failure

---

test/protocol-tests/pom.xml

Fixing build failure in `feature/master/sra-identity-auth-testing` branch 
```
2023-10-13T22:36:00.5257881Z [WARNING] Used undeclared dependencies found:
2023-10-13T22:36:00.5258939Z [WARNING]    software.amazon.awssdk:http-auth:jar:2.21.1-SNAPSHOT:compile
```
With useSraAuth=true, http-auth is required for NoAuthAuthScheme. This failure is happening now because failOnWarning=true is now merged into the branch.
Added missing dependency.
protocol-tests builds locally now.

Specify protocol-tests->http-auth dependency

---

http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/internal/ChannelDiagnostics.java
http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/internal/InUseTrackingChannelPoolListener.java
http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/internal/ResponseHandler.java
http-clients/netty-nio-client/src/test/java/software/amazon/awssdk/http/nio/netty/internal/ChannelDiagnosticsTest.java

- Track the latest duration the channel spent idling
- Track the number of responses received on the channel
Additional information for debugging

Implement additional ChannelDiagnostics information

---

buildspecs/release-javadoc.yml

Currently, links to Javadoc service API operation pages return 403 during the daily javadoc build
Copy `crosslink_redirect.html` to the source directory first before running `sync`

Copy crosslink redirect to source directory before running sync

---

core/http-auth-aws/src/main/java/software/amazon/awssdk/http/auth/aws/internal/signer/DefaultAwsV4HttpSigner.java
core/http-auth-aws/src/main/java/software/amazon/awssdk/http/auth/aws/internal/signer/V4CanonicalRequest.java
core/http-auth-aws/src/main/java/software/amazon/awssdk/http/auth/aws/internal/signer/checksums/Md5Checksum.java
core/http-auth-aws/src/main/java/software/amazon/awssdk/http/auth/aws/internal/signer/checksums/Sha1Checksum.java
core/http-auth-aws/src/main/java/software/amazon/awssdk/http/auth/aws/internal/signer/checksums/Sha256Checksum.java
core/http-auth-aws/src/main/java/software/amazon/awssdk/http/auth/aws/internal/signer/util/ChecksumUtil.java
core/http-auth-aws/src/main/java/software/amazon/awssdk/http/auth/aws/internal/signer/util/DigestAlgorithm.java
core/http-auth-aws/src/main/java/software/amazon/awssdk/http/auth/aws/internal/signer/util/SignerUtils.java

Slightly improve the performance for the SRA I&A new code paths.
* Use a new `DigestAlgorithm` class to keep thread local instances of the `MessageDigest` instances.
* Similar to the previous implementation [`CanonicalRequest`](https://github.com/aws/aws-sdk-java-v2/blob/6edd247202a87d8370a2f50ec078d69856ec7170/core/auth/src/main/java/software/amazon/awssdk/auth/signer/internal/AbstractAws4Signer.java#L485-L488), compute some of the fields in `V4CanonicalRequest` lazily since those might not be needed and some might be computed twice

Minor performance improvements

---

pom.xml

Bump CRT to 0.27.7

---

codegen/src/main/java/software/amazon/awssdk/codegen/poet/rules/RuleSetCreationSpec.java
codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/c2j/query/endpoint-rule-set.json
codegen/src/test/resources/software/amazon/awssdk/codegen/poet/rules/endpoint-provider-class.java

Bug fix.
Fix an issue where the code generator generates invalid code when multiple auth schemes are declared for an endpoint.

Fix incorrect authSchemes creation

---

codegen/src/main/resources/software/amazon/awssdk/codegen/rules/AuthSchemeUtils.java.resource
core/http-auth-aws/src/main/java/software/amazon/awssdk/http/auth/aws/internal/signer/util/SignerUtils.java

Remove an outdated TODO, the performance testing was already done and the use of a thread local digest already in place.
For the `AuthSchemeUtils` remove the TODO and make the class `@SdkInternalApi`.

Remove outdated TODOs

---

.changes/2.21.14.json
CHANGELOG.md

Update changelog entry

---

services/ec2/src/main/java/software/amazon/awssdk/services/ec2/transform/internal/GeneratePreSignUrlInterceptor.java
test/codegen-generated-classes-test/src/test/java/software/amazon/awssdk/services/HttpChecksumInHeaderTest.java
test/codegen-generated-classes-test/src/test/java/software/amazon/awssdk/services/endpointproviders/EndpointInterceptorTests.java

Remove TODO's for useSraAuth true

---

buildspecs/release-to-maven.yml
pom.xml

Updated release to maven build spec to run on standard5.0 code build images
- Updated pom.xml to support gpg signing in ubuntu instances of codebuild  with images of standard5.0
- updated gpg import with batch
- Tested on codebuild with signing  and releasinfgat local repositories.

Updated release to maven build spec to run on standard5.0 code build images

---

pom.xml

Update pom.xml to re-include sqs for japicmp check

Update pom.xml to re-include sqs for japicmp check

---

docs/LaunchChangelog.md
services-custom/s3-transfer-manager/src/main/java/software/amazon/awssdk/transfer/s3/S3TransferManager.java

- Update transfer manager doc
- Update launch changelog
- fix formatting and fix stale doc

Update transfer manager doc and launch changelog

---

.changes/next-release/feature-AWSSDKforJavav2Codegen-1b31942.json
codegen/src/main/java/software/amazon/awssdk/codegen/AddMetadata.java
codegen/src/main/java/software/amazon/awssdk/codegen/model/config/customization/CustomPackageName.java
codegen/src/main/java/software/amazon/awssdk/codegen/model/config/customization/CustomizationConfig.java
codegen/src/main/java/software/amazon/awssdk/codegen/naming/DefaultNamingStrategy.java
codegen/src/test/java/software/amazon/awssdk/codegen/poet/ClientTestModels.java
codegen/src/test/java/software/amazon/awssdk/codegen/poet/client/AsyncClientClassTest.java
codegen/src/test/java/software/amazon/awssdk/codegen/poet/client/SyncClientClassTest.java
codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/c2j/custompackage/customization.config
codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/c2j/custompackage/service-2.json
codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/c2j/custompackageprefix/customization.config
codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/c2j/custompackageprefix/service-2.json
codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/c2j/custompackagesuffix/customization.config
codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/c2j/custompackagesuffix/service-2.json
codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/test-custompackage-async.java
codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/test-custompackage-sync.java
codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/test-custompackageprefix-async.java
codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/test-custompackageprefix-sync.java
codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/test-custompackagesuffix-async.java
codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/test-custompackagesuffix-sync.java

Allow codegen users to customize package prefix and suffix
- prefix: by default it's `software.amazon.awssdk.services`
- suffix: by default it's the same as service ID, eg: `[packagePrefix].s3`
Example:
```
{
"packageName": {
"prefix": "foo.bar",
"suffix": "helloworld"
}
}
```

Support package name customization

---

.idea/inspectionProfiles/AWS_Java_SDK_2_0.xml
http-clients/aws-crt-client/src/main/java/software/amazon/awssdk/http/crt/AwsCrtAsyncHttpClient.java
http-clients/aws-crt-client/src/main/java/software/amazon/awssdk/http/crt/AwsCrtHttpClient.java
http-clients/aws-crt-client/src/main/java/software/amazon/awssdk/http/crt/AwsCrtHttpClientBase.java
http-clients/aws-crt-client/src/main/java/software/amazon/awssdk/http/crt/internal/CrtRequestExecutor.java
http-clients/aws-crt-client/src/main/java/software/amazon/awssdk/http/crt/internal/CrtUtils.java
http-clients/aws-crt-client/src/main/java/software/amazon/awssdk/http/crt/internal/request/CrtRequestAdapter.java
http-clients/aws-crt-client/src/main/java/software/amazon/awssdk/http/crt/internal/response/CrtResponseAdapter.java
http-clients/aws-crt-client/src/main/resources/META-INF/services/software.amazon.awssdk.http.SdkHttpService
http-clients/url-connection-client/src/test/java/software/amazon/awssdk/http/urlconnection/UrlConnectionHttpClientWireMockTest.java
http-clients/url-connection-client/src/test/resources/jetty-logging.properties
http-clients/url-connection-client/src/test/resources/log4j2.properties
test/http-client-tests/src/main/java/software/amazon/awssdk/http/SdkHttpClientTestSuite.java
test/stability-tests/src/it/java/software/amazon/awssdk/stability/tests/s3/S3CrtClientStabilityTest.java

Various refactoring:
- Update javadoc
- Fix retry 
- Fix checkstyle errors and bugs

Various refactoring on CRT Sync HTTP Client

---

core/auth/src/main/java/software/amazon/awssdk/auth/credentials/AwsBasicCredentials.java
core/auth/src/main/java/software/amazon/awssdk/auth/credentials/AwsSessionCredentials.java
core/auth/src/main/java/software/amazon/awssdk/auth/credentials/CredentialUtils.java
core/auth/src/main/java/software/amazon/awssdk/auth/credentials/ProcessCredentialsProvider.java
core/auth/src/main/java/software/amazon/awssdk/auth/credentials/internal/ProfileCredentialsUtils.java
core/auth/src/main/java/software/amazon/awssdk/auth/credentials/internal/SystemSettingsCredentialsProvider.java
core/auth/src/test/java/software/amazon/awssdk/auth/credentials/CredentialUtilsTest.java
core/auth/src/test/java/software/amazon/awssdk/auth/credentials/ProcessCredentialsProviderTest.java
core/auth/src/test/java/software/amazon/awssdk/auth/credentials/ProfileCredentialsProviderTest.java
core/auth/src/test/java/software/amazon/awssdk/auth/credentials/StaticCredentialsProviderTest.java
core/auth/src/test/java/software/amazon/awssdk/auth/credentials/SystemSettingsCredentialsProviderTest.java
core/auth/src/test/java/software/amazon/awssdk/auth/credentials/internal/AwsSessionCredentialsTest.java
core/auth/src/test/java/software/amazon/awssdk/auth/credentials/internal/ProfileCredentialsUtilsTest.java
core/auth/src/test/resources/resources/process/linux-credentials-script.sh
core/auth/src/test/resources/resources/process/windows-credentials-script.bat
core/http-auth-aws/src/main/java/software/amazon/awssdk/http/auth/aws/internal/signer/util/CredentialUtils.java
core/identity-spi/src/main/java/software/amazon/awssdk/identity/spi/AwsCredentialsIdentity.java
core/identity-spi/src/main/java/software/amazon/awssdk/identity/spi/AwsSessionCredentialsIdentity.java
core/identity-spi/src/main/java/software/amazon/awssdk/identity/spi/internal/DefaultAwsCredentialsIdentity.java
core/identity-spi/src/main/java/software/amazon/awssdk/identity/spi/internal/DefaultAwsSessionCredentialsIdentity.java
core/identity-spi/src/test/java/software/amazon/awssdk/identity/spi/AwsCredentialsIdentityTest.java
core/identity-spi/src/test/java/software/amazon/awssdk/identity/spi/AwsSessionCredentialsIdentityTest.java
core/profiles/src/main/java/software/amazon/awssdk/profiles/ProfileProperty.java
core/sdk-core/src/main/java/software/amazon/awssdk/core/SdkSystemSetting.java
pom.xml

Add `credentialScope` to profile, process, and environment variable credential providers
Add credentialScope `ProfileProperty` and `SdkSystemSetting`

Add credentialScope to SDK credential providers

---

codegen/src/main/java/software/amazon/awssdk/codegen/model/rules/endpoints/BuiltInParameter.java
codegen/src/main/java/software/amazon/awssdk/codegen/poet/rules/EndpointProviderSpec.java
codegen/src/main/java/software/amazon/awssdk/codegen/poet/rules/EndpointProviderTestSpec.java
codegen/src/main/java/software/amazon/awssdk/codegen/poet/rules/EndpointResolverInterceptorSpec.java
codegen/src/main/java/software/amazon/awssdk/codegen/poet/rules/EndpointRulesSpecUtils.java
codegen/src/test/resources/software/amazon/awssdk/codegen/poet/auth/scheme/query-endpoint-auth-params-auth-scheme-default-params-without-allowlist.java
codegen/src/test/resources/software/amazon/awssdk/codegen/poet/auth/scheme/query-endpoint-auth-params-auth-scheme-endpoint-provider-without-allowlist.java
codegen/src/test/resources/software/amazon/awssdk/codegen/poet/auth/scheme/query-endpoint-auth-params-auth-scheme-params-without-allowlist.java
codegen/src/test/resources/software/amazon/awssdk/codegen/poet/auth/scheme/query-endpoint-auth-params-without-allowlist-auth-scheme-interceptor.java
codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/c2j/query/endpoint-rule-set.json
codegen/src/test/resources/software/amazon/awssdk/codegen/poet/rules/endpoint-parameters.java
codegen/src/test/resources/software/amazon/awssdk/codegen/poet/rules/endpoint-provider-class.java
codegen/src/test/resources/software/amazon/awssdk/codegen/poet/rules/endpoint-resolve-interceptor-preSra.java
codegen/src/test/resources/software/amazon/awssdk/codegen/poet/rules/endpoint-resolve-interceptor.java

Update codegen to add `credentialScope` to endpoint params
Add credentialScope `BuiltInParameter`

Add credentialScope to endpoint params

---

services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/handlers/EnableTrailingChecksumInterceptor.java

Fix javadocs typo, should be GetObjectRequest instead of PutObjectRequest

Fix EnableTrailingChecksumInterceptor javadocs

---

test/codegen-generated-classes-test/src/test/java/software/amazon/awssdk/services/CredentialScopeTest.java

Test that `credentialScope` configuration precedence is honored in the following order: request -> client -> env var -> profile

Credential Scope Configuration Test

---

core/sdk-core/src/main/java/software/amazon/awssdk/core/interceptor/Context.java

Update javadocs to clarify casting to access full request/response on FailedExecution

Update javadocs for FailedExecution.Context

---

core/http-auth-aws/src/main/java/software/amazon/awssdk/http/auth/aws/internal/signer/Checksummer.java

Adding note in Checksummer regarding `X_AMZ_CONTENT_SHA256` header in SRA requests

Add note to Checksummer

---

services/s3/src/it/java/software/amazon/awssdk/services/s3/S3PresignerIntegrationTest.java
services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/signing/DefaultS3Presigner.java

`NORMALIZE_PATH` and `DOUBLE_URL_ENCODE` should be set to false for S3 presigning
https://github.com/aws/aws-sdk-java-v2/issues/4819
Set properties to false in `DefaultS3Presigner`
added integ test

Set S3Presigner normalizePath and doubleUrlEncode to false

---

codegen/src/main/java/software/amazon/awssdk/codegen/docs/AsyncOperationDocProvider.java
codegen/src/main/java/software/amazon/awssdk/codegen/docs/OperationDocProvider.java
codegen/src/main/java/software/amazon/awssdk/codegen/docs/SyncOperationDocProvider.java
codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/test-json-async-client-interface.java
codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/test-json-client-interface.java

Currently, javadocs for Paginator-style methods include description of the original method, which may have conflicting information and confuse users
Example: https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/services/cloudwatchlogs/CloudWatchLogsClient.html#filterLogEventsPaginator(software.amazon.awssdk.services.cloudwatchlogs.model.FilterLogEventsRequest)
Remove original method description from Paginator-style  methods
updated codegenerated test files

Update javadocs for paginator style methods

---

services/glacier/src/main/resources/codegen-resources/customization.config
services/s3/src/main/resources/codegen-resources/customization.config
services/s3control/src/main/resources/codegen-resources/customization.config

Enable compiled endpoint rules for s3, s3control and glacier

---

services/s3/src/test/java/software/amazon/awssdk/services/s3/internal/crossregion/S3CrossRegionAsyncClientTest.java
services/s3/src/test/java/software/amazon/awssdk/services/s3/internal/crossregion/S3CrossRegionSyncClientTest.java

After PR #4838 Endpoint Resolution is done twice ,thus updated the test case.
Update test case where endpoint resolution is checked for atleast once

Update test case where endpoint resolution is checked for atleast once

---

.github/workflows/closed-issue-message.yml
.github/workflows/stale-issue.yml

We received customer feedback that
1. Our closed issue message is too loud and too full of emoji
2. The issue staleness timings are too strict, especially over weekends and holidays
* Make the wording nicer (slightly)
* Double the time to stale issues.
None
None

Minor GitHub workflow changes

---

pom.xml

Update japicmp config to add new modules and re-enable it for modules that were previously commented out

Update japicmp config

---

aws-sdk-java/pom.xml

update aws-sdk-java pom to add imds and dyanmodb-enhanced

update aws-sdk-java pom to add imds and dyanmodb-enhanced

---

services/accessanalyzer/src/main/resources/codegen-resources/customization.config
services/account/src/main/resources/codegen-resources/customization.config
services/acm/src/main/resources/codegen-resources/customization.config
services/acmpca/src/main/resources/codegen-resources/customization.config
services/alexaforbusiness/src/main/resources/codegen-resources/customization.config
services/amp/src/main/resources/codegen-resources/customization.config
services/amplify/src/main/resources/codegen-resources/customization.config
services/amplifybackend/src/main/resources/codegen-resources/customization.config
services/amplifyuibuilder/src/main/resources/codegen-resources/customization.config
services/apigatewaymanagementapi/src/main/resources/codegen-resources/customization.config
services/appconfig/src/main/resources/codegen-resources/customization.config
services/appfabric/src/main/resources/codegen-resources/customization.config
services/appflow/src/main/resources/codegen-resources/customization.config
services/appintegrations/src/main/resources/codegen-resources/customization.config
services/applicationautoscaling/src/main/resources/codegen-resources/customization.config
services/applicationcostprofiler/src/main/resources/codegen-resources/customization.config
services/applicationdiscovery/src/main/resources/codegen-resources/customization.config
services/applicationinsights/src/main/resources/codegen-resources/customization.config
services/eks/src/main/resources/codegen-resources/customization.config
services/emrcontainers/src/main/resources/codegen-resources/customization.config
services/iot/src/main/resources/codegen-resources/customization.config
services/marketplacemetering/src/main/resources/codegen-resources/customization.config
services/paymentcryptography/src/main/resources/codegen-resources/customization.config
services/securityhub/src/main/resources/codegen-resources/customization.config

Correcting earlier change to 2 spaces

Changing indentation of config files to 4 spaces

---

.changes/next-release/feature-AmazonCloudFrontKeyValueStore-3a3d55e.json
services/cloudfrontkeyvaluestore/src/main/resources/codegen-resources/customization.config

Switching CloudFront KeyValueStore onto the new SRA (Smithy Reference Architecture) identity and auth logic that was released in v2.21.0.
Added the flag to use SRA auth, and also added the flag to use endpoint based auth scheme resolution because this service's APIs use Sigv4a. 
Ran local integration test calling the `listKeys` API (with `auth-crt` as a test dependency):
1. Without SRA, the call is successful
2. When the SRA auth flag `useSraAuth=true` is added, the test fails with a credentials error 
3. When the `enableEndpointAuthSchemeParams=true` is added, the test passes; the client now has an endpoint auth scheme resolver that gets the sigv4a scheme information from the rules.

Activating SRA for Amazon CloudFront KeyValueStore

---

services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/plugins/S3OverrideAuthSchemePropertiesPlugin.java

Fix a typo in the java doc, the example shows how to enable payload signing instead of showing how to disable chunk encoding.

Correct the javadoc for the main class

---

services/cloudfront/src/test/java/software/amazon/awssdk/services/cloudfront/CloudFrontUtilitiesIntegrationTest.java

Make it clear that the resource is not to be deleted.
- Rerun the integ test with updated prefix

Update CloudFront test resource name

---

services/accessanalyzer/src/main/resources/codegen-resources/customization.config
services/account/src/main/resources/codegen-resources/customization.config
services/acm/src/main/resources/codegen-resources/customization.config
services/acmpca/src/main/resources/codegen-resources/customization.config
services/alexaforbusiness/src/main/resources/codegen-resources/customization.config
services/amp/src/main/resources/codegen-resources/customization.config
services/amplify/src/main/resources/codegen-resources/customization.config
services/amplifybackend/src/main/resources/codegen-resources/customization.config
services/amplifyuibuilder/src/main/resources/codegen-resources/customization.config
services/apigatewaymanagementapi/src/main/resources/codegen-resources/customization.config
services/appconfig/src/main/resources/codegen-resources/customization.config
services/appfabric/src/main/resources/codegen-resources/customization.config
services/appflow/src/main/resources/codegen-resources/customization.config
services/appintegrations/src/main/resources/codegen-resources/customization.config
services/applicationautoscaling/src/main/resources/codegen-resources/customization.config
services/applicationcostprofiler/src/main/resources/codegen-resources/customization.config
services/applicationdiscovery/src/main/resources/codegen-resources/customization.config
services/applicationinsights/src/main/resources/codegen-resources/customization.config
services/cloudfrontkeyvaluestore/src/main/resources/codegen-resources/customization.config
services/cognitoidentityprovider/src/main/resources/codegen-resources/customization.config
services/eks/src/main/resources/codegen-resources/customization.config
services/emrcontainers/src/main/resources/codegen-resources/customization.config
services/iam/src/main/resources/codegen-resources/customization.config
services/iot/src/main/resources/codegen-resources/customization.config
services/marketplacemetering/src/main/resources/codegen-resources/customization.config
services/paymentcryptography/src/main/resources/codegen-resources/customization.config
services/securityhub/src/main/resources/codegen-resources/customization.config

Services included are:
- accessanalyzer
- account
- acm
- acmpca
- alexaforbusiness
- amp
- amplify
- amplifybackend
- amplifyuibuilder
- apigatewaymanagementapi
- appconfig
- appfabric
- appflow
- appintegrations
- applicationautoscaling
- applicationcostprofiler
- applicationdiscovery
- applicationinsights
- cloudfrontkeyvaluestore
- cognitoidentityprovider
- eks
- emrcontainers
- iam
- iot
- marketplacemetering
- paymentcryptography
- securityhub

Enable compiled endpoint rules for the third wave

---

.all-contributorsrc
README.md

Updating with contributions from the last quarter or so.

Update All Contributors hall

---

.github/workflows/codebuild-ci.yml

Fix codebuild-ci.yml to trigger CI automatically for PRs

Fix codebuild-ci.yml

---

.changes/next-release/bugfix-AWSSDKforJavav2-9c2ba2d.json
pom.xml

upgrade to latest Netty version (4.1.107.Final)
align with latest Netty release
https://netty.io/news/2024/02/13/4-1-107-Final.html
updated pom.xml
tests execute in CI build
- [ x ] Bug fix (non-breaking change which fixes an issue)
- [ x ] I confirm that this pull request can be released under the Apache 2 license

upgrade to netty 4.1.107.Final

---

.changes/next-release/bugfix-AWSSDKforJavav2-6454991.json
core/sdk-core/src/test/java/software/amazon/awssdk/core/internal/http/timers/HttpClientApiCallTimeoutTest.java
http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/internal/http2/Http2PingHandler.java
http-clients/netty-nio-client/src/test/java/software/amazon/awssdk/http/nio/netty/fault/PingTimeoutTest.java
http-clients/netty-nio-client/src/test/java/software/amazon/awssdk/http/nio/netty/fault/ServerNotRespondingTest.java
http-clients/netty-nio-client/src/test/java/software/amazon/awssdk/http/nio/netty/internal/http2/Http2PingHandlerTest.java

This reverts commit 1fa1d652939ab95920a92f8fb4c0086362b6a9a9.
Reverting this to run more tests.

Revert "Improve Http2 ping timeout logic (#4027)"

---

.gitignore

Ignore .vscode dir

---

services/ssooidc/src/main/resources/codegen-resources/customization.config

Allow underscore in name for ssooidc, reference `V1276055184`

Allow underscore in name for ssooidc

---

migration-tool/src/main/java/software/amazon/awssdk/migration/internal/recipe/NewV1ClassToBuilder.java
migration-tool/src/test/java/software/amazon/awssdk/migration/recipe/NewV1ModelClassToV2Test.java

Preserve prefix when moving from new to builder

---

bom/pom.xml

Fixes https://github.com/aws/aws-sdk-java-v2/issues/5116.

Add endpoints-spi to bom

---

migration-tool/src/main/java/software/amazon/awssdk/migration/internal/recipe/NewClassToBuilder.java
migration-tool/src/main/java/software/amazon/awssdk/migration/internal/recipe/V1SetterToV2.java
migration-tool/src/main/java/software/amazon/awssdk/migration/internal/utils/SdkTypeUtils.java
migration-tool/src/main/java/software/amazon/awssdk/migration/recipe/ChangeSdkType.java
migration-tool/src/main/java/software/amazon/awssdk/migration/recipe/NewClassToBuilderPattern.java
migration-tool/src/main/java/software/amazon/awssdk/migration/recipe/NewClassToStaticFactory.java
migration-tool/src/main/resources/META-INF/rewrite/change-auth-types.yml
migration-tool/src/main/resources/META-INF/rewrite/change-sdk-core-types.yml
migration-tool/src/main/resources/META-INF/rewrite/java-sdk-v1-to-v2.yml
migration-tool/src/test/java/software/amazon/awssdk/migration/internal/utils/SdkTypeUtilsTest.java
migration-tool/src/test/java/software/amazon/awssdk/migration/recipe/ChangeAuthTypesTest.java
migration-tool/src/test/java/software/amazon/awssdk/migration/recipe/CredentialsDependencyFactory.java
migration-tool/src/test/java/software/amazon/awssdk/migration/recipe/NewV1ClassToStaticFactoryTest.java
migration-tool/src/test/java/software/amazon/awssdk/migration/recipe/NewV1ClientClassToV2Test.java
migration-tool/src/test/java/software/amazon/awssdk/migration/recipe/NewV1ModelClassToV2Test.java
test/migration-tool-tests/src/test/resources/after/src/main/java/foo/bar/Application.java
test/migration-tool-tests/src/test/resources/after/src/main/java/foo/bar/CredentialsDependencyFactory.java
test/migration-tool-tests/src/test/resources/before/src/main/java/foo/bar/Application.java
test/migration-tool-tests/src/test/resources/before/src/main/java/foo/bar/CredentialsDependencyFactory.java
test/migration-tool-tests/src/test/resources/run-test

- Support code transformation for credentials related classes.
- Add NewClassToStaticFactory reciipe to convert objects creating using constructor to static factory method
`AWSCredentials credentials = new BasicAWSCredentials("foo", "bar");`
to
`AwsCredentials credentials = AwsBasicCredentials.create("foo", "bar");`
- Refactor NewClassToBuilderPattern to support client classes as well as core classes:
`DefaultAWSCredentialsProviderChain credentials = new DefaultAWSCredentialsProviderChain();` 
to
`DefaultCredentialsProvider credentials = DefaultCredentialsProvider.builder().build();`
Added tests

Support code transformation for credentials related classes.

---

.changes/next-release/bugfix-AWSSDKforJavav2Bundle-7dd8ce2.json
bundle-sdk/pom.xml

Fix #5108 
- Exclude dependencies that are already in the bundle from `aws-s3-accessgrants-java-plugin`
- Relocate third-party libraries that were missed last time
Ran the tests added in https://github.com/aws/aws-sdk-java-v2/pull/5187

Fix bundle shading

---

.brazil.json
bom/pom.xml
pom.xml

Add retry packages to brazil

---

http-clients/netty-nio-client/src/test/java/software/amazon/awssdk/http/nio/netty/fault/ServerConnectivityErrorMessageTest.java

I commented this test since it fails frequently on my computer and forgot to uncomment it.

Uncomment test left commented by mistake

---

pom.xml

Bump CRT version to 0.29.23 
https://github.com/awslabs/aws-crt-java/releases/tag/v0.29.23

Bump CRT version to 0.29.23

---

migration-tool/src/main/java/software/amazon/awssdk/migration/internal/utils/SdkTypeUtils.java

fix a NullPointerException in SdkTypeUtils.java
add logic to defend again null value

fix NPE in SdkTypeUtils

---

.changes/next-release/bugfix-AWSSDKforJavav2-b23bd48.json
pom.xml

upgrade to latest Netty version (4.1.111.Final)
align with latest Netty release
https://netty.io/news/2024/06/11/4-1-111-Final.html
updated pom.xml
tests execute in CI build
- [ x ] Bug fix (non-breaking change which fixes an issue)
- [ x ] I confirm that this pull request can be released under the Apache 2 license

upgrade netty version to 4.1.111.Final

---

migration-tool/src/main/java/software/amazon/awssdk/migration/recipe/ChangeSdkType.java

Fix NPE in ChangeSdkType

---

.changes/next-release/bugfix-AWSSDKforJavav2-65f766c.json
core/retries-spi/src/main/java/software/amazon/awssdk/retries/api/RetryStrategy.java
core/retries-spi/src/test/java/software/amazon/awssdk/retries/api/RetryStrategyBuilderTest.java
core/retries/src/it/java/software/amazon/awssdk/retries/internal/AdaptiveRetryStrategyResourceConstrainedTest.java
core/retries/src/main/java/software/amazon/awssdk/retries/AdaptiveRetryStrategy.java
core/retries/src/main/java/software/amazon/awssdk/retries/DefaultRetryStrategy.java
core/retries/src/main/java/software/amazon/awssdk/retries/StandardRetryStrategy.java
core/retries/src/main/java/software/amazon/awssdk/retries/internal/BaseRetryStrategy.java
core/retries/src/main/java/software/amazon/awssdk/retries/internal/DefaultAdaptiveRetryStrategy.java
core/retries/src/main/java/software/amazon/awssdk/retries/internal/DefaultLegacyRetryStrategy.java
core/retries/src/main/java/software/amazon/awssdk/retries/internal/DefaultStandardRetryStrategy.java
core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/retry/RetryPolicyAdapter.java
core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/retry/SdkDefaultRetryStrategy.java
test/codegen-generated-classes-test/src/test/java/software/amazon/awssdk/services/retry/RetryThrottledBehaviorTest.java

Add throttling backoff to all retry strategies

---

test/migration-tool-tests/src/test/resources/after/pom.xml
test/migration-tool-tests/src/test/resources/run-test

Remove hard-coded version in migration-tool-tests test script

Remove hard-coded version in migration-tool-tests test script

---

migration-tool/src/main/java/software/amazon/awssdk/migration/recipe/V1BuilderVariationsToV2Builder.java
migration-tool/src/test/java/software/amazon/awssdk/migration/recipe/V1BuilderVariationsToV2BuilderTest.java

v1 `defaultClient()` to v2 `create()`

Transform defaultClient to create

---

.brazil.json

Add package mapping for rewrite-java-dependencies

Add package mapping for rewrite-java-dependencies

---

.brazil.json

Fix package import for real, this time.

Fix package import

---

test/v2-migration-tests/src/test/resources/maven/after/src/main/java/foo/bar/Application.java
v2-migration/src/main/resources/META-INF/rewrite/s3-getobject-constructor-to-fluent.yml
v2-migration/src/main/resources/META-INF/rewrite/s3-putobject-constructor-to-fluent.yml
v2-migration/src/test/java/software/amazon/awssdk/v2migration/ConstructorToFluentTest.java
v2-migration/src/test/java/software/amazon/awssdk/v2migration/NumberToDurationTest.java
v2-migration/src/test/java/software/amazon/awssdk/v2migration/S3StreamingResponseToV2Test.java

Update packages and files naming
Updated end-to-end test

Fix package and file naming

---

bom/pom.xml
codegen/pom.xml
core/protocols/pom.xml
core/protocols/smithy-rpcv2-protocol/pom.xml
test/protocol-tests/pom.xml
test/tests-coverage-reporting/pom.xml

Add new module for the upcoming implementation of the Smithy RPCv2 protocol.

Add RPCv2 module

---

README.md

[IGNORE] Testing

---

README.md

[IGNORE] Testing2

---

v2-migration/src/main/resources/META-INF/rewrite/change-auth-types.yml
v2-migration/src/main/resources/META-INF/rewrite/change-config-types.yml

Update recipe display name

---

.changes/next-release/feature-AWSSDKforJavav2MigrationTool-48d11da.json
test/v2-migration-tests/pom.xml
test/v2-migration-tests/src/test/resources/run-test
v2-migration/pom.xml

Append PREVIEW to the migration tool version and add changelog entry

Append PREVIEW to the migration tool version and add changelog entry

---

v2-migration/src/main/java/software/amazon/awssdk/v2migration/internal/utils/NamingConversionUtils.java
v2-migration/src/test/java/software/amazon/awssdk/v2migration/internal/utils/NamingConversionUtilsTest.java

Fix v2 migration package mapping for services that have different package names. It's based on https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/migration-steps.html

Fix v2 migration package mapping

---

services-custom/dynamodb-enhanced/src/main/java/software/amazon/awssdk/enhanced/dynamodb/mapper/annotations/DynamoDbPreserveEmptyObject.java

Migrate to snippet to avoid HTML formatting issues

---

codegen/src/main/java/software/amazon/awssdk/codegen/poet/builder/BaseClientBuilderClass.java
codegen/src/test/resources/software/amazon/awssdk/codegen/poet/builder/sra/test-client-builder-class.java
codegen/src/test/resources/software/amazon/awssdk/codegen/poet/builder/test-client-builder-class.java
test/codegen-generated-classes-test/src/main/java/software/amazon/awssdk/services/protocolrestjsonwithconfig/ProtocolRestJsonWithConfigConfiguration.java
test/codegen-generated-classes-test/src/main/resources/codegen-resources/serviceconfig/customization.config
test/codegen-generated-classes-test/src/main/resources/codegen-resources/serviceconfig/endpoint-rule-set.json
test/codegen-generated-classes-test/src/main/resources/codegen-resources/serviceconfig/endpoint-tests.json
test/codegen-generated-classes-test/src/main/resources/codegen-resources/serviceconfig/paginators-1.json
test/codegen-generated-classes-test/src/main/resources/codegen-resources/serviceconfig/service-2.json
test/codegen-generated-classes-test/src/test/java/software/amazon/awssdk/services/DualstackEndpointTest.java

Fix an issue in S3 and S3 Control client's dualstack config resolution where the default value in S3Configuration and S3ControlConfiguration prevents the client from correctly falling back to the environment variable/system property value when the dualstack configuration is not set on the client or on configuration object.
- Updated unit tests

Fix S3/Control dualstack config resolution

---

services/sqs/src/test/java/software/amazon/awssdk/services/sqs/batchmanager/ReceiveBatchesMockTest.java

Update ReceiveBatchesMockTest to remove delayed response for a  MOCK test  where mocked SQS responses are expected ASAP
- Update ReceiveBatchesMockTest to remove delayed response for a  MOCK test  where mocked SQS responses are expected ASAP
-The default RecieveWaitTime is 50ms , and if we even give low values of Mocked SQS delay as 10 sometimes the Mock Server take 50+ms which cause MinReieveWaitTime to expire
- To avoid this we need to remove the delayed response and just stub the response.

Update ReceiveBatchesMockTest to remove delayed response for a Test

---

pom.xml

Bump CRT version to 0.31.1

---

core/protocols/aws-cbor-protocol/pom.xml

Use proper test scope for the test-utils dependency

---

.changes/2.25.x/2.25.37.json
.changes/2.28.4.json

Update changelogs for Account ID endpoints

Update changelogs for Account ID endpoints

---

services/dynamodb/src/main/resources/codegen-resources/customization.config
services/dynamodb/src/main/resources/codegen-resources/dynamodb/customization.config
services/dynamodb/src/main/resources/codegen-resources/dynamodbstreams/customization.config

Enable compiled endpoint rules for DynamoDB

---

core/protocols/aws-json-protocol/src/main/java/software/amazon/awssdk/protocols/json/internal/unmarshall/JsonProtocolUnmarshaller.java

Return the correct parser if present in the builder

---

core/aws-core/src/main/java/software/amazon/awssdk/awscore/client/builder/AwsDefaultClientBuilder.java

Add a todo regarding around the short term workaround

---

.changes/next-release/bugfix-AWSSDKforJavav2-5bce774.json
pom.xml

upgrade to latest version of Netty
https://netty.io/news/2024/10/01/4-1-114-Final.html
https://mvnrepository.com/artifact/io.netty/netty-bom/4.1.114.Final

upgrade to netty 4.1.114.Final

---

.changes/2.29.0.json
.changes/next-release/deprecation-AWSSDKforJavav2-eb641b5.json
.changes/next-release/feature-AWSSDKforJavav2-3676574.json
CHANGELOG.md

Fix 2.29.0 changelog entries

---

codegen/src/main/java/software/amazon/awssdk/codegen/model/service/OperationContextParam.java
codegen/src/main/java/software/amazon/awssdk/codegen/poet/rules/EndpointResolverInterceptorSpec.java
codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/c2j/query/customization-with-duplicate-operationcontextparams.config
codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/c2j/query/customization-with-incorrectName-operationcontextparams.config
codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/c2j/query/customization.config
codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/c2j/query/service-2.json
services/s3/src/main/resources/codegen-resources/customization.config
test/codegen-generated-classes-test/src/main/resources/codegen-resources/customresponsemetadata/customization.config
test/codegen-generated-classes-test/src/main/resources/codegen-resources/endpointproviders/customization.config

Per the spec, should be `path` instead of `value`
Renamed to `path` in `OperationContextParam` and updated `EndpointResolverInterceptorSpec`
updated codegen test files

Update value to path for operation context params

---

services/dynamodb/src/test/java/software/amazon/awssdk/services/dynamodb/PaginatorInUserAgentTest.java

Add assertion to test case

---

pom.xml

Bump CRT to 0.33.3

---

test/v2-migration-tests/src/test/java/software/amazon/awssdk/v2migrationtests/MavenProjectTest.java
test/v2-migration-tests/src/test/resources/software/amazon/awssdk/v2migrationtests/gradle/before/init.gradle
test/v2-migration-tests/src/test/resources/software/amazon/awssdk/v2migrationtests/maven/after/src/main/java/foo/bar/SdkClientsDependencyFactory.java
v2-migration/pom.xml

Bumping to latest OpenRewrite
https://github.com/openrewrite/rewrite-recipe-bom/releases/tag/v2.23.0
In response to https://github.com/openrewrite/rewrite-gradle-plugin/issues/347

Bump OpenRewrite

---

core/retries/src/main/java/software/amazon/awssdk/retries/internal/BaseRetryStrategy.java

This change copies the collections from the builder instead of keeping a reference to the collection in the builder.
See [this comment](https://github.com/aws/aws-sdk-java-v2/pull/5724/files#r1874250516).

Copy collections to avoid false sharing

---

feature.metadata

Remove unnecessary file

---

test/sdk-benchmarks/pom.xml
test/sdk-benchmarks/src/main/java/software/amazon/awssdk/benchmark/BenchmarkRunner.java
test/sdk-benchmarks/src/main/java/software/amazon/awssdk/benchmark/apicall/MetricsEnabledBenchmark.java
test/sdk-benchmarks/src/main/java/software/amazon/awssdk/benchmark/metricpublisher/emf/EmfMetricPublisherBenchmark.java

Added the Benchmark Test class for the emfMetricPublisher
Added EmfMetricPublisherBenchmark class, which extended MetricsEnabledBenchmark class.
Changed the enableMetrics method in MetricsEnabledBenchmark from private to protected
The benchmark tests are manually ran:
MetricsEnabledBenchmark: # Run complete. Total time: 00:18:49
EmfMetricPublisherBenchmark: # Run complete. Total time: 00:18:55

emf metric publisher performance test

---

test/v2-migration-tests/src/test/resources/software/amazon/awssdk/v2migrationtests/gradle/after/src/main/java/gradletest/foo/bar/Library.java
test/v2-migration-tests/src/test/resources/software/amazon/awssdk/v2migrationtests/maven/after/src/main/java/foo/bar/Application.java
test/v2-migration-tests/src/test/resources/software/amazon/awssdk/v2migrationtests/maven/after/src/main/java/foo/bar/Enums.java
test/v2-migration-tests/src/test/resources/software/amazon/awssdk/v2migrationtests/maven/after/src/main/java/foo/bar/S3.java
test/v2-migration-tests/src/test/resources/software/amazon/awssdk/v2migrationtests/maven/after/src/main/java/foo/bar/SdkClientsDependencyFactory.java
test/v2-migration-tests/src/test/resources/software/amazon/awssdk/v2migrationtests/maven/before/src/main/java/foo/bar/S3.java
v2-migration/src/main/java/software/amazon/awssdk/v2migration/ChangeSdkType.java
v2-migration/src/main/java/software/amazon/awssdk/v2migration/HttpSettingsToHttpClient.java
v2-migration/src/main/java/software/amazon/awssdk/v2migration/NewClassToBuilder.java
v2-migration/src/main/java/software/amazon/awssdk/v2migration/V1BuilderVariationsToV2Builder.java
v2-migration/src/main/java/software/amazon/awssdk/v2migration/V1SetterToV2.java
v2-migration/src/main/java/software/amazon/awssdk/v2migration/internal/utils/SdkTypeUtils.java
v2-migration/src/main/resources/META-INF/rewrite/change-config-types.yml
v2-migration/src/main/resources/META-INF/rewrite/s3-methods-constructor-to-fluent.yml
v2-migration/src/test/java/software/amazon/awssdk/v2migration/ChangeConfigTypesTest.java
v2-migration/src/test/java/software/amazon/awssdk/v2migration/ChangeSdkTypeTest.java
v2-migration/src/test/java/software/amazon/awssdk/v2migration/EnumCasingToV2Test.java
v2-migration/src/test/java/software/amazon/awssdk/v2migration/EnumGettersToV2Test.java
v2-migration/src/test/java/software/amazon/awssdk/v2migration/V1BuilderVariationsToV2BuilderTest.java
v2-migration/src/test/java/software/amazon/awssdk/v2migration/V1GetterToV2Test.java
v2-migration/src/test/java/software/amazon/awssdk/v2migration/internal/utils/SdkTypeUtilsTest.java

Various fixes in migration tool
- Fixed duplicate imports
- Fixed most of `recipeSpec.expectedCyclesThatMakeChanges(2)` in unit tests. All recipes are supposed to stabilize after 1 cycle.
- Added ChangeType for `AwsClientBuilder`, `AwsSyncClientBuilder` and `AwsAsyncClientBuilder`
- Fixed an issue in `ChangeSdkType` where client builder return type was still referencing to v1 class
- Fixed method identifier to make it have the same type as the method type
Updated tests

Various fixes in migration tool

---

v2-migration/pom.xml
v2-migration/src/main/java/software/amazon/awssdk/v2migration/ChangeSdkType.java
v2-migration/src/main/java/software/amazon/awssdk/v2migration/internal/utils/SdkTypeUtils.java
v2-migration/src/test/java/software/amazon/awssdk/v2migration/internal/utils/SdkTypeUtilsTest.java

Updating list of packages and classes to skip transforming since there are no v2 equivalents

Migration Tool: update list of packages to skip

---

.brazil.json
bom/pom.xml
core/eventstream/pom.xml
core/eventstream/src/main/java/software/amazon/awssdk/eventstream/Checksums.java
core/eventstream/src/main/java/software/amazon/awssdk/eventstream/Header.java
core/eventstream/src/main/java/software/amazon/awssdk/eventstream/HeaderType.java
core/eventstream/src/main/java/software/amazon/awssdk/eventstream/HeaderValue.java
core/eventstream/src/main/java/software/amazon/awssdk/eventstream/Message.java
core/eventstream/src/main/java/software/amazon/awssdk/eventstream/MessageBuilder.java
core/eventstream/src/main/java/software/amazon/awssdk/eventstream/MessageDecoder.java
core/eventstream/src/main/java/software/amazon/awssdk/eventstream/Prelude.java
core/eventstream/src/main/java/software/amazon/awssdk/eventstream/Utils.java
core/eventstream/src/test/java/software/amazon/awssdk/eventstream/HeaderTest.java
core/eventstream/src/test/java/software/amazon/awssdk/eventstream/MessageDecoderTest.java
core/eventstream/src/test/java/software/amazon/awssdk/eventstream/MessageTest.java
core/eventstream/src/test/java/software/amazon/awssdk/eventstream/PreludeTest.java
core/eventstream/src/test/java/software/amazon/awssdk/eventstream/TestUtils.java
core/eventstream/src/test/java/software/amazon/awssdk/eventstream/ToStringTest.java
core/pom.xml
pom.xml
test/tests-coverage-reporting/pom.xml

Import from https://github.com/awslabs/aws-eventstream-java/commit/1e76ef478f0108b38e2d7b70b598b4e5f0def3d1
`aws-eventstream-java` was meant as a reference implementation; this is a source import of this library so that we can customize it for our needs, e.g. changing or removing built-in validations.
Note this is the source for the same Maven version that we're currently depending on (`1.0.1`): https://github.com/aws/aws-sdk-java-v2/blob/56d82d003e53bd63428e598181971a0567cf673c/pom.xml#L107
Direct source import other than
- Fixing checkstyle violations
- Adding `@SdkProtectedApi` annotation to all classes.
- There are existing tests from the source repo, they are passing.

Import evenstream library

---

test/codegen-generated-classes-test/src/test/java/software/amazon/awssdk/services/compiledendpointrules/endpoints/internal/RuleUrlTest.java

A follow up to #5911 to add some other tests cases suggested in the comments.

Add some missing test cases

---

.changes/next-release/feature-AWSSDKforJavav2-54bedb6.json
core/sdk-core/src/main/java/software/amazon/awssdk/core/util/DefaultSdkAutoConstructList.java
core/sdk-core/src/main/java/software/amazon/awssdk/core/util/DefaultSdkAutoConstructMap.java
core/sdk-core/src/test/java/software/amazon/awssdk/core/util/DefaultSdkAutoConstructListTest.java
core/sdk-core/src/test/java/software/amazon/awssdk/core/util/DefaultSdkAutoConstructMapTest.java

Made DefaultSdkAutoConstructList and DefaultSdkAutoConstructMap serializable to ensure proper serialization of AttributeValue.
https://github.com/aws/aws-sdk-java-v2/issues/3143
Made DefaultSdkAutoConstructList and DefaultSdkAutoConstructMap serializable: added Serializable interface and implemented the readResolve() method to return the singleton INSTANCE.
ReadResolve() for Singleton: https://www.baeldung.com/java-serialization-readobject-vs-readresolve#use-of-readresolve
Added unit tests for serialization/deserialization

Made DefaultSdkAutoConstructList and DefaultSdkAutoConstructMap serializable

---

services/cloudwatchevents/src/main/resources/codegen-resources/customization.config
services/cloudwatchlogs/src/main/resources/codegen-resources/customization.config
services/eventbridge/src/main/resources/codegen-resources/customization.config
services/firehose/src/main/resources/codegen-resources/customization.config
services/kinesis/src/main/resources/codegen-resources/customization.config
services/kms/src/main/resources/codegen-resources/customization.config
services/swf/src/main/resources/codegen-resources/customization.config

Enable fast unmarshaller last wave. In this wave there are new 9 services onboarded.

Enable fast unmarshaller wave six and last

---

.brazil.json

Fix .brazil.json file mapping

---

buildspecs/release-javadoc.yml
buildspecs/release-to-maven.yml

Create a variable for modules to skip in release-javadoc yml and release-to-maven yml file to make it easier to maintain and less error prone.

Create a variable for modules to skip

---

.github/workflows/codeql.yml

Add CodeQL CI. The file is the default template provided by GH.

Add CodeQL CI

---

.all-contributorsrc
README.md

Add jencymaryjoseph as a contributor for code

docs: add jencymaryjoseph as a contributor for code

---

.github/workflows/new-module-verification.yml

Exclude service modules from new module verification

Exclude service modules from new module verification

---

.github/workflows/s3-regression-tests.yml

Hide Cloudwatch logs for s3 regression tests

Hide Cloudwatch logs for s3 regression tests

---

pom.xml

Bump CRT version to ~~0.38.8~~ 0.38.9 for https://github.com/awslabs/aws-c-http/issues/413#issuecomment-3137373980

Bump CRT version to 0.38.9
